const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const arbitrationLawProfessions = [
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "ADR Arbitration Lawyer", // Renamed to avoid uniqueness collision with Civil Law
        description: "A specialized legal advocate who exclusively represents clients outside of traditional courts. They argue cases in private, binding arbitration tribunals to resolve complex corporate or commercial disputes far faster than the public judicial system.",
        educationPath: "LLB",
        additionalQualification: "Deep procedural understanding of the Arbitration and Conciliation Act.",
        competitiveExams: ["State Law Entrances / CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Arbitration Pleading", "Cross-Examination in Tribunals", "Award Enforcement Litigation", "High-Volume Case Management"],
        salaryRange: "India: ₹6 LPA - ₹25 LPA | Global: $80,000 - $180,000 per year",
        roadmap: ["Arbitration Associate", "Independent Tribunal Advocate", "Partner - Dispute Resolution", "Designated Arbitrator"],
        courtPracticeOpportunities: "Litigates in High Courts primarily only to enforce or challenge final arbitration awards.",
        corporateOpportunities: "Hired heavily by engineering and infrastructure companies to fight daily contractual disputes.",
        lawFirmOpportunities: "A massive, expanding department in almost every modern corporate law firm.",
        workNature: "Private Tribunal Advocacy, Evidence Compilation & Award Execution.",
        futureScope: "Extremely secure. As public courts become increasingly backlogged (taking decades for a verdict), practically every commercial contract now mandates private arbitration for rapid dispute resolution.",
        jobDemandTrend: "High Volume / Expanding Rapidly",
        summary: "The private-sector litigators arguing complex contractual battles in highly efficient, closed-door arbitration tribunals rather than backlogged public courts."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Commercial Arbitration Specialist",
        description: "The absolute experts in resolving massive business-to-business (B2B) conflicts. They handle multi-million dollar disputes regarding fractured joint ventures, broken supply chains, and complex shareholder battles.",
        educationPath: "LLB -> LLM in Corporate/Commercial Law",
        additionalQualification: "Strong understanding of corporate accounting and valuation.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Commercial Damages Calculation", "Breach of Contract Analysis", "Shareholder Dispute Strategy", "Interim Relief Seeking"],
        salaryRange: "India: ₹8 LPA - ₹35 LPA | Global: $100,000 - $250,000 per year",
        roadmap: ["Commercial Litigator", "Senior Arbitration Counsel", "Head of Dispute Resolution", "Empanelled Tribunal Arbitrator"],
        courtPracticeOpportunities: "Approaching National Company Law Tribunals (NCLT) or High Courts for interim freezing orders.",
        corporateOpportunities: "Hired by massive retail and manufacturing giants to aggressively settle vendor disputes.",
        lawFirmOpportunities: "The bedrock of Tier-1 and Tier-2 commercial litigation boutiques.",
        workNature: "High-Stakes Commercial Argumentation, Financial Evidence Sifting & Corporate Chess.",
        futureScope: "Highly lucrative. When millions of dollars are locked up in a fractured corporate partnership, specialized commercial arbitrators are essential to extract that capital rapidly.",
        jobDemandTrend: "High Corporate Demand",
        summary: "The heavy-hitting commercial advocates fighting to rapidly resolve massively expensive, highly complex business-to-business contractual failures."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Global Arbitration Lawyer",
        description: "The global elite of dispute resolution. They fly around the world arguing multi-billion dollar cross-border disputes between massive multi-national corporations before prestigious tribunals like the LCIA (London) or SIAC (Singapore).",
        educationPath: "LLB -> LLM in International Dispute Resolution",
        additionalQualification: "Fluency in 'Conflict of Laws' (Private International Law) and multi-nodal jurisdictions.",
        competitiveExams: ["Global LLM Fellowships"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["CIArb (Chartered Institute of Arbitrators) Fellowship"],
        skills: ["Cross-Border Enforcement", "New York Convention Mastery", "Bilateral Investment Treaties (BITs)", "Global Diplomacy"],
        salaryRange: "India: ₹15 LPA - ₹50+ LPA | Global: $150,000 - $350,000+ per year",
        roadmap: ["International Associate", "Senior Global Counsel", "Partner - International Disputes", "Global Tribunal President"],
        courtPracticeOpportunities: "Arguing in foreign jurisdictions to enforce multi-million dollar international awards against rogue corporations.",
        corporateOpportunities: "Hired by multi-nationals (like Amazon or Reliance) for their most critical global disputes.",
        lawFirmOpportunities: "The absolute highest billing department in global Tier-1 'Magic Circle' law firms.",
        workNature: "Trans-National Arbitration, Elite Drafting & High-Level Corporate Diplomacy.",
        futureScope: "Extremely elite and fiercely competitive. Globalized commerce guarantees multi-jurisdictional disputes; lawyers who can navigate tribunals in London, Singapore, and New York simultaneously command phenomenal wealth.",
        jobDemandTrend: "Hyper-Elite / Cutthroat",
        summary: "The jet-setting global advocates arguing the absolute largest corporate disputes in the world before highly prestigious international tribunals."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Dispute Resolution Lawyer",
        description: "A versatile legal strategist who determines the absolute best path to solve a client's problem. They assess whether a corporate conflict should be litigated brutally in public court, or quietly arbitrated behind closed doors.",
        educationPath: "LLB",
        additionalQualification: "Deep psychological understanding of opposing counsel strategy.",
        competitiveExams: ["State Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Cost-Benefit Litigation Analysis", "Pre-Trial Leverage Generation", "Aggressive Settlement Negotiation", "Strategic Bluffing"],
        salaryRange: "India: ₹6 LPA - ₹25 LPA | Global: $80,000 - $180,000 per year",
        roadmap: ["Dispute Associate", "Senior Strategist", "Partner - Dispute Resolution", "General Counsel"],
        courtPracticeOpportunities: "Fluidly transitions between public courtrooms, private tribunals, and boardrooms.",
        corporateOpportunities: "The primary point of contact for an in-house corporate legal team facing a lawsuit.",
        lawFirmOpportunities: "The standard 'Litigation/Disputes' partner in any mid-to-large firm.",
        workNature: "Strategic Roadmapping, Multi-forum Argumentation & Elite Settlement.",
        futureScope: "Highly stable. Corporations don't just want to 'fight'—they want their problem solved in the cheapest, most effective way possible. This lawyer acts as the strategic architect of that solution.",
        jobDemandTrend: "High and Constant",
        summary: "The master legal strategists determining exactly when it is profitable to go to war in public courts, and when it is smarter to settle quietly in private tribunals."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Mediation Specialist",
        description: "A strictly neutral facilitator who does not judge or impose decisions. They sit between two warring parties (often in highly emotional IP or family business disputes) and psychologically guide them to construct their own mutually beneficial settlement.",
        educationPath: "LLB -> Specialized Mediation Training",
        additionalQualification: "Exceptional emotional intelligence, active listening, and de-escalation psychology.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Certified Mediator from recognized institutions (e.g., SIMC, MCPC)"],
        skills: ["Impartial Facilitation", "Psychological De-escalation", "Deadlock Breaking", "Creative Deal Structuring"],
        salaryRange: "India: ₹5 LPA - ₹20 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Junior Mediator", "Senior Conciliator", "Empanelled High Court Mediator", "Elite Independent Mediator"],
        courtPracticeOpportunities: "Legally mandated to attempt mediation before many civil trials proceed.",
        corporateOpportunities: "Hired internally for highly sensitive executive/founder disputes to prevent them from destroying a startup.",
        lawFirmOpportunities: "Leading specialized 'ADR Boutiques'.",
        workNature: "Intense Psychological Navigation, Guided Communication & Crafting Compromise.",
        futureScope: "Rapidly expanding. Governments are actively passing laws (like the Mediation Act) forcing belligerent parties to attempt mediation to decongest courts, radically spiking the demand for trained specialists.",
        jobDemandTrend: "High Growth / State Mandated",
        summary: "The deeply empathetic, neutral facilitators who psychologically guide furiously defensive parties into rationally signing mutually beneficial peace treaties."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Corporate Dispute Resolution Advisor",
        description: "In-house strategic risk managers. They actively monitor thousands of ongoing corporate contracts and immediately intervene when a vendor or partner relationship starts breaking down, fixing it before it ever escalates to a lawsuit.",
        educationPath: "LLB -> MBA / In-house experience",
        additionalQualification: "Deep understanding of the corporation's specific operational supply chain.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Corporate Governance Diplomas"],
        skills: ["Early Warning Detection", "Business Disruption Minimization", "Vendor De-escalation", "Internal Auditing"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $180,000 per year",
        roadmap: ["In-House Counsel", "Senior Dispute Risk Manager", "Director of Dispute Strategy", "Chief Legal Officer"],
        courtPracticeOpportunities: "Zero. Their entire job is to ensure the company never has to go to court.",
        corporateOpportunities: "The absolute backbone of risk management in massive conglomerates facing thousands of daily vendor friction points.",
        lawFirmOpportunities: "None. Strictly an internal 'General Counsel' track role.",
        workNature: "Internal Operational Auditing, Vendor Renegotiation & Strategic Risk Elimination.",
        futureScope: "Highly secure. Preventing a multi-million dollar arbitration saves a corporation millions in legal fees; lawyers who can fix disputes internally before they explode are highly valued executives.",
        jobDemandTrend: "High within Corporate Sectors",
        summary: "The internal corporate peacekeepers, detecting and neutralizing highly complex supply-chain and contractual friction before they detonate into massive lawsuits."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Arbitration Tribunal Legal Consultant",
        description: "The intellectual backbone of a private arbitration tribunal. Functioning like a highly advanced 'judicial clerk' for elite arbitrators, they research the incredibly dense evidence and draft the final, binding 'Arbitral Award'.",
        educationPath: "LLB -> LLM in Arbitration Law",
        additionalQualification: "Exceptional mastery of complex commercial evidence synthesis and flawless drafting.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Tribunal Secretary Certifications"],
        skills: ["Award Drafting", "Complex Evidence Marshalling", "Procedural Logistics", "Precedent Synthesis"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $75,000 - $140,000 per year",
        roadmap: ["Tribunal Secretary", "Registrar of Arbitral Institution", "Independent Arbitrator", "Global Tribunal President"],
        courtPracticeOpportunities: "None. They operate entirely behind the scenes of private tribunals.",
        corporateOpportunities: "Hired heavily by institutional arbitration centers (like MCIA, DIAC, ICC).",
        lawFirmOpportunities: "Often act as an intermediary step before re-joining a Tier-1 firm as a senior associate.",
        workNature: "Intense Evidence Review, Logistical Management & Authoring Binding Judgments.",
        futureScope: "A highly prestigious gateway. Serving as a tribunal secretary for a world-renowned arbitrator provides unparalleled mentorship and access to the absolute highest tier of the global legal elite.",
        jobDemandTrend: "Niche/Prestigious",
        summary: "The brilliant intellectual ghostwriters and logistical managers operating behind the scenes, drafting the multi-million dollar judgments issued by elite private arbitrators."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Construction Dispute Lawyer",
        description: "Operates in one of the most volatile, hyper-technical sectors of arbitration. They litigate massive multi-million dollar claims over delayed highways, collapsed bridges, and architectural failures using highly complex engineering evidence.",
        educationPath: "B.Tech (Civil) / Architecture -> LLB (Highly Prized Route)",
        additionalQualification: "Ability to instantly comprehend massive engineering blueprints and 'Critical Path' delay analysis.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["FIDIC Dispute Adjudication Board (DAB) Certifications"],
        skills: ["Delay Analysis Litigation", "Liquidated Damages Calculation", "Engineering Cross-Examination", "Massive Data Marshalling"],
        salaryRange: "India: ₹10 LPA - ₹35 LPA | Global: $120,000 - $250,000 per year",
        roadmap: ["Construction Litigator", "Senior Claims Specialist", "Partner - Infrastructure Disputes", "International DAB Member"],
        courtPracticeOpportunities: "Litigating in High Courts to freeze massive bank guarantees called during construction failures.",
        corporateOpportunities: "Guaranteed employment by massive infrastructure developers (L&T, Bechtel).",
        lawFirmOpportunities: "An incredibly lucrative, fiercely specialized 'Projects & Infra' department in Tier-1 firms.",
        workNature: "Technical Evidence Marshalling, Expert Witness Deposition & Complex Mathematical Litigation.",
        futureScope: "Extremely elite. Mega-infrastructure projects are notoriously delayed, triggering cascades of massive financial penalties. Specialized lawyers who understand both the law and the concrete are incredibly rare and highly paid.",
        jobDemandTrend: "Highly Specialized / Elite Volume",
        summary: "The hyper-specialized attorney-engineers who battle over catastrophic delays and massive financial penalties occurring during the construction of billion-dollar infrastructure projects."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Investment Arbitration Lawyer",
        description: "The absolute pinnacle of political law. They represent either massive corporations suing entire sovereign nations for expropriation (e.g., Vodafone suing India, or an oil company suing Venezuela), or they defend the nation-state against billions in corporate claims.",
        educationPath: "LLB -> LLM in Public International Law & Treaties",
        additionalQualification: "Deep geopolitical understanding and macroeconomic fluency.",
        competitiveExams: ["Global Fellowships"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Investor-State Dispute Settlement (ISDS) Training"],
        skills: ["Bilateral Investment Treaties (BITs)", "Sovereign Immunity Defense", "Expropriation Valuation", "Geopolitical Strategy"],
        salaryRange: "India: ₹15 LPA - ₹50+ LPA | Global: $160,000 - $400,000+ per year",
        roadmap: ["ISDS Associate", "Senior Global Strategist", "State Defense Counsel", "ICSID Arbitrator"],
        courtPracticeOpportunities: "Litigating primarily before the World Bank's ICSID (International Centre for Settlement of Investment Disputes).",
        corporateOpportunities: "Hired by multi-nationals whose massive foreign factories were suddenly nationalized by a host government.",
        lawFirmOpportunities: "The highest, most fiercely guarded echelon of 'Global Disputes' in international law firms.",
        workNature: "Trans-national Litigation, Geopolitical Negotiation & Mega-Damages Argumentation.",
        futureScope: "A tiny, astronomically rich niche. When a corporation sues a country for changing its tax laws (costing billions), the lawyers managing the tribunal practically operate as global diplomats.",
        jobDemandTrend: "Extremely Niche but Hyper-Elite",
        summary: "The elite geopolitical litigators managing the explosive multi-billion dollar tribunals where massive multi-national corporations sue entire sovereign nations."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Alternative Dispute Resolution (ADR) Specialist",
        description: "An incredibly fluid conflict-resolution expert who masters 'hybrid' approaches. They might start a dispute using mediation, seamlessly transition to 'Conciliation', and finally switch to binding 'Arbitration' to legally mandate the settlement.",
        educationPath: "LLB",
        additionalQualification: "Profound versatility across multiple conflict-resolution architectures.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Comprehensive ADR Diplomas"],
        skills: ["Med-Arb (Mediation followed by Arbitration)", "Conciliation", "Rapid Settlement Generation", "Client Psychology"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $80,000 - $160,000 per year",
        roadmap: ["ADR Practitioner", "Senior ADR Counsel", "Boutique Owner", "Empanelled High Court Conciliator"],
        courtPracticeOpportunities: "Diverts massive volumes of cases permanently away from the public court system.",
        corporateOpportunities: "Highly valued by massive consumer-facing companies (like ecommerce or telecom) to rapidly settle thousands of bulk consumer grievances outside of court.",
        lawFirmOpportunities: "Standard roles resolving mid-tier corporate fractures rapidly.",
        workNature: "Fluid Dispute Navigation, Rapid Psychological Dealmaking & Contract Drafting.",
        futureScope: "Highly functional. ADR Specialists save corporations millions in long-term court fees by utilizing a massive toolkit of psychological and legal frameworks to end disputes quickly.",
        jobDemandTrend: "High and Scalable",
        summary: "The versatile conflict-architects utilizing a massive toolkit of mediation, conciliation, and arbitration to rapidly extinguish disputes before they drain the client's finances."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Arbitration Case Analyst",
        description: "The data-heavy vanguard of a massive arbitration trial. They dig through hundreds of thousands of corporate emails, financial ledgers, and WhatsApp messages to unearth the 'smoking gun' required to win a billion-dollar commercial dispute.",
        educationPath: "LLB",
        additionalQualification: "Mastery of 'e-Discovery' software and high tolerance for complex financial data.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["e-Discovery/Data Forensics Certifications (Optional but valued)"],
        skills: ["Massive Data Marshalling", "Timeline Synthesis", "Financial Discrepancy Spotting", "Litigation Support"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $65,000 - $120,000 per year",
        roadmap: ["Discovery Analyst", "Senior Case Strategist", "Litigation Support Manager", "Partner - Evidence Strategy"],
        courtPracticeOpportunities: "Minimal courtroom speaking; their work is the foundation the senior advocate argues upon.",
        corporateOpportunities: "Crucial for internal corporate investigations before a massive arbitration begins.",
        lawFirmOpportunities: "The absolute backbone of the evidence-gathering phase in Tier-1 corporate litigation firms.",
        workNature: "Intense Data Mining, Evidence Architecting & Strategic Timeline Construction.",
        futureScope: "Critical. Modern commercial arbitration is won entirely on granular digital evidence; analysts who can synthesize millions of disorganized emails into a lethal legal weapon are highly prized.",
        jobDemandTrend: "High Volume / Tech-Adjacent",
        summary: "The meticulous data-detectives who sift through mountains of digital corporate communications and financial ledgers to unearth the lethal evidence that wins multi-million dollar arbitrations."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Arbitration Law Researcher",
        description: "The intellectual engine room of Dispute Resolution. They actively track how different global tribunals (Singapore, London, Paris) are currently interpreting complex commercial laws, providing the exact international precedents necessary for a lawyer to win their case.",
        educationPath: "LLB -> LLM in Arbitration Theory",
        additionalQualification: "Deep passion for comparative international jurisprudence.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Comparative Jurisprudence Synthesis", "Treaty Interpretation", "Academic Drafting", "Global Precedent Tracking"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $100,000 per year",
        roadmap: ["Research Associate", "Senior Arbitration Fellow", "Think-Tank Strategist", "Global Tribunal Secretary"],
        courtPracticeOpportunities: "Drafting the most complex legal briefs for senior advocates to present in High Courts regarding the enforcement of foreign arbitration awards.",
        corporateOpportunities: "Providing high-level macro-strategy to corporations constructing massive new joint-ventures.",
        lawFirmOpportunities: "The dedicated 'Knowledge Management' or Research department of elite firms.",
        workNature: "Intense Global Research, Academic Briefing & Precedent Mining.",
        futureScope: "Extremely stable. International Arbitration is an incredibly fluid, ever-changing field where a ruling in London heavily impacts a case in Mumbai; tracking this requires dedicated, brilliant researchers.",
        jobDemandTrend: "Stable within Elite Firms/Academia",
        summary: "The intellectual researchers actively monitoring the ever-shifting judgments of global tribunals, providing the lethal international precedents required to win massive corporate battles."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Arbitration & ADR Professor",
        description: "Educates the next generation of lawyers on why bypassing the public court system is heavily advantageous. They demystify the complex web of domestic arbitration, international treatises, and the psychological art of mediation.",
        educationPath: "LLB -> LLM -> Ph.D. in Dispute Resolution",
        additionalQualification: "Extensive publishing on global arbitration anomalies and enforcement issues.",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Procedural Demystification", "Doctrinal Analysis", "Pedagogy", "Academic Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean or International Arbitrator"],
        courtPracticeOpportunities: "Frequently hired by massive corporations or even states to act as 'Expert Witnesses' explaining complex international arbitration theories during a tribunal.",
        corporateOpportunities: "Running high-level 'Negotiation Masterclasses' for corporate C-suite executives.",
        lawFirmOpportunities: "Zero.",
        workNature: "Teaching, Mentoring, and Publishing Elite Dispute Resolution Theory.",
        futureScope: "Highly prestigious. As ADR rapidly becomes the mandatory default mechanism for all commercial disputes globally, professors capable of effectively teaching these complex mechanisms are highly sought after by top universities.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic authorities training future lawyers and corporate executives in the highly complex, psychological, and procedural art of resolving disputes outside the courtroom."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Negotiation & Conflict Resolution Consultant",
        description: "Highly elite hired guns brought in specifically when a multi-million dollar corporate negotiation has completely broken down. They utilize intense game theory, behavioral economics, and psychological leverage to fundamentally reset the negotiation table.",
        educationPath: "LLB -> Masters in Behavioral Economics / Negotiation (e.g., Harvard PON)",
        additionalQualification: "Elite emotional intelligence, charismatic dominance, and game-theory fluency.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["High-Level Executive Negotiation Certificates"],
        skills: ["Game Theory", "Hostile De-escalation", "BATNA Optimization", "Executive Persuasion"],
        salaryRange: "India: ₹10 LPA - ₹30+ LPA | Global: $120,000 - $250,000+ per year",
        roadmap: ["Negotiation Consultant", "Senior Strategy Advisor", "Boutique Firm Partner", "Global Conflict Expert"],
        courtPracticeOpportunities: "Zero. They operate purely in high-stakes corporate boardrooms.",
        corporateOpportunities: "Hired internally by Private Equity firms or massive conglomerates specifically to run complex, aggressive corporate buyouts or settle massive founder disputes.",
        lawFirmOpportunities: "Operating as an elite 'Of Counsel' strategy consultant for Tier-1 firms during massive M&A deadlocks.",
        workNature: "High-Stress Psychological Boardroom Battles, Game Theory Application & Deal Closing.",
        futureScope: "Astoundingly lucrative. When an ego-driven founder dispute threatens to destroy a multi-billion dollar IPO, an elite negotiator who can break the deadlock is worth their weight in gold.",
        jobDemandTrend: "Boutique / High-Level Consulting",
        summary: "The elite corporate 'fixers' who utilize advanced game theory and psychological dominance to aggressively break deadlocks in multi-million dollar corporate negotiations."
    },
    {
        domain: "Law",
        branch: "Arbitration & Dispute Resolution",
        title: "Certified Legal Mediator", // Renamed to ensure database uniqueness from Civil Law
        description: "Empanelled directly by the State or High Courts. When public courts are hopelessly overwhelmed with low-to-mid tier civil disputes, they mandate these certified mediators to rapidly force thousands of fighting parties into rapid, localized settlements.",
        educationPath: "LLB",
        additionalQualification: "Extensive localized networking and high stamina for arguing parties.",
        competitiveExams: ["Judicial/Mediation Empanelment Exams (Varies by state)"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["State Supreme/High Court Mediation Board Certification"],
        skills: ["High-Volume Dispute Rapid-Fire", "Vernacular Conciliation", "Court-Annexed Logistics", "Empathetic Coercion"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $110,000 per year",
        roadmap: ["Court Annexed Mediator", "Senior Empanelled Conciliator", "Director of State Mediation Board", "Judiciary (Optional)"],
        courtPracticeOpportunities: "Operates physically within 'Mediation Centers' attached directly to almost every major District or High Court globally.",
        corporateOpportunities: "Minimal. This is primarily a public-justice system role.",
        lawFirmOpportunities: "Often a part-time role taken on by senior independent litigators giving back to the judicial system.",
        workNature: "Relentless Public Dispute Facilitation, Rapid Settlements & Decongesting Courts.",
        futureScope: "A highly respected public service. Without this army of state-certified mediators rapidly settling daily family, business, and property fights, the entire public court system would structurally collapse under the caseload.",
        jobDemandTrend: "High Volume / Geographically Required",
        summary: "The relentless state-certified peacekeepers physically attached to courts, rapidly resolving thousands of localized disputes to prevent the public judicial system from totally collapsing."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Arbitration & Dispute Resolution" });
        await Career.insertMany(arbitrationLawProfessions);
        console.log('Arbitration & Dispute Resolution Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
