const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const publicAdminProfessions = [
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Civil Servant (IAS / Administrative Officer)",
        description: "Manage public administration and policy implementation across various government departments and ministries on a large scale.",
        summary: "Top-level government administrators executing public policy and managing civil departments.",
        skills: ["Strategic Planning", "Public Policy", "Leadership", "Crisis Management", "Legal Understanding"],
        salaryRange: "India: ₹8L - ₹30L+ | Global: $60K - $150K+",
        educationPath: "B.A. Public Administration / Political Science → Civil Services Exam",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Central Government", "State Government", "Ministries"],
        futureScope: "Extremely stable and prestigious with unmatched authority in policy making.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "Maximum. This is purely a government sector career.",
        freelanceOpportunities: "None. Requires absolute dedication to the state.",
        fieldWork: "High. Frequent travel, public meetings, and district tours.",
        riskLevel: "Moderate (High responsibility, political pressure)",
        certifications: ["Civil Services Examination Clearance"],
        internshipRequirements: "Probationary Training at specialized government institutes (e.g., LBSNAA).",
        roadmap: ["UPSC / Civil Services Exam", "Assistant Collector", "District Magistrate", "Secretary to the Government"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Public Policy Analyst",
        description: "Research, analyze, and evaluate the effects of existing and proposed government policies, laws, and social initiatives.",
        summary: "Researchers evaluating and shaping government policies to solve societal issues.",
        skills: ["Data Analysis", "Research", "Critical Thinking", "Policy Evaluation", "Report Writing"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $120K",
        educationPath: "B.A. Public Administration / Economics → M.A. Public Policy",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Think Tanks", "Government Agencies", "NGOs", "Consulting Firms"],
        futureScope: "Growing steadily as data-driven governance and policy reforms are prioritized globally.",
        jobDemandTrend: "Stable, Growing",
        governmentJobs: "High. Roles in planning commissions and advisory boards.",
        freelanceOpportunities: "Moderate. Policy consultants for various organizations.",
        fieldWork: "Low. Primarily office-based research.",
        riskLevel: "Low",
        certifications: ["Data Analytics Certifications"],
        internshipRequirements: "Internships with policy institutes or government legislative offices.",
        roadmap: ["Policy Research Assistant", "Policy Analyst", "Senior Analyst", "Director of Policy/Advisory Board Member"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "City Manager",
        description: "Oversee the day-to-day operations of a city or municipality, managing budgets, personnel, and local public services.",
        summary: "The executive managers overseeing municipal governments and city operations.",
        skills: ["Urban Governance", "Budgeting", "Public Relations", "Project Management", "Personnel Management"],
        salaryRange: "India: ₹6L - ₹20L | Global: $80K - $150K",
        educationPath: "B.A. Public Administration → Masters in Public Administration (MPA)",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Municipal Corporations", "City Councils", "Local Government Bodies"],
        futureScope: "Crucial role as cities expand and require professional management of complex urban infrastructure.",
        jobDemandTrend: "Steady",
        governmentJobs: "Maximum. Entirely based in local government.",
        freelanceOpportunities: "Low. Salaried government or contractual position.",
        fieldWork: "Moderate. Overseeing city infrastructure projects.",
        riskLevel: "Low to Moderate (Public scrutiny)",
        certifications: ["Certified Public Manager (CPM)"],
        internshipRequirements: "Municipal or local government internships.",
        roadmap: ["City Department Head", "Assistant City Manager", "City Manager", "Regional Administrator"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Foreign Service Officer (Diplomat)",
        description: "Represent the country's interests internationally, manage diplomatic relations, negotiate treaties, and assist citizens abroad.",
        summary: "Government representatives managing international diplomacy and foreign relations.",
        skills: ["Diplomacy", "Foreign Languages", "International Law", "Negotiation", "Cultural Sensitivity"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $70K - $160K+",
        educationPath: "B.A. Political Science / International Relations → Civil/Foreign Service Exams",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Ministry of External/Foreign Affairs", "Embassies", "Consulates"],
        futureScope: "Extremely prestigious. Essential for navigating complex global geopolitics and trade.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "Maximum. Direct government service.",
        freelanceOpportunities: "None.",
        fieldWork: "High. Frequent international postings and relocations.",
        riskLevel: "Moderate (Depends on global postings)",
        certifications: ["Foreign Service Examination"],
        internshipRequirements: "Language training and diplomatic probation.",
        roadmap: ["Foreign Service Exam", "Third Secretary", "Consul / First Secretary", "Ambassador / High Commissioner"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Urban / Regional Planner",
        description: "Develop plans and programs for land use, designing communities, and accommodating population growth in cities and counties.",
        summary: "Planners designing the sustainable development and infrastructure of cities and regions.",
        skills: ["Spatial Planning", "GIS Software", "Environmental Regulations", "Zoning Laws", "Analytical Thinking"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $110K",
        educationPath: "B.Plan / B.A. Geography → Masters in Urban Planning",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Government Planning Authorities", "Real Estate Developers", "Consulting Firms"],
        futureScope: "High demand due to rapid urbanization, climate change adaptation, and smart city initiatives.",
        jobDemandTrend: "Growing",
        governmentJobs: "High. Employed by city and state planning departments.",
        freelanceOpportunities: "Moderate. Urban planning consultants.",
        fieldWork: "Moderate. Site visits and public zoning hearings.",
        riskLevel: "Low",
        certifications: ["AICP Certification (Global) / Institute of Town Planners (India)"],
        internshipRequirements: "Internships with city planning departments or architectural firms.",
        roadmap: ["Junior Planner", "Urban Planner", "Senior Regional Planner", "Director of City Planning"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Public Health Administrator",
        description: "Plan, direct, and coordinate medical and health services on a community or national scale, driving public health policies.",
        summary: "Administrators managing public health programs, clinics, and national health initiatives.",
        skills: ["Healthcare Management", "Epidemiology Basics", "Budget Management", "Program Development", "Regulatory Compliance"],
        salaryRange: "India: ₹6L - ₹20L | Global: $70K - $130K",
        educationPath: "B.A. Public Administration / B.Sc. → Master of Public Health (MPH)",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Government Health Departments", "Hospitals", "NGOs (WHO, Red Cross)"],
        futureScope: "Critical field, drastically expanding following global health awareness and pandemic preparedness.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High. State health departments and national health missions.",
        freelanceOpportunities: "Low. Mostly institutional roles.",
        fieldWork: "Moderate. Community health program oversight.",
        riskLevel: "Low to Moderate",
        certifications: ["Public Health Certifications"],
        internshipRequirements: "Internships at public clinics or health NGOs.",
        roadmap: ["Health Program Coordinator", "Public Health Administrator", "Health Department Director", "Secretary of Health"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Emergency Management Director",
        description: "Prepare plans and procedures for responding to natural disasters or other emergencies, coordinating first responders and government resources.",
        summary: "Leaders coordinating the public response to disasters and emergencies.",
        skills: ["Crisis Management", "Logistics", "Interagency Coordination", "Calm Under Pressure", "Risk Assessment"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $115K",
        educationPath: "B.A. Public Administration → Certificate in Disaster Management",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Disaster Management Authorities (NDMA/FEMA)", "State Governments", "Large Corporations"],
        futureScope: "Increasing relevance due to climate change and the rising frequency of natural disasters.",
        jobDemandTrend: "Growing",
        governmentJobs: "Maximum. Mostly state and federal disaster agencies.",
        freelanceOpportunities: "Low. Risk management consultants for major corporations.",
        fieldWork: "High. On-site coordination during emergencies.",
        riskLevel: "High (High-stress, working in disaster zones)",
        certifications: ["Certified Emergency Manager (CEM)"],
        internshipRequirements: "Training with fire, police, or civil defense units.",
        roadmap: ["Emergency Response Specialist", "Operations Manager", "Emergency Management Director", "Head of National Disaster Agency"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Human Resources Director (Public Sector)",
        description: "Manage the recruitment, training, labor relations, and employee welfare for large government departments and public agencies.",
        summary: "HR experts specializing in the hiring and management of government employees.",
        skills: ["Labor Laws", "Public Sector Compliance", "Recruitment Strategy", "Conflict Resolution", "Benefits Administration"],
        salaryRange: "India: ₹6L - ₹22L | Global: $70K - $130K",
        educationPath: "B.A. Public Administration / HR → MBA (HR) or MPA",
        yearsOfStudy: "5 Years",
        industriesHiring: ["All Government Departments", "Public Sector Undertakings (PSUs)", "Municipalities"],
        futureScope: "Stable. Managing the civil service workforce is a continuous, permanent requirement.",
        jobDemandTrend: "Stable",
        governmentJobs: "Maximum. Working internally for government agencies.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Office-based.",
        riskLevel: "Low",
        certifications: ["SHRM or HRCI Certifications"],
        internshipRequirements: "HR internships within public or large corporate sectors.",
        roadmap: ["HR Specialist", "Labor Relations Manager", "Public Sector HR Director", "Chief Human Capital Officer"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Budget Analyst (Government)",
        description: "Examine budget estimates, evaluate funding requests, and ensure government funds are allocated efficiently and legally.",
        summary: "Financial specialists managing and auditing government department budgets.",
        skills: ["Financial Analysis", "Accounting Principles", "Forecasting", "Attention to Detail", "Public Finance Law"],
        salaryRange: "India: ₹5L - ₹15L | Global: $65K - $105K",
        educationPath: "B.A. Public Administration / Economics / Finance",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Ministry of Finance", "State Treasuries", "Municipal Financial Departments"],
        futureScope: "Critical for the transparent functioning of the government; demand remains constant.",
        jobDemandTrend: "Stable",
        governmentJobs: "Maximum. Direct finance department roles.",
        freelanceOpportunities: "Low. Strictly confidential internal roles.",
        fieldWork: "Low. Office-based.",
        riskLevel: "Low",
        certifications: ["Certified Government Financial Manager (CGFM)"],
        internshipRequirements: "Accounting or public finance internships.",
        roadmap: ["Junior Budget Analyst", "Senior Financial Analyst", "Budget Director", "Chief Financial Officer (Agency)"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Public Affairs Specialist",
        description: "Manage communication between government agencies and the public, handling press releases, media inquiries, and public awareness campaigns.",
        summary: "The communication bridge between government entities and the citizens they serve.",
        skills: ["Public Relations", "Crisis Communication", "Media Management", "Writing/Editing", "Diplomacy"],
        salaryRange: "India: ₹5L - ₹16L | Global: $60K - $110K",
        educationPath: "B.A. Public Administration / Mass Communication / PR",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Government Ministries", "Military Branches (Public Affairs)", "Public Sector PR Departments"],
        futureScope: "Growing as governments increasingly recognize the need to manage their public image on digital platforms.",
        jobDemandTrend: "Steady Growth",
        governmentJobs: "High. Press information bureaus and departmental spokespeople.",
        freelanceOpportunities: "Moderate. Consulting on political or public campaigns.",
        fieldWork: "Moderate. Attending press conferences and state events.",
        riskLevel: "Low (High stress during PR crises)",
        certifications: ["Public Relations Certificates"],
        internshipRequirements: "Internships with political campaigns or government PR desks.",
        roadmap: ["PR Assistant", "Public Affairs Specialist", "Press Secretary", "Director of Communications"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Economic Development Director",
        description: "Promote economic growth within a city or region by attracting businesses, securing grants, and developing infrastructure strategies.",
        summary: "Administrators focused on increasing a region's wealth, job market, and business investments.",
        skills: ["Economic Forecasting", "Business Negotiation", "Urban Planning", "Marketing", "Grant Writing"],
        salaryRange: "India: ₹7L - ₹25L | Global: $80K - $140K",
        educationPath: "B.A. Economics / Public Administration → MPA / MBA",
        yearsOfStudy: "5 Years",
        industriesHiring: ["State Economic Boards", "Chambers of Commerce", "City Development Authorities"],
        futureScope: "Highly valued role as local governments actively compete for tech hubs and corporate headquarters.",
        jobDemandTrend: "Growing",
        governmentJobs: "High. Working for state or local economic development commissions.",
        freelanceOpportunities: "Low.",
        fieldWork: "Moderate. Meeting with corporate investors and touring industrial sites.",
        riskLevel: "Low",
        certifications: ["Certified Economic Developer (CEcD)"],
        internshipRequirements: "Internships with chambers of commerce or trade boards.",
        roadmap: ["Development Analyst", "Economic Development Manager", "Regional Director", "Secretary of Commerce"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Customs and Immigration Officer",
        description: "Enforce customs, immigration, and border security laws, inspecting cargo and verifying passenger credentials at ports of entry.",
        summary: "Government officers safeguarding national borders and regulating international trade and travel.",
        skills: ["Law Enforcement Basics", "Observation Skills", "Legal Compliance", "Interrogation Techniques", "Integrity"],
        salaryRange: "India: ₹5L - ₹15L | Global: $55K - $100K",
        educationPath: "B.A. Public Administration / Any Degree → SSC/Customs Exam",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Border Security Agencies", "Customs Departments", "Airports & Seaports"],
        futureScope: "Permanent requirement for national security and economic regulation.",
        jobDemandTrend: "Stable",
        governmentJobs: "Maximum. Exclusive to federal/central enforcement agencies.",
        freelanceOpportunities: "None.",
        fieldWork: "Maximum. Working directly at borders, airports, and shipping docks.",
        riskLevel: "Moderate to High (Security and smuggling threats)",
        certifications: ["Law Enforcement Training Clearance"],
        internshipRequirements: "Probationary training at customs academies.",
        roadmap: ["Customs Inspector", "Superintendent of Customs", "Assistant Commissioner", "Chief Commissioner"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Non-Profit / NGO Director",
        description: "Manage the operations, fundraising, and policy execution of non-governmental organizations dedicated to social causes.",
        summary: "Executive leaders managing charitable organizations and driving social impact initiatives.",
        skills: ["Fundraising", "Program Management", "Advocacy", "Budgeting", "Public Speaking"],
        salaryRange: "India: ₹6L - ₹25L | Global: $70K - $140K",
        educationPath: "B.A. Public Administration / Social Work → Masters in Non-Profit Management / MSW",
        yearsOfStudy: "5 Years",
        industriesHiring: ["International NGOs (UNICEF, WWF)", "Local Charities", "Foundations"],
        futureScope: "Crucial for addressing social gaps that governments and markets fail to cover.",
        jobDemandTrend: "Growing",
        governmentJobs: "Often collaborate with, but remain independent from, the government.",
        freelanceOpportunities: "Moderate. Board advisory roles or consulting.",
        fieldWork: "Moderate. Depending on the NGO's focus (e.g., environmental or humanitarian).",
        riskLevel: "Low (Financial stability of the NGO can be a risk)",
        certifications: ["Non-Profit Leadership Certificates"],
        internshipRequirements: "Extensive volunteering and internships with established NGOs.",
        roadmap: ["Program Coordinator", "Program Manager", "Director of Operations", "Executive Director"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Public Sector Campaign Manager",
        description: "Plan, coordinate, and execute all operations of a political campaign, including fundraising, polling, advertising, and voter turnout.",
        summary: "Master strategists directing the election campaigns of politicians.",
        skills: ["Political Strategy", "Data Polling", "Fundraising", "Public Relations", "High-Stamps Management"],
        salaryRange: "India: ₹5L - ₹30L+ | Global: $60K - $200K+",
        educationPath: "B.A. Political Science / Public Administration",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Political Parties", "Political Action Committees (PACs)", "Political Consulting Firms"],
        futureScope: "Extremely lucrative but highly volatile. Successful managers become powerful behind-the-scenes figures.",
        jobDemandTrend: "Cyclical (Peaks during elections)",
        governmentJobs: "Often transition into Chief of Staff roles after a successful campaign.",
        freelanceOpportunities: "Maximum. Usually hired as independent consultants per campaign.",
        fieldWork: "High. Constant travel across voting districts.",
        riskLevel: "Moderate (High career volatility based on win/loss records)",
        certifications: ["None specific."],
        internshipRequirements: "Volunteering on local campaigns, canvassing.",
        roadmap: ["Field Organizer", "Communications Director", "Deputy Campaign Manager", "Public Sector Campaign Manager / Senior Strategist"]
    },
    {
        domain: "Arts",
        branch: "Public Administration",
        title: "Community Service Manager",
        description: "Coordinate and supervise social service programs and community organizations, overseeing staff and assessing the effectiveness of social initiatives.",
        summary: "Administrators managing local social programs to support community well-being.",
        skills: ["Social Work Principles", "Program Evaluation", "Grant Writing", "Empathy", "Resource Allocation"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $90K",
        educationPath: "B.A. Social Work / Public Administration → Master of Social Work (MSW) or MPA",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Local Government Social Services", "Community Centers", "Shelters", "Non-Profits"],
        futureScope: "Steady demand to address local social issues, mental health, and community development.",
        jobDemandTrend: "Stable Growth",
        governmentJobs: "High. roles in departments of human/social services.",
        freelanceOpportunities: "Low. Heavily institution-based.",
        fieldWork: "Moderate. Visiting community centers and meeting with local leaders.",
        riskLevel: "Low",
        certifications: ["Licensed Clinical Social Worker (LCSW) - if dealing with therapy"],
        internshipRequirements: "Fieldwork with social service agencies.",
        roadmap: ["Social Worker", "Program Coordinator", "Community Service Manager", "Director of Social Services"]
    }
];

const seedPublicAdmin = async () => {
    try {
        await Career.deleteMany({ branch: "Public Administration" });
        await Career.insertMany(publicAdminProfessions);
        console.log('Public Administration Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedPublicAdmin();
