const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');
const Branch = require('./models/Branch');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const historyProfessions = [
    {
        domain: "Arts",
        branch: "History",
        title: "Historian",
        description: "Study and research past events, human societies, and cultures by analyzing primary sources, documents, and historical artifacts to write books, papers, or educational materials.",
        summary: "The primary researchers who interpret past human events to guide our understanding of the present.",
        skills: ["Historical Research", "Archival Analysis", "Critical Thinking", "Writing & Publishing", "Foreign Languages (often)"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $90K",
        educationPath: "B.A. History → M.A. History → Ph.D. in History",
        yearsOfStudy: "5 to 8+ Years",
        industriesHiring: ["Academia & Universities", "Government Archives", "Museums", "Publishing"],
        futureScope: "Steady demand. Expanding into digital humanities creating vast databases of historical texts.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Opportunities in National Archives, State Historical Departments, and Civil Services.",
        fieldWork: "Low to Moderate. Mostly library, archive, and museum-based research.",
        certifications: ["Digital Humanities Certifications"],
        roadmap: ["B.A. History", "Master's & Specialization", "Conduct original Ph.D. research", "Publishing & Professorship"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Archaeologist",
        description: "Examine ancient ruins, artifacts, and structures uncovered through excavation to understand prehistoric and historic human life and cultural evolution.",
        summary: "Field researchers unearthing physical artifacts to reconstruct ancient civilizations.",
        skills: ["Excavation Techniques", "Artifact Analysis", "GIS & Mapping", "Radiocarbon Dating Knowledge", "Physical Endurance"],
        salaryRange: "India: ₹4L - ₹10L | Global: $45K - $85K",
        educationPath: "B.A./B.Sc. Archaeology → M.A./M.Sc. Archaeology",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Archaeological Survey Depts", "Heritage Consultancies", "Museums", "Universities"],
        futureScope: "Essential for protecting historical sites during modern urban development and infrastructure expansion.",
        jobDemandTrend: "Moderate, Project-Based",
        governmentJobs: "High. Primarily through Archaeological Survey of India (ASI) or equivalent national bodies.",
        fieldWork: "Very High. Requires weeks or months of physical excavation in remote or rugged locations under varying weather conditions.",
        certifications: ["GIS mapping certification", "Specialized Dating Techniques"],
        roadmap: ["Undergraduate degree focusing on human history", "Field schooling & digs", "Direct excavation projects", "Senior Archaeologist"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Archivist",
        description: "Appraise, catalog, and preserve historically significant documents, digital records, photographs, and audio recordings for public and institutional access.",
        summary: "The preservers of historical documents, protecting the primary sources of global history.",
        skills: ["Document Preservation", "Cataloging (MARC/DACS)", "Information Management", "Digital Archiving", "Attention to Detail"],
        salaryRange: "India: ₹3L - ₹9L | Global: $45K - $80K",
        educationPath: "B.A. History/Library Science → M.A. Archives & Records Management",
        yearsOfStudy: "5 Years",
        industriesHiring: ["National Archives", "Corporate Heritage Branches", "Libraries", "Universities"],
        futureScope: "Growing strongly in the 'Digital Archivist' sector as institutions digitize centuries of physical records.",
        jobDemandTrend: "Steady Growth",
        governmentJobs: "High. Central and State level archives consistently require official archivists.",
        fieldWork: "Low. Primarily based in climate-controlled repositories and libraries.",
        certifications: ["Certified Archivist (CA)", "Digital Preservation Certificates"],
        roadmap: ["Library/History degree", "Master's in Archival Science", "Manage institutional records", "Head Archivist"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Museum Curator",
        description: "Acquire, preserve, and display historical collections. They design exhibitions, write educational materials, and manage the administrative operations of a museum.",
        summary: "The creative minds designing historical exhibitions and managing priceless museum collections.",
        skills: ["Exhibition Design", "Cataloging", "Grant Writing", "Public Speaking", "Subject Matter Expertise"],
        salaryRange: "India: ₹5L - ₹15L | Global: $55K - $100K",
        educationPath: "B.A. History/Art History → M.A. Museology/Museum Studies",
        yearsOfStudy: "5 to 7 Years",
        industriesHiring: ["Public & Private Museums", "Art Galleries", "Cultural Foundations"],
        futureScope: "High impact. Curators are increasingly focusing on interactive, digital, and virtual reality museum experiences.",
        jobDemandTrend: "Competitive",
        governmentJobs: "Moderate to High. National and State museums offer prestigious positions.",
        fieldWork: "Low. Mostly indoor work, though occasional travel for artifact acquisition is required.",
        certifications: ["Certificate in Museum Studies"],
        roadmap: ["Museology degree", "Assistant Curator", "Design major exhibitions", "Chief Curator / Museum Director"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Heritage Manager",
        description: "Protect and promote historical sites, monuments, and properties. They balance conservation needs with public access, tourism, and commercial viability.",
        summary: "The managers protecting physical historical sites while promoting them to tourists and the public.",
        skills: ["Conservation Laws", "Tourism Management", "Budgeting & Fundraising", "Public Relations", "Project Management"],
        salaryRange: "India: ₹6L - ₹14L | Global: $55K - $95K",
        educationPath: "B.A. History/Architecture → M.A. Heritage Management",
        yearsOfStudy: "5 Years",
        industriesHiring: ["National Trust Organizations", "Tourism Boards", "Conservation NGOs", "Local Government"],
        futureScope: "Rapid growth in 'heritage tourism' ensures a steady need for professionals to manage these economic driving sites.",
        jobDemandTrend: "Growing",
        governmentJobs: "High. Heritage conservation boards and ministry of culture/tourism.",
        fieldWork: "Moderate. Requires regular site visits and inspections of monuments.",
        certifications: ["Certified Heritage Professional"],
        roadmap: ["Heritage Management degree", "Manage local sites", "Direct regional conservation policies", "Director of Heritage NGO/Trust"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Art Historian",
        description: "Study the history and development of painting, sculpture, and other visual arts to understand their historical contexts, cultural significance, and aesthetic value.",
        summary: "Scholars analyzing the evolution of visual arts across different civilizations and eras.",
        skills: ["Visual Analysis", "Artistic Technique Knowledge", "Historical Contextualization", "Writing", "Authentication Basics"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $95K",
        educationPath: "B.A. Art History → M.A. Art History → Ph.D.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Major Art Museums", "Auction Houses (Sotheby's/Christie's)", "Publishing"],
        futureScope: "Stable within academia and luxury art markets; auction houses heavily rely on their expertise.",
        jobDemandTrend: "Niche, Highly Competitive",
        governmentJobs: "Low. Limited to national galleries or cultural ministries.",
        fieldWork: "Low. Museum and library-based, though international travel to view specific artworks is common.",
        certifications: ["Appraisal Studies (optional)"],
        roadmap: ["Art History degrees", "Research specific art movements", "Publish books/catalogs", "Senior Art Expert / Professor"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Cultural Historian",
        description: "Analyze the beliefs, customs, and popular culture (literature, music, daily life) of past societies rather than just political or military events.",
        summary: "Researchers studying how everyday people lived, thought, and expressed themselves in the past.",
        skills: ["Sociological Analysis", "Literary Analysis", "Cultural Anthropology basics", "Thematic Research", "Writing"],
        salaryRange: "India: ₹4L - ₹10L | Global: $50K - $85K",
        educationPath: "B.A. History/Sociology → M.A. Cultural Studies/History → Ph.D.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Academia", "Cultural Think Tanks", "Documentary Production", "Publishing"],
        futureScope: "Increasingly relevant as society seeks to understand the historical roots of modern cultural movements and identities.",
        jobDemandTrend: "Stable within Academia",
        governmentJobs: "Low. Mostly academic or media-related.",
        fieldWork: "Low. Primarily text and archive-based research.",
        certifications: ["None specific; advanced degrees preferred."],
        roadmap: ["Cultural Studies degrees", "Publish papers on specific cultural phenomena", "Write historical books", "Tenured Professor"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Political Historian",
        description: "Study the rise and fall of governments, political systems, foreign policies, and massive global conflicts to understand power dynamics.",
        summary: "Experts analyzing past political systems, wars, and leaders to understand the nature of global power.",
        skills: ["Political Science", "International Relations Knowledge", "Archival Document Analysis", "Debate & Rhetoric Analysis", "Macro-level Synthesis"],
        salaryRange: "India: ₹5L - ₹15L | Global: $55K - $100K",
        educationPath: "B.A. History/Political Science → M.A. History → Ph.D.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Political Think Tanks", "Government Intelligence/Advisory", "News Media"],
        futureScope: "Highly relevant. Governments and think tanks employ political historians to provide context for current geopolitical crises.",
        jobDemandTrend: "Steady",
        governmentJobs: "Moderate. Foreign policy advisory roles and civil services sometimes specifically recruit history backgrounds.",
        fieldWork: "Low. Heavily archive and diplomatic-library based.",
        certifications: ["International Relations Certificates (optional)"],
        roadmap: ["History/PoliSci degrees", "Research specific eras of conflict", "Advise policy makers / Write books", "Senior Political Analyst/Professor"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Research Historian",
        description: "Work outside of academia to provide historical research for corporations, legal firms (land rights, treaties), or private clients needing deep historical context.",
        summary: "Professional researchers hired by corporations or law firms to investigate specific historical data.",
        skills: ["Deep Archival Digging", "Legal Document Analysis", "Corporate History", "Genealogy basics", "Fast-paced Report Writing"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $90K",
        educationPath: "B.A. History → M.A. History / Public History",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Law Firms", "Corporate History Departments", "Private Research Agencies", "Film Studios"],
        futureScope: "Growing in the private sector as corporations realize the branding value of their own history, and law firms dig into historical land rights.",
        jobDemandTrend: "Growing (Private Sector)",
        governmentJobs: "Low. Primarily private sector consulting.",
        fieldWork: "Moderate. Requires traveling to various obscure local registries and archives.",
        certifications: ["Public History Certificate"],
        roadmap: ["Master's in History", "Freelance research or join an agency", "Specialize in corporate or legal history", "Lead Research Consultant"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "History Professor / Lecturer",
        description: "Teach history at the collegiate and university level, develop syllabi, and conduct independent historical research to publish academic books.",
        summary: "Academic leaders educating the next generation while publishing their own original historical research.",
        skills: ["Pedagogy (Teaching)", "Advanced Research", "Curriculum Design", "Grant Writing", "Public Speaking"],
        salaryRange: "India: ₹6L - ₹20L | Global: $60K - $120K",
        educationPath: "B.A. → M.A. → Ph.D. in History",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Universities", "Colleges", "Elite High Schools"],
        futureScope: "Highly prestigious and stable, providing the ultimate platform for independent thought and research.",
        jobDemandTrend: "Steady, Highly Competitive",
        governmentJobs: "Moderate. Government-funded state universities offer stable roles via state exams (e.g., NET/SLET in India).",
        fieldWork: "Low. Classroom and library focused.",
        certifications: ["National Eligibility Test (NET) for lectureship"],
        roadmap: ["Complete Ph.D.", "Publish dissertations", "Secure tenure-track teaching position", "Tenured Professor of History"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Historical Consultant (Film / Media)",
        description: "Ensure historical accuracy in movies, video games, documentaries, and novels regarding costumes, language, architecture, and societal norms of the depicted era.",
        summary: "The experts making sure movies and video games stay historically accurate.",
        skills: ["Era-Specific Knowledge", "Script Analysis", "Costume/Prop Contextualization", "Adaptability", "Media Production basics"],
        salaryRange: "India: ₹5L - ₹15L (Project based) | Global: $50K - $100K+ (Project based)",
        educationPath: "B.A./M.A. History",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Film Production Studios", "Video Game Developers (e.g., Ubisoft)", "Television Networks", "Authors"],
        futureScope: "High growth. With huge investments in historical epics and games (like Assassin's Creed), studios desperately need historical authenticity.",
        jobDemandTrend: "Growing rapidly in Entertainment",
        governmentJobs: "None. purely private sector entertainment.",
        fieldWork: "Moderate. Requires presence on film production sets to advise directors.",
        certifications: ["None; reputation and deep niche knowledge matter most."],
        roadmap: ["History degree", "Build a niche expertise (e.g., Medieval Europe or Ancient India)", "Consult on small media projects", "Lead Historical Advisor for major studios"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Genealogist",
        description: "Trace family lineages and personal histories using census data, birth records, and DNA databases to help people discover their ancestry.",
        summary: "Historical detectives tracing family trees and ancestral lineages for private clients.",
        skills: ["Census/Vital Record Analysis", "Genetic Genealogy (DNA basics)", "Patience", "Database Navigation", "Paleography (reading old handwriting)"],
        salaryRange: "India: ₹3L - ₹8L | Global: $40K - $85K",
        educationPath: "B.A. History (Optional, often self-taught or specialized courses)",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Private Clients (Freelance)", "Genealogy Companies (Ancestry.com)", "Historical Societies"],
        futureScope: "Booming interest globally via commercial DNA kits has made tracing family history a massive new industry.",
        jobDemandTrend: "High Growth (Freelance/Corporate)",
        governmentJobs: "Low. Mostly freelance or private companies.",
        fieldWork: "Moderate. Requires visiting local churches, registries, and graveyards for physical records.",
        certifications: ["Board Certified Genealogist (BCG)"],
        roadmap: ["Learn deep archival research", "Complete genealogy certifications", "Build client base or join a firm", "Expert Forensic Genealogist"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Epigraphist",
        description: "Decipher, translate, and analyze ancient inscriptions carved into stone, metal, or coins to uncover lost languages and historical dates.",
        summary: "Linguistic historians translating ancient symbols and carved inscriptions.",
        skills: ["Ancient Languages (Sanskrit, Latin, Greek, etc.)", "Linguistics", "Paleography", "Pattern Recognition", "Historical Contextualization"],
        salaryRange: "India: ₹4L - ₹10L | Global: $50K - $90K",
        educationPath: "B.A. History/Linguistics → M.A. Ancient History/Epigraphy → Ph.D.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Archaeological Departments", "Museums", "Universities", "Numismatic Societies"],
        futureScope: "A highly specialized academic niche vital for unlocking the secrets of pre-literate or newly discovered ancient cultures.",
        jobDemandTrend: "Highly Specialized, Niche",
        governmentJobs: "High. ASI and national cultural ministries employ epigraphists to catalog national heritage.",
        fieldWork: "Moderate to High. Requires visiting ancient temples, ruins, and excavation sites to read raw inscriptions.",
        certifications: ["Specialised Language Diplomas"],
        roadmap: ["Master ancient languages", "Study specific regional scripts", "Publish translations of undiscovered stones", "Chief Epigraphist"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Anthropologist (History background)",
        description: "Study the evolution of human societies, cultures, and biological development by comparing historical data with modern human behavior.",
        summary: "Scientists studying the complete evolution of human culture and physical traits over thousands of years.",
        skills: ["Ethnography", "Cultural Analysis", "Field Interviewing", "Evolutionary Biology Basics", "Data Collection"],
        salaryRange: "India: ₹5L - ₹12L | Global: $55K - $95K",
        educationPath: "B.A./B.Sc. Anthropology/History → M.A. Anthropology",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Universities", "NGOs", "International Development Agencies", "Corporate UX departments"],
        futureScope: "Increasingly hired by tech companies to understand human-computer interaction across different cultures based on historical norms.",
        jobDemandTrend: "Steady Growth",
        governmentJobs: "Moderate. Anthropological Survey organizations and tribal welfare ministries.",
        fieldWork: "Very High. Ethnographic research requires deeply embedding oneself in different cultures or societies for months.",
        certifications: ["None specific."],
        roadmap: ["Anthropology degrees", "Conduct extensive field studies", "Publish ethnographic reports", "Senior Anthropological Researcher"]
    },
    {
        domain: "Arts",
        branch: "History",
        title: "Conservation Specialist (Historical Monuments)",
        description: "Apply chemistry and material science to carefully restore and physically preserve decaying historical monuments, paintings, and fragile manuscripts.",
        summary: "The scientific restorers who chemically and physically repair decaying ancient artifacts and buildings.",
        skills: ["Material Science / Chemistry", "Restoration Techniques", "Patience & Precision", "Art History Context", "Structural Integrity Analysis"],
        salaryRange: "India: ₹5L - ₹14L | Global: $55K - $90K",
        educationPath: "B.Sc./B.A. Chemistry/Art History → M.A./M.Sc. Conservation Studies",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["National Heritage Bodies", "Large Museums", "Private Fine Art Restorers", "Architecture Firms"],
        futureScope: "Absolutely critical. As pollution and climate change accelerate the decay of global monuments, conservationists are in desperate need.",
        jobDemandTrend: "High Demand (Niche)",
        governmentJobs: "High. Employed directly by governments to maintain national monuments globally.",
        fieldWork: "High. Often working directly on-site at major monuments using scaffolding and precision tools.",
        certifications: ["Professional Conservator Accreditation"],
        roadmap: ["Chemistry/History background", "Master's in Conservation", "Apprentice under master restorers", "Lead Monument Conservator"]
    }
];

const seedHistory = async () => {
    try {
        await Career.deleteMany({ branch: "History" });
        await Career.insertMany(historyProfessions);
        console.log('History Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedHistory();
