const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const internationalLawProfessions = [
    {
        domain: "Law",
        branch: "International Law",
        title: "International Lawyer",
        description: "A generalized expert dealing with multi-jurisdictional legal disputes. They advise massive MNCs, governments, or NGOs on how to navigate the conflicting laws of different countries regarding trade, treaties, or human rights.",
        educationPath: "LLB -> LLM in International Business Law or Public International Law",
        competitiveExams: ["CLAT (PG)", "Global University Entrances (LNAT/LSAT)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Cross-Border Jurisprudence", "Conflict of Laws (Private International Law)", "Cultural Negotiation", "Treaty Analysis"],
        salaryRange: "India: ₹8 LPA - ₹30+ LPA | Global: $90,000 - $250,000+ per year",
        roadmap: ["International Associate", "Foreign Legal Consultant", "Partner - International Desk", "Head of Global Legal Strategy"],
        governmentJobs: "Hired by the Ministry of External Affairs (MEA) Legal Division.",
        internationalOrganizationsOpportunities: "Frequently consulted by regional bodies (EU, ASEAN, SAARC).",
        globalLawFirmOpportunities: "High demand in Tier-1 global law firms representing MNCs with multi-national footprints.",
        workNature: "Advisory, Cross-Border Litigation & Global Corporate Structuring.",
        travelRequirementLevel: "High",
        futureScope: "As long as globalization connects economies, attorneys who can reconcile the clashing laws of different sovereign nations will be indispensable.",
        jobDemandTrend: "Stable and Highly Lucrative",
        summary: "The ultimate global legal generalist, solving complex legal puzzles where the laws of two or more countries collide."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Human Rights Lawyer",
        description: "Defends absolute fundamental human liberties on a global scale. They prosecute war criminals, defend refugees, and force authoritarian regimes to comply with universal human rights declarations.",
        educationPath: "LLB -> LLM in Human Rights / International Humanitarian Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Humanitarian Law Diplomas (Geneva Academy)"],
        skills: ["Geneva Conventions", "Trauma Advocacy", "International Criminal Court (ICC) Procedures", "Lobbying"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $60,000 - $130,000 per year",
        roadmap: ["Human Rights Fellow", "NGO Field Counsel", "Senior International Advocate", "UN Special Rapporteur"],
        governmentJobs: "Advising national Human Rights Commissions on global treaty compliance.",
        internationalOrganizationsOpportunities: "Massive opportunities within the United Nations (UNHCR, OHCHR), Amnesty International, and Human Rights Watch.",
        globalLawFirmOpportunities: "Mostly pro-bono departments of massive Global Law Firms.",
        workNature: "High-Stakes International Litigation, Field Auditing & Global Lobbying.",
        travelRequirementLevel: "Extremely High (Often to conflict zones)",
        futureScope: "A highly noble and relentlessly necessary field due to ongoing global geopolitical conflicts, refugee crises, and systemic human rights abuses.",
        jobDemandTrend: "High (Institution/NGO Driven)",
        summary: "A global guardian of humanity, wielding international treaties to protect the vulnerable from state-sponsored atrocities."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "Diplomatic Legal Advisor",
        description: "Works directly within embassies or foreign ministries. They advise diplomats and ambassadors on the legalities of international treaties, sovereign immunity, and consular relations during volatile geopolitical negotiations.",
        educationPath: "LLB -> Civil Services (Diplomacy) / Specialized LLM",
        competitiveExams: ["UPSC (IFS) or Country-Specific Diplomatic Exams"],
        yearsOfStudy: "5 Years + Extensive Civil Service Training",
        certifications: ["Diplomatic Certifications"],
        skills: ["Vienna Convention on Diplomatic Relations", "Statecraft", "International Treaty Law", "High-Level Diplomacy"],
        salaryRange: "India: Governed by IFS Pay Scales | Global: $80,000 - $160,000+ per year",
        roadmap: ["Legal Attaché", "First Secretary (Legal)", "Chief Legal Advisor (MEA)", "Ambassador"],
        governmentJobs: "100% Core Government/Foreign Service Role.",
        internationalOrganizationsOpportunities: "Represents the nation's legal stance at the UN General Assembly.",
        globalLawFirmOpportunities: "Often poached by elite private firms for their unmatched geopolitical networks post-retirement.",
        workNature: "Statecraft, Treaty Drafting & Sovereign Advisory.",
        travelRequirementLevel: "Extremely High (Permanent foreign postings)",
        futureScope: "The absolute pinnacle of public international law representing the sovereign state worldwide. Highly prestigious and highly secure.",
        jobDemandTrend: "Extremely Elite/Restricted",
        summary: "The legal brains behind high-stakes international diplomacy, shielding ambassadors and drafting the treaties that bind countries together."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Trade Lawyer",
        description: "Specializes in the massively complex rules governing how products and capital move across global borders. They handle brutal trade wars, tariff disputes, anti-dumping claims, and massive World Trade Organization (WTO) arbitrations.",
        educationPath: "LLB -> LLM in International Trade Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Customs & Trade Law Diplomas"],
        skills: ["WTO Regulations", "Anti-Dumping Laws", "Customs Tariffs", "Macroeconomic Understanding"],
        salaryRange: "India: ₹8 LPA - ₹35 LPA | Global: $100,000 - $300,000+ per year",
        roadmap: ["Trade Law Associate", "Customs Specialist", "Partner - International Trade", "WTO Appellate Body Member"],
        governmentJobs: "Advising the Ministry of Commerce & Industry during FTA (Free Trade Agreement) negotiations.",
        internationalOrganizationsOpportunities: "Direct employment at the WTO, World Bank, or IMF.",
        globalLawFirmOpportunities: "Extremely high demand in elite firm departments managing multi-billion dollar MNC supply chains.",
        workNature: "Trade Tribunal Arbitration, Tariff Structuring & Government Negotiations.",
        travelRequirementLevel: "High",
        futureScope: "Extremely lucrative. As nations increasingly use tariffs and trade bans as geopolitical weapons, elite trade lawyers are needed to defend corporate revenues.",
        jobDemandTrend: "Very High Demand",
        summary: "The commercial warriors of the globalized economy, utilizing WTO law to fight multi-billion dollar tariff wars."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Arbitration Lawyer",
        description: "Represents mega-corporations or sovereign states in private global tribunals rather than domestic courts. They handle hyper-complex disputes over massive infrastructure contracts or breached multinational treaties.",
        educationPath: "LLB -> LLM in Alternative Dispute Resolution (ADR)",
        competitiveExams: ["Global Certifications (MCIArb / FCIArb)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Chartered Institute of Arbitrators (CIArb)"],
        skills: ["UNCITRAL Model Law", "Cross-lingual Argumentation", "Treaty Parsing", "Massive Evidence Handling"],
        salaryRange: "India: ₹12 LPA - ₹60+ LPA | Global: $150,000 - $500,000+ per year",
        roadmap: ["Arbitration Junior", "International Litigator", "Partner - Global Disputes", "Appointed International Arbitrator"],
        governmentJobs: "Representing the State in Bilateral Investment Treaty (BIT) Arbitrations.",
        internationalOrganizationsOpportunities: "Arbitrating at SIAC (Singapore), LCIA (London), or ICC (Paris).",
        globalLawFirmOpportunities: "The absolute highest paying role in global Tier-1 dispute resolution departments.",
        workNature: "High-Stakes Private Tribunal Litigation & Sovereign Disputing.",
        travelRequirementLevel: "High (Arbitrations are held in global hubs like Singapore, Paris, London)",
        futureScope: "MNCs uniformly reject domestic courts for enforcing contracts, making international arbitration the undisputed king of cross-border corporate justice.",
        jobDemandTrend: "Elite / Hyper-Lucrative",
        summary: "Elite corporate litigators operating outside the public court system to resolve the world's largest commercial and sovereign battles."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "Maritime Law Specialist",
        description: "The 'lawyers of the sea'. They govern everything that happens on international waters, dealing with massive shipping logistics, piracy, oceanic pollution, ship arrest warrants, and international port disputes.",
        educationPath: "LLB -> LLM in Admiralty/Maritime Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Maritime Law Certifications (Swansea University/IMO)"],
        skills: ["UNCLOS (Law of the Sea)", "Admiralty Court Procedures", "Marine Insurance (P&I)", "Logistics Law"],
        salaryRange: "India: ₹7 LPA - ₹30 LPA | Global: $90,000 - $220,000 per year",
        roadmap: ["Maritime Associate", "Shipping Counsel", "Partner - Admiralty Law", "Maritime Arbitrator"],
        governmentJobs: "Advising Port Authorities, Coast Guard, or Navy regarding territorial waters.",
        internationalOrganizationsOpportunities: "Roles within the International Maritime Organization (IMO).",
        globalLawFirmOpportunities: "Extremely high demand in boutique admiralty firms and massive logistics corporations (Maersk).",
        workNature: "Specialized Litigation (Ship Arrests), Insurance Claims & Port Negotiation.",
        travelRequirementLevel: "Moderate (Mostly concentrated in massive port cities)",
        futureScope: "90% of global trade travels by sea. The legal complexities of massive cargo ships, oceanic environmental laws, and piracy guarantee permanent demand.",
        jobDemandTrend: "Highly Specialized Niche",
        summary: "The ultimate specialists of admiralty law, controlling the legal architecture of the multi-trillion dollar global shipping industry."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Criminal Lawyer",
        description: "The prosecutors and defenders of the world's worst individuals at the International Criminal Court (ICC) in The Hague. They handle cases of genocide, crimes against humanity, and massive war crimes.",
        educationPath: "LLB -> LLM in International Criminal Law",
        competitiveExams: ["Global specialized entrances"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory, but European/UN internships are practically required"],
        skills: ["Rome Statute Mastery", "Evidentiary Complexity", "Trauma Integration", "Flawless Multilingual Advocacy"],
        salaryRange: "India: N/A (Practiced Abroad) | Global: $80,000 - $180,000 per year",
        roadmap: ["Tribunal Clerk", "Assistant Prosecutor / Defense Counsel", "Lead Trial Counsel (ICC)", "ICC Judge"],
        governmentJobs: "Occasional state-appointed defense at the Hague.",
        internationalOrganizationsOpportunities: "100% focused on the ICC, ICJ, or special UN tribunals.",
        globalLawFirmOpportunities: "Virtually zero; this is a purely institutional and academic arena.",
        workNature: "Highest-Stakes Global Tribunal Litigation.",
        travelRequirementLevel: "High (Requires living in/traveling to The Hague periodically)",
        futureScope: "Extremely difficult to enter but represents the absolute pinnacle of criminal law, prosecuting heads of state and architects of genocide.",
        jobDemandTrend: "Hyper-Niche / Highly Elite",
        summary: "The courtroom titans fighting at the apex of human justice, prosecuting or defending global leaders for crimes against humanity."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "Treaty Negotiation Lawyer",
        description: "Specialized diplomatic lawyers who physically sit in the room during massive bilateral or multilateral summits, drafting the exact, unbreakable wording of global climate treaties, nuclear arms pacts, or massive trade deals.",
        educationPath: "LLB -> Masters in Public International Law / International Relations",
        competitiveExams: ["UPSC / Civil Services for Government Roles"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Treaty Law Diplomas"],
        skills: ["Precise Loophole-free Drafting", "Geopolitical Awareness", "Linguistics", "High-Stress Negotiation"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA (+ Perks) | Global: $90,000 - $170,000 per year",
        roadmap: ["Junior Legal Aide", "Treaty Draftsman", "Lead Negotiator", "Ambassador / Chief Legal Counsel"],
        governmentJobs: "The backbone of the Legal and Treaties Division of the Foreign Ministry.",
        internationalOrganizationsOpportunities: "Drafting treaties for the UN, WHO, or Climate Summits (COP).",
        globalLawFirmOpportunities: "Rare, though occasionally brought in as private consultants by developing nations.",
        workNature: "Intense Global Negotiations & Ultra-Precise Legal Drafting.",
        travelRequirementLevel: "Extremely High",
        futureScope: "Essential for global survival. From AI regulation to climate change, international treaties are the only mechanism to force global cooperation.",
        jobDemandTrend: "Institutional Requirement",
        summary: "The silent architects of global history, drafting the words that legally bind nations to peace, trade, or climate goals."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Legal Consultant",
        description: "Freelance or boutique firm experts who advise smaller law firms, corporations, or even developing nations on ultra-specific international legal niches (like space law, cybersecurity across borders, or foreign direct investment nuances).",
        educationPath: "LLB -> Specialized LLM / Ph.D.",
        competitiveExams: ["None"],
        yearsOfStudy: "6 to 8 Years",
        certifications: ["Foreign Bar Enrollments (Optional)"],
        skills: ["Niche Subject Expertise", "Comparative Law", "Networking", "Strategic Advising"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $100,000 - $200,000+ per year",
        roadmap: ["Subject Expert", "Boutique Consultant", "Of Counsel to Tier-1 Firms", "Global Policy Advisor"],
        governmentJobs: "Consultant for specific ministries dealing with niche international issues.",
        internationalOrganizationsOpportunities: "Hired on contract by the UN or World Bank for specific missions.",
        globalLawFirmOpportunities: "Hired on massive retainers when Tier-1 firms encounter an obscure international law issue outside their expertise.",
        workNature: "Deep Research, Advisory Strategy & Expert Testimony.",
        travelRequirementLevel: "Moderate to High",
        futureScope: "As law fragments into highly complex global niches (crypto, space, cyber), generalized firms will increasingly rely on these hyper-specialized global consultants.",
        jobDemandTrend: "Growing Niche Market",
        summary: "The mercenary experts of the legal world, hired to solve the most obscure, complex cross-border legal dilemmas."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Law Researcher",
        description: "Attached to the International Court of Justice (ICJ), elite universities, or global think tanks. They dig through customary international law, centuries of global treaties, and state practice to support landmark global judgments.",
        educationPath: "LLB -> LLM in Public International Law",
        competitiveExams: ["Global Fellowships / ICJ Judicial Fellowship Programme"],
        yearsOfStudy: "5 to 7 Years",
        certifications: ["None mandatory"],
        skills: ["Customary International Law", "Multilingual Research", "Academic Writing", "Synthesis"],
        salaryRange: "India: ₹5 LPA - ₹12 LPA | Global: $60,000 - $110,000 per year",
        roadmap: ["Judicial Fellow", "Senior Research Scholar", "Think-Tank Director", "Global Academic"],
        governmentJobs: "Research wings of the Foreign Ministry.",
        internationalOrganizationsOpportunities: "Highly coveted clerkships/fellowships at the ICJ in The Hague.",
        globalLawFirmOpportunities: "Hired by massive international arbitration practices for foundational research.",
        workNature: "Elite Legal Research, Archival Digging & Academic Drafting.",
        travelRequirementLevel: "Low to Moderate",
        futureScope: "A vital path into global academia or high-level international arbitration. Unearthing state practices can win international border/water disputes.",
        jobDemandTrend: "Stable within Elite Academia",
        summary: "The academic scholars unearthing the unwritten customary laws of the world to win massive sovereign disputes at the ICJ."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "Global Policy Legal Analyst",
        description: "Monitors the constant shifts in global law—such as changing US sanctions, new EU data laws, or changing global tax regimes—and translates these massive geopolitical shifts into actionable legal strategies for multinational corporations.",
        educationPath: "LLB / Masters in International Relations",
        competitiveExams: ["None"],
        yearsOfStudy: "4 to 5 Years",
        certifications: ["Public Policy Certifications"],
        skills: ["Geopolitical Forecasting", "Sanctions Law", "Policy Demystification", "Corporate Strategy"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $80,000 - $150,000 per year",
        roadmap: ["Policy Analyst", "Senior Global Strategist", "Director of Global Risk", "VP of Geopolitical Strategy"],
        governmentJobs: "Advising trade ministries on the impact of foreign legislation.",
        internationalOrganizationsOpportunities: "Roles in global economic forums like the WEF.",
        globalLawFirmOpportunities: "Massive demand in the strategy divisions of 'Big Law' and 'Big 4' consulting firms.",
        workNature: "Desk Research, Geopolitical Forecasting & Corporate Briefing.",
        travelRequirementLevel: "Low",
        futureScope: "Incredibly relevant. With global sanctions and trade regulations changing daily, corporations pay a premium for analysts who can predict legal weather.",
        jobDemandTrend: "Growing Rapidly",
        summary: "A pure geopolitical strategist who predicts how changes in global law will impact the bottom line of massive multinational corporations."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Law Professor",
        description: "The intellectual backbone of global law. They instruct aspiring diplomats and global lawyers at elite universities regarding the UN Charter, WTO law, and international jurisprudence while acting as visiting scholars globally.",
        educationPath: "LLB -> LLM -> Ph.D. in International Law",
        competitiveExams: ["UGC NET / Global Ph.D. Entrances"],
        yearsOfStudy: "8 to 10 Years",
        certifications: ["UGC NET (India)"],
        skills: ["Advanced Pedagogy", "Treatise Authoring", "Global Networking", "Debate & Theory Formulation"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $80,000 - $180,000+ per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean / Global Visiting Scholar"],
        governmentJobs: "Permanent faculty at National Law Universities.",
        internationalOrganizationsOpportunities: "Often invited to lecture at the Hague Academy of International Law.",
        globalLawFirmOpportunities: "Frequently hired as expert witnesses in complex international arbitrations to testify on customary international law.",
        workNature: "Teaching, Mentoring, Academic Publishing & Expert Testimony.",
        travelRequirementLevel: "Moderate (Visiting professorships globally)",
        futureScope: "Extremely prestigious. The top professors are the very architects of international legal theory, actively cited by the ICJ during landmark rulings.",
        jobDemandTrend: "High for elite Ph.D. Holders",
        summary: "The academic guardians of international law, teaching future diplomats and advising international tribunals on complex global jurisprudence."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "United Nations Legal Officer",
        description: "The core legal bureaucrats of the United Nations. They handle the massive internal legalities of the UN—ranging from drafting peacekeeping mandates to managing the employment contracts and diplomatic immunity of UN staff globally.",
        educationPath: "LLB -> LLM",
        competitiveExams: ["UN Young Professionals Programme (YPP)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Multilingualism (French/Spanish highly valued)"],
        skills: ["UN Charter Mastery", "Administrative Law", "Diplomatic Immunity", "Bureaucratic Navigation"],
        salaryRange: "India: N/A | Global: $70,000 - $150,000+ (Tax-Free UN Salary)",
        roadmap: ["Associate Legal Officer (P-2)", "Legal Officer (P-3/P-4)", "Senior Legal Officer (P-5)", "Under-Secretary-General for Legal Affairs"],
        governmentJobs: "N/A (Employees of the UN system, serving international interests).",
        internationalOrganizationsOpportunities: "100% focused on UN Secretariat and specialized UN agencies.",
        globalLawFirmOpportunities: "N/A",
        workNature: "Institutional Advisory, Contract Drafting & UN Policy Implementation.",
        travelRequirementLevel: "Moderate to High (Depending on agency posting)",
        futureScope: "Extremely secure, highly prestigious, and tax-free jobs. You are the legal foundation keeping the world's largest international organization functioning.",
        jobDemandTrend: "Hyper-Competitive",
        summary: "The bureaucratic lawyers who manage the legal scaffolding of the United Nations, ensuring global peace missions and agencies operate legally."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "International Organization Legal Advisor",
        description: "Operates outside the UN, working for massive global entities like the World Bank, IMF, WHO, or Interpol. They ensure the organization's policies comply with member-state laws and manage international lending or health regulation agreements.",
        educationPath: "LLB -> LLM in Global Finance/Health Law",
        competitiveExams: ["Organization-specific recruitments"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Domain-specific certificates (Finance/Health)"],
        skills: ["Institutional Law", "Global Finance/Health Regulations", "Treaty Parsing", "Diplomacy"],
        salaryRange: "India: N/A | Global: $80,000 - $160,000+ per year",
        roadmap: ["Legal Consultant", "Legal Advisor", "Senior Counsel", "General Counsel of the Organization"],
        governmentJobs: "N/A (Employees of independent international organizations).",
        internationalOrganizationsOpportunities: "100% focused on entities like the IMF, WHO, WIPO, or World Bank.",
        globalLawFirmOpportunities: "Extremely lucrative transitions into private practice post-tenure as consultants.",
        workNature: "High-Level Institutional Advisory & Policy Structuring.",
        travelRequirementLevel: "Moderate",
        futureScope: "Highly prestigious and well-compensated. These lawyers dictate how global finance is distributed and how global health mandates are enforced.",
        jobDemandTrend: "Elite/Competitive",
        summary: "The legal architects driving massive global institutions, ensuring international loans, health guidelines, and intellectual property treaties function seamlessly."
    },
    {
        domain: "Law",
        branch: "International Law",
        title: "Cross-Border Dispute Resolution Lawyer",
        description: "A hybrid litigator tackling disputes that don't fit perfectly into arbitration. They hunt down hidden assets across multiple countries, navigate international extradition, and enforce foreign court judgments in domestic courts.",
        educationPath: "LLB -> LLM in Private International Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollments in multiple jurisdictions (Ideal)"],
        skills: ["Conflict of Laws", "Foreign Judgment Enforcement", "Asset Tracing", "Extradition Law"],
        salaryRange: "India: ₹10 LPA - ₹40+ LPA | Global: $120,000 - $350,000+ per year",
        roadmap: ["Disputes Associate", "Cross-Border Strategist", "Partner - Global Disputes", "International Counsel"],
        governmentJobs: "Consulted by ED or CBI for massive international asset-recovery operations (e.g., fugitive economic offenders).",
        internationalOrganizationsOpportunities: "Collaborations with Interpol.",
        globalLawFirmOpportunities: "The bedrock of Tier-1 firm global disputes practices.",
        workNature: "Intense Multi-Jurisdictional Litigation & Global Asset Hunting.",
        travelRequirementLevel: "High",
        futureScope: "Extremely lucrative. As white-collar criminals and defaulting corporations hide money in complex offshore tax havens, lawyers who can crack foreign legal barriers are incredibly valuable.",
        jobDemandTrend: "Very High Demand",
        summary: "A high-stakes global litigator chasing fugitive assets and enforcing judgments across the chaotic web of international borders."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "International Law" });
        await Career.insertMany(internationalLawProfessions);
        console.log('International Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
