const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const homeopathyProfessions = [
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Classical Homeopathic Physician",
        description: "Primary care homeopathic doctors who prescribe extensively 'individualized' constitutional remedies based on a patient's exact physical, emotional, and psychological totality of symptoms.",
        summary: "General holistic doctors treating acute and chronic illnesses with individualized micro-dose remedies.",
        skills: ["Case Taking (Detailed Psychological Profiling)", "Materia Medica Mastery", "Repertorization", "Patient Empathy and Listening", "Holistic Diagnosis"],
        salaryRange: "India: ₹3L - ₹12L | Global: $50K - $100K",
        educationPath: "BHMS (Bachelor of Homeopathic Medicine and Surgery) → MD in Homeopathy (Materia Medica / Organon)",
        yearsOfStudy: "5.5 to 8.5 Years",
        industriesHiring: ["Private Clinics", "Holistic Wellness Centers", "Government Dispensaries (AYUSH)"],
        futureScope: "Steady demand. A growing global population seeks non-toxic, alternative medicines for chronic conditions where conventional medicine focuses primarily on symptom management.",
        jobDemandTrend: "Stable, High Niche",
        governmentJobs: "Maximum. Roles in national state-sponsored alternative medicine ministries (like India's AYUSH).",
        freelanceOpportunities: "Maximum. Over 70% of homeopaths operate independent private clinical practices.",
        fieldWork: "Low. Entirely clinic based.",
        riskLevel: "Low",
        certifications: ["State-/National Homeopathic Medical Council Registration"],
        internshipRequirements: "One year mandatory clinical rotatory internship.",
        roadmap: ["Junior Doctor", "Consultant Homeopath", "Senior Physician", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Pediatrician",
        description: "Focus purely on treating infants and children. Homeopathy is extremely popular in pediatrics because the sweet pills are easily accepted by children, and parents prefer to avoid heavy antibiotics.",
        summary: "Specialists treating childhood diseases (like recurrent colds, asthma, tonsillitis) with child-friendly remedies.",
        skills: ["Child Psychology", "Gentle Therapeutics", "Identifying Non-Verbal Symptoms", "Parental Counseling", "Pediatric Materia Medica"],
        salaryRange: "India: ₹4L - ₹15L | Global: $60K - $110K",
        educationPath: "BHMS → MD in Homeopathic Pediatrics",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Homeopathic Children's Clinics", "Multi-Specialty Alternative Hospitals", "Self-Employment"],
        futureScope: "High Growth. Parents globally are heavily driving the demand for non-invasive, natural remedies for their children's recurrent immunity and allergy issues.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate. AYUSH pediatric wards.",
        freelanceOpportunities: "Maximum. Setting up a dedicated pediatric homeopathic clinic is highly lucrative.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["MD (Pediatrics) Homeopathy Registration"],
        internshipRequirements: "Extensive residency in pediatric wards.",
        roadmap: ["Resident Doctor", "Consultant Pediatrician", "Clinic Director"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Dermatologist",
        description: "Specialize in treating chronic, severe skin conditions—such as extreme eczema, psoriasis, vitiligo, and acne—using deep-acting constitutional homeopathic remedies instead of topical steroid creams.",
        summary: "Specialists treating stubborn, recurring skin and hair diseases internally without steroids.",
        skills: ["Visual Skin Diagnostics", "Miasmatic prescribing (Chronic disease theory)", "Patient Patience/Counseling", "Dietary Advice"],
        salaryRange: "India: ₹5L - ₹18L+ | Global: $60K - $120K",
        educationPath: "BHMS → Specialized Diploma / MD focusing on Dermatology",
        yearsOfStudy: "5.5 to 8.5 Years",
        industriesHiring: ["Skin & Trichology Clinics", "Private Practice", "Holistic Cosmetology Centers"],
        futureScope: "Extremely lucrative. Autoimmune skin conditions often rebound with steroids, driving massive patient volumes toward homeopathy for a permanent internal cure.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Highly branded independent \"Skin & Hair\" clinics.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["Specialized training in Homeopathic Dermatology"],
        internshipRequirements: "Shadowing senior homeopaths managing severe chronic eczema/psoriasis cases.",
        roadmap: ["Assistant Doctor", "Consultant Dermatologist", "Chain Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Psychiatrist / Psychological Counselor",
        description: "Treat mental health disorders like anxiety, depression, ADHD, and severe grief by matching a patient's deep emotional profile to a specific homeopathic remedy, acting as both counselor and doctor.",
        summary: "Mental health specialists using detailed psychological profiling and micro-doses to cure emotional trauma.",
        skills: ["Extreme Case-Taking (Hours per patient)", "Deep Psycho-analysis", "Empathy", "Psychiatric Materia Medica", "Suicide Prevention Protocols"],
        salaryRange: "India: ₹5L - ₹15L | Global: $70K - $115K",
        educationPath: "BHMS → MD in Psychiatry (Homeopathy)",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Holistic Rehab Centers", "Psychiatric Alternative Clinics", "Self-Employment"],
        futureScope: "High niche demand. Patients aggressively seek homeopathy for mental health to avoid the severe numbing side-effects and addiction of standard psychiatric pills.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Online global consulting for mental health is exceptionally common.",
        fieldWork: "Low. Entirely office/tele-health based.",
        riskLevel: "Moderate (Managing severe, unpredictable psychiatric crises)",
        certifications: ["MD (Psychiatry) Homeopathy Registration"],
        internshipRequirements: "Working alongside conventional psychiatrists to understand severe clinical pathology.",
        roadmap: ["Resident", "Consultant Psychiatrist", "Director of Holistic Therapy"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Rheumatologist / Ortho-care",
        description: "Specialize in managing severe chronic pain and autoimmune joint destruction caused by Rheumatoid Arthritis, Osteoarthritis, and Gout without long-term NSAID painkillers.",
        summary: "Specialists treating chronic joint pain and autoimmune arthritis using alternative medicines.",
        skills: ["Orthopedic Diagnostics", "Autoimmune Pathology Understanding", "Pain Management Counseling", "Constitutional Prescribing"],
        salaryRange: "India: ₹4L - ₹14L | Global: $60K - $100K",
        educationPath: "BHMS → MD/Diploma in Musculoskeletal Disorders",
        yearsOfStudy: "5.5 to 8.5 Years",
        industriesHiring: ["Pain Management Centers", "Geriatric (Elderly) Care Clinics", "Private Practice"],
        futureScope: "Stable. As populations age, the demand for non-surgical, non-toxic pain management for degrading joints creates a permanent, massive patient base.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Moderate. General outpatient departments.",
        freelanceOpportunities: "High.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["MD Registration / Specialized Pain Management training"],
        internshipRequirements: "Managing long-term geriatric patients with severe mobility issues.",
        roadmap: ["Junior Doctor", "Consultant", "Senior Arthritis Specialist"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Gynecologist",
        description: "Manage female reproductive health, particularly focusing on hormone-driven conditions like PCOS, severe PMS, Endometriosis, and Menopause without prescribing synthetic hormone pills.",
        summary: "Women’s health experts treating hormonal imbalances, PCOS, and infertility holistically.",
        skills: ["Endocrinology Understanding", "Fertility Tracking", "Patient Empathy", "Ultrasound Diagnostics (Basic)"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $110K",
        educationPath: "BHMS → Specialized training/MD in Gynecology (Alternative)",
        yearsOfStudy: "5.5 to 8.5 Years",
        industriesHiring: ["Women's Holistic Clinics", "Fertility Centers", "Private Practice"],
        futureScope: "Extremely high. PCOS and infertility are skyrocketing globally; women are increasingly turning to homeopathy to regulate periods naturally.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum. Setting up independent \"Holistic Women's Clinics\" is highly recommended.",
        fieldWork: "Low.",
        riskLevel: "Moderate",
        certifications: ["Specialization in Female Health / Gynecology"],
        internshipRequirements: "Clinical hours in female health wards.",
        roadmap: ["Assistant Doctor", "Consultant Gynecologist", "Fertility Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Allergist / Immunologist",
        description: "Focus purely on curing hyper-reactive immune systems, successfully treating chronic asthma, severe hay fever, rhinitis, and food allergies by desensitizing the body constitutionally.",
        summary: "Specialists treating chronic asthma, sinus, and severe food allergies.",
        skills: ["Immune System Pathology", "Allergen Identification", "Long-term Case Management", "Dietary Restriction Counseling"],
        salaryRange: "India: ₹5L - ₹14L | Global: $65K - $105K",
        educationPath: "BHMS → Clinical experience focusing on respiratory/immune cases",
        yearsOfStudy: "5.5 Years + Extensive Practice",
        industriesHiring: ["Respiratory Clinics", "General Alternative Hospitals", "Private Practice"],
        futureScope: "High Growth. Global pollution and dietary changes mean chronic childhood and adult allergies are universally increasing.",
        jobDemandTrend: "High",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Patients with severe asthma attacks need acute care protocols)",
        certifications: ["Homeopathic Medical Council Registration"],
        internshipRequirements: "Managing acute asthmatic exacerbations.",
        roadmap: ["Junior Doctor", "Consultant Allergist", "Senior Specialist"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Veterinary Homeopath",
        description: "Apply homeopathic principles specifically to animals—from household dogs and cats to massive agricultural livestock—often chosen by organic farmers who refuse to use conventional antibiotics on their herds.",
        summary: "Alternative veterinarians treating pets and organic farm livestock with homeopathic remedies.",
        skills: ["Quadruped Pathology", "Animal Behavior Tracking (Since animals cannot speak symptoms)", "Organic Farming Compliance", "Owner Counseling"],
        salaryRange: "India: ₹3L - ₹8L | Global: $50K - $90K",
        educationPath: "B.V.Sc (Veterinary MBBS) → Diploma/Certification in Veterinary Homeopathy",
        yearsOfStudy: "6 to 7 Years",
        industriesHiring: ["Organic Dairy Farms", "Alternative Pet Clinics", "Equestrian (Horse) Hospitals"],
        futureScope: "Massive niche growth globally. The organic farming industry strictly limits conventional antibiotics, driving massive demand for herd homeopaths.",
        jobDemandTrend: "Rapid Growth (Niche)",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Traveling consultant for multiple organic farms.",
        fieldWork: "High. Constant travel to massive farms and ranches.",
        riskLevel: "Moderate (Dealing with large, sick, unpredictable animals)",
        certifications: ["Certified Veterinary Homeopath (CVH)"],
        internshipRequirements: "Shadowing holistic vets treating both small pets and large farm animals.",
        roadmap: ["Vet Trainee", "Certified Vet Homeopath", "Livestock Consultant"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Pharmacist / Dispenser",
        description: "Work with immense precision to dilute, succuss (shake), and prepare homeopathic medicines into exact potencies (like 30CH or 1M) according strictly to the official Homeopathic Pharmacopoeia.",
        summary: "The laboratory experts diluting and manufacturing standard homeopathic remedies.",
        skills: ["Potentization/Succussion Techniques", "Tincture Preparation", "Extreme Measurement Precision", "Pharmacopoeia Compliance"],
        salaryRange: "India: ₹2.5L - ₹7L | Global: $40K - $75K",
        educationPath: "Diploma in Homeopathic Pharmacy (DHP) or B.Pharm",
        yearsOfStudy: "2 to 4 Years",
        industriesHiring: ["Massive Homeopathic Manufacturers (e.g., Dr. Reckeweg, SBL)", "State Dispensaries", "Large Retail Homeopathic Pharmacies"],
        futureScope: "Stable. As long as homeopathic doctors exist, specialized pharmacists are strictly required to legally manufacture the extreme microscopic dilutions.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Dispensers for state AYUSH clinics.",
        freelanceOpportunities: "Low. Institutionalized.",
        fieldWork: "Low. Laboratory and retail based.",
        riskLevel: "Low",
        certifications: ["State Pharmacy Council Registration"],
        internshipRequirements: "Supervised manufacturing of mother tinctures and potentized dilutions.",
        roadmap: ["Dispenser", "Pharmacist", "Manufacturing Supervisor", "Quality Control Head"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Medical Officer (HMO)",
        description: "Government-appointed doctors acting as the clinical authority in state-run dispensaries, explicitly tasked with bringing cheap, alternative medical care to vast rural populations.",
        summary: "Government-employed doctors managing outpatient care in state dispensaries.",
        skills: ["High-Volume Rapid Case Taking", "Public Health Administration", "Community Outreach", "Inventory Management"],
        salaryRange: "India: ₹6L - ₹12L | Global: N/A",
        educationPath: "BHMS → State/Central Public Service Commission Examination",
        yearsOfStudy: "5.5 Years",
        industriesHiring: ["State Health Departments", "CGHS (Central Government Health Scheme)", "Public Sector Units"],
        futureScope: "Highly secure. Government jobs provide lifelong security, pensions, and consistent career progression regardless of private market forces.",
        jobDemandTrend: "Stable",
        governmentJobs: "Maximum. 100% government sector role.",
        freelanceOpportunities: "Low (Usually restricted by government service rules).",
        fieldWork: "Moderate. Managing community medical camps.",
        riskLevel: "Low",
        certifications: ["State Medical Council Registration"],
        internshipRequirements: "Rural clinical postings.",
        roadmap: ["Homeopathic Medical Officer", "Senior Medical Officer", "District AYUSH Officer", "Director of AYUSH"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Researcher",
        description: "Conduct rigorous clinical trials, double-blind studies, and purely academic research to provide statistical, modern scientific evidence that ultra-diluted homeopathic remedies legally work.",
        summary: "The academic scientists designing clinical trials to prove homeopathic efficacy.",
        skills: ["Clinical Trial Design (RCTs)", "Biostatistics", "Scientific Writing / Publishing", "Pharmacodynamics (Theory of Dilution)"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $100K",
        educationPath: "BHMS → MD / Ph.D. / M.Sc in Clinical Research",
        yearsOfStudy: "8.5 to 11 Years",
        industriesHiring: ["Government Research Councils (CCRH in India)", "Private Foundations", "Academic Universities"],
        futureScope: "Critical. The homeopathic industry is under immense global pressure to produce modern, peer-reviewed clinical data, making highly skilled researchers indispensable.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Maximum. National research institutes.",
        freelanceOpportunities: "Moderate. Grant-based dependent research.",
        fieldWork: "Low. Laboratory and academic center based.",
        riskLevel: "Low",
        certifications: ["Ph.D. / Clinical Research Certifications"],
        internshipRequirements: "Assisting in active clinical trials and data gathering.",
        roadmap: ["Research Assistant", "Research Officer", "Principal Investigator", "Director of Research Council"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Academician / Professor",
        description: "Teach incredibly complex subjects like Homeopathic Materia Medica, Organon of Medicine (Philosophy), and Repertory to thousands of undergraduate and postgraduate medical students.",
        summary: "The professors and philosophical pillars of homeopathic medical colleges.",
        skills: ["Deep Philosophical Comprehension (Organon)", "Didactic Lecturing", "Curriculum Design", "Mentoring", "Case-Study Presentation"],
        salaryRange: "India: ₹6L - ₹18L | Global: $70K - $110K",
        educationPath: "BHMS → MD in Homeopathy",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Homeopathic Medical Colleges and Universities"],
        futureScope: "Stable. Teaching roles are permanent, highly respected, and generally allow the professor to maintain a private evening clinical practice simultaneously.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. State medical colleges.",
        freelanceOpportunities: "High. Running concurrent private practices.",
        fieldWork: "Low. Campus based.",
        riskLevel: "Low",
        certifications: ["MD Registration (Teaching eligibility)"],
        internshipRequirements: "Extensive academic fellowships.",
        roadmap: ["Lecturer / Assistant Professor", "Associate Professor", "Professor / HOD", "College Principal"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Gastroenterologist",
        description: "Treat massive volumes of chronic digestive illnesses—such as Irritable Bowel Syndrome (IBS), Chronic Acidity, Gallstones, and Ulcers—that conventional medicine often struggles to permanently cure.",
        summary: "Specialists treating chronic stomach, intestinal, and liver diseases.",
        skills: ["GI Tract Pathology", "Dietary/Nutrition Counseling", "Stress/Gut-Brain Axis Analysis", "Repertorization of physical symptoms"],
        salaryRange: "India: ₹5L - ₹18L | Global: $65K - $110K",
        educationPath: "BHMS → Clinical experience focusing on Gastroenterology",
        yearsOfStudy: "5.5 Years + Extensive Practice",
        industriesHiring: ["Specialty Clinics", "Alternative Hospitals", "Private Practice"],
        futureScope: "Explosive. IBS and chronic digestive issues are rampant globally due to high stress and poor diets, and homeopathy is famously effective for functional gut disorders.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["Homeopathic Medical Council Registration"],
        internshipRequirements: "Managing long-term functional bowel cases.",
        roadmap: ["Assistant Doctor", "Consultant Specialist", "Senior Gastroenterology Homeopath"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Pulmonologist / Respiratory Specialist",
        description: "Specialize heavily in chronic lung diseases, treating thousands of cases of Chronic Bronchitis, COPD, and recurrent Childhood Pneumonias using constitutional lung-specific remedies.",
        summary: "Specialists focusing purely on chronic lung diseases, asthma, and severe coughs.",
        skills: ["Stethoscope Auscultation", "Reading Chest X-Rays/PFTs", "Understanding Chronic Inflammatory Pathways", "Patient Education"],
        salaryRange: "India: ₹4.5L - ₹15L | Global: $60K - $105K",
        educationPath: "BHMS → Clinical experience focusing on Respiratory diseases",
        yearsOfStudy: "5.5 Years + Extensive Practice",
        industriesHiring: ["Respiratory Clinics", "Private Practice", "Alternative Care Hospitals"],
        futureScope: "High Growth. Urban pollution directly correlates with a massive spike in lifelong respiratory patients who wish to reduce their dependency on steroid inhalers.",
        jobDemandTrend: "High",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Managing severe breathlessness and potential hypoxia manually)",
        certifications: ["Homeopathic Medical Council Registration"],
        internshipRequirements: "Intensive clinical exposure to COPD/Asthma wards.",
        roadmap: ["Junior Doctor", "Consultant Pulmonologist", "Senior Specialist"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Endocrinologist (Thyroid/Diabetes Focus)",
        description: "Focus on systemic glandular issues, explicitly treating Hypothyroidism, Hyperthyroidism, Diabetes Type-2, and massive hormonal shifts by attempting to constitutionally 'reboot' the endocrine system.",
        summary: "Specialists treating Thyroid diseases and Diabetes using holistic metabolic therapies.",
        skills: ["Interpreting Complex Blood Panels (T3, T4, TSH, HbA1c)", "Metabolic Science", "Weight Loss Counseling", "Long-term Case Follow-up"],
        salaryRange: "India: ₹5L - ₹15L | Global: $65K - $110K",
        educationPath: "BHMS → Specialized certification / Clinical focus in Endocrinology",
        yearsOfStudy: "5.5 Years + Extensive Practice",
        industriesHiring: ["Diabetes Care Centers", "Hormonal Clinics", "Private Practice"],
        futureScope: "Explosive. Thyroid disorders and Diabetes are global epidemics. Patients constantly seek alternative means to avoid taking lifelong daily synthetic thyroid hormones.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Must closely monitor blood test levels to prevent severe hormonal crashes)",
        certifications: ["Homeopathic Medical Council Registration"],
        internshipRequirements: "Co-managing complex diabetic and thyroid cases.",
        roadmap: ["Assistant Doctor", "Consultant Endocrinologist", "Hormone Clinic Director"]
    },
    {
        domain: "Medical",
        branch: "Homeopathy",
        title: "Homeopathic Oncologist (Adjunct / Palliative Care)",
        description: "Work explicitly alongside conventional cancer treatments (chemo/radiation) to provide homeopathic remedies that severely reduce nausea, pain, hair loss, and improve the terminal patient's final quality of life.",
        summary: "Specialized doctors providing highly necessary pain relief and side-effect reduction during severe cancer treatments.",
        skills: ["Palliative Care Empathy", "Understanding Chemo Side-effects", "Severe Pain Management", "Terminal Patient Counseling"],
        salaryRange: "India: ₹6L - ₹18L | Global: $75K - $125K",
        educationPath: "BHMS → MD → Extensive training in Oncology / Palliative Care",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Integrative Cancer Hospitals", "Hospice Care Centers", "Premium Private Clinics"],
        futureScope: "High Niche Demand. 'Integrative Oncology' is becoming mainstream globally, where conventional aggressive medicine and alternative soothing medicine work simultaneously.",
        jobDemandTrend: "Rapid Growth",
        governmentJobs: "Low. Usually integrative private sector.",
        freelanceOpportunities: "Moderate. Requires close collaboration with allopathic oncologists.",
        fieldWork: "Low. Hospital/Hospice based.",
        riskLevel: "Moderate (Heavy emotional toll dealing strictly with terminal or severely ill patients)",
        certifications: ["Specialization in Palliative / Integrative Care"],
        internshipRequirements: "Shadowing in oncology hospices and cancer wards.",
        roadmap: ["Resident Doctor", "Integrative Consult", "Head of Palliative Care"]
    }
];

const seedHomeopathy = async () => {
    try {
        await Career.deleteMany({ branch: "Homeopathy" });
        await Career.insertMany(homeopathyProfessions);
        console.log('Homeopathy Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedHomeopathy();
