const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const civilLawProfessions = [
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Civil Litigation Lawyer",
        description: "Represents clients in non-criminal lawsuits. They handle major disputes involving contracts, torts, property, and personal injury, fighting to secure financial compensation or specific performance for their clients.",
        educationPath: "LLB -> LLM in Civil Law (Optional)",
        competitiveExams: ["CLAT", "AILET", "State Law Entrance Exams (MH CET, AP LAWCET)"],
        yearsOfStudy: "5 Years (Integrated) or 3 Years (Post-Graduation)",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Courtroom Argumentation", "Civil Procedure Code (CPC)", "Evidence Presentation", "Cross-Examination"],
        salaryRange: "India: ₹4 LPA - ₹30+ LPA | Global: $60,000 - $180,000+ per year",
        roadmap: ["Junior Civil Advocate", "Independent Practitioner", "Senior Advocate", "Designated Senior Counsel"],
        courtPracticeOpportunities: "Massive; constant daily appearances in District Courts, High Courts, and Supreme Court.",
        governmentJobs: "Empanelment as State Counsel or Standing Counsel for various government departments.",
        privateSectorOpportunities: "Employed heavily by large litigation firms and senior advocates to manage case volume.",
        mediationArbitrationOpportunities: "Frequently involved in court-mandated mediation sessions before trial commences.",
        workNature: "Heavy Courtroom Litigation & Intense Legal Drafting.",
        riskLevel: "Moderate (Professional liability for case outcomes)",
        futureScope: "Extremely stable. Civil disputes are the absolute majority of all global legal cases, ensuring a permanent necessity for skilled litigators.",
        jobDemandTrend: "High and Constant",
        summary: "The quintessential courtroom warrior of the non-criminal world, fighting daily battles over massive financial and personal disputes."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Property Dispute Lawyer",
        description: "Specializes entirely in real estate conflicts. They handle cases involving contested inheritances, fraudulent land sales, boundary encroachments, and massive commercial lease breaches.",
        educationPath: "LLB -> LLM in Property/Real Estate Law",
        competitiveExams: ["CLAT", "State Entrance Exams"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Transfer of Property Act", "Title Verification", "Inheritance Law", "Local Zoning Codes"],
        salaryRange: "India: ₹6 LPA - ₹40+ LPA | Global: $70,000 - $200,000+ per year",
        roadmap: ["Junior Property Lawyer", "Consulting Advocate", "Senior Property Consultant", "Real Estate Litigation Partner"],
        courtPracticeOpportunities: "Extensive practice in Civil Courts, Revenue Courts, and Real Estate Regulatory Authorities (RERA).",
        governmentJobs: "Land Acquisition Officers, Revenue Department legal advisors.",
        privateSectorOpportunities: "High demand in infra-companies, builders, and elite real estate law boutiques.",
        mediationArbitrationOpportunities: "Highly favored route to avoid decades-long property freezes in civil courts.",
        workNature: "Courtroom Arguments, Field Verification & Heavy Documentation.",
        riskLevel: "Moderate",
        futureScope: "Exceptionally lucrative in developing nations experiencing massive urban expansion and consequent land disputes.",
        jobDemandTrend: "Very High Volume",
        summary: "A high-stakes litigator dealing exclusively with mankind's most valuable asset: land."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Contract Lawyer",
        description: "Focuses on the meticulous drafting, reviewing, and enforcing of legally binding agreements. When contracts are breached, they aggressively litigate to enforce the terms or extract massive compensatory damages.",
        educationPath: "LLB",
        competitiveExams: ["CLAT", "AILET"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Contract Act", "Specific Relief Act", "Flawless Drafting", "Commercial Negotiation"],
        salaryRange: "India: ₹5 LPA - ₹25 LPA | Global: $80,000 - $180,000 per year",
        roadmap: ["Drafting Associate", "Commercial Litigator", "Senior Counsel - Contracts", "Partner - Civil Commercial Dispute"],
        courtPracticeOpportunities: "High frequency of appearances in Commercial Courts and High Courts.",
        governmentJobs: "Advising PSU tender drafting and commercial contract execution.",
        privateSectorOpportunities: "Every massive corporation retains dedicated contract litigators.",
        mediationArbitrationOpportunities: "Almost all modern commercial contracts mandate arbitration before court litigation.",
        workNature: "Intense Desk Drafting & Commercial Court Litigation.",
        riskLevel: "Low to Moderate",
        futureScope: "The lifeblood of commerce; as global trade expands, the enforcement of cross-border and domestic contracts becomes vital.",
        jobDemandTrend: "Stable and Highly Lucrative",
        summary: "A precision-focused lawyer ensuring that every word in a contract holds up under full judicial scrutiny."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Family Settlement Lawyer",
        description: "Specializes in the non-litigious resolution of massive family wealth. They draft complex wills, execute trusts, and forcefully mediate bitter inheritance feuds to keep high-net-worth families out of public courts.",
        educationPath: "LLB -> Diploma in Trust & Estate Planning",
        competitiveExams: ["LSAT / CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment", "STEP Certificate (Optional)"],
        skills: ["Succession Laws", "Hindu/Muslim Personal Law", "Tax Mitigation", "Diplomacy"],
        salaryRange: "India: ₹6 LPA - ₹30+ LPA | Global: $75,000 - $200,000+ per year",
        roadmap: ["Family Law Associate", "Estate Planner", "Senior Family Counsel", "Partner - Private Client Practice"],
        courtPracticeOpportunities: "Mostly probate courts; actively tries to avoid public litigation.",
        governmentJobs: "Roles in state family welfare departments.",
        privateSectorOpportunities: "Elite roles in Private Wealth Management firms and Family Offices.",
        mediationArbitrationOpportunities: "Mediation is the absolute core of this profession—settling disputes behind closed doors.",
        workNature: "Advisory, Mediation, & Highly Sensitive Drafting.",
        riskLevel: "Low",
        futureScope: "With massive generational wealth transfers looming globally, keeping estates out of drawn-out litigation is a premium skill.",
        jobDemandTrend: "Growing rapidly among HNIs",
        summary: "The diplomatic peacemaker guarding family legacies, ensuring wealth transfers smoothly without shattering relationships."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Civil Legal Advisor",
        description: "Provides out-of-court strategic counsel to individuals and SMEs regarding civil liabilities, lease structures, consumer complaints, and general non-criminal legal risk mitigation.",
        educationPath: "LLB",
        competitiveExams: ["CLAT / AILET"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Risk Assessment", "Statutory Interpretation", "Tort Law", "Client Counseling"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $65,000 - $130,000 per year",
        roadmap: ["Legal Consultant", "Senior Legal Advisor", "In-house Counsel", "General Counsel"],
        courtPracticeOpportunities: "Low frequency; focuses strictly on pre-litigation settlement and advice.",
        governmentJobs: "General legal advisors to municipal bodies.",
        privateSectorOpportunities: "High demand in corporates wanting to avoid lawsuits.",
        mediationArbitrationOpportunities: "Acts as the primary client representative during non-binding mediation.",
        workNature: "Advisory, Legal Research & Corporate Consultation.",
        riskLevel: "Low",
        futureScope: "Extremely steady. Preventive legal care is becoming standard practice for SMEs to avoid catastrophic court penalties.",
        jobDemandTrend: "Stable Demand",
        summary: "A generalist civil law expert focusing on keeping individuals and businesses legally safe and out of court."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Real Estate Civil Lawyer",
        description: "Handles the massive legal architecture required to construct and sell buildings. They completely manage zoning laws, environmental clearances, mega-lease agreements, and RERA compliance for entire townships.",
        educationPath: "LLB -> LLM in Real Estate/Commercial Law",
        competitiveExams: ["State Entrance Exams"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Due Diligence", "RERA Act", "Municipal Zoning Codes", "Massive Contract Structuring"],
        salaryRange: "India: ₹8 LPA - ₹35+ LPA | Global: $90,000 - $250,000+ per year",
        roadmap: ["Real Estate Associate", "Senior Title Counsel", "Partner - Real Estate Law", "Infrastructure Legal Head"],
        courtPracticeOpportunities: "Regular appearances in RERA tribunals and civil courts to defend developers.",
        governmentJobs: "Consultant roles in smart-city development authorities.",
        privateSectorOpportunities: "Massive demand across Tier-1 infra developers (DLF, Godrej, Lodha).",
        mediationArbitrationOpportunities: "Frequently arbitrates massive disputes between developers and contractor syndicates.",
        workNature: "Heavy Transactions, Title Verifications & Tribunal Litigation.",
        riskLevel: "Moderate (High financial stakes)",
        futureScope: "As long as cities expand, the complexity of acquiring, zoning, and building on land will require massive legal oversight.",
        jobDemandTrend: "Very High Demand",
        summary: "The transactional architect behind every skyscraper, mall, and residential township."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Consumer Rights Lawyer",
        description: "Represents everyday consumers against massive corporations. They litigate cases regarding defective products, medical negligence, false advertising, and unfair trade practices to secure immense compensation.",
        educationPath: "LLB",
        competitiveExams: ["CLAT (UG & PG)"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Consumer Protection Act", "Class-Action Strategy", "Tort Litigation", "Public Speaking"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $140,000 per year",
        roadmap: ["Consumer Court Litigator", "Independent Practitioner", "Class-Action Specialist", "Senior Counsel"],
        courtPracticeOpportunities: "Daily practice in District, State, and National Consumer Dispute Redressal Commissions.",
        governmentJobs: "Appointed as members or presidents of consumer courts.",
        privateSectorOpportunities: "Operate highly profitable independent civil litigation chambers.",
        mediationArbitrationOpportunities: "High frequency of out-of-court settlements to avoid media embarrassment for corporations.",
        workNature: "Courtroom Arguments & Drafting Complaints.",
        riskLevel: "Low to Moderate",
        futureScope: "With digital commerce expanding and consumer awareness peaking globally, there is an endless stream of product liability lawsuits.",
        jobDemandTrend: "High Volume",
        summary: "The ultimate equalizer, utilizing civil tort laws to force massive corporations to compensate wronged individuals."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Civil Court Advocate",
        description: "The traditional all-rounder litigator practicing exclusively in the subordinate District courts. They handle everyday local civil matters: evictions, debt recovery, and minor injunctions.",
        educationPath: "LLB",
        competitiveExams: ["State Entrance / LSAT India"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Local Court Procedures", "Vernacular Language Fluency", "Rapid Drafting", "Client Management"],
        salaryRange: "India: ₹2 LPA - ₹10 LPA | Global: N/A (Highly localized)",
        roadmap: ["Junior District Advocate", "Independent Chamber Owner", "District Bar President", "Elevation to Judiciary"],
        courtPracticeOpportunities: "The absolute bulk of practice is physically inside the buzzing District Courts.",
        governmentJobs: "Stepping stone to becoming a District/Civil Judge via Judiciary Exams.",
        privateSectorOpportunities: "Running a purely independent local chamber.",
        mediationArbitrationOpportunities: "Mandatory civil mediation referrals from the district judge.",
        workNature: "Extreme High-Volume Courtroom Litigation.",
        riskLevel: "Low",
        futureScope: "Always stable. The vast majority of the nation's legal conflicts start and end at the district level.",
        jobDemandTrend: "Stable and Highly Localized",
        summary: "The grassroots litigator managing the daily pulse of localized civil disputes and keeping the lower courts functioning."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Civil Legal Consultant",
        description: "Provides highly specialized knowledge in obscure niches of civil law (like maritime civil damage, aviation torts, or unique copyright infringement) to other law firms lacking that specific expertise.",
        educationPath: "LLB -> LLM (Highly Specialized)",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Niche Industry Diplomas"],
        skills: ["Deep Niche Knowledge", "Precedent Synthesis", "Case Strategy", "Academic Precision"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $80,000 - $150,000 per year",
        roadmap: ["Subject Matter Expert", "Specialist Consultant", "Of Counsel", "Boutique Firm Partner"],
        courtPracticeOpportunities: "Very low; acts as the strategic brain behind the litigator actually appearing in court.",
        governmentJobs: "Consulting for specific government tribunals (e.g., NGT).",
        privateSectorOpportunities: "Hired on massive retainers by Tier-1 firms to consult on unicorn cases.",
        mediationArbitrationOpportunities: "Brought in as an expert third-party neutral evaluator.",
        workNature: "Deep Research, Advisory & Strategy Formulation.",
        riskLevel: "Low",
        futureScope: "As law becomes infinitely complex, generalized firms structurally require hyper-specialized consultants to win massive civil cases.",
        jobDemandTrend: "Niche but Ultra-Premium",
        summary: "The hyper-specialist brought in strategically to dictate the legal mechanism for uniquely complex civil dilemmas."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Civil Law Researcher",
        description: "Digs through massive archives of case law, colonial-era civil codes, and global precedents to find the exact legal argument needed by Senior Advocates to win impossible civil appeals.",
        educationPath: "LLB -> LLM",
        competitiveExams: ["CLAT / AILET"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["SCC/Manupatra Mastery", "Speed Reading", "Civil Jurisprudence", "Academic Writing"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $60,000 - $100,000 per year",
        roadmap: ["Judicial Clerk", "Senior Research Associate", "Think-Tank Scholar", "Academic Author"],
        courtPracticeOpportunities: "None. Purely behind-the-scenes support.",
        governmentJobs: "Law Clerk cum Research Assistants at the Supreme Court / High Courts.",
        privateSectorOpportunities: "Hired heavily by Senior Advocates designated by the High Court.",
        mediationArbitrationOpportunities: "N/A",
        workNature: "Pure Legal Research & Academic Drafting.",
        riskLevel: "Low",
        futureScope: "The absolute best training ground to master the Civil Procedure Code before branching out into elite appellate litigation.",
        jobDemandTrend: "Stable",
        summary: "The intellectual backbone of massive civil cases, unearthing the forgotten precedents that change the tides of civil appeals."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Legal Mediator",
        description: "A completely neutral third party tasked with resolving explosive civil disputes (family, property, business) entirely outside the courtroom. They do not judge; they strictly facilitate psychological and legal compromises.",
        educationPath: "LLB / Psychology Background",
        competitiveExams: ["None specific route"],
        yearsOfStudy: "5 Years",
        certifications: ["Certified Mediator Training (40 Hours Mandatory in India)"],
        skills: ["Extreme Empathy", "Conflict De-escalation", "Neutrality", "Creative Problem Solving"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $70,000 - $140,000 per year",
        roadmap: ["Empanelled Mediator", "Senior Core Mediator", "International Mediation Expert", "Mediation Center Director"],
        courtPracticeOpportunities: "None. They actively exist to prevent courtroom practice.",
        governmentJobs: "Empanelled directly by High Court Mediation Centers.",
        privateSectorOpportunities: "Incredible demand in corporate spheres wanting to avoid public PR disasters via courts.",
        mediationArbitrationOpportunities: "This is the entire definition of the role.",
        workNature: "Intense Negotiation, Counseling, & Dispute Facilitation.",
        riskLevel: "Low",
        futureScope: "The fastest growing global trend in civil law. Courts are hopelessly backlogged, forcing mandatory mediation across the world.",
        jobDemandTrend: "Exploding Demand",
        summary: "A psychological and legal hybrid creating win-win scenarios to save clients decades of excruciating court battles."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Arbitration Lawyer",
        description: "A highly specialized civil litigator who represents mega-corporations in private Arbitration tribunals rather than public courts. They handle hyper-complex international commercial disputes governed by the Arbitration Act.",
        educationPath: "LLB -> LLM in Alternative Dispute Resolution (ADR)",
        competitiveExams: ["MCIArb / FCIArb (Global Certifications)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment", "Chartered Institute of Arbitrators (CIArb)"],
        skills: ["Arbitration Act", "International Law", "Contractual Mastery", "Cross-Examination"],
        salaryRange: "India: ₹12 LPA - ₹50+ LPA | Global: $150,000 - $400,000+ per year",
        roadmap: ["Arbitration Associate", "Senior Counsel", "Partner - Dispute Resolution", "Appointed Arbitrator (Judge)"],
        courtPracticeOpportunities: "Limited to enforcing or challenging Arbitral Awards in the High Courts.",
        governmentJobs: "Representing NHAI, Railways, or PSUs in massive infrastructure arbitrations.",
        privateSectorOpportunities: "The absolute highest paying dispute resolution role in global Tier-1 law firms.",
        mediationArbitrationOpportunities: "This role acts as the prosecutor/defender within the Arbitration Tribunal.",
        workNature: "High-Stakes Private Tribunal Litigation & Intense Evidentiary Drafting.",
        riskLevel: "Moderate",
        futureScope: "Global MNCs completely bypass domestic courts via arbitration clauses. Arbitration Lawyers are the undisputed kings of modern commercial dispute resolution.",
        jobDemandTrend: "Very High (Elite Tier)",
        summary: "The elite, private-court litigator handling multi-million dollar corporate warfare behind closed doors."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Civil Case Analyst",
        description: "Utilizes historical data and legal AI software to analytically predict the exact success probability of a massive civil lawsuit before a corporation commits millions of dollars to litigation fees.",
        educationPath: "LLB / Operations Research",
        competitiveExams: ["None"],
        yearsOfStudy: "4 to 5 Years",
        certifications: ["Legal Tech / Data Analytics Diplomas"],
        skills: ["Data Synthesis", "Risk Probability", "Legal Cost Forecasting", "AI Legal Tools"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $75,000 - $140,000 per year",
        roadmap: ["Case Analyst", "Litigation Risk Modeler", "Director of Legal Strategy", "Chief Strategy Officer"],
        courtPracticeOpportunities: "None.",
        governmentJobs: "Advising government departments on whether to appeal lost cases.",
        privateSectorOpportunities: "Hired by Litigation Finance Firms (companies that fund lawsuits for a cut of the winnings).",
        mediationArbitrationOpportunities: "Advises clients on the exact financial point at which mediation is cheaper than winning at trial.",
        workNature: "Data Analytics, Financial Forecasting & Strategy.",
        riskLevel: "Low",
        futureScope: "A highly modern, tech-forward legal role driven by the massive rise of third-party litigation funding globally.",
        jobDemandTrend: "Emerging and Rapidly Growing",
        summary: "A pure strategist executing mathematical risk-assessments on whether a multi-million dollar civil lawsuit is actually worth fighting."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Legal Drafting Specialist",
        description: "The absolute masters of civil procedural language. They do not argue in court; they sit in drafting chambers creating the flawlessly structured plaints, written statements, and writ petitions that other lawyers read aloud.",
        educationPath: "LLB",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment (Optional if not signing)"],
        skills: ["Immaculate Grammar", "Civil Procedure Commands", "Pleading Formatting", "Extreme Attention to Detail"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $55,000 - $110,000 per year",
        roadmap: ["Drafting Junior", "Senior Legal Drafter", "Head of Documentation", "Independent Drafting Chamber"],
        courtPracticeOpportunities: "None. Exclusively a desk practice.",
        governmentJobs: "Draftsmen in the Legislative Department formatting actual bills and laws.",
        privateSectorOpportunities: "Senior Advocates desperately require elite drafters to handle their massive filing volume.",
        mediationArbitrationOpportunities: "Drafts the final, legally binding Settlement Agreements.",
        workNature: "Intense Desk Drafting & Formatting.",
        riskLevel: "Low",
        futureScope: "Every single civil case requires a perfectly drafted procedural document. The demand for flawless drafters continuously outstrips supply.",
        jobDemandTrend: "High and Constant",
        summary: "The unseen ghostwriters of the legal world, forging the physical documents that make or break a civil lawsuit."
    },
    {
        domain: "Law",
        branch: "Civil Law",
        title: "Civil Law Professor",
        description: "Dedicated academic scholars shaping the next generation of civil lawyers. They lecture on Constitutional Law, Torts, and Contracts at elite universities and publish treatises that influence judicial thinking.",
        educationPath: "LLB -> LLM -> Ph.D. in Law",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Pedagogy", "Academic Writing", "Jurisprudential Theory", "Debate & Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $160,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean or Vice-Chancellor"],
        courtPracticeOpportunities: "Can maintain an elite consulting appellate practice.",
        governmentJobs: "Permanent faculty positions in National Law Universities (NLUs).",
        privateSectorOpportunities: "Highly lucrative positions in elite private law schools (Jindal, Symbiosis).",
        mediationArbitrationOpportunities: "Frequently appointed as Arbitrators due to their profound theoretical neutrality.",
        workNature: "Teaching, Mentoring, & Academic Publishing.",
        riskLevel: "Low",
        futureScope: "Incredibly secure. Top professors are frequently cited in landmark Supreme Court judgments regarding complex civil codes.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic guardians of civil law, educating future advocates and writing the foundational treatises of national jurisprudence."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Civil Law" });
        await Career.insertMany(civilLawProfessions);
        console.log('Civil Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
