const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const biomedicalProfessions = [
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Clinical Scientist (Biochemistry)",
        description: "Analyze blood, urine, and other bodily fluids to diagnose diseases such as diabetes, cystic fibrosis, and organ failure, and monitor patient treatment progress.",
        summary: "Scientists running complex biochemical tests on patient samples to aid doctors in diagnoses.",
        skills: ["Analytical Chemistry", "Automated Analyzer Operation", "Data Interpretation", "Meticulous Accuracy", "Quality Control"],
        salaryRange: "India: ₹4L - ₹12L | Global: $80K - $120K",
        educationPath: "B.Sc Biomedical Science / Biochemistry → M.Sc Clinical Biochemistry",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Hospital Pathology Labs", "Private Diagnostic Chains", "Public Health Laboratories"],
        futureScope: "Extremely stable. 70% of all clinical diagnoses rely entirely on pathology and biochemistry tests.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Roles in every government hospital and diagnostic lab.",
        freelanceOpportunities: "Low. Highly institutionalized.",
        fieldWork: "Low. Strictly laboratory-based.",
        riskLevel: "Moderate (Biohazard exposure handling human fluids daily)",
        certifications: ["State Paramedical/Clinical Scientist Council Registration"],
        internshipRequirements: "1 year clinical laboratory rotation.",
        roadmap: ["Trainee Scientist", "Clinical Scientist", "Senior Biochemist", "Lab Director"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Medical Microbiologist",
        description: "Study microscopic organisms like bacteria, viruses, fungi, and parasites to identify the exact cause of infectious diseases and recommend specific antibiotic treatments.",
        summary: "The detectives identifying disease-causing pathogens in patient samples.",
        skills: ["Microbial Culturing", "Gram Staining", "PCR / Molecular Techniques", "Antimicrobial Susceptibility Testing", "Attention to Detail"],
        salaryRange: "India: ₹4L - ₹10L | Global: $75K - $115K",
        educationPath: "B.Sc Microbiology/Biomedical Science → M.Sc Medical Microbiology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Hospital Labs", "Infectious Disease Research Centers", "Public Health Departments"],
        futureScope: "Explosive growth post-COVID-19. Superbugs (antibiotic resistance) and viral outbreaks guarantee severe long-term global demand.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High. CDCR equivalents, state epidemiological centers.",
        freelanceOpportunities: "Low. Requires specialized BSL safety labs.",
        fieldWork: "Low. Strictly laboratory-based.",
        riskLevel: "High (Handling live, highly infectious dangerous pathogens daily)",
        certifications: ["Clinical Microbiology Certifications"],
        internshipRequirements: "Extensive hours in Bio-Safety Level 2 and 3 (BSL) labs.",
        roadmap: ["Lab Technician", "Microbiologist", "Infection Control Lead", "Director of Microbiology"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Hematologist (Clinical Scientist)",
        description: "Specialize in the study of blood, blood-forming organs, and blood diseases, crucial for diagnosing conditions like anemia, leukemia, and hemophilia.",
        summary: "Experts analyzing blood samples to diagnose cancers, clotting disorders, and anemias.",
        skills: ["Microscopic Morphology", "Flow Cytometry", "Coagulation Testing", "Precision", "Critical Thinking"],
        salaryRange: "India: ₹4.5L - ₹11L | Global: $85K - $125K",
        educationPath: "B.Sc Biomedical Science → M.Sc Hematology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Cancer Research Institutes", "Blood Banks", "Hospital Diagnostic Labs"],
        futureScope: "High demand. As blood cancers (leukemias) rise, highly trained scientists who can read peripheral blood smears are essential.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Moderate. Operating blood banks and state hospital labs.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Laboratory based.",
        riskLevel: "Moderate (Handling blood-borne pathogens)",
        certifications: ["Hematology Certifications"],
        internshipRequirements: "Rotations explicitly in blood typing and morphology.",
        roadmap: ["Hematology Trainee", "Clinical Hematologist", "Blood Bank Manager", "Lab Chief"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Clinical Immunologist",
        description: "Study and diagnose disorders of the immune system, such as autoimmune diseases (lupus, rheumatoid arthritis), severe allergies, and immunodeficiencies (HIV).",
        summary: "Scientists investigating immune system malfunctions, allergies, and autoimmune conditions.",
        skills: ["ELISA Testing", "Immunofluorescence", "Deep Cellular Understanding", "Analytical Troubleshooting"],
        salaryRange: "India: ₹5L - ₹14L | Global: $90K - $130K",
        educationPath: "B.Sc Biomedical / Immunology → M.Sc Clinical Immunology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Transplant Centers", "Autoimmune Clinics", "Biotech Research Companies"],
        futureScope: "Growing rapidly. Autoimmune diseases are increasing globally, and the development of immunotherapy (using the immune system to fight cancer) is a massive industry.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Roles in national immunology research institutes.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Laboratory based.",
        riskLevel: "Low to Moderate",
        certifications: ["Clinical Immunology Certifications"],
        internshipRequirements: "Working specifically with flow cytometers and tissue typing for transplants.",
        roadmap: ["Immunology Analyst", "Clinical Immunologist", "Principal Scientist", "Lab Director"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Genomic / Medical Geneticist Scientist",
        description: "Analyze human DNA to identify genetic mutations responsible for inherited diseases, cancer susceptibilities, and congenital abnormalities.",
        summary: "The DNA experts sequencing genes to find the exact root cause of inherited diseases.",
        skills: ["Next-Generation Sequencing (NGS)", "Bioinformatics Software", "Molecular Biology", "High-stress Accuracy", "Analytical Thinking"],
        salaryRange: "India: ₹6L - ₹18L | Global: $100K - $150K",
        educationPath: "B.Sc Genetics / Biomedical → M.Sc Medical Genetics",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Genomic Sequencing Startups", "Fertility/IVF Clinics", "Cancer Hospitals"],
        futureScope: "The future of medicine. 'Personalized medicine' relies entirely on sequencing a patient's DNA to tailor specific treatments.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate. Specialized genetics centers.",
        freelanceOpportunities: "Moderate. Bioinformatics data consulting remotely.",
        fieldWork: "Low. Office (computational) and lab based.",
        riskLevel: "Low",
        certifications: ["Board Certifications in Molecular Genetics"],
        internshipRequirements: "Intensive training operating sequencing machines and bioinformatics pipelines.",
        roadmap: ["Genetic Analyst", "Molecular Geneticist", "Lead Genomic Scientist", "Director of Genomics"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Histopathologist (Scientist/Technologist)",
        description: "Prepare and analyze ultra-thin slices of human tissue (biopsies) under microscopes to detect structural changes indicative of diseases, primarily cancer.",
        summary: "Experts who prepare patient tissue biopsies for microscopic cancer diagnosis.",
        skills: ["Microtome Operation", "Tissue Sectioning", "Complex Chemical Staining", "Extreme Manual Dexterity"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $70K - $105K",
        educationPath: "B.Sc Biomedical Science → DMLT / M.Sc Histopathology",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Oncology Hospitals", "Diagnostic Centers", "Research Universities"],
        futureScope: "Critical step in every single cancer diagnosis. As cancer rates rise, these highly skilled manual technicians are universally demanded.",
        jobDemandTrend: "High",
        governmentJobs: "High. Placed in every government hospital pathology wing.",
        freelanceOpportunities: "Low. Equipment dependent.",
        fieldWork: "Low. Laboratory based.",
        riskLevel: "Moderate (Exposure to toxic chemical fixatives like formaldehyde)",
        certifications: ["State Histotechnology Board Certifications"],
        internshipRequirements: "Hundreds of hours embedding and cutting tissue blocks without destroying the sample.",
        roadmap: ["Trainee Histotechnologist", "Senior Histology Scientist", "Lab Manager"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Toxicologist",
        description: "Analyze blood, tissue, and bodily fluids for the presence of poisons, illicit drugs, heavy metals, and prescription medication overdoses.",
        summary: "Scientists detecting drugs and poisons in the human body for medical or legal reasons.",
        skills: ["Mass Spectrometry", "Chromatography", "Analytical Problem Solving", "Legal/Chain of Custody Protocols"],
        salaryRange: "India: ₹4L - ₹12L | Global: $85K - $125K",
        educationPath: "B.Sc Biomedical / Chemistry → M.Sc Toxicology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Forensic Labs / Police", "Emergency Hospitals (Poison Control)", "Pharma Companies", "Sports Anti-Doping Agencies"],
        futureScope: "Stable and growing niche. Essential for analyzing overdose cases in emergency rooms and performing forensic investigations.",
        jobDemandTrend: "Stable (Niche)",
        governmentJobs: "Maximum. Forensic science laboratories and state poison control centers.",
        freelanceOpportunities: "Low. Highly regulated industry.",
        fieldWork: "Low. Laboratory based with occasional court appearances.",
        riskLevel: "Moderate (Handling highly toxic substances and lethal drugs)",
        certifications: ["Toxicology Board Certifications"],
        internshipRequirements: "Operating advanced analytical machinery like GC-MS under strict supervision.",
        roadmap: ["Analytical Chemist", "Clinical Toxicologist", "Forensic Toxicology Lead", "Lab Director"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Transfusion Science / Blood Bank Scientist",
        description: "Ensure the utter safety of blood transfusions by strictly cross-matching patient and donor blood, testing for infectious diseases, and preparing blood components (plasma, platelets).",
        summary: "Crucial scientists managing blood banks to guarantee safe blood transfusions during surgeries.",
        skills: ["Immunohematology", "Zero-Margin Error Tolerance", "Crisis Management (Trauma blood requests)", "Refrigeration Logistics"],
        salaryRange: "India: ₹4L - ₹9L | Global: $75K - $110K",
        educationPath: "B.Sc Biomedical Science → Specialization in Transfusion Science",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Red Cross / Blood Banks", "Trauma Centers", "General Hospitals"],
        futureScope: "Absolutely critical. No surgery or trauma center can function without a highly precise blood bank operating 24/7.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "High. State-run blood banks.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Laboratory based.",
        riskLevel: "Moderate (Handling thousands of pooled blood samples, high liability)",
        certifications: ["Blood Banking (BB) Certifications"],
        internshipRequirements: "Intensive rotations cross-matching blood under emergency time constraints.",
        roadmap: ["Blood Bank Tech", "Transfusion Scientist", "Quality Manager (Blood Bank)", "Director of Transfusion Services"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Biomedical Researcher / Principal Investigator",
        description: "Lead cutting-edge research teams at universities or institutes to uncover the fundamental cellular mechanisms of diseases like Alzheimer's, cancer, and diabetes.",
        summary: "Ph.D. scientists running laboratories to discover the deep biological causes of human diseases.",
        skills: ["Experimental Design", "Grant Writing", "Scientific Publication", "Animal Model Handling", "Data Analytics"],
        salaryRange: "India: ₹8L - ₹20L | Global: $90K - $150K",
        educationPath: "M.Sc Biomedical Science → Ph.D. → Post-Doctoral Fellowship",
        yearsOfStudy: "8 to 12 Years",
        industriesHiring: ["Universities", "National Research Institutes", "Biotech Startups"],
        futureScope: "The foundation of all medical progress. Securing funding is highly competitive, but successful researchers are globally recognized.",
        jobDemandTrend: "Competitive (Academic)",
        governmentJobs: "High. Roles in prestigious national scientific institutes.",
        freelanceOpportunities: "Moderate. Consulting for biotech venture capital firms.",
        fieldWork: "Low. Strictly academic and laboratory environments.",
        riskLevel: "Low",
        certifications: ["Ph.D. and a history of peer-reviewed publications"],
        internshipRequirements: "Years of grueling post-doctoral fellowships.",
        roadmap: ["Post-Doc Researcher", "Assistant Professor", "Principal Investigator (PI)", "Institute Director"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Virologist",
        description: "Study viruses strictly—how they mutate, how they infect human cells, and actively develop vaccines, antivirals, and rapid diagnostic kits.",
        summary: "Specialized scientists fighting global viral outbreaks through research and vaccine development.",
        skills: ["Cell Culturing", "Viral Load Testing", "Extreme Bio-Safety Compliance", "Molecular Epidemiology"],
        salaryRange: "India: ₹6L - ₹16L | Global: $95K - $135K",
        educationPath: "B.Sc Biomedical / Microbiology → M.Sc Virology / Ph.D.",
        yearsOfStudy: "6 to 9 Years",
        industriesHiring: ["Vaccine Manufacturers (Serum Institute, Pfizer)", "WHO/CDC equivalents", "Academic Labs"],
        futureScope: "Exploded exponentially after the COVID-19 pandemic. Global governments are pouring billions into viral threat monitoring and vaccine tech (mRNA).",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Maximum. State epidemic institutes.",
        freelanceOpportunities: "Low.",
        fieldWork: "Moderate. Occasionally dispatched to outbreak hotspots.",
        riskLevel: "High (Working explicitly with lethal, highly contagious viral pathogens in BSL-3/BSL-4 labs)",
        certifications: ["Specialized high-level bio-containment training"],
        internshipRequirements: "Training in maximum security biological laboratories.",
        roadmap: ["Research Assistant", "Clinical Virologist", "Vaccine Development Lead", "Head of Epidemic Response"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Neuroscientist (Molecular / Cellular)",
        description: "Investigate the complex biology of the brain and nervous system at a cellular level to find cures for degenerative diseases like Parkinson’s, Alzheimer's, and ALS.",
        summary: "Biomedical scientists dedicated to unlocking the mysteries and diseases of the human brain.",
        skills: ["Electrophysiology", "Advanced Microscopy", "Tissue Culturing", "Data Analytics (Python/R for brain mapping)"],
        salaryRange: "India: ₹7L - ₹18L | Global: $100K - $145K",
        educationPath: "M.Sc Neuroscience / Biomedical Science → Ph.D.",
        yearsOfStudy: "8 to 11 Years",
        industriesHiring: ["Neuro-Tech Startups", "Pharma R&D", "Universities", "Mental Health Institutes"],
        futureScope: "Massive potential. Neurological diseases are the next great frontier of medicine, heavily funded by governments preparing for aging populations.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Roles in national brain research centers.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["Ph.D."],
        internshipRequirements: "Extensive lab research using brain organoids or animal models.",
        roadmap: ["Ph.D. Candidate", "Post-Doc Neuroscientist", "Principal Investigator", "Head of Neuro-Research"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Embryologist (Clinical)",
        description: "Operate in fertility clinics to retrieve eggs, prepare sperm, perform In Vitro Fertilization (IVF), and carefully monitor the growth of human embryos in incubators before implantation.",
        summary: "The highly specialized clinical scientists creating human life in the laboratory during IVF procedures.",
        skills: ["Micromanipulation (ICSI)", "Cryopreservation (Freezing embryos)", "Extreme Dexterity", "Patience", "Clean-room Protocols"],
        salaryRange: "India: ₹6L - ₹20L+ | Global: $90K - $140K",
        educationPath: "B.Sc Biomedical Science → M.Sc Clinical Embryology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Private Fertility Clinics", "IVF Centers", "Maternity Hospitals"],
        futureScope: "Extremely lucrative and booming globally. As infertility rates rise and reproductive tech advances, skilled embryologists are constantly in desperate demand.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low. Heavily dominated by the premium private medical sector.",
        freelanceOpportunities: "High. Top embryologists freelance across multiple clinics performing ICSI.",
        fieldWork: "Low. Confined strictly to sterile IVF labs.",
        riskLevel: "Low (Very high stress as one mistake destroys a couple's chance at a child)",
        certifications: ["Clinical Embryology Certifications"],
        internshipRequirements: "Rigorous \"hands-on\" training manipulating microscopic eggs under inverted microscopes.",
        roadmap: ["Junior Embryologist", "Senior Clinical Embryologist", "Lab Director (IVF)"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Perfusionist (Clinical Scientist)",
        description: "Operate the highly complex heart-lung machine (cardiopulmonary bypass) during open-heart surgeries, artificially taking over the functions of the patient’s heart and lungs to keep them alive on the operating table.",
        summary: "Critical life-support scientists operating bypass machines during open-heart surgery.",
        skills: ["Crisis Management", "Understanding Complex Medical Machinery", "Surgical Pharmacology", "Focus Under Extreme Pressure"],
        salaryRange: "India: ₹6L - ₹15L | Global: $130K - $170K",
        educationPath: "B.Sc Biomedical Science → M.Sc / PG Diploma in Perfusion Technology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Cardiac Hospitals", "Trauma Centers", "Pediatric Heart Institutes"],
        futureScope: "Highly specialized and extremely well-paid niche. Only a few graduate yearly, but every heart surgery hospital requires them urgently.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "High. State hospitals with cardiac surgery wings.",
        freelanceOpportunities: "Moderate. Locum (freelance) perfusionists are paid massive daily rates to cover surgeries.",
        fieldWork: "Low. Entirely Operating Theater (OT) based.",
        riskLevel: "High (Split-second medical decisions; patient dies immediately if the machine fails or is operated incorrectly)",
        certifications: ["Board of Cardiovascular Perfusion (ABCP) Certified"],
        internshipRequirements: "Pumping hundreds of cases under senior supervision.",
        roadmap: ["Trainee Perfusionist", "Clinical Perfusionist", "Chief Perfusionist"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Biomedical Information Specialist / Bioinformatician",
        description: "Write code and use complex computational algorithms to analyze massive sets of biological data, such as mapping human genomes, tracking disease outbreaks, and discovering new drug targets via AI.",
        summary: "The data scientists of the medical world, analyzing DNA and disease data using code.",
        skills: ["Programming (Python, R)", "Machine Learning", "Statistical Modeling", "Genomics Understanding"],
        salaryRange: "India: ₹7L - ₹22L | Global: $110K - $160K",
        educationPath: "B.Sc Biomedical Science → M.Sc Bioinformatics / Computational Biology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Pharma IT Hubs", "Genomics Startups", "Healthcare AI Companies", "Research Universities"],
        futureScope: "The fastest growing technical field in medicine. Biology has become a data-science problem, and the fusion of AI with medical data is a multi-billion dollar industry.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate. Epidemiological data tracking.",
        freelanceOpportunities: "Maximum. Work from anywhere writing biological data algorithms.",
        fieldWork: "Low. Purely computer/desktop based work.",
        riskLevel: "Low",
        certifications: ["Data Science/Bioinformatics Certifications"],
        internshipRequirements: "Software engineering and data modeling internships in biotech firms.",
        roadmap: ["Bioinformatics Analyst", "Computational Biologist", "Lead Data Scientist", "Director of Bioinformatics"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Cytologist / Cytotechnologist",
        description: "Study individual human cells under a microscope to detect early signs of cancer, most famously analyzing Pap smears to detect cervical cancer.",
        summary: "Specialists trained to identify cancerous abnormalities in single human cells.",
        skills: ["Extreme Visual Attention to Detail", "Microscopy", "Staining Techniques", "Patience"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $80K - $110K",
        educationPath: "B.Sc Biomedical Science → M.Sc Cytology / Specialized PG Diploma",
        yearsOfStudy: "4.5 to 5.5 Years",
        industriesHiring: ["Diagnostic Laboratories", "Cancer Institutes", "Women's Health Clinics"],
        futureScope: "Stable and crucial. Cytologists are the primary frontline defense for catching cancers early before they form tumors.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Working in massive state biopsy labs.",
        freelanceOpportunities: "Low. Requires specialized lab setups.",
        fieldWork: "Low. Laboratory based.",
        riskLevel: "Low to Moderate (Hazardous chemical stains)",
        certifications: ["Cytotechnology Certification"],
        internshipRequirements: "Hundreds of hours reviewing normal and abnormal cytology slides.",
        roadmap: ["Trainee Cytologist", "Senior Cytotechnologist", "Lab Supervisor"]
    },
    {
        domain: "Medical",
        branch: "Biomedical Science",
        title: "Medical Science Liaison (MSL)",
        description: "Act as the primary scientific expert for a pharmaceutical company, traveling to meet top doctors and surgeons to educate them deeply on the complex science behind new drugs and therapies.",
        summary: "Elite scientific educators representing pharma companies, explaining complex drug science to top physicians.",
        skills: ["Deep Scientific Knowledge", "Public Speaking", "Networking", "Persuasion", "Clinical Trial Comprehension"],
        salaryRange: "India: ₹10L - ₹25L+ | Global: $140K - $200K+",
        educationPath: "M.Sc Biomedical Science → Ph.D. / Pharm.D",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Big Pharma (Medical Affairs Divisions)", "Biotech Firms", "Medical Device Companies"],
        futureScope: "Extremely well-paid, non-lab corporate role. As drugs (like biologics) become incredibly complex, companies desperately need Ph.D.-level scientists to explain them to doctors.",
        jobDemandTrend: "High Growth",
        governmentJobs: "None. Purely corporate pharmaceutical sector.",
        freelanceOpportunities: "Moderate. Independent consulting for startup drug companies.",
        fieldWork: "Maximum. Traveling extensively (60%+ of the time) to hospitals and international medical conferences.",
        riskLevel: "Low (High corporate pressure)",
        certifications: ["Often requires Ph.D., MD, or Pharm.D status"],
        internshipRequirements: "Medical affairs internships in pharma.",
        roadmap: ["Medical Writer / Analyst", "Medical Science Liaison", "Senior MSL", "Director of Medical Affairs"]
    }
];

const seedBiomedicalScience = async () => {
    try {
        await Career.deleteMany({ branch: "Biomedical Science" });
        await Career.insertMany(biomedicalProfessions);
        console.log('Biomedical Science Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedBiomedicalScience();
