const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const culturalStudiesProfessions = [
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Cultural Anthropologist",
        description: "Study human cultures, beliefs, practices, and social organization by immersing deeply within specific communities to understand their way of life.",
        summary: "Researchers who embed themselves in different societies to study human culture and behavior.",
        skills: ["Ethnography", "Qualitative Research", "Cultural Relativism", "Foreign Languages", "Patience"],
        salaryRange: "India: ₹4L - ₹15L | Global: $55K - $100K",
        educationPath: "B.A. Anthropology / Sociology → M.A. / Ph.D. in Cultural Anthropology",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Research Institutes", "Museums", "International NGOs"],
        futureScope: "Increasingly relevant in a globalized world to bridge cultural misunderstandings and study the impact of technology on society.",
        jobDemandTrend: "Stable, Academic Focus",
        governmentJobs: "Roles in cultural ministries or indigenous affairs departments.",
        freelanceOpportunities: "Moderate. Independent research grants or corporate cultural consulting.",
        fieldWork: "Maximum. Requires months or years living among the studied populations.",
        riskLevel: "Moderate (Depending on field location, exposure to remote environments)",
        certifications: ["PhD is typically required for lead research roles"],
        internshipRequirements: "Fieldwork assistantships during graduate studies.",
        roadmap: ["Research Assistant", "Field Ethnographer", "Professor / Senior Researcher", "Director of Anthropology Institute"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Cultural Museum Curator",
        description: "Acquire, preserve, and display collections of historical, artistic, or cultural significance, designing educational exhibitions for the public.",
        summary: "Experts who manage and construct exhibitions for museum collections.",
        skills: ["Historical Knowledge", "Archival Practices", "Exhibition Design", "Grant Writing", "Public Speaking"],
        salaryRange: "India: ₹4L - ₹15L | Global: $50K - $95K",
        educationPath: "B.A. History / Art History → M.A. Museum Studies / Museology",
        yearsOfStudy: "5 Years",
        industriesHiring: ["National Museums", "Private Art Galleries", "Historical Societies", "Universities"],
        futureScope: "Steady demand. Museums are evolving into interactive, digital experiences, requiring modern curatorial approaches.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "High. State and national museums, archaeological surveys.",
        freelanceOpportunities: "Moderate. Guest curators for independent exhibitions.",
        fieldWork: "Low to Moderate. Travel for acquiring artifacts or consulting other museums.",
        riskLevel: "Low",
        certifications: ["Certificates in Collections Management"],
        internshipRequirements: "Extensive volunteering and internships in museums and archives.",
        roadmap: ["Curatorial Assistant", "Assistant Curator", "Curator", "Chief Curator / Museum Director"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Heritage Manager",
        description: "Protect, manage, and promote historical sites, monuments, and cultural landscapes, ensuring their preservation for future generations while maximizing tourist engagement.",
        summary: "Professionals who protect and manage historical monuments and cultural sites.",
        skills: ["Conservation Knowledge", "Tourism Management", "Budgeting", "Local Laws & Regulations", "Marketing"],
        salaryRange: "India: ₹5L - ₹18L | Global: $55K - $100K",
        educationPath: "B.A. History / Archaeology → M.A. Heritage Management",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Archaeological Surveys (e.g., ASI)", "UNESCO", "National Trusts", "Tourism Boards"],
        futureScope: "Growing as governments recognize heritage sites as massive drivers for sustainable tourism economies.",
        jobDemandTrend: "Stable Growth",
        governmentJobs: "Maximum. Protecting state and national monuments.",
        freelanceOpportunities: "Moderate. Heritage consultants for real estate development near historic sites.",
        fieldWork: "High. Constant presence at historical sites and ongoing excavations.",
        riskLevel: "Low",
        certifications: ["Cultural Heritage Conservation Certificates"],
        internshipRequirements: "Work at historical sites or under conservation architects.",
        roadmap: ["Site Assistant", "Heritage Officer", "Site Manager", "Director of Conservation"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Arts Administrator",
        description: "Manage the business operations of arts organizations, handling funding, marketing, staffing, and community outreach for theaters, orchestras, and galleries.",
        summary: "The business managers who keep arts and cultural institutions financially viable and operational.",
        skills: ["Financial Management", "Arts Marketing", "Grant Writing", "Event Coordination", "Leadership"],
        salaryRange: "India: ₹4L - ₹16L | Global: $50K - $90K",
        educationPath: "B.A. Arts / Humanities → M.A. Arts Management",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Theaters", "Symphony Orchestras", "Art Foundations", "Cultural Centers"],
        futureScope: "Crucial role. As arts funding fluctuates, skilled administrators are needed to secure grants and private donations.",
        jobDemandTrend: "Stable",
        governmentJobs: "Roles in state arts councils and cultural ministries.",
        freelanceOpportunities: "Moderate. Consulting on arts funding.",
        fieldWork: "Low. Office-based with frequent attendance at evening arts events.",
        riskLevel: "Low",
        certifications: ["Non-profit Management Certificates"],
        internshipRequirements: "Interning in the administration offices of local arts venues.",
        roadmap: ["Arts Assistant", "Development Manager", "Managing Director", "Executive Director"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Cultural Art Historian",
        description: "Research and analyze visual arts, architecture, and design within their specific historical and cultural contexts, publishing academic papers or books.",
        summary: "Academics who study the timeline, cultural impact, and evolution of visual arts.",
        skills: ["Visual Analysis", "Historical Research", "Academic Writing", "Foreign Languages", "Archival Fluency"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $95K",
        educationPath: "B.A. Art History → M.A. / Ph.D. in Art History",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Museums", "Art Auction Houses (Sotheby's, Christie's)", "Publishing"],
        futureScope: "Primarily academic. Highly specialized with slow turnover in tenured positions.",
        jobDemandTrend: "Competitive, Academic",
        governmentJobs: "Researchers for state-owned art collections.",
        freelanceOpportunities: "Moderate. Writing art critiques, appraising private collections.",
        fieldWork: "Moderate. Traveling globally to view original artworks and archives.",
        riskLevel: "Low",
        certifications: ["Ph.D. required for major academic roles"],
        internshipRequirements: "Academic research assistantships.",
        roadmap: ["Research Assistant", "Adjunct Professor / Appraiser", "Tenured Professor", "Department Chair"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Cultural Policy Advisor",
        description: "Advise government bodies or massive NGOs on the implementation of policies that support the arts, protect indigenous cultures, and foster cultural diplomacy.",
        summary: "Advisors shaping government laws and funding surrounding arts and culture.",
        skills: ["Policy Drafting", "Political Acumen", "Cultural Advocacy", "Data Analysis", "Public Speaking"],
        salaryRange: "India: ₹6L - ₹20L | Global: $65K - $110K",
        educationPath: "B.A. Cultural Studies / Political Science → M.A. Cultural Policy / Public Policy",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Ministries of Culture", "UNESCO", "Think Tanks", "Arts Councils"],
        futureScope: "Growing as nations increasingly use culture as 'soft power' in international diplomacy.",
        jobDemandTrend: "Niche, High Level",
        governmentJobs: "Maximum. Directly advising government ministers and councils.",
        freelanceOpportunities: "Low. Usually structured institutional roles.",
        fieldWork: "Low to Moderate. Attending cultural summits and international forums.",
        riskLevel: "Low",
        certifications: ["Public Administration/Policy Certificates"],
        internshipRequirements: "Internships at state arts councils or political offices.",
        roadmap: ["Policy Analyst", "Senior Cultural Advisor", "Director of Arts Council", "Minister of Culture (Political)"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Festival Director / Cultural Events Manager",
        description: "Plan, curate, and execute large-scale cultural festivals, film festivals, or literary events, managing budgets, artists, and logistics.",
        summary: "The creative and logistical leaders behind major cultural festivals.",
        skills: ["Large-scale Logistics", "Curatorial Vision", "Sponsorship Negotiation", "Crisis Management", "Marketing"],
        salaryRange: "India: ₹5L - ₹25L | Global: $60K - $120K",
        educationPath: "B.A. Cultural Studies / Event Management",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Event Management Companies", "City Cultural Departments", "Independent Festival Boards"],
        futureScope: "Highly dynamic. The experience economy is booming, and cultural festivals are major tourist draws.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Managing state-sponsored cultural festivals.",
        freelanceOpportunities: "High. Independent producers hired to run specific events.",
        fieldWork: "High. On-site coordination before and during the festival.",
        riskLevel: "Low (High stress and financial risk)",
        certifications: ["Event Management Professional Certificates"],
        internshipRequirements: "Volunteering at established film, music, or literary festivals.",
        roadmap: ["Event Coordinator", "Logistics Manager", "Festival Producer", "Festival Director"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Cultural Archivist",
        description: "Appraise, preserve, and catalog significant historical documents, photographs, and digital records, making them accessible to researchers and the public.",
        summary: "Information professionals preserving the physical and digital documentary heritage of a culture.",
        skills: ["Cataloging (Metadata)", "Preservation Techniques", "Historical Context", "Digital Archiving Software", "Meticulous Detail"],
        salaryRange: "India: ₹3L - ₹10L | Global: $50K - $85K",
        educationPath: "B.A. History / Cultural Studies → M.A. Library Science / Archival Studies",
        yearsOfStudy: "5 Years",
        industriesHiring: ["National Archives", "Universities", "Corporate Archives (e.g., Disney, Ford)", "Libraries"],
        futureScope: "Stable, but rapidly evolving. The immediate future requires archivists who specialize in preserving born-digital media.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Working in state and national historical registries.",
        freelanceOpportunities: "Low. Requires access to vast institutional collections.",
        fieldWork: "Low. Primarily working in climate-controlled archive rooms.",
        riskLevel: "Low",
        certifications: ["Certified Archivist (CA)"],
        internshipRequirements: "Practicums in university or state archives.",
        roadmap: ["Archival Assistant", "Processing Archivist", "Senior Archivist", "Director of National Archives"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Ethnomusicologist",
        description: "Study music in its cultural and social contexts, researching how music reflects and shapes the identity, politics, and history of different communities.",
        summary: "Researchers studying the intersection of music, anthropology, and culture.",
        skills: ["Musical Analysis/Transcription", "Ethnography", "Foreign Languages", "Audio Recording/Archiving", "Cultural Sensitivity"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $90K",
        educationPath: "B.A. Music / Cultural Studies → M.A. / Ph.D. in Ethnomusicology",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Cultural Archives (e.g., Smithsonian)", "World Music Record Labels"],
        futureScope: "A fascinating niche focused on preserving global auditory heritage, though highly competitive academically.",
        jobDemandTrend: "Niche, Academic Focus",
        governmentJobs: "Roles in national cultural preservation boards.",
        freelanceOpportunities: "Moderate. Consulting for documentary films or world music festivals.",
        fieldWork: "High. Traveling to record and interview musicians in their native environments.",
        riskLevel: "Low",
        certifications: ["Ph.D. for leading academic roles"],
        internshipRequirements: "Field recording and archival research assistantships.",
        roadmap: ["Graduate Researcher", "Field Ethnomusicologist", "University Professor", "Archive Director"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Community Arts Worker",
        description: "Use art as a medium for social change, community building, and therapy, organizing workshops and projects in underserved or marginalized neighborhoods.",
        summary: "Activists using creative arts to heal, unify, and empower local communities.",
        skills: ["Community Organizing", "Therapeutic Arts", "Empathy", "Grant Writing", "Conflict Resolution"],
        salaryRange: "India: ₹3L - ₹8L | Global: $40K - $70K",
        educationPath: "B.A. Cultural Studies / Fine Arts / Social Work",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["NGOs", "Community Centers", "Local Government Cultural Departments", "Schools"],
        futureScope: "A passion-driven career crucial for urban development and youth intervention programs.",
        jobDemandTrend: "Stable",
        governmentJobs: "City council roles managing community grants.",
        freelanceOpportunities: "High. Operating independently to secure grants for specific neighborhood projects.",
        fieldWork: "High. Working directly in community centers, streets, and schools.",
        riskLevel: "Low to Moderate",
        certifications: ["Community development certificates"],
        internshipRequirements: "Volunteering extensively with grassroots art programs.",
        roadmap: ["Arts Volunteer", "Community Arts Coordinator", "Program Manager", "Director of Arts NGO"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Cultural Critic / Reviewer",
        description: "Analyze and critique cultural outputs—such as film, literature, music, and pop culture—exploring how they reflect broader societal trends and politics.",
        summary: "Writers identifying and analyzing deep societal trends within popular media and art.",
        skills: ["Analytical Writing", "Deep Cultural Knowledge", "Media Literacy", "Trend Forecasting", "Persuasive Argumentation"],
        salaryRange: "India: ₹3L - ₹15L | Global: $45K - $90K",
        educationPath: "B.A. Cultural Studies / Journalism / English",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Magazines (e.g., The New Yorker, The Atlantic)", "Digital Media Outlets", "Newspapers", "Publishing"],
        futureScope: "Evolving. Traditional print roles are shrinking, but independent commentators on platforms like Substack or YouTube are thriving.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "None.",
        freelanceOpportunities: "Maximum. Many top cultural critics are freelancers contributing to multiple publications.",
        fieldWork: "Low. Desk research, interviewing, and attending film/art screenings.",
        riskLevel: "Low",
        certifications: ["None specific."],
        internshipRequirements: "Writing for university papers or indie blogs.",
        roadmap: ["Freelance Blogger", "Staff Writer", "Senior Cultural Critic", "Author / Thought Leader"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Cross-Cultural Communications Consultant",
        description: "Train corporate executives, diplomats, or global teams to effectively communicate and negotiate across different cultural backgrounds and avoid faux pas.",
        summary: "Experts ensuring smooth, respectful, and effective communication between different global cultures.",
        skills: ["Intercultural Competence", "Corporate Training", "Psychology of Communication", "Foreign Languages", "Diplomacy"],
        salaryRange: "India: ₹6L - ₹20L | Global: $70K - $130K",
        educationPath: "B.A. Cultural Studies / IR → M.A. Intercultural Communication",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Multinational Corporations", "HR Consultancies", "Government Foreign Service Academies"],
        futureScope: "Extremely high demand as remote work and globalized teams make cross-cultural interaction a daily business reality.",
        jobDemandTrend: "Growing",
        governmentJobs: "Training diplomats in foreign service institutes.",
        freelanceOpportunities: "Maximum. Operating as independent executive coaches.",
        fieldWork: "Moderate. Traveling to conduct workshops at various corporate headquarters.",
        riskLevel: "Low",
        certifications: ["Intercultural Training Certifications"],
        internshipRequirements: "HR or international business internships.",
        roadmap: ["HR Assistant", "Intercultural Trainer", "Senior Consultant", "Global Diversity Officer"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Ethnographer (Corporate / Tech)",
        description: "Apply anthropological and cultural studies methods to the business world, observing how consumers interact with products, technology, and environments to drive UX and marketing.",
        summary: "Researchers studying human behavior to help companies design better products and services.",
        skills: ["Observational Research", "User Experience (UX) Basics", "Data Synthesis", "Corporate Strategy", "Empathy"],
        salaryRange: "India: ₹6L - ₹22L | Global: $80K - $140K",
        educationPath: "B.A. Cultural Studies / Anthropology → M.A. Applied Anthropology",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Tech Giants (Google, Intel, Meta)", "Design Agencies (IDEO)", "Market Research Firms"],
        futureScope: "Exploding field. Tech companies increasingly realize quantitative data isn't enough; they need qualitative 'thick data' to understand human context.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "High. Consulting for various product launches.",
        fieldWork: "Moderate. Conducting in-home interviews and field observations of consumers.",
        riskLevel: "Low",
        certifications: ["UX Research Certifications"],
        internshipRequirements: "UX Research or Market Research internships.",
        roadmap: ["Research Assistant", "UX Researcher / Ethnographer", "Senior Lead Researcher", "VP of Consumer Insights"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Media and Cultural Studies Researcher",
        description: "Academically investigate the intersection of media, technology, and culture, analyzing issues like algorithmic bias, online communities, and digital representation.",
        summary: "Academics analyzing how digital media and technology shape modern culture.",
        skills: ["Digital Sociology", "Media Theory", "Data Scraping/Analysis", "Critical Theory", "Academic Publishing"],
        salaryRange: "India: ₹5L - ₹15L | Global: $65K - $110K",
        educationPath: "M.A. Media Studies / Cultural Studies → Ph.D.",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Universities", "Technology Think Tanks", "Policy Institutes"],
        futureScope: "Highly relevant. We desperately need experts to understand the cultural impact of AI, social media, and digital polarization.",
        jobDemandTrend: "Growing (Academic/Think Tank)",
        governmentJobs: "Advising telecommunications or digital policy boards.",
        freelanceOpportunities: "Moderate. Writing for tech/culture publications.",
        fieldWork: "Low. Primarily desk-based, analyzing digital communities.",
        riskLevel: "Low",
        certifications: ["Ph.D. required for senior roles"],
        internshipRequirements: "Academic or think-tank research assistantships.",
        roadmap: ["Ph.D. Researcher", "Postdoctoral Fellow", "Think Tank Analyst / Professor", "Director of Media Institute"]
    },
    {
        domain: "Arts",
        branch: "Cultural Studies",
        title: "Indigenous Rights Advocate",
        description: "Work with indigenous communities to protect their land rights, cultural heritage, and languages, lobbying governments and navigating international human rights law.",
        summary: "Activists protecting the legal rights and cultural heritage of native populations.",
        skills: ["Indigenous Law Knowledge", "Advocacy", "Lobbying", "Cultural Sensitivity", "Community Organizing"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $90K",
        educationPath: "B.A. Cultural Studies / Anthropology → Law Degree or M.A. Public Policy",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Indigenous Tribal Councils", "Human Rights NGOs (Survival International)", "UN Permanent Forum on Indigenous Issues"],
        futureScope: "Critical, ongoing battle against land encroachment, linguistic extinction, and cultural assimilation globally.",
        jobDemandTrend: "Stable, Niche",
        governmentJobs: "Roles in federal departments of Indigenous/Aboriginal affairs.",
        freelanceOpportunities: "Moderate. Independent consulting for resource extraction companies on indigenous compliance.",
        fieldWork: "High. Traveling to remote tribal lands and reservations.",
        riskLevel: "Moderate (Navigating intense political and land-use conflicts)",
        certifications: ["None specific."],
        internshipRequirements: "Volunteering with indigenous rights organizations or legal clinics.",
        roadmap: ["Field Worker", "Policy Advocate", "Legal Counsel", "Director of Indigenous Affairs NGO"]
    }
];

const seedCulturalStudies = async () => {
    try {
        await Career.deleteMany({ branch: "Cultural Studies" });
        await Career.insertMany(culturalStudiesProfessions);
        console.log('Cultural Studies Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedCulturalStudies();
