const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const intlRelationsProfessions = [
    {
        domain: "Arts",
        branch: "International Relations",
        title: "International Service Officer (Diplomat)",
        description: "Represent the country's interests internationally, manage diplomatic relations, negotiate treaties, and assist citizens abroad.",
        summary: "Government representatives managing international diplomacy and foreign relations.",
        skills: ["Diplomacy", "Foreign Languages", "International Law", "Negotiation", "Cultural Sensitivity"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $70K - $160K+",
        educationPath: "B.A. Political Science / International Relations → Civil/Foreign Service Exams",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Ministry of External/Foreign Affairs", "Embassies", "Consulates"],
        futureScope: "Extremely prestigious. Essential for navigating complex global geopolitics and trade.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "Maximum. Direct government service.",
        freelanceOpportunities: "None.",
        fieldWork: "High. Frequent international postings and relocations.",
        riskLevel: "Moderate (Depends on global postings)",
        certifications: ["Foreign Service Examination"],
        internshipRequirements: "Language training and diplomatic probation.",
        roadmap: ["Foreign Service Exam", "Third Secretary", "Consul / First Secretary", "Ambassador / High Commissioner"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Intelligence Analyst",
        description: "Gather, analyze, and interpret intelligence data from multiple sources to assess foreign threats, political stability, and security risks.",
        summary: "Specialists who evaluate global information to advise on national security and foreign policy.",
        skills: ["Data Analysis", "Critical Thinking", "Geopolitical Knowledge", "Briefing", "Foreign Languages"],
        salaryRange: "India: ₹6L - ₹20L | Global: $70K - $130K",
        educationPath: "B.A. International Relations / Political Science → M.A. Security Studies",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["National Intelligence Agencies (RAW, CIA, MI6)", "Military Intelligence", "Private Security Firms"],
        futureScope: "Critical demand as global threats shift from conventional warfare to cyber and asymmetric warfare.",
        jobDemandTrend: "Growing (Security Sector)",
        governmentJobs: "Maximum. Mostly employed by national security apparatuses.",
        freelanceOpportunities: "Low. Highly classified work.",
        fieldWork: "Low to Moderate. Mostly desk analysis, but field assignments exist.",
        riskLevel: "Moderate to High (Handling classified material and operating in sensitive environments)",
        certifications: ["Security Clearances (Mandatory)"],
        internshipRequirements: "Internships within government defense or intelligence bodies.",
        roadmap: ["Junior Analyst", "Intelligence Analyst", "Senior Intelligence Officer", "Director of Intelligence"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "International Aid / Development Worker",
        description: "Design and implement relief programs in developing nations, focusing on healthcare, education, clean water, and disaster recovery.",
        summary: "Humanitarian professionals managing development projects in underserved global regions.",
        skills: ["Project Management", "Cross-Cultural Communication", "Adaptability", "Grant Writing", "Crisis Logistics"],
        salaryRange: "India: ₹5L - ₹15L | Global: $55K - $110K",
        educationPath: "B.A. International Relations → M.A. International Development",
        yearsOfStudy: "5 Years",
        industriesHiring: ["United Nations (UNDP, UNICEF)", "International NGOs (Oxfam, MSF)", "USAID"],
        futureScope: "Consistent need driven by global inequality, climate disasters, and conflict zones.",
        jobDemandTrend: "Stable, Highly Competitive",
        governmentJobs: "Roles in foreign aid departments of federal governments.",
        freelanceOpportunities: "Moderate. Contract consultants for specific global projects.",
        fieldWork: "Maximum. Extended deployments to developing nations or conflict zones.",
        riskLevel: "High (Potential exposure to disease, political unrest, and limited infrastructure)",
        certifications: ["Hostile Environment Awareness Training (HEAT)"],
        internshipRequirements: "Peace Corps, UN Volunteers, or overseas NGO experience.",
        roadmap: ["Field Volunteer/Intern", "Program Officer", "Country Director", "Head of International Agency"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Global Political Risk Analyst",
        description: "Assess and forecast the political and economic stability of foreign markets to advise multinational corporations on investment risks.",
        summary: "Consultants advising corporations on the financial risks of operating in varying global political climates.",
        skills: ["Economic Forecasting", "Geopolitical Analysis", "Risk Assessment", "Corporate Strategy", "Presentation Skills"],
        salaryRange: "India: ₹7L - ₹25L | Global: $80K - $150K",
        educationPath: "B.A. International Relations / Economics → M.A. International Political Economy",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Multinational Banks", "Risk Consultancies (Eurasia Group, Control Risks)", "Fortune 500 Companies"],
        futureScope: "Highly lucrative as businesses increasingly look to expand into emerging, volatile markets.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Low. Primarily a private-sector advisory role.",
        freelanceOpportunities: "High. Independent geopolitical consultants.",
        fieldWork: "Moderate. Traveling to assess market conditions firsthand.",
        riskLevel: "Low",
        certifications: ["Financial Risk Manager (FRM) is a plus"],
        internshipRequirements: "Internships with risk consultancies or private equity firms.",
        roadmap: ["Research Associate", "Political Risk Analyst", "Senior Consultant", "Partner / Director of Geopolitical Strategy"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "International Trade Economist",
        description: "Analyze international tariffs, trade agreements, and global market trends to influence national trade policies and corporate supply chains.",
        summary: "Economists specializing in the mechanics and policies of global commerce.",
        skills: ["Macroeconomics", "Data Analysis", "Trade Law Basics", "Statistical Modeling", "Policy Writing"],
        salaryRange: "India: ₹8L - ₹22L | Global: $85K - $140K",
        educationPath: "B.A. Economics / International Relations → Ph.D. or Master's in Economics",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["World Trade Organization (WTO)", "Ministry of Commerce", "Global Think Tanks"],
        futureScope: "Essential for navigating the increasingly complex web of international sanctions, tariffs, and trade wars.",
        jobDemandTrend: "Stable",
        governmentJobs: "Maximum. Leading trade negotiation teams and economic advisory boards.",
        freelanceOpportunities: "Moderate. Consultants for multinational logistics firms.",
        fieldWork: "Low. Desk research and attending global trade summits.",
        riskLevel: "Low",
        certifications: ["Advanced degrees are typically required"],
        internshipRequirements: "Research assistantships with economic institutes.",
        roadmap: ["Economic Researcher", "Trade Analyst", "Senior Trade Economist", "Chief Economist / Trade Representative"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Human Rights Lawyer/Advocate",
        description: "Investigate and document human rights abuses globally, advocating for policy changes or litigating in international courts.",
        summary: "Legal professionals advocating for justice and human rights on a global scale.",
        skills: ["International Law (IHL)", "Investigation", "Advocacy", "Public Speaking", "Persuasion"],
        salaryRange: "India: ₹5L - ₹18L | Global: $65K - $130K",
        educationPath: "B.A. International Relations / Pre-Law → J.D. / LL.B. with International Law focus",
        yearsOfStudy: "6 to 7 Years",
        industriesHiring: ["Amnesty International", "Human Rights Watch", "International Criminal Court (ICC)", "UNHCR"],
        futureScope: "A difficult but highly respected field, dealing with war crimes, asylum seekers, and systemic abuses.",
        jobDemandTrend: "Competitive, Passion-Driven",
        governmentJobs: "Roles in foreign affairs human rights desks.",
        freelanceOpportunities: "Moderate. Legal consulting for various NGOs.",
        fieldWork: "High. Collecting testimonies in conflict zones or refugee camps.",
        riskLevel: "High (Potential threats when investigating state-sponsored abuses or war crimes)",
        certifications: ["Bar Association Admittance in relevant jurisdictions"],
        internshipRequirements: "Clerking for international tribunals or human rights NGOs.",
        roadmap: ["Legal Researcher", "Staff Attorney (NGO)", "Senior Human Rights Lawyer", "Director of Legal Advocacy"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Immigration / Asylum Officer",
        description: "Interview applicants and review documentation to determine eligibility for asylum, refugee status, or citizenship based on international and domestic laws.",
        summary: "Government officials adjudicating claims for immigration, asylum, and citizenship.",
        skills: ["Interviewing", "Legal Evaluation", "Cultural Competence", "Trauma-Informed Questioning", "Attention to Detail"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $100K",
        educationPath: "B.A. International Relations / Political Science",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Federal Immigration Departments", "Border Agencies", "UN Refugee Agency"],
        futureScope: "Constant high demand due to ongoing global migration crises and border management policies.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Maximum. Direct federal employment.",
        freelanceOpportunities: "None.",
        fieldWork: "Moderate. Operating out of embassies, borders, or refugee processing centers.",
        riskLevel: "Moderate (High emotional stress, fast-paced decision making)",
        certifications: ["Government agency training clearances"],
        internshipRequirements: "Internships with immigrant advocacy groups or government agencies.",
        roadmap: ["Asylum Assistant", "Asylum Officer", "Supervisory Officer", "Director of Refugee Affairs"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Foreign Correspondent / International Journalist",
        description: "Report on international news, conflicts, and global politics while stationed in foreign bureaus, translating complex global events for domestic audiences.",
        summary: "Journalists reporting directly from foreign nations and conflict zones.",
        skills: ["Investigative Journalism", "Foreign Languages", "Risk Assessment", "Rapid Reporting", "Networking"],
        salaryRange: "India: ₹6L - ₹20L | Global: $55K - $120K",
        educationPath: "B.A. Journalism / International Relations → M.A. Global Journalism",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Major News Networks (CNN, BBC, Al Jazeera)", "Wire Services (Reuters, AP)"],
        futureScope: "Shrinking staff positions due to media budget cuts, but crucial for accurate global reporting.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "None. Must remain independent of state influence.",
        freelanceOpportunities: "High. Many act as 'stringers' supplying to multiple news outlets.",
        fieldWork: "Maximum. Entirely based in foreign countries, often conflict zones.",
        riskLevel: "Very High (Operating in war zones, dictatorships, and facing potential censorship or arrest)",
        certifications: ["Hostile Environment Training"],
        internshipRequirements: "Extensive local journalism experience before foreign deployment.",
        roadmap: ["Local Reporter", "Foreign Desk Editor", "Foreign Correspondent", "Bureau Chief"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Non-Proliferation / Arms Control Analyst",
        description: "Monitor and verify compliance with international treaties regarding nuclear, biological, and chemical weapons, working to prevent global arms races.",
        summary: "Security experts striving to prevent the spread of weapons of mass destruction.",
        skills: ["Technical Literacy (Physics/Chemistry basics)", "Treaty Law", "Negotiation", "Data Analysis", "Attention to Detail"],
        salaryRange: "India: ₹7L - ₹25L | Global: $80K - $130K",
        educationPath: "B.A. International Relations / Physics → M.A. Security Studies",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["IAEA (International Atomic Energy Agency)", "UN", "National Defense Departments", "Security Think Tanks"],
        futureScope: "Niche but absolutely critical for global survival as geopolitical tensions rise.",
        jobDemandTrend: "Stable, Niche",
        governmentJobs: "High. Employed by nuclear regulatory boards and defense ministries.",
        freelanceOpportunities: "Low. Highly secure, classified environments.",
        fieldWork: "Moderate. Inspecting nuclear facilities globally.",
        riskLevel: "Moderate (Political pressure, potential exposure risks depending on the facility)",
        certifications: ["UN or Defense Clearances"],
        internshipRequirements: "Research assistantships in defense think tanks.",
        roadmap: ["Research Assistant", "Arms Control Analyst", "Senior Inspector", "Director of Non-Proliferation Policy"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "International Business Consultant",
        description: "Guide companies through the legal, cultural, and logistical challenges of expanding their operations into foreign markets.",
        summary: "Experts assisting corporations in successfully expanding across global borders.",
        skills: ["Cross-Cultural Management", "Market Research", "Supply Chain Logistics", "Business Strategy", "Foreign Languages"],
        salaryRange: "India: ₹8L - ₹30L+ | Global: $85K - $160K+",
        educationPath: "B.A. International Relations / MBA in International Business",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Management Consulting Firms (McKinsey, BCG)", "Big 4 Accounting", "Multinational Corporations"],
        futureScope: "Very high demand as mid-sized companies attempt to globalize.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Roles in state commerce departments promoting exports.",
        freelanceOpportunities: "High. Independent cross-border consultants.",
        fieldWork: "High. Frequent international travel to client sites.",
        riskLevel: "Low",
        certifications: ["Certified Global Business Professional (CGBP)"],
        internshipRequirements: "Internships at major consulting or multinational firms.",
        roadmap: ["Business Analyst", "International Consultant", "Engagement Manager", "Partner"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Diplomatic Interpreter / Translator",
        description: "Provide real-time, highly accurate translation of spoken or written word between diplomats, world leaders, and at international summits.",
        summary: "Language experts ensuring precise communication in high-stakes international diplomacy.",
        skills: ["Impeccable Fluency (Multiple Languages)", "Rapid Processing", "Cultural Nuance", "Absolute Confidentiality", "Stress Tolerance"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $110K",
        educationPath: "B.A. Foreign Languages / IR → M.A. Interpretation",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["United Nations", "Embassies", "European Union", "Global Summits (G20, etc.)"],
        futureScope: "Despite AI advancements, high-stakes diplomacy requires human interpreters to capture tone, nuance, and intent flawlessly.",
        jobDemandTrend: "Stable, Highly Competitive",
        governmentJobs: "High. Employed directly by foreign ministries.",
        freelanceOpportunities: "Maximum. Many operate on highly paid daily contracts for specific summits.",
        fieldWork: "High. Traveling to international summits alongside leaders.",
        riskLevel: "Low (High stress environment)",
        certifications: ["UN Language Competitive Examination (LCE)"],
        internshipRequirements: "Extensive language immersion and shadowing senior interpreters.",
        roadmap: ["Junior Translator", "Simultaneous Interpreter", "Senior Diplomatic Interpreter", "Chief of Languages (UN)"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Cultural Attaché",
        description: "Promote their home country's arts, education, and culture in a foreign nation, organizing events, exchange programs, and cultural diplomacy initiatives.",
        summary: "Diplomats specialized in fostering international goodwill through art, education, and culture.",
        skills: ["Event Organization", "Public Relations", "Cultural Knowledge", "Networking", "Foreign Languages"],
        salaryRange: "India: ₹7L - ₹20L | Global: $65K - $120K",
        educationPath: "B.A. International Relations / Cultural Studies → Foreign Service Exams",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Embassies", "Consulates", "Ministry of Culture/External Affairs"],
        futureScope: "Vital 'soft power' approach to diplomacy, maintaining relations when political tensions rise.",
        jobDemandTrend: "Stable",
        governmentJobs: "Maximum. A specialized diplomatic role.",
        freelanceOpportunities: "None. Official government representatives.",
        fieldWork: "Moderate. Operating out of embassies and hosting local events.",
        riskLevel: "Low",
        certifications: ["Diplomatic Service Clearance"],
        internshipRequirements: "Working with international cultural institutes (Alliance Française, Goethe-Institut, etc.).",
        roadmap: ["Cultural Assistant", "Cultural Attaché", "Senior Public Diplomacy Officer", "Ambassador"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Climate Change Policy Advisor",
        description: "Advise governments and international bodies on environmental treaties (like the Paris Agreement), negotiating global standards for emissions and sustainability.",
        summary: "Experts negotiating international environmental regulations and climate treaties.",
        skills: ["Environmental Science Basics", "Treaty Negotiation", "Policy Drafting", "Diplomacy", "Economic Impact Analysis"],
        salaryRange: "India: ₹6L - ₹20L | Global: $70K - $130K",
        educationPath: "B.A. IR / Environmental Science → M.A. Environmental Policy",
        yearsOfStudy: "5 Years",
        industriesHiring: ["UNEP (UN Environment Programme)", "Ministries of Environment", "Global Environmental NGOs"],
        futureScope: "The fastest-growing subset of international relations, as climate change becomes the dominant global security threat.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High. Advising national leaders at global climate summits (COP).",
        freelanceOpportunities: "Moderate. Environmental consultants.",
        fieldWork: "Moderate. Attending global environmental summits.",
        riskLevel: "Low",
        certifications: ["Sustainability / Environmental Law Certifications"],
        internshipRequirements: "Working with environmental lobbies or NGOs.",
        roadmap: ["Policy Researcher", "Climate Policy Advisor", "Chief Negotiator", "Director of International Environmental Affairs"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Global Supply Chain Manager",
        description: "Coordinate the international sourcing, manufacturing, and distribution of goods, navigating customs, tariffs, and geopolitical disruptions.",
        summary: "Logistics experts managing the complex web of global manufacturing and trade.",
        skills: ["Logistics", "Risk Management", "Vendor Negotiation", "Understanding Trade Laws", "Crisis Logistics"],
        salaryRange: "India: ₹8L - ₹25L | Global: $80K - $140K",
        educationPath: "B.A. IR / Business → M.S. Supply Chain Management",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Multinational Manufacturing", "Global Retail (Amazon, Walmart)", "Shipping Conglomerates"],
        futureScope: "Critical role. Recent global events have proven that securing international supply chains is vital for corporate survival.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Logistics roles within defense or disaster relief agencies.",
        freelanceOpportunities: "Moderate. Supply chain resiliency consultants.",
        fieldWork: "Moderate. Traveling to inspect international manufacturing facilities and ports.",
        riskLevel: "Low",
        certifications: ["Certified Supply Chain Professional (CSCP)"],
        internshipRequirements: "Corporate internships in procurement or logistics.",
        roadmap: ["Logistics Coordinator", "Supply Chain Analyst", "Global Supply Chain Manager", "VP of Supply Chain"]
    },
    {
        domain: "Arts",
        branch: "International Relations",
        title: "Refugee Resettlement Coordinator",
        description: "Manage the logistics, legal paperwork, and social integration of refugees arriving in a new host country.",
        summary: "Advocates helping displaced populations settle and integrate into new societies.",
        skills: ["Casework Management", "Empathy", "Cultural Competence", "Trauma-Informed Care", "Language Skills"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $80K",
        educationPath: "B.A. International Relations / Social Work",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["UNHCR", "Refugee NGOs (IRC, Catholic Charities)", "State Immigration Departments"],
        futureScope: "Persistent demand driven by ongoing global conflicts causing mass displacement.",
        jobDemandTrend: "Stable, High Need",
        governmentJobs: "Roles in local offices of refugee resettlement.",
        freelanceOpportunities: "Low. Highly institutionalized.",
        fieldWork: "High. Working at processing centers, airports, and refugee homes.",
        riskLevel: "Low (High emotional stress and burnout rates)",
        certifications: ["Cross-cultural counseling certificates"],
        internshipRequirements: "Volunteering with immigrant or refugee aid programs.",
        roadmap: ["Caseworker", "Resettlement Coordinator", "Program Director", "Head of Refugee Services"]
    }
];

const seedIntlRelations = async () => {
    try {
        await Career.deleteMany({ branch: "International Relations" });
        await Career.insertMany(intlRelationsProfessions);
        console.log('International Relations Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedIntlRelations();
