const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const internationalBusinessProfessions = [
    {
        domain: "Commerce",
        branch: "International Business",
        title: "International Business Manager (Global)",
        description: "International Business Managers oversee their company's global operations, ensuring that international branches align with the corporate strategy. They adapt products, marketing, and business practices to fit various cultural, legal, and economic environments.",
        skills: ["Cross-Cultural Management", "Global Strategy", "Negotiation", "Financial Planning", "Market Adaptation"],
        salaryRange: "India: ₹15 LPA - ₹40+ LPA | Global: $90,000 - $180,000+ per year",
        educationPath: "BBA/B.Com / B.Tech -> MBA in International Business (Highly Preferred)",
        futureScope: "As companies scale, their growth inevitably hits national ceilings. Executives who can successfully navigate the complexities of foreign expansion are among the highest-valued leaders in the corporate world.",
        roadmap: [
            "Executive: International Business Analyst / Coordinator",
            "Manager: Country/Regional Manager",
            "Senior Manager: Director of International Operations",
            "Director: VP of Global Strategy",
            "Global Head: Chief Operations Officer (Global) / CEO"
        ],
        certifications: ["Certified Global Business Professional (CGBP)", "PMP"],
        summary: "An elite, highly strategic leadership role driving a company's financial and operational success across multiple continents.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Tech MNCs", "FMCG", "Automotive", "Pharmaceuticals", "Consulting"],
        jobDemandTrend: "High",
        governmentJobs: "Advisory roles in Ministry of Commerce and Industry.",
        competitiveExams: ["IIFT (for MBA IB)"],
        privateSectorOpportunities: "The primary leadership role in any multinational corporation (MNC) expanding aggressively.",
        internationalJobOpportunities: "Extremely high. This role inherently involves managing or relocating to foreign HQs.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Global expansion consulting for scaling mid-sized businesses.",
        licenseRequired: "None",
        riskLevel: "Moderate (High stakes decision making)"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Export Manager",
        description: "Export Managers are responsible for selling a company's products in foreign markets. They handle international client relationships, negotiate global sales contracts, and coordinate with logistics teams to ensure smooth outbound shipping and customs compliance.",
        skills: ["International Sales", "Export Regulations", "Incoterms", "Client Relationship Management", "Trade Finance"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $75,000 - $130,000 per year",
        educationPath: "BBA/B.Com -> Diploma/MBA in Export-Import Management",
        futureScope: "A critical revenue-generating role for manufacturing nations. India's push to become a global manufacturing hub significantly relies on expert export managers.",
        roadmap: [
            "Executive: Export Executive / Documentation Specialist",
            "Manager: Export Manager",
            "Senior Manager: Regional Export Head",
            "Director: VP of International Sales",
            "Global Head: Chief Revenue Officer"
        ],
        certifications: ["Diploma in Export & Import Management (IIFT)"],
        summary: "A sales-driven, highly technical role focused on maximizing outbound global revenue while navigating complex international trade laws.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Manufacturing", "Agriculture", "Textiles", "Pharmaceuticals", "Engineering Goods"],
        jobDemandTrend: "High",
        governmentJobs: "Export Promotion Councils (e.g., FIEO, APEDA).",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Vital for any mid-to-large scale manufacturing company looking beyond domestic markets.",
        internationalJobOpportunities: "High travel requirement to meet foreign distributors and attend global trade fairs.",
        remoteWorkPossibilities: "Low",
        freelanceOpportunities: "Independent Export Consultant / Commission Agent.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Import Manager",
        description: "Import Managers oversee the purchasing and inward logistics of raw materials or finished goods from foreign suppliers. They source international vendors, negotiate global procurement contracts, and ensure incoming goods clear customs efficiently and cost-effectively.",
        skills: ["Global Sourcing", "Vendor Negotiation", "Customs Regulations", "Supply Chain Optimization", "Foreign Exchange Management"],
        salaryRange: "India: ₹7 LPA - ₹22 LPA | Global: $70,000 - $125,000 per year",
        educationPath: "BBA/B.Com / Engineering -> PGD in Supply Chain / MBA Operations",
        futureScope: "In an interconnected world, very few products are entirely made domestically. Import managers ensure supply chains remain resilient and cost-effective despite global disruptions.",
        roadmap: [
            "Executive: Import Coordinator / Procurement Executive",
            "Manager: Import Manager",
            "Senior Manager: Head of Global Sourcing",
            "Director: VP of Procurement",
            "Global Head: Chief Supply Chain Officer (CSCO)"
        ],
        certifications: ["Certified Supply Chain Professional (CSCP)"],
        summary: "A pivotal operations role focused on strategic cost-saving, global vendor relationships, and ensuring uninterrupted inbound raw material flows.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Retail", "Electronics assembly", "Automotive", "E-commerce giants", "Wholesale Distributors"],
        jobDemandTrend: "Stable",
        governmentJobs: "Roles in state trading corporations.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Crucial in retail and manufacturing sectors heavily reliant on global raw materials.",
        internationalJobOpportunities: "Frequent travel to foreign manufacturing hubs (e.g., China, Vietnam, Germany) to vet suppliers.",
        remoteWorkPossibilities: "Low",
        freelanceOpportunities: "Sourcing agent for local D2C brands.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Global Supply Chain Manager (International)",
        description: "Global Supply Chain Managers design and control the entire flow of goods, from raw material extraction globally to the final consumer. They optimize multi-national manufacturing, warehousing, and transportation to maximize efficiency and minimize cost.",
        skills: ["End-to-end Logistics", "Demand Forecasting", "ERP Systems (SAP)", "Risk Management", "Data Analytics"],
        salaryRange: "India: ₹12 LPA - ₹35+ LPA | Global: $90,000 - $160,000+ per year",
        educationPath: "B.Tech/BBA -> MBA in Supply Chain Management / Operations",
        futureScope: "Recent global events (pandemics, canal blockages) highlighted the fragility of global supply chains. Experts who can build resilient, agile, data-driven supply networks are in extreme demand.",
        roadmap: [
            "Executive: Supply Chain Analyst",
            "Manager: Global Supply Chain Manager",
            "Senior Manager: Director of Supply Chain",
            "Director: VP Global Logistics",
            "Global Head: Chief Supply Chain Officer (CSCO)"
        ],
        certifications: ["APICS Certified in Production and Inventory Management (CPIM)", "CSCP"],
        summary: "The grand architects of physical commerce, orchestrating the movement of resources across the planet efficiently and cost-effectively.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Amazon/E-commerce", "FMCG", "Tech Hardware (Apple, Dell)", "Automotive", "Pharmaceuticals"],
        jobDemandTrend: "Very High",
        governmentJobs: "Logistics infrastructure planning roles (e.g., PM Gati Shakti).",
        competitiveExams: ["CAT (for MBA)"],
        privateSectorOpportunities: "The backbone role of any globally distributed manufacturing or retail empire.",
        internationalJobOpportunities: "Managing supply control towers in global hubs (Singapore, Dubai, Rotterdam).",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Supply chain optimization consulting for mid-sized manufacturers.",
        licenseRequired: "None",
        riskLevel: "Moderate (Managing massive financial physical risks)"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "International Trade Analyst (Business)",
        description: "International Trade Analysts within corporations monitor global market trends, tariffs, trade agreements, and geopolitical shifts. They advise corporate leadership on which foreign markets to enter, exit, or avoid based on economic risk.",
        skills: ["Market Research", "Geopolitical Analysis", "Tariff & Tax Knowledge", "Strategic Forecasting", "Data Interpretation"],
        salaryRange: "India: ₹8 LPA - ₹20 LPA | Global: $75,000 - $130,000 per year",
        educationPath: "B.A/B.Sc Economics / BBA -> M.A International Economics / MBA IB",
        futureScope: "As the world fragments into competing economic blocs, companies need analysts to navigate tariffs, sanctions, and complex trade wars to protect their bottom line.",
        roadmap: [
            "Executive: Junior Trade Analyst",
            "Manager: International Trade Analyst",
            "Senior Manager: Senior Market Strategist",
            "Director: Director of Global Market Intelligence",
            "Global Head: Chief Strategy Officer"
        ],
        certifications: ["Certified International Trade Professional (CITP)"],
        summary: "The intelligence-gathering wing of global business, predicting where the company should move its money and operations next.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Management Consulting (MBB)", "Tech Hardware", "Energy/Oil & Gas", "Financial Services"],
        jobDemandTrend: "High",
        governmentJobs: "Advisory roles in Ministry of Commerce.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Strategic roles in top-tier consulting firms advising Fortune 500 companies on global expansion.",
        internationalJobOpportunities: "High demand in global financial capitals and global corporate HQs.",
        remoteWorkPossibilities: "Moderate to High",
        freelanceOpportunities: "Independent market entry consulting.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Foreign Trade Officer (Corporate)",
        description: "Foreign Trade Officers in the corporate sector ensure that a company maximizes the benefits of government export-import policies. They claim government incentives, manage duty drawbacks, and handle complex licensing specifically for EXIM operations.",
        skills: ["Foreign Trade Policy (FTP)", "Documentation (DGFT)", "Liaisoning", "Regulatory Compliance", "Incentive Calculation"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: N/A (Highly region-specific)",
        educationPath: "B.Com / BBA -> Diploma in Foreign Trade / Exim Management",
        futureScope: "Governments constantly tweak trade policies to boost local manufacturing. Experts who can perfectly navigate these bureaucratic systems save companies millions in taxes and duties.",
        roadmap: [
            "Executive: EXIM Executive",
            "Manager: Foreign Trade Officer / Manager",
            "Senior Manager: General Manager - Commercial & EXIM",
            "Director: VP Commercial",
            "Global Head: Head of Trade & Customs"
        ],
        certifications: ["Diploma in EXIM Management"],
        summary: "A highly specialized, compliance-heavy role acting as the bridge between corporate export/import operations and complex government trade policies.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Manufacturing", "Pharmaceuticals", "Textiles", "Agro-chemicals", "Trading Houses"],
        jobDemandTrend: "Stable",
        governmentJobs: "Equivalent roles exist in DGFT (Directorate General of Foreign Trade) via government exams.",
        competitiveExams: ["None (for corporate role)"],
        privateSectorOpportunities: "Essential for any large-scale exporter looking to optimize profit margins via government schemes.",
        internationalJobOpportunities: "Low. This role requires hyper-specialized knowledge of domestic government policies.",
        remoteWorkPossibilities: "Low (Requires physical liaisoning with government departments)",
        freelanceOpportunities: "Consultant acting on behalf of smaller exporters to claim benefits.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "International Marketing Manager",
        description: "International Marketing Managers adapt a company's marketing strategy to fit foreign cultures and consumer behaviors. A successful ad campaign in the US might fail in Japan; they ensure brand messaging is culturally relevant, legally compliant, and effective globally.",
        skills: ["Cultural Intelligence", "Global Brand Strategy", "Market Localization", "Consumer Psychology", "Multi-regional Campaign Management"],
        salaryRange: "India: ₹12 LPA - ₹30 LPA | Global: $85,000 - $150,000 per year",
        educationPath: "BBA/B.Com / BA -> MBA International Marketing",
        futureScope: "Localization is the new globalization. Consumers want global products that feel inherently local. This role is fundamental to achieving that emotional brand connection worldwide.",
        roadmap: [
            "Executive: Global Marketing Coordinator",
            "Manager: International Marketing Manager",
            "Senior Manager: Regional Marketing Director (e.g., APAC, EMEA)",
            "Director: VP of Global Marketing",
            "Global Head: Global Chief Marketing Officer (CMO)"
        ],
        certifications: ["None strictly required; experience matters more."],
        summary: "A highly creative and strategic role tasked with navigating cultural nuances to sell a single brand to entirely different civilizations.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["FMCG", "Consumer Tech", "Entertainment/Streaming (Netflix, Disney)", "Fashion", "Automotive"],
        jobDemandTrend: "High",
        governmentJobs: "Tourism boards promoting the country internationally (e.g., Incredible India).",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Prestigious roles in global brand HQs dictating strategy for local regional offices.",
        internationalJobOpportunities: "High. Often based in regional hubs (e.g., managing 'EMEA' from London or 'APAC' from Singapore).",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Localization consulting for startups entering specific foreign markets.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Logistics & Distribution Manager (International)",
        description: "Logistics Managers focus specifically on the physical movement and storage of goods internationally. They negotiate with shipping lines, airlines, and 3PL (Third Party Logistics) providers to ensure cargo moves across borders safely and on time.",
        skills: ["Freight Forwarding", "Warehouse Management", "Route Optimization", "Vendor Negotiation", "Inventory Control"],
        salaryRange: "India: ₹8 LPA - ₹22 LPA | Global: $70,000 - $120,000 per year",
        educationPath: "BBA/B.Com / B.Tech -> MBA in Logistics/Operations",
        futureScope: "With the explosion of global e-commerce, the physical infrastructure to move boxes efficiently is strained. Logistics experts who can streamline distribution are critical to e-commerce survival.",
        roadmap: [
            "Executive: Logistics Coordinator",
            "Manager: Global Logistics Manager",
            "Senior Manager: Director of Distribution",
            "Director: VP of Logistics",
            "Global Head: Chief Operating Officer (COO)"
        ],
        certifications: ["Certified in Logistics, Transportation and Distribution (CLTD)"],
        summary: "The tactical executor of global trade, dealing strictly with ships, planes, trucks, warehouses, and the fastest way to connect them.",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Logistics Giants (Maersk, DHL, FedEx)", "E-commerce", "Retail", "Manufacturing"],
        jobDemandTrend: "Very High",
        governmentJobs: "Port Trusts, Railways, and national logistics planning.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Core operations roles turning strategic supply chain plans into physical reality.",
        internationalJobOpportunities: "High demand in global transit hubs and mega-ports.",
        remoteWorkPossibilities: "Low to Moderate",
        freelanceOpportunities: "Logistics consulting for smaller D2C brands.",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Global Procurement Manager",
        description: "While Import Managers handle the inward flow, Global Procurement Managers (or Sourcing Managers) are strictly responsible for finding the best suppliers globally, negotiating massive bulk contracts, and ensuring ethical sourcing standards.",
        skills: ["Strategic Sourcing", "Contract Negotiation", "Vendor Risk Management", "Spend Analysis", "Knowledge of Commodities"],
        salaryRange: "India: ₹10 LPA - ₹28 LPA | Global: $80,000 - $140,000 per year",
        educationPath: "B.Tech / BBA -> MBA Supply Chain / Procurement",
        futureScope: "Companies compete primarily on cost and quality. Procurement managers directly impact the bottom line by securing the cheapest, highest-quality materials globally before manufacturing even begins.",
        roadmap: [
            "Executive: Buyer / Sourcing Analyst",
            "Manager: Global Procurement Manager",
            "Senior Manager: Category Director",
            "Director: VP Global Sourcing",
            "Global Head: Chief Procurement Officer (CPO)"
        ],
        certifications: ["Certified Professional in Supply Management (CPSM)"],
        summary: "The ultimate corporate buyer, traveling the globe to negotiate multi-million dollar contracts for the materials that build a company's products.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Tech Hardware", "Apparel/Fashion", "Automotive", "Construction", "FMCG"],
        jobDemandTrend: "Stable",
        governmentJobs: "Public procurement roles (e.g., GeM portal management).",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Highly strategic roles in manufacturing HQs.",
        internationalJobOpportunities: "Heavy travel to industrial hubs across Asia, Europe, and Latin America to audit factories.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Independent sourcing agent connecting western buyers with eastern factories.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Trade Compliance Officer",
        description: "Trade Compliance Officers ensure a company's international transactions are entirely legal. They interpret complex international laws (sanctions, dual-use goods, anti-bribery laws) to ensure the company doesn't accidentally violate severe international treaties.",
        skills: ["International Trade Law", "Auditing", "Attention to Detail", "Risk Assessment", "Export Controls (e.g., ITAR, EAR)"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $85,000 - $145,000 per year",
        educationPath: "LLB / B.Com / BBA -> Specialized Certifications in Global Trade Law",
        futureScope: "As geopolitical tensions rise, sanctions and trade restrictions are multiplying. A single compliance failure can result in billion-dollar fines or executive arrests, making this role critically indispensable.",
        roadmap: [
            "Executive: Compliance Analyst",
            "Manager: Trade Compliance Officer / Manager",
            "Senior Manager: Director of Global Trade Compliance",
            "Director: VP Trade Compliance",
            "Global Head: Chief Compliance Officer (CCO)"
        ],
        certifications: ["Certified U.S. Export Compliance Officer (CUSECO) - if dealing with US trade"],
        summary: "The strict legal guardians of global business, preventing corporations from accidentally funding embargoed nations or violating international treaties.",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Aerospace & Defense", "Tech Hardware", "Banking/Finance", "Energy", "Pharmaceuticals"],
        jobDemandTrend: "High",
        governmentJobs: "Customs and regulatory bodies.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Vital for any multinational dealing in sensitive technology, massive financial flows, or defense.",
        internationalJobOpportunities: "Global compliance overview roles based in corporate HQs.",
        remoteWorkPossibilities: "High",
        freelanceOpportunities: "Compliance consulting for mid-sized firms expanding internationally.",
        licenseRequired: "None",
        riskLevel: "High (High legal responsibility)"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Customs Clearance Specialist",
        description: "Customs Clearance Specialists (or Licensed Customs Brokers) specialized solely in the hyper-complex paperwork and legalities required to get physical cargo across a specific national border rapidly without detainment or fines.",
        skills: ["HSN Classification", "Customs Valuation", "Tariff Calculations", "Liaisoning with Customs Officials", "Document Preparation"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $95,000 per year",
        educationPath: "Any Bachelor's Degree -> Passed National Customs Broker Exam (Rule 6 Examination in India)",
        futureScope: "Despite increasing automation, the physical border crossing of goods requires human legal accountability and deep operational knowledge of local port bureaucracy.",
        roadmap: [
            "Executive: Documentation Clerk / Field Executive",
            "Manager: Licensed Customs Broker (CHA)",
            "Senior Manager: Head of Customs Operations",
            "Director: Branch Manager (Logistics Firm)",
            "Global Head: Owner / Partner of Customs Agency"
        ],
        certifications: ["Customs Broker License (Issued by Government of India / Respective Nation)"],
        summary: "A highly operational, legally certified specialist responsible for physically unlocking borders for international cargo.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Customs House Agents (CHAs)", "Freight Forwarders (DHL, Kuehne+Nagel)", "Large Exporters/Importers"],
        jobDemandTrend: "Stable",
        governmentJobs: "Customs Inspector (via SSC/UPSC).",
        competitiveExams: ["Rule 6 Exam under Customs Broker Licensing Regulations (CBLR)"],
        privateSectorOpportunities: "Core operations roles in any international logistics company.",
        internationalJobOpportunities: "Low. This is a hyper-localized skill specific to the laws of one country.",
        remoteWorkPossibilities: "Low (Requires physical presence at ports/customs offices)",
        freelanceOpportunities: "Running an independent Customs Brokerage firm.",
        licenseRequired: "Customs Broker License (Mandatory for signing off documents)",
        riskLevel: "Moderate (Fines for misclassification)"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "International Sales Manager",
        description: "International Sales Managers build out B2B revenue channels in foreign territories. They identify foreign distributors, hire local sales teams, pitch to massive foreign clients, and localize the sales playbook for different cultures.",
        skills: ["B2B Enterprise Sales", "Cross-Cultural Communication", "Pipeline Management", "Contract Negotiation", "Strategic Partnerships"],
        salaryRange: "India: ₹12 LPA - ₹35+ LPA | Global: $90,000 - $160,000+ per year (Highly commission-driven)",
        educationPath: "BBA / B.Tech / B.Com -> MBA in Marketing/IB -> Proven Sales Experience",
        futureScope: "The spearhead of global expansion. While marketing generates awareness, these managers are responsible for closing the massive international contracts that actually generate corporate revenue.",
        roadmap: [
            "Executive: International Business Development Executive",
            "Manager: International Sales Manager",
            "Senior Manager: Regional Sales Director (e.g., EMEA Sales Head)",
            "Director: VP of Global Sales",
            "Global Head: Chief Revenue Officer (CRO)"
        ],
        certifications: ["None strictly required; track record is everything."],
        summary: "A high-octane, high-reward role focused on traveling the globe to close massive B2B contracts and build foreign revenue streams.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["SaaS / Tech", "Manufacturing", "Pharmaceuticals", "B2B Services", "Consulting"],
        jobDemandTrend: "Very High",
        governmentJobs: "None.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "The highest paying roles in global B2B expansion.",
        internationalJobOpportunities: "Extremely high. Heavy travel or permanent relocation to target markets is standard.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Independent sales agents working on commission for multiple foreign brands.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Cross-Border E-Commerce Manager",
        description: "Cross-Border E-Commerce Managers specialize in selling consumer goods directly to foreign customers via platforms like Amazon Global Selling, Shopify, or Alibaba. They manage international digital storefronts, cross-border shipping, and localized digital marketing.",
        skills: ["Amazon FBA Global", "Digital Marketing", "International Payment Gateways", "Global Logistics (D2C)", "Data Analytics"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $70,000 - $120,000 per year",
        educationPath: "BBA / B.Com -> Experience in Digital Marketing & E-commerce Operations",
        futureScope: "The fastest-growing segment of international trade. Direct-to-consumer (D2C) brands no longer need massive distribution networks to sell globally, they just need experts who understand global e-commerce algorithms and cross-border shipping.",
        roadmap: [
            "Executive: E-Commerce Executive",
            "Manager: Cross-Border E-Commerce Manager",
            "Senior Manager: Head of Global D2C",
            "Director: VP of E-Commerce",
            "Global Head: Chief Digital Officer"
        ],
        certifications: ["Amazon Global Selling Certifications, Digital Marketing Certificates"],
        summary: "A modern, highly digital role enabling small and large brands to sell their products directly to consumers anywhere in the world.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["D2C Brands", "E-commerce Aggregators (Thrasio models)", "Fashion", "Handicrafts", "Electronics"],
        jobDemandTrend: "Very High",
        governmentJobs: "None.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "At the forefront of modern retail expansion strategy.",
        internationalJobOpportunities: "Managing global digital storefronts, often from a central HQ.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "Consultants helping local brands list and sell on international Amazon marketplaces.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "Global Operations Manager (International)",
        description: "Global Operations Managers focus on the efficiency of the internal workings of a multinational company. They standardize processes, IT systems, HR policies, and production standards across all international offices to ensure a unified, efficient global machine.",
        skills: ["Process Optimization (Six Sigma)", "Project Management", "Change Management", "Data Analytics", "Cross-functional Leadership"],
        salaryRange: "India: ₹12 LPA - ₹35 LPA | Global: $85,000 - $150,000 per year",
        educationPath: "B.Tech / BBA -> MBA in Operations / General Management",
        futureScope: "As companies scale globally, they tend to become fragmented and inefficient. Operations leaders who can deploy AI and standardized processes across continents reduce massive overhead costs.",
        roadmap: [
            "Executive: Operations Analyst",
            "Manager: Global Operations Manager",
            "Senior Manager: Director of Global Operations",
            "Director: VP Operations",
            "Global Head: Chief Operating Officer (COO)"
        ],
        certifications: ["Six Sigma Black Belt", "PMP"],
        summary: "The internal engine tuners of a multinational corporation, ensuring extreme efficiency and standardization across all global offices and factories.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["IT Services / BPO", "Manufacturing", "Tech MNCs", "Global Financial Institutions"],
        jobDemandTrend: "Stable",
        governmentJobs: "None.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Critical roles in ensuring profitability at a massive global scale.",
        internationalJobOpportunities: "Relocation to regional operational hubs to standardize new acquisitions or offices.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Process optimization consulting for scaling businesses.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "International Business",
        title: "International Business Consultant (Global Advisory)",
        description: "International Business Consultants work for advisory firms (like McKinsey, BCG, Bain) helping massive corporations solve their most difficult global problems. They advise on foreign market entry, global mergers and acquisitions (M&A), and international restructuring.",
        skills: ["Advanced Problem Solving", "Financial Modeling", "Executive Communication", "Market Sizing", "Rapid Learning"],
        salaryRange: "India: ₹15 LPA - ₹40+ LPA | Global: $100,000 - $200,000+ per year",
        educationPath: "Top-tier B.Tech / B.A Economics -> MBA from a Premier Institute (IIMs, Ivy League, INSEAD)",
        futureScope: "The absolute pinnacle of corporate problem-solving. CEOs of massive companies hire these consultants when they face unprecedented global shifts or need unbiased, brilliant strategic advice for billion-dollar decisions.",
        roadmap: [
            "Executive: Business Analyst / Associate",
            "Manager: Consultant / Engagement Manager",
            "Senior Manager: Associate Partner/Principal",
            "Director: Partner",
            "Global Head: Senior Partner / Global Practice Leader"
        ],
        certifications: ["None; brand name of degree and firm matters most."],
        summary: "A high-stress, extremely prestigious role advising the CEOs of the world's largest companies on their most critical global strategies.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Management Consulting Firms (MBB, Big 4)"],
        jobDemandTrend: "High",
        governmentJobs: "Consultants are frequently hired by governments for policy implementation and mega-project planning.",
        competitiveExams: ["CAT/GMAT (for elite MBA entry)"],
        privateSectorOpportunities: "The fastest track to C-suite roles in global industry, serving as almost a 'finishing school' for future CEOs.",
        internationalJobOpportunities: "Extremely high. Constant travel across the globe to client sites is normal.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Independent consulting post-MBB experience.",
        licenseRequired: "None",
        riskLevel: "Low (High job security due to elite skill set)"
    }
];

const seedInternationalBusinessProfessions = async () => {
    try {
        await Career.deleteMany({ branch: "International Business" });
        await Career.insertMany(internationalBusinessProfessions);
        console.log('International Business Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedInternationalBusinessProfessions();
