const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const medicalLaboratoryProfessions = [
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Clinical Laboratory Technologist (Generalist)",
        description: "Perform a complex array of tests on body fluids, tissues, and cells to detect diseases. They operate across mass chemistry, hematology, and immunology departments in hospitals.",
        summary: "Versatile lab professionals conducting a massive range of diagnostic tests across all hospital lab departments.",
        skills: ["Operating Automated Analyzers", "Microscopy", "Quality Control Protocols", "Multi-departmental Dexterity", "Data Verification"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $65K - $95K",
        educationPath: "B.Sc Medical Laboratory Technology (BMLT)",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Hospital Pathology Labs", "Private Diagnostic Chains", "24/7 Emergency Labs"],
        futureScope: "Extremely high and stable. 70% of medical decisions rely on laboratory testing, making generalists indispensable to any hospital.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Roles in every state/central hospital.",
        freelanceOpportunities: "Low. Highly institutionalized.",
        fieldWork: "Low. Laboratory based.",
        riskLevel: "Moderate (Handling biohazardous materials daily)",
        certifications: ["State Paramedical Council Registration / ASCP Certification"],
        internshipRequirements: "One year mandatory rotatory clinical internship.",
        roadmap: ["Lab Intern", "Clinical Lab Technologist", "Section Supervisor", "Laboratory Manager"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Medical Laboratory Technician (MLT)",
        description: "Perform routine, highly standardized tests in medical laboratories under the supervision of technologists or pathologists, handling high-volume daily sample processing.",
        summary: "The backbone of the lab, executing thousands of daily routine diagnostic tests rapidly and accurately.",
        skills: ["Sample Preparation", "Standardized Test Execution", "Machine Maintenance", "High-Volume Processing", "Basic Microscopy"],
        salaryRange: "India: ₹2L - ₹5L | Global: $45K - $70K",
        educationPath: "Diploma in Medical Laboratory Technology (DMLT)",
        yearsOfStudy: "2 Years",
        industriesHiring: ["Primary Health Centers", "Diagnostic Chains", "Blood Collection Centers"],
        futureScope: "High demand. As corporate diagnostic chains expand massively (especially in India), the demand for technicians to process routine samples skyrockets.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High. State rural health dispensaries and polyclinics.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Clinic/Lab based.",
        riskLevel: "Moderate (Sample handling)",
        certifications: ["DMLT Registration"],
        internshipRequirements: "Six months clinical lab posting.",
        roadmap: ["Lab Technician", "Senior Technician", "Shift In-Charge"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Phlebotomist",
        description: "Specialize strictly in drawing blood from patients (venipuncture) across all age groups safely, painlessly, and in the exact tubes required for specific lab tests.",
        summary: "Specialists in safe and painless blood collection from patients.",
        skills: ["Venipuncture", "Patient Comfort / Calming", "Capillary Puncture (Pediatrics)", "Proper Tube Selection and Handling"],
        salaryRange: "India: ₹1.8L - ₹4L | Global: $35K - $55K",
        educationPath: "Certificate / Diploma in Phlebotomy Training",
        yearsOfStudy: "3 to 6 Months",
        industriesHiring: ["Diagnostic Chains", "Hospitals", "Home Healthcare Providers"],
        futureScope: "Explosive growth in home-collection services. Companies constantly hire phlebotomists to travel and collect samples directly from patients' homes.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate. Blood banks and casualty wards.",
        freelanceOpportunities: "High. Operating independently to collect home samples for various partnered labs.",
        fieldWork: "Maximum. Traveling extensively on two-wheelers for home collections.",
        riskLevel: "Moderate (Risk of accidental needle-stick injuries and transmitting bloodborne pathogens)",
        certifications: ["Certified Phlebotomy Technician (CPT)"],
        internshipRequirements: "Minimum 100 successful supervised blood draws.",
        roadmap: ["Trainee Phlebotomist", "Phlebotomist", "Home Collection Lead", "Phlebotomy Instructor"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Clinical Chemistry Technologist",
        description: "Specialize in analyzing the chemical and hormonal composition of bodily fluids using massive automated analyzers to diagnose conditions like diabetes, kidney failure, and thyroid disorders.",
        summary: "Experts operating the massive, automated robotic analyzers that perform biochemistry tests.",
        skills: ["Operating Complex Automated Chemistry Lines (e.g., Roche, Abbott)", "QC Calibration", "Troubleshooting Machine Errors", "Stat Sample Prioritization"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $65K - $95K",
        educationPath: "BMLT → Specialization / Experience in Clinical Chemistry",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Large Reference Laboratories", "Hospital Core Labs"],
        futureScope: "Stable. Highly reliant on automation, requiring techs primarily to validate machine accuracy and maintain the robotics.",
        jobDemandTrend: "Stable",
        governmentJobs: "High.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Lab based.",
        riskLevel: "Low to Moderate",
        certifications: ["Chemistry (C) ASCP Certification"],
        internshipRequirements: "Extensive training operating specific proprietary automated analyzers.",
        roadmap: ["Lab Tech", "Chemistry Technologist", "Chemistry Section Supervisor"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Clinical Microbiology Technologist",
        description: "Isolate and identify bacteria, parasites, and fungi from patient samples, and test which exact antibiotics will successfully kill the identified pathogen.",
        summary: "The bench-technologists culturing bacteria and testing antibiotic effectiveness.",
        skills: ["Aseptic Technique", "Bacterial Culturing on Agar", "Gram/Acid-Fast Staining", "Antimicrobial Susceptibility Testing", "Odour/Visual Pathogen Identification"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $65K - $95K",
        educationPath: "B.Sc Microbiology / BMLT",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Infectious Disease Hospitals", "Central Reference Labs", "Public Health Labs"],
        futureScope: "Critical. Sepsis and antibiotic resistance require highly skilled human technologists, as microbiology is far less automated than chemistry.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Lab based.",
        riskLevel: "High (High risk of exposure to infectious aerosols like Tuberculosis)",
        certifications: ["Microbiology (M) ASCP Certification"],
        internshipRequirements: "Months of training strictly in BSL-2 environments.",
        roadmap: ["Microbiology Tech", "Senior Microbiology Technologist", "Infection Control Assistant", "Microbiology Lead"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Hematology Technologist",
        description: "Specialize in analyzing whole blood samples to diagnose anemias, leukemias (blood cancers), and severe clotting disorders by examining blood smears under a microscope.",
        summary: "Microscopy experts identifying abnormal blood cells to diagnose anemias and leukemias.",
        skills: ["Peripheral Blood Smear Review", "Flow Cytometry Operation", "Coagulation Testing", "Extreme Visual Pattern Recognition"],
        salaryRange: "India: ₹3.5L - ₹8.5L | Global: $65K - $95K",
        educationPath: "BMLT → Specialization in Hematology",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Cancer Institutes", "General Hospitals", "Diagnostic Chains"],
        futureScope: "Stable. While machines count basic cells, highly trained technologists are strictly required to manually review cancerous or abnormal cells.",
        jobDemandTrend: "Stable",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Blood handling)",
        certifications: ["Hematology (H) ASCP Certification"],
        internshipRequirements: "Hundreds of hours viewing normal and abnormal blood slides.",
        roadmap: ["Lab Tech", "Hematology Technologist", "Hematology Section Head"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Blood Bank / Immunohematology Technologist",
        description: "Determine patient blood types, identify complex dangerous antibodies, and cross-match blood from donors to ensure patients do not suffer lethal transfusion reactions during surgery.",
        summary: "Critical-care technologists cross-matching blood to prevent lethal transfusion reactions.",
        skills: ["ABO/Rh Blood Typing", "Antibody Screening/Panel Resolution", "Extreme Stress Management", "Zero-Error Tolerance", "Blood Component Thawing"],
        salaryRange: "India: ₹4L - ₹10L | Global: $70K - $105K",
        educationPath: "BMLT → Specialized Blood Banking Training",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Trauma Centers", "Red Cross/Blood Banks", "Major Surgical Hospitals"],
        futureScope: "Essential and high-stress. The blood bank is the only lab department where a single technologist error can kill a patient instantly on the operating table.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "High. State blood banks.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Lab based.",
        riskLevel: "Moderate (High liability, extremely high stress during massive trauma bleeding cases)",
        certifications: ["Blood Banking (BB) ASCP Certification"],
        internshipRequirements: "Intensive training in emergency cross-matching protocols.",
        roadmap: ["Blood Bank Tech", "Senior Immunohematology Technologist", "Blood Bank Supervisor"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Histotechnologist",
        description: "Complexly process, encase in wax, cut into microscopic slivers, and chemically stain solid human tissue removed during surgery so a pathologist can diagnose cancer.",
        summary: "The skilled manual artisans of the lab, cutting and staining human tissue for cancer diagnosis.",
        skills: ["Microtomy (Cutting tissue at 4 microns)", "Tissue Processing (Formalin/Xylene)", "Complex Special Staining Techniques", "Extreme Manual Dexterity"],
        salaryRange: "India: ₹3.5L - ₹8.5L | Global: $65K - $95K",
        educationPath: "BMLT or B.Sc Biology → Certification in Histotechnology",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Oncology Centers", "Anatomic Pathology Labs", "Dermatology Clinics"],
        futureScope: "Highly stable. Histology is an \"art\" requiring intense manual skill that robots currently cannot fully replicate.",
        jobDemandTrend: "Stable",
        governmentJobs: "Moderate. Autopsy and biopsy centers.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Exposure to toxic, carcinogenic chemicals like Formaldehyde and Xylene)",
        certifications: ["Histotechnologist (HTL) ASCP Certification"],
        internshipRequirements: "Rigorous manual training cutting hundreds of wax blocks.",
        roadmap: ["Histotechnician", "Histotechnologist", "Grossing Assistant", "Histology Lab Manager"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Cytotechnologist",
        description: "Examine single human cells under a microscope to detect minute changes indicating pre-cancer, primarily reviewing thousands of gynecological (Pap) smears and fluid aspirates daily.",
        summary: "Microscopic specialists screening individual cells to catch cancer at its earliest stage.",
        skills: ["Extreme Visual Fatigue Tolerance", "Detailed Cellular Morphology", "Pattern Recognition", "Focus"],
        salaryRange: "India: ₹4L - ₹10L | Global: $75K - $110K",
        educationPath: "B.Sc/BMLT → Specialized Cytotechnology Post-Graduation",
        yearsOfStudy: "4.5 Years",
        industriesHiring: ["Women's Health Diagnostic Labs", "Cancer Hospitals", "Major Reference Labs"],
        futureScope: "Currently strong, though the integration of AI image analysis algorithms may eventually assist or reduce the total number of manual screeners needed.",
        jobDemandTrend: "Stable",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Moderate. Some \"tele-cytology\" viewing digital slides remotely.",
        fieldWork: "Low. Laboratory based.",
        riskLevel: "Low to Moderate (Extreme eye strain / ergonomic issues)",
        certifications: ["Cytotechnologist (CT) ASCP Certification"],
        internshipRequirements: "Evaluating thousands of specialized Pap smear slides.",
        roadmap: ["Trainee Screen", "Cytotechnologist", "Senior Reviewer", "Cytology Supervisor"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Molecular Diagnostics Technologist",
        description: "Perform highly complex genetic and molecular testing—such as PCR—to diagnose viral infections (like COVID-19/HIV) or detect specific cancer-causing genetic mutations.",
        summary: "The DNA/RNA experts using PCR technology to detect viruses and genetic mutations.",
        skills: ["Polymerase Chain Reaction (PCR)", "DNA/RNA Extraction", "Pipetting Precision", "Next-Generation Sequencing Preparation", "Strict Contamination Control"],
        salaryRange: "India: ₹4.5L - ₹12L | Global: $75K - $115K",
        educationPath: "B.Sc Biotechnology/Genetics or BMLT → M.Sc Molecular Diagnostics",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Genomic Testing Labs", "Infectious Disease Hospitals", "Forensic Labs"],
        futureScope: "The absolute fastest-growing sector in laboratory medicine globally. Molecular techniques are rapidly replacing traditional cultures and chemistry.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High. State infectious disease response labs (e.g., ICMR centers).",
        freelanceOpportunities: "Low.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Biohazard exposure)",
        certifications: ["Molecular Biology (MB) ASCP Certification"],
        internshipRequirements: "Handling and extracting RNA/DNA in 'clean room' environments.",
        roadmap: ["Molecular Tech", "Senior Molecular Technologist", "Molecular Lab Manager"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Immunology / Serology Technologist",
        description: "Analyze the patient’s immune response, measuring antibodies to diagnose autoimmune diseases (e.g., Rheumatoid Arthritis, Lupus) and recent infections (e.g., Dengue, Syphilis).",
        summary: "Technologists testing for antibodies in the blood to diagnose autoimmune diseases and past infections.",
        skills: ["ELISA/EIA Techniques", "Immunofluorescence Microscopy", "Agglutination Assays", "Serial Dilutions"],
        salaryRange: "India: ₹3.5L - ₹8.5L | Global: $65K - $95K",
        educationPath: "BMLT or B.Sc Microbiology",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Rheumatology Clinics", "Hospital Pathology Labs", "Reference Diagnostics"],
        futureScope: "Stable and growing as autoimmune disorders rise globally. Highly automated but still requires specialized interpretation.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Lab based.",
        riskLevel: "Moderate (Handling serum from infectious patients)",
        certifications: ["State Registration"],
        internshipRequirements: "Running complex ELISA plates and validating standard curves.",
        roadmap: ["Serology Tech", "Immunology Technologist", "Serology Section Supervisor"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Toxicology Technologist",
        description: "Test bodily fluids (blood, urine) for the presence of illicit recreational drugs, heavy metals, poisons, and prescribed therapeutic drug levels in emergency overdose cases.",
        summary: "Lab experts testing for drug overdoses, poisons, and performing employee drug screenings.",
        skills: ["Gas Chromatography/Mass Spectrometry (GC/MS)", "Chain of Custody Procedures", "Analytical Troubleshooting", "Strict Legal Compliance"],
        salaryRange: "India: ₹4L - ₹10L | Global: $70K - $100K",
        educationPath: "BMLT / B.Sc Chemistry → Specialization in Analytical/Toxicology Testing",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Poison Control Emergency Labs", "Forensic/Police Labs", "Employee Drug Testing Centers"],
        futureScope: "High demand driven by the global opioid crisis and stringent corporate/sports drug-testing protocols.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Maximum. Forensic science labs.",
        freelanceOpportunities: "Low. Highly regulated.",
        fieldWork: "Low (Occasional court testimony in forensic roles).",
        riskLevel: "Low to Moderate",
        certifications: ["Toxicology Specialist Certifications"],
        internshipRequirements: "Extensive training on Mass Spectrometers.",
        roadmap: ["Tox Tech", "Senior Analytical Technologist", "Toxicology Lab Director"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Pathologists' Assistant",
        description: "Assist the lead Medical Pathologist by performing the initial physical dissection (\"grossing\") of surgically removed organs, limbs, or entire bodies during autopsies.",
        summary: "Elite lab professionals dissecting surgical specimens and performing autopsies under a pathologist.",
        skills: ["Surgical Scalpel Grossing", "Deep Human Anatomy", "Autopsy Procedures", "Dictation/Descriptive Documentation", "Emotional Resilience"],
        salaryRange: "India: ₹8L - ₹18L | Global: $90K - $130K",
        educationPath: "B.Sc Biology/BMLT → Master’s Level Pathologists' Assistant Program",
        yearsOfStudy: "5.5 to 6 Years",
        industriesHiring: ["Major Teaching Hospitals", "Forensic Morgues", "Large Anatomic Pathology Labs"],
        futureScope: "Extremely lucrative niche. They save Pathologists massive amounts of time by doing the physical dissections, making them highly sought after in large hospitals.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "High. State forensic morgues.",
        freelanceOpportunities: "Moderate. Locum (traveling) grossing coverage for labs.",
        fieldWork: "Low. Autopsy suites and grossing rooms.",
        riskLevel: "High (Extreme biohazard exposure, dealing daily with diseased organs and deceased bodies)",
        certifications: ["Pathologists' Assistant (PA) ASCP Certification"],
        internshipRequirements: "Hundreds of hours performing autopsies and dissecting complex cancer organs.",
        roadmap: ["PA Student", "Pathologists' Assistant", "Lead PA", "Anatomy Instructor"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Cytogenetic Technologist",
        description: "Extract DNA and map out entire human chromosomes on a computer screen to visibly detect massive genetic abnormalities like Down Syndrome or specific leukemias.",
        summary: "Genetic technologists visually mapping chromosomes to detect birth defects and cancers.",
        skills: ["Karyotyping", "FISH Techniques", "Cell Culturing (Amniotic fluid/Bone marrow)", "Microscopy"],
        salaryRange: "India: ₹4.5L - ₹11L | Global: $75K - $110K",
        educationPath: "B.Sc Genetics / Biotechnology → Training in Cytogenetics",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Prenatal Testing Clinics", "Cancer Research Hospitals", "Genomic Reference Labs"],
        futureScope: "Stable, but slowly transforming as digital chromosome mapping softwares begin to automate parts of the visual counting process.",
        jobDemandTrend: "Stable",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. Lab and computer based.",
        riskLevel: "Low to Moderate",
        certifications: ["Cytogenetics (CG) ASCP Certification"],
        internshipRequirements: "Intensive training in harvesting cells and capturing metaphase chromosome spreads.",
        roadmap: ["Cytogenetics Tech", "FISH Specialist", "Cytogenetics Lab Manager"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Flow Cytometry Technologist",
        description: "Operate incredibly complex, multi-million dollar lasers to shoot individual blood cells through a beam of light to diagnose incredibly specific sub-types of lymphomas and leukemias.",
        summary: "Niche technologists using lasers to diagnose complex blood and bone-marrow cancers.",
        skills: ["Flow Cytometer Laser Operation", "Data Plot Gating Analysis", "Deep Cellular Immunology", "Fluorochrome Understanding"],
        salaryRange: "India: ₹5L - ₹14L | Global: $85K - $125K",
        educationPath: "BMLT / B.Sc Immunology → Extensive On-the-Job Training in Flow Cytometry",
        yearsOfStudy: "4.5 to 5 Years",
        industriesHiring: ["Elite Oncology Centers", "Biotech Research Companies", "Stem Cell/Transplant Centers"],
        futureScope: "Extremely specialized and highly paid. As cancer therapies become hyper-targeted (like CAR-T cell therapy), these technologists are essentially invaluable.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Moderate. Only in elite national cancer/genome centers.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["SCYM (Specialist in Cytometry) Certification"],
        internshipRequirements: "Years apprenticing under an experienced flow cytometry data analyst.",
        roadmap: ["General Tech", "Flow Cytometry Specialist", "Immunology Lab Director"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Point-of-Care Testing (POCT) Coordinator",
        description: "Manage, calibrate, and oversee all the small, rapid-test medical devices (like glucose meters and rapid strep tests) used by nurses and doctors outside the main laboratory.",
        summary: "Lab experts ensuring that rapid tests used in the ER or ICU are accurate and functioning correctly.",
        skills: ["Device Calibration", "Quality Assurance", "Teaching Nurses/Doctors", "Regulatory Compliance / Auditing"],
        salaryRange: "India: ₹5L - ₹12L | Global: $75K - $115K",
        educationPath: "BMLT + 5 Years Clinical Lab Experience",
        yearsOfStudy: "4 Years (plus experience)",
        industriesHiring: ["Large Hospital Networks", "Ambulatory Surgical Centers"],
        futureScope: "Explosive growth. Hospitals rapidly want testing done at the patient's bedside instantly, requiring experts to manage all these decentralized machines.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Moderate. Consulting for rural clinics to set up their rapid testing.",
        fieldWork: "High. Constantly walking across the hospital to every ward, ER, and ICU.",
        riskLevel: "Low",
        certifications: ["Point of Care Specialist Certifications"],
        internshipRequirements: "Extensive experience working in a central hospital lab first.",
        roadmap: ["Clinical Lab Technologist", "POCT Coordinator", "Director of Hospital Quality Assurance"]
    },
    {
        domain: "Medical",
        branch: "Medical Laboratory",
        title: "Laboratory Information System (LIS) Analyst",
        description: "Act as the critical IT bridge in the laboratory, configuring the software that connects the diagnostic machines directly to the patient's electronic medical record.",
        summary: "The IT experts of the lab, ensuring blood test results automatically transfer to the doctor's screen.",
        skills: ["LIS Software Configuration (Epic Beaker, Cerner)", "Database Management", "HL7 Interfaces", "Clinical Workflow Understanding"],
        salaryRange: "India: ₹7L - ₹18L | Global: $90K - $135K",
        educationPath: "BMLT → Certification in Health IT / Computer Science",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Health IT Corporations", "Massive Hospital Systems", "Diagnostic Corporate Chains"],
        futureScope: "Extremely lucrative non-bench role. As labs become entirely automated and paperless, technicians who can code and understand clinical data are in severe demand.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum. Highly paid freelance IT consultants for new lab setups.",
        fieldWork: "Low. Entirely IT/office based.",
        riskLevel: "Low",
        certifications: ["Specific LIS Vendor Certifications (e.g., Epic Beaker Certification)"],
        internshipRequirements: "Transitioning from the bench to hospital IT departments.",
        roadmap: ["Lab Technologist", "LIS Build Analyst", "LIS Manager", "Chief Health Information Officer"]
    }
];

const seedMedicalLaboratory = async () => {
    try {
        await Career.deleteMany({ branch: "Medical Laboratory" });
        await Career.insertMany(medicalLaboratoryProfessions);
        console.log('Medical Laboratory Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedMedicalLaboratory();
