const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const mbbsProfessions = [
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "General Practitioner / Family Physician",
        description: "Diagnose and treat common illnesses, provide preventive care, and manage overall patient health before referring to specialists if necessary.",
        summary: "Primary care doctors providing comprehensive medical care to individuals and families.",
        skills: ["Diagnostic Skills", "Patient Communication", "Empathy", "Broad Medical Knowledge", "Time Management"],
        salaryRange: "India: ₹8L - ₹15L | Global: $150K - $250K",
        educationPath: "10+2 (PCB) → NEET-UG → MBBS → Internship",
        yearsOfStudy: "5.5 Years",
        industriesHiring: ["Private Clinics", "Government Primary Health Centers (PHC)", "Corporate Hospitals"],
        futureScope: "Constant, high demand globally due to growing populations and the need for accessible primary healthcare.",
        jobDemandTrend: "High",
        governmentJobs: "Maximum. Backbone of state and national health services.",
        freelanceOpportunities: "High. Running independent private clinics or telemedicine consulting.",
        fieldWork: "Low to Moderate. Mostly clinic-based, occasionally attending medical camps.",
        riskLevel: "Low to Moderate (Exposure to infectious diseases, stressful patient interactions)",
        certifications: ["State/National Medical Council Registration"],
        internshipRequirements: "1-year rotating compulsory residential internship.",
        roadmap: ["Medical Student", "Medical Intern", "Junior Resident / Medical Officer", "Senior Consultant / Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Cardiologist",
        description: "Diagnose, treat, and prevent diseases bridging the heart and blood vessels, utilizing advanced surgical and non-surgical procedures.",
        summary: "Specialist doctors focusing on diagnosing and treating heart conditions.",
        skills: ["Surgical Precision (if Interventional)", "Echocardiography", "Stress Management", "Critical Decision Making", "Continuous Learning"],
        salaryRange: "India: ₹20L - ₹50L+ | Global: $350K - $500K+",
        educationPath: "MBBS → MD (General Medicine) → DM / DNB (Cardiology)",
        yearsOfStudy: "11.5 to 13 Years",
        industriesHiring: ["Super-Specialty Hospitals", "Research Institutes", "Private Nursing Homes"],
        futureScope: "Extremely high due to rising global rates of cardiovascular diseases and aging populations.",
        jobDemandTrend: "Very High",
        governmentJobs: "High. Specialized roles in massive government tertiary care hospitals.",
        freelanceOpportunities: "Moderate. Visiting consultants at multiple hospitals.",
        fieldWork: "Low. Surgery and consultation are hospital-based.",
        riskLevel: "Moderate (High emotional stress and demanding irregular hours)",
        certifications: ["Specialization Board Certifications"],
        internshipRequirements: "Extensive residency and fellowship programs working under senior cardiologists.",
        roadmap: ["MBBS Doctor", "MD Resident", "Cardiology Fellow", "Senior Interventional Cardiologist"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Neurologist",
        description: "Specialize in the diagnosis and treatment of disorders affecting the brain, spinal cord, and the central/peripheral nervous systems.",
        summary: "Specialists treating brain and nervous system disorders like epilepsy, Parkinson's, and strokes.",
        skills: ["Analytical Thinking", "Neuro-anatomy Expertise", "Patience", "Empathy (chronic illnesses)", "Precision"],
        salaryRange: "India: ₹18L - ₹40L+ | Global: $250K - $400K+",
        educationPath: "MBBS → MD (General Medicine) → DM (Neurology)",
        yearsOfStudy: "11.5 to 13 Years",
        industriesHiring: ["Multi-Specialty Hospitals", "Neuro-Science Institutes", "Rehabilitation Centers"],
        futureScope: "Very strong demand as life expectancy increases, leading to more age-related neurological disorders.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate to High in leading government medical institutes.",
        freelanceOpportunities: "Moderate. Visiting consultants privately.",
        fieldWork: "Low.",
        riskLevel: "Low (Very high intellectual demand, emotionally taxing)",
        certifications: ["National Board Certifications in Neurology"],
        internshipRequirements: "Rigorous clinical residency and neurological fellowships.",
        roadmap: ["Junior Resident", "Neurology Fellow", "Consultant Neurologist", "HOD Neurology"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Pediatrician",
        description: "Provide comprehensive medical, physical, behavioral, and mental health care for infants, children, and adolescents.",
        summary: "Doctors specializing in the physical and mental health of infants, children, and adolescents.",
        skills: ["Patience", "Child Psychology", "Gentle Communication", "Diagnostic Intuition", "Reassurance"],
        salaryRange: "India: ₹10L - ₹30L | Global: $180K - $250K",
        educationPath: "MBBS → MD / DCH (Pediatrics)",
        yearsOfStudy: "8.5 to 9.5 Years",
        industriesHiring: ["Children's Hospitals", "Maternity Homes", "Private Pediatric Clinics"],
        futureScope: "Constant demand globally. Focus is shifting slightly toward pediatric mental health and early intervention.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Crucial for government child immunization and welfare programs.",
        freelanceOpportunities: "Maximum. Opening independent pediatric clinics is highly viable.",
        fieldWork: "Low to Moderate. Occasional participation in vaccination drives.",
        riskLevel: "Low",
        certifications: ["Board Certification in Pediatrics"],
        internshipRequirements: "Pediatric ward rotations during PG residency.",
        roadmap: ["MBBS Doctor", "Pediatric Resident", "Attending Pediatrician", "Chief of Pediatrics / Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "General Surgeon",
        description: "Perform operative procedures to treat injuries, diseases, and deformities, focusing on the abdominal organs, thyroid, and skin.",
        summary: "Surgical experts treating abdominal organs, hernias, trauma, and extensive soft tissue conditions.",
        skills: ["Manual Dexterity", "Surgical Precision", "Physical Stamina", "Crisis Management", "Leadership under Pressure"],
        salaryRange: "India: ₹15L - ₹40L | Global: $300K - $450K",
        educationPath: "MBBS → MS (General Surgery)",
        yearsOfStudy: "8.5 to 10 Years",
        industriesHiring: ["Trauma Centers", "General Hospitals", "Military Medical Corps"],
        futureScope: "Foundation of hospital medicine. Highly demanding but consistently lucrative and respected.",
        jobDemandTrend: "Very High",
        governmentJobs: "High. Every government hospital requires round-the-clock surgical staff.",
        freelanceOpportunities: "Moderate. Operating across multiple nursing homes.",
        fieldWork: "Low.",
        riskLevel: "High (High stress, life-and-death decisions daily, physical toll of long surgeries)",
        certifications: ["Surgical Board Certifications"],
        internshipRequirements: "Intense, grueling surgical residency programs spanning thousands of hours.",
        roadmap: ["Surgical Intern", "Surgical Resident", "Consultant Surgeon", "Head of Surgery"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Oncologist",
        description: "Diagnose and treat various types of cancer using systemic therapies like chemotherapy, targeted therapy, and immunotherapy.",
        summary: "Specialized doctors focused on diagnosing and treating cancer.",
        skills: ["Empathy", "Resilience", "Up-to-date Knowledge of Genetics/Immunotherapy", "Communication of Hard Truths"],
        salaryRange: "India: ₹20L - ₹50L | Global: $300K - $450K",
        educationPath: "MBBS → MD (General Medicine) → DM / DNB (Medical Oncology)",
        yearsOfStudy: "11.5 to 13 Years",
        industriesHiring: ["Cancer Research Institutes", "Super-Specialty Hospitals"],
        futureScope: "Explosive growth as cancer rates rise globally and new targeted therapies transform the landscape of cancer survival.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Roles in national cancer institutes and specialized wings of state hospitals.",
        freelanceOpportunities: "Low. Highly dependent on massive hospital infrastructure.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Extreme emotional toll dealing with terminally ill patients)",
        certifications: ["Oncology Board Certifications"],
        internshipRequirements: "Extensive clinical fellowships in oncology wards.",
        roadmap: ["PG Resident", "Oncology Fellow", "Consultant Oncologist", "Director of Oncology Institute"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Psychiatrist",
        description: "Diagnose, treat, and prevent mental, emotional, and behavioral disorders, prescribing medication in conjunction with psychotherapy.",
        summary: "Medical doctors specializing in mental health disorders and psychiatric medication.",
        skills: ["Active Listening", "Diagnostic Evaluation", "Empathy", "Pharmacology Knowledge", "De-escalation"],
        salaryRange: "India: ₹10L - ₹25L | Global: $200K - $300K",
        educationPath: "MBBS → MD (Psychiatry) / DPM",
        yearsOfStudy: "8.5 to 10 Years",
        industriesHiring: ["Mental Health Institutes", "Corporate Wellness Programs", "Rehabilitation Clinics"],
        futureScope: "Massive increasing demand as the stigma around mental health fades and global anxiety/depression rates soar.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Roles in state mental hospitals and public health policy.",
        freelanceOpportunities: "Maximum. Tele-psychiatry and private practices are thriving.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Risk of dealing with volatile/aggressive patients)",
        certifications: ["Psychiatry Board Certifications"],
        internshipRequirements: "Clinical rotations in psychiatric wards and addiction centers.",
        roadmap: ["Psychiatric Resident", "Attending Psychiatrist", "Senior Consultant", "Chief Psychiatrist"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Gynecologist & Obstetrician (OB-GYN)",
        description: "Manage women's reproductive health, diagnosing diseases, and managing pregnancies, labor, and the puerperium (post-childbirth period).",
        summary: "Specialists in female reproductive health, pregnancy, and childbirth.",
        skills: ["Surgical Skills (C-Sections)", "Empathy", "Quick Decision Making (Labor)", "Stamina", "Communication"],
        salaryRange: "India: ₹15L - ₹35L+ | Global: $250K - $350K",
        educationPath: "MBBS → MS / MD (Obstetrics & Gynecology)",
        yearsOfStudy: "8.5 to 10 Years",
        industriesHiring: ["Maternity Hospitals", "Fertility/IVF Clinics", "General Hospitals"],
        futureScope: "Constant, high demand. Additionally, fertility medicine (IVF) is becoming a massive and highly lucrative sub-specialty.",
        jobDemandTrend: "High",
        governmentJobs: "Maximum. Critical for maternal mortality reduction programs globally.",
        freelanceOpportunities: "High. Private maternity clinics are extremely common.",
        fieldWork: "Low.",
        riskLevel: "Moderate (High liability/malpractice risk regarding childbirth complications)",
        certifications: ["Board Certification in OB-GYN"],
        internshipRequirements: "Rigorous residency in labor rooms and surgical wards.",
        roadmap: ["OB-GYN Resident", "Consultant Gynecologist", "Senior Surgeon/IVF Specialist", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Orthopedic Surgeon",
        description: "Diagnose, treat, and perform surgeries on conditions involving the musculoskeletal system: bones, joints, ligaments, tendons, and muscles.",
        summary: "Surgical specialists focused on the skeletal system, joints, and sports injuries.",
        skills: ["Physical Strength", "Surgical Precision", "Mechanical Aptitude", "Patience", "Stamina"],
        salaryRange: "India: ₹18L - ₹45L | Global: $400K - $600K+",
        educationPath: "MBBS → MS (Orthopedics)",
        yearsOfStudy: "8.5 to 10 Years",
        industriesHiring: ["Trauma Centers", "Sports Medicine Clinics", "Joint Replacement Centers"],
        futureScope: "Extremely high. As populations age (needing joint replacements) and sports medicine grows, orthopedics is one of the most lucrative medical fields.",
        jobDemandTrend: "Very High",
        governmentJobs: "High. Required in casualty/trauma wards of all major hospitals.",
        freelanceOpportunities: "Moderate. Operating in private nursing homes.",
        fieldWork: "Low.",
        riskLevel: "Low to Moderate (Physically demanding surgeries, high liability)",
        certifications: ["Orthopedic Board Certifications", "Fellowships in Joint/Spine surgery"],
        internshipRequirements: "Residency dealing heavily with trauma, fractures, and joint replacements.",
        roadmap: ["Orthopedic Resident", "Attending Surgeon", "Specialist (Spine/Sports)", "HOD Orthopedics"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Dermatologist",
        description: "Diagnose and treat over 3,000 conditions of the skin, hair, and nails, effectively bridging clinical medicine with cosmetic/aesthetic procedures.",
        summary: "Medical doctors specializing in skin, hair, and nail health, as well as cosmetic procedures.",
        skills: ["Visual Diagnostic Skills", "Aesthetic Sense", "Precision (Laser/Surgery)", "Patient Communication", "Patience"],
        salaryRange: "India: ₹15L - ₹40L+ | Global: $300K - $450K+",
        educationPath: "MBBS → MD (Dermatology, Venereology & Leprosy)",
        yearsOfStudy: "8.5 to 10 Years",
        industriesHiring: ["Cosmetic Surgery Clinics", "Skin Hospitals", "Private Practice"],
        futureScope: "Booming. The aesthetic and cosmetic procedure industry is growing exponentially, making dermatology one of the most sought-after and highest-paying medical branches.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate. Standard outpatient department roles.",
        freelanceOpportunities: "Maximum. The vast majority run highly profitable private clinics.",
        fieldWork: "Low.",
        riskLevel: "Low (No emergency calls, excellent work-life balance compared to surgical fields)",
        certifications: ["Board Certification in Dermatology"],
        internshipRequirements: "Clinical residency focusing heavily on out-patient clinics and laser treatments.",
        roadmap: ["Dermatology Resident", "Clinical Dermatologist", "Cosmetic Dermatologist", "Chain Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Anesthesiologist",
        description: "Administer anesthesia and monitor patient vital signs during surgery, manage acute post-operative pain, and oversee intensive care units (ICU).",
        summary: "Critical care specialists who manage pain and vital signs during surgical operations.",
        skills: ["Extreme Attention to Detail", "Crisis Management", "Pharmacology Expertise", "Calm Under Pressure", "Multi-tasking"],
        salaryRange: "India: ₹12L - ₹30L | Global: $300K - $450K",
        educationPath: "MBBS → MD / DA (Anesthesiology)",
        yearsOfStudy: "8.5 to 10 Years",
        industriesHiring: ["Surgical Hospitals", "Pain Management Clinics", "Trauma Centers"],
        futureScope: "Absolutely critical. No surgery can take place without them. They also play a major role in expanding pain management clinics.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "High. Mandatory in every operating theater.",
        freelanceOpportunities: "High. Operating as free-lancing anesthesiologists across multiple nursing homes.",
        fieldWork: "Low. Entirely OT and ICU based.",
        riskLevel: "High (High liability, split-second life-or-death decisions in the OT)",
        certifications: ["Anesthesia Board Certifications"],
        internshipRequirements: "Rigorous OT and ICU training.",
        roadmap: ["Anesthesia Resident", "Consultant Anesthesiologist", "Intensivist (ICU)", "Head of Anesthesia"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Gastroenterologist",
        description: "Diagnose and treat diseases affecting the gastrointestinal tract (esophagus, stomach, intestines) and liver, bile ducts, and pancreas.",
        summary: "Specialists in digestive system health, performing endoscopies and treating liver/bowel diseases.",
        skills: ["Endoscopic Proficiency", "Diagnostic Acumen", "Patience", "Surgical Hand-Eye Coordination", "Communication"],
        salaryRange: "India: ₹18L - ₹45L | Global: $350K - $500K",
        educationPath: "MBBS → MD (General Medicine) → DM (Gastroenterology)",
        yearsOfStudy: "11.5 to 13 Years",
        industriesHiring: ["Super-Specialty Hospitals", "Liver Transplant Centers"],
        futureScope: "High demand due to rising rates of obesity, poor diet-related digestive disorders, and liver diseases globally.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate. Specialized state hospital departments.",
        freelanceOpportunities: "Moderate. Visiting consultants for endoscopic procedures.",
        fieldWork: "Low.",
        riskLevel: "Low to Moderate",
        certifications: ["Gastroenterology Board Certifications"],
        internshipRequirements: "Extensive fellowships mastering complex endoscopic procedures.",
        roadmap: ["MD Resident", "Gastroenterology Fellow", "Consultant Gastroenterologist", "Head of Hepato-Gastroenterology"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Ophthalmologist",
        description: "Diagnose and treat all eye and visual disorders, perform complex eye surgeries (cataract, LASIK, retina), and prescribe corrective lenses.",
        summary: "Eye doctors specializing in medical and surgical eye care.",
        skills: ["Micro-Surgical Precision", "Patience", "Technological Aptitude (Lasers)", "Steady Hands", "Communication"],
        salaryRange: "India: ₹15L - ₹35L+ | Global: $250K - $400K",
        educationPath: "MBBS → MS / MD (Ophthalmology)",
        yearsOfStudy: "8.5 to 10 Years",
        industriesHiring: ["Eye Hospitals (e.g., Sankara Nethralaya)", "Private Clinics", "General Hospitals"],
        futureScope: "Extremely stable and highly profitable. Aging populations require cataract surgeries, and rising screen time increases myopia and retinal issues.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "High. Crucial for state blindness control programs.",
        freelanceOpportunities: "Maximum. Opening independent eye clinics is highly successful.",
        fieldWork: "Low. Office and OT based.",
        riskLevel: "Low (Excellent work-life balance, rarely any midnight emergencies)",
        certifications: ["Board Certification in Ophthalmology"],
        internshipRequirements: "Residency heavily focused on micro-surgical techniques.",
        roadmap: ["Ophthalmology Resident", "Consultant Ophthalmologist", "Specialist (Cornea/Retina)", "Eye Hospital Director"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Endocrinologist",
        description: "Diagnose and treat diseases related to hormones and glands, primarily focusing on managing diabetes, thyroid conditions, and metabolic disorders.",
        summary: "Specialists in hormones, glands, and metabolic diseases like diabetes.",
        skills: ["Analytical Thinking", "Long-term Patient Management", "Empathy", "Deep Biochemical Knowledge", "Communication"],
        salaryRange: "India: ₹15L - ₹30L | Global: $200K - $300K",
        educationPath: "MBBS → MD (General Medicine) → DM / DNB (Endocrinology)",
        yearsOfStudy: "11.5 to 13 Years",
        industriesHiring: ["Multi-Specialty Hospitals", "Diabetic Research Clinics"],
        futureScope: "Explosive growth. Diabetes is a global epidemic, guaranteeing long-term, high-volume patient demand for endocrinologists.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate. Operating within large state hospitals.",
        freelanceOpportunities: "High. Excellent potential for independent diabetic and thyroid management clinics.",
        fieldWork: "Low. Purely consultation based.",
        riskLevel: "Low (No surgeries, scheduled appointments, great work-life balance)",
        certifications: ["Board Certification in Endocrinology"],
        internshipRequirements: "Clinical fellowships focusing on hormone management and out-patient care.",
        roadmap: ["MD Resident", "Endocrinology Fellow", "Consultant Endocrinologist", "Head of Metabolic Diseases"]
    },
    {
        domain: "Medical",
        branch: "MBBS/Medicine",
        title: "Medical Researcher / Scientist (Clinical Investigator)",
        description: "Design and conduct rigorous clinical trials and laboratory research to discover new drugs, treatments, and understand complex disease mechanisms.",
        summary: "Physician-scientists who push the boundaries of medicine through research and drug trials.",
        skills: ["Scientific Rigor", "Data Analysis", "Grant Writing", "Patience", "Understanding of Bioethics"],
        salaryRange: "India: ₹10L - ₹25L | Global: $150K - $250K+",
        educationPath: "MBBS → MD / Ph.D. in medical sciences or Clinical Research",
        yearsOfStudy: "8.5 to 12 Years",
        industriesHiring: ["Pharmaceutical Conglomerates (Pfizer, Novartis)", "National Institutes of Health (NIH, ICMR)", "Universities"],
        futureScope: "Critical for medical advancement. Growing demand in pharmacovigilance, vaccine development, and genetics.",
        jobDemandTrend: "Stable, Academic Focus",
        governmentJobs: "High. Leading national medical research bodies.",
        freelanceOpportunities: "Moderate. Consulting for pharma companies as an expert regulatory advisor.",
        fieldWork: "Low. Primarily laboratory and office based.",
        riskLevel: "Low to Moderate (Handling dangerous pathogens depending on the lab)",
        certifications: ["Certificates in Clinical Research and Bioethics"],
        internshipRequirements: "Research fellowships and publishing multiple peer-reviewed papers.",
        roadmap: ["Clinical Research Fellow", "Principal Investigator", "Director of Research", "Chief Medical Officer (Pharma)"]
    }
];

const seedMBBS = async () => {
    try {
        await Career.deleteMany({ branch: "MBBS/Medicine" });
        await Career.insertMany(mbbsProfessions);
        console.log('MBBS/Medicine Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedMBBS();
