const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const publicHealthProfessions = [
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Epidemiologist",
        description: "Investigate patterns and causes of human diseases and injuries within populations, acting as disease detectives during outbreaks to find the source and stop the spread.",
        summary: "Disease detectives tracking and mapping outbreaks to stop their spread across populations.",
        skills: ["Statistical Modeling", "Data Analytics (R, SAS, Python)", "Study Design", "Critical Thinking", "Crisis Communication"],
        salaryRange: "India: ₹6L - ₹15L | Global: $80K - $130K",
        educationPath: "B.Sc/MBBS/BDS → Master of Public Health (MPH - Epidemiology) → Ph.D.",
        yearsOfStudy: "6 to 8+ Years",
        industriesHiring: ["Government Health Agencies (CDC, WHO)", "State Health Departments", "Academic Institutes", "Pharmaceutical Companies"],
        futureScope: "Explosive growth post-COVID. Governments realize strong epidemiological surveillance is essential for national security.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Maximum. The core of national disease surveillance systems.",
        freelanceOpportunities: "Low. Institutional and data-dependent.",
        fieldWork: "Moderate to High. Field epidemiology requires rapid deployment to outbreak hotspots.",
        riskLevel: "Moderate (Potential exposure to infectious diseases during field outbreak investigations)",
        certifications: ["Certification Board of Infection Control and Epidemiology (CBIC)"],
        internshipRequirements: "Extensive data analysis and field-work tracking active disease cases.",
        roadmap: ["Research Assistant", "Field Epidemiologist", "Senior Epidemiologist", "Director of Public Health Surveillance"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Biostatistician",
        description: "Apply complex mathematics and statistics exclusively to public health, biology, and medicine, designing clinical trials and interpreting massive healthcare datasets to prove if a drug or policy works.",
        summary: "The math geniuses analyzing massive medical datasets and designing flawless clinical trials.",
        skills: ["Advanced Mathematics", "Statistical Software (SAS, R, STATA)", "Clinical Trial Design", "Data Interpretation", "Precision"],
        salaryRange: "India: ₹8L - ₹20L | Global: $90K - $150K",
        educationPath: "B.Sc Mathematics/Statistics → M.Sc Biostatistics or MPH (Biostatistics)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Pharmaceutical Companies", "Contract Research Organizations (CROs)", "Universities", "Government Agencies"],
        futureScope: "Extremely high and lucrative. Every single new medicine or public health policy must be proven statistically sound before approval.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High. Advising health ministries on population data.",
        freelanceOpportunities: "Maximum. Highly paid consultants for biotech startups running clinical trials.",
        fieldWork: "Low. Purely desktop and mathematics based.",
        riskLevel: "Low",
        certifications: ["Certified Health Data Analyst (CHDA)"],
        internshipRequirements: "Analyzing real-world clinical trial datasets.",
        roadmap: ["Stat Programmer", "Biostatistician", "Principal Statistician", "Director of Biometrics"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Health Policy Analyst",
        description: "Evaluate, develop, and advocate for healthcare laws and policies, analyzing how current laws affect public access to medicine, hospitals, and hygiene.",
        summary: "The architects of healthcare laws and government medical policies.",
        skills: ["Policy Writing", "Economic Analysis", "Lobbying/Advocacy", "Deep understanding of Healthcare Law/Insurance"],
        salaryRange: "India: ₹6L - ₹18L | Global: $85K - $140K",
        educationPath: "BA/B.Sc Economics/Health → Master of Public Policy (MPP) / MPH (Health Policy)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Government Think Tanks", "Health Ministries", "NGOs", "Healthcare Consulting Firms"],
        futureScope: "Critical role. As healthcare costs skyrocket globally, analysts are desperately needed to design efficient, cost-saving state healthcare programs.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Advising politicians and health ministers.",
        freelanceOpportunities: "Moderate. Policy consulting for large NGOs.",
        fieldWork: "Low. Office and parliament/legislature based.",
        riskLevel: "Low",
        certifications: ["Health Policy certifications"],
        internshipRequirements: "Interning at state health departments or policy think-tanks.",
        roadmap: ["Policy Researcher", "Health Policy Analyst", "Senior Policy Advisor", "Health Secretary"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Global Health Professional",
        description: "Work internationally to improve health equity and eradicate global diseases (like Malaria or HIV) in developing nations, usually through massive international organizations.",
        summary: "International experts executing massive health initiatives and fighting disease in developing nations.",
        skills: ["Cross-cultural Communication", "Program Management in low-resource settings", "Language/Translation", "Logistics"],
        salaryRange: "India: ₹8L - ₹25L | Global: $90K - $160K",
        educationPath: "MBBS / MPH / Global Health Master's Degree",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["World Health Organization (WHO)", "UNICEF", "Doctors Without Borders", "Bill & Melinda Gates Foundation"],
        futureScope: "Highly prestigious and impactful. Global interconnectedness means a local disease in a developing nation can become a global crisis if not managed by these professionals.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Roles in foreign aid agencies (USAID, UKAID).",
        freelanceOpportunities: "Low. Operates through massive multi-national agencies.",
        fieldWork: "Maximum. Traveling globally to low-resource or crisis-hit regions.",
        riskLevel: "High (Working in war zones, areas with outbreaks of lethal diseases, or extreme poverty)",
        certifications: ["Certifications in Tropical Medicine/Global Health"],
        internshipRequirements: "Field work in developing countries running health camps.",
        roadmap: ["Field Officer", "Country Director", "Regional Health Advisor", "Global Program Director"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Environmental Health Scientist",
        description: "Study how environmental factors—such as air pollution, contaminated water, and toxic chemicals—directly affect human health, and enforce regulations to prevent public poisoning.",
        summary: "Scientists protecting populations from environmental hazards like pollution, bad water, and toxic waste.",
        skills: ["Environmental Chemistry", "Risk Assessment", "Regulatory Law Comprehension", "Field Sampling"],
        salaryRange: "India: ₹4.5L - ₹12L | Global: $75K - $115K",
        educationPath: "B.Sc Environmental Science → MPH (Environmental Health)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Environmental Protection Agencies (EPA/Pollution Control Boards)", "Industrial Manufacturing (Safety Depts)", "NGOs"],
        futureScope: "Extremely vital. Climate change, urbanization, and industrial pollution are making environmental health the most pressing long-term public health issue.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Maximum. Enforcing pollution control laws.",
        freelanceOpportunities: "Moderate. Environmental impact consulting for new factories/mines.",
        fieldWork: "High. Collecting samples from rivers, factories, and toxic sites.",
        riskLevel: "Moderate (Exposure to hazardous chemicals/waste during field sampling)",
        certifications: ["Registered Environmental Health Specialist (REHS)"],
        internshipRequirements: "Auditing factories for toxic emissions or testing municipal water.",
        roadmap: ["Health Inspector", "Environmental Health Scientist", "Lead Risk Assessor", "Director of EPA Division"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Health Educator / Health Promotion Specialist",
        description: "Design and implement massive community-level programs to educate the public on wellness, from anti-smoking campaigns to sexual health and maternal nutrition.",
        summary: "The communicators designing campaigns to teach the public how to live healthier, disease-free lives.",
        skills: ["Public Speaking", "Curriculum Design", "Cultural Competency", "Social Media / Mass Communication", "Empathy"],
        salaryRange: "India: ₹3.5L - ₹8L | Global: $60K - $90K",
        educationPath: "BA/B.Sc Health Education → MPH (Health Promotion)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Community NGOs", "Schools/Universities", "State Health Departments", "Corporate Wellness Programs"],
        futureScope: "Stable. Prevention is drastically cheaper than treatment, so organizations continuously fund educators to prevent lifestyle diseases (diabetes, obesity).",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Running state or national health awareness campaigns.",
        freelanceOpportunities: "Moderate. Corporate wellness consulting.",
        fieldWork: "High. Conducting sessions in schools, rural villages, and community centers.",
        riskLevel: "Low",
        certifications: ["Certified Health Education Specialist (CHES)"],
        internshipRequirements: "Running ground-level community health camps.",
        roadmap: ["Community Health Worker", "Health Educator", "Program Manager", "Director of Health Promotion"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Occupational Health and Safety Specialist",
        description: "Inspect workplaces—from corporate offices to massive industrial manufacturing plants—to ensure compliance with safety regulations, preventing deadly accidents and occupational diseases.",
        summary: "Experts ensuring that factories, construction sites, and offices are physically safe for workers.",
        skills: ["Industrial Hygiene", "Ergonomics", "Hazard Recognition", "Accident Investigation", "Legal Compliance"],
        salaryRange: "India: ₹5L - ₹15L | Global: $75K - $110K",
        educationPath: "B.Sc Occupational Safety / Engineering → Master of Occupational Safety/Health",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Construction Firms", "Oil and Gas Industry", "Manufacturing Plants", "Government Labor Departments"],
        futureScope: "Strong and legally mandated. No major factory or construction site can legally operate without dedicated safety personnel.",
        jobDemandTrend: "High",
        governmentJobs: "Positions as state and central labor/safety inspectors.",
        freelanceOpportunities: "High. Independent safety auditors for manufacturing plants.",
        fieldWork: "Maximum. Constantly walking construction sites, rigs, and factory floors.",
        riskLevel: "Moderate (Physically inspecting hazardous, high-risk industrial environments)",
        certifications: ["Certified Safety Professional (CSP)"],
        internshipRequirements: "Shadowing inspectors in heavy industries.",
        roadmap: ["Safety Officer", "HSE Manager", "Regional Safety Director", "VP of Environment, Health and Safety"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Maternal and Child Health (MCH) Specialist",
        description: "Focus exclusively on the complex health issues affecting women, infants, and children, working to reduce maternal mortality rates, improve infant nutrition, and ensure safe deliveries.",
        summary: "Dedicated specialists executing programs to keep pregnant women and young children alive and healthy.",
        skills: ["Reproductive Health Knowledge", "Nutrition Science", "Community Advocacy", "Program Evaluation", "Empathy"],
        salaryRange: "India: ₹4.5L - ₹12L | Global: $75K - $115K",
        educationPath: "MBBS / Nursing / B.Sc → MPH (Maternal and Child Health)",
        yearsOfStudy: "5 to 7 Years",
        industriesHiring: ["UNICEF / WHO", "Women's NGOs", "State Rural Health Missions", "Academic Research"],
        futureScope: "Crucial in developing nations. Reducing maternal/infant mortality is a primary global metric for a country's development, ensuring continuous massive funding.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Directing massive state rural health maternal schemes.",
        freelanceOpportunities: "Low.",
        fieldWork: "High. Deep engagement with rural clinics, midwives, and mothers.",
        riskLevel: "Low",
        certifications: ["MCH Specializations"],
        internshipRequirements: "Working in rural primary health centers delivering maternal care.",
        roadmap: ["MCH Coordinator", "Program Specialist", "Director of Family Health Programs"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Public Health Nutritionist",
        description: "Analyze population-level diets to combat malnutrition, design food fortification programs (like adding iodine to salt), and create policies to combat the obesity epidemic.",
        summary: "Experts tackling massive dietary issues, from severe malnutrition in villages to the obesity crisis in cities.",
        skills: ["Nutritional Epidemiology", "Food Policy Design", "Cultural Understanding of Diets", "Scientific Communication"],
        salaryRange: "India: ₹4L - ₹10L | Global: $70K - $100K",
        educationPath: "B.Sc Nutrition → MPH / M.Sc Public Health Nutrition",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Government Food & Civil Supplies", "WFP (World Food Programme)", "NGOs", "Schools"],
        futureScope: "Growing fast as the world faces a 'double burden'—severe undernutrition in rural areas and an exploding obesity/diabetes crisis in urban environments.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High. Designing mid-day meal schemes for state schools.",
        freelanceOpportunities: "Moderate. Consulting for food corporations on healthier product lines.",
        fieldWork: "Moderate. Assessing nutrition in schools and communities.",
        riskLevel: "Low",
        certifications: ["Registered Dietitian (RD) with Public Health specialty"],
        internshipRequirements: "Assessing BMI and executing diet plans in community populations.",
        roadmap: ["Community Nutritionist", "MCH Nutrition Specialist", "Chief of Nutrition Programs"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Infection Control Practitioner (ICP)",
        description: "Work internally within massive hospitals to track baseline infection rates, enforce strict sterilization protocols, and stop deadly 'superbugs' from spreading between patients.",
        summary: "The specialized police of the hospital answering to no one, ensuring absolute sterility and stopping outbreaks within the wards.",
        skills: ["Microbiology Knowledge", "Strict Protocol Enforcement", "Data Tracking", "Surgical Sterility Guidelines", "Authoritative Communication"],
        salaryRange: "India: ₹4.5L - ₹11L | Global: $85K - $125K",
        educationPath: "B.Sc Nursing / Microbiology → MPH or Certification in Infection Control",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Hospitals", "Surgical Centers", "Long-term Care/Nursing Homes"],
        futureScope: "Critical. Hospital-acquired infections (HAIs) kill millions and cost hospitals billions. ICPs are essential, heavily funded assets.",
        jobDemandTrend: "High",
        governmentJobs: "High. Required in every state hospital.",
        freelanceOpportunities: "Moderate. Auditing private clinics for safety compliance.",
        fieldWork: "Low. Entirely hospital-ward based.",
        riskLevel: "Moderate (Constantly investigating rooms with highly infectious patients)",
        certifications: ["Certification in Infection Prevention and Control (CIC)"],
        internshipRequirements: "Training under senior hospital epidemiologists.",
        roadmap: ["Infection Control Nurse/Analyst", "Senior ICP", "Director of Infection Prevention"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Health Economist",
        description: "Apply economic theories deeply to the healthcare sector, determining the most cost-effective ways to deliver care, price life-saving drugs, and design national health insurance schemes.",
        summary: "The financial geniuses figuring out how to deliver the best healthcare to the most people using limited government money.",
        skills: ["Econometrics", "Healthcare Financing", "Deep Analytical Modeling", "Data Science"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $100K - $160K+",
        educationPath: "B.Sc Economics / Mathematics → Master's / Ph.D. in Health Economics",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["World Bank / IMF", "Health Insurance Companies", "Pharma Companies (Market Access)", "Government Health Ministries"],
        futureScope: "Extremely lucrative and influential. As medical technology becomes astronomically expensive, someone must calculate who pays for it and how.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Maximum. Advising prime ministers and health ministers on budget allocation.",
        freelanceOpportunities: "High. Consulting for massive pharmaceutical firms on drug pricing.",
        fieldWork: "Low. Office and boardroom based.",
        riskLevel: "Low",
        certifications: ["HEOR / Health Economics Certifications"],
        internshipRequirements: "Data analysis internships with national health funding agencies.",
        roadmap: ["Economic Analyst", "Health Economist", "Director of Health Financing", "Policy Chief"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Disaster and Emergency Management Director",
        description: "Coordinate the absolute chaos during massive public health crises—like earthquakes, pandemics, or bioterrorism—ensuring hospitals have supplies, triaging patients, and managing mass casualties.",
        summary: "The calm, strategic commanders organizing massive medical responses during major disasters and crises.",
        skills: ["Extreme Crisis Management", "Logistics/Supply Chain", "Incident Command Systems (ICS)", "Rapid Decision Making under stress"],
        salaryRange: "India: ₹7L - ₹18L | Global: $85K - $130K",
        educationPath: "BA/B.Sc → Master's in Emergency Management / MPH (Disaster Management)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["FEMA/NDMA equivalents", "Red Cross", "Large Hospital Networks", "Military Health Corps"],
        futureScope: "Growing rapidly. Climate change guarantees an increase in severe natural disasters, requiring highly trained professionals to manage medical fallout.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Maximum. Operating at the core of national disaster response agencies.",
        freelanceOpportunities: "Low. Heavily state-dependent.",
        fieldWork: "Maximum. Deployed instantly to the center of natural or man-made disaster zones.",
        riskLevel: "High (Operating in devastated areas without infrastructure, potential violence or ongoing threats)",
        certifications: ["Certified Emergency Manager (CEM)"],
        internshipRequirements: "Participating in simulated mass-casualty drills with military or first responders.",
        roadmap: ["Emergency Planner", "Disaster Response Coordinator", "Director of Emergency Management"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Medical Record / Health Information Administrator (HIA)",
        description: "Design, manage, and secure the massive digital databases of patient health records (EHR/EMR) for entire hospital networks, ensuring data privacy and legal compliance.",
        summary: "The IT-focused experts managing millions of digital patient records and ensuring their privacy and accuracy.",
        skills: ["Database Management (SQL/EHR Systems)", "Medical Coding (ICD-10)", "Data Privacy Laws (HIPAA)", "Cybersecurity Awareness"],
        salaryRange: "India: ₹4L - ₹12L | Global: $75K - $115K",
        educationPath: "B.Sc Health Information Management → Master's in Health Informatics",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Massive Hospital Networks", "Health IT Tech Startups", "Government Health Data Centers"],
        futureScope: "Explosive. The entire medical world has shifted to digital records, creating a massive vulnerability for cyber-attacks and a desperate need for organizers.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High. Managing state citizen health databases.",
        freelanceOpportunities: "Moderate. Consulting on EHR software implementation.",
        fieldWork: "Low. Entirely IT/Office based.",
        riskLevel: "Low",
        certifications: ["Registered Health Information Administrator (RHIA)"],
        internshipRequirements: "Hands-on experience processing and coding patient files in a hospital IT dept.",
        roadmap: ["Health Data Analyst", "Health Information Manager", "Chief Privacy Officer", "VP of Health Informatics"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Behavioral Health Scientist",
        description: "Study how deep human behaviors (addiction, diet choices, violence) affect public health, and design psychological interventions to change these destructive habits on a population scale.",
        summary: "Scientists diving into the psychology of public health, figuring out *why* people make unhealthy choices and how to stop them.",
        skills: ["Psychology/Sociology", "Qualitative Research Design", "Behavior Change Theories", "Survey Design"],
        salaryRange: "India: ₹5L - ₹14L | Global: $80K - $120K",
        educationPath: "BA Psychology/Sociology → MPH (Social and Behavioral Sciences) / Ph.D.",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Addiction/Rehab Centers", "Public Health Research Institutes", "Mental Health NGOs"],
        futureScope: "Crucial. Most modern health crises (obesity, opioid addiction, smoking) are behavioral, not viral, requiring psychological expertise to solve at scale.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High. Designing anti-drug or anti-tobacco campaigns.",
        freelanceOpportunities: "Moderate.",
        fieldWork: "Moderate. Conducting extensive focus groups and interviews.",
        riskLevel: "Low",
        certifications: ["Often requires Ph.D. for high-level research"],
        internshipRequirements: "Running behavioral intervention groups for at-risk populations.",
        roadmap: ["Research Assistant", "Behavioral Scientist", "Intervention Director", "Principal Investigator"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Tropical Medicine / Vector Control Specialist",
        description: "Focus intensely on eradicating diseases transmitted by insects and parasites (malaria, dengue, Zika) by managing mosquito populations, sanitation, and specialized treatments.",
        summary: "Specialists fighting mosquito and parasite-borne deadly diseases in tropical and developing environments.",
        skills: ["Entomology (Study of insects)", "Pesticide Logistics", "Geographic Information Systems (GIS) Mapping", "Parasitology"],
        salaryRange: "India: ₹5L - ₹12L | Global: $80K - $125K",
        educationPath: "B.Sc Zoology / Biomedical → MPH (Tropical Medicine) or specialized diploma.",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["National Vector Borne Disease Control Programs", "WHO", "Military Medical Corps in Tropics"],
        futureScope: "Extremely necessary. Changing global climates are pushing tropical diseases like Dengue and Malaria further north, expanding the need for these experts globally.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Maximum. Running state and municipal anti-mosquito/malaria programs.",
        freelanceOpportunities: "Low.",
        fieldWork: "Maximum. Slums, swamps, and tropical jungles mapping breeding grounds.",
        riskLevel: "High (Working in deep outbreak zones with high exposure to lethal vector-borne diseases)",
        certifications: ["Certifications in Tropical Medicine/Hygiene"],
        internshipRequirements: "Field work actively trapping and testing disease vectors.",
        roadmap: ["Field Biologist", "Vector Control Officer", "Regional Eradication Director"]
    },
    {
        domain: "Medical",
        branch: "Public Health",
        title: "Public Health Veterinarian",
        description: "Investigate and prevent 'zoonotic' diseases—lethal viruses and bacteria (like Rabies, Avian Flu, Ebola, COVID) that jump from animals into human populations.",
        summary: "Veterinarians who protect humans by tracking and stopping diseases that transfer from animals to people.",
        skills: ["Veterinary Epidemiology", "Zoonotic Disease Pathology", "Livestock Management Protocols", "Outbreak Investigation"],
        salaryRange: "India: ₹6L - ₹14L | Global: $90K - $140K",
        educationPath: "B.V.Sc (Veterinary Medicine) → Master of Public Health (MPH)",
        yearsOfStudy: "6.5 to 8 Years",
        industriesHiring: ["Department of Agriculture/Livestock", "CDC / WHO", "Wildlife Conservation NGOs"],
        futureScope: "Arguably the most critical role of the century. 75% of all new emerging human diseases (including COVID-19 and Ebola) originated in animals.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Maximum. National agricultural and epidemiological surveillance agencies.",
        freelanceOpportunities: "Low.",
        fieldWork: "Maximum. Investigating factory farms, wildlife markets, and remote forests.",
        riskLevel: "High (Handling sick, aggressive animals carrying potentially lethal human-transmissible viruses)",
        certifications: ["Board Certified in Veterinary Preventive Medicine"],
        internshipRequirements: "Working with outbreaks in massive livestock herds or wildlife.",
        roadmap: ["Veterinary Officer", "Zoonotic Epidemiologist", "Director of Public Health Veterinary Services"]
    }
];

const seedPublicHealth = async () => {
    try {
        await Career.deleteMany({ branch: "Public Health" });
        await Career.insertMany(publicHealthProfessions);
        console.log('Public Health Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedPublicHealth();
