const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const nursingProfessions = [
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Registered Nurse (RN)",
        description: "Provide direct patient care, administer medications, assist in medical procedures, and educate patients and their families on health management.",
        summary: "The backbone of the healthcare system, providing essential daily patient care in hospitals and clinics.",
        skills: ["Patient Monitoring", "Medication Administration", "Empathy", "Stamina", "Basic Life Support (BLS)"],
        salaryRange: "India: ₹3L - ₹8L | Global: $70K - $100K",
        educationPath: "10+2 (PCB) → B.Sc Nursing / GNM",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Hospitals", "Private Clinics", "Nursing Homes", "Schools"],
        futureScope: "Constant, massive global demand. Aging populations guarantee a perpetual shortage of RNs worldwide.",
        jobDemandTrend: "Very High",
        governmentJobs: "Maximum. Essential staffing at all government hospitals and primary health centers.",
        freelanceOpportunities: "High. Private duty nursing or home-care nursing.",
        fieldWork: "Low. Primarily ward-based.",
        riskLevel: "Moderate (Exposure to infections, physical strain from lifting patients, long shifts)",
        certifications: ["State Nursing Council Registration"],
        internshipRequirements: "Six months to one year of mandatory clinical rotation during studies.",
        roadmap: ["Nursing Student", "Staff Nurse (RN)", "Nursing Supervisor", "Chief Nursing Officer / Matron"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Nurse Practitioner (NP)",
        description: "Advanced practice registered nurses (APRNs) trained to diagnose illnesses, prescribe medications, and manage patient care independently or alongside doctors.",
        summary: "Advanced nurses performing many of the same functions as primary care physicians.",
        skills: ["Advanced Diagnostics", "Prescriptive Authority", "Clinical Judgment", "Patient Counseling", "Leadership"],
        salaryRange: "India: ₹6L - ₹15L | Global: $110K - $150K",
        educationPath: "B.Sc Nursing → M.Sc Nursing / Nurse Practitioner Post-Graduate Program",
        yearsOfStudy: "6 to 7 Years",
        industriesHiring: ["Primary Care Clinics", "Specialty Hospitals", "Community Health Centers"],
        futureScope: "Explosive growth in the West as a primary solution to the doctor shortage; gradually gaining recognition globally.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Growing role in government clinics to offload doctors.",
        freelanceOpportunities: "High. Operating independent NP clinics where legally permitted.",
        fieldWork: "Low.",
        riskLevel: "Moderate (High clinical responsibility and liability)",
        certifications: ["Nurse Practitioner License / Certification"],
        internshipRequirements: "Extensive clinical hours at the Master's level.",
        roadmap: ["Registered Nurse", "Nurse Practitioner", "Lead NP", "Clinic Director"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Critical Care / ICU Nurse",
        description: "Provide highly specialized, intensive care to critically ill or unstable patients following extensive surgeries, trauma, or life-threatening diseases.",
        summary: "Highly skilled nurses managing patients on life-support in Intensive Care Units.",
        skills: ["Operating Ventilators/Monitors", "Rapid Response", "ACLS (Advanced Cardiovascular Life Support)", "Emotional Resilience", "Precision"],
        salaryRange: "India: ₹5L - ₹12L | Global: $85K - $120K",
        educationPath: "B.Sc Nursing → Post-Basic Diploma reflecting Critical Care or specialized ICU training",
        yearsOfStudy: "4.5 to 5 Years",
        industriesHiring: ["Hospital ICUs", "Trauma Centers", "Cardiac Care Units (CCU)"],
        futureScope: "Always in high demand. Requires a high baseline of technical competence and stress tolerance.",
        jobDemandTrend: "High",
        governmentJobs: "High. Required for all government hospital ICUs.",
        freelanceOpportunities: "Moderate. Specialized home ICU setups for terminal or chronic patients.",
        fieldWork: "Low. Strictly confined to the ICU.",
        riskLevel: "High (High-stress environment, critical decisions, infectious disease exposure)",
        certifications: ["Critical Care Registered Nurse (CCRN)"],
        internshipRequirements: "Residency/training specifically in ICU environments.",
        roadmap: ["Staff Nurse", "ICU RN", "Charge Nurse ICU", "Critical Care Director"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Nurse Anesthetist (CRNA)",
        description: "Administer anesthesia for surgery or other medical procedures, monitor patients' vital signs, and manage post-anesthesia recovery.",
        summary: "Advanced nurses qualified to administer anesthesia and manage pain therapy.",
        skills: ["Pharmacology Expertise", "Airway Management", "Extreme Attention to Detail", "Crisis Management", "Anatomical Knowledge"],
        salaryRange: "India: ₹8L - ₹18L | Global: $180K - $220K",
        educationPath: "B.Sc Nursing → ICU Experience → M.Sc in Nurse Anesthesia",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Surgical Hospitals", "Dental Surgery Clinics", "Pain Management Centers"],
        futureScope: "One of the highest-paying nursing specialties globally, rapidly replacing anesthesiologists in routine surgeries to lower healthcare costs.",
        jobDemandTrend: "Very High",
        governmentJobs: "Moderate to High in surgical operating theaters.",
        freelanceOpportunities: "Moderate. Operating as locum tenens across various surgery centers.",
        fieldWork: "Low. Operating Room (OR) based.",
        riskLevel: "High (High liability operating anesthesia independently or under supervision)",
        certifications: ["Certified Registered Nurse Anesthetist (CRNA)"],
        internshipRequirements: "Extensive clinical hours in the OR.",
        roadmap: ["ICU Nurse", "Nurse Anesthesia Student", "CRNA", "Chief CRNA"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Neonatal Intensive Care Unit (NICU) Nurse",
        description: "Care for premature or critically ill newborn infants, operating incubators, ventilators, and administering specialized, minute doses of medication.",
        summary: "Specialized ICU nurses dedicated to keeping premature and sick infants alive.",
        skills: ["Neonatal Resuscitation Program (NRP)", "Extreme Precision", "Emotional Fortitude", "Operating Specialized Infant Equipment", "Family Communication"],
        salaryRange: "India: ₹5L - ₹12L | Global: $80K - $115K",
        educationPath: "B.Sc Nursing → Specialized Certification or M.Sc in Neonatal Nursing",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Maternity Hospitals", "Children's Hospitals", "Tertiary Care Centers"],
        futureScope: "Extremely secure. As reproductive tech (IVF) increases, multiple births and preemies are more common, demanding NICU beds.",
        jobDemandTrend: "High",
        governmentJobs: "High in state maternal and child hospital wings.",
        freelanceOpportunities: "Low. Highly dependent on hospital equipment.",
        fieldWork: "Low.",
        riskLevel: "High (Heartbreaking outcomes, high stress dealing with fragile infants)",
        certifications: ["Neonatal Resuscitation Program (NRP)", "Neonatal Intensive Care Nursing Certification"],
        internshipRequirements: "Clinical rotations specifically in a Level III or Level IV NICU.",
        roadmap: ["Labor & Delivery Nurse / RN", "NICU Staff Nurse", "NICU Charge Nurse", "NICU Nurse Manager"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Emergency Room (ER) Nurse",
        description: "Treat patients in emergency situations where they're experiencing trauma or injury, rapidly triaging their condition and stabilizing them to save their lives.",
        summary: "Frontline trauma nurses working in the fast-paced, high-pressure environment of the ER.",
        skills: ["Triage Assessment", "Rapid Trauma Intervention", "Chaos Management", "ACLS/PALS", "Quick Decision Making"],
        salaryRange: "India: ₹4L - ₹10L | Global: $75K - $110K",
        educationPath: "B.Sc Nursing → ER Nursing Certification",
        yearsOfStudy: "4 Years",
        industriesHiring: ["Trauma Centers", "General Hospitals ER Departments"],
        futureScope: "Always crucial. Being an ER nurse requires a specific adrenaline-driven personality type, so turnover is high, ensuring constant job openings.",
        jobDemandTrend: "Very High",
        governmentJobs: "Maximum. The backbone of government casualty wards.",
        freelanceOpportunities: "Moderate. Travel nursing contracts for ER nurses are highly lucrative.",
        fieldWork: "Low to Moderate. Occasional disaster response deployment.",
        riskLevel: "High (Exposure to blood-borne pathogens, aggressive patients, extreme stress)",
        certifications: ["Certified Emergency Nurse (CEN)", "Trauma Nursing Core Course (TNCC)"],
        internshipRequirements: "Clinical rotations in casualty/ER wards.",
        roadmap: ["New Grad RN", "ER Nurse", "Trauma Nurse Coordinator", "Director of Emergency Services"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Nurse Midwife (CNM)",
        description: "Provide healthcare, education, and support to women during pregnancy, childbirth, and the postpartum period, often delivering babies independently in natural births.",
        summary: "Advanced nurses leading low-risk pregnancies and baby deliveries.",
        skills: ["Labor Management", "Fetal Monitoring", "Calming Demeanor", "Suturing", "Cultural Sensitivity"],
        salaryRange: "India: ₹5L - ₹12L | Global: $100K - $130K",
        educationPath: "B.Sc Nursing → M.Sc in OB/GYN Nursing / Certified Midwifery Program",
        yearsOfStudy: "6 Years",
        industriesHiring: ["Maternity Clinics", "Birthing Centers", "Hospitals", "Home Birth Practices"],
        futureScope: "Growing globally as many mothers opt for natural, less-medicalized birthing experiences supported by midwives rather than surgeons (OB-GYNs).",
        jobDemandTrend: "Growing",
        governmentJobs: "High. Primary rural healthcare heavily relies on midwives.",
        freelanceOpportunities: "High. Private midwifery and home birthing practices.",
        fieldWork: "Moderate. Home visits for postpartum checks.",
        riskLevel: "Moderate (Unpredictable hours, birthing complications requiring sudden surgical transfer)",
        certifications: ["Certified Nurse-Midwife (CNM)"],
        internshipRequirements: "Extensive supervised deliveries during training.",
        roadmap: ["Labor & Delivery Nurse", "Nurse Midwife Student", "Certified Nurse Midwife", "Director of Midwifery Services"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Oncology Nurse",
        description: "Care for patients fighting cancer, administering highly toxic chemotherapy drugs safely, and managing the severe side effects and emotional toll of the disease.",
        summary: "Specialized nurses delivering cancer treatments and palliative care.",
        skills: ["Chemotherapy Administration", "Port/PICC Line Access", "Deep Empathy", "Palliative Care Basics", "Symptom Management"],
        salaryRange: "India: ₹5L - ₹11L | Global: $80K - $115K",
        educationPath: "B.Sc Nursing → Oncology Nursing Certification post-experience",
        yearsOfStudy: "4.5 Years",
        industriesHiring: ["Cancer Research Hospitals", "Outpatient Infusion Centers", "Hospice Care"],
        futureScope: "Explosive growth parallel to the rising global rates of cancer diagnoses.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Roles in national/state cancer institutes.",
        freelanceOpportunities: "Moderate. Home-based palliative nursing.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Handling hazardous cytotoxic drugs, very high emotional burnout)",
        certifications: ["Oncology Certified Nurse (OCN)"],
        internshipRequirements: "Training specifically on infusion safety and biohazard handling.",
        roadmap: ["RN", "Oncology Staff Nurse", "Chemotherapy Infusion Specialist", "Oncology Nurse Manager"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Psychiatric / Mental Health Nurse",
        description: "Assess, support, and care for patients diagnosed with mental illnesses, depression, schizophrenia, and addiction issues, often in locked psychiatric facilities.",
        summary: "Nurses managing the daily care and therapy of psychiatric patients.",
        skills: ["De-escalation Techniques", "Psychiatric Pharmacology", "Therapeutic Communication", "Patience", "Boundaries"],
        salaryRange: "India: ₹4L - ₹10L | Global: $75K - $110K",
        educationPath: "B.Sc Nursing → Diploma or M.Sc in Psychiatric Nursing",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Mental Health Facilities", "Rehabilitation Centers", "Prisons / Forensics", "General Hospitals"],
        futureScope: "Massive demand as society increasingly prioritizes mental health and rehabilitation over incarceration.",
        jobDemandTrend: "High Growth",
        governmentJobs: "State mental hospitals and forensic/prison facilities.",
        freelanceOpportunities: "Moderate. Specialized home care or tele-nursing for behavioral health.",
        fieldWork: "Low.",
        riskLevel: "High (Potential for physical violence from acutely psychotic or detoxing patients)",
        certifications: ["Psychiatric-Mental Health Nursing Certification"],
        internshipRequirements: "Clinical rotations in locked psychiatric units.",
        roadmap: ["RN", "Psychiatric RN", "Charge Nurse (Psych Ward)", "Director of Nursing (Mental Health)"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Surgical / Perioperative Nurse",
        description: "Work directly alongside surgeons in the operating room (OR), preparing surgical instruments, anticipating the surgeon's needs, and ensuring a sterile environment.",
        summary: "The vital 'scrub nurses' who assist surgeons during complex operations.",
        skills: ["Sterile Technique Mastery", "Quick Reflexes", "Instrument Knowledge", "Stamina", "Operating Room Protocols"],
        salaryRange: "India: ₹5L - ₹12L | Global: $80K - $115K",
        educationPath: "B.Sc Nursing → Perioperative Nursing Certification",
        yearsOfStudy: "4.5 Years",
        industriesHiring: ["Surgical Hospitals", "Ambulatory Surgery Centers", "Multi-Specialty Clinics"],
        futureScope: "Stable and secure. As surgical volumes rise (especially elective and cosmetic), OR nurses are always needed.",
        jobDemandTrend: "High",
        governmentJobs: "Mandatory staffing in government operating theaters.",
        freelanceOpportunities: "High. Travel nursing OR contracts are incredibly lucrative.",
        fieldWork: "Low. Entirely OR based.",
        riskLevel: "Moderate (Needlestick injuries, prolonged standing, inhaling surgical smoke)",
        certifications: ["CNOR (Certified Perioperative Nurse)"],
        internshipRequirements: "Vast hours 'scrubbing in' and circulating in the OR.",
        roadmap: ["RN", "Circulating Nurse", "Scrub Nurse", "Operating Room Manager"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Public Health Nurse",
        description: "Focus on population health rather than individual patients, designing community health programs, managing vaccination drives, and tracking disease outbreaks.",
        summary: "Community-focused nurses working outside hospitals to prevent disease and educate the public.",
        skills: ["Epidemiology Basics", "Community Outreach", "Health Education", "Data Collection", "Cultural Competence"],
        salaryRange: "India: ₹3L - ₹8L | Global: $65K - $95K",
        educationPath: "B.Sc Nursing → MPH (Master of Public Health) or Diploma in Public Health Nursing",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Government Health Departments", "NGOs (WHO, UNICEF)", "Community Clinics"],
        futureScope: "Vastly important post-pandemic. Governments are investing heavily in community health infrastructure and outbreak prevention.",
        jobDemandTrend: "Stable, Policy Driven",
        governmentJobs: "Maximum. The core of state rural health and sanitation programs.",
        freelanceOpportunities: "Low. Highly institutionalized.",
        fieldWork: "Maximum. Traveling through communities, schools, and rural outposts.",
        riskLevel: "Moderate (Exposure in epidemic hotspots, remote travel hazards)",
        certifications: ["Public Health Nursing Certification"],
        internshipRequirements: "Working with local health departments or rural NGOs.",
        roadmap: ["Community Nurse", "Public Health Nurse", "Program Coordinator", "Director of Public Health Initiatives"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Geriatric / Gerontological Nurse",
        description: "Specialize in the care of elderly patients, managing complex, overlapping chronic conditions like Alzheimer's, arthritis, and cardiovascular diseases.",
        summary: "Compassionate nurses dedicated to the complex care needs of aging populations.",
        skills: ["Patience", "Dementia Care", "Palliative Care Basics", "Polypharmacy Knowledge", "Fall Prevention"],
        salaryRange: "India: ₹4L - ₹9L | Global: $75K - $105K",
        educationPath: "B.Sc Nursing → Geriatric Nursing Certification",
        yearsOfStudy: "4 Years",
        industriesHiring: ["Nursing Homes / Assisted Living", "Hospice", "Hospitals", "Home Healthcare Agencies"],
        futureScope: "The most statistically guaranteed growth path in nursing, driven by the global 'silver tsunami' of an aging population.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High in state-funded veteran or elderly care facilities.",
        freelanceOpportunities: "Maximum. Very high demand for private elderly home care.",
        fieldWork: "Moderate. Often traveling to patients' homes.",
        riskLevel: "Low to Moderate (Physical strain, high patient mortality rate causing burnout)",
        certifications: ["Gerontological Nursing Certification"],
        internshipRequirements: "Clinical rotations in assisted living facilities.",
        roadmap: ["RN", "Geriatric Staff Nurse", "Director of Nursing (Assisted Living Facility)", "Elder Care Consultant"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Pediatric Nurse",
        description: "Provide medical care specifically tailored to infants, children, and adolescents, adapting procedures to ease the fear and physical limitations of children.",
        summary: "Specialized nurses delivering compassionate clinical care to children.",
        skills: ["Child Psychology & Distraction", "PALS (Pediatric Advanced Life Support)", "Patience", "Parent Counseling", "Finding tiny veins"],
        salaryRange: "India: ₹4L - ₹9L | Global: $75K - $105K",
        educationPath: "B.Sc Nursing → Post-Basic Diploma in Pediatric Nursing",
        yearsOfStudy: "4.5 Years",
        industriesHiring: ["Children's Hospitals", "Pediatric Clinics", "Schools", "Pediatric ICUs"],
        futureScope: "Consistent demand. Pediatrics requires a unique, gentle skill set that cannot be automated.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maternal and child health wards.",
        freelanceOpportunities: "Moderate. Specialized pediatric home health care.",
        fieldWork: "Low. Primarily hospital and clinic-based.",
        riskLevel: "Low to Moderate",
        certifications: ["Certified Pediatric Nurse (CPN)"],
        internshipRequirements: "Rotations exclusively in pediatric and PICU wards.",
        roadmap: ["RN", "Pediatric Floor Nurse", "Charge Nurse Pediatrics", "Pediatric Nurse Practitioner"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Nurse Educator",
        description: "Combine clinical expertise with teaching to train the next generation of nurses in universities and lead continuing education programs in hospitals.",
        summary: "Experienced nurses who teach passing clinical knowledge to nursing students.",
        skills: ["Didactic Teaching", "Curriculum Development", "Clinical Evaluation", "Public Speaking", "Mentorship"],
        salaryRange: "India: ₹6L - ₹15L | Global: $80K - $120K",
        educationPath: "B.Sc Nursing → M.Sc Nursing → Ph.D. (Optional for higher academia)",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Nursing Colleges", "Universities", "Hospital Education Departments"],
        futureScope: "Critical bottleneck locally and globally. There is a massive shortage of nursing professors, holding back the graduation of new nurses.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Professorships at government nursing schools.",
        freelanceOpportunities: "Moderate. Independent clinical instruction or writing textbooks.",
        fieldWork: "Moderate. Instructing students on the clinical hospital floor.",
        riskLevel: "Low (Academic environment, no direct primary patient liability)",
        certifications: ["Certified Nurse Educator (CNE)"],
        internshipRequirements: "Must have several years of active clinical RN experience before teaching.",
        roadmap: ["Clinical RN", "Clinical Instructor", "Assistant Professor", "Dean of Nursing"]
    },
    {
        domain: "Medical",
        branch: "Nursing",
        title: "Clinical Nurse Specialist (CNS)",
        description: "Advanced practice nurses who act as clinical experts in a specific patient population, diagnosing, treating, and consulting to improve hospital-wide nursing protocols.",
        summary: "The experts whom other nurses and doctors consult for complex, specialized patient cases.",
        skills: ["Evidence-Based Practice", "Systems Thinking", "Advanced Diagnostics", "Protocol Development", "Leadership"],
        salaryRange: "India: ₹7L - ₹16L | Global: $100K - $140K",
        educationPath: "B.Sc Nursing → M.Sc Nursing or DNP (Doctor of Nursing Practice)",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Large Hospital Systems", "Specialized Clinics (e.g., Wound Care, Diabetes)", "Healthcare Consulting"],
        futureScope: "Highly respected. Hospitals rely on them to reduce medical errors, lower complication rates, and train staff on the latest research.",
        jobDemandTrend: "Stable, High Level",
        governmentJobs: "Advising clinical practice at a state policy level.",
        freelanceOpportunities: "High. Healthcare consulting for clinics regarding patient outcome improvement.",
        fieldWork: "Low. Hospital-based.",
        riskLevel: "Low to Moderate (Less direct hands-on care, more system-wide oversight)",
        certifications: ["Clinical Nurse Specialist Certification (in chosen specialty)"],
        internshipRequirements: "Master's level clinical practicums.",
        roadmap: ["RN", "Specialty RN", "Clinical Nurse Specialist", "Director of Clinical Excellence"]
    }
];

const seedNursing = async () => {
    try {
        await Career.deleteMany({ branch: "Nursing" });
        await Career.insertMany(nursingProfessions);
        console.log('Nursing Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedNursing();
