const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const realEstateLawProfessions = [
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Lawyer",
        description: "A comprehensive legal specialist governing the buying, selling, and development of physical land. They handle everything from massive commercial mall acquisitions to resolving residential boundary disputes.",
        educationPath: "LLB",
        additionalQualification: "Deep operational knowledge of local municipal zooming and land registries.",
        competitiveExams: ["State Law Entrances / CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Transfer of Property Act", "RERA Regulations", "Lease Drafting", "Title Verification"],
        salaryRange: "India: ₹5 LPA - ₹25 LPA | Global: $70,000 - $180,000 per year",
        roadmap: ["Real Estate Associate", "Independent Property Advocate", "Partner - Real Estate", "Senior designated Counsel"],
        governmentOpportunities: "Legal Officers in State Housing Boards and Development Authorities.",
        corporateOpportunities: "Massive demand in national real estate conglomerates (e.g., DLF, Godrej Properties).",
        lawFirmOpportunities: "A highly lucrative core practice area in every major and mid-tier law firm.",
        workNature: "Title Due Diligence, Conveyancing & Civil Court Litigation.",
        futureScope: "Extremely stable. Land is the foundation of almost all physical wealth; the legal mechanisms to securely transfer and develop it will always be in massive demand.",
        jobDemandTrend: "High Volume / Geographically Broad",
        summary: "The foundational architects of physical wealth, ensuring that multi-million dollar property transactions and developments are legally secure."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Dispute Lawyer",
        description: "The aggressive civil litigators of the real estate world. They fight bitter, multi-generational battles in court over forged wills, encroached ancestral land, and illegal property occupations.",
        educationPath: "LLB",
        additionalQualification: "Fluency in local vernacular and understanding of decades-old revenue records.",
        competitiveExams: ["State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Specific Relief Act", "Injunctions", "Cross-Examination", "Ancestral Title Tracing"],
        salaryRange: "India: ₹4 LPA - ₹30+ LPA | Global: $80,000 - $200,000+ per year",
        roadmap: ["Civil Junior Civil Advocate", "Trial Lawyer", "Senior Property Appellate Counsel", "Judge"],
        governmentOpportunities: "Empanelled to defend government land against organized encroachment syndicates.",
        corporateOpportunities: "Hired by massive developers to evict illegal squatters blocking billion-dollar projects.",
        lawFirmOpportunities: "The primary revenue generator for independent litigation chambers across the country.",
        workNature: "High-Volume Trial Court Litigation & Aggressive Client Defense.",
        futureScope: "Recession-proof. Because property values are constantly rising and land records in developing nations are historically chaotic, property litigation is an eternal, booming industry.",
        jobDemandTrend: "Very High Volume",
        summary: "The relentless trial advocates battling in chaotic civil courts to reclaim stolen ancestral lands and secure multi-million dollar disputed properties."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Land Acquisition Lawyer",
        description: "Focuses exclusively on massive state-backed infrastructure. They orchestrate the legally explosive process of forcing private citizens to sell their ancestral farming land to build national highways, airports, or massive dams.",
        educationPath: "LLB -> Specific focus on Land Revenue Laws",
        additionalQualification: "Understanding of massive socio-political dynamics and agrarian economics.",
        competitiveExams: ["CLAT (Optional)"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["None specific"],
        skills: ["Land Acquisition Act (LARR)", "Eminent Domain", "Agrarian Compensation Negotiation", "Tribunal Litigation"],
        salaryRange: "India: ₹6 LPA - ₹25 LPA | Global: $90,000 - $190,000 per year",
        roadmap: ["Acquisition Associate", "Senior Compensation Litigator", "Special Government Prosecutor", "Infrastructure Legal Head"],
        governmentOpportunities: "The absolute legal backbone for the NHAI (National Highways Authority) and Airport Authorities.",
        corporateOpportunities: "Hired by massive infrastructure conglomerates (L&T, Adani) to legally expedite stalled projects.",
        lawFirmOpportunities: "Highly specialized boutique firms handling massive class-action compensation suits for farmers.",
        workNature: "Negotiating Compensation, Fighting Constitutional Writs & Bureaucratic Clearences.",
        futureScope: "Critical for national progress. Expanding an economy requires massive new infrastructure; navigating the volatile legalities of uprooting citizens to build it requires elite specialized lawyers.",
        jobDemandTrend: "High (Infrastructure Driven)",
        summary: "The highly specialized legal engineers who navigate the volatile, legally explosive process of acquiring private land for massive national infrastructure."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Compliance Lawyer",
        description: "Operates exclusively out of court to ensure housing developers don't end up in jail. They ensure every massive residential tower has strictly complied with RERA guidelines, fire-safety, and municipal ecological building codes.",
        educationPath: "LLB -> PG Diploma in Real Estate/Construction Law",
        additionalQualification: "Understanding of municipal bylaws and zoning grids.",
        competitiveExams: ["None"],
        yearsOfStudy: "4 to 5 Years",
        certifications: ["RERA Compliance Certificates"],
        skills: ["RERA / RERA Appellate Tribunal", "Municipal Zoning Laws", "Due Diligence", "Project Auditing"],
        salaryRange: "India: ₹7 LPA - ₹20 LPA | Global: $80,000 - $150,000 per year",
        roadmap: ["Compliance Analyst", "RERA Manager", "VP of Regulatory Affairs", "Chief Legal Officer (Developer)"],
        governmentOpportunities: "Legal Officers functioning directly within the state RERA authorities.",
        corporateOpportunities: "Mandatory in every single real estate development company in the country to avoid catastrophic fines.",
        lawFirmOpportunities: "Specialized auditing teams within tier-1 general corporate practices.",
        workNature: "Desk Auditing, Regulatory Filings & Project Governance.",
        futureScope: "Extremely secure. As governments globally crack down on fraudulent builders through strict centralized acts (like RERA), developers are forced to hire armies of internal compliance lawyers.",
        jobDemandTrend: "High and Mandated",
        summary: "The rigorous internal auditors legally fortifying massive housing projects against crippling governmental fines and consumer RERA lawsuits."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Construction Law Specialist",
        description: "A hybrid between an engineer and a draftsperson. They do not deal with the land; they deal with the massive concrete structures built upon it. They draft incredibly complex multi-million dollar contracts between developers, architects, and mega-contractors.",
        educationPath: "LLB -> LLM in Construction / Commercial Contracts",
        additionalQualification: "Understanding of civil engineering timelines and procurement logistics.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 Years",
        certifications: ["FIDIC Contracts Mastery (Elite)"],
        skills: ["FIDIC Standardization", "Delay/Disruption Claims", "Complex Arbitration", "Commercial Drafting"],
        salaryRange: "India: ₹10 LPA - ₹35 LPA | Global: $120,000 - $250,000 per year",
        roadmap: ["Construction Associate", "Senior Contracts Counsel", "Partner - Projects & Infrastructure", "Global Arbitrator"],
        governmentOpportunities: "Advising the Ministry of Housing and Urban Affairs on massive public works contracts.",
        corporateOpportunities: "Extensively hired by multi-national construction giants (Bechtel, Shapoorji Pallonji).",
        lawFirmOpportunities: "One of the most complex, lucrative niches in tier-1 corporate law firms.",
        workNature: "Mega-Contract Drafting, Financial Claim Negotiation & High-Stakes Arbitration.",
        futureScope: "Highly elite. A 6-month delay on building a mega-airport triggers millions in contractual penalties; these lawyers enforce or defend against those catastrophic financial claims.",
        jobDemandTrend: "Niche/Elite",
        summary: "The incredibly detail-oriented drafting masters who legally orchestrate the actual physical construction of the world's most massive buildings."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Property Registration Legal Advisor",
        description: "The logistical experts bridging the gap between a written agreement and legal reality. They navigate the notoriously corrupt and archaic local sub-registrar offices to legally register the transfer of massive properties, ensuring stamp duty compliance.",
        educationPath: "LLB",
        additionalQualification: "Extreme local networking and fluency in local sub-registrar colloquialisms.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Stamp Duty Laws", "Registration Act", "Bureaucratic Navigation", "Deed Drafting"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $110,000 per year",
        roadmap: ["Registration Agent/Lawyer", "Senior Conveyancing Counsel", "Registration Chamber Owner", "Local Real Estate Fixer"],
        governmentOpportunities: "Often a stepping stone to taking exams to become a Government Sub-Registrar.",
        corporateOpportunities: "Hired heavily by massive retail banks to ensure their mortgaged properties are legally registered upon disbursement.",
        lawFirmOpportunities: "Often outsourced by Tier-1 firms to local independent lawyers due to the 'street-level' networking required.",
        workNature: "Heavy Bureaucratic Liaising, Desk Deed Drafting & Tax Calculation.",
        futureScope: "Extremely stable. No piece of land legally changes hands without passing through the archaic local registry offices, requiring specialized navigators.",
        jobDemandTrend: "High Volume / Geographically Broad",
        summary: "The highly networked logistical navigators ensuring that multi-million dollar property transfers are perfectly registered and globally recognized."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Transaction Lawyer",
        description: "The orchestrators of multi-billion dollar commercial acquisitions. They handle massive REITs (Real Estate Investment Trusts), foreign direct investment into Indian IT Parks, and the colossal mergers of real estate conglomerates.",
        educationPath: "LLB -> MBA or LLM in Corporate Finance",
        additionalQualification: "Deep understanding of tax structuring (FEMA) and cross-border cash flows.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Corporate/M&A Diplomas"],
        skills: ["REIT Structuring", "FDI in Real Estate", "Joint Venture Architectures", "Capital Markets Intersections"],
        salaryRange: "India: ₹12 LPA - ₹40+ LPA | Global: $130,000 - $300,000+ per year",
        roadmap: ["Capital Markets/REIT Associate", "Senior Transactions Counsel", "Partner - Corporate Real Estate", "General Counsel (REIT)"],
        governmentOpportunities: "None. This is the apex of private corporate finance.",
        corporateOpportunities: "Hired by massive global Private Equity firms (Blackstone, Brookfield) acquiring commercial real estate.",
        lawFirmOpportunities: "The highest-billing 'Real Estate' department in global Tier-1 law firms.",
        workNature: "Intense Deal Negotiation, Financial Structuring & Desk Drafting.",
        futureScope: "Phenomenal wealth generation. As commercial real estate increasingly becomes 'financialized' (traded like stocks via REITs), lawyers who understand both land and capital markets are intensely valuable.",
        jobDemandTrend: "Hyper-Elite / Highly Lucrative",
        summary: "The apex financial architects structuring massive, multi-billion dollar commercial real estate acquisitions for global private equity firms."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Land Title Verification Lawyer",
        description: "The historical detectives of the legal world. Before a massive mall or bank loan is approved, they spend weeks digging through 50 years of dusty government archives to ensure the person selling the land actually owns it.",
        educationPath: "LLB",
        additionalQualification: "Patience and ability to read decades-old vernacular/colonial era revenue records.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Aggressive Archive Digging", "Chain of Title Tracing", "Revenue Record Verification", "Due Diligence Reporting"],
        salaryRange: "India: ₹4 LPA - ₹18 LPA | Global: $65,000 - $130,000 per year",
        roadmap: ["Due Diligence Associate", "Title Expert", "Director of Land Acquisitions", "Boutique Verification Firm Owner"],
        governmentOpportunities: "None.",
        corporateOpportunities: "The absolute first step for any bank issuing a mortgage or any developer buying farmland.",
        lawFirmOpportunities: "Massive volume work outsourced by Tier-1 corporate law firms.",
        workNature: "Intense Archival Reading, Complex Revenue Documentation & Drafting 'Title Search Reports'.",
        futureScope: "Critical step-zero. A billion-dollar skyscraper cannot be built legally if there is a flaw in the underlying 50-year title history of the dirt it sits on.",
        jobDemandTrend: "High Volume",
        summary: "The meticulous legal detectives unearthing decades of hidden property history to ensure multi-million dollar deals aren't built on fraudulent land."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Legal Consultant",
        description: "Strategic advisors operating mostly out of specialized real estate brokerages (like JLL or CBRE). They advise High-Net-Worth Individuals (HNIs) on precisely how to structure the purchase of ultra-luxury villas or commercial properties to avoid massive taxation.",
        educationPath: "LLB -> Wealth Management/Taxation background",
        additionalQualification: "Deep operational knowledge of high-end real estate markets.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 Years",
        certifications: ["Wealth Management / Tax Planning Certifications"],
        skills: ["Capital Gains Tax Avoidance", "HNI Advisory", "Luxury Market Negotiation", "Discreet Dealmaking"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $200,000 per year",
        roadmap: ["Legal Consultant", "Senior HNI Advisor", "Director of Legal Strategy", "Private Wealth Partner"],
        governmentOpportunities: "None.",
        corporateOpportunities: "Employed directly by global luxury real estate brokerages and family offices.",
        lawFirmOpportunities: "Niche 'Private Client' practices handling billionaire assets.",
        workNature: "High-Level Networking, Tax Strategy & Bespoke Contract Drafting.",
        futureScope: "Extremely lucrative. Handling the personal, ultra-luxury real estate portfolios of billionaires requires absolute discretion and a brilliant understanding of tax-shielding.",
        jobDemandTrend: "Niche/Elite",
        summary: "The discreet strategic advisors structuring the ultra-luxury real estate purchases of billionaires to maximize investment and legally bypass massive taxation."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Property Litigation Lawyer",
        description: "The heavy artillery brought in when massive commercial developments collapse. They litigate multi-jurisdictional frauds involving thousands of homebuyers, massive builder bankruptcies, and collapsed REITs.",
        educationPath: "LLB -> Focus in Insolvency & Consumer Law",
        additionalQualification: "Ability to handle high-stress, mass-plaintiff situations.",
        competitiveExams: ["CLAT (PG) / State Entrances"],
        yearsOfStudy: "5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["National Consumer Disputes Redressal Commission (NCDRC)", "Insolvency Code (IBC)", "Class-Action Architecting", "Media Crisis Management"],
        salaryRange: "India: ₹8 LPA - ₹35 LPA | Global: $100,000 - $280,000 per year",
        roadmap: ["Litigation Associate", "Senior NCDRC Advocate", "Partner - Real Estate Insolvency", "Designated Senior Counsel"],
        governmentOpportunities: "Empanelled to prosecute massively fraudulent pyramid-scheme builders.",
        corporateOpportunities: "Hired heavily by groups of stalled homebuyers forming massive legal associations to seize incomplete buildings.",
        lawFirmOpportunities: "Highly specialized, highly visible elite litigation practices.",
        workNature: "High-Volume Appellate Litigation, Insolvency Seizures & Rapid Injunctions.",
        futureScope: "Highly visible and lucrative. When a multi-billion dollar housing developer goes bankrupt, these litigators command the national media representing thousands of ruined homebuyers.",
        jobDemandTrend: "High Demand",
        summary: "The relentless elite litigators seizing bankrupt megaprojects and fighting historic class-action consumer battles against fraudulent housing developers."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Law Researcher",
        description: "Operates largely out of academia or think-tanks. They research the sociological impact of archaic land-ceiling acts, the transition of agrarian societies to urban grids, and draft policies to digitize centuries-old chaotic land records.",
        educationPath: "LLB -> LLM in Property Law / Public Policy",
        additionalQualification: "Deep passion for sociological land-reform histories.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Relevant Fellowships"],
        skills: ["Land Reform Jurisprudence", "Agrarian Economics", "Policy Drafting", "Blockchain integration in Registries"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $100,000 per year",
        roadmap: ["Research Fellow", "Senior Policy Analyst", "Think-Tank Director", "Global Property Scholar"],
        governmentOpportunities: "The ultimate architects advising the Ministry of Rural Development on digitizing the archaic land registries via blockchain/DILRMP.",
        corporateOpportunities: "Consultants to massive mapping/GIS tech companies attempting to privatize land records.",
        lawFirmOpportunities: "Providing deep historical research for 'unicorn' constitutional land battles.",
        workNature: "Pure Legal Research, Academic Drafting & Government Adisory.",
        futureScope: "Critical for modernization. The absolute biggest anchor dragging down developing economies is unverified, chaotic land records. Researchers drafting the policies to digitize this are nation-building.",
        jobDemandTrend: "Stable within Policy/Gov",
        summary: "The visionary researchers designing the modern legal frameworks required to drag chaotic, colonial-era land registries into the digital future."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Law Professor",
        description: "Educates the next generation of transactional lawyers and civil litigators on the overwhelmingly dense Transfer of Property Act, Rent Control Acts, and complex municipal zoning grids.",
        educationPath: "LLB -> LLM -> Ph.D. in Real Estate/Property Law",
        additionalQualification: "Extensive publishing on urban gentrification or land reforms.",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Doctrinal Analysis", "Pedagogy", "Syllabus Modernization", "Academic Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean of specialized Property Institutes"],
        governmentOpportunities: "Permanent faculty in National Law Universities or National Institutes of Urban Affairs.",
        corporateOpportunities: "Frequently hired by massive real estate conglomerates to conduct specialized 'RERA up-skilling' workshops for their internal teams.",
        lawFirmOpportunities: "Called upon as expert witnesses regarding the strict interpretation of archaic property laws during billion-dollar tribunals.",
        workNature: "Teaching, Mentoring, and Producing Elite Academic Real Estate Theory.",
        futureScope: "Highly prestigious. Property runs the entire legal framework of a nation, and professors capable of perfectly explaining its chaotic origins are highly sought after.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic authorities who demystify archaic colonial property laws and modern RERA grids for the legal architects of the future."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Real Estate Contract Specialist",
        description: "A highly specialized commercial draftsperson focusing entirely on 'Leasing'. They draft the ironclad 10-year lock-in leases that allow global giants like Amazon or Apple to rent out millions of square feet in luxury commercial properties.",
        educationPath: "LLB -> Focus in Commercial Drafting",
        additionalQualification: "Extreme detail orientation and understanding of commercial HVAC/Maintenance logistics.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Lock-in Clauses", "Force Majeure Negotiation", "Commercial Rent Arbitrage", "Complex Indemnification"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $85,000 - $180,000 per year",
        roadmap: ["Leasing Associate", "Senior Commercial Counsel", "Partner - Commercial Real Estate", "Head of Leasing Strategy"],
        governmentOpportunities: "None.",
        corporateOpportunities: "Massive demand. Every tech giant opening new global headquarters requires these lawyers to aggressively negotiate the leases with massive mall/IT park owners.",
        lawFirmOpportunities: "A highly profitable, high-volume practice within general corporate boutiques.",
        workNature: "Intense Desk Drafting, Mega-Lease Negotiation & Commercial Structuring.",
        futureScope: "Extremely stable. The entire concept of modern corporate expansion runs on massive, highly complex leasing. These lawyers secure the legal foundation of global tech hubs.",
        jobDemandTrend: "High Demand",
        summary: "The meticulous drafting experts finalizing the highly complex, multi-million dollar corporate leases that house global tech and retail conglomerates."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Property Investment Legal Advisor",
        description: "A hybrid between an investment banker and a lawyer. They orchestrate massive cross-border capital flows into domestic real estate, assuring foreign billionaires and funds that their $500M investment is legally secure under local laws.",
        educationPath: "LLB -> MBA / LLM in International Finance",
        additionalQualification: "Fluency in Foreign Direct Investment (FDI) guidelines.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["International Taxation Diplomas"],
        skills: ["FEMA Mastery", "Cross-Border Wealth Re-patriation", "Joint-Venture Law", "Offshore Structuring"],
        salaryRange: "India: ₹12 LPA - ₹35 LPA | Global: $130,000 - $280,000 per year",
        roadmap: ["Investment Associate", "Foreign Capital Strategist", "Partner - Real Estate M&A", "Global Private Equity Head"],
        governmentOpportunities: "Advising the Ministry of Commerce on easing FDI caps regarding massive housing projects.",
        corporateOpportunities: "Employed directly by massive sovereign wealth funds (e.g., ADIA) investing in foreign real estate markets.",
        lawFirmOpportunities: "The most elite 'FDI in Real Estate' desks in global law firms.",
        workNature: "Structuring Foreign Wealth Integration, Off-Shore Advisory & Deal Architecting.",
        futureScope: "Highly lucrative. As global capital furiously hunts for returns in rapidly developing nations, lawyers who can securely pipeline that money into local skyscrapers make phenomenal wealth.",
        jobDemandTrend: "Elite / High Demand",
        summary: "The ultimate cross-border architects, structuring the massive, highly complex flow of foreign sovereign wealth into booming domestic real estate markets."
    },
    {
        domain: "Law",
        branch: "Real Estate / Property Law",
        title: "Urban Development Legal Consultant",
        description: "The legal visionaries behind 'Smart Cities'. They merge complex municipal zoning, renewable energy integration, and massive public-private partnership (PPP) contracts to legally build entire new tech cities from scratch.",
        educationPath: "LLB -> Masters in Urban/Infrastructure Policy",
        additionalQualification: "Understanding of hyper-modern smart-grid technology and surveillance laws.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 Years",
        certifications: ["Sustainable Development Policies"],
        skills: ["PPP Contract Mastery", "Municipal Zoning Overhauls", "Data Privacy Intersections (Smart Cities)", "Bureaucratic Future-Casting"],
        salaryRange: "India: ₹10 LPA - ₹30 LPA | Global: $100,000 - $220,000 per year",
        roadmap: ["Urban Policy Associate", "Senior Smart-City Counsel", "PPP Partner", "Global Urbanization Consultant"],
        governmentOpportunities: "The lead architects advising the Ministry of Urban Affairs on 'Smart City' legal transformations.",
        corporateOpportunities: "Hired by massive infrastructure conglomerates looking to privately run entire municipal grids (e.g., Tata/Reliance).",
        lawFirmOpportunities: "Extremely high-level 'Projects & Infrastructure' consulting.",
        workNature: "Urban Future Mapping, Mega-PPP Negotiations & Municipal Advisory.",
        futureScope: "A visionary frontier. As developing nations construct entirely new, AI-integrated mega-cities, lawyers must invent entirely new legal frameworks to successfully govern them.",
        jobDemandTrend: "Rapidly Emerging / Visionary",
        summary: "The visionary legal architects designing the massive government-corporate contracts required to physically build the AI-integrated mega-cities of the future."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Real Estate / Property Law" });
        await Career.insertMany(realEstateLawProfessions);
        console.log('Real Estate and Property Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
