const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const ayurvedaProfessions = [
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Physician (Vaidya / Kayachikitsa Specialist)",
        description: "Primary care holistic doctors who diagnose illnesses using traditional methods like pulse diagnosis (Nadi Pariksha) and treat patients using herbal medicines, diet regulations, and lifestyle changes.",
        summary: "General Ayurvedic doctors treating systemic diseases holistically with herbs and lifestyle adjustments.",
        skills: ["Pulse Diagnosis (Nadi Pariksha)", "Prakriti (Body Constitution) Analysis", "Herbal Pharmacognosy", "Holistic Patient Counseling", "Dietary Prescription"],
        salaryRange: "India: ₹4L - ₹15L | Global: $60K - $120K",
        educationPath: "BAMS (Bachelor of Ayurvedic Medicine and Surgery) → MD in Kayachikitsa (Internal Medicine)",
        yearsOfStudy: "5.5 to 8.5 Years",
        industriesHiring: ["Ayurvedic Hospitals", "Wellness Retreats", "Private Clinics", "Government Dispensaries"],
        futureScope: "High. As global interest in holistic, preventive, and natural medicine surges, Ayurvedic physicians are highly sought after to manage chronic, lifestyle-induced diseases.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Maximum. Roles in AYUSH ministries, state dispensaries, and national rural health missions.",
        freelanceOpportunities: "Maximum. Independent practice is the most common and lucrative path.",
        fieldWork: "Low. Entirely clinic based.",
        riskLevel: "Low",
        certifications: ["Registration with Central Council of Indian Medicine (CCIM) / State Boards"],
        internshipRequirements: "One year mandatory rotatory clinical internship.",
        roadmap: ["Junior Vaidya", "Consultant Ayurvedic Physician", "Chief Medical Officer", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Panchakarma Specialist",
        description: "Specialize strictly in 'Panchakarma'—the five intense, deep-cleansing detoxification and rejuvenation therapies of Ayurveda using medicated oils, enemas, and emesis.",
        summary: "Specialists administering deep Ayurvedic detox therapies to cure chronic systemic diseases.",
        skills: ["Panchakarma Protocol Execution (Vamana, Virechana, Basti)", "Pulse Monitoring", "Anatomy & Physiology", "Therapist Supervision"],
        salaryRange: "India: ₹5L - ₹18L | Global: $70K - $130K",
        educationPath: "BAMS → MD in Panchakarma",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Premium Luxury Wellness Resorts", "Specialized Panchakarma Hospitals", "Global Holistic Centers"],
        futureScope: "Explosive growth globally. Medical tourism for authentic Panchakarma is a multi-million dollar industry, creating immense demand for certified specialists.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High. Specialized Panchakarma units in state hospitals.",
        freelanceOpportunities: "High. Traveling consultants for luxury spas.",
        fieldWork: "Low. Hospital/Spa based.",
        riskLevel: "Moderate (Managing intense physical reactions during severe detoxifications)",
        certifications: ["MD Panchakarma Registration"],
        internshipRequirements: "Hundreds of hours supervising live detoxification procedures.",
        roadmap: ["Resident Doctor", "Panchakarma Specialist", "Wellness Director", "Retreat Owner"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Surgeon (Shalya Tantra Specialist)",
        description: "Perform ancient yet scientifically validated surgical procedures, using specialized Ayurvedic instruments, techniques, and unique herbal-mineral healing pastes.",
        summary: "Surgical specialists combining ancient Ayurvedic surgery techniques with modern medical knowledge.",
        skills: ["Surgical Precision", "Wound Management (Vrana)", "Handling Specialized Instruments (Yantra/Shastra)", "Anatomy", "Infection Control"],
        salaryRange: "India: ₹6L - ₹20L | Global: Varied (Subject to country-specific surgical licenses)",
        educationPath: "BAMS → MS in Shalya Tantra (General Surgery)",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Ayurvedic Medical Colleges", "AYUSH Hospitals", "Private Surgical Nursing Homes"],
        futureScope: "Highly stable in India. Ayurvedic surgeons are legally permitted to perform dozens of specified general surgeries.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Surgical postings in primary health centers and district hospitals.",
        freelanceOpportunities: "Moderate. Visiting surgeon for multiple clinics.",
        fieldWork: "Low. Operating Theater (OT) based.",
        riskLevel: "High (Surgical risks, bleeding, infection liability)",
        certifications: ["MS (Ayurveda) Surgical Registration"],
        internshipRequirements: "Rigorous 3-year surgical residency.",
        roadmap: ["Surgical Resident", "Ayurvedic Surgeon", "Chief Surgeon", "Hospital Director"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Kshara Sutra Specialist (Anorectal Surgeon)",
        description: "A highly demanded surgical subset of Shalya Tantra specializing entirely in treating complex fistulas, piles, and fissures using medicated alkaline threads (Kshara Sutra).",
        summary: "Famed Ayurvedic specialists using medicated threads to painlessly cure complex severe anorectal diseases.",
        skills: ["Kshara Sutra Ligation", "Proctology Anatomy", "Pain Management", "Post-operative Care"],
        salaryRange: "India: ₹8L - ₹30L+ | Global: $80K - $150K",
        educationPath: "BAMS → MS (Shalya Tantra) → Specialized Training/Fellowship in Kshara Sutra",
        yearsOfStudy: "8.5 to 9 Years",
        industriesHiring: ["Specialized Proctology Clinics", "Ayurvedic Hospitals", "Corporate Chains specializing in Piles"],
        futureScope: "Extremely lucrative. Kshara Sutra has a higher success rate globally for complex fistulas than conventional allopathic surgery, driving immense patient volume.",
        jobDemandTrend: "Explosive Growth (Niche)",
        governmentJobs: "High. Specific postings in district hospitals.",
        freelanceOpportunities: "Maximum. Establishing an independent \"Piles/Fistula Clinic\" is highly profitable.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Surgical complications in sensitive areas)",
        certifications: ["Kshara Sutra Certification"],
        internshipRequirements: "Extensive surgical residency specifically in the anorectal region.",
        roadmap: ["Resident", "Consultant Proctologist", "Kshara Sutra Expert", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Gynecologist & Obstetrician (Prasuti Tantra & Stri Roga)",
        description: "Provide complete healthcare for women according to Ayurveda, including natural fertility enhancement, prenatal care (Garbh Sanskar), and treating gynecological disorders like PCOS.",
        summary: "Specialists in women’s health, using Ayurveda to treat infertility, PCOS, and manage natural pregnancies.",
        skills: ["Garbh Sanskar (Prenatal Regimen)", "Treatment of Infertility", "Managing Menstrual Disorders", "Counseling", "Basic Ultrasound Understanding"],
        salaryRange: "India: ₹5L - ₹18L | Global: $70K - $120K",
        educationPath: "BAMS → MS in Prasuti Tantra and Stri Roga",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Maternity Homes", "Ayurvedic Fertility Clinics", "Women's Wellness Centers"],
        futureScope: "Massive demand. Ayurveda is highly effective and heavily sought after for managing lifestyle-induced infertility, endometriosis, and PCOS without severe hormones.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Maximum. Medical officer roles in women’s wards of district hospitals.",
        freelanceOpportunities: "High. Independent women’s wellness and fertility clinics.",
        fieldWork: "Low. Clinic and Maternity ward based.",
        riskLevel: "Moderate (Handling pregnancies and potential delivery complications)",
        certifications: ["MS (Ayurveda) Gyn & Obs Registration"],
        internshipRequirements: "Intensive 3-year residency delivering babies and managing female disorders.",
        roadmap: ["Resident Doctor", "Consultant Gynecologist", "Fertility Expert", "Maternity Center Head"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Pediatrician (Kaumarabhritya Specialist)",
        description: "Specialize in the health, immunity-building, and treatment of diseases in infants and children (from birth to adolescence), heavily emphasizing natural immunity boosters like Swarna Prashana.",
        summary: "Ayurvedic doctors focusing purely on babies and children, emphasizing natural immunity and growth.",
        skills: ["Swarna Prashana Administration", "Child Psychology", "Gentle Therapeutics", "Nutritional Counseling for Children"],
        salaryRange: "India: ₹4L - ₹12L | Global: $60K - $100K",
        educationPath: "BAMS → MD in Kaumarabhritya (Bal Roga)",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Pediatric Ayurvedic Clinics", "General Hospitals", "Special Education Centers (for developmental delays)"],
        futureScope: "Growing steadily. Modern parents increasingly prefer natural, non-antibiotic treatments to build their children's baseline immunity with Ayurveda.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate. Roles in child welfare centers.",
        freelanceOpportunities: "High. Running independent pediatric holistic clinics.",
        fieldWork: "Low.",
        riskLevel: "Low to Moderate (Treating medically fragile infants)",
        certifications: ["MD (Ayurveda) Registration"],
        internshipRequirements: "Residency in pediatric wards managing child health crises.",
        roadmap: ["Pediatric Resident", "Consultant Ayurvedic Pediatrician", "Clinic Director"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Pharmacist / Formulator (Rasashastra & Bhaishajya Kalpana)",
        description: "Focus entirely on the complex science of formulating, purifying, and scaling the mass manufacturing of Ayurvedic medicines, herbal syrups, and herbo-mineral compounds.",
        summary: "The industrial scientists designing, purifying, and manufacturing exact Ayurvedic medicines.",
        skills: ["Herbo-Mineral Purification (Shodhana)", "Industrial Scaling", "Quality Control", "Pharmacognosy", "Knowledge of Heavy Metal toxicity protocols"],
        salaryRange: "India: ₹5L - ₹20L | Global: $80K - $130K",
        educationPath: "BAMS → MD in Rasashastra & Bhaishajya Kalpana OR B.Pharm (Ayurveda)",
        yearsOfStudy: "4 to 8.5 Years",
        industriesHiring: ["FMCG Wellness Giants (Patanjali, Dabur, Himalaya)", "Ayurvedic Manufacturing Plants", "Research Labs"],
        futureScope: "Explosive. The global market for Ayurvedic supplements and cosmetics is a multi-billion dollar industry requiring expert formulators to ensure safety and scale.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High. Drug inspectors and quality control experts for state AYUSH boards.",
        freelanceOpportunities: "Maximum. Lucrative consulting for beauty/wellness startups creating new herbal product lines.",
        fieldWork: "Low. Laboratory and Industrial Plant based.",
        riskLevel: "Moderate (Industrial manufacturing hazards, exposure to raw heavy metals before purification)",
        certifications: ["Pharmacy/Formulation certifications"],
        internshipRequirements: "Working physically with large-scale industrial vats and pharmaceutical testing machinery.",
        roadmap: ["Formulation Scientist", "Production Manager", "R&D Head", "VP of Manufacturing"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Dietitian / Nutritionist (Ahara Vijnana Specialist)",
        description: "Design highly personalized diet plans based exclusively on a patient's Ayurvedic 'Dosha' (Vata, Pitta, Kapha), the current season (Ritucharya), and their specific medical condition.",
        summary: "Dietitians using ancient Ayurvedic principles of body constitution to cure diseases through food alone.",
        skills: ["Dosha Assessment", "Deep Dietary Knowledge (Ahara)", "Patient Empathy", "Behavior Modification Counseling"],
        salaryRange: "India: ₹3.5L - ₹10L | Global: $50K - $90K",
        educationPath: "BAMS or B.Sc/Diploma in Ayurvedic Nutrition",
        yearsOfStudy: "2 to 5.5 Years",
        industriesHiring: ["Wellness Retreats", "High-end Spas", "Ayurvedic Hospitals", "Sports Ashrams"],
        futureScope: "High demand. Integration of specialized 'Dosha' diet plans is a massive trend in global wellness, weight-loss, and holistic centers.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Online consultation and running independent diet clinics.",
        fieldWork: "Low. Entirely consulting/office based.",
        riskLevel: "Low",
        certifications: ["Ayurvedic Nutrition/Dietetics Diploma"],
        internshipRequirements: "Drafting hundreds of customized meal plans.",
        roadmap: ["Ayurvedic Nutritionist", "Senior Diet Consultant", "Wellness Program Director"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Preventive Medicine & Yoga Expert (Swasthavritta & Yoga)",
        description: "Integrate Ayurvedic daily routines (Dinacharya), seasonal routines (Ritucharya), and specialized therapeutic Yoga to proactively prevent diseases and manage community health.",
        summary: "Specialists fighting lifestyle diseases proactively by combining Ayurvedic routines and Yoga therapy.",
        skills: ["Therapeutic Yoga Instruction", "Lifestyle Counseling", "Public Health Intervention", "Preventive Healthcare Modeling"],
        salaryRange: "India: ₹4L - ₹12L | Global: $60K - $100K",
        educationPath: "BAMS → MD in Swasthavritta and Yoga",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Naturopathy Centers", "Corporate Wellness Programs", "Yoga Ashrams", "Government Health Schemes"],
        futureScope: "Growing aggressively. Preventive medicine is heavily funded to combat the massive global rise in metabolic diseases (diabetes, hypertension).",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Organizing mass Yoga and wellness camps for state bodies.",
        freelanceOpportunities: "High. Corporate wellness coaching.",
        fieldWork: "Moderate. Conducting community training programs.",
        riskLevel: "Low",
        certifications: ["MD Registration / Quality Council Yoga Certifications"],
        internshipRequirements: "Conducting community health outreach and therapeutic yoga classes.",
        roadmap: ["Medical Officer", "Preventive Health Consultant", "Director of Wellness Initiatives"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Psychiatrist / Psychologist (Manasa Roga Specialist)",
        description: "Treat mental health disorders—such as severe anxiety, depression, insomnia, and schizophrenia—using Ayurvedic herbs, detoxification (Shirodhara), and deep psychological counseling (Sattvavajaya Chikitsa).",
        summary: "Mental health experts using Ayurvedic neurology, herbs, and therapies to treat psychiatric disorders.",
        skills: ["Psychiatric Evaluation", "Shirodhara Administration", "Patient Empathy", "Meditation/Counseling Techniques", "Neurological Pharmacy"],
        salaryRange: "India: ₹5L - ₹15L | Global: $70K - $110K",
        educationPath: "BAMS → MD in Manovijnana evum Manasa Roga",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Psychiatric Clinics", "Rehabilitation Centers", "Ayurvedic Hospitals"],
        futureScope: "High niche demand. A massive demographic is desperately seeking alternatives to heavy, addictive allopathic psychiatric medications for anxiety and depression.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum. Independent holistic mental health clinics.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Managing severe, unpredictable psychiatric crises)",
        certifications: ["MD Registration (Psychiatry subset)"],
        internshipRequirements: "Residency in psychiatric wards.",
        roadmap: ["Ayurvedic Psychiatrist", "Senior Consultant", "Director of Holistic Rehab Center"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Toxicologist (Agada Tantra)",
        description: "Specialize in the study, diagnosis, and treatment of all poisons (toxins, snake bites, insect stings) and heavy metal toxicities using specific Ayurvedic antidotes.",
        summary: "Specialists treating natural poisonings, modern toxic exposure, and venomous bites.",
        skills: ["Crisis Stabilization", "Deep knowledge of Antidotes", "Forensic Autopsy (in some jurisdictions)", "Identification of flora/fauna"],
        salaryRange: "India: ₹4L - ₹10L | Global: N/A (Highly region specific)",
        educationPath: "BAMS → MD in Agada Tantra (Toxicology and Forensic Medicine)",
        yearsOfStudy: "8.5 Years",
        industriesHiring: ["Rural Government Hospitals", "Forensic Departments", "Ayurvedic Medical Colleges"],
        futureScope: "Niche but critical in rural areas (specifically South India) where deaths from snake and scorpion bites remain extremely high.",
        jobDemandTrend: "Stable (Niche)",
        governmentJobs: "Maximum. Employed in rural primary health centers to treat localized poisonings.",
        freelanceOpportunities: "Low. Acute emergency care role.",
        fieldWork: "Low.",
        riskLevel: "Moderate",
        certifications: ["MD Registration"],
        internshipRequirements: "Handling live emergency poisonings.",
        roadmap: ["Medical Officer", "Toxicology Consultant", "Department Head"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Dermatologist (Twak Roga Specialist)",
        description: "Focus entirely on complex, chronic skin and hair diseases (like Psoriasis, Eczema, Vitiligo, severe acne) using continuous blood purification herbs, leeches, and dietary regimens.",
        summary: "Holistic skin specialists aggressively treating severe, chronic dermatology issues through blood purification.",
        skills: ["Leech Therapy (Jalaukavacharana)", "Visual Diagnostics of Skin Pathology", "Blood Cleansing Protocols", "Aesthetic Sensibility"],
        salaryRange: "India: ₹6L - ₹20L+ | Global: $70K - $120K",
        educationPath: "BAMS → MD/Specialized Training in Dermatology (Twak Roga)",
        yearsOfStudy: "5.5 to 8.5 Years",
        industriesHiring: ["Cosmetology Clinics", "Skin Specialty Hospitals", "Self-Employment"],
        futureScope: "Extremely lucrative. Patients with chronic autoimmune skin diseases like Psoriasis often turn to Ayurveda when steroids fail them, providing a constant massive patient base.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum. Running an independent holistic dermatology/trichology clinic is highly profitable.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["Specific training in Ayurvedic Dermatology"],
        internshipRequirements: "Extensive OPD executing leech therapy and managing chronic skin lesions.",
        roadmap: ["Resident Doctor", "Consultant Dermatologist", "Cosmetology Center Owner"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Medical Officer (AMO)",
        description: "Act as the primary administrative and clinical authority in government-run clinics, tasked with expanding rural healthcare access and implementing state-sponsored holistic health policies.",
        summary: "Government doctors heavily managing both clinical treatment and rural public health administration.",
        skills: ["Clinical Diagnostics", "Public Health Administration", "Record Keeping", "Resource Management", "Community Outreach"],
        salaryRange: "India: ₹6L - ₹12L | Global: N/A",
        educationPath: "BAMS → State Public Service Commission Examination",
        yearsOfStudy: "5.5 Years",
        industriesHiring: ["State Health Departments", "National Rural Health Mission (NRHM)", "Military (Paramilitary forces)"],
        futureScope: "Highly secure. Government jobs provide lifelong security, pensions, and consistent career progression regardless of market forces.",
        jobDemandTrend: "Stable",
        governmentJobs: "Maximum. 100% government sector role.",
        freelanceOpportunities: "Low (Usually restricted by government service rules).",
        fieldWork: "Moderate. Managing community medical camps.",
        riskLevel: "Low",
        certifications: ["State Medical Council Registration"],
        internshipRequirements: "Rural postings.",
        roadmap: ["Ayurvedic Medical Officer", "Senior Medical Officer", "District AYUSH Officer", "State Director of AYUSH"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Marma Therapist (Vital Energy Point Specialist)",
        description: "A highly specialized master who applies precise pressure to the body’s 107 vital energy points (Marma points) to treat paralysis, chronic pain, and nerve damage.",
        summary: "The Ayurvedic equivalent of acupressure/martial-arts masters, healing severe nerve and muscular damage via energy points.",
        skills: ["Deep Knowledge of the 107 Marma Points", "Pranic Healing", "Orthopedic Anatomy", "Physical Strength and Precision"],
        salaryRange: "India: ₹4L - ₹12L | Global: $60K - $100K",
        educationPath: "BAMS/Physiotherapy → Intense apprenticeship/diploma in Marma Chikitsa",
        yearsOfStudy: "5.5 to 7 Years",
        industriesHiring: ["Ayurvedic Orthopedic Centers", "Sports Rehabilitation Clinics", "Luxury Spas"],
        futureScope: "High niche demand. Highly requested for sports injuries, sciatica, and post-stroke rehabilitation.",
        jobDemandTrend: "Stable (Niche)",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Highly sought after individual specialists.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Incorrect pressure on Marma points can cause severe physiological harm)",
        certifications: ["Marma Therapy Certification"],
        internshipRequirements: "Years of practical apprenticeship under a master therapist.",
        roadmap: ["Marma Trainee", "Consultant Marma Therapist", "Master Healer / Teacher"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Nadi Pariksha Specialist (Pulse Diagnosis Expert)",
        description: "Masters who evaluate a patient's physical and mental diseases, past history, and future predispositions entirely by feeling the subtle rhythmic patterns of the pulse at the wrist.",
        summary: "Elite diagnosticians who can identify complex internal diseases simply by reading the pulse.",
        skills: ["Extreme Tactile Sensitivity", "Deep understanding of Dosha subtleties", "Concentration", "Intuitive Synthesis"],
        salaryRange: "India: ₹6L - ₹25L+ | Global: $80K - $150K+",
        educationPath: "BAMS → Years of dedicated apprenticeship under a Nadi Guru",
        yearsOfStudy: "5.5 Years + Lifetime Apprenticeship",
        industriesHiring: ["Premium Wellness Foundations", "Independent Practice", "Visiting Consultant roles globally"],
        futureScope: "Extremely lucrative. True Nadi Pariksha experts are rare, and patients travel globally to consult with famous pulse-readers.",
        jobDemandTrend: "Explosive Growth (Niche)",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Operating as a highly paid touring consultant or exclusive private practitioner.",
        fieldWork: "Low.",
        riskLevel: "Low (Diagnostic role)",
        certifications: ["Nadi Pariksha Specialization"],
        internshipRequirements: "Thousands of hours feeling diverse pulses under expert supervision.",
        roadmap: ["Apprentice", "Consultant Nadi Vaidya", "Master Diagnostician / Guru"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Spa and Wellness Resort Director",
        description: "Cross into business management to oversee operations, therapeutic quality, hiring, and finances of massive luxury Ayurvedic retreats catering to high net-worth global tourists.",
        summary: "The medical-business executives running multi-million dollar luxury Ayurvedic retreats and spas.",
        skills: ["Hospitality Management", "Clinical Protocol Enforcement", "Sales/Marketing", "Client Relationship Management", "Team Leadership"],
        salaryRange: "India: ₹10L - ₹30L+ | Global: $100K - $180K",
        educationPath: "BAMS → MBA (Hospitality / Healthcare Management)",
        yearsOfStudy: "7.5 Years",
        industriesHiring: ["Luxury 5-Star Resort Chains", "Medical Tourism Companies", "Global Wellness Spas"],
        futureScope: "Extremely lucrative. Ayurvedic medical tourism is booming. Managing VIP clients requires a unique mix of medical credibility and high-end hospitality skills.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "None. Purely private luxury sector.",
        freelanceOpportunities: "Moderate. Consulting for new resorts to design their wellness menus.",
        fieldWork: "Low. Elite resort based.",
        riskLevel: "Low",
        certifications: ["Hospital/Spa Management Certifications"],
        internshipRequirements: "Management trainee roles in luxury medical spas.",
        roadmap: ["Duty Doctor / Consultant", "Wellness Manager", "General Manager", "Director of Global Wellness Operations"]
    },
    {
        domain: "Medical",
        branch: "Ayurveda",
        title: "Ayurvedic Researcher & Academician",
        description: "Work in laboratories to scientifically validate ancient Ayurvedic texts using modern pharmacology, publish peer-reviewed papers, and teach BAMS/MD students at universities.",
        summary: "The academic scientists proving Ayurvedic concepts in modern labs and educating the next generation of doctors.",
        skills: ["Scientific Writing / Publishing", "Research Methodology", "Didactic Teaching", "Grant Writing", "Modern Pharmacology"],
        salaryRange: "India: ₹6L - ₹18L | Global: $80K - $120K",
        educationPath: "BAMS → MD → Ph.D. in Ayurveda",
        yearsOfStudy: "10.5 to 13 Years",
        industriesHiring: ["Ayurvedic Universities", "Government Research Councils (CCRAS)", "Pharma R&D Divisions"],
        futureScope: "Crucial. Ayurveda requires massive modern scientific validation to be integrated globally. Researchers are heavily funded by state and global bodies.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. National research institutes and state professorships.",
        freelanceOpportunities: "Moderate. Consulting for pharmaceutical validation trials.",
        fieldWork: "Low. Academic campus and laboratory based.",
        riskLevel: "Low",
        certifications: ["Ph.D. / Peer-reviewed publications"],
        internshipRequirements: "Extensive academic fellowships.",
        roadmap: ["Research Scholar / Assistant Professor", "Associate Professor", "Principal Investigator", "Dean of University"]
    }
];

const seedAyurveda = async () => {
    try {
        await Career.deleteMany({ branch: "Ayurveda" });
        await Career.insertMany(ayurvedaProfessions);
        console.log('Ayurveda Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedAyurveda();
