const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const bankFinLawProfessions = [
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Banking Lawyer",
        description: "A comprehensive legal specialist ensuring banks operate legally within the strict boundaries set by central regulators. They handle institutional lending agreements, recover bad loans, and defend banks from consumer litigation.",
        educationPath: "LLB",
        additionalQualification: "Understanding of banking operations and central bank circulars.",
        competitiveExams: ["CLAT / State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["SARFAESI Act / RDDBFI Act", "Debt Recovery Tribunal (DRT) Procedures", "Retail Banking Law", "Litigation Defense"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $80,000 - $180,000 per year",
        roadmap: ["Banking Litigator", "In-House Legal Manager", "Senior Bank Counsel", "Legal Head (Retail Banking)"],
        governmentJobs: "Legal Officers in Public Sector Banks (e.g., SBI) via IBPS SO exams.",
        corporateOpportunities: "Massive demand across all retail and commercial banking sectors (HDFC, ICICI, Citi).",
        lawFirmOpportunities: "High volume retainer work from banks to handle mass loan-default litigation.",
        workNature: "DRT Litigation, Retail Loan Agreements & Default Recoveries.",
        futureScope: "Extremely stable. The banking sector is the lifeblood of the economy, and the legal machinery to secure and recover retail/commercial loans will always remain in massive demand.",
        jobDemandTrend: "High and Constant",
        summary: "The frontline defenders of retail and commercial banking, litigating defaults in specialized tribunals to secure the financial health of the bank."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Financial Regulatory Lawyer",
        description: "Operates at the macro-level, interpreting complex edicts from absolute regulators like the SEC, RBI, or SEBI. They predict how new banking laws will affect multi-national financial institutions and ensure absolute compliance.",
        educationPath: "LLB -> LLM in Financial Regulation",
        additionalQualification: "Deep macroeconomic understanding.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Capital Markets / Regulatory Diplomas"],
        skills: ["Regulatory Auditing", "Macro-Financial Forecasting", "RBI/SEBI Circular Synthesis", "Board-Level Communication"],
        salaryRange: "India: ₹10 LPA - ₹35 LPA | Global: $120,000 - $250,000 per year",
        roadmap: ["Regulatory Analyst", "Senior Regulatory Counsel", "Chief Compliance Officer", "Global Regulatory Head"],
        governmentJobs: "Recruited directly by Central Banks (RBI) and Securities Regulators as policy drafters.",
        corporateOpportunities: "Employed in the C-suite of massive global financial conglomerates.",
        lawFirmOpportunities: "An elite consulting department within Tier-1 general corporate law firms.",
        workNature: "Desk Policy Parsing, Regulator Liaising & Strategic Compliance Auditing.",
        futureScope: "Highly lucrative. A single misinterpretation of a central bank's regulatory circular can cost a multinational bank billions in fines; these lawyers explicitly prevent that.",
        jobDemandTrend: "Elite / High Demand",
        summary: "The macro-strategists parsing through immensely complex central bank regulations to safely steer global financial conglomerates."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Banking Compliance Lawyer",
        description: "Focuses relentlessly on internal audits to prevent massive financial crimes. They build the rigid legal frameworks that stop money laundering (AML) and terrorist financing (KYC/CFT) from infiltrating the bank's systems.",
        educationPath: "LLB -> CS / CA Background (Optional but highly coveted)",
        additionalQualification: "Understanding of international anti-money laundering (AML) frameworks.",
        competitiveExams: ["None required for practice"],
        yearsOfStudy: "4 to 5 Years",
        certifications: ["Certified Anti-Money Laundering Specialist (CAMS)"],
        skills: ["AML / KYC Regulations", "Financial Auditing", "Cross-Border Tax Laws (FATCA)", "Fraud Interdiction"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $190,000 per year",
        roadmap: ["Compliance Analyst", "AML Legal Manager", "Director of Financial Crimes", "Chief Compliance Officer"],
        governmentJobs: "Advising the Enforcement Directorate (ED) or Financial Intelligence Units (FIU).",
        corporateOpportunities: "Mandatory in every single bank and financial institution globally.",
        lawFirmOpportunities: "Conducting massive independent structural audits for banks ahead of global mergers.",
        workNature: "Internal Auditing, Designing KYC Architecture & Regulator Reporting.",
        futureScope: "Exploding. As global governments crack down exponentially on terrorist financing and tax havens, compliance lawyers possessing CAMS certification have literally unfireable jobs.",
        jobDemandTrend: "Explosive and Mandated",
        summary: "The rigorous internal auditors legally fortifying banks against multi-billion dollar fines triggered by money launderers and global financial criminals."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Investment Banking Legal Advisor",
        description: "The elite deal-structurers sitting on Wall Street or Dalal Street. They do not litigate; they legally architect colossal Initial Public Offerings (IPOs), multi-billion dollar corporate buyouts, and sovereign wealth fund investments.",
        educationPath: "LLB -> MBA / LLM in Finance",
        additionalQualification: "Must understand complex financial modeling and corporate valuation techniques.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Capital Markets Law", "M&A Structuring", "Prospectus Drafting (Red Herring)", "Intense Deal Negotiation"],
        salaryRange: "India: ₹12 LPA - ₹50+ LPA | Global: $150,000 - $400,000+ per year",
        roadmap: ["Capital Markets Associate", "Senior Investment Counsel", "Partner - M&A/Capital Markets", "General Counsel (Private Equity)"],
        governmentJobs: "None. This is the absolute apex of the private sector.",
        corporateOpportunities: "Hired internally by 'Bulge Bracket' Investment Banks (Goldman Sachs, Morgan Stanley).",
        lawFirmOpportunities: "The highest billing, most brutal, and most prestigious department in global Tier-1 law firms.",
        workNature: "Intense M&A Drafting, IPO Prospectus Authoring & High-Stakes Financial Dealmaking.",
        futureScope: "The absolute pinnacle of wealth in the legal field. When billions of dollars change hands during an acquisition or IPO, these lawyers take a fractional cut that amounts to phenomenal wealth.",
        jobDemandTrend: "Hyper-Elite / Cutthroat",
        summary: "The apex financial architects legally orchestrating the massive mergers, acquisitions, and IPOs that define the global economy."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Financial Transactions Lawyer",
        description: "The mechanics of massive debt. Whenever a corporation needs $500 million to build a dam or a highway, these lawyers write the highly complex, multi-party 'Syndicated Loan' contracts that secure the debt against future revenue.",
        educationPath: "LLB",
        additionalQualification: "Deep understanding of Project Finance and structured debt mechanisms.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Syndicated Lending", "Asset-Backed Securitization", "Debt Restructuring", "Flawless Commercial Drafting"],
        salaryRange: "India: ₹10 LPA - ₹30 LPA | Global: $110,000 - $250,000 per year",
        roadmap: ["Transactions Associate", "Senior Debt Strategist", "Partner - Banking & Finance", "Global Finance Head"],
        governmentJobs: "Advising state infrastructure funds on receiving international loans (World Bank / ADB).",
        corporateOpportunities: "Massive reliance by corporate treasury departments taking on institutional debt.",
        lawFirmOpportunities: "A massive, extremely stable revenue center for top corporate law firms.",
        workNature: "Intense Desk Drafting, Mega-Loan Negotiation & Cross-Border Debt Structuring.",
        futureScope: "Extremely stable. The entire global infrastructure and corporate expansion model runs on massive syndicated debt; these lawyers are the ones who safely write the contracts for it.",
        jobDemandTrend: "High and Constant",
        summary: "The incredibly detail-oriented draftspeople structuring the colossal, multi-bank loans that fund global infrastructure and corporate expansion."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Banking Litigation Lawyer",
        description: "The aggressive courtroom fighters of the financial sector. They act when massive corporate loans default, brutally litigating in tribunals to seize corporate assets, factories, and airplanes to recover the bank's money.",
        educationPath: "LLB",
        additionalQualification: "Mastery of Insolvency frameworks.",
        competitiveExams: ["State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Insolvency and Bankruptcy Code (IBC)", "NCLT/NCLAT Advocacy", "Asset Tracing", "Rapid Injunctions"],
        salaryRange: "India: ₹8 LPA - ₹40+ LPA | Global: $120,000 - $300,000+ per year",
        roadmap: ["Litigation Associate", "Senior NCLT Practitioner", "Insolvency Partner", "Designated Senior Counsel (Finance)"],
        governmentJobs: "Empanelled by state-run banks to ruthlessly recover bad corporate debt.",
        corporateOpportunities: "Hired heavily by Asset Reconstruction Companies (ARCs) whose entire business is buying and recovering bad loans.",
        lawFirmOpportunities: "Highly lucrative practice areas dominating the National Company Law Tribunals.",
        workNature: "High-Volume Tribunal Battles, Corporate Asset Seizure & Complex Appellate Litigation.",
        futureScope: "Recession-proof. When the economy booms, transaction lawyers make money. When the economy crashes and corporations default, bankruptcy litigators make historic fortunes recovering the debt.",
        jobDemandTrend: "Very High / Always Stable",
        summary: "The aggressive tribunal litigators who utilize unforgiving bankruptcy laws to seize corporate assets and recover multi-million dollar defaulted bank loans."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Loan & Credit Legal Specialist",
        description: "Operates at the consumer retail level, finalizing the legalities of thousands of mortgages, auto loans, and micro-finance lending. They conduct title searches on properties to ensure the bank can legally seize them if the loan defaults.",
        educationPath: "LLB",
        additionalQualification: "Deep knowledge of local real-estate property laws and title verification.",
        competitiveExams: ["None specific"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Property Title Search", "Transfer of Property Act", "Retail Loan Origination", "Local Language Fluency"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $120,000 per year",
        roadmap: ["Title Searcher", "Retail Loan Manager", "Regional Mortgage Legal Head", "Independent Property Advocate"],
        governmentJobs: "Occasional roles in state housing finance corporations.",
        corporateOpportunities: "The absolute backbone of Non-Banking Financial Companies (NBFCs) and retail mortgage lenders.",
        lawFirmOpportunities: "High-volume outsourced title-search work for independent specialized chambers.",
        workNature: "High-Volume Property Due Diligence, Registry Navigation & Loan Documentation.",
        futureScope: "Extremely stable. The consumer credit market (home loans, car loans) is scaling massively, requiring an army of local specialists to verify the underlying collateral.",
        jobDemandTrend: "High Volume / Geographically Broad",
        summary: "The localized property experts ensuring every single retail mortgage is legally bulletproof by flawlessly verifying the underlying real estate titles."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Banking Risk & Compliance Officer (Legal)",
        description: "A hybrid risk-manager and lawyer. They stress-test the bank's entire legal exposure to massive external shocks—such as a sudden change in crypto regulations, global boycotts, or an unprecedented economic pandemic crash.",
        educationPath: "LLB -> MBA in Financial Risk",
        additionalQualification: "Advanced understanding of Basel III/IV capital adequacy norms.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Financial Risk Manager (FRM) optional but elite"],
        skills: ["Systemic Risk Analysis", "Stress Testing Portfolios", "Basel Norms Compliance", "Executive Advising"],
        salaryRange: "India: ₹10 LPA - ₹30 LPA | Global: $110,000 - $220,000 per year",
        roadmap: ["Risk Analyst", "Legal Risk VP", "Director of Enterprise Risk", "Chief Risk Officer (CRO)"],
        governmentJobs: "Advising Central Banks on macro-prudential regulations to prevent systemic banking collapses.",
        corporateOpportunities: "Mandatory C-Suite advisory roles in every 'Systemically Important' bank (Too Big To Fail).",
        lawFirmOpportunities: "Specialized systemic advisory during mega-mergers.",
        workNature: "Macro-Economic Analysis, Legal Stress-Testing & Global Regulatory Compliance.",
        futureScope: "Crucial. After the 2008 financial crash, governments globally mandated that banks retain incredibly powerful internal 'Risk Officers' to prevent the bank from taking legally catastrophic gambles.",
        jobDemandTrend: "High and Mandated",
        summary: "The internal stress-testers predicting and legally shielding the bank against massive, economy-destroying regulatory or financial shockwaves."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Securities & Financial Markets Lawyer",
        description: "The absolute masters of the stock market. They govern mutual funds, hedge funds, and insider trading allegations, ensuring that trillions of dollars flowing through the stock exchanges happen without illegal market manipulation.",
        educationPath: "LLB -> CS / CA Background Highly Preferred",
        additionalQualification: "Deep understanding of equity derivatives, futures, and high-frequency trading.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 Years",
        certifications: ["Capital Market Modules (NISM)"],
        skills: ["SEBI / SEC Act Mastery", "Insider Trading Defense", "Mutual Fund Structuring", "Market Manipulation Compliance"],
        salaryRange: "India: ₹10 LPA - ₹40+ LPA | Global: $130,000 - $300,000+ per year",
        roadmap: ["Securities Associate", "Funds/Derivatives Counsel", "Partner - Capital Markets", "SEBI Adjudicator"],
        governmentJobs: "The core regulatory backbone of Securities Regulators (SEBI/SEC) and Stock Exchanges (BSE/NYSE).",
        corporateOpportunities: "In-house at Hedge Funds, massive Mutual Funds, and algorithmic trading firms.",
        lawFirmOpportunities: "Highly elite, massively profitable securities litigation/advisory departments.",
        workNature: "Structuring Massive Funds, Dealing with Stock Exchanges & Defending Insider Trading.",
        futureScope: "Extremely lucrative. As retail investment in the stock market reaches historic highs, the legal mechanisms to manage those trillions of dollars are in unprecedented demand.",
        jobDemandTrend: "Elite / Very High Demand",
        summary: "The ultimate rulers of the stock exchange, structuring massive investment funds and fiercely defending against billion-dollar market manipulation probes."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Financial Services Legal Consultant",
        description: "Operates broadly across the booming FinTech, insurance, and wealth-management sectors. They advise startups on how to offer fractional shares, peer-to-peer lending, or micro-insurance without operating as illegal unregulated banks.",
        educationPath: "LLB",
        additionalQualification: "Understanding of rapidly shifting digital payment architectures (UPI, Wallets, Neo-banks).",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["None specific"],
        skills: ["FinTech P2P Regulatory Arbitrage", "Payment Aggregator Guidelines", "InsurTech Compliance", "Venture Structuring"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $180,000 per year",
        roadmap: ["Consulting Associate", "Senior FinTech Advisor", "Partner - Digital Finance", "General Counsel (NeoBank)"],
        governmentJobs: "Advising the government on regulating rapid tech-driven financial inclusion architectures.",
        corporateOpportunities: "Massive demand in Insurance (InsurTech) and non-traditional digital lenders.",
        lawFirmOpportunities: "A required practice area for any firm dealing with Silicon Valley/Bengaluru startups.",
        workNature: "Strategic Innovation Advisory, Regulatory Mapping & Tech-Finance Structuring.",
        futureScope: "Explosive. The line between 'tech company' and 'bank' has vanished (e.g., Apple Pay, Google Pay). Lawyers who can navigate this regulatory gray-zone are incredibly valuable.",
        jobDemandTrend: "Rapidly Growing",
        summary: "The agile legal strategists guiding massive, disruptive FinTech and InsurTech companies safely through archaic banking regulations."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Banking Law Researcher",
        description: "Dives deep into the academic and geopolitical philosophy of money. They research CBDC (Central Bank Digital Currency), the transition away from the US Dollar, and the macroeconomic effects of global interest-rate legalities.",
        educationPath: "LLB -> LLM in Finance Law/Economics",
        additionalQualification: "Strong background in global macroeconomics.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Macro-financial Policy Synthesis", "CBDC Jurisprudence", "Academic Drafting", "Comparative Global Economics"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $120,000 per year",
        roadmap: ["Research Assistant", "Senior Financial Fellow", "Think-Tank Economist/Lawyer", "Reserve Bank Policy Advisor"],
        governmentJobs: "Hired heavily by the deep-research wings of Central Banks (RBI) and the Ministry of Finance.",
        corporateOpportunities: "Guiding the macroeconomic strategy for massive sovereign wealth funds.",
        lawFirmOpportunities: "Minimal. Purely academic / policy-driven.",
        workNature: "Intense Macro-Policy Research, Economic Publishing & Think-Tank Strategy.",
        futureScope: "Niche but globally influential. As physical fiat money disappears into purely digital central bank ledgers, researchers must invent the legalities of this entirely new global reality.",
        jobDemandTrend: "Stable within Academia/Think-Tanks",
        summary: "The macroeconomic visionaries researching the transition from physical money to digital currencies, drafting the theoretical frameworks for central banks."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Banking & Finance Law Professor",
        description: "Educates law students on the immensely dense technicalities of corporate finance, bankruptcy proceedings, and securities regulations, producing the highly technical lawyers the financial industry desperate requires.",
        educationPath: "LLB -> LLM -> Ph.D. in Financial Law",
        additionalQualification: "Extensive publishing on capital markets and insolvency reforms.",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Complex Financial Demystification", "Doctrinal Capital Markets Theory", "Pedagogy", "Academic Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $80,000 - $160,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Corporate Law", "Dean / Leading Financial Scholar"],
        governmentJobs: "Permanent faculty in National Law Universities or the National Institute of Securities Markets (NISM).",
        corporateOpportunities: "Frequently hired to run 'Executive Legal Education' up-skilling courses for in-house corporate banking teams.",
        lawFirmOpportunities: "Called upon as expert academic witnesses regarding the strict interpretation of arcane securities laws during tribunals.",
        workNature: "Teaching, Mentoring, and Producing Elite Corporate Legal Architecture.",
        futureScope: "Highly prestigious. Because corporate and financial law offers the highest paying jobs to students, professors who can actually teach it competently are aggressively headhunted by top universities.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic authorities demystifying the insanely complex algorithms of global financial law for the next generation of Wall Street and Dalal Street elite."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Corporate Finance Lawyer",
        description: "Not to be confused with a transaction lawyer. They manage the internal financial structure of a single massive corporation, legally deciding whether to issue new equity shares, sell off divisions, or hoard cash to optimize tax liabilities.",
        educationPath: "LLB -> CA/CS/MBA Preferred",
        additionalQualification: "Extreme proficiency in corporate balance sheets and valuation models.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Corporate Governance Diplomas"],
        skills: ["Capital Architecture Strategy", "Dividend Legality", "Share Buyback Regulations", "Tax/Finance Synergy"],
        salaryRange: "India: ₹10 LPA - ₹35 LPA | Global: $110,000 - $250,000 per year",
        roadmap: ["Corporate Finance Counsel", "Director of Capital Strategy", "Chief Financial/Legal Officer", "Board of Directors"],
        governmentJobs: "Advising on the disinvestment/privatization of massive state-owned assets (e.g., selling Air India).",
        corporateOpportunities: "The absolute nexus of the 'C-Suite'—operating interchangeably with the CFO.",
        lawFirmOpportunities: "High-level advisory roles for extremely massive corporate clients restructuring their entire financial architecture.",
        workNature: "Internal Valuation Strategy, Corporate Restructuring Advisory & Executive Board Reporting.",
        futureScope: "Extremely secure. The financial efficiency of a corporation directly dictates its stock price; lawyers who can engineer completely legal tax-efficient capital structures are invaluable to shareholders.",
        jobDemandTrend: "High for Hybrid (Law + Commerce) Talent",
        summary: "The ultimate corporate strategists, utilizing law to optimize the massive internal financial frameworks and share-structures of multi-billion dollar conglomerates."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "FinTech Legal Advisor",
        description: "The hyper-specialized lawyers for companies like Stripe, Paytm, or Plaid. They focus purely on the intersection of digital payment APIs, open-banking regulations, and completely bypassing traditional banking cartels.",
        educationPath: "B.Tech/Commerce -> LLB",
        additionalQualification: "Must fundamentally understand API architecture, Cloud computing, and digital cryptography.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 Years",
        certifications: ["Technology/Privacy Law Integrations"],
        skills: ["Payment Gateway Architectures", "RBI Digital Lending Guidelines", "Data Privacy Symbiosis", "API Contracting"],
        salaryRange: "India: ₹12 LPA - ₹40 LPA | Global: $130,000 - $280,000 per year",
        roadmap: ["FinTech Counsel", "Senior Digital Strategy Lawyer", "Partner - Tech/Finance", "General Counsel (Unicorn FinTech)"],
        governmentJobs: "Advising the NPCI (National Payments Corporation of India) on globalizing the UPI framework.",
        corporateOpportunities: "Massive demand in every digital payment aggregator and neo-bank globally.",
        lawFirmOpportunities: "The fastest growing practice area spanning tech and finance law domains.",
        workNature: "Structuring Digital Architectures, Vetting App Flows & Regulatory Arbitrage.",
        futureScope: "Explosive. FinTech is entirely replacing traditional banking. Lawyers who can fluently speak 'Software Engineering' while drafting 'Financial Compliance' command immense, bidding-war level salaries.",
        jobDemandTrend: "Hyper-Growth",
        summary: "The bridge between Silicon Valley and Wall Street, legally structuring the digital payment apps and APIs that are slowly destroying traditional banks."
    },
    {
        domain: "Law",
        branch: "Banking & Finance Law",
        title: "Banking Dispute Resolution Lawyer",
        description: "A specialized arbitrator who absolutely avoids litigation. When two massive global banks have a billion-dollar dispute over a syndicated loan failure, they hire this neutral lawyer to cleanly negotiate a private settlement behind closed doors.",
        educationPath: "LLB -> LLM in Corporate Arbitration",
        additionalQualification: "Deep operational respect within the elite global banking community.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["International Commercial Arbitration (e.g., CIArb)"],
        skills: ["High-Level Diplomacy", "Complex Financial Unwinding", "Confidentiality Enforcement", "Bilateral Dealmaking"],
        salaryRange: "India: ₹8 LPA - ₹30+ LPA | Global: $120,000 - $250,000+ per year",
        roadmap: ["Arbitration Associate", "Senior Commercial Mediator", "Partner - Arbitration", "Eminent Global Arbitrator"],
        governmentJobs: "Appointed to prestigious international arbitration panels (e.g., SIAC, LCIA).",
        corporateOpportunities: "Hired specifically by massive banks demanding rapid, private closure of embarrassing financial miscalculations.",
        lawFirmOpportunities: "Extremely lucrative niche within elite commercial dispute law firms.",
        workNature: "Intense Private Arbitration, Multi-Bank Negotiation & Elite Drafting.",
        futureScope: "Highly lucrative. A public tribunal battle over a failed trillion-dollar banking alliance destroys stock prices and causes market panics. Private, rapid arbitration is the only acceptable route.",
        jobDemandTrend: "Growing within Elite Spheres",
        summary: "The ultimate financial diplomats, rapidly and quietly resolving catastrophic billion-dollar disputes between global banks far away from the volatile public eye."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Banking & Finance Law" });
        await Career.insertMany(bankFinLawProfessions);
        console.log('Banking and Finance Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
