const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const sociologyProfessions = [
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Sociologist",
        description: "Study society, social institutions, and social relationships. They analyze how cultural, political, and economic trends impact human behavior in groups.",
        summary: "Researchers studying human society, cultural norms, and the institutions that govern human interaction.",
        skills: ["Qualitative Research", "Social Theory", "Data Analysis", "Cultural Sensitivity", "Report Writing"],
        salaryRange: "India: ₹4L - ₹15L | Global: $50K - $100K",
        educationPath: "B.A. Sociology → M.A. Sociology → Ph.D.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Government Agencies", "Research Institutes", "Marketing Firms"],
        futureScope: "Stable demand. Understanding shifting demographics is increasingly vital for both public policy and commercial marketing.",
        jobDemandTrend: "Stable",
        competitiveExams: ["UGC NET (for academia)"],
        governmentJobs: "High. Needed for census operations, demographic planning, and social welfare departments.",
        ngoOpportunities: "Extensive. Core researchers for global NGOs studying poverty, migration, and inequality.",
        fieldWork: "Frequent. Involves conducting interviews, ethnographies, and field observations across various communities.",
        roadmap: ["B.A. Sociology", "Research Assistant", "Lead Researcher", "Published Sociologist / Professor"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Social Researcher",
        description: "Focus on designing, managing, and analyzing surveys and focus groups to gather data on social issues, public opinion, or consumer behavior.",
        summary: "Data-driven analysts who conduct surveys to measure public opinion and social trends.",
        skills: ["Survey Design", "Statistical Software (SPSS/R)", "Focus Group Facilitation", "Data Visualization", "Demography"],
        salaryRange: "India: ₹3L - ₹12L | Global: $45K - $90K",
        educationPath: "B.A. Sociology/Statistics → M.A. Applied Social Research",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Polling Agencies", "Think Tanks", "Market Research Firms", "Media Networks"],
        futureScope: "High growth. Driven by the corporate and political need for accurate human behavior data.",
        jobDemandTrend: "Growing",
        competitiveExams: ["None."],
        governmentJobs: "Moderate. Contracted by statistical bureaus.",
        ngoOpportunities: "High. Employed to measure the effectiveness of humanitarian interventions.",
        fieldWork: "Moderate. Often involves coordinating survey teams in specific geographic areas.",
        roadmap: ["Bachelor's degree", "Field Interviewer / Junior Analyst", "Research Manager", "Director of Social Research"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Social Policy Analyst",
        description: "Evaluate the social impact of government policies (like healthcare, education, housing) and recommend legislative changes to improve public welfare.",
        summary: "Experts who evaluate how government laws actually impact the daily lives of citizens.",
        skills: ["Policy Evaluation", "Economics Basics", "Legislation Tracking", "Advocacy", "Systems Thinking"],
        salaryRange: "India: ₹5L - ₹18L | Global: $60K - $110K",
        educationPath: "B.A. Sociology → M.A. Public Policy (MPP) or Social Work",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Government Ministries", "Lobbying Firms", "Think Tanks", "Labor Unions"],
        futureScope: "Crucial role. As inequality grows globally, policy analysts are heavily relied upon to draft fair legislation.",
        jobDemandTrend: "Steady",
        competitiveExams: ["Civil Services, State PSCs"],
        governmentJobs: "High. Primarily work within welfare and housing departments.",
        ngoOpportunities: "Maximum. They are the ideological architects for major advocacy organizations.",
        fieldWork: "Low. Primarily desk-based research and political lobbying.",
        roadmap: ["Degree in Sociology/Policy", "Policy Assistant", "Senior Analyst", "Director of Policy Strategy"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "NGO Program Manager",
        description: "Design, implement, and oversee humanitarian and social welfare programs for Non-Governmental Organizations on a local or global scale.",
        summary: "The executives who run charitable operations, managing budgets, staff, and crisis interventions.",
        skills: ["Project Management", "Grant Writing", "Budgeting", "Cross-cultural Communication", "Crisis Intervention"],
        salaryRange: "India: ₹6L - ₹20L | Global: $55K - $120K",
        educationPath: "B.A. Sociology → Master of Social Work (MSW) or Development Studies",
        yearsOfStudy: "5 Years",
        industriesHiring: ["International NGOs (UNICEF, Oxfam)", "Local Charities", "Foundations"],
        futureScope: "High impact. Essential for distributing billions of dollars in philanthropic aid effectively.",
        jobDemandTrend: "Growing",
        competitiveExams: ["None."],
        governmentJobs: "Moderate. Often interface with government grant agencies.",
        ngoOpportunities: "Maximum. This is the pinnacle career path within the NGO sector.",
        fieldWork: "Very High. Often deployed to crisis zones, rural villages, or inner-city projects.",
        roadmap: ["Volunteer/Field Worker", "Program Coordinator", "Program Manager", "Country Director (NGO)"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Community Development Officer",
        description: "Work directly with marginalized or underdeveloped communities to identify their needs, secure funding, and build local infrastructure or educational programs.",
        summary: "Grassroots organizers helping local communities build resources and advocate for themselves.",
        skills: ["Community Organizing", "Empathy", "Resource Mobilization", "Conflict Resolution", "Local Languages"],
        salaryRange: "India: ₹3L - ₹10L | Global: $40K - $75K",
        educationPath: "B.A. Sociology / Social Work",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Municipal Governments", "Local Outreach Centers", "Religious Charities"],
        futureScope: "Steady demand at the local municipal level, serving as the bridge between government aid and the citizens.",
        jobDemandTrend: "Stable",
        competitiveExams: ["Municipal/Panchayat level exams (India)"],
        governmentJobs: "High. Often employed by city councils or rural development ministries.",
        ngoOpportunities: "High. Acting as the 'boots on the ground' for larger national charities.",
        fieldWork: "Maximum. Daily interaction directly within the assigned community.",
        roadmap: ["Social Work degree", "Field Organizer", "Community Manager", "Director of Community Services"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Social Impact Analyst",
        description: "Evaluate the social and environmental consequences of corporate actions or major infrastructure projects, ensuring they meet ESG (Environmental, Social, Governance) standards.",
        summary: "Corporate auditors who ensure businesses aren't harming society or the environment.",
        skills: ["ESG Frameworks", "Corporate Auditing", "Stakeholder Engagement", "Sustainability Reporting", "Ethics"],
        salaryRange: "India: ₹6L - ₹20L | Global: $65K - $120K",
        educationPath: "B.A. Sociology → MBA (Sustainability) / M.A. Social Entrepreneurship",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Consulting Firms (Big 4)", "Multinational Corporations", "Mining/Energy Sectors"],
        futureScope: "Explosive growth. As ESG regulations become mandatory worldwide, corporations desperately need social impact experts.",
        jobDemandTrend: "High Growth",
        competitiveExams: ["None."],
        governmentJobs: "Low.",
        ngoOpportunities: "Moderate. NGOs hire them to audit corporate partners.",
        fieldWork: "Moderate. Visiting factory floors, supply chain origins, or project sites.",
        roadmap: ["Sociology/Business degree", "ESG Analyst", "Senior Impact Consultant", "Chief Sustainability Officer"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Urban Sociologist",
        description: "Study city life, gentrification, urban decay, and the social structures of metropolitan areas. They help city planners design more equitable urban spaces.",
        summary: "Specialists analyzing city dynamics to help design better, more livable urban environments.",
        skills: ["Urban Planning Basics", "Spatial Analysis (GIS)", "Demographic Mapping", "Public Transport Systems", "Criminology"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $110K",
        educationPath: "B.A. Sociology → Master’s in Urban Planning / Urban Sociology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["City Planning Departments", "Real Estate Developers", "Urban Think Tanks"],
        futureScope: "Crucial. As global mega-cities expand rapidly, urban sociologists are needed to prevent slums and massive inequality.",
        jobDemandTrend: "Steady",
        competitiveExams: ["State Urban Planning Board Exams"],
        governmentJobs: "High. Work directly with mayors, transit authorities, and housing departments.",
        ngoOpportunities: "Moderate. Focused on housing rights and anti-gentrification advocacy.",
        fieldWork: "High. Studying neighborhoods, transit flows, and community spaces directly.",
        roadmap: ["Sociology degree", "Urban Researcher", "Urban Planner", "Director of City Planning"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Rural Development Officer",
        description: "Focus entirely on the economic, agricultural, and social advancement of rural and agrarian communities, addressing issues like poverty, healthcare access, and water rights.",
        summary: "Government or NGO agents dedicated to uplifting and modernizing rural villages.",
        skills: ["Agrarian Sociology", "Micro-finance Basics", "Water/Sanitation Management", "Resilience", "Local dialects"],
        salaryRange: "India: ₹4L - ₹12L | Global: $45K - $85K",
        educationPath: "B.A. Sociology → M.A. Rural Development",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Ministry of Rural Development", "Agricultural Cooperatives", "International Aid Agencies"],
        futureScope: "Vital in developing nations (like India) where massive populations still reside outside urban centers.",
        jobDemandTrend: "Stable, High Need",
        competitiveExams: ["UPSC, State PSCs, NABARD (India)"],
        governmentJobs: "Maximum. Often civil servants managing massive block-level budgets.",
        ngoOpportunities: "High. Working with charities providing rural healthcare and education.",
        fieldWork: "Maximum. Requires living in or constantly traveling to remote areas.",
        roadmap: ["Rural Development degree", "Block Development Officer", "District Manager", "State Director of Rural Affairs"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Human Rights Officer",
        description: "Investigate and document abuses of marginalized groups, minorities, or refugees. They build cases using sociological frameworks to demand legal or international intervention.",
        summary: "Field investigators documenting social injustices and advocating for basic human rights.",
        skills: ["International Human Rights Law", "Trauma-Informed Interviewing", "Documentation", "Risk Assessment", "Advocacy"],
        salaryRange: "India: ₹5L - ₹15L | Global: $55K - $110K",
        educationPath: "B.A. Sociology → M.A. Human Rights / International Law",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["United Nations (UNHCR)", "Amnesty International", "Human Rights Watch", "Legal Aid Centres"],
        futureScope: "Always crucial. They provide the sociological data necessary for international courts to prosecute human rights violations.",
        jobDemandTrend: "Competitive",
        competitiveExams: ["UN Young Professionals Programme (YPP)"],
        governmentJobs: "Low. Usually act as an independent watch-dog *against* governments.",
        ngoOpportunities: "Maximum. This is the core employment sector for this role.",
        fieldWork: "Maximum. Often deployed to conflict zones, refugee camps, or protest sites.",
        roadmap: ["Sociology/Human Rights degree", "Field Investigator", "Senior Human Rights Officer", "International Policy Director"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Social Demographer",
        description: "Study the statistical characteristics of human populations—such as birth rates, aging, migration, and mortality—to forecast future societal trends.",
        summary: "The statisticians of society, predicting how population shifts will change the world.",
        skills: ["Statistical Modeling", "Population Forecasting", "Epidemiology Basics", "Data Mining", "Quantitative Sociology"],
        salaryRange: "India: ₹6L - ₹16L | Global: $65K - $115K",
        educationPath: "B.A. Sociology/Math → M.A. Demography / Population Studies",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["National Census Bureaus", "Healthcare Planners", "Actuarial Firms", "Universities"],
        futureScope: "High impact. Demographers are sounding the alarm on aging populations (e.g., in Japan/Europe) and mass climate migration.",
        jobDemandTrend: "Steady",
        competitiveExams: ["UPSC (Indian Statistical Service)"],
        governmentJobs: "High. Running national census operations.",
        ngoOpportunities: "Moderate. Working with global health NGOs.",
        fieldWork: "Low. Primarily analyzing massive data sets via software.",
        roadmap: ["Demography Master's", "Junior Data Analyst", "Senior Demographer", "Chief Statistician"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Public Welfare Officer",
        description: "Administer state-sponsored welfare programs, evaluating applicants for food assistance, housing aid, unemployment benefits, and child protective services.",
        summary: "Government agents who distribute social safety net resources to citizens in crisis.",
        skills: ["Casework Management", "Regulatory Compliance", "Interviewing", "Crisis De-escalation", "Patience"],
        salaryRange: "India: ₹4L - ₹10L | Global: $45K - $80K",
        educationPath: "B.A. Sociology / Social Work",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Department of Social Services", "Child Welfare Agencies", "State Housing Authorities"],
        futureScope: "A permanent government pillar. Crucial for maintaining the social safety net during economic downturns.",
        jobDemandTrend: "Stable, High Turnover",
        competitiveExams: ["State Civil Service Exams"],
        governmentJobs: "Maximum. A purely municipal or state-level administrative role.",
        ngoOpportunities: "Low.",
        fieldWork: "Moderate. Conducting home visits to verify applicants' living conditions.",
        roadmap: ["Social Work degree", "Junior Caseworker", "Senior Supervisor", "Director of Social Services"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Corporate Social Responsibility (CSR) Manager",
        description: "Direct a corporation's philanthropic initiatives, ensuring the company gives back to the community via grants, volunteer programs, and environmental actions.",
        summary: "The executives managing a corporation's charitable giving and social image.",
        skills: ["Philanthropic Strategy", "Corporate Communications", "Budget Management", "Partnership Building", "Public Relations"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $75K - $140K",
        educationPath: "B.A. Sociology → MBA / Master’s in Social Entrepreneurship",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Major Corporations (Tech, Banks, Retail)", "Corporate Foundations"],
        futureScope: "Highly lucrative. Companies use strong CSR strategies not just for charity, but as a core component of their brand identity and recruitment.",
        jobDemandTrend: "High Growth",
        competitiveExams: ["None."],
        governmentJobs: "Low.",
        ngoOpportunities: "Moderate. They often partner with NGOs to execute the corporate grants.",
        fieldWork: "Moderate. Visiting the sites of the charity projects they have funded.",
        roadmap: ["Sociology/Business degree", "CSR Coordinator", "CSR Manager", "VP of Corporate Responsibility"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Social Survey Specialist",
        description: "Specialists within the polling industry who craft the exact psychological wording and methodologies of questionnaires to ensure unbiased demographic representation.",
        summary: "Methodology experts who design the complex psychological surveys used in political and market research.",
        skills: ["Psychometrics", "Questionnaire Design", "Bias Reduction Methodologies", "A/B Testing", "Behavioral Sociology"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $95K",
        educationPath: "B.A. Sociology/Psychology → M.A. Social Research",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Market Research Giants (Nielsen)", "Academic Institutes", "Political Campaigns"],
        futureScope: "Stable. Flawed surveys ruin multi-million dollar marketing campaigns; experts who can eliminate 'leading questions' are highly valued.",
        jobDemandTrend: "Steady",
        competitiveExams: ["None."],
        governmentJobs: "Moderate. Designing surveys for public health awareness.",
        ngoOpportunities: "Low to Moderate.",
        fieldWork: "Low.",
        roadmap: ["Research degree", "Survey Analyst", "Methodology Specialist", "Director of Research Design"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Gender Studies Researcher",
        description: "Analyze the social construction of gender, the intersectionality of race and class, and how patriarchal or systemic biases affect economics, politics, and culture.",
        summary: "Academics studying how gender roles and systemic inequalities shape modern society.",
        skills: ["Feminist Theory", "Intersectionality Frameworks", "Historical Analysis", "Advocacy", "Academic Publishing"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $95K",
        educationPath: "B.A. Sociology → M.A. Gender Studies → Ph.D.",
        yearsOfStudy: "8 Years",
        industriesHiring: ["Universities", "Diversity & Inclusion (DEI) Corporate Departments", "Policy Think Tanks"],
        futureScope: "Significant societal impact. Their academic work directly informs modern civil rights legislation and corporate DEI policies.",
        jobDemandTrend: "Steady (Academic), Growing (Corporate DEI)",
        competitiveExams: ["UGC NET (for academia)"],
        governmentJobs: "Moderate. Advising ministries of women and child development.",
        ngoOpportunities: "High. Working with international global rights organizations.",
        fieldWork: "Moderate. Depending on specific sociological research topics.",
        roadmap: ["M.A./Ph.D. in Gender Studies", "Research Assistant / Junior Faculty", "Published Author", "Tenured Professor / Head of DEI"]
    },
    {
        domain: "Arts",
        branch: "Sociology",
        title: "Social Statistics Analyst",
        description: "Combine heavy data science with sociological theory to process massive datasets (e.g., social media behavior, national crime stats) into actionable insights.",
        summary: "Data scientists specializing in mapping human behavior and macroscopic societal trends.",
        skills: ["Python/R Programming", "Machine Learning basics", "Big Data Analysis", "Criminology/Sociology theory", "Data Storytelling"],
        salaryRange: "India: ₹7L - ₹22L | Global: $75K - $130K",
        educationPath: "B.A. Sociology → M.Sc. Data Science / Quantitative Methods",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Tech Giants (Meta, X)", "Government Intelligence", "Academic Research Centres"],
        futureScope: "Explosive. The future of sociology is computational. Analyzing billions of social media interactions requires deep sociological understanding mixed with code.",
        jobDemandTrend: "High Growth",
        competitiveExams: ["None."],
        governmentJobs: "High. State intelligence and massive public databases (like Aadhaar/Census).",
        ngoOpportunities: "Moderate. Utilizing data to track global aid efficacy.",
        fieldWork: "Low. A purely quantitative, tech-focused role.",
        roadmap: ["Sociology degree + Coding Bootcamp", "Data Analyst", "Senior Computational Sociologist", "Lead Social Data Scientist"]
    }
];

const seedSociology = async () => {
    try {
        await Career.deleteMany({ branch: "Sociology" });
        await Career.insertMany(sociologyProfessions);
        console.log('Sociology Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedSociology();
