const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const veterinaryScienceProfessions = [
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Companion Animal Veterinarian (Small Animal Practitioner)",
        description: "Primary care physicians entirely dedicated to diagnosing and treating household pets (dogs, cats, rabbits). They provide routine vaccinations, perform basic surgeries (spay/neuter), and manage chronic pet diseases.",
        summary: "The classic local \"vet\" providing holistic and surgical care primarily for family dogs and cats.",
        skills: ["Small Animal Anatomy", "Canine/Feline Internal Medicine", "Owner Empathy/Counseling", "Basic Soft-Tissue Surgery", "Vaccination Protocols"],
        salaryRange: "India: ₹4L - ₹15L | Global: $85K - $130K",
        educationPath: "BVSc & AH (Bachelor of Veterinary Science and Animal Husbandry) / DVM externally",
        yearsOfStudy: "5.5 to 8 Years",
        industriesHiring: ["Private Pet Clinics", "Corporate Veterinary Chains (e.g., Banfield, VCA)", "Animal Shelters (NGOs)"],
        futureScope: "Explosive. The 'pet humanization' trend means owners are willing to spend massive amounts of money on advanced healthcare for their pets, guaranteeing lifelong demand.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate. Mostly in municipal pet health camps.",
        freelanceOpportunities: "Maximum. Over 70% of vets eventually open their own private, highly lucrative clinics.",
        fieldWork: "Low. Entirely clinic based.",
        riskLevel: "Moderate (High risk of severe bites, scratches, and extreme emotional burnout/compassion fatigue)",
        certifications: ["State/National Veterinary Council Registration"],
        internshipRequirements: "One year mandatory rotatory clinical internship.",
        roadmap: ["Junior Associate Vet", "Senior Clinic Veterinarian", "Clinic Owner / Practice Partner"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Large Animal / Livestock Veterinarian",
        description: "Focus entirely on massive agricultural animals—cattle, sheep, pigs, and goats. These vets travel extensively to farms to ensure herd health, deliver calves, and prevent disease outbreaks that could collapse the food supply.",
        summary: "The roaming farm doctors protecting global food supplies and treating massive livestock.",
        skills: ["Bovine/Equine/Porcine Anatomy", "Herd Disease Management", "Reproductive Ultrasonography", "Extreme Physical Strength", "Field Surgery under non-sterile conditions"],
        salaryRange: "India: ₹6L - ₹14L | Global: $90K - $140K",
        educationPath: "BVSc & AH → MD/Specialization in Livestock Health",
        yearsOfStudy: "5.5 to 8 Years",
        industriesHiring: ["Corporate Dairy/Beef Farms", "Government Agriculture Departments", "Independent Mobile Practices"],
        futureScope: "Highly secure and desperate for talent. Very few new graduates want the intense physical labor of treating massive farm animals, creating a massive global shortage and high pay.",
        jobDemandTrend: "Very High (Severe Shortage)",
        governmentJobs: "Maximum. The backbone of central and state animal husbandry departments.",
        freelanceOpportunities: "Maximum. Operating entirely out of specialized \"mobile clinic\" trucks serving multiple farms.",
        fieldWork: "Maximum. Driving hundreds of miles weekly to rural, muddy terrains.",
        riskLevel: "High (Extreme physical danger from trampling/kicking by 2,000lb animals, plus zoonotic infections)",
        certifications: ["Large Animal Veterinary Certifications"],
        internshipRequirements: "Grueling outdoor internships in massive commercial dairies or ranches.",
        roadmap: ["Field Vet", "Herd Health Consultant", "State Director of Animal Husbandry"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Equine Veterinarian",
        description: "A highly elite, specialized branch of large animal medicine focusing exclusively on horses—ranging from family ponies to multi-million dollar Olympic showjumpers and thoroughbred racehorses.",
        summary: "Elite specialists treating horses, dealing heavily with sports medicine, joint injections, and racing injuries.",
        skills: ["Equine Sports Medicine / Lameness Exams", "Portable Digital Radiography", "Equine Colic Surgery", "Handling High-Net-Worth VIP Owners"],
        salaryRange: "India: ₹8L - ₹25L | Global: $95K - $180K+",
        educationPath: "BVSc / DVM → Equine Internship → Residency in Equine Surgery/Medicine",
        yearsOfStudy: "6.5 to 10 Years",
        industriesHiring: ["Polo/Racing Turf Clubs", "Elite Equestrian Breeding Farms", "Army Remount Veterinary Corps"],
        futureScope: "Extremely lucrative niche. Treating racehorses involves massive insurance sums and cutting-edge sports therapies (like stem-cell joint injections).",
        jobDemandTrend: "Stable (Niche)",
        governmentJobs: "Moderate. Military (Cavalry/Police horses).",
        freelanceOpportunities: "Maximum. Many operate purely as mobile consultants to the richest horse farms.",
        fieldWork: "High. Traveling aggressively to racetracks and breeding barns.",
        riskLevel: "High (Horses are hyper-reactive prey animals weighing half a ton)",
        certifications: ["Specialization in Equine Medicine/Surgery"],
        internshipRequirements: "Specialized 1-2 year internships specifically at equine-only hospitals.",
        roadmap: ["Equine Intern", "Associate Equine Vet", "Partner at Equine Practice", "Chief Racecourse Veterinarian"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Surgeon (Board Certified)",
        description: "The elite specialists who perform incredibly complex orthopedic (bone plating, joint replacements) and soft-tissue (tumor removal, deep abdominal) surgeries on animals, taking referrals from standard local vets.",
        summary: "Expert surgeons performing complex bone, joint, and cancer surgeries that regular vets cannot handle.",
        skills: ["Advanced Surgical Anatomy", "Arthroscopy and Bone Plating", "Complex Tissue Grafting", "Micro-surgery", "Surgical Leadership"],
        salaryRange: "India: ₹12L - ₹30L | Global: $180K - $350K+",
        educationPath: "BVSc / DVM → General Internship → 3-Year Surgical Residency",
        yearsOfStudy: "10 to 12 Years",
        industriesHiring: ["Massive 24/7 Specialty Referral Hospitals", "Veterinary Universities"],
        futureScope: "Extremely lucrative and in high demand. General practitioners now refer almost all complex fractures and tumors to boarded surgeons rather than risking it themselves.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low. Almost entirely lucrative private sector.",
        freelanceOpportunities: "High. \"Mobile Surgeons\" travel to regular clinics to perform specialized operations in their OTs.",
        fieldWork: "Low. Dedicated specialty surgical suites.",
        riskLevel: "Low to Moderate (High malpractice liability)",
        certifications: ["Diplomate of the American/European College of Veterinary Surgeons (DACVS/DECVS) or MVSc (Surgery)"],
        internshipRequirements: "Brutal, highly competitive multi-year surgical residencies.",
        roadmap: ["Surgical Resident", "Board Certified Surgeon", "Head of Surgery Department"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Oncologist",
        description: "Specialize entirely in diagnosing and treating cancer in animals using chemotherapy, advanced immunotherapy, and palliative care, drastically extending the quality of life for beloved pets.",
        summary: "Dedicated cancer specialists for animals, managing chemotherapy and advanced tumor care.",
        skills: ["Canine/Feline Oncology Pathology", "Chemotherapy Protocol Design", "Palliative Care", "Intense Grief Counseling for Owners"],
        salaryRange: "India: ₹10L - ₹25L | Global: $150K - $250K",
        educationPath: "BVSc / DVM → Internship → 3-Year Oncology Residency",
        yearsOfStudy: "10 to 12 Years",
        industriesHiring: ["Specialty Referral Centers", "Veterinary Universities"],
        futureScope: "Massive growth. Because pets live longer now, cancer is the leading cause of death in older dogs and cats. Owners will pay heavily for targeted oncology care.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "Moderate. Consulting on complex cases remotely.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Daily handling of highly toxic chemotherapeutic chemical agents)",
        certifications: ["Diplomate in Medical Oncology / MVSc (Medicine)"],
        internshipRequirements: "Residency managing terminal cancer wards in animals.",
        roadmap: ["Resident Doctor", "Boarded Oncologist", "Head of Veterinary Oncology"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Wildlife / Zoo Veterinarian",
        description: "The rarest and most wildly diverse veterinary path, treating exotic species ranging from tigers and elephants to exotic birds and reptiles, entirely in zoos, national parks, or wildlife sanctuaries.",
        summary: "The adrenaline-heavy elite treating lions, elephants, and exotic wildlife in zoos or massive reserves.",
        skills: ["Exotic/Avian/Reptile Anatomy", "Dart Gun Immobilization (Chemical Restraint)", "Massive Stress Management", "Conservation Science Mastery"],
        salaryRange: "India: ₹6L - ₹18L | Global: $75K - $120K",
        educationPath: "BVSc / DVM → Internships at Zoos → Residency in Zoological Medicine",
        yearsOfStudy: "10+ Years",
        industriesHiring: ["Government National Parks", "Major City Zoos", "Global Conservation NGOs (WWF)", "Exotic Animal Sanctuaries"],
        futureScope: "Extremely difficult to enter but highly prestigious. The scope is limited globally to the number of major zoos and funded conservation parks.",
        jobDemandTrend: "Stable (Extremely High Competition)",
        governmentJobs: "Maximum. The primary employer for national parks and state zoos.",
        freelanceOpportunities: "Low. Highly institutionalized.",
        fieldWork: "Maximum. Helicopters, jeeps, dealing with wild animal captures.",
        riskLevel: "Maximum (Daily interactions with apex predators; high risk of fatal maulings or accidental tranquilizer exposure)",
        certifications: ["Diplomate in Zoological Medicine / MVSc (Wildlife)"],
        internshipRequirements: "Fiercely competitive apprenticeships at major zoos handling exotic species.",
        roadmap: ["Zoo Intern", "Associate Veterinarian", "Chief Veterinarian of Zoo/Reserve"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Pathologist",
        description: "Work exclusively behind a microscope in a laboratory, never seeing the animal alive. They analyze biopsies, bodily fluids, and perform autopsies (necropsies) to tell the surgeon exactly what the disease is.",
        summary: "The brilliant lab-detectives deciding if a tumor is benign or cancer by looking at animal cells.",
        skills: ["Histopathology (Tissue analysis)", "Cytology", "Necropsy (Animal Autopsy)", "Broad multi-species cellular knowledge"],
        salaryRange: "India: ₹8L - ₹20L | Global: $140K - $220K",
        educationPath: "BVSc / DVM → 3-Year Residency in Anatomic/Clinical Pathology",
        yearsOfStudy: "9 to 11 Years",
        industriesHiring: ["Massive Diagnostic Labs (e.g., IDEXX, Antech)", "Universities", "Pharmaceutical Toxicology Labs"],
        futureScope: "Immense demand and massive salaries. Every single clinic sends tissue samples to these massive centralized labs to get a definitive diagnosis.",
        jobDemandTrend: "High",
        governmentJobs: "Moderate. State forensic pathology and disease control labs.",
        freelanceOpportunities: "High. Reading digital biopsy slides remotely from home (Tele-pathology).",
        fieldWork: "Low. Purely microscope/desktop based.",
        riskLevel: "Low to Moderate (Pathogen exposure during necropsy)",
        certifications: ["Board Certified Veterinary Pathologist / MVSc (Pathology)"],
        internshipRequirements: "Thousands of hours strictly reading slides and performing animal autopsies.",
        roadmap: ["Pathology Resident", "Board Certified Pathologist", "Director of Diagnostic Laboratory"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Public Health & Epidemiology Expert",
        description: "Protect the human population from 'zoonotic' diseases—viruses like Avian Flu, Rabies, or COVID-19 that jump from animals to humans. They map outbreaks rather than treating individual animals.",
        summary: "The global protectors stopping devastating diseases from jumping from animals into the human population.",
        skills: ["Epidemiological Statistics", "Food Safety Auditing", "Zoonotic Outbreak Tracing", "Mass Culling Protocols"],
        salaryRange: "India: ₹7L - ₹18L | Global: $90K - $150K",
        educationPath: "BVSc / DVM → Master of Public Health (MPH) or MVSc (Veterinary Public Health)",
        yearsOfStudy: "7.5 to 9 Years",
        industriesHiring: ["CDC", "World Health Organization (WHO)", "Department of Agriculture / Food Safety"],
        futureScope: "The most critical global defense role. As humans push into wildlife habitats, zoonotic pandemics will increase, making these vets the frontline of human defense.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Maximum. The core of national epidemiological defense.",
        freelanceOpportunities: "Low.",
        fieldWork: "Maximum. Deploying to outbreak 'Hot Zones' globally.",
        riskLevel: "High (Dealing with highly lethal, highly infectious zoonotic pathogens like Ebola or Nipah virus)",
        certifications: ["Specialization in Veterinary Preventive Medicine"],
        internshipRequirements: "Tracking live diseases in massive populations of livestock/wildlife.",
        roadmap: ["Field Epidemiologist", "Zoonotic Disease Specialist", "National Director of Veterinary Public Health"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Dentist",
        description: "Perform highly specialized root canals, extractions, massive jaw surgeries, and braces explicitly for animals. Dental disease is rampant in dogs and cats, making this a highly booked specialty.",
        summary: "Elite specialists performing root canals, jaw surgeries, and complex extractions for animals.",
        skills: ["Feline/Canine Odontology", "Complex Tooth Extractions", "Maxillofacial Surgery", "Veterinary Dental Radiography"],
        salaryRange: "India: ₹8L - ₹20L | Global: $160K - $250K",
        educationPath: "BVSc / DVM → Residency in Veterinary Dentistry",
        yearsOfStudy: "9 to 11 Years",
        industriesHiring: ["Specialty Referral Centers", "Private Dedicated Dental Veterinary Clinics"],
        futureScope: "Extremely lucrative. 80% of dogs over age 3 have severe dental disease, and general vets eagerly refer complicated extractions or cracked teeth to these specialists.",
        jobDemandTrend: "Very High",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Traveling consultant performing complex dental surgeries in general clinics.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Anesthetic risks for older, sick patients requiring dental care)",
        certifications: ["Board Certified Veterinary Dentist"],
        internshipRequirements: "Hundreds of hours performing microscopic root canals on animals.",
        roadmap: ["Dental Resident", "Veterinary Dentist", "Head of Dental Surgery"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Neurologist",
        description: "Diagnose and surgically treat extreme disorders of the animal nervous system, brain, and spine—such as repairing slipped discs in paralyzed dogs (IVDD) or managing severe epilepsy.",
        summary: "Brain and spine surgeons for animals, curing paralysis and massive neurological diseases.",
        skills: ["Spinal Surgery (Hemilaminectomy)", "MRI/CT Interpretation of the Brain", "Electromyography", "Neurological Localization Exams"],
        salaryRange: "India: ₹12L - ₹30L | Global: $200K - $350K+",
        educationPath: "BVSc / DVM → Internship → 3-Year Residency in Neurology/Neurosurgery",
        yearsOfStudy: "10 to 12 Years",
        industriesHiring: ["High-End Referral Neuro Centers", "University Surgical Hospitals"],
        futureScope: "Massive demand. The ability to completely cure a suddenly paralyzed dachshund with spinal surgery is considered \"miraculous\" by owners, ensuring constant high-value referrals.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "Low. Requires massive infrastructure (in-house MRI).",
        fieldWork: "Low.",
        riskLevel: "Moderate (Extreme precision required; surgical failure means permanent animal paralysis)",
        certifications: ["Board Certified Neurologist / Neurosurgeon"],
        internshipRequirements: "Brutal surgical residency mastering the animal spinal cord.",
        roadmap: ["Neurology Resident", "Consultant Neurologist", "Chief of Neurosurgery"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Emergency and Critical Care Veterinarian",
        description: "The ER doctors of the animal world, working intense overnight shifts handling pure adrenaline cases: hit-by-cars, massive poisonings, twisted stomachs (GDV), and performing emergency CPR.",
        summary: "The overnight adrenaline-junkies saving animals from massive trauma and immediate death.",
        skills: ["Triaging Mass Trauma", "Emergency Fluid Resuscitation", "Acute Toxicity Management", "Rapid Emergency Surgery (e.g., Splenectomy)", "Zero Hesitation"],
        salaryRange: "India: ₹8L - ₹20L | Global: $120K - $200K+",
        educationPath: "BVSc / DVM → Desired Residency in Emergency/Critical Care or extensive ER experience",
        yearsOfStudy: "6 to 10 Years",
        industriesHiring: ["24/7 Veterinary Emergency Hospitals"],
        futureScope: "Always desperate for talent. The overnight, high-stress shifts lead to massive burnout, meaning hospitals will pay premium salaries for doctors willing to work the ER.",
        jobDemandTrend: "Explosive Growth (Highest Shortage)",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. \"Relief Vets\" can charge massive hourly rates simply to cover overnight trauma shifts.",
        fieldWork: "Low. ER based.",
        riskLevel: "High (High bite risk, monumental emotional stress/burnout)",
        certifications: ["Diplomate in Emergency and Critical Care (Optional but highly paid)"],
        internshipRequirements: "Surviving the grueling pace of a 24/7 animal trauma center.",
        roadmap: ["ER Veterinarian", "Criticalist", "Medical Director of Emergency Services"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Anesthesiologist",
        description: "Calculate and administer complex, hyper-precise anesthetic drugs to keep medically fragile animals (with heart or kidney failure) safely unconscious and pain-free during massive surgeries.",
        summary: "The experts who ensure animals survive complex surgeries and wake up pain-free.",
        skills: ["Complex Pharmacokinetics", "Cardiovascular Monitoring Protocol", "Epidural/Local Nerve Blocks", "Resuscitation Mastery"],
        salaryRange: "India: ₹10L - ₹22L | Global: $180K - $260K+",
        educationPath: "BVSc / DVM → 3-Year Residency in Veterinary Anesthesia & Analgesia",
        yearsOfStudy: "10 to 11 Years",
        industriesHiring: ["Specialty Surgical Centers", "University Hospitals"],
        futureScope: "Extremely secure. Complex surgeons completely rely on the Anesthesiologist to keep the patient alive, making them the silent, indispensable power in the OT.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Low.",
        freelanceOpportunities: "High. Locum coverage for specialty hospitals lacking an anesthesiologist.",
        fieldWork: "Low. OT based.",
        riskLevel: "Moderate (Extreme liability; anesthesia deaths are heavily scrutinized)",
        certifications: ["Board Certified Veterinary Anesthesiologist"],
        internshipRequirements: "Managing thousands of complex, high-risk surgical anesthesias.",
        roadmap: ["Anesthesia Resident", "Boarded Anesthesiologist", "Head of Anesthesia and Pain Management"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Behaviorist",
        description: "The \"Psychiatrists\" of the animal world. They use neurochemistry (Prozac, Xanax) combined with deep behavioral modification to cure severe animal aggression, extreme anxiety, or phobias that trainers cannot fix.",
        summary: "Specialist psychiatrists fixing severe aggression and anxiety in animals using medication and therapy.",
        skills: ["Animal Psychopharmacology", "Ethology (Animal Behavior)", "Owner Re-education Techniques", "Deep understanding of Fear Pathways"],
        salaryRange: "India: ₹8L - ₹18L | Global: $100K - $160K",
        educationPath: "BVSc / DVM → Residency in Veterinary Behavior",
        yearsOfStudy: "9 to 11 Years",
        industriesHiring: ["Specialty Clinics", "Large Animal Shelters/Rescue Orgs", "Private Practice"],
        futureScope: "Massive unrecognized growth. As more rescue dogs present with severe trauma/aggression, normal vets refer them to Behaviorists as a \"last hope\" before euthanasia.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Completely remote tele-health consults are highly viable.",
        fieldWork: "Moderate. Doing \"in-home\" assessments of severe dog aggression.",
        riskLevel: "High (Routinely dealing with unpredictably aggressive, dangerous dogs)",
        certifications: ["Board Certified Veterinary Behaviorist"],
        internshipRequirements: "Managing severe clinical aggression and anxiety caseloads.",
        roadmap: ["Behavior Resident", "Veterinary Behaviorist", "Animal Shelter Consultant"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Avian/Exotic Pet Veterinarian",
        description: "Specialize entirely in the incredibly fragile anatomy of \"pocket pets\" and birds—treating parrots, ferrets, guinea pigs, iguanas, and sugar gliders, entirely avoiding dogs and cats.",
        summary: "Micro-specialists treating the incredibly complex, tiny anatomies of birds, reptiles, and ferrets.",
        skills: ["Avian/Reptile Anatomy", "Micro-surgery on tiny patients", "Avian Husbandry / Diet Analysis", "Specialized Exotic Anesthesia"],
        salaryRange: "India: ₹5L - ₹15L | Global: $85K - $140K",
        educationPath: "BVSc / DVM → Internship → Avian/Exotic Residency",
        yearsOfStudy: "9 to 11 Years",
        industriesHiring: ["Exclusive Exotic Pet Clinics", "High-End General Practices"],
        futureScope: "Extremely secure. Finding a vet who will confidently perform surgery on a 50-gram parakeet is nearly impossible, meaning these specialists are booked months in advance.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Low.",
        freelanceOpportunities: "High. Setting up an \"Exotics Only\" clinic is highly branded and successful.",
        fieldWork: "Low.",
        riskLevel: "Low to Moderate (Exotic animal bites/zoonotic diseases from reptiles)",
        certifications: ["Board Certified in Avian or Exotic Companion Mammal Medicine"],
        internshipRequirements: "Intense specialization dealing specifically with non-traditional pets.",
        roadmap: ["Exotics Intern", "Specialist Avian/Exotic Vet", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Technologist / Technician (Vet Tech)",
        description: "The absolute backbone of the clinic—essentially the \"nurses\" for animals. They draw blood, place IV catheters, induce anesthesia, take X-rays, and intensely monitor hospitalized pets while the vet performs surgery.",
        summary: "The elite animal nurses who handle blood draws, anesthesia, and intense ICU care.",
        skills: ["Jugular/Cephalic Venipuncture", "Anesthesia Induction/Monitoring", "Animal Restraint", "Dental Scaling", "Laboratory Diagnostics"],
        salaryRange: "India: ₹2L - ₹6L | Global: $40K - $65K",
        educationPath: "Diploma / B.Sc in Veterinary Technology or Animal Nursing",
        yearsOfStudy: "2 to 4 Years",
        industriesHiring: ["Every Private Clinic globally", "Specialty Centers", "Research Laboratories"],
        futureScope: "Most sought after clinic role. The veterinary industry is utterly crippled globally by a massive shortage of licensed technicians. They are hired instantly.",
        jobDemandTrend: "Explosive Growth (Massive Shortage)",
        governmentJobs: "High. Dispensary assistants and livestock inspectors.",
        freelanceOpportunities: "Moderate. Relief/Locum technicians are highly paid.",
        fieldWork: "Low.",
        riskLevel: "High (Take the brunt of animal handling, bites, scratches, and physical burnout)",
        certifications: ["Registered/Licensed Veterinary Technician (RVT/LVT)"],
        internshipRequirements: "Hundreds of clinical hours placing IVs and running lab work.",
        roadmap: ["Vet Assistant", "Vet Tech", "Lead Surgical Technician", "Practice Manager"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Regulatory / Pharmaceutical Veterinarian",
        description: "Never touch clinical practice. They work in massive pharmaceutical labs to ethically manage the lab animals, conduct research for new veterinary drugs (like flea/tick preventatives), or work for the FDA.",
        summary: "The corporate scientists designing and testing massive new vaccines and medicines for the veterinary market.",
        skills: ["Laboratory Animal Medicine (LAM)", "Strict Regulatory Compliance (FDA/USDA/EMA)", "Pharmacology R&D", "Corporate Boardroom Presentation"],
        salaryRange: "India: ₹10L - ₹30L | Global: $150K - $250K+",
        educationPath: "BVSc / DVM → Specialized Lab Animal Residency or Corporate Entry",
        yearsOfStudy: "6 to 10 Years",
        industriesHiring: ["Big Pharma (Zoetis, Boehringer Ingelheim)", "Corporate R&D", "Government Drug Regulatory Bodies"],
        futureScope: "Extremely lucrative, low stress, and zero weekend shifts. Big Pharma pours billions into pet medications, and these vets are the key authority.",
        jobDemandTrend: "Stable, Highly Competitive",
        governmentJobs: "High. FDA, USDA, or equivalent medical compliance officers.",
        freelanceOpportunities: "Low. Heavily corporate.",
        fieldWork: "Low. Lab and Corporate Office based.",
        riskLevel: "Low",
        certifications: ["Board Certified in Lab Animal Medicine (Optional)"],
        internshipRequirements: "Corporate pathways or Lab Animal residencies.",
        roadmap: ["Research Veterinarian", "Regulatory Director", "VP of Veterinary Medical Affairs"]
    },
    {
        domain: "Medical",
        branch: "Veterinary Science",
        title: "Veterinary Cardiologist",
        description: "Specialize entirely in the diagnosis and medical/surgical management of severe heart disease in animals, heavily utilizing advanced echocardiography and EKG to manage heart failure.",
        summary: "Heart specialists for animals, managing heart failure and performing advanced cardiac ultrasounds.",
        skills: ["Advanced Echocardiography (Ultrasound)", "Electrocardiogram (EKG) Analysis", "Cardiovascular Pharmacology", "Pacemaker Implantation"],
        salaryRange: "India: ₹12L - ₹28L | Global: $180K - $300K+",
        educationPath: "BVSc / DVM → Internship → 3-Year Cardiology Residency",
        yearsOfStudy: "10 to 12 Years",
        industriesHiring: ["Specialty Referral Centers", "University Teaching Hospitals"],
        futureScope: "Massive demand. Heart murmurs and eventual heart failure are extremely common in aging dogs and cats, generating massive, consistent referrals from general vets.",
        jobDemandTrend: "Very High",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Operating as a mobile cardiologist, performing echos inside general clinics.",
        fieldWork: "Low.",
        riskLevel: "Low to Moderate",
        certifications: ["Board Certified Veterinary Cardiologist"],
        internshipRequirements: "Intensive cardiology residency performing hundreds of echos.",
        roadmap: ["Cardiology Resident", "Board Certified Cardiologist", "Head of Cardiology Department"]
    }
];

const seedVeterinaryScience = async () => {
    try {
        await Career.deleteMany({ branch: "Veterinary Science" });
        await Career.insertMany(veterinaryScienceProfessions);
        console.log('Veterinary Science Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedVeterinaryScience();
