const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const socialWorkProfessions = [
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Clinical Social Worker",
        description: "Diagnose and treat mental, behavioral, and emotional disorders, providing therapy and counseling to individuals, families, and couples.",
        summary: "Licensed professionals providing mental health therapy and counseling services.",
        skills: ["Diagnostic Assessment", "Psychotherapy", "Empathy", "Crisis Intervention", "Active Listening"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $90K",
        educationPath: "B.A. Social Work (BSW) / Psychology → Master of Social Work (MSW)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Hospitals", "Mental Health Clinics", "Private Practice", "Schools"],
        futureScope: "High demand worldwide due to increasing awareness and de-stigmatization of mental health issues.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Roles in state-run hospitals and veteran affairs departments.",
        freelanceOpportunities: "Maximum. Many operate independent private therapy practices.",
        fieldWork: "Low. Primarily office or clinic-based counseling.",
        riskLevel: "Moderate (Emotional burnout and secondary trauma)",
        certifications: ["Licensed Clinical Social Worker (LCSW) credential is mandatory"],
        internshipRequirements: "Extensive supervised clinical hours (often 2,000-3,000 hours) post-master's.",
        roadmap: ["BSW", "MSW & Clinical Internships", "Licensed Social Worker", "Private Practice Owner / Clinical Director"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Child and Family Social Worker",
        description: "Protect vulnerable children and support families in need of assistance, intervening in cases of abuse, neglect, or extreme poverty.",
        summary: "Advocates who protect children and help families navigate social crises.",
        skills: ["Child Advocacy", "Risk Assessment", "De-escalation", "Legal/Court Navigation", "Resilience"],
        salaryRange: "India: ₹3L - ₹10L | Global: $45K - $80K",
        educationPath: "Bachelor of Social Work (BSW) → Master of Social Work (MSW)",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Child Protective Services (CPS)", "Foster Care Agencies", "NGOs"],
        futureScope: "Continuous, critical need. Unfortunately, the demand for child protection remains persistently high.",
        jobDemandTrend: "Stable, High Need",
        governmentJobs: "Maximum. The majority work directly for state child welfare departments.",
        freelanceOpportunities: "Low. Highly institutionalized and regulated.",
        fieldWork: "Maximum. Constant home visits, court appearances, and school meetings.",
        riskLevel: "High (Potential for aggressive encounters during child removals, high emotional toll)",
        certifications: ["State Social Work Licensure"],
        internshipRequirements: "Field placements in child welfare agencies during studies.",
        roadmap: ["Caseworker", "Senior Child Protective Specialist", "Agency Supervisor", "Director of Family Services"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "School Social Worker",
        description: "Address psychological and social problems that interfere with students' academic performance, handling bullying, truancy, and home issues.",
        summary: "Professionals stationed in schools to support students' emotional well-being and academic success.",
        skills: ["Youth Counseling", "Conflict Resolution", "Special Education Laws", "Parental Engagement"],
        salaryRange: "India: ₹3L - ₹9L | Global: $50K - $85K",
        educationPath: "B.A. Social Work (BSW) / Education → Master of Social Work (MSW)",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Public Schools", "Private Educational Institutions", "School Districts"],
        futureScope: "Growing as schools recognize that mental health is foundational to academic achievement.",
        jobDemandTrend: "Growing",
        governmentJobs: "High. Employed by public school districts.",
        freelanceOpportunities: "Low. Salaried educational staff.",
        fieldWork: "Low. Based within the school building.",
        riskLevel: "Low to Moderate",
        certifications: ["School Social Work Specialist (C-SSWS) depending on region"],
        internshipRequirements: "Internships within school counseling departments.",
        roadmap: ["School Social Worker", "District Social Work Coordinator", "Director of Student Services"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Medical Social Worker",
        description: "Provide support to patients and their families coping with chronic, acute, or terminal illnesses, helping them navigate the healthcare system and discharge planning.",
        summary: "Hospital-based advocates helping patients cope with severe illnesses and medical logistics.",
        skills: ["Medical Terminology Basics", "Grief Counseling", "Discharge Planning", "Insurance Navigation"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $90K",
        educationPath: "Bachelor of Social Work (BSW) → Master of Social Work (MSW)",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Hospitals", "Oncology Centers", "Hospice Care", "Nursing Homes"],
        futureScope: "High demand driven by an aging global population requiring extensive medical care and support.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Roles in government-run hospitals and public health networks.",
        freelanceOpportunities: "Low. Integrated into hospital care teams.",
        fieldWork: "Low to Moderate. Mostly hospital-based, occasional home hospice visits.",
        riskLevel: "Moderate (High emotional toll due to patient mortality)",
        certifications: ["Certified Social Worker in Health Care (C-SWHC)"],
        internshipRequirements: "Clinical rotations in hospital settings.",
        roadmap: ["Medical Social Worker", "Palliative Care Specialist", "Director of Hospital Social Work"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Substance Abuse / Addiction Counselor",
        description: "Advise individuals struggling with alcoholism, drug addiction, or other dependencies, developing treatment plans to support recovery.",
        summary: "Counselors dedicated to helping individuals overcome severe addictions.",
        skills: ["Addiction Psychology", "Relapse Prevention", "Motivational Interviewing", "Extreme Patience"],
        salaryRange: "India: ₹3L - ₹10L | Global: $45K - $80K",
        educationPath: "B.A. Psychology / BSW → Specialization/Master's in Addiction Studies",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Rehabilitation Centers", "Prisons", "Outpatient Clinics", "NGOs"],
        futureScope: "Regrettably high demand due to ongoing global crises with opioid and chemical dependencies.",
        jobDemandTrend: "High Demand",
        governmentJobs: "Roles in state-funded rehab programs and the corrections system.",
        freelanceOpportunities: "Moderate. Specialized private coaching/intervention services.",
        fieldWork: "Low. Mostly clinic or rehab-center based.",
        riskLevel: "Moderate (Dealing with unpredictable behavior from patients)",
        certifications: ["Certified Addictions Counselor (CAC) or Master Addiction Counselor (MAC)"],
        internshipRequirements: "Supervised hours in rehabilitation or detox facilities.",
        roadmap: ["Recovery Coach", "Addiction Counselor", "Clinical Supervisor", "Rehab Center Director"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Gerontological Social Worker",
        description: "Specialize in the physical, psychological, and social needs of the elderly population, helping them maintain their independence and quality of life.",
        summary: "Specialists dedicated to the welfare, healthcare navigation, and support of the elderly.",
        skills: ["Knowledge of Aging Processes", "Elder Abuse Detection", "Medicare/Healthcare Laws", "Empathy"],
        salaryRange: "India: ₹3L - ₹10L | Global: $50K - $85K",
        educationPath: "BSW → MSW with a specialization in Gerontology",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Nursing Homes", "Assisted Living Facilities", "Hospice", "Elderly Care NGOs"],
        futureScope: "One of the absolute fastest-growing fields due to the rapidly aging 'Baby Boomer' demographic.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Departments of Aging or senior welfare services.",
        freelanceOpportunities: "Moderate. Private care managers for wealthy families.",
        fieldWork: "Moderate. Visiting retirement communities and private homes.",
        riskLevel: "Low",
        certifications: ["Advanced Social Worker in Gerontology (ASW-G)"],
        internshipRequirements: "Practicums in nursing homes or senior centers.",
        roadmap: ["Elder Care Caseworker", "Geriatric Social Worker", "Director of Senior Services"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Forensic / Criminal Justice Social Worker",
        description: "Work within the justice system to assist inmates, newly released individuals, crime victims, and defendants with rehabilitation, court navigation, and societal reentry.",
        summary: "Social workers operating at the intersection of psychology, law, and the prison system.",
        skills: ["Criminal Law Basics", "Trauma-Informed Care", "Risk Assessment", "Conflict Resolution", "Boundaries"],
        salaryRange: "India: ₹4L - ₹12L | Global: $55K - $90K",
        educationPath: "BSW/Psychology / Criminal Justice → MSW",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Prisons / Department of Corrections", "Courts", "Victim Advocacy Non-profits", "Police Departments"],
        futureScope: "Growing as justice systems slowly transition from purely punitive models toward rehabilitation.",
        jobDemandTrend: "Growing",
        governmentJobs: "Maximum. Most are employed directly by the criminal justice system.",
        freelanceOpportunities: "Low. Expert witness consulting in court cases.",
        fieldWork: "High. Working inside prisons, courthouses, and parole offices.",
        riskLevel: "High (Working closely with convicted felons and trauma victims in high-security environments)",
        certifications: ["Forensic Social Work Certification"],
        internshipRequirements: "Placements in correctional facilities or court advocacy programs.",
        roadmap: ["Parole Caseworker", "Forensic Social Worker", "Prison Rehabilitation Director"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Corporate Social Responsibility Director",
        description: "Develop and oversee programs that ensure a corporation is ethically, environmentally, and socially beneficial to the public, managing large philanthropic budgets.",
        summary: "Professionals directing the charitable and ethical initiatives of major corporations.",
        skills: ["Corporate Strategy", "Public Relations", "Grant Allocation", "Sustainability", "Stakeholder Management"],
        salaryRange: "India: ₹8L - ₹30L | Global: $80K - $140K",
        educationPath: "MSW / MBA / B.A. Communications",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Fortune 500 Companies", "Large Tech Firms (Google, Microsoft)", "Major Manufacturing"],
        futureScope: "Highly lucrative. Consumers increasingly demand that corporations prove their social impact, making CSR a core business function.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Low. Strictly private sector.",
        freelanceOpportunities: "Moderate. CSR consultants.",
        fieldWork: "Low to Moderate. Traveling to oversee corporate-sponsored social projects.",
        riskLevel: "Low",
        certifications: ["CSR/Sustainability Certificates"],
        internshipRequirements: "Corporate internships in HR or CSR departments.",
        roadmap: ["CSR Coordinator", "CSR Manager", "Director of Social Impact", "Chief Sustainability Officer"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Military / Veteran Social Worker",
        description: "Provide counseling and transition assistance exclusively to active-duty military personnel, veterans, and their families, dealing heavily with PTSD and combat trauma.",
        summary: "Specialists assisting soldiers and veterans with trauma recovery and civilian reintegration.",
        skills: ["Trauma Therapy (EMDR, CBT)", "Military Culture Competency", "Crisis Intervention", "Resilience Building"],
        salaryRange: "India: ₹5L - ₹15L | Global: $65K - $100K",
        educationPath: "BSW → MSW + Clinical Licensure (LCSW)",
        yearsOfStudy: "6 Years",
        industriesHiring: ["Department of Veterans Affairs (VA)", "Military Bases", "Veteran Support NGOs"],
        futureScope: "Permanent and critical demand based on the immense psychological toll of military service.",
        jobDemandTrend: "Stable, High Need",
        governmentJobs: "Maximum. The vast majority work for the VA or directly for the military branches.",
        freelanceOpportunities: "Moderate. Private therapists specializing in veteran PTSD.",
        fieldWork: "Low. Primarily clinic-based on or near military bases.",
        riskLevel: "Moderate (Secondary trauma from severe combat stories)",
        certifications: ["Military Social Work Certificates"],
        internshipRequirements: "Clinical hours completed within VA hospitals or military clinics.",
        roadmap: ["Clinical Intern at VA", "Staff Social Worker", "PTSD Specialist", "Director of Veteran Support Services"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Psychiatric Social Worker",
        description: "Work specifically in psychiatric facilities or emergency wards with patients suffering from severe and complex mental illnesses (e.g., schizophrenia, severe bipolar disorder).",
        summary: "Highly specialized clinical workers managing the social care of severely mentally ill patients.",
        skills: ["Severe Psychopathology Knowledge", "Involuntary Commitment Laws", "De-escalation", "Psychiatric Assessment"],
        salaryRange: "India: ₹5L - ₹15L | Global: $65K - $95K",
        educationPath: "BSW → MSW + Clinical Licensure (LCSW)",
        yearsOfStudy: "6 Years",
        industriesHiring: ["Psychiatric Hospitals", "Emergency Rooms", "Mental Health Asylums"],
        futureScope: "High demand. Emergency psychiatric care is a severely understaffed sector globally.",
        jobDemandTrend: "High Demand",
        governmentJobs: "High. State-run psychiatric facilities.",
        freelanceOpportunities: "Low. Requires secure, institutional settings.",
        fieldWork: "Low. Confined to secure hospital wards.",
        riskLevel: "High (Interacting with actively psychotic or violently distressed patients)",
        certifications: ["LCSW required, Psychiatric specializations"],
        internshipRequirements: "Practicums in locked psychiatric wards.",
        roadmap: ["Psychiatric Case Worker", "Licensed Psychiatric Social Worker", "Clinical Supervisor", "Ward Director"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Community Organizer / Advocate",
        description: "Mobilize community members, build grassroots organizations, and lead campaigns to enact social, economic, or environmental changes at a local or systemic level.",
        summary: "Grassroots leaders rallying communities to fight for legislative or social changes.",
        skills: ["Public Speaking", "Grassroots Mobilization", "Campaign Strategy", "Networking", "Media Relations"],
        salaryRange: "India: ₹3L - ₹10L | Global: $45K - $80K",
        educationPath: "B.A. Social Work / Political Science / Sociology",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Political Advocacy Groups", "Environmental NGOs", "Labor Unions", "Civil Rights Organizations"],
        futureScope: "Highly variable. Often passion-driven rather than financially driven, but successful organizers can transition into politics.",
        jobDemandTrend: "Stable (Niche)",
        governmentJobs: "Low. Typically working *against* or pushing the government to change.",
        freelanceOpportunities: "Moderate. Independent political or union consultants.",
        fieldWork: "Maximum. Constantly on the streets, at rallies, and holding town halls.",
        riskLevel: "Moderate (Potential for arrest during protests or intense public backlash)",
        certifications: ["None specific."],
        internshipRequirements: "Volunteering heavily with established advocacy groups.",
        roadmap: ["Volunteer/Canvasser", "Field Organizer", "Lead Community Organizer", "Director of Advocacy / Politician"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "International Social Worker",
        description: "Work with international NGOs or the UN to provide humanitarian aid, refugee support, and social development in developing nations or disaster zones.",
        summary: "Global humanitarian workers providing aid and social support in international crisis zones.",
        skills: ["Cross-Cultural Competency", "Foreign Languages", "Crisis Logistics", "International Law Basics", "Adaptability"],
        salaryRange: "India: ₹6L - ₹20L | Global: $60K - $120K (Often tax-free depending on organization)",
        educationPath: "BSW/International Relations → MSW / Master's in Global Development",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["United Nations (UNICEF, UNHCR)", "International Red Cross", "Doctors Without Borders (MSF) - Social support wings", "Global NGOs"],
        futureScope: "Highly competitive but crucial. Driven by global events such as wars, famines, and refugee crises.",
        jobDemandTrend: "Competitive, Specialized",
        governmentJobs: "Foreign aid departments (e.g., USAID).",
        freelanceOpportunities: "Low. Requires institutional logistical support.",
        fieldWork: "Maximum. Requires relocating to foreign, often developing or unstable countries.",
        riskLevel: "Very High (Operating in war zones, refugee camps, or politically unstable regions)",
        certifications: ["International Social Work Certifications / Security Training"],
        internshipRequirements: "Overseas volunteer programs, Peace Corps, or UN internships.",
        roadmap: ["Peace Corps / Overseas Volunteer", "NGO Field Officer", "International Program Manager", "Country Director (NGO)"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Housing / Homelessness Social Worker",
        description: "Assist individuals experiencing homelessness to secure emergency shelter, permanent housing, job training, and mental health services.",
        summary: "Advocates dedicated to moving individuals from the streets into stable housing and employment.",
        skills: ["Street Outreach", "Housing Law Knowledge", "Empathy", "Resource Coordination", "Patience"],
        salaryRange: "India: ₹3L - ₹8L | Global: $45K - $75K",
        educationPath: "Bachelor of Social Work (BSW)",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["City Homeless Departments", "Shelters", "Housing Non-profits", "Urban Development Agencies"],
        futureScope: "High demand in urban centers where housing crises and homelessness are escalating.",
        jobDemandTrend: "High Need (Urban areas)",
        governmentJobs: "High. Municipal housing authorities.",
        freelanceOpportunities: "Low.",
        fieldWork: "High. Street outreach and visiting shelters/encampments.",
        riskLevel: "Moderate (Street outreach can sometimes involve unpredictable encounters)",
        certifications: ["None specific."],
        internshipRequirements: "Volunteering at homeless shelters or food banks.",
        roadmap: ["Outreach Specialist", "Housing Case Manager", "Shelter Director", "City Director of Homeless Services"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Disability Caseworker",
        description: "Advocate for the rights, accessibility, and care of individuals with physical or developmental disabilities, ensuring they receive government benefits and proper education.",
        summary: "Specialists ensuring a high quality of life and equal access for individuals with disabilities.",
        skills: ["Disability Law (e.g., ADA)", "Individualized Education Program (IEP) navigation", "Empathy", "Advocacy", "Patience"],
        salaryRange: "India: ₹3L - ₹10L | Global: $45K - $80K",
        educationPath: "BSW or B.A. Special Education",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["State Disability Departments", "Specialized NGOs", "Rehabilitation Centers", "Special Education Schools"],
        futureScope: "Stable and rewarding. Society is increasingly focused on providing robust infrastructural support for disabled individuals.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. State and federal social security or disability departments.",
        freelanceOpportunities: "Moderate. Private disability consultants for families.",
        fieldWork: "Moderate. Home visits to assess accessibility and living conditions.",
        riskLevel: "Low",
        certifications: ["Special Needs Advocacy Certificates"],
        internshipRequirements: "Working with specialized care facilities or special education classes.",
        roadmap: ["Caseworker", "Senior Disability Advocate", "Regional Director of Disability Services"]
    },
    {
        domain: "Arts",
        branch: "Social Work",
        title: "Social Policy Researcher / Academic",
        description: "Conduct high-level academic or institutional research to identify the root causes of societal issues and publish papers to influence broad social legislation.",
        summary: "The academics of social work, researching systemic inequalities to drive macro-level change.",
        skills: ["Advanced Quantitative/Qualitative Research", "Statistical Analysis (SPSS)", "Academic Writing", "Grant Writing", "Sociology Masters"],
        salaryRange: "India: ₹5L - ₹18L | Global: $65K - $110K",
        educationPath: "MSW → Ph.D. in Social Work or Social Policy",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Universities", "Major Think Tanks", "Federal Government (Data Departments)"],
        futureScope: "Prestigious and influential. Their published data directly shapes how billions of dollars in government welfare are spent.",
        jobDemandTrend: "Stable, Highly Competitive",
        governmentJobs: "High. Researching for government planning commissions.",
        freelanceOpportunities: "Moderate. Contracted research or publishing.",
        fieldWork: "Low. Primarily academic/desk-based data analysis.",
        riskLevel: "Low",
        certifications: ["Ph.D. required for top tiers"],
        internshipRequirements: "Academic research assistantships.",
        roadmap: ["Ph.D. Candidate", "Postdoctoral Researcher", "Assistant Professor / Think Tank Fellow", "Tenured Professor of Social Work"]
    }
];

const seedSocialWork = async () => {
    try {
        await Career.deleteMany({ branch: "Social Work" });
        await Career.insertMany(socialWorkProfessions);
        console.log('Social Work Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedSocialWork();
