const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();
mongoose.connect(process.env.MONGO_URI);

const corporateLawProfessions = [
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Mergers & Acquisitions (M&A) Law",
        description: "Focuses on the legalities of combining companies through various financial transactions. M&A lawyers draft, negotiate, and advise on deals to ensure antitrust compliance, proper valuation, and smooth corporate integration.",
        keyLegalFunctions: ["Due Diligence", "Drafting Purchase Agreements", "Antitrust Filings", "Shareholder Negotiations"],
        industriesHiring: ["Investment Banks", "Big Law Firms", "Tech Giants", "Private Equity"],
        educationPath: "LL.B. / J.D. -> LL.M. in Corporate Law",
        yearsOfStudy: "5 to 7 Years",
        certifications: ["CS (Company Secretary)", "CFA (Optional)"],
        skills: ["Contract Drafting", "Financial Literacy", "Negotiation", "Corporate Strategy"],
        typicalProfessionals: ["M&A Lawyer", "Corporate Legal Advisor", "In-house Deal Counsel"],
        salaryRange: "Entry: $80k-$120k | Mid: $150k-$250k | Senior: $300k-$1M+ (Global Avg)",
        roadmap: ["Associate M&A Lawyer", "Senior Associate", "Of Counsel", "M&A Partner"],
        internationalJobOpportunities: "Extremely high in global financial hubs (NY, London, Singapore, Hong Kong).",
        futureScope: "Continuous demand driven by endless corporate consolidations, tech acquisitions, and cross-border expansions.",
        relatedSubSpecializations: ["Antitrust Law", "Private Equity Law", "Tax Structuring"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Corporate Governance Law",
        description: "Deals with the rules, practices, and processes by which a company is directed and controlled. Ensures that the board of directors acts in the best interest of shareholders and complies with strict ethical laws.",
        keyLegalFunctions: ["Board Advising", "Drafting Corporate Bylaws", "Fiduciary Duty Compliance", "Proxy Management"],
        industriesHiring: ["Publicly Traded Companies", "Consulting Firms (Big 4)", "Financial Institutions"],
        educationPath: "LL.B. / J.D. -> CS (Company Secretary) / LL.M.",
        yearsOfStudy: "5 to 6 Years",
        certifications: ["CS (Company Secretary)", "Corporate Governance Certifications"],
        skills: ["Ethics Compliance", "Board Communication", "Regulatory Knowledge", "Risk Mitigation"],
        typicalProfessionals: ["Corporate Governance Consultant", "Company Secretary", "General Counsel"],
        salaryRange: "Entry: $70k-$100k | Mid: $120k-$180k | Senior: $200k-$400k+ (Global Avg)",
        roadmap: ["Compliance Associate", "Corporate Secretary", "Director of Governance", "Chief Legal Officer (CLO)"],
        internationalJobOpportunities: "High demand across the US, UK, and EU due to stringent corporate disclosure laws.",
        futureScope: "Exploding requirement as investors increasingly demand absolute transparency and accountability from corporate boards.",
        relatedSubSpecializations: ["ESG Law", "Shareholder Rights", "Executive Compensation Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Securities & Capital Markets Law",
        description: "Governs the issuance and trading of financial instruments like stocks and bonds. Lawyers ensure that public offerings (IPOs) and debt issuances strictly comply with national financial regulators (like the SEC or SEBI).",
        keyLegalFunctions: ["IPO Structuring", "Drafting Prospectuses", "Insider Trading Compliance", "Debt Issuance"],
        industriesHiring: ["Investment Banks", "Stock Exchanges", "Regulators (SEC/SEBI)", "Corporate Treasuries"],
        educationPath: "LL.B. / J.D. -> LL.M. in Financial/Securities Law",
        yearsOfStudy: "5 to 7 Years",
        certifications: ["Securities Regulation Diplomas", "Financial Modeling Certs"],
        skills: ["Capital Markets Knowledge", "Hyper-attention to Detail", "Securities Regulation", "Financial Structuring"],
        typicalProfessionals: ["Securities Lawyer", "Capital Markets Associate", "Regulatory Counsel"],
        salaryRange: "Entry: $90k-$140k | Mid: $160k-$280k | Senior: $350k-$2M+ (Global Avg)",
        roadmap: ["Capital Markets Associate", "Senior Regulatory Counsel", "Partner - Capital Markets", "Head of Global Capital Markets"],
        internationalJobOpportunities: "Maximum demand in Wall Street (US), City of London (UK), and Tokyo.",
        futureScope: "Perpetually necessary as massive corporations and nation-states continuously rely on capital markets for funding.",
        relatedSubSpecializations: ["Derivatives Law", "Corporate Finance Law", "Investment Funds Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Startup & Venture Capital Law",
        description: "Focuses on the rapid, high-stakes lifecycle of startup companies, from initial incorporation and founder agreements to securing venture capital term sheets and eventual exits.",
        keyLegalFunctions: ["Founder Equity Splitting", "Term Sheet Negotiation", "IP Assignment", "Seed/Series A Funding"],
        industriesHiring: ["Silicon Valley Boutiques", "Venture Capital Firms", "Incubators", "Tech Startups"],
        educationPath: "LL.B. / J.D. -> Startup Law/Tech Law specialization",
        yearsOfStudy: "5 Years",
        certifications: ["Venture Capital/Private Equity Diplomas"],
        skills: ["Agile Drafting", "Business Strategy", "Venture Finance", "IP Fundamentals"],
        typicalProfessionals: ["Startup Legal Advisor", "VC Counsel", "Fractional General Counsel"],
        salaryRange: "Entry: $70k-$110k | Mid: $130k-$200k | Senior: $250k-$500k+ (Global Avg)",
        roadmap: ["Junior Startup Counsel", "Senior Tech Lawyer", "General Counsel (Startup)", "Venture Capital Partner"],
        internationalJobOpportunities: "Immense demand in global tech hubs: San Francisco, Tel Aviv, Bengaluru, Berlin.",
        futureScope: "Massive growth trajectory matching the global explosion of tech entrepreneurship and venture funding.",
        relatedSubSpecializations: ["IP Law", "Technology Law", "Corporate Finance Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Corporate Compliance & Regulatory Law",
        description: "Ensures that a company adheres strictly to the complex web of external laws and internal guidelines. They design compliance programs to prevent monstrous government fines or criminal charges.",
        keyLegalFunctions: ["Anti-Money Laundering (AML)", "Data Privacy Audits", "Whistleblower Policies", "Regulatory Investigations"],
        industriesHiring: ["Pharmaceuticals", "Banking & Finance", "Healthcare", "Manufacturing"],
        educationPath: "LL.B. / J.D. -> Compliance/Regulatory Certification",
        yearsOfStudy: "5 Years",
        certifications: ["Certified Compliance & Ethics Professional (CCEP)", "AML Certifications"],
        skills: ["Risk Assessment", "Policy Drafting", "Auditing", "Regulatory Law"],
        typicalProfessionals: ["Compliance Officer", "Regulatory Affairs Counsel", "Risk Manager"],
        salaryRange: "Entry: $60k-$90k | Mid: $100k-$160k | Senior: $180k-$300k+ (Global Avg)",
        roadmap: ["Compliance Analyst", "Compliance Manager", "Director of Regulatory Affairs", "Chief Compliance Officer (CCO)"],
        internationalJobOpportunities: "Consistently high globally, heavily concentrated in Europe (GDPR) and the US.",
        futureScope: "One of the safest, most stable legal sub-categories as global data, health, and financial regulations tighten aggressively.",
        relatedSubSpecializations: ["Data Privacy & Cyber Law", "Environmental Compliance", "Anti-trust Compliance"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Private Equity Law",
        description: "Caters exclusively to massive Private Equity (PE) firms. PE lawyers structure the aggressive buyouts of private companies, manage the debt utilized for acquisitions, and organize the eventual lucrative exit strategies.",
        keyLegalFunctions: ["Leveraged Buyouts (LBOs)", "Fund Formation", "Management Buyouts", "Portfolio Company Advisory"],
        industriesHiring: ["Private Equity Firms", "Elite Global Law Firms (Magic Circle/White Shoe)"],
        educationPath: "LL.B. / J.D. -> LL.M. / Elite University Background",
        yearsOfStudy: "5 to 6 Years",
        certifications: ["CAIA (Alternative Investments)", "Financial Law Diplomas"],
        skills: ["Complex Financial Structuring", "High-Stakes Negotiation", "Tax Efficiency", "M&A Mechanics"],
        typicalProfessionals: ["PE Lawyer", "Fund Counsel", "Investment Structuring Advisor"],
        salaryRange: "Entry: $100k-$160k | Mid: $200k-$400k | Senior: $500k-$3M+ (Global Avg)",
        roadmap: ["PE Associate", "Senior PE Counsel", "Partner - Private Equity", "Managing Partner"],
        internationalJobOpportunities: "Extremely lucrative roles centered in New York, London, and offshore tax havens (Cayman Islands).",
        futureScope: "Highly elite and exceedingly well-compensated, tracking the massive influx of capital into alternative private investments.",
        relatedSubSpecializations: ["Fund Formation Law", "Corporate Tax Structuring", "M&A Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Bankruptcy & Insolvency Law",
        description: "Steers corporations through crippling financial distress. They manage legal debt restructuring, defend companies from aggressive creditors, and oversee the orderly liquidation of assets if recovery is impossible.",
        keyLegalFunctions: ["Chapter 11 Defaults (US)/IBC (India)", "Creditor Negotiations", "Asset Liquidation", "Debt Restructuring"],
        industriesHiring: ["Banks (NPA Divisions)", "Asset Reconstruction Companies", "Restructuring Consulting Firms"],
        educationPath: "LL.B. / J.D. -> Specialization in Insolvency Code",
        yearsOfStudy: "5 Years",
        certifications: ["Insolvency Professional (IP) Certification"],
        skills: ["Financial Analysis", "Litigation", "Crisis Management", "Debt Structuring"],
        typicalProfessionals: ["Insolvency Lawyer", "Restructuring Counsel", "Insolvency Professional"],
        salaryRange: "Entry: $70k-$100k | Mid: $130k-$220k | Senior: $250k-$600k+ (Global Avg)",
        roadmap: ["Bankruptcy Associate", "Restructuring Manager", "Insolvency Partner", "Lead Liquidator/Resolution Professional"],
        internationalJobOpportunities: "Counter-cyclical demand; peaks heavily during global economic recessions across all nations.",
        futureScope: "A highly resilient career ('recession-proof') as economic downturns and corporate failures are inevitable global cycles.",
        relatedSubSpecializations: ["Corporate Litigation", "Banking & Finance Law", "Distressed M&A"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Corporate Finance Law",
        description: "Dictates how corporations legally raise the massive capital needed for operations. This includes orchestrating syndicated loans, drafting commercial lending agreements, and structuring complex financial instruments.",
        keyLegalFunctions: ["Syndicated Lending", "Asset Finance", "Project Finance", "Drafting Credit Agreements"],
        industriesHiring: ["Commercial Banks", "Corporate Treasuries", "Infrastructure Developers"],
        educationPath: "LL.B. / J.D. -> Background in Commerce/Finance",
        yearsOfStudy: "5 to 6 Years",
        certifications: ["CFA (Optional)"],
        skills: ["Banking Regulations", "Commercial Awareness", "Contract Drafting", "Risk Assessment"],
        typicalProfessionals: ["Corporate Finance Lawyer", "Banking Counsel", "Project Finance Advisor"],
        salaryRange: "Entry: $80k-$120k | Mid: $140k-$240k | Senior: $250k-$800k+ (Global Avg)",
        roadmap: ["Finance Law Associate", "Senior Finance Counsel", "Partner - Banking & Finance", "General Counsel (Bank)"],
        internationalJobOpportunities: "High in financial centers actively funding massive infrastructure and corporate operations globally.",
        futureScope: "Enduring stability, forming the bedrock of corporate expansion and massive multinational infrastructure projects.",
        relatedSubSpecializations: ["Banking Law", "Securities Law", "Private Equity Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Joint Ventures & Strategic Alliances Law",
        description: "Manages the legal complexities when two independent companies collaborate on a massive project. Lawyers protect intellectual property, outline profit-sharing, and plan legal exit strategies if the alliance fails.",
        keyLegalFunctions: ["Drafting JV Agreements", "IP Licensing", "Technology Transfer", "Dispute Resolution Planning"],
        industriesHiring: ["Energy Sector", "Automotive", "Tech & Pharma", "Defense"],
        educationPath: "LL.B. / J.D.",
        yearsOfStudy: "5 Years",
        certifications: ["International Trade Diplomas"],
        skills: ["Commercial Negotiation", "International Law Formulation", "IP Protection", "Corporate Strategy"],
        typicalProfessionals: ["JV Legal Advisor", "Corporate Contracts Lawyer", "Commercial Attorney"],
        salaryRange: "Entry: $70k-$100k | Mid: $120k-$190k | Senior: $220k-$500k+ (Global Avg)",
        roadmap: ["Commercial Associate", "Senior Commercial Counsel", "JV Structuring Lead", "Partner - Commercial Law"],
        internationalJobOpportunities: "High across the Middle East, Asia, and Europe for massive cross-border tech and energy alliances.",
        futureScope: "Increasing demand as companies look to merge capabilities (like legacy auto forming JVs with AI tech startups).",
        relatedSubSpecializations: ["M&A Law", "Intellectual Property Law", "International Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Cross-Border Corporate Transactions",
        description: "Specialized in navigating the extreme complexities of executing corporate deals between companies situated in entirely different sovereign states, facing deeply conflicting tax laws, labor codes, and geopolitical regulations.",
        keyLegalFunctions: ["FDI Compliance", "Multi-Jurisdictional Tax Structuring", "International Trade Compliance", "Sanctions Advisory"],
        industriesHiring: ["Multinational Corporations (MNCs)", "Global Supply Chain Firms", "Big Law Firms"],
        educationPath: "LL.B. / J.D. -> LL.M. in International Business Law",
        yearsOfStudy: "6 Years",
        certifications: ["International Law & Tax Diplomas"],
        skills: ["Cultural Negotiation", "Foreign Corrupt Practices Act (FCPA)", "International Tax", "Geopolitics"],
        typicalProfessionals: ["Cross-Border Lawyer", "International Corporate Advisor", "Foreign Direct Investment Counsel"],
        salaryRange: "Entry: $90k-$130k | Mid: $150k-$260k | Senior: $300k-$1M+ (Global Avg)",
        roadmap: ["International Associate", "Regional Counsel (APAC/EMEA)", "Partner - Cross-Border", "Global General Counsel"],
        internationalJobOpportunities: "The definition of international demand; essentially requires constant travel between global corporate hubs.",
        futureScope: "Critically important as major corporations establish global footprints and shift supply chains continuously.",
        relatedSubSpecializations: ["International Trade Law", "Corporate Tax Structuring", "Customs Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Corporate Litigation",
        description: "The aggressively confrontational branch of corporate law. These lawyers represent corporations in high-stakes courtroom battles regarding massive antitrust breaches, class-action lawsuits, or billion-dollar contract disputes.",
        keyLegalFunctions: ["Courtroom Argument", "Discovery Management", "Class-Action Defense", "Witness Cross-Examination"],
        industriesHiring: ["Litigation Boutiques", "Mega Law Firms", "Independent Practice"],
        educationPath: "LL.B. / J.D. -> Bar Passage",
        yearsOfStudy: "5 Years",
        certifications: ["Trial Advocacy Certifications"],
        skills: ["Persuasive Oral Argument", "Aggressive Litigation Strategy", "Case Law Research", "High-Stress Endurance"],
        typicalProfessionals: ["Corporate Litigator", "Trial Lawyer", "Dispute Resolution Partner"],
        salaryRange: "Entry: $80k-$130k | Mid: $150k-$300k | Senior: $400k-$2M+ (Global Avg)",
        roadmap: ["Litigation Associate", "Senior Litigator", "Partner - Dispute Resolution", "Senior Trial Advocate"],
        internationalJobOpportunities: "Highly domestic, as litigation requires deep expertise in a specific nation's procedural court system.",
        futureScope: "Extremely secure; as long as massive corporations interact, massive disputes and fierce litigation are guaranteed.",
        relatedSubSpecializations: ["Arbitration & Dispute Resolution", "White-Collar Criminal Defense"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Corporate Tax Structuring",
        description: "The most vital component of corporate strategy. These lawyers design intricate international corporate webs to legally minimize tax liabilities across jurisdictions, utilizing tax havens and precise treaties.",
        keyLegalFunctions: ["Double Taxation Avoidance", "Offshore Structuring", "Transfer Pricing", "M&A Tax Optimization"],
        industriesHiring: ["Big 4 Consultancies", "Tax Boutiques", "MNC Tax Divisions"],
        educationPath: "LL.B. / J.D. -> CA / CPA / LL.M. in Taxation",
        yearsOfStudy: "5 to 7 Years",
        certifications: ["Chartered Accountant (CA)", "Certified Public Accountant (CPA)"],
        skills: ["Elite Financial Calculus", "Tax Law Exploitation", "Global Treaties", "Forensic Accounting"],
        typicalProfessionals: ["Tax Structuring Lawyer", "Corporate Tax Advisor", "Transfer Pricing Specialist"],
        salaryRange: "Entry: $80k-$140k | Mid: $160k-$280k | Senior: $350k-$1.5M+ (Global Avg)",
        roadmap: ["Tax Associate", "Tax Manager", "Partner - Corporate Tax", "Global Tax Director"],
        internationalJobOpportunities: "Highest demand in massive global financial hubs and offshore tax epicenters.",
        futureScope: "With global governments constantly changing tax codes to capture corporate wealth, tax structuring is perhaps the most lucrative niche in corporate law.",
        relatedSubSpecializations: ["M&A Law", "Cross-Border Corporate Transactions", "Wealth Management Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Shareholder Rights & Activism Law",
        description: "A combative area where lawyers either help massive activist investors forcefully change a company’s leadership and strategy, or defend corporate boards from these hostile activist takeovers.",
        keyLegalFunctions: ["Proxy Fights", "Hostile Takeovers", "Fiduciary Duty Audits", "Poison Pill Defenses"],
        industriesHiring: ["Activist Hedge Funds", "Corporate Defense Firms", "Private Equity"],
        educationPath: "LL.B. / J.D. -> Finance Background",
        yearsOfStudy: "5 Years",
        certifications: ["Securities Regulation Certifications"],
        skills: ["Hostile Strategy", "Corporate Governance", "Voting Mechanics", "PR Management"],
        typicalProfessionals: ["Activist Counsel", "Corporate Defense Lawyer", "Shareholder Litigator"],
        salaryRange: "Entry: $90k-$130k | Mid: $160k-$250k | Senior: $300k-$1M+ (Global Avg)",
        roadmap: ["Corporate Associate", "Defense Counsel", "Partner - Activism Defense", "Head of Corporate Strategy"],
        internationalJobOpportunities: "Most prominent in the US (Wall Street) and the UK where shareholder activism is a deeply entrenched financial strategy.",
        futureScope: "Growing rapidly as activist hedge funds amass unprecedented capital to forcefully target underperforming global boards.",
        relatedSubSpecializations: ["Corporate Governance Law", "M&A Law", "Securities Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "Corporate Risk & Crisis Management Law",
        description: "The 'fixers' of the corporate world. They are mobilized during catastrophic corporate events—massive data breaches, global PR scandals, or sudden CEO arrests—to legally shield the corporation from destruction.",
        keyLegalFunctions: ["Emergency Litigation Defense", "Regulatory Shielding", "Internal Investigations", "PR Restructuring"],
        industriesHiring: ["Crisis Management Boutiques", "Elite Law Firms", "Massive Fortune 500s"],
        educationPath: "LL.B. / J.D. -> Experience in Litigation/White-Collar Crime",
        yearsOfStudy: "5 to 8 Years",
        certifications: ["Media & Law Certifications"],
        skills: ["Extreme Crisis Mitigation", "Media/PR Savvy", "Internal Investigations", "Calm Under Fire"],
        typicalProfessionals: ["Crisis Management Counsel", "Corporate Defense Lawyer", "Chief Legal Officer"],
        salaryRange: "Entry: $80k-$120k | Mid: $150k-$280k | Senior: $400k-$1.5M+ (Global Avg)",
        roadmap: ["White-Collar Associate", "Internal Investigator", "Partner - Crisis Management", "Global Head of Risk"],
        internationalJobOpportunities: "Commanded globally by massive corporations that frequently face existential geopolitical or digital crises.",
        futureScope: "Extremely vital. As digital data breaches and corporate scandals happen instantly online, expert crisis lawyers are infinitely valuable.",
        relatedSubSpecializations: ["White-Collar Criminal Law", "Cyber Law", "Corporate Governance Law"]
    },
    {
        domain: "Law",
        branch: "Corporate Law",
        title: "ESG & Sustainability Corporate Law",
        description: "The newest frontier of corporate law. Forces companies to legally integrate massive Environmental, Social, and Governance (ESG) guidelines into their operations to satisfy global climate goals and prevent 'greenwashing'.",
        keyLegalFunctions: ["Carbon Disclosure Compliance", "Supply Chain Auditing", "Greenwashing Defense", "Sustainability Reporting"],
        industriesHiring: ["Energy Utilities", "FMCG Giants", "Consulting Firms", "Manufacturing"],
        educationPath: "LL.B. / J.D. -> Diploma in Environmental Law / ESG",
        yearsOfStudy: "5 Years",
        certifications: ["ESG Certificates (CFA ESG, SASB)"],
        skills: ["Environmental Regulation", "Corporate Disclosure", "Supply Chain Analysis", "Future-casting"],
        typicalProfessionals: ["ESG Counsel", "Chief Sustainability Officer", "Green Compliance Advisor"],
        salaryRange: "Entry: $70k-$110k | Mid: $130k-$200k | Senior: $250k-$500k+ (Global Avg)",
        roadmap: ["ESG Associate", "Sustainability Counsel", "Partner - ESG Law", "Chief Sustainability Officer (CSO)"],
        internationalJobOpportunities: "Massive demand across Europe (due to strict EU ESG mandates) and rapidly expanding in the US and APAC.",
        futureScope: "The absolute highest growth area in modern law, driven entirely by unstoppable global shifts toward climate legislation and ethical supply chains.",
        relatedSubSpecializations: ["Environmental Law", "Corporate Governance Law", "Corporate Compliance Law"]
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Corporate Law" });
        await Career.insertMany(corporateLawProfessions);
        console.log('Corporate Law Sub-categories Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedData();
