const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const philosophyProfessions = [
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Philosopher",
        description: "Engage in rigorous intellectual inquiry regarding fundamental questions about existence, knowledge, values, reason, mind, and language.",
        summary: "Thinkers who dedicate their lives to analyzing the fundamental nature of knowledge, reality, and existence.",
        skills: ["Critical Thinking", "Logical Analysis", "Argument Construction", "Deep Reading", "Abstract Reasoning"],
        salaryRange: "India: ₹4L - ₹15L | Global: $45K - $100K",
        educationPath: "B.A. Philosophy → M.A. Philosophy → Ph.D.",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Academia", "Publishing", "Think Tanks", "Independent Authorship"],
        futureScope: "A stable, niche intellectual field. Growing relevance in AI ethics and bioethics.",
        jobDemandTrend: "Stable, Highly Competitive",
        academicOpportunities: "High. Most professional philosophers are tenured professors or researchers at universities.",
        researchOpportunities: "Extensive. Primarily textual analysis, publishing books, and contributing to peer-reviewed philosophy journals.",
        certifications: ["None specific."],
        roadmap: ["B.A. Philosophy", "M.A. & Ph.D. specialisation", "Postdoc fellowships", "Published Author / Tenured Professor"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Ethics Consultant",
        description: "Advise corporations, hospitals, and tech companies on complex moral dilemmas, ensuring corporate policies and new technologies align with ethical standards.",
        summary: "Professional moral advisors helping organizations navigate complex ethical decisions in business and healthcare.",
        skills: ["Applied Ethics", "Regulatory Knowledge", "Conflict Resolution", "Stakeholder Communication", "Risk Assessment"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $130K",
        educationPath: "B.A. Philosophy/Pre-Med/Law → M.A. Bioethics/Applied Ethics",
        yearsOfStudy: "5 to 7 Years",
        industriesHiring: ["Hospitals (Bioethics)", "Tech Companies (AI Ethics)", "Corporate Compliance Departments", "Government Panels"],
        futureScope: "Explosive growth. The rise of Artificial Intelligence and complex medical technologies has created a massive demand for professional ethicists.",
        jobDemandTrend: "High Growth",
        academicOpportunities: "Moderate. Often serve as adjunct faculty while maintaining a private consultancy.",
        researchOpportunities: "Moderate. Researching the ethical implications of emerging technologies (like CRISPR or AI).",
        certifications: ["Healthcare Ethics Consultant-Certified (HEC-C)"],
        roadmap: ["Degree in Philosophy/Ethics", "Specialization (Medical or Tech ethics)", "Consulting for small firms/hospitals", "Lead Ethics Officer for major corporation"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Political Philosopher",
        description: "Analyze the fundamental principles of government, liberty, justice, property, and the enforcement of the legal code by authority.",
        summary: "Theorists analyzing the concepts of justice, liberty, and how societies should be governed.",
        skills: ["Political Theory", "Historical Contextualization", "Macro-level Societal Analysis", "Debate", "Writing"],
        salaryRange: "India: ₹5L - ₹15L | Global: $55K - $110K",
        educationPath: "B.A. Philosophy/Political Science → M.A. Political Philosophy → Ph.D.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Political Think Tanks", "Policy Institutes", "Advocacy Groups"],
        futureScope: "Highly relevant. Their theories often form the ideological foundations for modern political movements and policy shifts.",
        jobDemandTrend: "Steady",
        academicOpportunities: "Very High. Core faculty positions in political science and philosophy departments.",
        researchOpportunities: "High. Publishing theories on democratic theory, human rights, and global justice systems.",
        certifications: ["None specific."],
        roadmap: ["Undergraduate studies", "Ph.D. researching specific political systems", "Publishing influential articles", "Senior Fellow at a Think Tank / Professor"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Moral Philosopher",
        description: "Study what constitutes right and wrong behavior, the nature of moral judgments, and how individuals ought to live their lives.",
        summary: "Experts investigating the absolute nature of good and evil and human moral responsibility.",
        skills: ["Normative Ethics", "Meta-ethics", "Logical Deduction", "Persuasive Writing", "Empathy"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $95K",
        educationPath: "B.A. Philosophy → M.A. Philosophy → Ph.D.",
        yearsOfStudy: "8 Years",
        industriesHiring: ["Academia", "Theological Seminaries", "Publishing", "Non-Profit Strategy"],
        futureScope: "Stable academic demand. Increasingly collaborating with neurologists and psychologists to understand the biological basis of morality.",
        jobDemandTrend: "Stable",
        academicOpportunities: "High. Universities require moral philosophers for core humanities curriculums.",
        researchOpportunities: "High. Investigating everything from animal rights theories to the morality of war.",
        certifications: ["None specific."],
        roadmap: ["Philosophy degrees", "Specialize in a moral framework (e.g., Utilitarianism)", "Publishing books", "Recognized Authority on Moral Theory"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Philosophy Professor / Lecturer",
        description: "Teach philosophical texts and logic to university students while conducting independent research to advance the academic field.",
        summary: "Academic educators shaping the critical thinking skills of the next generation.",
        skills: ["Pedagogy", "Public Speaking", "Curriculum Development", "Academic Mentorship", "Socratic Questioning"],
        salaryRange: "India: ₹6L - ₹20L | Global: $60K - $120K",
        educationPath: "B.A. → M.A. → Ph.D. in Philosophy",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Universities", "Liberal Arts Colleges", "Community Colleges"],
        futureScope: "Highly prestigious. Allows complete intellectual freedom but faces intense competition for tenured positions.",
        jobDemandTrend: "Highly Competitive",
        academicOpportunities: "Maximum. This is the ultimate academic role within the field.",
        researchOpportunities: "Extensive. Professors are required to 'publish or perish', constantly releasing new research.",
        certifications: ["National Eligibility Test (NET) for lectureship (India)"],
        roadmap: ["Complete Ph.D.", "Postdoctoral fellowship", "Assistant Professor", "Tenured Professor of Philosophy"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Research Scholar in Philosophy",
        description: "Focus entirely on investigating obscure or emerging philosophical texts, often supported by university grants or private endowments.",
        summary: "Dedicated academics funded entirely to produce groundbreaking philosophical research and translations.",
        skills: ["Archival Research", "Ancient Languages (Greek, Latin, German, etc.)", "Grant Writing", "Textual Exegesis", "Patience"],
        salaryRange: "India: ₹3L - ₹8L (Stipend/Grant based) | Global: $40K - $80K",
        educationPath: "M.A. Philosophy → Ph.D. / Postdoc",
        yearsOfStudy: "5 to 8+ Years",
        industriesHiring: ["Research Institutes", "University Fellowships", "Private Foundations"],
        futureScope: "Niche but essential for translating undiscovered ancient texts or developing entirely new schools of thought.",
        jobDemandTrend: "Niche, Grant-dependent",
        academicOpportunities: "High. Often a stepping stone to a full professorship.",
        researchOpportunities: "Maximum. The entire career is dedicated to reading, translating, and writing.",
        certifications: ["Specialised Language Certifications"],
        roadmap: ["Master's Degree", "Secure Ph.D. funding", "Win a Postdoc fellowship", "Senior Research Fellow"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Public Policy Advisor (Philosophy background)",
        description: "Use philosophical training in logic and ethics to help draft, analyze, and justify government legislation and social policies.",
        summary: "Strategists applying ethical frameworks and intense logic to create fairer government laws.",
        skills: ["Policy Analysis", "Utilitarian/Deontological Ethics", "Legal Writing", "Stakeholder Negotiation", "Data Interpretation"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $120K",
        educationPath: "B.A. Philosophy/Economics → M.A. Public Policy (MPP)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Government Ministries", "Legislative Offices", "NGOs", "International Bodies (UN, WHO)"],
        futureScope: "Strong demand. Governments increasingly need advisors who can foresee the ethical implications of complex new laws.",
        jobDemandTrend: "Growing",
        academicOpportunities: "Moderate. Can transition into teaching public policy.",
        researchOpportunities: "High. Researching the socio-economic impacts of proposed legislation.",
        certifications: ["Public Policy Certificates"],
        roadmap: ["Philosophy/Policy degree", "Legislative Assistant", "Policy Analyst", "Senior Public Policy Advisor"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Legal Theory Analyst",
        description: "Study the philosophy of law (Jurisprudence), analyzing the deeper moral and logical justifications behind why specific laws exist and how they should be interpreted.",
        summary: "The philosophers of law, determining the moral justification for the legal system itself.",
        skills: ["Jurisprudence", "Constitutional Analysis", "Formal Logic", "Advanced Rhetoric", "Case Law Knowledge"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $115K",
        educationPath: "B.A. Philosophy → J.D. (Law Degree) or Ph.D. in Legal Philosophy",
        yearsOfStudy: "7 to 8 Years",
        industriesHiring: ["Law Schools", "Supreme Court Think Tanks", "Constitutional Advocacy Groups"],
        futureScope: "Critical for shaping constitutional interpretations and arguing groundbreaking civil rights cases.",
        jobDemandTrend: "Stable, Highly Specialized",
        academicOpportunities: "High. Often teach in law schools rather than philosophy departments.",
        researchOpportunities: "Extensive. Publishing papers that influence supreme court decisions and legal precedents.",
        certifications: ["Bar Association Membership (if practicing law)"],
        roadmap: ["Philosophy degree", "Law School / Ph.D.", "Clerkship or Research role", "Professor of Jurisprudence / Legal Scholar"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Religious Studies Scholar",
        description: "Analyze the philosophy of religion, examining the nature of faith, the arguments for/against the existence of God, and the philosophical underpinnings of world religions.",
        summary: "Academics examining the profound philosophical concepts underlying global religious traditions.",
        skills: ["Theology", "Comparative Religion", "Phenomenology", "Ancient Texts Analysis", "Cultural Sensitivity"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $90K",
        educationPath: "B.A. Philosophy/Theology → M.A. Religious Studies → Ph.D.",
        yearsOfStudy: "8 Years",
        industriesHiring: ["Universities", "Theological Colleges", "Publishing", "Interfaith NGOs"],
        futureScope: "Stable academic niche. Highly relevant in global diplomacy for understanding the philosophical motivations of different cultures.",
        jobDemandTrend: "Stable",
        academicOpportunities: "High. Faculty positions in Religious Studies or Philosophy departments.",
        researchOpportunities: "Extensive. Translating sacred texts and evaluating theological arguments.",
        certifications: ["None specific."],
        roadmap: ["Religious Studies degrees", "Specialization in a specific tradition or comparative philosophy", "Publishing", "Senior Scholar"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Logic Specialist",
        description: "Focus entirely on formal, mathematical, and symbolic logic. They often bridge the gap between philosophy, advanced mathematics, and theoretical computer science.",
        summary: "The mathematicians of philosophy, dealing with the absolute foundations of reasoning and computation.",
        skills: ["Symbolic Logic", "Set Theory", "Mathematical Proofs", "Analytical Philosophy", "Algorithms Basics"],
        salaryRange: "India: ₹6L - ₹20L | Global: $70K - $130K",
        educationPath: "B.Sc. Math/B.A. Philosophy → M.A./M.Sc. Logic → Ph.D.",
        yearsOfStudy: "8 Years",
        industriesHiring: ["Computer Science Departments", "Philosophy Departments", "AI Research Labs", "Tech Giants"],
        futureScope: "Extremely high impact. Logicians are foundational to the development of Artificial Intelligence and advanced programming languages.",
        jobDemandTrend: "Growing rapidly (intersecting with AI)",
        academicOpportunities: "High. Can work in both Math and Philosophy faculties.",
        researchOpportunities: "Extensive. Researching non-classical logic, paradoxes, and computability theory.",
        certifications: ["None specific."],
        roadmap: ["Math/Philosophy degrees", "Ph.D. in Formal Logic", "Academic research or transition to AI logic design", "Lead Theoretical Logician"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Academic Writer (Philosophy)",
        description: "Translate complex philosophical concepts into accessible books, essays, and articles for the general public or specialized academic journals.",
        summary: "Authors bringing dense philosophical ideas out of the university and into public awareness.",
        skills: ["Simplification of Complex Ideas", "Exceptional Writing", "Subject Matter Breadth", "Editing", "SEO/Digital Publishing basics"],
        salaryRange: "India: ₹3L - ₹10L | Global: $45K - $90K",
        educationPath: "B.A./M.A. Philosophy",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Academic Journals", "Major Magazines (e.g., The Atlantic)", "Publishing Houses", "Freelance"],
        futureScope: "Growing. There is a massive public hunger for \"pop-philosophy\" (like Stoicism) to help people navigate modern anxieties.",
        jobDemandTrend: "Growing (Freelance/Media)",
        academicOpportunities: "Moderate. Often write for university presses.",
        researchOpportunities: "High. Continual research required to write on new, diverse topics.",
        certifications: ["None; portfolio is paramount."],
        roadmap: ["Philosophy degree", "Start a blog/freelance writing", "Get published in major outlets", "Bestselling Non-Fiction Author"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Think Tank Researcher",
        description: "Provide the philosophical and ethical foundations for policy papers, op-eds, and strategic plans produced by private or politically-affiliated research institutes.",
        summary: "Intellectuals hired by institutes to develop the ideological arguments for new public policies.",
        skills: ["Ideological Synthesis", "Rapid Research", "Persuasive Argumentation", "Political Awareness", "Public Speaking"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $110K",
        educationPath: "M.A. or Ph.D. in Philosophy/Political Science",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Political Think Tanks", "Economic Institutes", "Foreign Policy Boards"],
        futureScope: "High influence. Think tanks heavily dictate the future legislation of nations by framing the ethical imperatives.",
        jobDemandTrend: "Competitive, Steady",
        academicOpportunities: "Moderate. Often rotate between academia and think tanks.",
        researchOpportunities: "Maximum. The primary duty is researching and publishing 'white papers'.",
        certifications: ["None specific."],
        roadmap: ["M.A./Ph.D.", "Research Assistant at a Think Tank", "Policy Fellow", "Director of Research or Ideology"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Social Critic",
        description: "Analyze and critique modern societal trends, culture, media, and economy using deep philosophical frameworks, usually through essays, books, and media appearances.",
        summary: "Public intellectuals critiquing the flaws and trends of modern society through a philosophical lens.",
        skills: ["Cultural Analysis", "Media Literacy", "Provocative Writing", "Oratory Skills", "Sociology basics"],
        salaryRange: "India: ₹3L - ₹12L | Global: $40K - $100K+ (Highly variable)",
        educationPath: "B.A./M.A. Philosophy, Sociology, or Literature",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["News Media", "Digital Journalism", "Publishing", "Podcasting/YouTube"],
        futureScope: "Massive potential in the digital age. Independent platforms allow social critics to build direct, lucrative audiences.",
        jobDemandTrend: "High Growth (Independent Creator Economy)",
        academicOpportunities: "Low to Moderate.",
        researchOpportunities: "High. Continuous observation and research on modern cultural phenomena.",
        certifications: ["None."],
        roadmap: ["Philosophy/Humanities degree", "Publish essays online", "Build media presence/podcasts", "Prominent Public Intellectual"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Debate Coach",
        description: "Train students or professionals in formal logic, rhetoric, and argumentation, utilizing philosophical concepts to win argumentative competitions or legal cases.",
        summary: "Experts in logic and rhetoric training others to construct unbreakable arguments.",
        skills: ["Formal Logic", "Rhetoric", "Coaching/Mentorship", "Quick Thinking", "Extensive Knowledge of Ethics/Politics"],
        salaryRange: "India: ₹3L - ₹10L | Global: $45K - $85K",
        educationPath: "B.A. Philosophy/Communications",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["High Schools", "Universities", "Law Firms (Jury Consultants)", "Political Campaigns"],
        futureScope: "Stable demand in education, but highly lucrative when transitioning to political consulting or legal trial preparation.",
        jobDemandTrend: "Steady",
        academicOpportunities: "High. Employed directly by educational institutions.",
        researchOpportunities: "Moderate. Researching specific debate topics annually.",
        certifications: ["National Speech and Debate Association memberships"],
        roadmap: ["Participate heavily in collegiate debate", "Philosophy degree", "Assistant Coach", "Director of Forensics/Debate"]
    },
    {
        domain: "Arts",
        branch: "Philosophy",
        title: "Human Rights Advocate (Philosophy background)",
        description: "Utilize deep understanding of human rights philosophy to champion causes for marginalized groups, working with international law and global NGOs.",
        summary: "Activists using philosophical arguments for universal human rights to drive global humanitarian change.",
        skills: ["Moral Philosophy", "International Law basics", "Advocacy & Campaigning", "Grant Writing", "Public Relations"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $95K",
        educationPath: "B.A. Philosophy → M.A. Human Rights / International Relations",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Amnesty International", "United Nations", "Civil Rights NGOs", "Legal Aid Societies"],
        futureScope: "Crucial. As global conflicts arise, these advocates provide the moral reasoning necessary to demand international intervention and legal protection.",
        jobDemandTrend: "Growing",
        academicOpportunities: "Moderate. Guest lecturing or transitioning to academia later.",
        researchOpportunities: "High. Documenting human rights abuses and drafting philosophical/legal defenses.",
        certifications: ["Human Rights Law Certificates"],
        roadmap: ["Philosophy degree", "Volunteer/Intern at NGOs", "Manage grassroots campaigns", "Director of International Advocacy"]
    }
];

const seedPhilosophy = async () => {
    try {
        await Career.deleteMany({ branch: "Philosophy" });
        await Career.insertMany(philosophyProfessions);
        console.log('Philosophy Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedPhilosophy();
