const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const criminalLawProfessions = [
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Defense Lawyer",
        description: "Represents individuals and organizations charged with criminal offenses. Their primary duty is to advocate for their clients to ensure a fair trial, negotiate plea deals, or secure an acquittal in court.",
        educationPath: "LLB -> LLM in Criminal Law (Optional)",
        competitiveExams: ["CLAT", "AILET", "State Law Entrance Exams (MH CET, DLB)"],
        yearsOfStudy: "5 Years (Integrated) or 3 Years (Post-Graduation)",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Courtroom Argumentation", "Cross-Examination", "Legal Research", "Persuasion"],
        salaryRange: "India: ₹4 LPA - ₹30+ LPA | Global: $60,000 - $180,000+ per year",
        roadmap: ["Junior Associate", "Independent Counsel", "Senior Advocate", "Designated Senior Counsel"],
        courtPracticeOpportunities: "Massive opportunities ranging from local Magistracy to the Supreme Court.",
        governmentJobs: "Eligible for Legal Aid panels and amicus curiae appointments.",
        privateSectorOpportunities: "High demand in top criminal defense chambers and boutique litigation firms.",
        workNature: "Primarily Courtroom Litigation & Client Consultation.",
        riskLevel: "High (Due to proximity with criminal elements & high-stakes outcomes)",
        futureScope: "Will forever remain a cornerstone of the justice system; rising demand for specialized defense in complex white-collar and cybercrimes.",
        jobDemandTrend: "High and Constant",
        summary: "A high-adrenaline, adversarial career focused entirely on defending the accused against state machinery in local and apex courts."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Public Prosecutor",
        description: "An advocate appointed by the state or central government to represent the government in criminal trials. They present the case against the accused on behalf of the public.",
        educationPath: "LLB -> State Public Service Commission Exams",
        competitiveExams: ["APO / APP / Judicial Services (State-specific)"],
        yearsOfStudy: "3 to 5 Years + 7+ Years Practice for Higher Roles",
        certifications: ["Bar Council Enrollment", "Government Appointment"],
        skills: ["Objective Analysis", "Prosecution Strategy", "Witness Management", "Evidence Presentation"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA (Plus Perks) | Global: $70,000 - $140,000 per year",
        roadmap: ["Assistant Public Prosecutor (APP)", "Additional Public Prosecutor", "Public Prosecutor (PP)", "Director of Prosecution"],
        courtPracticeOpportunities: "Exclusive practice in Sessions Courts, High Courts, and Supreme Court representing the state.",
        governmentJobs: "100% Government Role.",
        privateSectorOpportunities: "N/A while in office.",
        workNature: "Heavy Courtroom Litigation.",
        riskLevel: "Moderate to High",
        futureScope: "Extremely stable and prestigious government career, often serving as a direct stepping stone to becoming a High Court Judge.",
        jobDemandTrend: "Stable (State-regulated intake)",
        summary: "A highly respected governmental role focused on proving the guilt of the accused beyond a reasonable doubt to maintain societal order."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Litigation Lawyer",
        description: "Handles the end-to-end procedural filing, petitioning, and daily hearings of criminal cases. They handle bail applications, criminal writ petitions, and the massive paperwork involved in criminal trials.",
        educationPath: "LLB",
        competitiveExams: ["CLAT / AILET"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Drafting Petitions", "Bail Hearings", "Procedural Criminal Law (CrPC)", "Evidence Act"],
        salaryRange: "India: ₹3 LPA - ₹15 LPA | Global: $55,000 - $120,000 per year",
        roadmap: ["Litigation Assistant", "Associate Litigator", "High Court Practitioner", "Senior Partner - Litigation"],
        courtPracticeOpportunities: "Intense daily practice in trial courts and appellate tribunals.",
        governmentJobs: "Contractual empanelment by state agencies.",
        privateSectorOpportunities: "Employed heavily by large litigation firms and senior advocates to handle case volumes.",
        workNature: "Blend of Courtroom Hearings and Intensive Desk Drafting.",
        riskLevel: "Moderate",
        futureScope: "The bedrock of legal practice. Excellent litigators naturally progress to become elite defense or appellate lawyers.",
        jobDemandTrend: "Very High Volume",
        summary: "The backbone of the criminal justice process, managing the immense procedural and filing requirements to keep trials moving."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Legal Advisor",
        description: "Provides out-of-court strategic counsel to individuals, corporations, or media regarding criminal liability, regulatory violations, and risk mitigation to prevent actual prosecution.",
        educationPath: "LLB -> LLM (Optional)",
        competitiveExams: ["CLAT (PG) / AILET (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Risk Assessment", "Statutory Interpretation", "Corporate Defense Strategy", "Negotiation"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $75,000 - $160,000 per year",
        roadmap: ["Legal Consultant", "Senior Legal Advisor", "In-house Counsel", "General Counsel (Risk)"],
        courtPracticeOpportunities: "Low; mostly out-of-court advisory.",
        governmentJobs: "Advisory to Law Commissions and policy-making bodies.",
        privateSectorOpportunities: "High demand in large corporations, tech giants, and elite consulting firms.",
        workNature: "Advisory, Legal Research & Corporate Consultation.",
        riskLevel: "Low",
        futureScope: "Rising significantly as corporations aggressively seek out preventative counsel to avoid multi-million dollar criminal liabilities and PR disasters.",
        jobDemandTrend: "Growing rapidly",
        summary: "A highly strategic advisory role focused on preventive law, shielding clients from criminal charges before they happen."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Forensic Legal Consultant",
        description: "Operates at the intersection of law and science. They assist defense lawyers or prosecutors in interpreting complex forensic evidence (DNA, ballistics, toxicology) to validate or destroy the opposing side's claims in court.",
        educationPath: "B.Sc/M.Sc Forensic Science + LLB",
        competitiveExams: ["AIFSET / CLAT"],
        yearsOfStudy: "6 to 7 Years",
        certifications: ["Forensic Certifications", "Bar Council Enrollment (If litigating)"],
        skills: ["Forensic Pathology", "Evidence Tempering Analysis", "Cross-Examining Experts", "Scientific Reporting"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $65,000 - $130,000 per year",
        roadmap: ["Forensic Legal Analyst", "Expert Witness Coordinator", "Senior Forensic Counsel", "Independent Consultant"],
        courtPracticeOpportunities: "Acts as co-counsel or expert consultant during cross-examinations.",
        governmentJobs: "Consultant roles in State/Central Forensic Science Laboratories (FSL).",
        privateSectorOpportunities: "Boutique criminal defense firms highly value forensic expertise.",
        workNature: "Investigative Analysis & Courtroom Strategy.",
        riskLevel: "Low to Moderate",
        futureScope: "Extremely valuable niche. As modern crimes leave intense digital and biological footprints, forensic capability makes or breaks cases.",
        jobDemandTrend: "Niche but High Value",
        summary: "A unique hybrid role demystifying complex scientific evidence to forge massive breakthroughs in criminal trials."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Cyber Crime Lawyer",
        description: "Specializes in crimes committed via the internet or digital networks. They handle cases involving hacking, dark web syndicates, identity theft, financial fraud, and digital espionage.",
        educationPath: "LLB -> Diploma/LLM in Cyber Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Certified Ethical Hacker (Optional but valuable)", "Data Privacy Certs"],
        skills: ["Digital Forensics", "IT Act knowledge", "Data Privacy", "Tech Literacy"],
        salaryRange: "India: ₹7 LPA - ₹25 LPA | Global: $90,000 - $200,000 per year",
        roadmap: ["Cyber Legal Associate", "Cyber Crime Counsel", "Partner - Tech Litigation", "Global Cyber Authority"],
        courtPracticeOpportunities: "Practice in specialized Cyber Appellate Tribunals and High Courts.",
        governmentJobs: "Advising national cyber-defense agencies (CERT-In).",
        privateSectorOpportunities: "Massive demand in tech companies, banks, and specialized cyber-defense firms.",
        workNature: "Highly analytical, combining intense tech-audits with legal filings.",
        riskLevel: "Low to Moderate",
        futureScope: "Explosive growth trajectory. As warfare and theft move entirely online, cyber crime experts command the absolute highest premiums in criminal law.",
        jobDemandTrend: "Explosively High",
        summary: "The ultimate modern criminal lawyer, defending and prosecuting massive digital heists and complex virtual offenses."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "White Collar Crime Lawyer",
        description: "Defends high-net-worth individuals, politicians, and massive corporations accused of non-violent, financially motivated crimes like embezzlement, insider trading, massive tax evasion, and money laundering.",
        educationPath: "LLB -> LLM / CS / CA Background (Preferred)",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 to 7 Years",
        certifications: ["Anti-Money Laundering (AML) Certifications"],
        skills: ["Forensic Accounting", "Corporate Law", "Financial Argumentation", "Regulatory Defense"],
        salaryRange: "India: ₹10 LPA - ₹50+ LPA | Global: $150,000 - $500,000+ per year",
        roadmap: ["White Collar Associate", "Senior Corporate Defender", "Partner - White-Collar Defense", "Elite Trial Counsel"],
        courtPracticeOpportunities: "Intense practice in specialized financial courts (e.g., PMLA Courts, ED Tribunals).",
        governmentJobs: "Prosecuting on behalf of the Enforcement Directorate (ED), CBI, or SEC.",
        privateSectorOpportunities: "The highest paying sector for criminal lawyers in elite Tier-1 law firms.",
        workNature: "Deep Financial Investigation & High-Stakes Courtroom Defense.",
        riskLevel: "Moderate",
        futureScope: "Incredibly lucrative. Governments are aggressively cracking down on global corporate fraud, guaranteeing massive retainers for elite defenders.",
        jobDemandTrend: "Very High (Elite Tier)",
        summary: "The most financially lucrative branch of criminal law, representing billionaires and executives facing catastrophic financial charges."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Appellate Lawyer",
        description: "Focuses exclusively on appealing criminal convictions to higher courts (High Courts and Supreme Court). They do not recount facts, but strictly argue that constitutional or procedural errors occurred during the initial trial.",
        educationPath: "LLB -> LLM",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years + 10+ Years Litigation Experience",
        certifications: ["Advocate-on-Record (AOR) for Supreme Court"],
        skills: ["Constitutional Law", "Flawless Legal Drafting", "High-Level Persuasion", "Jurisprudence Research"],
        salaryRange: "India: ₹12 LPA - ₹50+ LPA | Global: $120,000 - $300,000+ per year",
        roadmap: ["Appellate Junior", "Independent Appellate Counsel", "Senior Advocate", "Supreme Court Specialist"],
        courtPracticeOpportunities: "Exclusive practice in the High Courts and Supreme Court.",
        governmentJobs: "Appointed as Additional/Solicitor General representing the state in appeals.",
        privateSectorOpportunities: "Operate elite independent appellate chambers.",
        workNature: "Intense Legal Research, Drafting, & Elite Apex Court Arguments.",
        riskLevel: "Low",
        futureScope: "Extremely prestigious. The apex of criminal practice, arguing cases that literally reshape the constitutional laws of the country.",
        jobDemandTrend: "Stable (Elite Niche)",
        summary: "The intellectual titans of the criminal justice system, fighting to overturn convictions at the highest levels of the judiciary."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Legal Investigator",
        description: "Works closely with criminal defense lawyers to physically track down witnesses, unearth hidden documents, surveil locations, and gather evidence that the police either missed or ignored to blow apart the prosecution's case.",
        educationPath: "Any Degree / LLB / Criminology",
        competitiveExams: ["None specifically required"],
        yearsOfStudy: "3 to 4 Years",
        certifications: ["Private Investigator Licenses (Jurisdiction specific)"],
        skills: ["Surveillance", "Interrogation / Interviewing", "Evidence Handling", "Street Smarts"],
        salaryRange: "India: ₹3 LPA - ₹10 LPA | Global: $50,000 - $90,000 per year",
        roadmap: ["Field Investigator", "Lead Legal Investigator", "Private Detective Agency Owner", "Chief Investigative Consultant"],
        courtPracticeOpportunities: "None directly, but extensively called as witnesses to testify.",
        governmentJobs: "Roles in CBI, CID, or anti-corruption bureaus.",
        privateSectorOpportunities: "Employed permanently by massive defense firms or operating private detective agencies.",
        workNature: "Physical Field Work, Intelligence Gathering, & Witness Interviews.",
        riskLevel: "High (Physical risk during field ops)",
        futureScope: "Essential to high-stakes defense. Finding the one piece of evidence the state missed is what wins multi-million dollar cases.",
        jobDemandTrend: "Stable",
        summary: "A thrilling on-the-ground investigative role fueling the arguments that lawyers present in court."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Law Researcher",
        description: "Usually attached to a judge, senior advocate, or legal think tank. They spend their time diving deep into historical case laws, international jurisprudence, and statutes to find the exact precedents needed to win complex arguments.",
        educationPath: "LLB -> LLM",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Advanced Legal Databases (SCC/LexisNexis)", "Speed Reading", "Synthesizing Precedents", "Academic Writing"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $60,000 - $110,000 per year",
        roadmap: ["Judicial Clerk / Researcher", "Senior Research Associate", "Think-Tank Director", "Academic Scholar"],
        courtPracticeOpportunities: "Very low; purely an academic and behind-the-scenes support role.",
        governmentJobs: "Law Clerk cum Research Assistants at the Supreme Court / High Courts.",
        privateSectorOpportunities: "Hired by Tier-1 law firms and massive NGOs for policy research.",
        workNature: "Pure Legal Research & Academic Drafting.",
        riskLevel: "Low",
        futureScope: "A fantastic stepping stone for fresh graduates seeking to build immense knowledge before entering active appellate litigation or the judiciary.",
        jobDemandTrend: "Stable",
        summary: "The intellectual backbone of massive cases, unearthing the forgotten precedents that change the tides of criminal appeals."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Victim Rights Advocate",
        description: "Unlike prosecutors who represent the state, these advocates represent the specific, personal interests of the victims. They ensure the victim is protected, receives restitution, and has a voice during the sentencing of the offender.",
        educationPath: "LLB / Master of Social Work (MSW)",
        competitiveExams: ["State Entrance Exams"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Trauma-Informed Care Certifications"],
        skills: ["Empathy/Trauma Counseling", "Restitution Claims", "Victim Compensation Schemes", "Advocacy"],
        salaryRange: "India: ₹3 LPA - ₹8 LPA | Global: $45,000 - $80,000 per year",
        roadmap: ["Victim Intake Specialist", "Victim Advocate", "Director of Victim Services", "NGO Founder"],
        courtPracticeOpportunities: "Filing private compensation petitions and representing victim interests during bail hearings.",
        governmentJobs: "Employed in state victim assistance programs and women's commissions.",
        privateSectorOpportunities: "Extensively employed by massive domestic violence and human rights NGOs.",
        workNature: "Counseling, Legal Strategy, & Social Advocacy.",
        riskLevel: "Moderate (Emotional burnout is high)",
        futureScope: "Increasing focus globally on restorative justice ensures a growing demand for specialized victim protection lawyers.",
        jobDemandTrend: "Growing slowly",
        summary: "A deeply noble and empathetic legal role focused on restoring dignity, safety, and financial compensation to those shattered by crime."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Justice Consultant",
        description: "Advises governments, police forces, or international organizations on how to fundamentally reform prison systems, policing tactics, and criminal statutes to be more humane, efficient, and technologically advanced.",
        educationPath: "LLB -> Masters in Criminology / Public Policy",
        competitiveExams: ["UPSC (Optional route) / GRE (for abroad)"],
        yearsOfStudy: "6 to 7 Years",
        certifications: ["Public Policy Diplomas"],
        skills: ["Systemic Auditing", "Macro Policy Design", "Data Analytics (Crime Rates)", "International Law"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $80,000 - $150,000 per year",
        roadmap: ["Policy Analyst", "Criminology Consultant", "Senior Reform Advisor", "Director of Criminal Justice Policy"],
        courtPracticeOpportunities: "None. Strictly an advisory macro-level role.",
        governmentJobs: "Employed directly by the Ministry of Home Affairs, NITI Aayog, or Police Academies.",
        privateSectorOpportunities: "Hired heavily by massive International NGOs, UN bodies, and global consulting firms.",
        workNature: "Policy Drafting, Systemic Audits, & International Research.",
        riskLevel: "Low",
        futureScope: "Highly relevant as nations seek to modernize their drastically outdated police and penal systems to meet global human rights standards.",
        jobDemandTrend: "Niche",
        summary: "A macro-level policy creator who doesn't fight cases, but instead fights to fix the entire criminal justice system from the top down."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Law Professor",
        description: "Dedicated to shaping the next generation of lawyers. They teach criminal jurisprudence, IPC, CrPC, and Evidence Act at elite national law universities, and frequently publish leading academic books.",
        educationPath: "LLB -> LLM -> Ph.D. in Law",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Pedagogy", "Academic Writing", "Jurisprudential Theory", "Debate & Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $160,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean or Vice-Chancellor"],
        courtPracticeOpportunities: "Can maintain a consulting appellate practice alongside teaching.",
        governmentJobs: "Permanent faculty positions in National Law Universities (NLUs).",
        privateSectorOpportunities: "Highly lucrative positions in elite private law schools (Jindal, Symbiosis).",
        workNature: "Teaching, Mentoring, & Academic Publishing.",
        riskLevel: "Low",
        futureScope: "Incredibly secure and prestigious. Top professors are frequently called upon by the Supreme Court to consult on constitutional criminal matters.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic guardians of criminal law, educating future generations and writing the textbooks that judges rely on."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Criminal Case Analyst",
        description: "Employed heavily by the media, true-crime networks, or massive defense teams to break down highly complex, nationwide sensational crimes into understandable narratives, timelines, and legal probabilities.",
        educationPath: "LLB / Journalism / Criminology",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Investigative Journalism (Optional)"],
        skills: ["Data Synthesis", "Timeline Construction", "Public Speaking", "Media Savvy"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $120,000 per year",
        roadmap: ["Case Analyst", "Lead Investigative Analyst", "Senior Legal Correspondent", "Media Personality / Author"],
        courtPracticeOpportunities: "None directly.",
        governmentJobs: "Occasional contractual analysis for specialized police task forces.",
        privateSectorOpportunities: "Massive demand in modern media, streaming networks (Netflix true-crime), and top-tier law firms.",
        workNature: "Media Consulting, Data Synthesis, & Public Broadcast Strategy.",
        riskLevel: "Low",
        futureScope: "Explosive growth due to the immense global popularity of true-crime media, documentaries, and 24/7 public interest in sensational trials.",
        jobDemandTrend: "Growing Rapidly",
        summary: "A brilliant analytical role that bridges the gap between complex criminal evidence and public/media consumption."
    },
    {
        domain: "Law",
        branch: "Criminal Law",
        title: "Legal Aid Attorney (Criminal Cases)",
        description: "Attorneys who provide totally free, fiercely dedicated criminal defense to the absolute poorest and most marginalized citizens who cannot afford a lawyer, ensuring a fair trial for the underprivileged.",
        educationPath: "LLB",
        competitiveExams: ["CLAT / State Entrance"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Empathy", "Rapid Trial Preparation", "Bail Mechanics", "Tenacity"],
        salaryRange: "India: ₹3 LPA - ₹8 LPA | Global: $50,000 - $85,000 per year",
        roadmap: ["Legal Aid Volunteer", "Staff Attorney", "Senior Defender", "Director of Public Defender Office"],
        courtPracticeOpportunities: "Massive, non-stop daily practice in trial courts, handling extreme volume.",
        governmentJobs: "Employed directly by the State Legal Services Authorities.",
        privateSectorOpportunities: "Employed by heavily funded litigation NGOs.",
        workNature: "High-Volume Courtroom Defense & Prison Visits.",
        riskLevel: "Moderate (Mentally exhausting with high burnout)",
        futureScope: "An incredibly noble calling that builds legendary courtroom endurance. Excellent training ground for future senior advocates and judges.",
        jobDemandTrend: "Constant",
        summary: "The ultimate protectors of constitutional rights, fighting tirelessly on the front lines to prevent the wrongful conviction of the impoverished."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Criminal Law" });
        await Career.insertMany(criminalLawProfessions);
        console.log('Criminal Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
