const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const entrepreneurshipProfessions = [
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Startup Founder (Entrepreneurship)",
        description: "A Startup Founder creates a new business from scratch, typically aimed at solving a specific problem with an innovative, scalable product or service. They are responsible for the initial vision, building the founding team, and securing early funding.",
        educationPath: "Flexible - B.Tech / BBA / MBA / Self-Taught / Domain Expertise",
        certifications: ["Y Combinator Startup School", "Various Startup Incubator Programs (Optional)"],
        yearsOfStudy: "Not Applicable",
        skills: ["Visionary Leadership", "Resilience", "Pitching/Fundraising", "Product Development", "Team Building"],
        salaryRange: "India: Equity-based (Often low initial salary, massive exit potential) | Global: Unlimited",
        roadmap: [
            "Ideation Phase: Concept Validation & MVP",
            "Startup Phase: Securing Seed Funding & First Users",
            "Scale Phase: Series A/B Funding & Rapid Growth",
            "Expansion Phase: Market Dominance",
            "Exit: IPO or Acquisition"
        ],
        governmentJobs: "None. Direct beneficiary of government schemes.",
        privateSectorOpportunities: "Building the next major private sector company.",
        remoteWorkPossibilities: "High (depending on the start-up type)",
        freelanceOpportunities: "This is the ultimate evolution of independent work.",
        futureScope: "With increasing access to global capital and technology, the barrier to creating a global tech or consumer company is lower than ever. The future economy relies heavily on bold founders.",
        jobDemandTrend: "Very High",
        summary: "The visionary risk-taker who builds the scalable companies of tomorrow, trading initial financial security for unlimited equity upside.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "Low to Moderate (Bootstrapping phase)",
        riskLevel: "Very High",
        incomePotential: "Unlimited",
        fundingOpportunities: "Bootstrapping, Angel Investors, Venture Capital",
        governmentSupportSchemes: "Startup India, Mudra Yojana, Stand-Up India",
        globalExpansionPossibility: "Very High",
        leadershipRequirementLevel: "Very High",
        decisionMakingResponsibilityLevel: "Very High",
        workNature: "Dynamic / Strategic / Risk-Based"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Co-Founder",
        description: "A Co-Founder partners with the primary founder to launch and scale a business. They typically bring complementary skills to the table—for example, a technical co-founder pairing with a business/sales-focused founder.",
        educationPath: "Flexible - B.Tech / BBA / MBA / Self-Taught / Domain Expertise",
        certifications: ["None required; proven skill in a specific domain (Tech, Sales, Finance) is critical."],
        yearsOfStudy: "Not Applicable",
        skills: ["Domain Expertise (Tech/Sales/Ops)", "Collaboration", "Strategic Execution", "Conflict Resolution", "Adaptability"],
        salaryRange: "India: Equity-based | Global: Unlimited",
        roadmap: [
            "Startup Phase: Joining the founding team for equity",
            "Scale Phase: Leading a specific massive department (e.g., CTO, CRO)",
            "Expansion Phase: Scaling operations internationally",
            "Exit: IPO or Acquisition"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "Building a major private enterprise alongside the founder.",
        remoteWorkPossibilities: "High",
        freelanceOpportunities: "N/A",
        futureScope: "Solo founders mathematically have lower success rates than co-founding teams. Investors highly prefer funding balanced teams of co-founders.",
        jobDemandTrend: "High",
        summary: "The critical operational or technical partner who shares the extreme risks and massive rewards of building a new company.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "Low (Usually contributes sweat equity)",
        riskLevel: "Very High",
        incomePotential: "Unlimited",
        fundingOpportunities: "Angel Investors, Venture Capital",
        governmentSupportSchemes: "Startup India",
        globalExpansionPossibility: "Very High",
        leadershipRequirementLevel: "High",
        decisionMakingResponsibilityLevel: "Very High",
        workNature: "Dynamic / Strategic / Risk-Based"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Small Business Owner",
        description: "Small Business Owners operate localized businesses such as retail stores, restaurants, local service agencies, or boutique firms. Their focus is generally on sustainable, profitable local operations rather than hyper-scaling globally.",
        educationPath: "Flexible - High School / B.Com / BBA / Vocational Training",
        certifications: ["Local Trade Licenses", "Basic Accounting/Tally"],
        yearsOfStudy: "Not Applicable",
        skills: ["Local Market Knowledge", "Customer Service", "Financial Prudence (Cash Flow Management)", "Local Networking", "People Management"],
        salaryRange: "India: ₹3 LPA - ₹50+ LPA (Net Profit) | Global: $50,000 - $500,000+",
        roadmap: [
            "Startup Phase: Opening one location/service",
            "Scale Phase: Reaching consistent profitability",
            "Expansion Phase: Opening 2-3 local branches",
            "Exit: Selling the business or passing to family"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "The backbone of the domestic private sector economy.",
        remoteWorkPossibilities: "Low (Usually requires physical presence)",
        freelanceOpportunities: "N/A",
        futureScope: "Small businesses remain the largest employers in most economies. While tech scales faster, local sustainable businesses offer steady, lifelong income generation.",
        jobDemandTrend: "Stable",
        summary: "The steady, highly profitable bedrock of the economy, focused on providing essential goods or services to a local community.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "Moderate to High",
        riskLevel: "Moderate",
        incomePotential: "High",
        fundingOpportunities: "Bank Loans (MSME), Bootstrapping",
        governmentSupportSchemes: "MSME Loans, Mudra Scheme, PMFME",
        globalExpansionPossibility: "Low",
        leadershipRequirementLevel: "Moderate",
        decisionMakingResponsibilityLevel: "High",
        workNature: "Dynamic / Operations-Based"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Serial Entrepreneur",
        description: "Serial Entrepreneurs continuously come up with new ideas, launch businesses, scale them to a certain point, and then sell them (or bring in a CEO to run them) while they move on to launch their next venture.",
        educationPath: "Flexible - Extensive real-world business experience",
        certifications: ["None required."],
        yearsOfStudy: "Not Applicable",
        skills: ["Pattern Recognition", "Rapid Prototyping", "Delegation", "Exit Strategy Negotiation", "Accessing Capital"],
        salaryRange: "India: Multi-Crore Exits | Global: Multi-Million Dollar Exits",
        roadmap: [
            "Venture 1: Build -> Scale -> Exit",
            "Venture 2: Reinvest capital -> Build faster -> Exit",
            "Venture 3+: Continuous portfolio creation"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "Creating multiple distinct corporations over a lifetime.",
        remoteWorkPossibilities: "High",
        freelanceOpportunities: "N/A",
        futureScope: "With established networks and proven track records, serial entrepreneurs attract VC funding effortlessly for new ventures compared to first-time founders.",
        jobDemandTrend: "High",
        summary: "The ultimate business creator who treats the act of 'building a company' as their primary lifelong profession.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "Low (Usually funded by VCs or previous exits)",
        riskLevel: "High",
        incomePotential: "Unlimited",
        fundingOpportunities: "Venture Capital, Private Equity, Own Capital",
        governmentSupportSchemes: "Tax rebates on reinvested capital gains.",
        globalExpansionPossibility: "Very High",
        leadershipRequirementLevel: "Very High",
        decisionMakingResponsibilityLevel: "Very High",
        workNature: "Strategic / Risk-Based"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Social Entrepreneur",
        description: "Social Entrepreneurs build businesses specifically to solve a social, cultural, or environmental problem (e.g., poor sanitation, lack of education, climate change). They prioritize social impact alongside, or sometimes above, pure financial profit.",
        educationPath: "Flexible - B.A/B.Sc / MSW / MBA / Domain Expertise",
        certifications: ["Social Innovation/Impact Certificates"],
        yearsOfStudy: "Not Applicable",
        skills: ["Empathy", "Grant Writing", "Stakeholder Management", "Sustainable Business Modeling", "Impact Measurement"],
        salaryRange: "India: Profit reinvested / Moderate salary | Global: $60,000 - $150,000 (often capped by charter)",
        roadmap: [
            "Startup Phase: Identifying a social crisis & piloting a solution",
            "Scale Phase: Securing grants/impact investments",
            "Expansion Phase: National or global impact scaling",
            "Exit: N/A (Usually remains a lifelong mission or structured NGO/B-Corp)"
        ],
        governmentJobs: "Partnering heavily with government welfare schemes.",
        privateSectorOpportunities: "Creating a successful B-Corporation or For-Profit Social Enterprise.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Consulting for NGOs or CSR wings of large companies.",
        futureScope: "As consumer awareness regarding ethics and climate change rises, 'Impact Investing' is becoming a massive financial sector, heavily funding these ventures.",
        jobDemandTrend: "Increasing rapidly",
        summary: "A purpose-driven founder utilizing capitalist efficiency to permanently solve deeply rooted societal and environmental crises.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "Moderate",
        riskLevel: "Moderate",
        incomePotential: "Moderate",
        fundingOpportunities: "Grants, Impact Investors, CSR Funds",
        governmentSupportSchemes: "Various NGO and Social Welfare Grants",
        globalExpansionPossibility: "Moderate to High",
        leadershipRequirementLevel: "High",
        decisionMakingResponsibilityLevel: "High",
        workNature: "Dynamic / Purpose-Driven / Field-oriented"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Tech Entrepreneur",
        description: "Tech Entrepreneurs build companies exclusively centered around a new software, application, AI model, or hardware. They rely heavily on intellectual property and coding architectures to disrupt existing non-digital industries.",
        educationPath: "B.Tech / B.Sc Computer Science / Self-taught Coder",
        certifications: ["Cloud Certifications (AWS/GCP), AI/ML Bootcamps"],
        yearsOfStudy: "Not Applicable",
        skills: ["Product Architecture", "Coding/Algorithm Design", "Tech Stack Management", "UI/UX Sensibility", "Venture Capital Pitching"],
        salaryRange: "India: Equity-based | Global: Unlimited",
        roadmap: [
            "Startup Phase: Coding the MVP (Minimum Viable Product)",
            "Scale Phase: Reaching Product-Market Fit & scaling servers",
            "Expansion Phase: Global user acquisition",
            "Exit: Tech Acquisition (e.g., bought by Google/Meta) or IPO"
        ],
        governmentJobs: "None. May bid for government tech contracts.",
        privateSectorOpportunities: "Leading the digital transformation of the economy.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "N/A",
        futureScope: "The most scalable form of entrepreneurship. Software has zero marginal cost of reproduction, allowing tech entrepreneurs to reach billions of users from a single laptop.",
        jobDemandTrend: "Extremely High",
        summary: "The architect of the digital age, writing code that transforms into billion-dollar companies disrupting traditional markets.",
        isFormalDegreeMandatory: "Optional (Code quality matters more than degrees)",
        initialInvestmentRequirement: "Low (A laptop and server costs)",
        riskLevel: "High",
        incomePotential: "Unlimited",
        fundingOpportunities: "Angel Investors, Venture Capital (Y Combinator, Sequoia)",
        governmentSupportSchemes: "Startup India Seed Fund",
        globalExpansionPossibility: "Very High",
        leadershipRequirementLevel: "Moderate (Early) to High (Scale)",
        decisionMakingResponsibilityLevel: "Very High",
        workNature: "Dynamic / Technical / Strategic"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Franchise Owner",
        description: "Franchise Owners purchase the rights to use a proven, larger brand's name, trademark, and business model (e.g., McDonald's, Domino's, Zara). They operate an independent location while adhering strictly to the parent company's operational rules.",
        educationPath: "Flexible - B.Com / BBA / Capital Availability",
        certifications: ["Parent company specific training programs"],
        yearsOfStudy: "Not Applicable",
        skills: ["Operations Management", "Staff Management", "Standard Operating Procedure (SOP) Compliance", "Local Marketing", "Inventory Control"],
        salaryRange: "India: ₹6 LPA - ₹50+ LPA (Net Profit) | Global: $60,000 - $300,000+",
        roadmap: [
            "Startup Phase: Paying franchise fee & setting up store to spec",
            "Scale Phase: Hiring reliable local managers & stabilizing profit",
            "Expansion Phase: Buying rights to open multiple franchise locations",
            "Exit: Selling the franchise rights to another operator"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "Operating within a massive global corporate network.",
        remoteWorkPossibilities: "Low",
        freelanceOpportunities: "N/A",
        futureScope: "A highly secure form of business ownership. As global mega-brands continue to expand into tier 2 and 3 cities, the demand for local operators is immense.",
        jobDemandTrend: "Stable",
        summary: "A lower-risk entrepreneurial path focusing on excellent operational execution of an already proven, billion-dollar business model.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "High to Very High (Franchise fees + Real Estate)",
        riskLevel: "Low",
        incomePotential: "High",
        fundingOpportunities: "Bank Loans (Collateral based), Own Capital",
        governmentSupportSchemes: "MSME Loans for infrastructure.",
        globalExpansionPossibility: "Low (Usually geographically restricted by contract)",
        leadershipRequirementLevel: "Moderate",
        decisionMakingResponsibilityLevel: "Moderate (Must follow brand rules)",
        workNature: "Operations-Based"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "E-Commerce Entrepreneur",
        description: "E-Commerce Entrepreneurs build borderless retail businesses online. They utilize platforms like Shopify, Amazon FBA, or custom websites to sell physical or digital goods directly to consumers, cutting out traditional retail middlemen.",
        educationPath: "Flexible - Self-taught digital marketing and sourcing",
        certifications: ["Digital Marketing, Google Ads, Amazon Global Selling"],
        yearsOfStudy: "Not Applicable",
        skills: ["Digital Advertising (Meta/Google Ads)", "Supply Chain/Sourcing (often from China/India)", "Conversion Rate Optimization", "Customer Retention", "Trend Spotting"],
        salaryRange: "India: ₹5 LPA - Multi-Crores | Global: Unlimited",
        roadmap: [
            "Startup Phase: Finding a winning product & setting up Shopify/Amazon",
            "Scale Phase: Scaling ad budgets profitably",
            "Expansion Phase: Expanding product lines & global shipping",
            "Exit: Selling the D2C brand to an aggregator (e.g., Thrasio)"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "Building massive Direct-to-Consumer (D2C) brands.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "N/A",
        futureScope: "The dominant form of modern retail. Dropshipping and third-party logistics (3PL) allow sole founders to run multi-million dollar retail empires from a laptop.",
        jobDemandTrend: "Very High",
        summary: "A heavily digital, marketing-focused founder who constructs modern, scalable retail brands entirely on the internet.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "Low to Moderate (Ad spend & Initial Inventory)",
        riskLevel: "Moderate (Testing products fast minimizes risk)",
        incomePotential: "Unlimited",
        fundingOpportunities: "Bootstrapping, Revenue-based financing",
        governmentSupportSchemes: "Export incentives if selling globally.",
        globalExpansionPossibility: "Very High",
        leadershipRequirementLevel: "Low (Often run with very small teams/contractors)",
        decisionMakingResponsibilityLevel: "High",
        workNature: "Dynamic / Digital / Analytical"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Family Business Manager",
        description: "Family Business Managers (often second or third-generation heirs) take over existing family run enterprises. Their primary challenge is modernizing legacy systems, introducing corporate governance, and scaling the business without breaking family harmony.",
        educationPath: "BBA / B.Com -> MBA in Family Managed Business (FMB)",
        certifications: ["Specialized FMB Programs (e.g., S.P. Jain FMB)"],
        yearsOfStudy: "Not Applicable",
        skills: ["Change Management", "Conflict Resolution", "Financial Modernization", "Respect for Legacy", "Strategic Scaling"],
        salaryRange: "India: Inherited Wealth / Profit Share | Global: Varies",
        roadmap: [
            "Startup Phase: Shadowing the founder/patriarch",
            "Scale Phase: Introducing tech, professional HR, and modern accounting",
            "Expansion Phase: Taking the local business national/international",
            "Exit: Preparing the business for the next generation or IPO"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "Transforming traditional massive SMEs into modern corporate entities.",
        remoteWorkPossibilities: "Low",
        freelanceOpportunities: "N/A",
        futureScope: "A massive percentage of the Indian and global economy relies on family businesses. The transition phase to the modern, tech-savvy generation is critical for economic survival.",
        jobDemandTrend: "Stable",
        summary: "The crucial bridge between a business's traditional, founder-led past and its corporatized, scalable future.",
        isFormalDegreeMandatory: "Optional (But highly recommended to bring outside perspective)",
        initialInvestmentRequirement: "Low (Inheriting existing infrastructure)",
        riskLevel: "Moderate",
        incomePotential: "High",
        fundingOpportunities: "Existing cash flow, Bank Loans",
        governmentSupportSchemes: "MSME upgradation schemes.",
        globalExpansionPossibility: "Moderate",
        leadershipRequirementLevel: "High",
        decisionMakingResponsibilityLevel: "Very High",
        workNature: "Strategic / Relationship-Based"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Business Consultant (Independent)",
        description: "Independent Business Consultants are entrepreneurial experts who sell their specialized knowledge (marketing, finance, operations, strategy) to other businesses. They operate as a 'company of one', taking on high-level advisory projects on a contract basis.",
        educationPath: "Domain Expertise -> MBA (Optional) -> Extensive Industry Experience",
        certifications: ["CMC (Certified Management Consultant)"],
        yearsOfStudy: "Not Applicable",
        skills: ["Deep Niche Expertise", "Networking/Sales", "Client Management", "Diagnostics/Problem Solving", "Personal Branding"],
        salaryRange: "India: ₹10 LPA - ₹1 Crore+ | Global: $100,000 - $500,000+",
        roadmap: [
            "Startup Phase: Leaving a corporate job and securing first 2-3 clients",
            "Scale Phase: Raising hourly/project rates based on results",
            "Expansion Phase: Productizing knowledge (courses/books) or hiring junior consultants",
            "Exit: Building an agency and selling it, or retiring"
        ],
        governmentJobs: "Consulting on government projects via tenders.",
        privateSectorOpportunities: "Advising startups, SMEs, and occasionally large corporations.",
        remoteWorkPossibilities: "High",
        freelanceOpportunities: "This is a premium freelance/agency model.",
        futureScope: "The gig economy is reaching the C-suite. 'Fractional CMOs' or 'Fractional CFOs' are highly demanded by startups who need expert advice but cannot afford a full-time executive salary.",
        jobDemandTrend: "High",
        summary: "A highly lucrative 'solopreneur' path monetizing years of hard-earned corporate or entrepreneurial wisdom.",
        isFormalDegreeMandatory: "No (Experience and track record are paramount)",
        initialInvestmentRequirement: "Very Low (Requires only a laptop and network)",
        riskLevel: "Low",
        incomePotential: "High",
        fundingOpportunities: "Bootstrapping",
        governmentSupportSchemes: "None specific.",
        globalExpansionPossibility: "High",
        leadershipRequirementLevel: "Low (Leading clients, not employees)",
        decisionMakingResponsibilityLevel: "High (Advisory capability)",
        workNature: "Advisory / Strategic / Networking"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Venture Capitalist (VC)",
        description: "Venture Capitalists manage pooled funds from wealthy individuals and institutions to invest in high-risk, high-reward startups. They don't build companies directly; they aggressively hunt for the best founders, provide millions in capital, and take equity in return.",
        educationPath: "Elite MBA (IIM/Ivy League) / Ex-Founder / Ex-Investment Banker",
        certifications: ["CFA (Optional)"],
        yearsOfStudy: "Not Applicable",
        skills: ["Financial Modeling", "Market Sizing", "Extreme Networking", "Due Diligence", "Board-level Advisory"],
        salaryRange: "India: Base (High) + Massive Carry (Share of profits) | Global: Base ($150k+) + Millions in Carry",
        roadmap: [
            "Executive: Associate / Analyst (Hunting for deals)",
            "Manager: Principal (Leading deals and sitting on boards)",
            "Senior Manager: Partner",
            "Director: Managing Partner (Raising the fund itself)"
        ],
        governmentJobs: "Managing government-backed startup sovereign funds (e.g., SIDBI).",
        privateSectorOpportunities: "Core roles in Major VC firms (Sequoia, Accel, Nexus).",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "N/A",
        futureScope: "They are the kingmakers of the modern economy. VCs dictate which technologies and companies get the fuel (cash) required to take over the world.",
        jobDemandTrend: "Highly Competitive",
        summary: "The financial elite of the startup ecosystem, making high-stakes bets on unproven founders with the goal of finding the next billion-dollar 'unicorn'.",
        isFormalDegreeMandatory: "Yes (Unless previously a successful founder)",
        initialInvestmentRequirement: "N/A (Managing others' money)",
        riskLevel: "High (For the fund, not personal capital)",
        incomePotential: "Unlimited",
        fundingOpportunities: "Raising capital from LPs (Limited Partners - Pension funds, Billionaires)",
        governmentSupportSchemes: "Fund of Funds for Startups (FFS).",
        globalExpansionPossibility: "High",
        leadershipRequirementLevel: "Moderate",
        decisionMakingResponsibilityLevel: "Very High",
        workNature: "Financial / Strategic / Networking"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Angel Investor",
        description: "Angel Investors are typically wealthy individuals (often successful ex-entrepreneurs themselves) who use their own personal money to fund startups at their absolute earliest, riskiest stage—often when it's just an idea on a napkin.",
        educationPath: "N/A - Requires possessing significant personal liquid wealth.",
        certifications: ["None."],
        yearsOfStudy: "Not Applicable",
        skills: ["Risk Tolerance", "Gut Instinct regarding Founders", "Industry Foresight", "Mentorship", "Deal Structuring"],
        salaryRange: "India & Global: Entirely dependent on the success (ROI) of their portfolio companies.",
        roadmap: [
            "Startup Phase: Writing small checks ($10k - $50k) to multiple founders",
            "Scale Phase: Helping founders raise larger institutional (VC) rounds",
            "Expansion Phase: N/A",
            "Exit: Cashing out shares when the startup goes public or is acquired"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "Acting as an independent catalyst in the private tech sector.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "N/A",
        futureScope: "Angel investors are the crucial first bridge for founders who have ideas but no traction yet. Their numbers are exploding due to the creation of Angel Syndicates and platforms like AngelList.",
        jobDemandTrend: "N/A (Depends on personal wealth)",
        summary: "A high net-worth individual acting as a crucial mentor and the very first financial backer for unproven, high-potential startups.",
        isFormalDegreeMandatory: "No",
        initialInvestmentRequirement: "Very High (Requires personal capital to burn)",
        riskLevel: "Very High",
        incomePotential: "Unlimited",
        fundingOpportunities: "Personal Wealth",
        governmentSupportSchemes: "Tax exemptions on angel investments (Angel Tax exemptions).",
        globalExpansionPossibility: "High (Investing globally via syndicates)",
        leadershipRequirementLevel: "Low",
        decisionMakingResponsibilityLevel: "High (Personal financial risk)",
        workNature: "Advisory / Financial Risk-Taking"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Startup Incubator Manager",
        description: "Startup Incubator/Accelerator Managers run programs designed to systematically help early-stage startups succeed. They provide founders with office space, strict mentorship curriculums, networking events with investors, and early-stage seed capital.",
        skills: ["Program Management", "Ecosystem Networking", "Mentorship Coordination", "Event Organization", "Start-up Evaluation"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $75,000 - $140,000 per year",
        educationPath: "MBA / Ex-Founder / Experience in the VC-Startup Ecosystem",
        futureScope: "Governments and universities worldwide are aggressively opening incubators to foster local innovation, creating a massive demand for professionals who know how to organize and support erratic startup founders.",
        roadmap: [
            "Executive: Program Coordinator",
            "Manager: Incubator Manager / EIR (Entrepreneur in Residence)",
            "Senior Manager: Director of Programs",
            "Director: Head of Accelerator (e.g., Techstars, YC level)",
            "Global Head: Managing Director"
        ],
        certifications: ["None required."],
        summary: "The community builder and curriculum designer responsible for nurturing raw startup ideas into viable, fundable companies.",
        yearsOfStudy: "Not Applicable",
        isFormalDegreeMandatory: "No (Ecosystem presence matters)",
        initialInvestmentRequirement: "N/A",
        riskLevel: "Low (Salaried role)",
        incomePotential: "Moderate",
        fundingOpportunities: "University/Government Grants",
        governmentSupportSchemes: "Atal Incubation Centres (AIC) funding.",
        globalExpansionPossibility: "Moderate",
        leadershipRequirementLevel: "High",
        decisionMakingResponsibilityLevel: "Moderate",
        workNature: "Community / Educational / Strategic"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Innovation Manager (Corporate)",
        description: "Innovation Managers work inside massive, slow-moving corporations. Their job is to act like an entrepreneur, identifying disruptive new technologies (like AI or Web3), prototyping new products, and preventing the corporation from becoming obsolete.",
        educationPath: "B.Tech / BBA -> MBA in Innovation/Strategy -> Corporate Experience",
        certifications: ["Design Thinking, Agile/Scrum Certifications"],
        yearsOfStudy: "Not Applicable",
        skills: ["Design Thinking", "Trend Forecasting", "Internal Corporate Politics", "Rapid Prototyping", "Risk Management"],
        salaryRange: "India: ₹15 LPA - ₹40 LPA | Global: $100,000 - $180,000 per year",
        roadmap: [
            "Executive: Innovation Analyst",
            "Manager: Innovation Manager",
            "Senior Manager: Director of R&D / Innovation Lab",
            "Director: Chief Innovation Officer (CINO)",
            "Global Head: Chief Strategy Officer"
        ],
        governmentJobs: "Innovation cells within major PSUs and government bodies (NITI Aayog).",
        privateSectorOpportunities: "Critical roles in FMCG, Banking, and Legacy Tech companies terrified of being disrupted by agile startups.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Innovation consulting for legacy brands.",
        futureScope: "As the pace of technological change accelerates exponentially, corporations must innovate constantly to survive. The CINO (Chief Innovation Officer) is becoming as important as the CFO.",
        jobDemandTrend: "High",
        summary: "The internal disruptor tasked with keeping massive legacy corporations relevant in a rapidly evolving, tech-driven world.",
        isFormalDegreeMandatory: "Yes (Corporate requirement)",
        initialInvestmentRequirement: "N/A",
        riskLevel: "Low",
        incomePotential: "High",
        fundingOpportunities: "Corporate R&D Budgets",
        governmentSupportSchemes: "R&D tax credits for corporations.",
        globalExpansionPossibility: "High",
        leadershipRequirementLevel: "High",
        decisionMakingResponsibilityLevel: "High",
        workNature: "Strategic / Corporate / Research-Based"
    },
    {
        domain: "Commerce",
        branch: "Entrepreneurship",
        title: "Corporate Entrepreneur (Intrapreneur)",
        description: "An Intrapreneur is an employee who is given the financial backing, resources, and freedom to build a completely new startup internally within a massive corporation (e.g., the team that built Gmail inside Google, or AWS inside Amazon).",
        educationPath: "Highly variable. Usually top performers within a specialized domain in a company.",
        certifications: ["None. Promoted based on internal merit and visionary ideas."],
        yearsOfStudy: "Not Applicable",
        skills: ["Visionary Execution", "Resource Mobilization", "Corporate Navigation", "Product Development", "Risk Negotiation"],
        salaryRange: "India: ₹20 LPA - ₹1 Crore+ (Plus massive internal bonuses) | Global: $150,000 - $300,000+",
        roadmap: [
            "Startup Phase: Pitching the 'Startup' idea to the Corporate Board",
            "Scale Phase: Building the product using massive corporate capital",
            "Expansion Phase: Launching as a new critical division of the parent company",
            "Exit: Becoming the CEO/VP of the new spin-off division"
        ],
        governmentJobs: "None.",
        privateSectorOpportunities: "Exclusive to massive, forward-thinking tech and conglomerate companies (Tata, Reliance, Google, Amazon).",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "N/A",
        futureScope: "Corporations realize they lose their best talent if they don't allow them to act like founders. Giving brilliant employees the capital to build intra-startups is the ultimate corporate retention strategy.",
        jobDemandTrend: "High (But roles are highly exclusive)",
        summary: "The ultimate hybrid—possessing the freedom and creative power of a startup founder, backed by the infinite capital and safety net of a multi-billion dollar corporation.",
        isFormalDegreeMandatory: "Optional (Track record trumps degrees)",
        initialInvestmentRequirement: "N/A (Funded by parent corporation)",
        riskLevel: "Low to Moderate (Failed projects don't ruin personal finances)",
        incomePotential: "High",
        fundingOpportunities: "Corporate Treasury",
        governmentSupportSchemes: "None.",
        globalExpansionPossibility: "Very High",
        leadershipRequirementLevel: "Very High",
        decisionMakingResponsibilityLevel: "Very High",
        workNature: "Dynamic / Strategic / High-Resources"
    }
];

const seedEntrepreneurshipProfessions = async () => {
    try {
        await Career.deleteMany({ branch: "Entrepreneurship" });
        await Career.insertMany(entrepreneurshipProfessions);
        console.log('Entrepreneurship Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedEntrepreneurshipProfessions();
