const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const politicalScienceProfessions = [
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Political Scientist",
        description: "Study the origin, development, and operation of political systems. They research political ideas and analyze governments, policies, political trends, and related issues.",
        summary: "Researchers who analyze policies, political trends, and the fundamental operation of governments worldwide.",
        skills: ["Data Analysis", "Political Theory", "Research Methodologies", "Public Policy Knowledge", "Critical Writing"],
        salaryRange: "India: ₹6L - ₹18L | Global: $60K - $125K",
        educationPath: "B.A. Political Science → M.A. Political Science → Ph.D. or Public Policy Degree",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Government Agencies", "Think Tanks", "Labor Organizations"],
        futureScope: "Steady demand. Governments and NGOs increasingly rely on data-driven political forecasting and policy analytics.",
        jobDemandTrend: "Stable",
        competitiveExams: ["UGC NET (for professorships)", "Civil Services (Optional Subject)"],
        governmentJobs: "High. Employed directly as researchers for legislative branches and state intelligence units.",
        privateSectorOpportunities: "Moderate. Mostly working with corporate lobbying groups or major NGOs.",
        roadmap: ["B.A. in Political Science", "Advanced research degrees", "Join a research institute/university", "Senior Political Analyst / Professor"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Policy Analyst",
        description: "Examine the efficacy of existing policies and lay out the groundwork for new legislation. They focus strongly on healthcare, economics, or environmental policy.",
        summary: "Specialists who evaluate laws and regulations to determine their actual impact on the public.",
        skills: ["Quantitative Analysis", "Legislative Process Knowledge", "Economics Basics", "Statistical Software", "Public Speaking"],
        salaryRange: "India: ₹5L - ₹16L | Global: $55K - $110K",
        educationPath: "B.A. Political Science/Economics → M.A. Public Policy (MPP)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Think Tanks", "Non-Profits", "Government Ministries", "Corporate Strategy Departments"],
        futureScope: "High growth. The increasing complexity of tech, environment, and social laws constantly requires expert evaluation.",
        jobDemandTrend: "Growing",
        competitiveExams: ["State Public Service Commissions (Policy wings)"],
        governmentJobs: "High. Crucial roles within state and federal departments crafting legislation.",
        privateSectorOpportunities: "High. Corporations heavily employ them to analyze how new laws will impact their business.",
        roadmap: ["Degree in Public Policy", "Research Assistant", "Lead Policy Analyst for a sector", "Director of Policy Strategy"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Public Policy Advisor",
        description: "Advise elected officials, legislative committees, or corporate executives directly on the implications of specific public policies and political strategies.",
        summary: "The direct advisors to politicians and CEOs, guiding their decisions on new laws and regulations.",
        skills: ["Strategic Communication", "Crisis Management", "Stakeholder Negotiation", "Policy Drafting", "Networking"],
        salaryRange: "India: ₹8L - ₹25L | Global: $70K - $150K",
        educationPath: "M.A. Public Policy / J.D. (Law Degree)",
        yearsOfStudy: "5 to 7 Years",
        industriesHiring: ["Political Campaigns", "Legislative Offices", "Lobbying Firms", "Major Corporations"],
        futureScope: "Highly lucrative and influential. Senior advisors hold immense un-elected power in shaping modern legislation.",
        jobDemandTrend: "Competitive, High Value",
        competitiveExams: ["None specific; purely based on networking and competence."],
        governmentJobs: "High. Serving directly alongside Ministers, Senators, and Mayors.",
        privateSectorOpportunities: "High. Often heavily recruited by private consulting firms and tech giants (e.g., Google's public policy team).",
        roadmap: ["Legislative Intern/Aide", "Master's Degree", "Policy Advisor", "Chief of Staff / Senior Advisor"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Political Consultant",
        description: "Promote the election of certain candidates or the interests of certain groups. They plan campaigns, coordinate media strategies, and conduct political polling.",
        summary: "The strategists who run political campaigns and manage the public image of politicians.",
        skills: ["Campaign Strategy", "Media Relations", "Polling/Data Analytics", "Fundraising", "Crisis PR"],
        salaryRange: "India: ₹6L - ₹30L+ (Project based) | Global: $65K - $200K+ (Project based)",
        educationPath: "B.A. Political Science / Communications",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Political Campaigns", "PR Firms", "PACs (Political Action Committees)"],
        futureScope: "Massive growth. Political consulting is a multi-billion dollar industry globally, especially digital media consulting.",
        jobDemandTrend: "Highly Variable (Election Cycle Dependent)",
        competitiveExams: ["None."],
        governmentJobs: "Low. Most consultants operate in the private sector selling strategy to politicians.",
        privateSectorOpportunities: "Very High. Operate their own highly lucrative strategic agencies.",
        roadmap: ["Campaign Volunteer/Staffer", "Manage regional campaigns", "Specialize in data or media", "Partner at a major Political Consulting Firm"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Legislative Assistant",
        description: "Support legislators in drafting bills, interacting with constituents, maintaining schedules, and researching the political viability of upcoming votes.",
        summary: "The backbone staff members keeping the offices of politicians and lawmakers functional.",
        skills: ["Constituent Relations", "Fast Research", "Memo Writing", "Organization", "Discretion"],
        salaryRange: "India: ₹3L - ₹8L | Global: $40K - $75K",
        educationPath: "B.A. Political Science",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Federal/State Legislatures", "City Councils", "Parliamentary Offices"],
        futureScope: "A standard, excellent entry-point. Acts as the primary training ground for future politicians and senior advisors.",
        jobDemandTrend: "Steady, High Turnover",
        competitiveExams: ["Legislative Secretariat Exams (India)"],
        governmentJobs: "Maximum. You are directly employed by the government or the elected official's office.",
        privateSectorOpportunities: "Low. Though many leave to join private lobbying firms.",
        roadmap: ["Political Science degree", "Campaign volunteer", "Legislative Assistant", "Legislative Director / Chief of Staff"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Diplomat",
        description: "Represent their home country's interests abroad. They negotiate international treaties, protect traveling citizens, and manage foreign trade relations.",
        summary: "Official government envoys managing international relations and foreign policy directly in other nations.",
        skills: ["International Law", "Foreign Languages", "Cross-Cultural Negotiation", "Diplomatic Protocol", "Macro-Economics"],
        salaryRange: "India: ₹10L - ₹25L+ (Plus huge perks) | Global: $70K - $160K+ (Varies by rank)",
        educationPath: "B.A./M.A. Political Science / International Relations",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Ministry of External Affairs (MEA)", "United Nations", "Embassies/Consulates"],
        futureScope: "Highly prestigious and fiercely guarded. Requires lifelong commitment but offers unmatched global influence.",
        jobDemandTrend: "Extremely Competitive",
        competitiveExams: ["UPSC Civil Services (IFS) in India", "Foreign Service Officer Test (FSOT) in US"],
        governmentJobs: "Maximum. A purely governmental role representing the sovereign state.",
        privateSectorOpportunities: "None while active. High-level corporate advisory roles upon retirement.",
        roadmap: ["Pass demanding Foreign Service Exams", "Junior Attaché", "Consul General", "Ambassador"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Civil Services Officer",
        description: "Manage the sprawling administrative operations of the government, implementing the laws drafted by politicians across districts and states.",
        summary: "The executive bureaucrats responsible for the day-to-day governance and administration of the country.",
        skills: ["Public Administration", "Constitutional Law", "Crisis Management", "Leadership", "Budgeting"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $60K - $130K",
        educationPath: "Any Bachelor's (Political Science is highly preferred for the syllabus)",
        yearsOfStudy: "3 to 5 Years (Plus years of exam prep)",
        industriesHiring: ["Federal, State, and Local Governments"],
        futureScope: "The bedrock of stability in nations like India and the UK. Offers immense authority and job security.",
        jobDemandTrend: "Extremely Competitive",
        competitiveExams: ["UPSC CSE (IAS, IPS, IRS) in India", "State PSCs"],
        governmentJobs: "Maximum. The highest tier of government employment.",
        privateSectorOpportunities: "None while active.",
        roadmap: ["Crack UPSC/equivalent exams", "District level administration", "State secretariats", "Secretary to the Government"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Election Analyst",
        description: "Use statistical modeling and demographic data to predict election outcomes (psephology), analyze voting patterns, and advise news networks or political parties.",
        summary: "The data scientists of politics (Psephologists) who predict who will win elections based on voting data.",
        skills: ["Psephology", "Advanced Statistics (R/Python)", "Demographic Analysis", "Polling Methodologies", "Election Law"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $120K",
        educationPath: "B.A. Political Science → M.Sc. Data Science / Statistics",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["News Broadcasting Networks", "Polling Agencies (e.g., Gallup)", "Political Parties"],
        futureScope: "High growth. The integration of big data into modern elections has made quantitative election analysts incredibly valuable.",
        jobDemandTrend: "Growing rapidly",
        competitiveExams: ["None."],
        governmentJobs: "Low. Works occasionally with Election Commissions for demographic mapping.",
        privateSectorOpportunities: "High. News networks and private polling agencies are the primary employers.",
        roadmap: ["Political Science & Stats background", "Work with polling firms", "Model complex national elections", "Chief Polling Strategist"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Political Researcher",
        description: "Conduct deep background research on rival political candidates (opposition research), historical voting records, and current public sentiment to feed into campaign strategies.",
        summary: "Investigators digging into voting records, candidate histories, and public data to build campaign dossiers.",
        skills: ["Opposition Research", "Database Mining", "Legal Record Analysis", "Fact-Checking", "Discretion"],
        salaryRange: "India: ₹4L - ₹10L | Global: $50K - $90K",
        educationPath: "B.A. Political Science/Journalism",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Political Campaigns", "Opposition Research Firms", "Journalism Investigatory Units"],
        futureScope: "A permanent fixture of modern adversarial politics. As long as there are campaigns, 'oppo-researchers' are heavily funded.",
        jobDemandTrend: "Steady",
        competitiveExams: ["None."],
        governmentJobs: "Low.",
        privateSectorOpportunities: "High. Heavily utilized by private political consulting firms and major campaigns.",
        roadmap: ["Political Science degree", "Junior Researcher on a campaign", "Opposition Research Specialist", "Director of Research Strategy"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Political Journalist",
        description: "Report on political events, campaigns, specific legislation, and government controversies for newspapers, television networks, and digital media.",
        summary: "Reporters who keep the public informed on government actions and political maneuvering.",
        skills: ["Investigative Reporting", "Political Network Building", "Shorthand/Fast Writing", "Constitutional Knowledge", "Neutrality/Objectivity"],
        salaryRange: "India: ₹4L - ₹15L | Global: $45K - $100K",
        educationPath: "B.A. Political Science / Journalism",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["News Networks (CNN, NDTV, BBC)", "Digital Publications", "Print Media"],
        futureScope: "Crucial for democracy, but the industry is undergoing massive shifts towards independent digital journalism and newsletters (e.g., Substack).",
        jobDemandTrend: "Competitive, Evolving",
        competitiveExams: ["None."],
        governmentJobs: "Low.",
        privateSectorOpportunities: "High. The entire journalistic media landscape is largely privatized.",
        roadmap: ["Journalism degree", "Local political beat reporter", "National political correspondent", "Senior Political Editor / Anchor"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Government Affairs Manager",
        description: "Act as the bridge between massive corporations and the government. They lobby for laws that benefit their industry and ensure their company complies with new state regulations.",
        summary: "Corporate lobbyists representing company interests directly to legislators to shape favorable laws.",
        skills: ["Corporate Lobbying", "Regulatory Compliance", "Advocacy", "Relationship Management", "Business Acumen"],
        salaryRange: "India: ₹10L - ₹30L+ | Global: $85K - $160K+",
        educationPath: "B.A. Political Science / J.D. (Law) / MBA",
        yearsOfStudy: "5 to 7 Years",
        industriesHiring: ["Major Corporations (Tech, Pharma, Energy)", "Industry Trade Associations", "Lobbying Firms"],
        futureScope: "Extremely lucrative. Tech companies facing antitrust lawsuits are currently spending billions on government affairs managers globally.",
        jobDemandTrend: "High Growth",
        competitiveExams: ["None."],
        governmentJobs: "Low. You lobby *to* the government, you don't work *for* them.",
        privateSectorOpportunities: "Maximum. This is the ultimate private-sector application of political science.",
        roadmap: ["Political Science/Law degree", "Work in government (to build network)", "Move to private sector affairs", "VP of Global Government Relations"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "International Relations Specialist",
        description: "Analyze how global events, trade wars, and foreign conflicts impact organizations like international NGOs, multinational corporations, or defense contractors.",
        summary: "Global strategists analyzing how conflicts and treaties affect international businesses and charities.",
        skills: ["Geopolitical Analysis", "Global Trade Agreements", "Cultural Fluency", "Risk Assessment", "Foreign Languages"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $120K",
        educationPath: "M.A. International Relations / Global Affairs",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["International NGOs (Red Cross)", "Multinational Tech/Finance Firms", "Risk Consultancies"],
        futureScope: "High demand. In an interconnected supply chain, disruptions in one country massively affect another, requiring global specialists.",
        jobDemandTrend: "Growing",
        competitiveExams: ["None specific, unless entering UN programs (YPP)."],
        governmentJobs: "Moderate. Intelligence agencies and defense ministries.",
        privateSectorOpportunities: "High. Defense contractors and global finance firms hire them to predict geopolitical risks.",
        roadmap: ["M.A. International Relations", "Analyst at a global firm", "Geopolitical Risk Consultant", "Director of International Strategy"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Public Administration Officer",
        description: "Oversee specific municipal or state departments—like housing, transportation, or public health—ensuring that government funds are spent efficiently and legally.",
        summary: "The executives managing city and state departments to ensure public services function smoothly.",
        skills: ["Public Budgeting", "Urban Planning Basics", "Personnel Management", "Bureaucratic Navigation", "Grant Administration"],
        salaryRange: "India: ₹6L - ₹15L | Global: $60K - $110K",
        educationPath: "Master of Public Administration (MPA)",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["City Governments", "State Departments", "Public Universities"],
        futureScope: "Incredibly stable. Cities will always require trained administrators to manage public school budgets, housing, and transit.",
        jobDemandTrend: "Stable",
        competitiveExams: ["State Public Service Commissions", "Municipal Exams"],
        governmentJobs: "Maximum. The core of this career is municipal or state operation.",
        privateSectorOpportunities: "Low. Though skills transfer well to managing large NGOs.",
        roadmap: ["Get an MPA degree", "Assistant City Manager / Department Analyst", "Department Head", "City Manager"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Political Campaign Manager",
        description: "The absolute leader of a political campaign. They hire staff, manage massive multi-million dollar budgets, dictate the policy platform, and handle the candidate's schedule.",
        summary: "The executives running the entire operation of a politician's election campaign.",
        skills: ["Executive Leadership", "Crisis Management", "Financial Oversight", "Political Intuition", "Ruthless Organization"],
        salaryRange: "India: ₹8L - ₹40L+ | Global: $80K - $250K+ (Highly variable)",
        educationPath: "B.A. Political Science/Business",
        yearsOfStudy: "4 Years",
        industriesHiring: ["Political Action Committees (PACs)", "Direct Candidates", "National Party Committees"],
        futureScope: "High risk, high reward. A successful campaign manager for a major national candidate essentially writes their own ticket in politics.",
        jobDemandTrend: "Volatile, High Demand",
        competitiveExams: ["None."],
        governmentJobs: "Low. You operate in campaigns; though victory usually results in a top White House / Prime Minister's Office staff position.",
        privateSectorOpportunities: "High. Campaign organizations are essentially large private startups.",
        roadmap: ["Volunteer/Field Organizer", "Regional Campaign Director", "Manage a Congressional/State level race", "National Campaign Manager"]
    },
    {
        domain: "Arts",
        branch: "Political Science",
        title: "Political Think Tank Researcher",
        description: "Work at privately funded institutes to produce 'white papers' and extensive studies that argue for specific political ideologies or public policies.",
        summary: "Ideological scholars producing the research that political parties use to justify their new laws.",
        skills: ["Deep Policy Research", "Ideological Frameworks", "Academic Writing", "Statistical Synthesis", "Media Defensibility"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $110K",
        educationPath: "M.A. or Ph.D. in Political Science",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Brookings Institution, ORF, Heritage Foundation, etc.", "Policy Institutes"],
        futureScope: "Highly influential. Think tanks are often referred to as 'universities without students' and heavily dictate national debate.",
        jobDemandTrend: "Competitive, Steady",
        competitiveExams: ["None."],
        governmentJobs: "Moderate. Rotating door between think tanks and formal government advisory roles.",
        privateSectorOpportunities: "High. Think tanks are private, privately-funded institutions.",
        roadmap: ["Ph.D. in Political Science", "Research fellow", "Publish influential policy papers", "Senior Fellow / Director of Policy"]
    }
];

const seedPoliticalScience = async () => {
    try {
        await Career.deleteMany({ branch: "Political Science" });
        await Career.insertMany(politicalScienceProfessions);
        console.log('Political Science Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedPoliticalScience();
