const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const radiologyProfessions = [
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Diagnostic Radiologist (MD/DO)",
        description: "Medical doctors who specialize strictly in diagnosing diseases and injuries by analyzing all forms of medical imaging (X-rays, CT, MRI, PET, Ultrasound).",
        summary: "Medical doctors acting as the final authority in interpreting medical imaging for diagnoses.",
        skills: ["Deep Anatomical Pathology", "Multi-Modality Image Interpretation", "Diagnostic Synthesis", "Consultative Communication with Surgeons"],
        salaryRange: "India: ₹12L - ₹40L+ | Global: $350K - $500K+",
        educationPath: "MBBS/DO → MD/DNB in Radiodiagnosis",
        yearsOfStudy: "10 to 12 Years",
        industriesHiring: ["Multi-Specialty Hospitals", "Private Diagnostic Centers", "Teleradiology IT Companies"],
        futureScope: "Extremely stable and lucrative. While AI will heavily assist, liability and complex case integration mean doctors will remain the final sign-off.",
        jobDemandTrend: "High",
        governmentJobs: "High. Required in every state and central hospital.",
        freelanceOpportunities: "Maximum. Consulting for multiple clinics or working purely remotely as a Teleradiologist.",
        fieldWork: "Low. Entirely computer/dark-room based.",
        riskLevel: "Low",
        certifications: ["Medical Council Registration (Radiodiagnosis)"],
        internshipRequirements: "Rigorous 3-year MD residency constantly reading hundreds of scans daily.",
        roadmap: ["Radiology Resident", "Consultant Radiologist", "Head of Radiology", "Teleradiology Firm Director"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Interventional Radiologist (IR)",
        description: "Perform highly complex, minimally invasive surgical procedures (like placing stents or stopping internal bleeding) by using real-time CT and X-ray imaging to guide tiny catheters through the body's blood vessels.",
        summary: "Surgical specialists using real-time imaging to perform minimally invasive operations.",
        skills: ["Micro-surgical Cannulation", "Real-time Fluoroscopy Guidance", "Crisis Management (Trauma bleeding)", "Deep Vascular Anatomy"],
        salaryRange: "India: ₹18L - ₹50L+ | Global: $450K - $600K+",
        educationPath: "MBBS → MD (Radiology) → Fellowship in Interventional Radiology",
        yearsOfStudy: "12 to 14 Years",
        industriesHiring: ["Trauma Centers", "Cardiac/Vascular Hospitals", "Oncology Centers"],
        futureScope: "Explosive growth. IR is rapidly replacing traditional open surgeries as it results in less pain, shorter recovery, and microscopic precision.",
        jobDemandTrend: "Very High",
        governmentJobs: "High. Placed in advanced tertiary government trauma centers.",
        freelanceOpportunities: "Low. Heavily hospital-dependent due to the need for massive \"Cath Labs\".",
        fieldWork: "Low. OT/Cath-lab based.",
        riskLevel: "Moderate to High (Surgical risks, exposure to scattered radiation)",
        certifications: ["Fellowship in Interventional Radiology"],
        internshipRequirements: "Grueling fellowships operating on complex vascular trauma cases.",
        roadmap: ["IR Fellow", "Consultant Interventional Radiologist", "Chief of IR Surgery"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Radiologic Technologist (Radiographer)",
        description: "The primary imaging professionals performing diagnostic X-ray examinations, positioning patients precisely, and calculating correct radiation exposure levels to capture perfect images.",
        summary: "The frontline professionals physically positioning patients and operating X-ray machines.",
        skills: ["Patient Positioning", "Radiation Physics (kVp/mAs calculation)", "Anatomy", "Patient Care / Calming"],
        salaryRange: "India: ₹3L - ₹8L | Global: $60K - $85K",
        educationPath: "B.Sc Medical Imaging Technology / Radiography",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Hospitals", "Urgent Care Centers", "Orthopedic Clinics", "Portable X-ray Services"],
        futureScope: "Extremely stable. The baseline entry test for almost all physical trauma is an X-ray, guaranteeing constant, massive volume demand.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Maximum. Roles in every rural dispensary and state casualty ward.",
        freelanceOpportunities: "Moderate. Mobile/Portable X-ray services.",
        fieldWork: "Low to Moderate.",
        riskLevel: "Moderate (Occupational radiation exposure if protocols are ignored)",
        certifications: ["ARRT (RT) equivalent / State Radiography Council Registration"],
        internshipRequirements: "Extensive clinical hours shooting actual patient X-rays.",
        roadmap: ["Radiographer", "Senior Tech", "Shift Supervisor", "Modality Specialist"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "MRI Technologist",
        description: "Operate massive, highly complex magnetic resonance imaging (MRI) scanners, which use giant magnets and radio waves to generate stunningly detailed 3D cross-sectional images of soft tissues, brains, and spines.",
        summary: "Specialists operating massive superconducting magnets to image deep soft tissues and the brain.",
        skills: ["MRI Physics / Pulse Sequencing", "Claustrophobia Patient Management", "Strict Magnetic Safety Enforcement", "Cross-Sectional Anatomy"],
        salaryRange: "India: ₹4L - ₹10L | Global: $75K - $105K",
        educationPath: "B.Sc Medical Imaging → Advanced Training/Certification in MRI",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Neurology Centers", "Advanced Diagnostic Chains", "Sports Medicine Hospitals"],
        futureScope: "Growing steadily. As MRI becomes faster and cheaper, it is increasingly used to avoid the ionizing radiation of CT scans.",
        jobDemandTrend: "High",
        governmentJobs: "Moderate. Only in major tertiary state hospitals.",
        freelanceOpportunities: "Low. Machine dependent.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Risk of lethal accidents if metallic magnetic items enter the scan room)",
        certifications: ["ARRT (MR) equivalent"],
        internshipRequirements: "Hundreds of supervised hours configuring complex MRI parameters.",
        roadmap: ["MRI Tech", "Lead MRI Technologist", "MRI Safety Officer"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "CT (Computed Tomography) Technologist",
        description: "Operate rapidly rotating CT scanners to produce detailed 3D 'slice' views of the body, incredibly crucial in emergency trauma settings for quickly identifying internal bleeding or strokes.",
        summary: "Fast-paced trauma technologists creating massive 3D X-ray maps of patients in the ER.",
        skills: ["IV Insertion (for contrast dye)", "Instant Trauma Positioning", "Rapid Scan Configuration", "Recognizing Contrast Dye Allergenic Reactions"],
        salaryRange: "India: ₹4L - ₹9L | Global: $75K - $100K",
        educationPath: "B.Sc Medical Imaging → Specialized CT Training",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Emergency Rooms / Level 1 Trauma Centers", "Oncology Scans", "Cardiovascular Hospitals"],
        futureScope: "Highly secure. CT is the absolute gold-standard diagnostic tool in any hospital's emergency room due to its blinding speed.",
        jobDemandTrend: "High",
        governmentJobs: "High.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low. ER/Hospital based.",
        riskLevel: "Moderate (Daily occupational scattered X-ray exposure)",
        certifications: ["ARRT (CT) equivalent"],
        internshipRequirements: "Intense ER-based clinical hours.",
        roadmap: ["CT Tech", "Senior Trauma CT Tech", "CT Scan Supervisor"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Diagnostic Medical Sonographer (Ultrasound Tech)",
        description: "Use specialized wands (transducers) emitting high-frequency sound waves to create real-time, moving images of internal organs, blood flow, and developing fetuses without using any harmful radiation.",
        summary: "Experts using zero-radiation soundwaves to continuously image organs, hearts, and pregnancies.",
        skills: ["Acoustic Physics", "Dynamic/Real-Time Anatomy Understanding", "Extreme Transducer Hand Dexterity", "Patient Bedside Manner"],
        salaryRange: "India: ₹4L - ₹12L | Global: $80K - $115K",
        educationPath: "B.Sc/Diploma inside Medical Sonography",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Maternity Clinics (OB/GYN)", "Cardiology Centers", "Vascular Surgery", "General Hospitals"],
        futureScope: "Explosive growth. Ultrasound imaging is entirely safe (no radiation), incredibly cheap, and machines are becoming highly portable.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High. Primary rural healthcare.",
        freelanceOpportunities: "Maximum. Many sonographers consult dynamically across multiple different maternity and private clinics daily.",
        fieldWork: "Moderate. Highly mobile within and outside the hospital.",
        riskLevel: "Low to Moderate (Extreme ergonomic wrist, shoulder, and neck injuries are rampant)",
        certifications: ["ARDMS Certification equivalent / PNDT Act Registration (India)"],
        internshipRequirements: "Mandatory hundreds of hours scanning live patients to develop transducer 'feel'.",
        roadmap: ["Sonographer", "Lead Sonographer", "Ultrasound Department Head"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Nuclear Medicine Technologist",
        description: "Inject patients with specialized, safe radioactive drugs (radiopharmaceuticals) and then operate massive gamma cameras or PET scanners to visualize how the body's cells are functioning on a metabolic level.",
        summary: "Specialists injecting patients with trace radiation to image actual cellular function, primarily for cancer detection.",
        skills: ["Radiation Safety (Handling unsealed isotopes)", "Venipuncture", "PET/SPECT Camera Operation", "Pharmacokinetics understanding"],
        salaryRange: "India: ₹5L - ₹12L | Global: $85K - $115K",
        educationPath: "B.Sc Nuclear Medicine Technology",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Oncology (Cancer) Hospitals", "Cardiac Stress Test Centers", "Specialized Imaging Centers"],
        futureScope: "High demand niche. PET scans are universally required to map cancer spread (metastasis). The technology is irreplaceable.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Moderate. Large national state hospitals only.",
        freelanceOpportunities: "Low. Requires heavily regulated, expensive facilities.",
        fieldWork: "Low. Lab/Camera room based.",
        riskLevel: "High (Handling and injecting unsealed liquid radioactive isotopes daily)",
        certifications: ["NMTCB or ARRT (N) equivalent / AERB approval (India)"],
        internshipRequirements: "Rigorous clinical hours in 'hot labs' explicitly preparing and injecting isotopes.",
        roadmap: ["Nuclear Medicine Tech", "PET/CT Specialist", "Radiation Safety Officer", "Department Supervisor"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Radiation Therapist",
        description: "Work exclusively in oncology, precisely operating massive linear accelerators to deliver calculated, lethal doses of high-energy radiation to entirely destroy cancerous tumors while sparing healthy tissue.",
        summary: "Crucial oncology technologists operating the massive machines that physically burn away cancer.",
        skills: ["Linear Accelerator Operation", "Extreme Geometric Precision", "Deep Empathy (Seeing patients constantly over weeks)", "Radiation Physics"],
        salaryRange: "India: ₹4.5L - ₹10L | Global: $85K - $125K",
        educationPath: "B.Sc Radiotherapy Technology",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Specialized Cancer Institutes", "Hospital Oncology Departments"],
        futureScope: "Extremely stable. Roughly 50% of all cancer patients will require targeted radiation therapy at some point in their treatment.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "High in state cancer and oncology wings.",
        freelanceOpportunities: "Low. Highly machine-dependent.",
        fieldWork: "Low. Bunker/Vault based.",
        riskLevel: "Moderate (Exposure risks, immense emotional strain from oncology care)",
        certifications: ["ARRT (T) equivalent / AERB (India)"],
        internshipRequirements: "Positioning hundreds of patients with absolute millimeter precision.",
        roadmap: ["Radiation Therapist", "Dosimetrist Trainee", "Lead Therapist", "Manager of Radiation Oncology"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Medical Dosimetrist",
        description: "Work behind the scenes alongside radiation oncologists to meticulously calculate and mathematically map out the exact angles and doses of radiation needed to destroy a tumor without killing the surrounding healthy organs.",
        summary: "The math and physics experts calculating the exact angles and doses required to safely irradiate cancer.",
        skills: ["Complex 3D Computer Modeling", "Advanced Geometry & Physics", "Anatomical Contouring", "Analytical Perfectionism"],
        salaryRange: "India: ₹6L - ₹15L | Global: $120K - $160K",
        educationPath: "B.Sc Radiotherapy / Physics → Specialized Diploma/Master's in Medical Dosimetry",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Comprehensive Cancer Centers", "Radiation Oncology Departments"],
        futureScope: "Highly lucrative. The shift towards hyper-precise radiotherapy (like CyberKnife or IMRT) heavily relies on expert dosimetric calculation.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Moderate. Remote remote treatment planning (Tele-dosimetry).",
        fieldWork: "Low. Purely computer/workstation based.",
        riskLevel: "Low",
        certifications: ["Certified Medical Dosimetrist (CMD)"],
        internshipRequirements: "Hundreds of hours virtually designing complex 3D radiation treatment plans.",
        roadmap: ["Junior Dosimetrist", "Certified Medical Dosimetrist", "Chief Dosimetrist"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Mammography Technologist",
        description: "Specialize strictly in imaging breast tissue to meticulously screen for early signs of breast cancer, requiring specialized X-ray equipment and extreme patient care.",
        summary: "Specialists trained explicitly to image breast tissue and detect breast cancer early.",
        skills: ["Breast Anatomy", "Mammography Positioning Mastery", "Patient Comfort and Empathy", "Attention to Microcalcifications"],
        salaryRange: "India: ₹3.5L - ₹8.5L | Global: $75K - $100K",
        educationPath: "B.Sc Radiography → Specialization in Mammography",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Women's Health Clinics", "Breast Cancer Diagnostic Centers", "General Hospitals"],
        futureScope: "Very secure. Mammograms are universally mandated global screening procedures for women over 40, guaranteeing massive annual volume.",
        jobDemandTrend: "Stable",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Moderate. Operating mobile mammography screening buses.",
        fieldWork: "Low to Moderate.",
        riskLevel: "Moderate (Radiation exposure and immense ergonomic positioning strain)",
        certifications: ["ARRT (M) equivalent"],
        internshipRequirements: "Extensive supervised clinical imaging of breasts under extreme quality-control standards.",
        roadmap: ["Radiographer", "Mammography Specialist", "Lead Mammographer"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Cardiovascular / Cath Lab Technologist",
        description: "Assist cardiologists simultaneously within the Cath Lab during heart attacks, physically scrubbed in to monitor vital signs and manage the fluoroscopic imaging while stents are placed in the heart.",
        summary: "High-stress surgical imaging techs working directly inside the Cath Lab during heart interventions.",
        skills: ["Hemodynamic Monitoring", "Scrubbing in surgically", "Real-time Fluoroscopy Angio imaging", "Extreme Crisis / Cardiac Arrest Management"],
        salaryRange: "India: ₹4L - ₹12L | Global: $80K - $120K",
        educationPath: "B.Sc Cardiovascular Technology or B.Sc Radiography",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Heart Institutes", "Vascular Surgery Centers", "Emergency Heart Attack/STEMI Hospitals"],
        futureScope: "Explosive. Heart disease is the number one killer globally, and immediate Cath Lab intervention is the only cure for a massive heart attack.",
        jobDemandTrend: "Very High",
        governmentJobs: "High. Every major hospital Cath Lab.",
        freelanceOpportunities: "Low. Entirely dependent on surgical suites.",
        fieldWork: "Low. Surgery room based.",
        riskLevel: "High (High radiation dosages physically next to the machine, high stress)",
        certifications: ["RCIS (Registered Cardiovascular Invasive Specialist) equivalent"],
        internshipRequirements: "Hundreds of hours literally standing next to cardiologists during live heart attacks.",
        roadmap: ["Cath Lab Tech", "Senior EP (Electrophysiology) Tech", "Cath Lab Manager"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Bone Densitometry Technologist (DEXA)",
        description: "Operate dual-energy X-ray absorptiometry (DEXA) scanners to instantly measure bone mineral density, primarily to diagnose osteoporosis in aging populations.",
        summary: "Specialists operating bone-density scanners to diagnose osteoporosis.",
        skills: ["DEXA Machine Operation", "Anatomical Tracking (Spine/Hip)", "Patient Data Entry", "Precision Positioning"],
        salaryRange: "India: ₹3L - ₹6L | Global: $55K - $80K",
        educationPath: "B.Sc Radiography / Diploma + Specialized DEXA Training",
        yearsOfStudy: "3 Years",
        industriesHiring: ["Rheumatology Clinics", "Women's Health Centers", "Endocrinology Clinics"],
        futureScope: "Stable but often a dual-role. As populations age, osteoporosis scanning is crucial, but these techs often cross-train in standard X-ray.",
        jobDemandTrend: "Stable (Often dual-specialty)",
        governmentJobs: "Low.",
        freelanceOpportunities: "Low.",
        fieldWork: "Low.",
        riskLevel: "Low (DEXA emits incredibly low amounts of radiation)",
        certifications: ["ARRT (BD) / ISCD Certification equivalent"],
        internshipRequirements: "Executing specific BMD scans on the spine and femur.",
        roadmap: ["Radiographer", "DEXA Specialist", "Imaging Center Coordinator"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Medical Physicist (Radiology/Oncology)",
        description: "The supreme authority on radiation in a hospital, calibrating multi-million dollar imaging and cancer radiation machines to ensure they emit the exact legal, safe, and lethal dosages required.",
        summary: "The physics masterminds responsible for calibrating extremely dangerous radiation equipment.",
        skills: ["High-level Quantum/Nuclear Physics", "Radiation QA / Calibration", "Mathematical Problem Solving", "Regulatory Law Comprehension"],
        salaryRange: "India: ₹10L - ₹25L | Global: $170K - $250K+",
        educationPath: "B.Sc Physics → M.Sc Medical Physics / Radiotherapy Physics",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Cancer Hospitals", "Large Diagnostic Mega-Centers", "University Labs", "Govt Atomic Energy Boards"],
        futureScope: "Incredibly high demand, low supply niche. It's illegal for any hospital to run radiation machines without a resident certified Medical Physicist.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "High. State cancer institutes and atomic energy regulatory boards.",
        freelanceOpportunities: "Maximum. Highly paid consultants performing monthly or annual safety audits across dozens of private clinics.",
        fieldWork: "Moderate. Traveling between hospital bunkers for machine calibrations.",
        riskLevel: "Low to Moderate",
        certifications: ["Board Certified Medical Physicist / AERB certification (India)"],
        internshipRequirements: "Grueling physics residency measuring actual radiation output behind lead walls.",
        roadmap: ["Junior Physicist", "Senior Medical Physicist", "Chief Radiation Safety Officer"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "PACS (Picture Archiving and Communication System) Administrator",
        description: "Cross completely into IT to manage and secure the massive digital server networks that instantly distribute gigabytes of high-res MRI and CT scans to doctors' monitors hospital-wide.",
        summary: "The specialized IT administrators managing the hospital's massive digital image storage network.",
        skills: ["DICOM/HL7 Standards", "Database / Server Administration", "Clinical Workflow Understanding", "Network Security (HIPAA)"],
        salaryRange: "India: ₹7L - ₹20L | Global: $90K - $140K",
        educationPath: "B.Sc Radiography / IT → Certification in PACS Administration",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Large Hospital IT Departments", "Teleradiology Corporations", "Diagnostic Chains"],
        futureScope: "Explosive. Scans have moved entirely from physical film to digital servers, creating a desperate need for radiographers who can also code and manage networks.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "High. PACS consulting and system setups.",
        fieldWork: "Low. Entirely computer/server-room based.",
        riskLevel: "Low",
        certifications: ["Certified Imaging Informatics Professional (CIIP) / PACS Certification"],
        internshipRequirements: "Transitioning from physical machine operation to the IT department.",
        roadmap: ["Radiographer", "PACS Administrator", "Director of Imaging Informatics", "Chief Information Officer"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Echocardiographer (Cardiac Sonographer)",
        description: "A highly specialized subset of ultrasound focused exclusively on the moving heart, tracking real-time blood flow, valve defects, and pumping pressure to prevent heart failure.",
        summary: "Sonographers strictly dedicated to taking real-time ultrasound videos of the beating heart.",
        skills: ["Cardiac Anatomy (TTE/TEE)", "Doppler Physics", "Rapid Identification of Cardiac Abnormalities", "Extreme Visual Focus"],
        salaryRange: "India: ₹5L - ₹14L | Global: $85K - $125K",
        educationPath: "B.Sc Echocardiography / B.Sc Cardiovascular Technology",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Cardiology Clinics", "Heart Attack ERs", "Pediatric Heart Hospitals"],
        futureScope: "Extremely high. Fast, non-invasive, and zero radiation. Every single patient presenting with chest pain requires an 'Echo'.",
        jobDemandTrend: "Very High",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum. Easily consulting across multiple cardiology clinics daily.",
        fieldWork: "Moderate. Highly mobile within the hospital.",
        riskLevel: "Low",
        certifications: ["Registered Diagnostic Cardiac Sonographer (RDCS) equivalent"],
        internshipRequirements: "Scanning hundreds of living hearts to master the complex angled views.",
        roadmap: ["Junior Echocardiographer", "Senior Cardiac Sonographer", "Lead of Non-Invasive Cardiology"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Veterinary Radiographer",
        description: "Apply standard and advanced medical imaging techniques (X-Ray, CT, Ultrasound) exclusively to animals—ranging from tiny clinic pets to horses or zoo wildlife—often requiring anesthesia.",
        summary: "Imaging professionals translating human X-ray and ultrasound techniques to animal anatomy.",
        skills: ["Quadruped/Avian Anatomy", "Animal Restraint / Safety", "Anesthesia Monitoring Assistance", "Fast Adjustment under pressure"],
        salaryRange: "India: ₹3.5L - ₹8L | Global: $55K - $85K",
        educationPath: "B.Sc Radiography → Specialization in Veterinary Imaging or Vet Tech Degree",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Specialized Veterinary Hospitals", "Equine (Horse) Rescue Centers", "Zoos"],
        futureScope: "Massive niche growth. Pet owners are demanding human-level diagnostics (like $2,000 dog MRIs) driving explosive growth in vet specialty centers.",
        jobDemandTrend: "High Growth (Niche)",
        governmentJobs: "Low. State wildlife or agricultural roles.",
        freelanceOpportunities: "Moderate. Mobile equine X-ray for horse farms.",
        fieldWork: "Moderate. Traveling to massive farms or zoos if needed.",
        riskLevel: "Moderate (Risk of severe injury from frightened or combative animals)",
        certifications: ["Specific Veterinary Imaging credentials"],
        internshipRequirements: "Clinical positioning of sedated and awake animals.",
        roadmap: ["Vet Tech", "Lead Vet Radiographer", "Director of Veterinary Imaging"]
    },
    {
        domain: "Medical",
        branch: "Radiology",
        title: "Fluoroscopy / Special Procedures Technologist",
        description: "Operate 'live, video X-ray' machines (fluoroscopy) assisting doctors during painful joint injections, swallowing studies, or complex gastrointestinal evaluations.",
        summary: "Technologists operating real-time moving X-rays to visualize swallowing or joint injections.",
        skills: ["Dynamic Real-Time Imaging", "Barium Swallowing Studies", "Sterile Field Maintenance", "Patient Instruction"],
        salaryRange: "India: ₹4L - ₹9L | Global: $70K - $95K",
        educationPath: "B.Sc Radiography + Fluoroscopy Experience",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Pain Management Clinics", "Gastroenterology Centers", "Hospitals"],
        futureScope: "Stable. Highly important in gastrointestinal medicine and chronic back pain management.",
        jobDemandTrend: "Stable",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Low. Heavily doctor-dependent.",
        fieldWork: "Low. Procedure room based.",
        riskLevel: "Moderate (High levels of sustained, scattered radiation during live feeds)",
        certifications: ["State Fluoroscopy Permits"],
        internshipRequirements: "Working alongside GI doctors viewing live digestive tracks.",
        roadmap: ["Radiographer", "Fluoroscopy Lead", "Special Procedures Coordinator"]
    }
];

const seedRadiology = async () => {
    try {
        await Career.deleteMany({ branch: "Radiology" });
        await Career.insertMany(radiologyProfessions);
        console.log('Radiology Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedRadiology();
