const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const familyLawProfessions = [
    {
        domain: "Law",
        branch: "Family Law",
        title: "Family Lawyer",
        description: "A generalist dealing with the legal aspects of domestic relationships. They handle a wide spectrum of cases including divorce, child custody, alimony, and domestic violence, acting as both litigators and advisors.",
        educationPath: "LLB",
        competitiveExams: ["CLAT", "State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Empathy & Emotional Intelligence", "Family Court Procedures", "Personal Law (Hindu/Muslim/Christian)", "Litigation Strategy"],
        salaryRange: "India: ₹4 LPA - ₹20 LPA | Global: $60,000 - $150,000 per year",
        roadmap: ["Junior Associate", "Independent Practitioner", "Senior Family Court Advocate", "Family Law Specialist"],
        courtPracticeOpportunities: "High volume of daily practice in specialized Family Courts and District Courts.",
        governmentJobs: "Appointed as legal counselors in state-run women’s commissions.",
        lawFirmOpportunities: "Extensive opportunities in boutique family law chambers.",
        mediationCounselingOpportunities: "High frequency. They often attempt to settle disputes before filing formal petitions.",
        workNature: "Courtroom Litigation, Client Counseling & Drafting Petitions.",
        futureScope: "Extremely stable. Unfortunately, as societal dynamics shift and divorce rates rise globally, the demand for family dispute resolution remains constantly high.",
        jobDemandTrend: "High and Constant Volume",
        summary: "The frontline legal defenders of domestic rights, navigating clients through the most emotionally turbulent periods of their lives."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Divorce Lawyer",
        description: "A hyper-specialized family lawyer focusing entirely on the dissolution of marriage. They aggressively negotiate alimony, division of marital assets, and separation agreements.",
        educationPath: "LLB -> Practice Focus in Matrimonial Law",
        competitiveExams: ["State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Asset Tracing", "Aggressive Negotiation", "Cross-Examination", "Alimony Calculation"],
        salaryRange: "India: ₹5 LPA - ₹30+ LPA | Global: $80,000 - $250,000+ per year",
        roadmap: ["Divorce Litigator", "High-Net-Worth Matrimonial Specialist", "Senior Counsel", "Partner - Private Client Practice"],
        courtPracticeOpportunities: "Daily appearances in Family Courts.",
        governmentJobs: "Minimal.",
        lawFirmOpportunities: "Highly lucrative practice areas in Tier-1 firms handling 'High-Net-Worth' (HNI) divorces.",
        mediationCounselingOpportunities: "Often engaged in intense out-of-court financial settlements.",
        workNature: "High-Stakes Financial Negotiation & Emotional Courtroom Litigation.",
        futureScope: "Highly lucrative, especially in HNI sectors where multi-million dollar business assets are tied to matrimonial disputes.",
        jobDemandTrend: "Very High Demand",
        summary: "The strategic negotiators and litigators who untangle the complex legal and financial webs of dissolved marriages."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Child Custody Lawyer",
        description: "Focuses exclusively on the legal battles surrounding the guardianship, visitation rights, and financial support of children post-divorce. Their absolute legal mandate is to argue for the 'best interests of the child'.",
        educationPath: "LLB",
        competitiveExams: ["LSAT / CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment", "Child Psychology Diplomas (Optional)"],
        skills: ["Guardian and Wards Act", "Child Psychology", "Cross-Examination of Experts", "Extreme Patience"],
        salaryRange: "India: ₹4 LPA - ₹18 LPA | Global: $70,000 - $160,000 per year",
        roadmap: ["Custody Advocate", "Senior Guardian Ad Litem", "Independent Child Rights Specialist", "Court Appointed Mediator"],
        courtPracticeOpportunities: "Dedicated practice before Family Court Judges.",
        governmentJobs: "Consultants for Child Welfare Committees (CWC).",
        lawFirmOpportunities: "Niche roles within broader family law boutiques.",
        mediationCounselingOpportunities: "Constantly mediating between hostile parents to prevent court-mandated emotional trauma to the child.",
        workNature: "Highly Sensitive Litigation, NGO Collaboration & Mediation.",
        futureScope: "Crucial and forever necessary. Courts mandate specialized legal representation to ensure children are protected during brutal matrimonial wars.",
        jobDemandTrend: "Stable",
        summary: "Fierce courtroom advocates who strictly protect the psychological and financial well-being of the most vulnerable victims of divorce."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Marriage & Matrimonial Lawyer",
        description: "Focuses on the legal architecture of getting married and staying married safely. They draft complex pre-nuptial agreements (where legal), register inter-faith marriages under the Special Marriage Act, and resolve immigration matrimonial issues.",
        educationPath: "LLB",
        competitiveExams: ["None specifically required"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Special Marriage Act", "Immigration Law (Spousal Visas)", "Pre-Nup Drafting", "Advisory"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $75,000 - $180,000 per year",
        roadmap: ["Matrimonial Consultant", "Senior Advisory Counsel", "Cross-Border Marriage Specialist", "Private Client Partner"],
        courtPracticeOpportunities: "Low. Mostly works with marriage registrars and embassies.",
        governmentJobs: "Appointed as official Marriage Officers or Registrars.",
        lawFirmOpportunities: "Hired by global immigration firms to handle complex spousal visas.",
        mediationCounselingOpportunities: "Counseling couples on the legal/financial realities before tying the knot.",
        workNature: "Desk Drafting, Registration Procedures & Preventive Advisory.",
        futureScope: "Growing globally. As international/inter-faith marriages and the desire to protect pre-marital assets increase, pre-litigation matrimonial advisory is booming.",
        jobDemandTrend: "Growing (Especially Pre-Nups globally)",
        summary: "The preventive legal advisors who structure marriages legally, ensuring smooth registrations and protecting assets before conflicts arise."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Adoption Lawyer",
        description: "Navigates the intensely strict bureaucratic and legal frameworks required to permanently adopt a child. They handle CARA (Central Adoption Resource Authority) regulations, surrogacy contracts, and international adoptions.",
        educationPath: "LLB",
        competitiveExams: ["State Entrance Exams"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Juvenile Justice Act", "CARA Guidelines", "International Hague Convention", "Extreme Detail Orientation"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $65,000 - $140,000 per year",
        roadmap: ["Adoption Counsel", "Surrogacy Law Specialist", "International Adoption Expert", "NGO Legal Head"],
        courtPracticeOpportunities: "Limited to obtaining final adoption decrees from District/Family Courts.",
        governmentJobs: "Legal officers within CARA or State Adoption Resource Agencies (SARA).",
        lawFirmOpportunities: "Boutique practices handling high-net-worth surrogacy and international adoptions.",
        mediationCounselingOpportunities: "Counseling prospective parents on the agonizingly slow legal realities of adoption.",
        workNature: "Heavy Bureaucratic Navigation, Desk Drafting & Agency Liaising.",
        futureScope: "Highly specialized. With the rise of assisted reproductive technology (IVF/Surrogacy) and changing family dynamics, the legal nuances of becoming a parent are highly complex.",
        jobDemandTrend: "Niche but Essential",
        summary: "The bureaucratic navigators who fulfill family dreams by legally guiding parents through the labyrinth of domestic and international adoption laws."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Domestic Violence Lawyer",
        description: "A hybrid criminal-family lawyer who protects victims of abuse. They urgently file for restraining orders, secure emergency maintenance, and initiate criminal proceedings under the Protection of Women from Domestic Violence Act.",
        educationPath: "LLB -> Criminal/Family Practice",
        competitiveExams: ["CLAT / AILET"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["High-Speed Injunctions", "Trauma-Informed Lawyering", "CrPC & PWDVA Procedures", "Rapid Crisis Management"],
        salaryRange: "India: ₹4 LPA - ₹18 LPA | Global: $60,000 - $130,000 per year",
        roadmap: ["Legal Aid Lawyer", "Independent Trial Advocate", "Senior Criminal-Family Counsel", "Activist / NGO Head"],
        courtPracticeOpportunities: "Daily high-stress appearances in Magistrate and Family Courts.",
        governmentJobs: "Appointed as Protection Officers by state governments.",
        lawFirmOpportunities: "Extensively handled by litigation chambers and women's rights NGOs.",
        mediationCounselingOpportunities: "Absolutely NONE. Mediation is strictly prohibited in cases of ongoing physical violence.",
        workNature: "Urgent Trial Law, Police Coordination & Crisis Intervention.",
        futureScope: "A relentless, noble necessity. Ensuring physical safety via the legal system is one of the most fundamental purposes of a functioning judiciary.",
        jobDemandTrend: "High Volume / Socially Critical",
        summary: "The absolute first line of legal defense, utilizing emergency court orders to physically and financially protect victims from abusive households."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Family Legal Advisor",
        description: "Operates as a 'General Practitioner' for all legal matters affecting a specific family over generations. They draft wills, advise on property buying, handle minor traffic disputes, and manage basic tax filings.",
        educationPath: "LLB",
        competitiveExams: ["State Entrance Exams"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Broad Generalist Knowledge", "Trust Building", "Succession Planning", "Real Estate Basics"],
        salaryRange: "India: ₹3 LPA - ₹15 LPA | Global: $50,000 - $110,000 per year",
        roadmap: ["General Practitioner", "Trusted Family Counsel", "Estate Planner", "Independent Chamber Owner"],
        courtPracticeOpportunities: "Occasional local civil court appearances.",
        governmentJobs: "Notaries or Oath Commissioners.",
        lawFirmOpportunities: "Running purely independent, highly localized legal chambers.",
        mediationCounselingOpportunities: "Constantly mediating minor disputes between family members to prevent formal lawsuits.",
        workNature: "Advisory, Basic Legal Drafting & Relationship Management.",
        futureScope: "Very stable in Tier-2 and Tier-3 cities. Families deeply value a trusted local lawyer who can be called at 2 AM for any legal emergency.",
        jobDemandTrend: "Stable & Locally Driven",
        summary: "The trusted neighborhood legal generalist, managing the day-to-day legal health and inter-generational property transfers of everyday families."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Family Court Advocate",
        description: "The traditional courtroom brawler of the family law system. They do not do corporate or criminal work; they spend their entire careers mastering the specific procedural quirks and judicial temperaments of local Family Courts.",
        educationPath: "LLB",
        competitiveExams: ["LSAT India / State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Vernacular Fluency", "Local Court Procedures", "Cross-Examination", "Rapid Pleadings"],
        salaryRange: "India: ₹3 LPA - ₹15+ LPA | Global: N/A (Highly Localized)",
        roadmap: ["Junior Court Advocate", "Independent Trial Lawyer", "Family Bar President", "Elevation to Family Judge"],
        courtPracticeOpportunities: "100% focused on physical presence in the Family Courts.",
        governmentJobs: "Stepping stone to becoming a Family Court Judge via state exams.",
        lawFirmOpportunities: "Running high-volume, independent litigation chambers.",
        mediationCounselingOpportunities: "Participates when mandated by the judge, but their primary skillset is litigation.",
        workNature: "Extreme High-Volume Courtroom Argumentation.",
        futureScope: "The absolute backbone of the domestic legal system. As long as family courts exist, advocates who know how to navigate their chaotic halls will be in demand.",
        jobDemandTrend: "High Volume",
        summary: "The grassroots litigator navigating the daily, chaotic grind of the local Family Court to secure maintenance and separation decrees."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Family Mediation Specialist",
        description: "A neutral third party, often with a psychology background, who facilitates out-of-court settlements for divorcing couples. They aggressively try to keep families out of the destructive, public, and expensive court system.",
        educationPath: "LLB + Masters in Psychology/Social Work",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Certified Mediator Training (40 Hours Mandatory in India)"],
        skills: ["Conflict De-escalation", "Neutrality", "Financial Compromise", "Trauma Counseling"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $130,000 per year",
        roadmap: ["Empanelled Mediator", "Senior Private Mediator", "Director of Mediation Center", "Policy Advisor on ADR"],
        courtPracticeOpportunities: "None. They actively exist to divert cases away from the courtroom.",
        governmentJobs: "Empanelled directly by the High Court or District Court Mediation Centers.",
        lawFirmOpportunities: "Extensive demand. Modern law firms prefer offering mediation as a premium service to HNI clients preferring privacy.",
        mediationCounselingOpportunities: "This is the absolute core definition of the profession.",
        workNature: "Intense Negotiation, Emotional Counseling & Drafting Settlement Agreements.",
        futureScope: "Exploding. Courts globally are heavily backlogged and now legally mandate mediation before a divorce trial can even begin.",
        jobDemandTrend: "Rapidly Growing",
        summary: "The legal peacemakers who utilize psychology and negotiation to settle bitter divorces behind closed doors, saving clients years of court trauma."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Child Rights Lawyer",
        description: "Focuses on the macro-legal protection of children against state and systemic failures. They handle cases regarding child labor, constitutional right to education (RTE), juvenile justice reform, and child trafficking.",
        educationPath: "LLB -> LLM in Human Rights",
        competitiveExams: ["CLAT / AILET"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["POCSO Act", "Juvenile Justice Act", "Constitutional Writs", "Activism"],
        salaryRange: "India: ₹3 LPA - ₹12 LPA | Global: $50,000 - $100,000 per year",
        roadmap: ["NGO Legal Officer", "Independent Rights Advocate", "Senior Policy Advisor", "UNICEF Consultant"],
        courtPracticeOpportunities: "Filing Public Interest Litigations (PILs) in High Courts and representing minors in Juvenile Justice Boards.",
        governmentJobs: "Roles in the National Commission for Protection of Child Rights (NCPCR).",
        lawFirmOpportunities: "Limited to pro-bono departments; dominated by NGOs (e.g., Bachpan Bachao Andolan).",
        mediationCounselingOpportunities: "Policy advocacy and counseling rescued minors.",
        workNature: "Activism, High Court Litigation & Policy Drafting.",
        futureScope: "A socially vital role. As laws around juvenile crime and digital child-exploitation (cyber-bullying/pornography) evolve, specialized advocates are critical.",
        jobDemandTrend: "Stable (NGO/State Driven)",
        summary: "A courtroom activist fighting systemic abuses to ensure the constitutional and human rights of the nation's children are enforced."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Family Law Researcher",
        description: "Works behind the scenes in academia or think-tanks, studying the sociological impact of family laws. They research how Uniform Civil Codes, changing alimony structures, or same-sex marriage legalization affect society.",
        educationPath: "LLB -> LLM in Family/Sociological Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Sociological Jurisprudence", "Data Synthesis", "Comparative Global Family Law", "Academic Publishing"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $100,000 per year",
        roadmap: ["Research Fellow", "Senior Policy Analyst", "Think-Tank Director", "Academic Author"],
        courtPracticeOpportunities: "None. Purely academic.",
        governmentJobs: "Research wings for the Law Commission of India when proposing new family legislation.",
        lawFirmOpportunities: "Consultants for firms writing massive appeals on unconstitutional personal laws.",
        mediationCounselingOpportunities: "N/A",
        workNature: "Pure Legal Research, Academic Writing & Policy Formulation.",
        futureScope: "Crucial for legislative reform. Family law is the most hotly debated political topic (e.g., UCC), and researchers provide the actual data politicians use to craft new laws.",
        jobDemandTrend: "Niche Academic",
        summary: "The intellectual backbone analyzing how personal laws impact society, providing the research that shapes future national legislation."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Family Law Professor",
        description: "Educates law students on the immensely complex web of religious personal laws, secular marriage acts, and constitutional family rights. They publish treatises that judges often cite during landmark rulings.",
        educationPath: "LLB -> LLM -> Ph.D. in Family Law",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Doctrinal Knowledge", "Pedagogy", "Religious Law Interpretation", "Debate & Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean of Law School"],
        courtPracticeOpportunities: "Occasionally appointed as Amicus Curiae by the Supreme Court in complex personal law cases.",
        governmentJobs: "Permanent faculty at National Law Universities.",
        lawFirmOpportunities: "Hired as expert consultants to interpret obscure, century-old religious texts during elite property battles.",
        mediationCounselingOpportunities: "Often act as highly respected, neutral mediators in major community disputes.",
        workNature: "Teaching, Mentoring, Academic Publishing.",
        futureScope: "Highly respected and secure. Understanding the collision of religion, constitution, and family is a mandatory foundational skill for every lawyer.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic authorities who teach the intricacies of religious and secular family laws to the next generation of advocates."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Guardianship Lawyer",
        description: "Specializes in legally assigning decision-making power over individuals who cannot care for themselves. This includes orphaned children, adults with severe mental disabilities, and elderly citizens suffering from dementia.",
        educationPath: "LLB",
        competitiveExams: ["State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Mental Healthcare Act", "Disability Law", "Compassionate Communication", "Court Petitioning"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $65,000 - $130,000 per year",
        roadmap: ["Guardianship Associate", "Senior Disability Rights Counsel", "Appointed Receiver", "Independent Consultant"],
        courtPracticeOpportunities: "Frequent filings in District Courts to obtain legal guardianship certificates.",
        governmentJobs: "Advising State Disability Commissions.",
        lawFirmOpportunities: "A core subset of 'Elder Law' and private wealth management boutiques.",
        mediationCounselingOpportunities: "Counseling overwhelmed families on the legal liabilities of taking over an adult's finances.",
        workNature: "Court Petitioning, Medical Board Liaising & Highly Sensitive Advisory.",
        futureScope: "A rapidly growing niche. With increasing life expectancies globally, the legal mechanism to manage the assets and healthcare of the incapacitated elderly is in massive demand.",
        jobDemandTrend: "Growing (Elder Law)",
        summary: "The compassionate legal defenders who ensure that the most legally vulnerable in society—the disabled and the elderly—are placed under safe, court-monitored protection."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Inheritance & Succession Lawyer",
        description: "Deals exclusively with what happens to wealth after death. They draft bulletproof wills, execute probate in court, and litigate bitter, multi-generational family wars over contested ancestral property.",
        educationPath: "LLB",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Indian Succession Act", "Hindu Succession Act", "Tax Mitigation", "Flawless Drafting"],
        salaryRange: "India: ₹6 LPA - ₹35+ LPA | Global: $80,000 - $250,000+ per year",
        roadmap: ["Probate Lawyer", "Estate Planning Specialist", "Senior Counsel - Succession", "Partner - Private Wealth"],
        courtPracticeOpportunities: "High volume of Probate and Testamentary cases in High Courts and District Courts.",
        governmentJobs: "Minimal.",
        lawFirmOpportunities: "Extremely lucrative roles in Tier-1 firms managing the estates of billionaires and royal families.",
        mediationCounselingOpportunities: "Aggressively mediates to prevent wealth from being frozen in courts for decades.",
        workNature: "Elite Drafting, Probate Litigation & Family Wealth Advisory.",
        futureScope: "As massive wealth transfers occur between the Boomer generation and Millennials, lawyers who can ensure this transfer happens without taxation or litigation are invaluable.",
        jobDemandTrend: "Very High Demand",
        summary: "The architects of generational wealth, drafting the legal documents that dictate exactly how family empires are divided after death."
    },
    {
        domain: "Law",
        branch: "Family Law",
        title: "Family Dispute Resolution Consultant",
        description: "A business-meets-family hybrid. They specialize exclusively in resolving conflicts within massive 'Family Businesses' (e.g., Ambani-style splits), ensuring the company survives the internal family feud without collapsing.",
        educationPath: "LLB -> MBA / LLM in Corporate Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Corporate Governance Certifications"],
        skills: ["Corporate Law", "Shareholder Agreements", "Family Dynamics", "High-Stakes Negotiation"],
        salaryRange: "India: ₹10 LPA - ₹50+ LPA | Global: $120,000 - $350,000+ per year",
        roadmap: ["Corporate/Family Associate", "Senior Governance Strategist", "Partner - Family Offices", "Chief Legal Strategy Officer"],
        courtPracticeOpportunities: "Fights in the NCLT (National Company Law Tribunal) rather than standard Family Courts.",
        governmentJobs: "None.",
        lawFirmOpportunities: "The absolute elite tier of corporate law firms specifically catering to 'Family Offices'.",
        mediationCounselingOpportunities: "The ultimate goal is to mediate privately to prevent the company's stock from crashing due to public family disputes.",
        workNature: "Corporate Governance Drafting, Boardroom Mediation & Wealth Restructuring.",
        futureScope: "Extremely lucrative. The majority of massive businesses globally (and especially in India) are family-owned. When the patriarch dies, these lawyers step in to legally separate the business without destroying it.",
        jobDemandTrend: "Elite / Corporate Niche",
        summary: "The ultimate boardroom diplomats, using corporate and family law to peacefully dissect multi-billion dollar family empires during highly toxic successions."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Family Law" });
        await Career.insertMany(familyLawProfessions);
        console.log('Family Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
