const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const dentistryProfessions = [
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "General Dentist",
        description: "Diagnose, treat, and manage overall oral healthcare needs including preventative education, cavity fillings, root canals, and basic extractions.",
        summary: "Primary care oral health providers managing routine dental checkups and treatments.",
        skills: ["Manual Dexterity", "Patient Communication", "Diagnostic Imaging (Reading X-rays)", "Local Anesthesia Delivery", "Time Management"],
        salaryRange: "India: ₹3L - ₹12L | Global: $120K - $180K",
        educationPath: "BDS (Bachelor of Dental Surgery) / DDS / DMD",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Private Dental Clinics", "Corporate Dental Chains", "Government Hospitals", "Military Dental Corps"],
        futureScope: "Extremely stable. General dentists are the frontline of oral health and there is a consistent, universal need for routine dental care.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "High. Primary health centers and state hospitals require dental surgeons.",
        freelanceOpportunities: "Maximum. Opening independent private dental clinics is highly viable and common.",
        fieldWork: "Low. Entirely clinic based.",
        riskLevel: "Low to Moderate (Exposure to blood-borne pathogens, severe back/neck ergonomic strain over a career)",
        certifications: ["State/National Dental Council Registration"],
        internshipRequirements: "One year mandatory rotatory clinical internship.",
        roadmap: ["Dental Intern", "Associate Dentist", "Senior Dental Surgeon", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Orthodontist",
        description: "Specialize in the diagnosis, prevention, and correction of misaligned teeth and jaws using braces, clear aligners (like Invisalign), and retainers.",
        summary: "Specialists who straighten teeth and correct bite misalignments using braces and aligners.",
        skills: ["Spatial Awareness", "Biomechanics of Tooth Movement", "Aesthetic Sensibility", "Patience (Long-term treatments)", "Precision"],
        salaryRange: "India: ₹6L - ₹20L+ | Global: $180K - $300K+",
        educationPath: "BDS → MDS (Orthodontics and Dentofacial Orthopedics)",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["Specialized Orthodontic Clinics", "Multi-Specialty Dental Centers", "Academic Institutions"],
        futureScope: "Highly lucrative. The focus on cosmetic appearance and the explosion of clear aligner technology has massively increased demand among adults.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate in specialized state dental colleges/hospitals.",
        freelanceOpportunities: "Maximum. Many work as visiting consultants across 10-15 different clinics.",
        fieldWork: "Low. Frequent travel between clinics if working as a consultant.",
        riskLevel: "Low",
        certifications: ["Board Certification in Orthodontics"],
        internshipRequirements: "Intensive 3-year clinical residency managing hundreds of wire/aligner cases.",
        roadmap: ["Orthodontic Resident", "Consultant Orthodontist", "Senior Specialist", "Orthodontic Center Director"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Oral and Maxillofacial Surgeon (OMFS)",
        description: "Perform complex surgeries on the mouth, jaw, face, and neck, including impacted wisdom teeth extractions, facial trauma reconstruction, jaw realignment, and oral cancer incisions.",
        summary: "Elite surgical specialists bridging dentistry and medicine to treat severe facial trauma and complex jaw surgeries.",
        skills: ["Surgical Precision", "Crisis Management", "Deep Anatomical Knowledge", "Physical Stamina", "Anesthesia Management"],
        salaryRange: "India: ₹10L - ₹30L+ | Global: $250K - $450K+",
        educationPath: "BDS → MDS (Oral and Maxillofacial Surgery) [Sometimes Dual Degree with MBBS/MD]",
        yearsOfStudy: "8 to 12 Years",
        industriesHiring: ["Trauma Centers", "Maxillofacial Hospitals", "Cancer Institutes", "Multi-specialty Dental Clinics"],
        futureScope: "Extremely critical and highly respected. Often required in emergency trauma cases (car accidents) making them indispensable in large hospitals.",
        jobDemandTrend: "Very High",
        governmentJobs: "High. Placed in casualty/trauma wings of major government hospitals.",
        freelanceOpportunities: "High. Visiting surgical consultants for complex extractions/implants in smaller clinics.",
        fieldWork: "Low. OT and clinic based.",
        riskLevel: "High (High medical liability, dealing with severe trauma and life-threatening emergencies)",
        certifications: ["OMFS Board Certification (Often requires medical trauma certifications)"],
        internshipRequirements: "Grueling hospital-based surgical residency, including ER rotations.",
        roadmap: ["OMFS Resident", "Consultant Maxillofacial Surgeon", "Chief of Maxillofacial Trauma"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Endodontist",
        description: "Specialize strictly in diagnosing and treating tooth pain and performing complex root canal therapies to save infected or severely damaged teeth.",
        summary: "Specialists focusing entirely on root canals and saving the inner dental pulp.",
        skills: ["Micro-surgical Precision", "Operating Microscope Proficiency", "Pain Management", "Patience", "Diagnostic Accuracy"],
        salaryRange: "India: ₹6L - ₹18L | Global: $180K - $280K",
        educationPath: "BDS → MDS (Conservative Dentistry & Endodontics)",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["Root Canal Specialty Clinics", "Corporate Dental Chains", "Academic Universities"],
        futureScope: "Extremely stable. People constantly prefer saving their natural teeth over extractions. Advanced rotary instruments make this highly profitable.",
        jobDemandTrend: "High",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Maximum. The most common visiting dental consultants in India, performing complex single-sitting root canals across multiple clinics.",
        fieldWork: "Low.",
        riskLevel: "Low (Very minor risk of instrument breakage inside canals)",
        certifications: ["Board Certification in Endodontics"],
        internshipRequirements: "3-year PG residency explicitly focused on the dental pulp.",
        roadmap: ["Endo Resident", "Consultant Endodontist", "Micro-Endodontic Specialist", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Prosthodontist",
        description: "Restore and replace missing or severely damaged teeth using crowns, bridges, dentures, and surgically placed dental implants to restore oral function and aesthetics.",
        summary: "The architects of the mouth, restoring massive tooth loss with implants, crowns, and dentures.",
        skills: ["Biomaterials Knowledge", "Aesthetic Vision", "Prosthetic Design/Lab Communication", "Surgical Implant Placement", "Attention to Detail"],
        salaryRange: "India: ₹6L - ₹20L | Global: $150K - $250K",
        educationPath: "BDS → MDS (Prosthodontics and Crown & Bridge)",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["Implant Centers", "Cosmetic Dentistry Clinics", "Geriatric Dental Centers"],
        futureScope: "Massive growth. As populations age, tooth loss is inevitable. Furthermore, implant dentistry is one of the highest-revenue procedures in the field.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "Moderate to High. Consulting for full-mouth rehabilitations.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["Prosthodontic Board Certification"],
        internshipRequirements: "Residency heavily focused on lab fabrication and implant surgeries.",
        roadmap: ["Resident", "Consultant Prosthodontist", "Implantology Specialist", "Director of Full-Mouth Rehab Center"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Periodontist",
        description: "Specialize in the prevention, diagnosis, and treatment of diseases affecting the gums and supporting bone structures, as well as placing dental implants.",
        summary: "Experts treating gum disease, bone loss, and performing soft-tissue (gum) surgeries.",
        skills: ["Gum Surgery Techniques", "Bone Grafting", "Micro-surgical Precision", "Deep Cleaning/Scaling", "Patient Education (Hygiene)"],
        salaryRange: "India: ₹5L - ₹15L | Global: $150K - $230K",
        educationPath: "BDS → MDS (Periodontology)",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["Periodontal Clinics", "Multi-Specialty Dental Hospitals", "Implantology Centers"],
        futureScope: "Growing steadily. Research increasingly links severe gum disease to systemic health issues (cardiovascular disease, diabetes), making periodontics vital.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Moderate.",
        freelanceOpportunities: "High. Visiting consultants for flap surgeries and bone grafts.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["Board Certification in Periodontology"],
        internshipRequirements: "Residency dealing heavily with chronic gum infections.",
        roadmap: ["Peri-Resident", "Consultant Periodontist", "Implant/Gum Surgery Specialist"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Pediatric Dentist (Pedodontist)",
        description: "Provide comprehensive dental care strictly to infants, children, and adolescents, managing their unique dental development and addressing dental anxiety.",
        summary: "Specialists in children's dentistry, focusing on behavior management and early preventative care.",
        skills: ["Child Psychology", "Behavior Management (Nitrous Oxide/Sedation)", "Patience", "Empathy", "Quick Operative Skills"],
        salaryRange: "India: ₹6L - ₹16L | Global: $160K - $240K",
        educationPath: "BDS → MDS (Pediatric and Preventive Dentistry)",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["Children's Dental Clinics", "Pediatric Hospitals", "Academic Institutions"],
        futureScope: "Highly lucrative. Parents are highly invested in their children's painless dental experiences. Early orthodontic intervention is also expanding.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate. School dental health programs.",
        freelanceOpportunities: "High. Exclusive pediatric private practices are exceptionally profitable.",
        fieldWork: "Low. Occasional school check-up camps.",
        riskLevel: "Low (Requires dealing with highly uncooperative/crying toddlers)",
        certifications: ["Board Certification in Pediatric Dentistry"],
        internshipRequirements: "Residency focused on interceptive orthodontics and pediatric sedation.",
        roadmap: ["Pedo Resident", "Consultant Pedodontist", "Director of Children's Dental Chain"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Oral Pathologist",
        description: "Investigate and diagnose diseases of the mouth, jaws, and face (like oral cancer) by examining tissue biopsies under a microscope.",
        summary: "The laboratory detectives of dentistry, reading biopsies to diagnose oral cancers and cysts.",
        skills: ["Microscopic Evaluation", "Histology", "Deep Pathological Knowledge", "Attention to Detail", "Diagnostic Accuracy"],
        salaryRange: "India: ₹4L - ₹12L | Global: $130K - $200K",
        educationPath: "BDS → MDS (Oral Pathology and Microbiology)",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["Diagnostic Laboratories", "Cancer Institutes", "Dental Universities"],
        futureScope: "Critical, particularly in regions (like India) with extremely high incidences of tobacco-related oral cancers.",
        jobDemandTrend: "Stable, Academic/Lab Focus",
        governmentJobs: "High in state cancer institutes and forensic departments.",
        freelanceOpportunities: "Moderate. Interpreting slides for multiple oral surgeons/clinics remotely or in a private lab.",
        fieldWork: "Low. Strictly laboratory and office based.",
        riskLevel: "Low (Handling hazardous biological/chemical stains)",
        certifications: ["Board Certification in Oral Pathology"],
        internshipRequirements: "Thousands of hours evaluating histopathology slides.",
        roadmap: ["Pathology Resident", "Consultant Oral Pathologist", "Head of Diagnostic Laboratory"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Public Health Dentist",
        description: "Focus on preventing dental diseases and promoting oral health on a massive population level through community programs, fluoridation policies, and epidemiological research.",
        summary: "Community-focused specialists working to improve oral health on a population scale rather than a clinical chair.",
        skills: ["Epidemiology", "Biostatistics", "Public Policy Design", "Community Organization", "Health Education"],
        salaryRange: "India: ₹4L - ₹10L | Global: $100K - $160K",
        educationPath: "BDS → MDS (Public Health Dentistry) or MPH",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["WHO/NGOs", "Government Health Ministries", "Academic Research Centers", "Community Clinics"],
        futureScope: "Crucial for national health metrics. Governments rely on these experts to allocate oral health funding and manage rural outreach.",
        jobDemandTrend: "Stable, Policy Driven",
        governmentJobs: "Maximum. The core of state and national oral health initiatives.",
        freelanceOpportunities: "Low. Institutional and policy-focused.",
        fieldWork: "Maximum. Designing and running massive rural or school dental camps.",
        riskLevel: "Low",
        certifications: ["Public Health Certifications"],
        internshipRequirements: "Extensive rural and community postings organizing health camps.",
        roadmap: ["Community Dentist", "Public Health Researcher", "Director of State Oral Health Dept"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Oral Medicine and Radiology Specialist",
        description: "Diagnose complex medical conditions affecting the mouth (ulcers, autoimmune oral lesions) and act as the experts in interpreting dental/facial X-rays, CBCT scans, and MRIs.",
        summary: "Diagnostic specialists using advanced imaging and medicine to identify complex oral diseases.",
        skills: ["Radiological Interpretation (CBCT/MRI)", "Medical History Correlation", "Pharmacotherapy", "Diagnostic Precision"],
        salaryRange: "India: ₹4L - ₹12L | Global: $120K - $180K",
        educationPath: "BDS → MDS (Oral Medicine and Radiology)",
        yearsOfStudy: "7.5 to 8.5 Years",
        industriesHiring: ["Diagnostic Centers", "Dental Colleges", "Multi-specialty Hospitals", "Cancer Centers"],
        futureScope: "With the rise of 3D CBCT scanning for implants, trained radiologists are in high demand to read complex bone structures.",
        jobDemandTrend: "Stable",
        governmentJobs: "Moderate. Academic and hospital diagnostic roles.",
        freelanceOpportunities: "High. Remote \"teleradiology\" reporting for multiple clinics.",
        fieldWork: "Low. Office/Scan-center based.",
        riskLevel: "Low (Radiation safety protocols are strictly enforced)",
        certifications: ["CBCT/Radiology specialized training"],
        internshipRequirements: "Extensive hours reading complex maxillofacial scans.",
        roadmap: ["Resident", "Consultant Maxillofacial Radiologist", "Diagnostic Center Owner"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Cosmetic / Aesthetic Dentist",
        description: "Focus entirely on improving the visual appearance of a patient's teeth, gums, and smile using veneers, teeth whitening, and complex smile-design treatments.",
        summary: "The artists of dentistry focusing strictly on creating perfect, aesthetic \"Hollywood\" smiles.",
        skills: ["Digital Smile Design (DSD)", "Aesthetic Perception", "Veneer Bonding Techniques", "Photography", "Sales/Communication"],
        salaryRange: "India: ₹8L - ₹30L+ | Global: $180K - $350K+",
        educationPath: "BDS → Advanced Fellowships/Certificates in Aesthetic Dentistry",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["High-end Premium Private Clinics", "Celebrity Dental Chains", "Self-Employed"],
        futureScope: "Extremely lucrative and booming globally driven by social media and aesthetic awareness.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "None. Strictly private sector.",
        freelanceOpportunities: "Maximum. Owning a premium, luxury aesthetic studio.",
        fieldWork: "Low.",
        riskLevel: "Low (Very high patient aesthetic expectations and minor legal liability if unsatisfied)",
        certifications: ["Fellowship from American Academy of Cosmetic Dentistry (AACD) or similar"],
        internshipRequirements: "Apprenticeship under master cosmetic dentists.",
        roadmap: ["Associate Dentist", "Cosmetic Specialist", "Lead Aesthetic Architect", "Luxury Studio Owner"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Implantologist",
        description: "Surgically place titanium implants into the jawbone and restore them with crowns, serving as the modern replacement for missing teeth.",
        summary: "Specialists dedicated entirely to placing and restoring dental implants.",
        skills: ["Bone Grafting", "Surgical Precision", "3D CBCT Planning", "Prosthetic Integration", "Infection Control"],
        salaryRange: "India: ₹10L - ₹35L+ | Global: $200K - $400K+",
        educationPath: "BDS → MDS (Prosthodontics/Periodontology/OMFS) OR Extensive 1-2 Year Implant Fellowships",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Implant Institutes", "Multi-Specialty Private Clinics", "Corporate Dental Chains"],
        futureScope: "The highest grossing daily procedure in modern dentistry. Fully replacing roots with implants is the global standard of care.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low to Moderate.",
        freelanceOpportunities: "Maximum. Highest paid visiting consultants, traveling placing implants across the city.",
        fieldWork: "Low.",
        riskLevel: "Moderate (Surgical risks, nerve proximity, implant failure liabilities)",
        certifications: ["Fellowship/Diplomate of International Congress of Oral Implantologists (ICOI)"],
        internshipRequirements: "Placing a strictly mandated minimum number of implants under surgical supervision.",
        roadmap: ["Implant Fellow", "Implantologist", "Senior Implant Surgeon", "Lecturer/Implant Trainer"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Geriatric Dentist",
        description: "Provide dental care explicitly to the elderly, managing complex oral health issues complicated by age, medically compromised statuses, and polypharmacy.",
        summary: "Specialists tailored to treat the complex medical and dental needs of the elderly population.",
        skills: ["Understanding Polypharmacy (drug interactions)", "Empathy", "Patience", "Prosthodontic Skills (Dentures)"],
        salaryRange: "India: ₹4L - ₹12L | Global: $120K - $180K",
        educationPath: "BDS → MDS / Fellowship in Geriatric Dentistry",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Nursing Homes", "Veterans Hospitals", "Specialized Geriatric Clinics", "Home-visit Dental Services"],
        futureScope: "Rapidly expanding. The global demographic shift towards an aging population guarantees a massive influx of elderly patients needing specialized care.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate. Roles in state elderly welfare/care facilities.",
        freelanceOpportunities: "High. Mobile dentistry (visiting nursing homes with portable dental units) is a massive niche.",
        fieldWork: "Moderate to High (If running a mobile dental unit).",
        riskLevel: "Low to Moderate (Treating medically fragile patients)",
        certifications: ["Special Care/Geriatric Dentistry Fellowships"],
        internshipRequirements: "Clinical rotations in nursing homes or specialized hospital wings.",
        roadmap: ["Dental Surgeon", "Geriatric Dental Specialist", "Mobile Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Forensic Odontologist",
        description: "Work with law enforcement to identify unknown victims through dental records and analyze bite marks in criminal investigations.",
        summary: "The crime-scene investigators of dentistry, using teeth to identify victims and perpetrators.",
        skills: ["Analytical Thinking", "Attention to Detail", "Legal/Courtroom Testimony Experience", "Radiographic Comparison", "Emotional Resilience"],
        salaryRange: "India: ₹4L - ₹10L | Global: $100K - $150K",
        educationPath: "BDS → Fellowship / Master's degree in Forensic Odontology",
        yearsOfStudy: "5 to 7 Years",
        industriesHiring: ["Government Forensic Laboratories", "Police/CBI Investigation units", "Dental Colleges (Academic)"],
        futureScope: "Niche but critically important. Essential for mass casualty identifications (plane crashes, natural disasters) globally.",
        jobDemandTrend: "Stable (Niche)",
        governmentJobs: "Maximum. Almost entirely a government or law enforcement sector role.",
        freelanceOpportunities: "Low. Occasionally hired as an independent expert witness in legal trials.",
        fieldWork: "Moderate. Visiting morgues, crime scenes, or courtrooms.",
        riskLevel: "Low (Physically safe, but extremely high emotional/psychological toll dealing with deceased victims)",
        certifications: ["Board Certified Forensic Odontologist"],
        internshipRequirements: "Working alongside medical examiners and pathologists.",
        roadmap: ["Dental Surgeon", "Forensic Odontology Fellow", "Chief Forensic Odontologist (State)"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Dental Hygienist",
        description: "Perform professional teeth cleaning (scaling), examine patients for signs of oral diseases like gingivitis, and provide preventative dental education.",
        summary: "Preventative care experts who perform professional teeth cleanings and oral health screenings.",
        skills: ["Ultrasonic Scaling", "Patient Comfort", "Preventative Education", "Manual Dexterity", "Stamina"],
        salaryRange: "India: ₹2L - ₹5L | Global: $70K - $100K",
        educationPath: "Diploma in Dental Hygiene or B.Sc in Dental Hygiene",
        yearsOfStudy: "2 to 3 Years",
        industriesHiring: ["Private Dental Clinics", "Corporate Dental Chains", "Schools"],
        futureScope: "Extremely high in Western countries where hygienists work completely independently in dental offices. Growing slowly but steadily in India.",
        jobDemandTrend: "High (Globally)",
        governmentJobs: "Low to Moderate.",
        freelanceOpportunities: "Moderate. Working part-time across various dental offices.",
        fieldWork: "Low. Entirely clinic based.",
        riskLevel: "Low (High risk of ergonomic back/neck/wrist strain)",
        certifications: ["State Dental Hygiene License"],
        internshipRequirements: "Clinical hours cleaning patients varying widely by program.",
        roadmap: ["Dental Hygiene Student", "Registered Dental Hygienist", "Lead Hygienist"]
    },
    {
        domain: "Medical",
        branch: "Dentistry",
        title: "Dental Researcher / Academician",
        description: "Conduct scientific research on new dental materials, stem-cell tooth regeneration, or oral disease pathways, while teaching dental students at universities.",
        summary: "The academic scientists researching the next generation of dental materials and teaching future dentists.",
        skills: ["Scientific Writing", "Laboratory Protocols", "Biomaterials Science", "Didactic Teaching", "Grant Acquisition"],
        salaryRange: "India: ₹5L - ₹15L | Global: $90K - $140K",
        educationPath: "BDS → MDS → Ph.D. in Dental Sciences / Biomaterials",
        yearsOfStudy: "8.5 to 11 Years",
        industriesHiring: ["Universities", "Dental Material Manufacturers (e.g., 3M, Dentsply)", "Government Research Institutes"],
        futureScope: "Essential. The advancement of dentistry relies entirely on these researchers inventing stronger composites, better implants, and tissue engineering.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Government universities and national medical research councils.",
        freelanceOpportunities: "Moderate. Consulting for huge dental manufacturing corporations on new product lines.",
        fieldWork: "Low. Academic campus and laboratory based.",
        riskLevel: "Low",
        certifications: ["Ph.D. / Peer-reviewed publications"],
        internshipRequirements: "Research fellowships.",
        roadmap: ["Assistant Professor", "Principal Investigator", "HOD", "Dean of Dental Sciences"]
    }
];

const seedDentistry = async () => {
    try {
        await Career.deleteMany({ branch: "Dentistry" });
        await Career.insertMany(dentistryProfessions);
        console.log('Dentistry Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedDentistry();
