const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const humanRightsLawProfessions = [
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Human Rights Lawyer",
        description: "The vanguard of fundamental freedoms. They litigate against the state and massive corporations to protect vulnerable populations from police brutality, illegal detentions, systemic discrimination, and state-sponsored oppression.",
        educationPath: "LLB -> LLM in Human Rights Law",
        additionalQualification: "Deep passion for activism and grassroots social work.",
        competitiveExams: ["State Law Entrances / CLAT"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Constitutional Writs (Habeas Corpus)", "International Covenants (ICCPR)", "Media Advocacy", "Grassroots Mobilization"],
        salaryRange: "India: ₹3 LPA - ₹15 LPA | Global: $60,000 - $130,000 per year",
        roadmap: ["Rights Activist", "Independent Human Rights Counsel", "NGO Legal Director", "Senior Constitutional Advocate"],
        governmentOpportunities: "Advising the National Human Rights Commission (NHRC) or State Legal Services Authorities.",
        ngoInternationalOrganizationOpportunities: "The absolute core of this profession—employed by Amnesty International, Human Rights Watch, and local civil-rights NGOs.",
        corporateOpportunities: "Virtually none. Their work is fundamentally adversarial to large corporations and the state.",
        workNature: "High-Risk Public Interest Litigation, Fact-Finding Missions & Activist Defense.",
        futureScope: "A critical, eternal requirement for any functioning democracy. As authoritarianism and systemic inequalities rise globally, fearless human rights lawyers are the last line of defense for the vulnerable.",
        jobDemandTrend: "Stable (Ideology Driven)",
        summary: "The fearless courtroom warriors dedicated entirely to protecting the oppressed from civil rights violations, systemic discrimination, and state violence."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Civil Liberties Lawyer",
        description: "Focuses intensely on preserving the core freedoms guaranteed by a democracy—specifically free speech, right to privacy, and the right to peaceful assembly. They frequently defend journalists, whistleblowers, and political dissidents.",
        educationPath: "LLB",
        additionalQualification: "Profound understanding of Constitutional Law and historical free-speech precedents.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Defamation Defense", "Digital Privacy Rights", "Anti-Terror Law Defense (UAPA/Sedition)", "Appellate Litigation"],
        salaryRange: "India: ₹4 LPA - ₹20 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Litigation Associate", "Defamation Specialist", "Director of Civil Liberties Union", "Senior Constitutional Lawyer"],
        governmentOpportunities: "Minimal; usually actively fighting the government's attempts to curb freedoms.",
        ngoInternationalOrganizationOpportunities: "Core roles in organizations like the ACLU (in the US) or the PUCL (in India).",
        corporateOpportunities: "Consulting for massive tech companies (like X or Meta) regarding global censorship compliance vs. free speech.",
        workNature: "High-Profile Defense Litigation, Constitutional Challenges & Media Strategy.",
        futureScope: "Extremely critical. In the digital age, state surveillance and corporate data-mining are erasing privacy. Civil liberties lawyers are desperately needed to legally map and protect these evaporating freedoms.",
        jobDemandTrend: "High Demand (Digital Rights focus)",
        summary: "The fierce defenders of democracy's absolute core—free speech, privacy, and the right to dissent against massive state or corporate pressure."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "International Human Rights Advocate",
        description: "Operates above domestic courts. They spend their careers documenting war crimes, genocides, and systemic torture, bringing massive international pressure and legal cases to platforms like the UN Human Rights Council or the ICC.",
        educationPath: "LLB -> LLM in Public International Law & Human Rights",
        additionalQualification: "Fluency in multiple UN languages (French, Arabic) is highly advantageous.",
        competitiveExams: ["Global Fellowships"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["International Humanitarian Law Diplomas"],
        skills: ["UN Treaty Bodies Navigation", "War Crimes Documentation", "Sovereign Immunity Piercing", "Global Diplomacy"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $180,000 per year",
        roadmap: ["International Legal Fellow", "UN Rapporteur Advisor", "Director of Global NGO", "International Tribunal Judge"],
        governmentOpportunities: "Advising the Ministry of External Affairs on international human rights treaty compliances.",
        ngoInternationalOrganizationOpportunities: "The absolute pinnacle. Highly coveted roles in the UN, Amnesty International Global HQ, and Geneva-based tribunals.",
        corporateOpportunities: "Zero.",
        workNature: "International Lobbying, Report Authoring & Trans-national Legal Advocacy.",
        futureScope: "A highly prestigious, incredibly difficult field to enter. They are the global watchdogs holding rogue states and dictators accountable on the world stage.",
        jobDemandTrend: "Niche but Globally Vital",
        summary: "The elite global advocates leveraging international treaties and the UN to fight war crimes, genocide, and trans-national human rights abuses."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Human Rights Legal Advisor",
        description: "A strategic consultant who advises both global NGOs and progressive corporations on how to align their operations with international human rights standards, ensuring their supply chains don't rely on forced labor or exploit indigenous lands.",
        educationPath: "LLB -> LLM in Business and Human Rights",
        additionalQualification: "Understanding of ESG (Environmental, Social, Governance) corporate frameworks.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Corporate Sustainability Certifications"],
        skills: ["Supply Chain Auditing", "UN Guiding Principles on Business", "ESG Compliance", "Corporate Mediation"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $85,000 - $160,000 per year",
        roadmap: ["Advisory Associate", "Senior Human Rights Auditor", "Director of ESG (Corporate)", "Global Consultant"],
        governmentOpportunities: "Advising trade ministries on ethical sourcing policies for national imports.",
        ngoInternationalOrganizationOpportunities: "Drafting the complex frameworks that NGOs use to rank and grade corporate human rights compliances.",
        corporateOpportunities: "Massive emerging demand. Multi-national corporations (Apple, Nike) desperately need these advisors to ensure their global factories aren't violating basic labor/human rights.",
        workNature: "Corporate Risk Auditing, Policy Drafting & Preventive Advisory.",
        futureScope: "Exploding growth. 'Business and Human Rights' is rapidly shifting from a moral suggestion to a massive legal requirement globally, forcing corporations to hire specialized human rights advisors.",
        jobDemandTrend: "Rapidly Emerging in Corporate Sectors",
        summary: "The strategic auditors bringing human rights into the boardroom, ensuring multi-billion dollar corporate supply chains are free of exploitation and legally compliant via ESG."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Refugee & Asylum Lawyer",
        description: "The last legal lifeline for people fleeing war, persecution, and climate collapse. They fight brutal, complex bureaucratic battles to legally secure safe harbor for refugees within deeply hostile border-control and immigration systems.",
        educationPath: "LLB -> Specialization in Immigration/Refugee Law",
        additionalQualification: "Deep empathy and trauma-informed interviewing skills.",
        competitiveExams: ["None specifically"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["UNHCR Certifications"],
        skills: ["1951 Refugee Convention", "Asylum Tribunal Advocacy", "Deportation Defense", "Trauma Evidence Gathering"],
        salaryRange: "India: ₹3 LPA - ₹12 LPA | Global: $50,000 - $120,000 per year",
        roadmap: ["Asylum Advocate", "Senior Immigration Counsel", "NGO Director (Refugees)", "Global Migration Policy Maker"],
        governmentOpportunities: "Working within state immigration departments to process incredibly complex asylum claims neutrally.",
        ngoInternationalOrganizationOpportunities: "Massive employment by the UNHCR and millions of local border-defense NGOs.",
        corporateOpportunities: "None. Strictly humanitarian work.",
        workNature: "High-Stress Bureaucratic Appeals, Deportation Stays & Client Counseling.",
        futureScope: "Tragically booming. As climate change and geopolitical instability create unprecedented waves of global refugees, the demand for lawyers to navigate their asylum claims is surging.",
        jobDemandTrend: "High Volume (Crisis Driven)",
        summary: "The legal lifelines for the displaced, fighting desperate courtroom battles to secure asylum and prevent the deportation of refugees back to warzones."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Human Rights Litigation Lawyer",
        description: "The heavily specialized trial lawyers who focus exclusively on civil lawsuits demanding massive financial compensation from the state or corporations for egregious human rights violations like false imprisonment or toxic poisoning.",
        educationPath: "LLB",
        additionalQualification: "Mastery of tort law and civil damages calculations.",
        competitiveExams: ["State Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Torts & Civil Damages", "Class-Action Structuring", "Aggressive Cross-Examination", "State Liability Navigation"],
        salaryRange: "India: ₹5 LPA - ₹25 LPA | Global: $80,000 - $180,000 per year",
        roadmap: ["Litigation Associate", "Independent Trial Lawyer", "Class Action Specialist", "Designated Senior Civil Counsel"],
        governmentOpportunities: "Defending the state against massive civil rights claims (Adversarial).",
        ngoInternationalOrganizationOpportunities: "Hired on retainer by NGOs to litigate massive compensation claims for victims.",
        corporateOpportunities: "Hired defensively by corporations facing massive human-rights related class-action lawsuits.",
        workNature: "Brutal Civil Trials, Evidence Discovery & Extracting Financial Settlements.",
        futureScope: "Extremely necessary. While activists seek policy change, these litigators use the threat of massive financial ruin to force the state and corporations to respect human rights.",
        jobDemandTrend: "High for Skilled Trial Lawyers",
        summary: "The aggressive civil litigators converting human rights violations into massive, punitive financial lawsuits against the state and abusive corporations."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "NGO Legal Counsel (Human Rights)",
        description: "The dedicated internal lawyers who actually run the massive human rights NGOs. They protect the organization's foreign funding (FCRA), defend activists from state retaliation, and manage the legal risks of organizing massive protests.",
        educationPath: "LLB",
        additionalQualification: "Deep understanding of non-profit corporate governance and protest laws.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Non-Profit Governance Diplomas"],
        skills: ["FCRA (Foreign Funding) Compliance", "Activist Bail Petitions", "Strategic Risk Management", "Non-Profit Strategy"],
        salaryRange: "India: ₹5 LPA - ₹18 LPA | Global: $70,000 - $130,000 per year",
        roadmap: ["Legal Officer", "Senior NGO Counsel", "General Counsel (Amnesty/Greenpeace)", "Global NGO Director"],
        governmentOpportunities: "None. Usually viewed hostilely by the government.",
        ngoInternationalOrganizationOpportunities: "The absolute backbone of every massive human rights organization.",
        corporateOpportunities: "None.",
        workNature: "Internal Compliance Auditing, Activist Protection & rapid Bail Petitions.",
        futureScope: "Essential for the survival of activism. NGOs are under unprecedented global attack via funding freezes and sedition laws; their internal counsel is the only thing keeping them legally alive.",
        jobDemandTrend: "Stable within Non-Profit Sector",
        summary: "The strategic legal operators keeping massive human rights NGOs alive, securing their funding and protecting their activists from government retaliation."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Social Justice Legal Consultant",
        description: "Independent experts hired to evaluate structural inequalities. They work with massive foundations (like Ford or Gates) to find out which marginalized communities need specialized legal aid pipelines, and they design the funding frameworks to build them.",
        educationPath: "LLB -> Masters in Social Work (MSW) or Public Policy",
        additionalQualification: "Deep, data-driven understanding of intersectional poverty and caste/race dynamics.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 Years",
        certifications: ["Policy Evaluation Certifications"],
        skills: ["Grant Writing & Structuring", "Impact Metrics Assessment", "Systemic Inequality Mapping", "Philanthropic Advisory"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $75,000 - $140,000 per year",
        roadmap: ["Consulting Associate", "Senior Impact Advisor", "Director of Philanthropic Grants", "Independent Foundation Consultant"],
        governmentOpportunities: "Advising the Ministry of Social Justice on the efficacy of state-sponsored legal aid programs.",
        ngoInternationalOrganizationOpportunities: "Consulting for massive global philanthropic foundations distributing billions in human rights grants.",
        corporateOpportunities: "Advising multi-nationals on incredibly massive CSR (Corporate Social Responsibility) impact funds.",
        workNature: "Data Analysis, Grant Structuring & Macro-Social Strategy.",
        futureScope: "Highly influential. Billions of dollars are poured into \"human rights\" annually; these consultants dictate precisely which grassroots legal clinics actually receive that life-saving funding.",
        jobDemandTrend: "Niche/Philanthropy Driven",
        summary: "The strategic architects directing billions of dollars in global philanthropic funding to the most effective, grassroots human rights legal initiatives."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Children's Human Rights Lawyer",
        description: "Fiercely specialized advocates dedicated to protecting the rights of minors. They battle child-labor syndicates, navigate brutal juvenile justice systems, and force governments to implement the Right to Education.",
        educationPath: "LLB -> Focus in Juvenile/Family/Human Rights Law",
        additionalQualification: "Trauma-informed child interviewing skills.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Child Psychology Basics (Highly Recommended)"],
        skills: ["Juvenile Justice Act", "POCSO (Protection of Children from Sexual Offences) Court Procedures", "RTE Implementation", "Trauma Advocacy"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $120,000 per year",
        roadmap: ["Child Rights Advocate", "POCSO Special Prosecutor", "NGO Legal Head (Child Welfare)", "Global UNICEF Advisor"],
        governmentOpportunities: "Operating within Child Welfare Committees (CWC) or as specialized POCSO prosecutors.",
        ngoInternationalOrganizationOpportunities: "Employed by massive dedicated NGOs like Save the Children, Bachpan Bachao Andolan, and UNICEF.",
        corporateOpportunities: "Minimal.",
        workNature: "Highly Sensitive Litigation, Rescuing Minors & Juvenile Tribunal Advocacy.",
        futureScope: "A deeply challenging, profoundly necessary calling. Securing justice for the absolutely most vulnerable class of humans requires specialized lawyers who can stomach devastating cases.",
        jobDemandTrend: "Stable / NGO Driven",
        summary: "The fiercely dedicated advocates utilizing specialized tribunals to rescue and legally protect children from exploitation, abuse, and systemic neglect."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Gender Rights Lawyer",
        description: "Focuses on shattering systemic barriers based on gender and sexual orientation. They litigate for equal pay, fight workplace sexual harassment, and run massive constitutional campaigns for LGBTQ+ marriage and adoption rights.",
        educationPath: "LLB",
        additionalQualification: "Profound understanding of intersectional feminism and queer legal theory.",
        competitiveExams: ["None specifically"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Constitutional Equality Writs", "POSH Act Enforcement", "Anti-Discrimination Litigation", "Legislative Lobbying"],
        salaryRange: "India: ₹5 LPA - ₹18 LPA | Global: $70,000 - $140,000 per year",
        roadmap: ["Gender Rights Advocate", "Senior Civil Rights Litigator", "NGO Vanguard Leader", "Constitutional Pioneer"],
        governmentOpportunities: "Advising the National Commission for Women or similar state-level equality boards.",
        ngoInternationalOrganizationOpportunities: "Leading legal strategy for organizations fighting for LGBTQ+ rights and reproductive freedoms globally.",
        corporateOpportunities: "Consulting with massive HR departments to completely rewrite massive corporate gender/diversity policies.",
        workNature: "Constitutional Advocacy, Media Campaigning & Equality Litigation.",
        futureScope: "A rapidly evolving, high-impact frontier. As societal norms dramatically shift regarding gender and identity, these lawyers are the ones forcing the archaic legal system to catch up.",
        jobDemandTrend: "High Impact / Growing",
        summary: "The progressive litigators utilizing the constitution to obliterate systemic legal discrimination based on gender, sexuality, and reproductive choices."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Human Rights Policy Analyst",
        description: "Operates deep within think-tanks and government corridors. They read horrifying reports of systemic abuse, synthesize the data, and draft the comprehensive new laws or treaties required to legally prevent the abuse from happening again.",
        educationPath: "LLB -> Masters in Public Policy (MPP) / Human Rights",
        additionalQualification: "Exceptional data-synthesis and long-form academic writing.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Legislative Drafting Fellowships"],
        skills: ["Macro-Social Data Analysis", "Whitepaper Authoring", "Bureaucratic Lobbying", "Treaty Architecture"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $75,000 - $140,000 per year",
        roadmap: ["Research Fellow", "Senior Policy Architect", "Think-Tank Director", "UN Policy Advisor"],
        governmentOpportunities: "The primary brains drafting comprehensive new acts (e.g., Transgender Persons Protection Act, new Disability laws) for the legislature.",
        ngoInternationalOrganizationOpportunities: "The intellectual backbone of global NGOs, providing the raw drafted legislation that lobbyists then push to politicians.",
        corporateOpportunities: "Zero.",
        workNature: "Pure Policy Research, Legislative Drafting & Think-Tank Strategy.",
        futureScope: "Extremely influential. Litigators win individual cases; policy analysts rewrite the entire legal code to protect millions simultaneously.",
        jobDemandTrend: "Stable within Policy Circles",
        summary: "The intellectual architects analyzing massive societal abuses to draft the comprehensive new national laws and treaties required to eradicate them."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Human Rights Law Researcher",
        description: "Dives into the darkest, most complex historical abuses of human rights. They track the evolution of genocide laws, caste-discrimination precedents, and sovereign immunity, providing the foundational legal ammunition for landmark constitutional battles.",
        educationPath: "LLB -> LLM in Human Rights",
        additionalQualification: "A voracious capability for reading complex, devastating historical documentation.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Historical Jurisprudence", "Precedent Mining", "Comparative International Law", "Academic Writing"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $100,000 per year",
        roadmap: ["Research Assistant", "Senior Fellow (Human Rights)", "Independent Scholar", "Global Academic Expert"],
        governmentOpportunities: "Serving as judicial clerks for Supreme Court judges presiding over massive civil/fundamental rights benches.",
        ngoInternationalOrganizationOpportunities: "Producing the devastatingly thorough legal research reports published annually by amnesty and Human Rights Watch.",
        corporateOpportunities: "None.",
        workNature: "Intense Academic Research, Chamber Briefing & Global Precedent Synthesis.",
        futureScope: "Essential for pushing constitutional boundaries. To argue that a new right exists (e.g., the Right to Privacy/Internet), a senior advocate fundamentally relies on the exhausting groundwork compiled by these researchers.",
        jobDemandTrend: "Stable within Academia/Think-Tanks",
        summary: "The academic pioneers unearthing profound historical precedents to assist senior advocates in radically expanding the constitutional definition of human rights."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Human Rights Law Professor",
        description: "Educates law students on the philosophy, agonizing history, and complex legal mechanisms of global civil rights, ensuring the next generation of corporate lawyers doesn't entirely lose its moral compass.",
        educationPath: "LLB -> LLM -> Ph.D. in Human Rights Law",
        additionalQualification: "Extensive publishing on civil liberties and constitutional abuses.",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Jurisprudential Theory", "Pedagogy", "Syllabus Modernization", "Academic Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean / Leading Human Rights Scholar"],
        governmentOpportunities: "Permanent faculty in National Law Universities or serving on specialized law commission advisory boards.",
        ngoInternationalOrganizationOpportunities: "Their academic papers are frequently adopted and funded by massive global rights organizations.",
        corporateOpportunities: "Zero.",
        workNature: "Teaching, Mentoring, and Producing Elite Academic Rights Theory.",
        futureScope: "Highly prestigious. They are responsible for instilling the critical concepts of constitutional morality and fundamental rights into the minds of future generations of judges and lawmakers.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The profound academic philosophers who ensure the agonizing history of human rights abuses is understood by the next generation of lawyers and judges."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "International Humanitarian Law Specialist",
        description: "Focuses exclusively on the incredibly grim 'Laws of War' (The Geneva Conventions). They advise military generals on legal targeting, investigate war crimes tribunals regarding chemical weapons, and manage POW (Prisoner of War) legalities.",
        educationPath: "LLB -> LLM in Armed Conflict / Humanitarian Law",
        additionalQualification: "Ability to remain completely neutral and objective while analyzing catastrophic violence.",
        competitiveExams: ["JAG (Judge Advocate General) Exams for military entry"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Red Cross / ICRC specialized training"],
        skills: ["Geneva Conventions Mastery", "War Crimes Tribunal Procedures", "Rules of Engagement Drafting", "Military Law"],
        salaryRange: "India: ₹8 LPA - ₹20 LPA | Global: $90,000 - $170,000 per year",
        roadmap: ["Humanitarian Legal Officer", "Military Legal Advisor", "ICRC Global Delegate", "War Crimes Prosecutor"],
        governmentOpportunities: "The absolute core of the Military/Army Legal branches (JAG), advising generals on the legality of airstrikes.",
        ngoInternationalOrganizationOpportunities: "Highly coveted delegate roles in the International Committee of the Red Cross (ICRC).",
        corporateOpportunities: "Guiding massive private military/defense contractors on weapons compliance.",
        workNature: "Military Advisory, Tribunal Prosecutions & Operating in Conflict Zones.",
        futureScope: "A highly elite, incredibly intense niche. As modern warfare shifts to drones and cyber-attacks, these lawyers must continually interpret how the Geneva Conventions apply to entirely new methods of killing.",
        jobDemandTrend: "Niche/Elite",
        summary: "The intense, highly specialized lawyers applying the Geneva Conventions to active warzones, advising the military and prosecuting catastrophic war crimes."
    },
    {
        domain: "Law",
        branch: "Human Rights Law",
        title: "Human Rights PIL Lawyer",
        description: "The absolute masters of Public Interest Litigation. Instead of taking one client, they file a single massive lawsuit on behalf of thousands of marginalized people (e.g., manual scavengers, bonded laborers) directly in the Supreme Court.",
        educationPath: "LLB -> Apprenticeship under Senior Constitutional Advocates",
        additionalQualification: "Exceptional media-management and narrative-building skills.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["PIL Drafting/Strategy", "Supreme Court Procedures", "Media/Public Relations", "Class-Action Architecting"],
        salaryRange: "India: ₹4 LPA - ₹30+ LPA | Global: $80,000 - $200,000+ per year",
        roadmap: ["PIL Junior Advocate", "Independent Rights Litigator", "NGO Vanguard Counsel", "Designated Senior Counsel"],
        governmentOpportunities: "Frequently appointed by the Supreme Court as 'Amicus Curiae' (Friend of the Court) to independently investigate massive tragedies.",
        ngoInternationalOrganizationOpportunities: "The absolute spearhead for any NGO wanting to instantly halt a massive, unconstitutional government action.",
        corporateOpportunities: "Fiercely adversarial to corporations.",
        workNature: "High-Profile Supreme Court Arguments, Media Briefings & Constitutional Showdowns.",
        futureScope: "The most famous tier of activism. When a single PIL lawyer successfully forces the Supreme Court to change a national policy, they alter the lives of millions overnight. Highly respected, high-risk work.",
        jobDemandTrend: "High Impact / Elite",
        summary: "The vanguard constitutional warriors who utilize the Supreme Court's Public Interest Litigation mechanisms to force massive, nation-wide policy changes overnight."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Human Rights Law" });
        await Career.insertMany(humanRightsLawProfessions);
        console.log('Human Rights Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
