const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const envLawProfessions = [
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Lawyer",
        description: "A specialized litigator and advisor handling cases related to pollution, natural resource management, and ecological damage. They use constitutional writs and statutory laws to protect the environment or defend corporations against environmental claims.",
        educationPath: "LLB -> LLM in Environmental Law",
        additionalQualification: "Understanding of Environmental Sciences is highly beneficial.",
        competitiveExams: ["CLAT", "State Law Entrances"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["National Green Tribunal (NGT) Procedures", "Environmental Protection Act mapping", "Scientific Data Interpretation", "Filing Public Interest Litigations (PILs)"],
        salaryRange: "India: ₹5 LPA - ₹25 LPA | Global: $70,000 - $180,000 per year",
        roadmap: ["Environmental Associate", "NGT Practitioner", "Senior Environmental Advocate", "Public Policy Advisor"],
        governmentOpportunities: "Empanelled by State Pollution Control Boards and the Ministry of Environment, Forest and Climate Change (MoEFCC).",
        ngoInternationalOrganizationOpportunities: "Massive demand in national/global environmental defense NGOs.",
        corporateOpportunities: "Hired by massive infrastructure and mining corporations to defend against environmental lawsuits.",
        workNature: "Tribunal Litigation (NGT/High Courts), Drafting PILs & Corporate Defense.",
        futureScope: "Extremely critical. As climate change accelerates and courts aggressively enforce ecological preservation, the demand for dedicated environmental litigators is surging.",
        jobDemandTrend: "High and Rising Rapidly",
        summary: "The courtroom eco-warriors and corporate defenders, utilizing specialized environmental tribunals to battle over the future of the planet's resources."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Compliance Lawyer",
        description: "Operates largely out of court, ensuring that massive corporations absolutely comply with complex environmental regulations before they build factories, launch mining operations, or dispose of chemical waste.",
        educationPath: "LLB -> PG Diploma in Environmental Law",
        additionalQualification: "Understanding of corporate sustainability (ESG) metrics.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["ISO 14001 (Environmental Management) Lead Auditor - Optional"],
        skills: ["Regulatory Auditing", "Hazardous Waste Management Rules", "Corporate Governance", "Liaising with Pollution Boards"],
        salaryRange: "India: ₹7 LPA - ₹25 LPA | Global: $80,000 - $190,000 per year",
        roadmap: ["Compliance Associate", "Senior Regulatory Counsel", "ESG Legal Director", "Chief Sustainability Officer"],
        governmentOpportunities: "Advising government PSUs on maintaining ecological compliance during massive public works.",
        ngoInternationalOrganizationOpportunities: "Consulting for global watchdogs monitoring corporate supply chains.",
        corporateOpportunities: "The bedrock of any manufacturing, chemical, or energy corporation. They are the ultimate internal regulators.",
        workNature: "Desk Auditing, Regulatory Filings & Preventive Corporate Advisory.",
        futureScope: "Phenomenal growth. Corporate 'ESG' (Environmental, Social, Governance) compliance is now globally mandated by investors. A strict compliance lawyer is a company's greatest shield against catastrophic fines.",
        jobDemandTrend: "Exploding Corporate Demand",
        summary: "The preventive internal regulators, ensuring multi-billion dollar corporations don't trigger massive environmental disasters or crippling regulatory fines."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Climate Change Law Specialist",
        description: "Focuses entirely on the macro-legalities of global warming. They handle carbon-credit trading architectures, advise on the Paris Agreement compliance, and litigate 'climate justice' cases demanding reparations for rising sea levels.",
        educationPath: "LLB -> LLM in Climate Change / Energy Law",
        additionalQualification: "Deep understanding of carbon markets and global climate treaties.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Climate Finance / Carbon Trading Certifications"],
        skills: ["UNFCCC Treaties", "Carbon Market Legal Structuring", "Geopolitical Forecasting", "Appellate Litigation"],
        salaryRange: "India: ₹8 LPA - ₹30 LPA | Global: $100,000 - $250,000 per year",
        roadmap: ["Climate Policy Associate", "Carbon Market Counsel", "Partner - Climate Law", "Global Climate Negotiator"],
        governmentOpportunities: "Advising the central government prior to COP (Conference of Parties) global summits.",
        ngoInternationalOrganizationOpportunities: "Roles in the UN Environment Programme (UNEP) and global climate defense funds.",
        corporateOpportunities: "Guiding massive energy conglomerates transitioning from fossil fuels to renewables.",
        workNature: "Global Treaty Parsing, Carbon Trading Contracts & High-Level Policy Advisory.",
        futureScope: "The absolute legal frontier. Climate change is the defining crisis of the century; specializing in the laws that attempts to mitigate it is incredibly prestigious and highly lucrative in the corporate sector.",
        jobDemandTrend: "Hyper-Niche / Rapidly Growing",
        summary: "The legal architects of the global energy transition, structuring the carbon markets and litigating the unprecedented impacts of global warming."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Litigation Lawyer",
        description: "The hardcore trial lawyers who only enter the picture once a massive environmental disaster occurs (e.g., oil spills, gas leaks, illegal deforestation). They fight brutal, multi-year court battles to secure billion-dollar damages.",
        educationPath: "LLB -> Tort / Environmental Litigation focus",
        additionalQualification: "Mass-tort and class-action litigation experience.",
        competitiveExams: ["CLAT / State Exams"],
        yearsOfStudy: "5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Environmental Torts (Strict/Absolute Liability)", "Class-Action Structuring", "Cross-Examining Scientists", "Injunctions"],
        salaryRange: "India: ₹8 LPA - ₹40+ LPA | Global: $120,000 - $350,000+ per year",
        roadmap: ["Litigation Associate", "NGT Specialist", "Partner - Environmental Disputes", "Designated Senior Counsel"],
        governmentOpportunities: "State-appointed special prosecutors for catastrophic ecological disasters.",
        ngoInternationalOrganizationOpportunities: "Massive reliance by local NGOs to fight giant corporations destroying local habitats.",
        corporateOpportunities: "Hired on massive retainers by the corporations causing the disaster to mitigate their damages.",
        workNature: "High-Stakes Courtroom Trials, Deposing Expert Witnesses & Managing Massive Evidence Exhibits.",
        futureScope: "Extremely secure. The financial liabilities in environmental disasters are staggering, requiring the absolute best litigators to either extract or block those payouts.",
        jobDemandTrend: "High for Elite Litigators",
        summary: "The heavy-hitting trial lawyers summoned for catastrophic environmental disasters, battling over multi-million dollar liabilities in specialized tribunals."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Wildlife Protection Lawyer",
        description: "Specializes entirely in the defense of animals, endangered species habitats, and prosecuting international poaching syndicates. They utilize the Wildlife Protection Act and CITES treaties to freeze illegal wildlife trade.",
        educationPath: "LLB -> Passion for Wildlife Conservation",
        additionalQualification: "Forestry or Wildlife Biology background is highly advantageous.",
        competitiveExams: ["None specific to the sub-field"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Animal Law Diplomas"],
        skills: ["Wildlife Protection Act Masterclass", "CITES Treaty Enforcement", "Forest Rights Act", "Anti-Poaching Operations Law"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $120,000 per year",
        roadmap: ["Wildlife Legal Volunteer", "NGO Legal Head", "Independent Forest Rights Advocate", "Global Wildlife Policy Maker"],
        governmentOpportunities: "Advising the National Tiger Conservation Authority (NTCA) or State Forest Departments.",
        ngoInternationalOrganizationOpportunities: "Employed by WWF, WTI, and highly localized forest-protection NGOs.",
        corporateOpportunities: "Minimal, mostly adversarial (fighting corporations encroaching on forest land).",
        workNature: "Trial Court Prosecutions (Poaching cases), High Court PILs & Field Investigations.",
        futureScope: "A highly passionate, mission-driven niche. As habitats shrink and wildlife crimes become highly organized global syndicates, specialized prosecutors are desperately needed.",
        jobDemandTrend: "NGO/Government Driven (Stable)",
        summary: "The legal defenders of the voiceless, utilizing fierce litigation to destroy poaching syndicates and block corporate bulldozers from primary forests."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Policy Legal Advisor",
        description: "Operates at the highest levels of government and think-tanks, reading incoming science reports and translating them into massive, nation-wide environmental regulations and parliamentary bills.",
        educationPath: "LLB -> Masters in Public Policy (MPP) / Environmental Law",
        additionalQualification: "Deep geopolitical and macroeconomic understanding.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Policy Fellowships"],
        skills: ["Legislative Drafting", "Macro-Ecological Synthesis", "Lobbying", "Stakeholder Negotiation"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $80,000 - $150,000 per year",
        roadmap: ["Policy Analyst", "Senior Legal Draftsman", "Director of Think-Tank", "Ministerial Advisor"],
        governmentOpportunities: "The core drafters of rules for the Ministry of Environment (MoEFCC).",
        ngoInternationalOrganizationOpportunities: "Drafting shadow policies and whitepapers for global environmental watchdogs.",
        corporateOpportunities: "Hired by industry bodies (like CII/FICCI) to negotiate softer environmental regulations with the government.",
        workNature: "Pure Legal Research, Bill Drafting & High-Level Bureaucratic Lobbying.",
        futureScope: "Extremely influential. Before an environmental lawyer can argue a law in court, a policy advisor must draft it. They are the true architects of ecological governance.",
        jobDemandTrend: "Stable within Policy Circles",
        summary: "The strategic architects translating urgent climate science into binding national legislation and corporate regulations."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Natural Resources Lawyer",
        description: "Focuses on the incredibly lucrative legalities of extracting the earth's resources. They handle the massive leasing contracts, indigenous land rights, and environmental clearances required for mining, oil drilling, and water extraction.",
        educationPath: "LLB -> LLM in Energy/Natural Resources Law",
        additionalQualification: "Understanding of geology and extractive engineering timelines.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Energy Law Diplomas"],
        skills: ["Mines & Minerals Act", "Land Acquisition Strategy", "Indigenous Rights Laws", "Massive Contract Structuring"],
        salaryRange: "India: ₹10 LPA - ₹40 LPA | Global: $120,000 - $300,000 per year",
        roadmap: ["Resources Associate", "Senior Leasing Counsel", "Partner - Energy & Mining", "Chief Legal Officer (Mining Corp)"],
        governmentOpportunities: "Ministry of Mines, Ministry of Petroleum & Natural Gas.",
        ngoInternationalOrganizationOpportunities: "Usually works against NGOs, though some specialize in helping indigenous tribes negotiate better mining royalties.",
        corporateOpportunities: "Extremely high demand in massive extractive conglomerates (Vedanta, Coal India, Exxon).",
        workNature: "Mega-Lease Negotiation, Bureaucratic Clearances & Resource Arbitration.",
        futureScope: "Highly lucrative. As critical minerals (Lithium, Cobalt) become the new oil for electric vehicles, securing the legal rights to mine them is a multi-billion dollar priority.",
        jobDemandTrend: "Very High Corporate Demand",
        summary: "The highly-paid legal engineers who orchestrate the massive contracts allowing corporations to legally extract multi-billion dollar resources from the earth."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Legal Consultant",
        description: "Freelance or boutique firm experts who advise massive infrastructure projects (dams, highways, smart cities) on how to navigate the absolute maze of local and national environmental laws without getting sued and halted.",
        educationPath: "LLB -> LLM with extensive field experience",
        additionalQualification: "Exceptional networking with state pollution control boards.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Environmental Auditing Certifications"],
        skills: ["Clearance Navigation", "Strategic Bureaucracy Maneuvering", "Project Finance Intersections", "Risk Forecasting"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $180,000 per year",
        roadmap: ["Consulting Associate", "Senior Environmental Strategist", "Of Counsel to Tier-1 Firms", "Independent Boutique Owner"],
        governmentOpportunities: "Hired as third-party consultants for massive state-run infrastructure projects (NHAI).",
        ngoInternationalOrganizationOpportunities: "Providing expert opinions on the legality of controversial dams/projects.",
        corporateOpportunities: "Massive reliance by real estate developers and infrastructure giants.",
        workNature: "Strategic Advisory, Risk Auditing & Bureaucratic Liaising.",
        futureScope: "A highly profitable problem-solving role. Time is money in construction; these consultants prevent $100M infrastructure projects from being frozen by the NGT for years.",
        jobDemandTrend: "Stable / Highly Lucrative locally",
        summary: "The strategic navigators hired to guide multi-million dollar infrastructure projects safely through the lethal minefield of environmental regulations."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Impact Assessment (EIA) Legal Expert",
        description: "A hyper-niche role. They review the massive scientific 'EIA Reports' required before any major factory or dam is built, ensuring the science strictly matches the legal requirements, or launching lawsuits to prove the report was falsified.",
        educationPath: "B.Sc (Environmental Science) -> LLB",
        additionalQualification: "Deep capability to read and tear apart complex scientific environmental data.",
        competitiveExams: ["None specifically"],
        yearsOfStudy: "6 to 7 Years",
        certifications: ["EIA Training / Certification"],
        skills: ["EIA Notification Rules", "Scientific Data Cross-Examination", "Administrative Law", "Flawless Attention to Detail"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $80,000 - $150,000 per year",
        roadmap: ["EIA Reviewer", "Senior Compliance Authority", "EIA Litigation Specialist", "Expert Tribunal Member"],
        governmentOpportunities: "Serving on the state Expert Appraisal Committees (EAC) that grant or deny environmental clearances.",
        ngoInternationalOrganizationOpportunities: "Hired by NGOs specifically to find legal flaws in corporate EIA reports to stop controversial projects.",
        corporateOpportunities: "Hired by corporations to bulletproof their EIA reports before government submission.",
        workNature: "Deep Scientific-Legal Auditing & Administrative Tribunal Arguments.",
        futureScope: "Critical bottleneck role. The EIA is the single most important document determining if a project lives or dies; controlling its legal validity is immense power.",
        jobDemandTrend: "Niche but Highly Powerful",
        summary: "The scientific-legal hybrids who inspect the foundational ecological reports of massive projects, possessing the power to greenlight or destroy them."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Pollution Control Law Specialist",
        description: "Focuses entirely on the granular regulations of air, water, and noise pollution. They deal directly with factory closures, toxic effluent discharge limits, and negotiating massive fines imposed by Pollution Control Boards.",
        educationPath: "LLB",
        additionalQualification: "Understanding of basic chemical engineering/effluent treatment.",
        competitiveExams: ["State Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Air/Water Act Mastery", "Factory Closure Stay Orders", "Effluent Standard Navigation", "Negotiating with Bureaucracy"],
        salaryRange: "India: ₹5 LPA - ₹18 LPA | Global: $70,000 - $140,000 per year",
        roadmap: ["Pollution Litigator", "Corporate Compliance Officer", "Senior NGT Advocate", "Pollution Board Chairperson"],
        governmentOpportunities: "The absolute backbone legal staff of State and Central Pollution Control Boards.",
        ngoInternationalOrganizationOpportunities: "Filing cases against chronic industrial polluters.",
        corporateOpportunities: "Hired by heavy industries (Textiles, Chemicals, Tanneries) to fight closure notices.",
        workNature: "Rapid Injunction Filings, Factory Audits & High Court Writ Petitions.",
        futureScope: "Extremely high volume. Every single factory in the country requires a 'Consent to Operate' from pollution boards; managing this and fighting arbitrary closures is a permanent localized industry.",
        jobDemandTrend: "High Volume / Geographically Broad",
        summary: "The front-line negotiators and litigators fighting daily, highly localized battles over factory pollution limits and toxic waste discharge."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Law Researcher",
        description: "Acts as the intellectual vanguard, synthesizing decades of ecological jurisprudence, tracking global NGT/Supreme Court precedents, and providing the bedrock research required to win 'unicorn' environmental cases.",
        educationPath: "LLB -> LLM in Environmental Law",
        additionalQualification: "Passion for deep ecology and academic writing.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Precedent Synthesis", "Global Ecological Jurisprudence", "Speed Reading", "Academic Writing"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $100,000 per year",
        roadmap: ["Research Assistant", "Senior Ecological Fellow", "Think-Tank Director", "Global Environmental Scholar"],
        governmentOpportunities: "Clerking for National Green Tribunal (NGT) Judges.",
        ngoInternationalOrganizationOpportunities: "The primary engine generating the research for massive NGO PILs.",
        corporateOpportunities: "Consultant roles identifying future regulatory trends.",
        workNature: "Pure Legal Research, Academic Drafting & Chamber Briefing.",
        futureScope: "Essential for pushing the boundaries of the law. Concepts like granting \"legal personhood\" to rivers or mountains start as research papers before becoming binding Supreme Court laws.",
        jobDemandTrend: "Stable within Academia/Think-Tanks",
        summary: "The intellectual researchers unearthing the profound precdents that allow senior advocates to radically expand the legal definition of environmental protection."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental Law Professor",
        description: "Dedicated academic scholars advancing the highly complex theory of environmental jurisprudence. They teach aspiring lawyers about sustainable development, intergenerational equity, and the 'polluter pays' principle.",
        educationPath: "LLB -> LLM -> Ph.D. in Environmental Law",
        additionalQualification: "Extensive peer-reviewed publications.",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Pedagogy", "Jurisprudential Theory", "Doctrinal Analysis", "Academic Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean / Leading Author"],
        governmentOpportunities: "Serving on specialized environmental reform committees (e.g., TSR Subramanian Committee).",
        ngoInternationalOrganizationOpportunities: "Frequently publish research funded by the UN or massive global foundations.",
        corporateOpportunities: "Hired as independent expert witnesses regarding complex ecological-legal theories during massive trials.",
        workNature: "Teaching, Mentoring & Elite Academic Publishing.",
        futureScope: "Highly respected. Environmental Law is rapidly moving from a niche elective to a mandatory core subject, sharply increasing the demand for elite professors globally.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic authorities defining the philosophical and legal frameworks of ecological survival for the next generation of lawyers."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "International Environmental Law Lawyer",
        description: "Operates on a planetary scale. They navigate the deeply complex treaties dealing with international waters, transboundary air pollution, global hazardous waste dumping, and Antarctic resource protection.",
        educationPath: "LLB -> LLM in Public International Law (Focus on Environment)",
        additionalQualification: "Multilingual capabilities highly preferred.",
        competitiveExams: ["Global Fellowships (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Treaty Law Diplomas"],
        skills: ["UN Convention Parsing", "Customary International Law", "Cross-Border Arbitration", "Diplomacy"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $200,000 per year",
        roadmap: ["International Associate", "Global Treaty Counsel", "UN Legal Delegate", "Partner - Global Disputes"],
        governmentOpportunities: "Advising the Ministry of External Affairs on international water-sharing treaties (e.g., Indus Water Treaty).",
        ngoInternationalOrganizationOpportunities: "Highest echelon roles within the UN, ICJ, or Greenpeace International.",
        corporateOpportunities: "Advising global shipping lines and multi-nationals on cross-border toxic waste transport (Basel Convention).",
        workNature: "High-Level Treaty Interpretation, International Tribunal Arbitration & Sovereignty Advisory.",
        futureScope: "An elite, highly diplomatic tier of environmental law. As resources become scarce, wars over international rivers and oceanic zones will increasingly be fought by these lawyers.",
        jobDemandTrend: "Niche/Elite",
        summary: "The global legal diplomats managing the treaties and disputes that dictate the environmental survival of the entire planet."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Environmental NGO Legal Advisor",
        description: "The dedicated in-house counsel and strategic director for massive environmental non-profits. They manage the NGO's legal risks, draft funding compliance, and orchestrate massive, coordinated public interest litigations nationwide.",
        educationPath: "LLB -> Passion for Activism",
        additionalQualification: "Understanding of FCRA (Foreign Contribution Regulation Act) for NGO funding.",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Non-Profit Management (Optional)"],
        skills: ["PIL Strategy", "NGO Compliance (FCRA)", "Activist Protection", "Media Coordination"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $120,000 per year",
        roadmap: ["Legal Officer", "Director of Litigation Strategy", "General Counsel (NGO)", "Global NGO President"],
        governmentOpportunities: "Highly adversarial to the government; frequently sues state entities for ecological delays.",
        ngoInternationalOrganizationOpportunities: "This is the absolute core of the profession. Roles in Amnesty, Greenpeace, Sierra Club.",
        corporateOpportunities: "Zero. Purely a non-profit/activism driven role.",
        workNature: "Activism Coordination, PIL Drafting & NGO Risk Auditing.",
        futureScope: "A highly passionate, mission-driven role. NGOs are the primary challengers to corporate environmental destruction; their leading lawyers are essentially national heroes.",
        jobDemandTrend: "Stable (NGO Driven)",
        summary: "The strategic legal brains running the nation's most aggressive eco-NGOs, coordinating massive lawsuits while protecting the activists from retaliation."
    },
    {
        domain: "Law",
        branch: "Environmental Law",
        title: "Sustainable Development Legal Consultant",
        description: "A forward-looking hybrid advisor. They help municipalities, smart-cities, and massive real-estate conglomerates draft the legal frameworks required to build fully 'green', net-zero, and legally compliant sustainable ecosystems.",
        educationPath: "LLB -> Masters in Urban Planning/Sustainability",
        additionalQualification: "Deep understanding of green building codes (LEED/GRIHA) and renewable energy integration.",
        competitiveExams: ["None"],
        yearsOfStudy: "5 Years",
        certifications: ["Green Building/Sustainability Credentials"],
        skills: ["Urban Planning Law", "Renewable Energy Subsidies", "Municipal Zoning codes", "Future-casting"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $180,000 per year",
        roadmap: ["Sustainability Associate", "Green Infrastructure Counsel", "Smart-City Legal Director", "Global ESG Consultant"],
        governmentOpportunities: "Advising NITI Aayog or Urban Development Ministries on 'Smart City' legal grids.",
        ngoInternationalOrganizationOpportunities: "Consulting for the World Bank on funding sustainable urban projects in developing nations.",
        corporateOpportunities: "Massive demand among Tier-1 Real Estate conglomerates transitioning to sustainable infrastructure to attract foreign ESG funding.",
        workNature: "Urban Policy Consulting, Green Infrastructure Contract Drafting & Subsidy Navigation.",
        futureScope: "The architects of tomorrow's legal cities. As urbanization explodes, building cities that don't destroy the environment requires entirely new legal frameworks and visionary lawyers to draft them.",
        jobDemandTrend: "Rapidly Emerging / High Potential",
        summary: "The visionary lawyers merging urban planning, renewable energy, and corporate law to legally build the sustainable mega-cities of the future."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Environmental Law" });
        await Career.insertMany(envLawProfessions);
        console.log('Environmental Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
