const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const ipLawProfessions = [
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Intellectual Property (IP) Lawyer",
        description: "A comprehensive legal expert who protects intangible creations of the human intellect. They advise clients on how to legally secure, manage, and enforce their patents, trademarks, copyrights, and trade secrets globally.",
        educationPath: "LLB -> LLM in Intellectual Property Law",
        additionalQualification: "Science/Tech background highly preferred but not mandatory for general IP.",
        competitiveExams: ["CLAT (PG)", "AILET (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["IP Strategy", "Legal Drafting", "Cross-Border IP Treaties", "Technology Law"],
        salaryRange: "India: ₹6 LPA - ₹30+ LPA | Global: $80,000 - $250,000+ per year",
        roadmap: ["IP Associate", "Senior IP Counsel", "Partner - IP Practice", "Head of Global IP Strategy"],
        governmentJobs: "Empanelled as prosecutors for the Trade Marks Registry or Patent Office.",
        corporateOpportunities: "Massive demand in every MNC's legal department to protect global brand assets.",
        lawFirmOpportunities: "Extensively hired by Tier-1 corporate law firms and dedicated IP boutiques.",
        workNature: "Advisory, Portfolio Management, Licensing & IP Enforcement.",
        futureScope: "Explosive growth. As the global economy shifts entirely towards digital assets, software, and branding, protecting these intangibles is the highest corporate priority.",
        jobDemandTrend: "High and Constant",
        summary: "The ultimate protectors of human innovation, safeguarding the billion-dollar ideas and brands that drive the modern economy."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Patent Attorney",
        description: "A highly specialized lawyer who bridges deep science and complex law. They evaluate new scientific inventions, draft incredibly complex patent specifications, and fight to secure exclusive patent rights for inventors.",
        educationPath: "B.Sc/B.Tech/Ph.D. in STEM -> LLB",
        additionalQualification: "Patent Agent Examination (Registered Patent Agent).",
        competitiveExams: ["Indian Patent Agent Examination", "CLAT (For LLB)"],
        yearsOfStudy: "7 to 8 Years (STEM Degree + Law Degree)",
        certifications: ["Registered Patent Agent", "Bar Council Enrollment"],
        skills: ["Scientific Literacy", "Patent Claim Drafting", "Prior Art Searching", "Complex Prosecution"],
        salaryRange: "India: ₹8 LPA - ₹40+ LPA | Global: $120,000 - $350,000+ per year",
        roadmap: ["Patent Associate", "Registered Patent Attorney", "Partner - Patent Prosecution", "Chief IP Officer"],
        governmentJobs: "Roles as Examiners of Patents and Designs (Ministry of Commerce).",
        corporateOpportunities: "The absolute backbone of Pharmaceutical, Biotech, and Hardware Tech companies.",
        lawFirmOpportunities: "The highest-paid niche within elite IP boutique law firms.",
        workNature: "Intense Scientific Analysis, Technical Drafting & Patent Office Prosecution.",
        futureScope: "Extremely lucrative and heavily insulated from AI replacement due to the necessity of combining cutting-edge scientific understanding with high-level legal strategy.",
        jobDemandTrend: "Very High (Severe shortage of STEM-qualified lawyers)",
        summary: "A rare hybrid of scientist and lawyer, holding a legal monopoly over securing the rights to the world's most advanced technological breakthroughs."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Trademark Attorney",
        description: "Specializes exclusively in the protection of brand identities—logos, names, slogans, and trade dress. They ensure corporations do not infringe on existing brands and aggressively prosecute trademark hijackers.",
        educationPath: "LLB",
        additionalQualification: "Registered Trademark Agent (Optional if Bar Enrolled).",
        competitiveExams: ["CLAT / State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Brand Strategy", "Trademark Prosecution", "Cease and Desist Drafting", "Consumer Psychology"],
        salaryRange: "India: ₹5 LPA - ₹20 LPA | Global: $70,000 - $180,000 per year",
        roadmap: ["Trademark Associate", "Managing Attorney", "Partner - Trademarks", "Global Brand Protection Head"],
        governmentJobs: "Examiners of Trade Marks (Intellectual Property Office).",
        corporateOpportunities: "Employed by massive FMCG, Fashion, and Tech giants to manage global portfolios.",
        lawFirmOpportunities: "High volume practice in both boutique and Tier-1 general corporate firms.",
        workNature: "Search Clearances, Registry Prosecution & Opposition Hearings.",
        futureScope: "Perpetually stable. Every single new company, app, or physical product globally requires instant, bulletproof trademark protection.",
        jobDemandTrend: "Stable and High Volume",
        summary: "The legal guardians of corporate identity, ensuring that multi-billion dollar brands are never stolen, diluted, or counterfeited."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Copyright Lawyer",
        description: "Focuses on protecting original artistic, literary, and musical creations. They negotiate publishing deals, stop media piracy, and handle complex software code copyright claims.",
        educationPath: "LLB -> LLM in IP Law (Optional)",
        additionalQualification: "None mandatory.",
        competitiveExams: ["CLAT / AILET"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Software Copyrighting", "Media Licensing", "Piracy Enforcement", "Fair Use Analysis"],
        salaryRange: "India: ₹5 LPA - ₹18 LPA | Global: $70,000 - $160,000 per year",
        roadmap: ["Media/IP Associate", "Senior Licensing Counsel", "Partner - Copyrights", "Head of Media Legal Affairs"],
        governmentJobs: "Copyright Board/Office roles and advising the Ministry of I&B.",
        corporateOpportunities: "Massive demand in Software Companies, Record Labels, and Publishing Houses.",
        lawFirmOpportunities: "Employed extensively by entertainment and tech-focused boutique firms.",
        workNature: "Licensing Drafting, Royalty Negotiations & Anti-Piracy Action.",
        futureScope: "With the explosion of generative AI and global digital content creation, defining and protecting original intellectual copyright is a violently expanding legal frontier.",
        jobDemandTrend: "Growing Rapidly",
        summary: "The protectors of human creativity, securing the financial and legal rights of artists, authors, and software developers."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "IP Litigation Lawyer",
        description: "The courtroom warriors of intellectual property. When multi-million dollar patents or massive brand names are infringed upon, these litigators go to trial to secure massive financial damages or immediate injunctions.",
        educationPath: "LLB",
        additionalQualification: "STEM degree highly preferred if litigating tech/pharma patents.",
        competitiveExams: ["CLAT / AILET"],
        yearsOfStudy: "5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Aggressive Courtroom Argument", "Complex Evidentiary Knowledge", "Injunction Pleadings", "Cross-Examination"],
        salaryRange: "India: ₹8 LPA - ₹50+ LPA | Global: $150,000 - $400,000+ per year",
        roadmap: ["Litigation Associate", "Senior IP Litigator", "Partner - IP Disputes", "Designated Senior Advocate (IP)"],
        governmentJobs: "Empanelled to defend the state's IP policies or contested patents.",
        corporateOpportunities: "In-house roles managing external litigation strategy.",
        lawFirmOpportunities: "The absolute most lucrative IP roles in global mega-firms.",
        workNature: "High-Stakes Courtroom Trials, Deposing Experts & Aggressive Legal Drafting.",
        futureScope: "Extremely secure. The financial stakes in patent and trademark wars between global mega-corporations guarantee a permanent need for ruthless IP trial lawyers.",
        jobDemandTrend: "Very High for Top Talent",
        summary: "The gladiators of the IP world, fighting brutal, incredibly complex courtroom battles over stolen technology and hijacked brands."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Patent Analyst",
        description: "A highly technical role operating largely outside the courtroom. They scour global databases to figure out if a new invention is truly novel, map out competitor technology trends, and evaluate if a patent can be legally invalidated.",
        educationPath: "B.Tech/M.Tech/Ph.D. + LLB (Optional but highly beneficial)",
        additionalQualification: "Deep technical expertise in a specific niche (e.g., AI, Genomics, Telecommunications).",
        competitiveExams: ["GATE/CSIR-NET (for Science) -> Law Exames"],
        yearsOfStudy: "4 to 6 Years",
        certifications: ["WIPO Patent Analytics Certifications"],
        skills: ["Prior Art Search", "Patent Mapping/Landscaping", "Freedom to Operate (FTO) Analysis", "Data Mining"],
        salaryRange: "India: ₹5 LPA - ₹16 LPA | Global: $70,000 - $130,000 per year",
        roadmap: ["Junior Analyst", "Senior Patent Engineer", "IP Analytics Manager", "Director of Patent Intelligence"],
        governmentJobs: "Patent Office research division roles.",
        corporateOpportunities: "Hired heavily by R&D departments to determine what technology to invent next without infringing existing patents.",
        lawFirmOpportunities: "A critical support role in massive IP litigation departments.",
        workNature: "Deep Technical Research, Data Analytics & FTO Reporting.",
        futureScope: "A rapidly growing field heavily integrated with AI tools, crucial for corporate R&D strategy and avoiding multi-million dollar patent lawsuits.",
        jobDemandTrend: "Stable and Growing",
        summary: "The intelligence-gatherers of the tech world, mapping global patents to dictate exactly where corporations can legally innovate."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Trademark Consultant",
        description: "Provides highly targeted strategic advice to advertising agencies, startups, and massive corporations regarding whether their new multi-million dollar brand name is legally available globally before they initiate marketing campaigns.",
        educationPath: "LLB / Marketing Degree -> Law Degree",
        additionalQualification: "Expertise in Global Trademark Treaties (Madrid Protocol).",
        competitiveExams: ["None specifically"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Registered Trademark Agent"],
        skills: ["Global Search Methodologies", "Brand Dilution Risk", "Advertising Law", "Marketing Synergy"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $65,000 - $120,000 per year",
        roadmap: ["Search Specialist", "Brand Consultant", "Senior Strategy Counsel", "Chief Brand Risk Officer"],
        governmentJobs: "Registry consultation.",
        corporateOpportunities: "Employed directly by massive FMCG conglomerates (Unilever, P&G) and global ad agencies.",
        lawFirmOpportunities: "High demand in boutique trademark practices.",
        workNature: "Global Brand Searching, Risk Assessment & Marketing Consultation.",
        futureScope: "Vital to the marketing world. A single global trademark lawsuit can force a multinational to rebrand entirely; these consultants prevent that catastrophe.",
        jobDemandTrend: "Stable",
        summary: "The legal safety-net for global marketing, ensuring that a brilliant new brand name doesn't instantly trigger a catastrophic lawsuit."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "IP Legal Advisor for Corporations",
        description: "An in-house generalist solely responsible for maximizing a corporation's intellectual assets. They decide whether to patent a tech, keep it a trade secret, or aggressively monetize it through global licensing deals.",
        educationPath: "LLB -> CS (Company Secretary) or MBA/LLM",
        additionalQualification: "Business Strategy Acumen.",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["In-House Counsel Diplomas"],
        skills: ["Trade Secret Protection", "IP Valuation", "Employee NDAs", "Corporate IP Policy"],
        salaryRange: "India: ₹8 LPA - ₹30 LPA | Global: $100,000 - $220,000 per year",
        roadmap: ["In-House Counsel (IP)", "Senior IP Advisor", "General Counsel", "Chief Intellectual Property Officer (CIPO)"],
        governmentJobs: "Advising major PSUs (like ISRO, DRDO) on how to commercialize their state-funded research.",
        corporateOpportunities: "100% focused on corporate employment; arguably the most crucial role in modern tech/pharma firms.",
        lawFirmOpportunities: "N/A (Strictly an in-house role).",
        workNature: "Corporate Strategy, Commercializing Assets & NDA Enforcement.",
        futureScope: "A highly prestigious corporate role. In the modern economy, a company's IP is its highest-valued asset; managing it is a strictly C-suite strategic function.",
        jobDemandTrend: "High in Tech/Pharma",
        summary: "The business-minded legal strategist optimizing and monetizing every internal idea, patent, and brand a corporation owns."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Technology & Software IP Lawyer",
        description: "Specializes exclusively in the insanely complex intersection of software code, algorithms, and law. They structure open-source licensing compliance, SaaS agreements, and patent AI innovations.",
        educationPath: "B.Tech (Computer Science) -> LLB",
        additionalQualification: "Deep understanding of coding, SaaS architecture, and AI models.",
        competitiveExams: ["Tech Entrances -> Law Entrances"],
        yearsOfStudy: "7 Years",
        certifications: ["Certified Information Privacy Professional (CIPP/E) Optional"],
        skills: ["Software Patents", "Open Source Licensing (GPL, Apache)", "Tech Transfer Agreements", "SaaS Law"],
        salaryRange: "India: ₹10 LPA - ₹40 LPA | Global: $130,000 - $300,000 per year",
        roadmap: ["Tech Law Associate", "Senior Software Counsel", "Partner - Tech IP", "General Counsel (Tech Giant)"],
        governmentJobs: "Advising government IT initiatives on software procurement and IP ownership.",
        corporateOpportunities: "Massive demand in Silicon Valley, Bengaluru tech hubs, and multi-billion dollar SaaS startups.",
        lawFirmOpportunities: "The fastest growing department in Tier-1 corporate law firms.",
        workNature: "Code Licensing, Complex Tech Drafting & AI Legal Structuring.",
        futureScope: "The absolute apex of modern IP law. As software and AI eat the world, lawyers who truly understand both code and copyright command unparalleled premiums.",
        jobDemandTrend: "Explosive Growth",
        summary: "A hyper-specialized attorney acting as the crucial translating layer between elite software engineers and global legal frameworks."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Entertainment & Media IP Lawyer",
        description: "The power-brokers of the entertainment industry. They negotiate rights for major motion pictures, clear music sampling copyrights, draft talent agreements, and structure multi-million dollar streaming distribution deals.",
        educationPath: "LLB -> LLM in Entertainment/Media Law",
        additionalQualification: "Deep operational knowledge of the entertainment industry.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 Years",
        certifications: ["Media Law Diplomas"],
        skills: ["Sync Licensing", "Talent Contracts", "Character Copyrighting", "Defamation/Privacy Law"],
        salaryRange: "India: ₹6 LPA - ₹30+ LPA | Global: $90,000 - $400,000+ per year",
        roadmap: ["Media Associate", "Talent Counsel", "Studio Legal Executive", "Partner - Entertainment Law"],
        governmentJobs: "Roles in the Ministry of Information and Broadcasting (I&B).",
        corporateOpportunities: "Hired directly by Netflix, Disney, massive record labels, and production studios.",
        lawFirmOpportunities: "Boutique entertainment law firms operating in Los Angeles, London, and Mumbai.",
        workNature: "High-level Hollywood/Bollywood Deal Structuring & Rights Clearance.",
        futureScope: "As global streaming wars intensify and indie content explodes, the demand for lawyers to lock down aggressive IP distribution rights is massive and glamorous.",
        jobDemandTrend: "Highly Lucrative Niche",
        summary: "The Hollywood/Bollywood legal architects, ensuring artists get paid and studios legally secure the rights to global blockbusters."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "IP Licensing & Contracts Specialist",
        description: "Does not litigate or register IP; intensely focused on monetizing it. They draft the highly lucrative contracts that allow other companies to legally rent or use a patent, character, or brand logo for massive royalties.",
        educationPath: "LLB -> Commerce/Finance Background",
        additionalQualification: "Financial modeling and valuation skills.",
        competitiveExams: ["None specific"],
        yearsOfStudy: "5 Years",
        certifications: ["Commercial Law Diplomas"],
        skills: ["Royalty Structuring", "Franchising Agreements", "Cross-Licensing", "Commercial Drafting"],
        salaryRange: "India: ₹7 LPA - ₹25 LPA | Global: $85,000 - $180,000 per year",
        roadmap: ["Licensing Executive", "Senior Commercial Counsel", "Director of Licensing", "VP of Revenue (IP)"],
        governmentJobs: "Managing licensing of indigenous technology developed by state labs.",
        corporateOpportunities: "Massive demand in merchandising companies, pharma giants, and tech hardware firms.",
        lawFirmOpportunities: "A core competency required in all major corporate transactions.",
        workNature: "Intense Deal Negotiation, Royalty Analytics & Complex Financial Drafting.",
        futureScope: "The financial engine of IP. Generating passive revenue by aggressively licensing unused patents or character rights is the ultimate corporate goal.",
        jobDemandTrend: "Stable and High Value",
        summary: "The master negotiators who turn dormant patents and cartoon characters into multi-million dollar, reoccurring corporate revenue streams."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "IP Portfolio Manager",
        description: "Operates like a wealth manager, but for intellectual rather than financial assets. They oversee thousands of global patents and trademarks for MNCs, ensuring renewals are paid, identifying weak assets to abandon, and acquiring new startups for their IP.",
        educationPath: "LLB or MBA + IP Certification",
        additionalQualification: "Data Analytics and highly organized database management skills.",
        competitiveExams: ["None"],
        yearsOfStudy: "4 to 5 Years",
        certifications: ["WIPO Advanced Diplomas in IP Management"],
        skills: ["Global Maintenance Filings", "IP Valuation", "Budget Forecasting", "M&A IP Auditing"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $80,000 - $150,000 per year",
        roadmap: ["IP Paralegal/Associate", "Portfolio Manager", "Director of IP Assets", "Chief Intellectual Property Officer"],
        governmentJobs: "Managing state-owned enterprise portfolios.",
        corporateOpportunities: "Essential for massive conglomerates managing global IP rights across 100+ jurisdictions.",
        lawFirmOpportunities: "A high-revenue service offered to clients by massive IP boutiques.",
        workNature: "Database Management, Financial Auditing & Global Legal Maintenance.",
        futureScope: "A highly analytical, non-adversarial role offering immense stability and work-life balance while remaining critical to global corporate operations.",
        jobDemandTrend: "Stable",
        summary: "The meticulous orchestrators managing and defending the massive, multi-jurisdictional IP treasuries of global conglomerates."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "IP Law Researcher",
        description: "Dives deep into the highly ambiguous frontiers of IP law—such as whether a machine-learning AI can legally hold a patent, or who owns the copyright to bio-genetically engineered DNA.",
        educationPath: "LLB -> LLM in Tech/IP Law",
        additionalQualification: "Strong academic background in emerging technologies.",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Advanced Jurisprudence", "AI Ethics", "Biotech Law", "Policy Synthesizing"],
        salaryRange: "India: ₹5 LPA - ₹12 LPA | Global: $65,000 - $110,000 per year",
        roadmap: ["Research Fellow", "Senior IP Analyst", "Think-Tank Scholar", "Policy Advisor"],
        governmentJobs: "Working within the Department for Promotion of Industry and Internal Trade (DPIIT).",
        corporateOpportunities: "Hired by massive tech lobbies (like NASSCOM/BSA) to influence government policy.",
        lawFirmOpportunities: "Hired by litigation teams to research arguments for entirely unprecedented 'unicorn' cases.",
        workNature: "Pure Legal Research, Academic Writing & Policy Formulation.",
        futureScope: "Crucial for navigating the chaotic legal vacuum created by rapid technological advancements (Generative AI, CRISPR, Web3).",
        jobDemandTrend: "Niche but Expanding",
        summary: "The academic pioneers exploring and defining the legal rules for technologies that have barely been invented."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Intellectual Property Law Professor",
        description: "Instructs aspiring tech and corporate lawyers on the complex international systems (WIPO, TRIPS, Paris Convention) governing intellectual assets, while publishing heavily cited research papers on modern patent reforms.",
        educationPath: "LLB -> LLM -> Ph.D. in IP Law",
        additionalQualification: "Published academic treatises.",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Deep Doctrinal Knowledge", "Pedagogy", "TRIPS Agreement Analysis", "Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $80,000 - $170,000+ per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean of specialized IP Institutions"],
        governmentJobs: "Permanent faculty at institutions like National Law Universities or the Rajiv Gandhi National Institute of Intellectual Property Management (RGNIIPM).",
        corporateOpportunities: "Frequently hired as ad-hoc expert consultants.",
        lawFirmOpportunities: "Hired as expert witnesses in massive software or pharma litigations.",
        workNature: "Teaching, Researching, and Publishing.",
        futureScope: "An incredibly prestigious academic route. With tech-law being the most desired specialization for modern students, elite IP professors are highly sought after by top universities globally.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic titans defining the theoretical frameworks of innovation law and mentoring the next generation of tech lawyers."
    },
    {
        domain: "Law",
        branch: "Intellectual Property Law",
        title: "Innovation & Patent Strategy Consultant",
        description: "A high-level hybrid of data-scientist, engineer, and lawyer. They do not draft patents; they sit with corporate CEOs and tell them exactly which new technologies to invest R&D money into based on gaps in global patent data.",
        educationPath: "Ph.D. in STEM / MBA -> Legal Knowledge Base",
        additionalQualification: "Deep operational knowledge of the tech/pharma industries.",
        competitiveExams: ["None"],
        yearsOfStudy: "8+ Years",
        certifications: ["Patent Information Professional Certificates"],
        skills: ["White-Space Analysis", "Tech Forecasting", "R&D Strategy", "Executive Advising"],
        salaryRange: "India: ₹12 LPA - ₹35 LPA | Global: $120,000 - $250,000 per year",
        roadmap: ["Patent Analyst", "Innovation Strategist", "Director of Technology Intelligence", "Chief Innovation Officer"],
        governmentJobs: "Advising national science foundations on strategic grant allocations.",
        corporateOpportunities: "Employed directly within the C-suite of massive R&D driven pharmaceutical and tech conglomerates.",
        lawFirmOpportunities: "Operating largely within elite 'Big 4' consulting firms or specialized IP intelligence boutiques.",
        workNature: "Executive Consulting, Data Mining & Geopolitical Tech Forecasting.",
        futureScope: "The apex of actionable tech intelligence. Dictating exactly where a multi-billion dollar corporation should aim its R&D budget saves billions in wasted research and secures future global monopolies.",
        jobDemandTrend: "Highly Elite/Lucrative",
        summary: "A pure visionary strategist, utilizing global patent data to map out the future of technology and command corporate R&D directions."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Intellectual Property Law" });
        await Career.insertMany(ipLawProfessions);
        console.log('Intellectual Property Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
