const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const economicsProfessions = [
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Economist",
        description: "Economists study the production and distribution of resources, goods, and services by collecting and analyzing data, researching trends, and evaluating economic issues. They provide forecasts to guide governments and businesses.",
        skills: ["Macro/Microeconomics", "Statistical Analysis", "Econometrics", "Forecasting", "Policy Evaluation"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $80,000 - $150,000+ per year",
        educationPath: "B.A/B.Sc Economics -> M.A/M.Sc Economics -> PhD (Preferred for top roles)",
        futureScope: "As global markets become increasingly intertwined and complex, governments and corporations heavily rely on economists to predict risks, manage inflation, and guide long-term financial strategy.",
        roadmap: [
            "Junior Analyst: Research Assistant / Junior Economist",
            "Senior Analyst: Economist / Policy Advisor",
            "Lead Economist: Senior Economist / Research Director",
            "Chief Economist: Chief Economist (Bank/Government)"
        ],
        certifications: ["None strictly required; PhD is the benchmark."],
        summary: "The highest authority on market behavior and financial systems, shaping the economic frameworks of nations and massive corporations.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Government", "Think Tanks", "Academia", "Banks", "International Organizations"],
        jobDemandTrend: "Stable",
        governmentJobs: "Indian Economic Service (IES), RBI, NITI Aayog, Ministry of Finance.",
        competitiveExams: ["UPSC IES", "RBI Grade B (DEPR)"],
        privateSectorOpportunities: "Chief Economist roles in commercial banks, mutual funds, and large consulting firms.",
        internationalJobOpportunities: "World Bank, IMF, Asian Development Bank, United Nations.",
        researchOpportunities: "Extensive scope in think tanks (e.g., Brookings, CPR) and academia.",
        fieldWork: "Research / Policy",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Economic Analyst",
        description: "Economic Analysts apply economic theory to business problems. They analyze market data, track economic indicators (like GDP and inflation), and help companies understand how broader economic trends impact their specific industry.",
        skills: ["Data Analysis", "Market Research", "Financial Modeling", "Excel/SQL", "Report Writing"],
        salaryRange: "India: ₹6 LPA - ₹15 LPA | Global: $65,000 - $110,000 per year",
        educationPath: "B.A/B.Sc Economics -> M.A/M.Sc Economics or MBA",
        futureScope: "With businesses becoming highly data-reliant, bridging the gap between raw economic data and actionable corporate strategy makes Economic Analysts highly sought after.",
        roadmap: [
            "Junior Analyst: Junior Economic Analyst",
            "Senior Analyst: Senior Analyst / Consultant",
            "Lead Economist: Economics Manager",
            "Chief Economist: Director of Economic Strategy"
        ],
        certifications: ["CFA (Optional but highly beneficial)"],
        summary: "A practical, corporate-focused role utilizing economic principles to drive profitability and mitigate market risks for businesses.",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Consulting", "Financial Services", "Corporate Strategy", "Market Research"],
        jobDemandTrend: "High",
        governmentJobs: "Contractual analyst roles in various state and central ministries.",
        competitiveExams: ["None specific to the corporate role."],
        privateSectorOpportunities: "High demand in Big 4 consulting and corporate strategy teams.",
        internationalJobOpportunities: "Global consulting firms and multinational corporate HQs.",
        researchOpportunities: "Applied market research in private sector think tanks.",
        fieldWork: "Corporate / Research",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Economic Policy Analyst",
        description: "Policy Analysts review, evaluate, and develop government policies or corporate guidelines. They assess the economic and social impact of proposed legislation and advise lawmakers or executives on the best course of action.",
        skills: ["Public Policy", "Qualitative Research", "Data Interpretation", "Stakeholder Management", "Legal Knowledge"],
        salaryRange: "India: ₹5 LPA - ₹18 LPA | Global: $60,000 - $120,000 per year",
        educationPath: "B.A Economics/Pol Science -> Master's in Public Policy (MPP) / Economics",
        futureScope: "As social, environmental, and economic issues become profoundly complex, governments and NGOs require expert analysts to draft effective, evidence-based policies.",
        roadmap: [
            "Junior Analyst: Research Associate",
            "Senior Analyst: Policy Analyst",
            "Lead Economist: Senior Policy Advisor",
            "Chief Economist: Director of Policy / Secretary"
        ],
        certifications: ["None required."],
        summary: "A deeply impactful career focused on shaping the rules, laws, and systemic frameworks that govern society and business.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Government", "Think Tanks", "NGOs", "Corporate Public Affairs"],
        jobDemandTrend: "Stable",
        governmentJobs: "Direct roles in ministries, legislative assistant roles (LAMP Fellowship).",
        competitiveExams: ["UPSC Civil Services (for highest policy roles)"],
        privateSectorOpportunities: "Public Policy / Government Affairs teams in tech giants (Google, Meta) and consulting.",
        internationalJobOpportunities: "UN Agencies, WHO, WEF, and global philanthropic foundations.",
        researchOpportunities: "High scope in academic and independent policy research institutes.",
        fieldWork: "Policy / Research",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Development Economist",
        description: "Development Economists focus on improving the economic, health, and social conditions of developing nations. They study poverty, inequality, healthcare, education, and design systemic interventions to promote sustainable global growth.",
        skills: ["Development Theory", "Impact Evaluation", "Field Research", "Statistical Software (Stata/R)", "Empathy"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $70,000 - $140,000 per year",
        educationPath: "B.A Economics -> M.A Development Economics -> PhD (Highly Recommended)",
        futureScope: "Critical for achieving the UN's Sustainable Development Goals (SDGs). They lead massive funding initiatives to structurally uplift impoverished regions globally.",
        roadmap: [
            "Junior Analyst: Field Researcher / Research Assistant",
            "Senior Analyst: Development Economist",
            "Lead Economist: Principal Investigator / Program Director",
            "Chief Economist: Head of Global Development"
        ],
        certifications: ["Specialized courses in Impact Evaluation (e.g., J-PAL)"],
        summary: "A noble, globally influential career dedicated to solving humanity's most pressing socioeconomic crises directly at the ground level.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["International NGOs", "Global Financial Institutions", "Government", "Academia"],
        jobDemandTrend: "High (in global sector)",
        governmentJobs: "Roles in NITI Aayog, Ministry of Rural Development, Ministry of Finance.",
        competitiveExams: ["IES (for government development roles)"],
        privateSectorOpportunities: "ESG/CSR (Corporate Social Responsibility) wings of major corporations.",
        internationalJobOpportunities: "Peak roles in the World Bank, IMF, UN Development Programme (UNDP), Gates Foundation.",
        researchOpportunities: "Extensive global field research and collaboration with universities.",
        fieldWork: "Field / Policy / Research",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Financial Economist",
        description: "Financial Economists analyze immense financial markets, banking systems, and investment portfolios. They study how macroeconomic factors (interest rates, inflation) influence the trading and pricing of financial assets.",
        skills: ["Financial Markets", "Econometrics", "Quantitative Finance", "Risk Modeling", "Asset Pricing"],
        salaryRange: "India: ₹10 LPA - ₹30+ LPA | Global: $90,000 - $200,000+ per year",
        educationPath: "B.Sc/B.A Economics -> Master's in Financial Economics / Quantitative Finance",
        futureScope: "Extremely lucrative. As algorithmic trading and complex derivatives dominate finance, deep understanding of macroeconomic market drivers is essential for hedge funds and investment banks.",
        roadmap: [
            "Junior Analyst: Quantitative Researcher",
            "Senior Analyst: Financial Economist / Trader",
            "Lead Economist: Portfolio Manager",
            "Chief Economist: Chief Investment Officer / Partner"
        ],
        certifications: ["CFA", "FRM", "CQF"],
        summary: "The highest paying sub-field of economics, strictly focused on maximizing financial returns and managing risks in global capital markets.",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Investment Banks", "Hedge Funds", "Central Banks", "Asset Management"],
        jobDemandTrend: "High",
        governmentJobs: "Specialized roles in RBI (Financial Markets Department) and SEBI.",
        competitiveExams: ["RBI Grade B (DEPR)"],
        privateSectorOpportunities: "Dominant in Wall Street equivalents; hedge funds, quantitative trading desks.",
        internationalJobOpportunities: "Global financial capitals (New York, London, Singapore).",
        researchOpportunities: "Publishing financial models and market research for institutional investors.",
        fieldWork: "Corporate / Research",
        licenseRequired: "SEBI/Regulatory licenses if managing public funds.",
        riskLevel: "High"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Research Economist",
        description: "Research Economists dedicate their careers to academic or institutional research, uncovering new economic theories, publishing vital papers, and teaching at the university level.",
        skills: ["Advanced Mathematics", "Econometric Theory", "Academic Writing", "Critical Thinking", "Teaching"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $80,000 - $160,000 per year",
        educationPath: "B.A/B.Sc Economics -> M.A Economics -> PhD (Mandatory)",
        futureScope: "The bedrock of economic evolution. They formulate theories that governments and central banks will use decades into the future to manage the global economy.",
        roadmap: [
            "Junior Analyst: PhD Candidate / Postdoctoral Fellow",
            "Senior Analyst: Assistant Professor",
            "Lead Economist: Tenured Professor / Senior Researcher",
            "Chief Economist: Head of Department / Think Tank Director"
        ],
        certifications: ["UGC NET (for teaching in India)"],
        summary: "A pure academic pursuit focused on expanding human knowledge regarding commerce, behavior, and societal resource allocation.",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Universities", "Independent Think Tanks", "Central Banks"],
        jobDemandTrend: "Stable",
        governmentJobs: "Professorships in Central Universities, Research Wings of Government Ministries.",
        competitiveExams: ["UGC NET", "UPSC (for research directorates)"],
        privateSectorOpportunities: "Research roles in private economic institutions and consulting.",
        internationalJobOpportunities: "Academic placements in global top-tier universities (Ivy League, Oxbridge).",
        researchOpportunities: "100% focused on research and publication.",
        fieldWork: "Research",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Data Economist",
        description: "A hybrid between a Data Scientist and an Economist. Data Economists use advanced machine learning, big data tools, and coding to test economic theories on massive, unstructured datasets often gathered from digital platforms.",
        skills: ["Python/R", "Machine Learning", "Econometrics", "Big Data (Hadoop/Spark)", "Cloud Computing"],
        salaryRange: "India: ₹12 LPA - ₹35 LPA | Global: $100,000 - $200,000+ per year",
        educationPath: "B.Sc Economics/Stats -> Master's in Applied Economics / Data Science",
        futureScope: "The future of corporate economics. Tech giants rely on them to design auction pricing, recommendation algorithms, and platform monetization strategies.",
        roadmap: [
            "Junior Analyst: Data Analyst / Junior Data Scientist",
            "Senior Analyst: Data Economist",
            "Lead Economist: Lead Tech Economist",
            "Chief Economist: Chief Economist (Tech Platforms)"
        ],
        certifications: ["Data Science Certifications (AWS, Google Cloud)"],
        summary: "The modern evolution of economics, heavily relying on elite coding and AI to model consumer behavior on an unprecedented, algorithmic scale.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Big Tech (FAANG)", "E-commerce", "Ride-Sharing Apps", "Fintech"],
        jobDemandTrend: "Very High",
        governmentJobs: "Limited, but growing in specialized data cells within RBI and NITI Aayog.",
        competitiveExams: ["None specific."],
        privateSectorOpportunities: "Extensive opportunities in companies like Amazon, Uber, AirBnb, and Netflix.",
        internationalJobOpportunities: "Massive demand in Global Tech Hubs (Silicon Valley, Seattle, London).",
        researchOpportunities: "Algorithmic economics research within tech giants.",
        fieldWork: "Corporate / Research",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Public Finance Analyst",
        description: "Public Finance Analysts study the role of the government in the economy. They analyze taxation policies, government spending, public debt, and massive state budgets to ensure the financial viability of public works and social schemes.",
        skills: ["Public Budgeting", "Taxation Policy", "Cost-Benefit Analysis", "Fiscal Policy", "Financial Modeling"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $70,000 - $130,000 per year",
        educationPath: "B.A Economics/Commerce -> M.A Economics / Master's of Public Administration (MPA)",
        futureScope: "Essential for state functioning. As national debts rise and infrastructure spending increases, experts managing public treasuries are critically important.",
        roadmap: [
            "Junior Analyst: Budget Analyst",
            "Senior Analyst: Public Finance Consultant",
            "Lead Economist: Senior Fiscal Advisor",
            "Chief Economist: Finance Secretary / Comptroller"
        ],
        certifications: ["None specific"],
        summary: "A role operating at the intersection of economics and governance, directly dealing with how a country finances its operations and citizens.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Government", "Municipalities", "Consulting (Public Sector Practice)", "Think Tanks"],
        jobDemandTrend: "Stable",
        governmentJobs: "High scope in Ministry of Finance, state finance departments, CAG.",
        competitiveExams: ["UPSC Civil Services", "State PSCs", "IES"],
        privateSectorOpportunities: "Public Sector Advisory roles in the Big 4 consulting firms.",
        internationalJobOpportunities: "IMF (Fiscal Affairs Department), World Bank.",
        researchOpportunities: "Fiscal policy research in premier economic think tanks.",
        fieldWork: "Policy",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "International Trade Analyst",
        description: "International Trade Analysts examine the complex flow of goods, services, and capital across international borders. They study tariffs, trade agreements, sanctions, and global supply chains to advise corporations or governments on global commerce strategies.",
        skills: ["International Trade Law", "Macroeconomics", "Tariff Analysis", "Geopolitics", "Data Visualization"],
        salaryRange: "India: ₹7 LPA - ₹20 LPA | Global: $75,000 - $140,000 per year",
        educationPath: "B.A Economics -> M.A International Economics / International Relations",
        futureScope: "Amidst shifting global alliances, trade wars, and new supply chain routes, specialists who understand international trade mechanisms are highly strategic assets.",
        roadmap: [
            "Junior Analyst: Trade Analyst",
            "Senior Analyst: Senior Trade Consultant",
            "Lead Economist: Principal Trade Advisor",
            "Chief Economist: Trade Negotiator / Director of Global Strategy"
        ],
        certifications: ["None required"],
        summary: "A deeply geopolitical economics role navigating the complex treaties and tariffs that dictate global imports and exports.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["MNCs", "Government Trade Ministries", "Logistics Giants", "Consulting"],
        jobDemandTrend: "High",
        governmentJobs: "Ministry of Commerce and Industry, Directorate General of Foreign Trade (DGFT).",
        competitiveExams: ["UPSC", "IES"],
        privateSectorOpportunities: "Global strategy departments in any multinational corporation navigating tariffs.",
        internationalJobOpportunities: "World Trade Organization (WTO), UNCTAD.",
        researchOpportunities: "Trade policy analysis in global strategic think tanks.",
        fieldWork: "Policy / Corporate",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Actuary (Economics/Finance)",
        description: "Actuaries use extreme mathematics, statistics, and financial theory to study uncertain future events, especially those of concern to insurance and pension programs. They evaluate the likelihood of those events and design creative ways to reduce financial impact.",
        skills: ["Advanced Mathematics", "Probability Theory", "Risk Management", "Statistical Software", "Attention to Detail"],
        salaryRange: "India: ₹10 LPA - ₹40+ LPA | Global: $90,000 - $200,000+ per year",
        educationPath: "B.Sc Math/Stats/Economics -> Actuarial Exams (Continuous)",
        futureScope: "Consistently ranked as one of the best jobs globally regarding pay, work-life balance, and job security due to the extreme barrier to entry (tough exams) and constant necessity in insurance.",
        roadmap: [
            "Junior Analyst: Actuarial Analyst (Clearing initial exams)",
            "Senior Analyst: Associate Actuary",
            "Lead Economist: Fellow Actuary",
            "Chief Economist: Chief Risk Officer / Chief Actuary"
        ],
        certifications: ["Fellowship from Institute of Actuaries (IAI, IFoA, SOA)"],
        summary: "An incredibly specialized, high-paying career requiring unparalleled mathematical prowess to calculate and price global risks.",
        yearsOfStudy: "3 Years (Degree) + 5 to 7 Years (Clearing 10-15 Actuarial Exams while working)",
        industriesHiring: ["Insurance", "Reinsurance", "Pension Funds", "Consulting"],
        jobDemandTrend: "Very High",
        governmentJobs: "Roles in IRDAI, LIC, and pension regulatory bodies.",
        competitiveExams: ["ACET", "Actuarial Professional Exams"],
        privateSectorOpportunities: "Massive demand in global insurance hubs and Big 4 valuation teams.",
        internationalJobOpportunities: "Universal demand globally; actuarial credentials from IFoA/SOA are globally recognized.",
        researchOpportunities: "Developing new mortality tables and complex risk models.",
        fieldWork: "Corporate",
        licenseRequired: "Fellowship required to sign off on specific statutory reports.",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Statistician (Economics/Data)",
        description: "Statisticians apply statistical methods and models to real-world problems. They gather, analyze, and interpret massive amounts of numerical data to help businesses, governments, and scientists make informed decisions.",
        skills: ["Statistical Modeling", "SAS/Python/R", "Data Mining", "Survey Design", "Quantitative Analysis"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $75,000 - $130,000 per year",
        educationPath: "B.Sc Statistics/Math/Economics -> M.Sc Statistics",
        futureScope: "The foundational role behind the 'data revolution'. Before AI and ML, robust statistical significance must be established, making statisticians indispensable across all sectors.",
        roadmap: [
            "Junior Analyst: Statistical Analyst / Programmer",
            "Senior Analyst: Senior Statistician",
            "Lead Economist: Lead Data Scientist / Biostatistician",
            "Chief Economist: Director of Statistics / Analytics"
        ],
        certifications: ["SAS Certified Advanced Programmer"],
        summary: "A deeply analytical career utilizing pure mathematics to draw undeniable, factual conclusions from raw data across infinite domains.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Healthcare/Pharma", "Government", "Tech", "Finance", "Market Research"],
        jobDemandTrend: "High",
        governmentJobs: "Indian Statistical Service (ISS), Ministry of Statistics and Programme Implementation (MoSPI).",
        competitiveExams: ["UPSC ISS"],
        privateSectorOpportunities: "Heavy demand in clinical research (Biostatisticians) and corporate data teams.",
        internationalJobOpportunities: "UN Statistics Division, global health organizations.",
        researchOpportunities: "Core methodology research in academia or applied research in corporate R&D.",
        fieldWork: "Research / Corporate",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Government Economic Officer",
        description: "Government Economic Officers (like those in the Indian Economic Service) aid in drafting and implementing national economic policies. They utilize economic principles to advise the executive branch on taxation, employment, and resource allocation.",
        skills: ["Public Administration", "Policy Formulation", "Macroeconomics", "Diplomacy", "Strategic Thinking"],
        salaryRange: "India: ₹10 LPA - ₹25 LPA (Plus massive government perks) | Global: N/A",
        educationPath: "M.A/M.Sc in Economics (Minimum criteria) -> Competitive Exam -> Interview",
        futureScope: "Extremely secure and prestigious. These officers rise to the highest levels of national bureaucracy, shaping the economic destiny of the country.",
        roadmap: [
            "Junior Analyst: Assistant Director",
            "Senior Analyst: Deputy/Joint Director",
            "Lead Economist: Economic Adviser",
            "Chief Economist: Chief Economic Adviser (CEA)"
        ],
        certifications: ["None"],
        summary: "An elite bureaucratic role granting immense power and responsibility over national economic planning and government expenditure.",
        yearsOfStudy: "5 Years (Plus intense exam preparation)",
        industriesHiring: ["Central Government Ministries", "Planning Commissions"],
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "This is purely a government-centric elite cadre.",
        competitiveExams: ["UPSC Indian Economic Service (IES) Exam"],
        privateSectorOpportunities: "Extraordinary exit opportunities post-retirement into corporate boards or consulting.",
        internationalJobOpportunities: "Deputations to the UN, IMF, World Bank representing the national government.",
        researchOpportunities: "Internal governmental research and economic surveys.",
        fieldWork: "Policy",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Economic Consultant",
        description: "Economic Consultants use advanced economic analysis to help corporations, law firms, and government agencies solve complex issues. They often provide expert testimony in antitrust lawsuits, calculate damages, and analyze market competition.",
        skills: ["Microeconomics", "Econometrics", "Regulatory Law", "Litigation Support", "Expert Report Writing"],
        salaryRange: "India: ₹12 LPA - ₹35 LPA | Global: $90,000 - $180,000+ per year",
        educationPath: "M.A/Ph.D in Economics -> Specialization in Industrial Organization / Antitrust",
        futureScope: "A highly specialized niche. As massive tech monopolies face intense global antitrust scrutiny, the demand for elite economic consultants to defend or prosecute them is skyrocketing.",
        roadmap: [
            "Junior Analyst: Research Analyst",
            "Senior Analyst: Consultant / Senior Consultant",
            "Lead Economist: Principal",
            "Chief Economist: Managing Director / Testifying Expert"
        ],
        certifications: ["None required; academic pedigree is paramount."],
        summary: "A lucrative intersection of economics and law, utilizing complex market theories to settle massive corporate disputes and antitrust litigation.",
        yearsOfStudy: "5 to 8 Years (Ph.D highly preferred)",
        industriesHiring: ["Economic Consulting Firms (e.g., NERA, Compass Lexecon, Cornerstone)", "Big Law Firms"],
        jobDemandTrend: "High",
        governmentJobs: "Consulting for bodies like the Competition Commission of India (CCI).",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Top boutique economic consulting firms.",
        internationalJobOpportunities: "Massive demand in the US and Europe dealing with anti-monopoly laws.",
        researchOpportunities: "Deep applied research on market power and competitive pricing.",
        fieldWork: "Corporate / Legal",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Market Research Analyst",
        description: "Market Research Analysts study consumer behavior, market conditions, and competitor activities to help companies decide what products to sell, who will buy them, and at what price.",
        skills: ["Survey Design", "Qualitative/Quantitative Analysis", "Consumer Psychology", "Data Visualization", "Communication"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $60,000 - $100,000 per year",
        educationPath: "B.A Economics/Statistics/BBA -> MBA in Marketing or Master's in Applied Stats",
        futureScope: "Essential for product launches. In a hyper-competitive consumer market, companies must rely on precise market research to avoid costly product failures.",
        roadmap: [
            "Junior Analyst: Research Executive",
            "Senior Analyst: Senior Research Analyst",
            "Lead Economist: Research Manager",
            "Chief Economist: Consumer Insights Director"
        ],
        certifications: ["Certifications in Market Research (e.g., from insights associations)"],
        summary: "The driving force behind consumer-centric corporate strategy, ensuring businesses create products that the market actually wants.",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Market Research Firms (Nielsen, Kantar)", "FMCG", "Tech", "Media"],
        jobDemandTrend: "High",
        governmentJobs: "Roles in governmental statistical agencies and demographic surveys.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Extensive roles in ad agencies and massive consumer goods companies.",
        internationalJobOpportunities: "Global consumer insight roles in MNCs.",
        researchOpportunities: "Core primary and secondary corporate research.",
        fieldWork: "Corporate / Research",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Economics",
        title: "Behavioral Economist",
        description: "Behavioral Economists integrate psychology with economics. They study the hidden psychological, cognitive, and emotional factors that cause consumers and institutions to make irrational financial decisions, and design systems to 'nudge' better behavior.",
        skills: ["Behavioral Science", "Psychology", "Experimental Design", "Data Analytics", "Public Policy Design"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $85,000 - $150,000+ per year",
        educationPath: "B.A Economics/Psychology -> M.A/Ph.D in Behavioral Economics",
        futureScope: "A rapidly growing, cutting-edge subfield. Governments use them to improve policy compliance, and tech companies use them to optimize user engagement and product design.",
        roadmap: [
            "Junior Analyst: Behavioral Researcher",
            "Senior Analyst: Behavioral Scientist",
            "Lead Economist: Lead Behavioral Strategist",
            "Chief Economist: Chief Behavioral Officer"
        ],
        certifications: ["None required; multidisciplinary academic background preferred."],
        summary: "A fascinating career blending human psychology with market economics, uncovering the actual, often irrational, ways wealth and decisions flow in society.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Tech/Product Companies", "Marketing Agencies", "Government 'Nudge Units'", "Finance"],
        jobDemandTrend: "Very High (Exponentially growing niche)",
        governmentJobs: "Consultant roles in policy design units (Behavioral Insights Teams / Nudge Units).",
        competitiveExams: ["None"],
        privateSectorOpportunities: "UX and Product Strategy teams in massive tech and financial companies.",
        internationalJobOpportunities: "High demand in Western governments and global tech HQs.",
        researchOpportunities: "Heavy academic and experimental applied research.",
        fieldWork: "Research / Corporate / Policy",
        licenseRequired: "None",
        riskLevel: "Low"
    }
];

const seedEconomicsProfessions = async () => {
    try {
        await Career.deleteMany({ branch: "Economics" });
        await Career.insertMany(economicsProfessions);
        console.log('Economics Professions Seeded Successfully!'.blue.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedEconomicsProfessions();
