const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const physiotherapyProfessions = [
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Orthopedic Physiotherapist",
        description: "Diagnose, manage, and treat disorders and injuries of the musculoskeletal system including rehabilitation after orthopedic surgery.",
        summary: "Specialists in treating bone, joint, muscle, and ligament injuries and post-surgical rehab.",
        skills: ["Manual Therapy", "Joint Mobilization", "Strength Training", "Pain Management", "Patient Assessment"],
        salaryRange: "India: ₹3L - ₹8L | Global: $70K - $100K",
        educationPath: "BPT (Bachelor of Physiotherapy) → MPT (Orthopedics)",
        yearsOfStudy: "4.5 to 6.5 Years",
        industriesHiring: ["Hospitals", "Private Clinics", "Sports Clubs", "Rehabilitation Centers"],
        futureScope: "High demand due to an aging population, rising osteoporosis, and sedentary lifestyle-induced musculoskeletal issues.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate. Roles in government hospital physiotherapy departments.",
        freelanceOpportunities: "Maximum. Highly lucrative to open independent private practices.",
        fieldWork: "Low. Clinic or hospital based.",
        riskLevel: "Low (Physical strain possible from manual therapy)",
        certifications: ["State Physiotherapy Council Registration"],
        internshipRequirements: "Six months mandatory internship during BPT.",
        roadmap: ["Junior Physiotherapist", "Orthopedic Physiotherapist", "Senior Consultant", "Clinic Owner"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Sports Physiotherapist",
        description: "Work exclusively with athletes to prevent, evaluate, and treat sports-related injuries, focusing on rapid recovery and performance enhancement.",
        summary: "Rehab specialists optimizing athlete performance and managing sports injuries.",
        skills: ["Taping/Strapping Techniques", "Biomechanics Analysis", "Rapid On-field Triage", "Exercise Physiology", "Communication"],
        salaryRange: "India: ₹4L - ₹15L | Global: $80K - $120K",
        educationPath: "BPT → MPT (Sports Physiotherapy) / Diploma in Sports Medicine",
        yearsOfStudy: "4.5 to 6.5 Years",
        industriesHiring: ["Professional Sports Teams", "National Sports Academies (e.g., SAI)", "Fitness Centers"],
        futureScope: "Extremely high and lucrative as the professional sports industry grows globally and amateur athletics surge.",
        jobDemandTrend: "Very High",
        governmentJobs: "Roles in national/state sports authorities.",
        freelanceOpportunities: "High. Personal physiotherapist for elite athletes.",
        fieldWork: "Maximum. Traveling constantly with sports teams for tournaments.",
        riskLevel: "Low (High pressure to quickly return athletes to play)",
        certifications: ["Sports Physiotherapy Board Certification"],
        internshipRequirements: "Clinical rotations with collegiate or professional sports teams.",
        roadmap: ["Assistant Team Physio", "Head Team Physiotherapist", "Sports Rehab Center Director", "National Team Physio"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Neurological Physiotherapist",
        description: "Treat individuals with neurological conditions affecting the brain and spinal cord, such as stroke, multiple sclerosis, Parkinson's, and spinal cord injuries.",
        summary: "Specialists helping patients regain movement and function after brain or spinal injuries.",
        skills: ["Neuro-plasticity Knowledge", "Gait Training", "Extreme Patience", "Balance Therapy", "Handling Techniques (Bobath)"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $75K - $105K",
        educationPath: "BPT → MPT (Neurology)",
        yearsOfStudy: "4.5 to 6.5 Years",
        industriesHiring: ["Neuro-Rehab Centers", "Multi-Specialty Hospitals", "Stroke Units"],
        futureScope: "Growing steadily as medical advancements increase survival rates from severe strokes and neuro-traumas, necessitating long-term rehab.",
        jobDemandTrend: "Stable, High",
        governmentJobs: "Moderate in specialized neuro-centers.",
        freelanceOpportunities: "High. Massive demand for specialized home visits for paralyzed/stroke patients.",
        fieldWork: "Moderate. Home visits highly common.",
        riskLevel: "Low to Moderate (Emotional toll and physical lifting of paralyzed patients)",
        certifications: ["Neuro-Developmental Treatment (NDT) Certification"],
        internshipRequirements: "Clinical postings in neurology and neuro-surgery wards.",
        roadmap: ["Physiotherapist", "Neuro-Physiotherapist", "Lead Neuro-rehab Specialist", "Rehab Center Head"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Cardiopulmonary Physiotherapist",
        description: "Provide rehabilitation for patients suffering from cardiovascular and respiratory conditions (like COPD, asthma, heart attacks) to improve physical stamina.",
        summary: "Experts in respiratory and heart rehabilitation, working heavily in ICUs.",
        skills: ["Chest Physiotherapy", "Interpreting ECG/Vitals", "Airway Clearance Techniques", "Cardiac Rehab Programming"],
        salaryRange: "India: ₹3L - ₹8.5L | Global: $75K - $105K",
        educationPath: "BPT → MPT (Cardiothoracic / Cardiopulmonary)",
        yearsOfStudy: "4.5 to 6.5 Years",
        industriesHiring: ["Hospital ICUs", "Cardiac Care Centers", "Pulmonary Rehab Clinics"],
        futureScope: "Critical demand, massively increased post-COVID-19 due to the surge in long-term pulmonary complications.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High. Placed in infectious disease units and ICUs.",
        freelanceOpportunities: "Moderate. Post-discharge home cardiac rehabilitation.",
        fieldWork: "Low. Strictly hospital and ICU-based in acute stages.",
        riskLevel: "Moderate (Working in highly infectious environments like TB/COVID wards)",
        certifications: ["Basic and Advanced Life Support (BLS/ACLS)"],
        internshipRequirements: "Rigorous ICU rotations.",
        roadmap: ["ICU Physiotherapist", "Cardiopulmonary Specialist", "Head of Cardiac Rehab"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Pediatric Physiotherapist",
        description: "Specialize in the diagnosis, treatment, and management of infants, children, and adolescents with a variety of congenital, developmental, and acquired disorders.",
        summary: "Gentle specialists helping children with developmental or physical disabilities.",
        skills: ["Play Therapy", "Developmental Milestones Knowledge", "Patience", "Parent/Family Counseling", "Gentle Handling"],
        salaryRange: "India: ₹3.5L - ₹8L | Global: $70K - $100K",
        educationPath: "BPT → MPT (Pediatrics)",
        yearsOfStudy: "4.5 to 6.5 Years",
        industriesHiring: ["Children's Hospitals", "Special Education Schools", "Pediatric Clinics"],
        futureScope: "Stable and deeply rewarding. Early intervention programs are expanding globally.",
        jobDemandTrend: "Stable Growth",
        governmentJobs: "Roles in state child development and early intervention programs.",
        freelanceOpportunities: "High. Private pediatric therapy centers.",
        fieldWork: "Moderate. Visiting schools and specialized care centers.",
        riskLevel: "Low",
        certifications: ["Pediatric Clinical Specialist Certification"],
        internshipRequirements: "Rotations in NICU and pediatric wards.",
        roadmap: ["Junior PT", "Pediatric PT", "Early Intervention Coordinator", "Pediatric Rehab Director"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Geriatric Physiotherapist",
        description: "Focus on the complex needs of older adults, helping to maintain mobility, manage chronic joint pain (arthritis), and prevent devastating falls.",
        summary: "Experts dedicated to keeping the elderly mobile, safe, and pain-free.",
        skills: ["Fall Prevention Strategies", "Arthritis Management", "Patience", "Empathy", "Understanding Polypharmacy Effects"],
        salaryRange: "India: ₹3L - ₹7.5L | Global: $75K - $105K",
        educationPath: "BPT → MPT (Geriatrics)",
        yearsOfStudy: "4.5 to 6.5 Years",
        industriesHiring: ["Nursing Homes", "Assisted Living Facilities", "Home Health Agencies"],
        futureScope: "The fastest-growing physiotherapy specialty due to the massive global demographic shift toward an aging population.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "High in state-funded veteran or elderly care facilities.",
        freelanceOpportunities: "Maximum. Massive demand for regular home visits for elderly patients.",
        fieldWork: "High. Frequent travel to patients' homes or care facilities.",
        riskLevel: "Low",
        certifications: ["Geriatric Clinical Specialist Certification"],
        internshipRequirements: "Clinical rotations in nursing homes.",
        roadmap: ["Physiotherapist", "Geriatric Specialist", "Director of Rehab (Nursing Facility)", "Consultant"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Women's Health / Pelvic Floor Physiotherapist",
        description: "Specialize in treating conditions related to the female reproductive system, childbirth, and pelvic floor dysfunction (incontinence, pelvic pain).",
        summary: "Specialists in pre-and-post-natal care and pelvic floor rehabilitation.",
        skills: ["Pelvic Floor Assessment", "Prenatal/Postnatal Exercise Prescription", "Discretion & Empathy", "Manual Therapy"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $75K - $110K",
        educationPath: "BPT → MPT (Women's Health / OBGYN)",
        yearsOfStudy: "4.5 to 6.5 Years",
        industriesHiring: ["Maternity Hospitals", "Specialized Women's Clinics", "Private Practice"],
        futureScope: "Rapidly growing field as awareness regarding postpartum recovery and pelvic health increases globally.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Moderate in government maternity wards.",
        freelanceOpportunities: "Maximum. Highly successful as specialized private clinics.",
        fieldWork: "Low. Clinic-based.",
        riskLevel: "Low",
        certifications: ["Pelvic Rehabilitation Practitioner Certification (PRPC)"],
        internshipRequirements: "Rotations in OB/GYN wards.",
        roadmap: ["Physiotherapist", "Women's Health Specialist", "Clinic Owner", "Maternal Rehab Director"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Ergonomics Consultant / Occupational Physiotherapist",
        description: "Assess corporate workspaces to prevent repetitive strain injuries, improve employee posture, and design safer, more efficient physical work environments.",
        summary: "Consultants hired by corporations to optimize workspace setups and prevent employee injuries.",
        skills: ["Biomechanical Assessment", "Corporate Workflow Analysis", "Presentation Skills", "Preventive Physiology"],
        salaryRange: "India: ₹5L - ₹12L | Global: $80K - $120K",
        educationPath: "BPT → Diploma/Certification in Ergonomics or Occupational Health",
        yearsOfStudy: "4.5 to 5.5 Years",
        industriesHiring: ["IT/Corporate Sectors", "Manufacturing Plants", "Ergonomic Consulting Firms"],
        futureScope: "Extremely lucrative niche. Tech companies aggressively hire ergonomists to prevent costly employee medical leaves due to poor posture.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Low. Primarily a corporate sector role.",
        freelanceOpportunities: "Maximum. Function entirely as independent consultants charging premium corporate rates.",
        fieldWork: "High. Traveling aggressively between corporate offices and factories.",
        riskLevel: "Low",
        certifications: ["Certified Professional Ergonomist (CPE)"],
        internshipRequirements: "Shadowing industrial hygienists or ergonomists.",
        roadmap: ["Physiotherapist", "Ergonomics Assessor", "Corporate Health Consultant", "Lead Corporate Ergonomist"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Oncology Physiotherapist",
        description: "Assist cancer patients in recovering strength, mobility, and managing side effects (like lymphedema) caused by surgery, radiation, and chemotherapy.",
        summary: "Rehab specialists helping cancer survivors regain physical autonomy.",
        skills: ["Lymphedema Drainage Techniques", "Fatigue Management", "Deep Empathy", "Understanding Oncology Contraindications"],
        salaryRange: "India: ₹3.5L - ₹8.5L | Global: $75K - $105K",
        educationPath: "BPT → Specialized Oncology Rehab Certification",
        yearsOfStudy: "4.5 to 5.5 Years",
        industriesHiring: ["Cancer Research Hospitals", "Palliative Care Centers", "Outpatient Rehab Clinics"],
        futureScope: "Growing steadily as cancer survival rates increase, shifting focus to the long-term quality of life for survivors.",
        jobDemandTrend: "Growing",
        governmentJobs: "Roles in national cancer institutes.",
        freelanceOpportunities: "Moderate. Home-based palliative care.",
        fieldWork: "Low.",
        riskLevel: "Low (High emotional toll)",
        certifications: ["Certified Lymphedema Therapist (CLT)"],
        internshipRequirements: "Clinical hours in oncology wards.",
        roadmap: ["Physiotherapist", "Lymphedema Specialist", "Oncology Rehab Director"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Vestibular Rehabilitation Specialist",
        description: "Diagnose and treat dizziness, vertigo, and balance disorders caused by inner ear deficits or central nervous system issues.",
        summary: "Niche experts treating vertigo and complex balance disorders.",
        skills: ["Canalith Repositioning Maneuvers", "Gaze Stabilization Training", "Detailed Neurological Assessment", "Patience"],
        salaryRange: "India: ₹4L - ₹10L | Global: $80K - $115K",
        educationPath: "BPT → Vestibular Rehabilitation Certification / MPT (Neurology)",
        yearsOfStudy: "4.5 to 6 Years",
        industriesHiring: ["ENT Clinics", "Neurology Centers", "Specialized Balance Clinics"],
        futureScope: "A highly specialized, low-competition niche. Vertigo is incredibly common yet severely under-treated.",
        jobDemandTrend: "High Niche Demand",
        governmentJobs: "Low.",
        freelanceOpportunities: "High. Consulting across multiple ENT clinics.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["Vestibular Rehabilitation Certification"],
        internshipRequirements: "Shadowing neuro-otologists or vestibular therapists.",
        roadmap: ["Physiotherapist", "Vestibular Therapist", "Director of Balance Clinic"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Burn and Plastic Surgery Physiotherapist",
        description: "Provide immediate and long-term care to patients with severe burns, focusing on preventing contractures, mobilizing scar tissue, and maintaining joint range of motion.",
        summary: "Specialists ensuring burn victims and plastic surgery patients retain joint mobility as skin heals.",
        skills: ["Scar Tissue Mobilization", "Splinting", "Pain Management", "Infection Control Protocols", "Extreme Emotional Resilience"],
        salaryRange: "India: ₹3.5L - ₹8L | Global: $70K - $100K",
        educationPath: "BPT → Advanced training in Burn / Plastic Surgery Rehab",
        yearsOfStudy: "4.5 to 5 Years",
        industriesHiring: ["Burn Units in General Hospitals", "Plastic & Reconstructive Surgery Centers"],
        futureScope: "Crucial specialty. Highly specialized and demanding, ensuring job security in major trauma and cosmetic centers.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Primary role in massive government trauma centers with burn units.",
        freelanceOpportunities: "Low. Highly hospital-dependent.",
        fieldWork: "Low.",
        riskLevel: "Moderate (High emotional trauma, strict sterile environments required)",
        certifications: ["Wound Care Certification (Optional but helpful)"],
        internshipRequirements: "Rigorous postings in burn ICUs.",
        roadmap: ["Physiotherapist", "Burn Unit Therapist", "Lead Reconstructive Rehab Specialist"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Aquatic Physiotherapist (Hydrotherapist)",
        description: "Conduct rehabilitation sessions in specialized heated pools, utilizing the buoyancy and resistance of water to treat patients who cannot tolerate land-based exercises.",
        summary: "Therapists executing zero-impact rehabilitation programs in aquatic environments.",
        skills: ["Water Safety/Lifesaving", "Hydrodynamics Principles", "Creative Exercise Adaptation", "Physical Stamina in Water"],
        salaryRange: "India: ₹3.5L - ₹9L | Global: $75K - $105K",
        educationPath: "BPT → Certificate in Aquatic Physical Therapy",
        yearsOfStudy: "4.5 to 5 Years",
        industriesHiring: ["High-end Sports Rehab Centers", "Spinal Cord Injury Centers", "Specialized Hydrotherapy Clinics"],
        futureScope: "Growing as a premium service for severe arthritis, complex trauma, and elite athletes.",
        jobDemandTrend: "Growing",
        governmentJobs: "Low.",
        freelanceOpportunities: "Moderate. Requires access to specialized clinic pools.",
        fieldWork: "Low.",
        riskLevel: "Low (Physical stamina required for prolonged periods in warm water)",
        certifications: ["Aquatic Therapy & Rehab Institute Certification (ATRIC)"],
        internshipRequirements: "Training specifically in clinical hydrotherapy pools.",
        roadmap: ["Physiotherapist", "Aquatic Therapist", "Hydrotherapy Center Director"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Veterinary Physiotherapist",
        description: "Apply physical therapy techniques to animals (primarily horses and dogs) recovering from surgery, injuries, or suffering from degenerative diseases.",
        summary: "Niche practitioners rehabilitating animals, primarily sports horses and pets.",
        skills: ["Animal Anatomy/Biomechanics", "Animal Handling/Safety", "Observational Diagnostics (animals can't speak)", "Manual Therapy"],
        salaryRange: "India: ₹3L - ₹8L | Global: $60K - $90K",
        educationPath: "BPT / B.V.Sc → Post-Graduate Diploma in Veterinary Physiotherapy",
        yearsOfStudy: "5.5 to 6.5 Years",
        industriesHiring: ["Equine/Equestrian Centers", "Veterinary Hospitals", "Veterinary Rehab Clinics"],
        futureScope: "Extremely rapid growth. Pet owners are spending more than ever on advanced medical care for animals.",
        jobDemandTrend: "Explosive Growth (Niche)",
        governmentJobs: "Low. Sometimes military/police canine units.",
        freelanceOpportunities: "Maximum. Operating a mobile veterinary rehab service is highly popular.",
        fieldWork: "Maximum. Traveling to farms, stables, and client homes.",
        riskLevel: "Moderate (Risk of injury from handling large or frightened animals)",
        certifications: ["Certified Canine Rehabilitation Practitioner (CCRP)"],
        internshipRequirements: "Shadowing experienced animal rehab specialists.",
        roadmap: ["Physiotherapist", "Animal Rehab Certification", "Veterinary Physiotherapist", "Equine Rehab Center Owner"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Academic / Research Physiotherapist",
        description: "Focus on teaching the next generation of physiotherapists in universities and conducting clinical trials to validate new, evidence-based physical therapy techniques.",
        summary: "The professors and scientists advancing the field of physical therapy through research.",
        skills: ["Research Methodology", "Data Analytics", "Grant Writing", "Didactic Teaching", "Evidence-Based Practice Validation"],
        salaryRange: "India: ₹6L - ₹15L | Global: $80K - $120K",
        educationPath: "BPT → MPT → Ph.D. in Physiotherapy/Rehabilitation Sciences",
        yearsOfStudy: "8.5 to 10+ Years",
        industriesHiring: ["Universities", "Medical Research Institutes", "Health Policy Organizations"],
        futureScope: "Critical for the elevation of the profession. As physiotherapy seeks greater autonomy globally, rigorous academic research is mandatory.",
        jobDemandTrend: "Stable",
        governmentJobs: "High. Professorships at state-run medical colleges.",
        freelanceOpportunities: "Moderate. Consulting on ergonomics or clinical trial designs.",
        fieldWork: "Low. Academic/Lab based.",
        riskLevel: "Low",
        certifications: ["Ph.D. / Academic publications"],
        internshipRequirements: "Extensive clinical experience before entering academia.",
        roadmap: ["Clinical PT", "Assistant Professor", "Principal Investigator", "Dean of Physiotherapy School"]
    },
    {
        domain: "Medical",
        branch: "Physiotherapy",
        title: "Tele-Rehabilitation Physiotherapist",
        description: "Assess, diagnose, and guide patients through physical therapy regimens entirely via specialized video conferencing and wearable sensor technology.",
        summary: "Digital-first physiotherapists providing remote rehabilitation across the globe.",
        skills: ["Digital Communication", "Triage via Video", "Wearable Tech Integration", "Clear Verbal Exercise Instruction", "Software Aptitude"],
        salaryRange: "India: ₹4L - ₹10L | Global: $70K - $100K",
        educationPath: "BPT → Clinical Experience → Telehealth Certification",
        yearsOfStudy: "4.5 Years",
        industriesHiring: ["Telehealth Startups", "Large Hospital Networks", "Digital Health Platforms"],
        futureScope: "Explosive. Post-pandemic, tele-rehab has proven effective for basic musculoskeletal issues, drastically expanding the geographical reach of a therapist.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. The ultimate geographic freedom for an independent practitioner.",
        fieldWork: "Low. Entirely remote/home-office based.",
        riskLevel: "Low",
        certifications: ["Telehealth/Telemedicine Certifications"],
        internshipRequirements: "Strong foundational clinical experience in-person is strictly required first.",
        roadmap: ["Clinical PT", "Tele-health Consultant", "Digital Rehab Program Manager", "Tele-Rehab Startup Founder"]
    }
];

const seedPhysiotherapy = async () => {
    try {
        await Career.deleteMany({ branch: "Physiotherapy" });
        await Career.insertMany(physiotherapyProfessions);
        console.log('Physiotherapy Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedPhysiotherapy();
