const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const constitutionalLawProfessions = [
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Constitutional Lawyer",
        description: "Specializes in the interpretation, application, and defense of the national constitution. They handle cases where fundamental rights are violated by the state or where governmental authority exceeds its constitutional limits.",
        educationPath: "LLB -> LLM in Constitutional Law",
        competitiveExams: ["CLAT", "AILET", "State Law Entrance Exams"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Constitutional Interpretation", "Writ Jurisdiction (Art. 32/226)", "Appellate Advocacy", "Jurisprudential Synthesis"],
        salaryRange: "India: ₹6 LPA - ₹40+ LPA | Global: $80,000 - $250,000+ per year",
        roadmap: ["High Court Practitioner", "Constitutional Litigator", "Senior Advocate", "Constitutional Expert"],
        supremeCourtHighCourtOpportunities: "Practices almost exclusively in the High Courts and the Supreme Court.",
        governmentJobs: "Appointed as Advocate General or Attorney General.",
        policyLegislativeOpportunities: "Frequently consulted on massive national policy shifts to ensure constitutional validity.",
        workNature: "Elite Courtroom Litigation, Filing Writ Petitions & High-Level Advisory.",
        riskLevel: "Low to Moderate",
        futureScope: "Extremely prestigious. As governments rapidly enact modern laws (surveillance, data, citizenship), testing these against the constitution is a permanent, high-demand field.",
        jobDemandTrend: "Stable and Highly Respected",
        summary: "The ultimate defenders of civil liberties, actively restricting the overreach of the state through high-level constitutional litigation."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Supreme Court Advocate",
        description: "A highly specialized litigator practicing exclusively at the highest judicial forum. They do not handle trials or facts; they argue purely on questions of law and constitutional validity to overturn lower court judgments.",
        educationPath: "LLB -> LLM",
        competitiveExams: ["Advocate-on-Record (AOR) Exam"],
        yearsOfStudy: "5 Years + 5+ Years Litigation + AOR Certification",
        certifications: ["AOR Designation (Mandatory for filing in SC)", "Bar Council Enrollment"],
        skills: ["Apex Court Procedures", "Special Leave Petitions (SLP)", "Flawless Legal Drafting", "Persuasive Argumentation"],
        salaryRange: "India: ₹15 LPA - ₹1 Crore+ | Global: N/A (Highly specific to national apex courts)",
        roadmap: ["Junior to AOR", "Advocate-on-Record", "Independent Apex Practitioner", "Designated Senior Advocate"],
        supremeCourtHighCourtOpportunities: "100% focused on Supreme Court litigation.",
        governmentJobs: "Empanelled as Additional Solicitor General (ASG).",
        policyLegislativeOpportunities: "Directly shapes national law through landmark Supreme Court rulings.",
        workNature: "Intense Apex Court Arguments & Drafting Complex Appellate Briefs.",
        riskLevel: "Low",
        futureScope: "The absolute pinnacle of the legal profession. Supreme Court advocates are the highest-paid and most respected litigators in the country.",
        jobDemandTrend: "Elite Niche",
        summary: "The titans of the courtroom, arguing the final, absolute legal appeals that set binding precedents for the entire nation."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Constitutional Litigation Specialist",
        description: "Hired by massive corporations or political entities to specifically challenge the constitutionality of new government regulations, tax levies, or industrial bans that threaten their operations.",
        educationPath: "LLB -> LLM in Public Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Regulatory Law", "Constitutional Torts", "Corporate Defense Strategy", "Writ Drafting"],
        salaryRange: "India: ₹10 LPA - ₹50+ LPA | Global: $120,000 - $350,000+ per year",
        roadmap: ["Associate Specialist", "Senior Constitutional Litigator", "Partner - Public Law", "Senior Counsel"],
        supremeCourtHighCourtOpportunities: "Primary battlegrounds are High Courts (challenging state action) and the Supreme Court.",
        governmentJobs: "Hired as special counsel to defend the government against corporate writs.",
        policyLegislativeOpportunities: "Advising corporations on how to legally circumvent or challenge new bureaucratic red tape.",
        workNature: "High-Stakes Corporate Litigation vs. The State.",
        riskLevel: "Moderate",
        futureScope: "Extremely lucrative. As governments heavily regulate tech, AI, and finance, corporations require elite constitutionalists to strike down restrictive laws.",
        jobDemandTrend: "Very High among MNCs",
        summary: "The elite corporate shield against government overreach, using constitutional writs to protect multi-billion dollar industries."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Public Interest Litigation (PIL) Lawyer",
        description: "Uses the power of the constitution to file massive class-action lawsuits on behalf of the public or marginalized groups regarding environmental destruction, government corruption, or human rights violations.",
        educationPath: "LLB",
        competitiveExams: ["CLAT / State Exams"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Activism", "Social Justice Jurisprudence", "Media Management", "Drafting PILs"],
        salaryRange: "India: ₹3 LPA - ₹15 LPA | Global: $50,000 - $100,000 per year",
        roadmap: ["NGO Litigator", "Independent PIL Advocate", "Public Rights Champion", "Senior Advocate / Policy Maker"],
        supremeCourtHighCourtOpportunities: "PILs are exclusively filed in High Courts (Art. 226) and Supreme Court (Art. 32).",
        governmentJobs: "Consulted by human rights commissions.",
        policyLegislativeOpportunities: "Successful PILs force the government to instantly draft new protective legislation.",
        workNature: "Courtroom Activism, Legal Research & Media Interaction.",
        riskLevel: "High (Fighting powerful political and corporate syndicates)",
        futureScope: "The most powerful tool for rapid social change. High-profile PIL lawyers frequently become national figures and policy architects.",
        jobDemandTrend: "High Impact / Niche Earnings",
        summary: "A courtroom activist wielding the constitution to fight systemic corruption and protect the fundamental rights of the masses."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Human Rights Constitutional Lawyer",
        description: "Operates at the intersection of domestic constitutional law and international human rights law. They defend victims of state-sponsored violence, illegal detention, and mass discrimination.",
        educationPath: "LLB -> LLM in Human Rights",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment", "International Humanitarian Law Diplomas"],
        skills: ["Habeas Corpus Writs", "International Treaties", "Trauma Counseling", "Advocacy"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $60,000 - $120,000 per year",
        roadmap: ["Human Rights Fellow", "NGO Legal Head", "Independent Counsel", "UN Representative"],
        supremeCourtHighCourtOpportunities: "Intense daily practice filing urgent writs to protect life and liberty.",
        governmentJobs: "Roles within the National Human Rights Commission (NHRC).",
        policyLegislativeOpportunities: "Drafting shadow reports for UN bodies regarding constitutional violations in the country.",
        workNature: "High-Stress Litigation, Field Interviews & International Advocacy.",
        riskLevel: "High",
        futureScope: "Crucial and constantly necessary. With rising global authoritarianism, the demand for lawyers willing to enforce constitutional human rights is peaking.",
        jobDemandTrend: "Stable (NGO/Institutional driven)",
        summary: "The ultimate guardians of human dignity, fighting the state to prevent illegal arrests, torture, and systemic discrimination."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Constitutional Legal Advisor",
        description: "Provides highly sensitive, out-of-court strategic counsel to political parties, Chief Ministers, or state governors regarding the constitutional legality of their executive decisions, preventing political crises.",
        educationPath: "LLB -> extensive political/legal experience",
        competitiveExams: ["None specifically required"],
        yearsOfStudy: "5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Political Strategy", "Deep Constitutional Precedents", "Executive Power Limits", "Crisis Management"],
        salaryRange: "India: ₹12 LPA - ₹40 LPA | Global: $100,000 - $250,000 per year",
        roadmap: ["Political Legal Aide", "Senior Advisor", "Chief Legal Counsel to State", "Attorney General"],
        supremeCourtHighCourtOpportunities: "Minimal courtroom appearances; entirely strategic advisory.",
        governmentJobs: "Appointed as OSD (Officer on Special Duty) or Legal Advisor to Chief Ministers/Governors.",
        policyLegislativeOpportunities: "Directly involved in architecting state-level ordinances and executive orders.",
        workNature: "High-Level Advisory, Political Strategy & Crisis De-escalation.",
        riskLevel: "Low",
        futureScope: "An incredibly powerful shadow role. Political parties heavily rely on constitutional advisors to navigate defection laws and state-center conflicts.",
        jobDemandTrend: "Elite / Highly Connected",
        summary: "The strategic brain behind political leaders, ensuring every massive executive action survives constitutional scrutiny."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Government Constitutional Advisor",
        description: "A formal bureaucratic position representing the highest echelon of state legal service. They advise the reigning government on drafting new bills, ensuring they do not violate the constitution and trigger Supreme Court strikes.",
        educationPath: "LLB -> Judicial Services / UPSC (Legal)",
        competitiveExams: ["UPSC (Indian Legal Service) / State PSC"],
        yearsOfStudy: "5 Years",
        certifications: ["Government Gazetted Officer"],
        skills: ["Legislative Drafting", "Constitutional Validity", "Bureaucratic Procedures", "Administrative Law"],
        salaryRange: "India: ₹10 LPA - ₹25 LPA (+ Massive Gov Perks) | Global: $80,000 - $160,000 per year",
        roadmap: ["Assistant Legal Advisor", "Deputy Secretary (Legal)", "Joint Secretary", "Law Secretary of India"],
        supremeCourtHighCourtOpportunities: "Coordinates with the Solicitor General for defending government policies in court.",
        governmentJobs: "100% Core Government Role (Ministry of Law & Justice).",
        policyLegislativeOpportunities: "They are the literal authors of the nation's new laws and amendments.",
        workNature: "Bureaucratic Drafting, Policy Auditing & Cabinet Advising.",
        riskLevel: "Low",
        futureScope: "A permanent, highly prestigious pillar of the government. They are the quality-control mechanism for all national legislation.",
        jobDemandTrend: "Stable (Government intake)",
        summary: "The quiet bureaucratic powerhouses who read, draft, and modify every single law before it is passed by Parliament."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Constitutional Law Researcher",
        description: "Attached to Supreme Court judges or elite think-tanks. They synthesize thousands of pages of historical constituent assembly debates, foreign constitutions, and global precedents to help formulate landmark apex judgments.",
        educationPath: "LLB -> LLM in Constitutional Law",
        competitiveExams: ["CLAT (PG) / Supreme Court Clerkship Exam"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Comparative Constitutional Law", "Jurisprudence", "Speed Synthesis", "Flawless Academic Writing"],
        salaryRange: "India: ₹6 LPA - ₹15 LPA | Global: $70,000 - $120,000 per year",
        roadmap: ["Judicial Clerk", "Senior Research Fellow", "Think-Tank Director", "Constitutional Scholar"],
        supremeCourtHighCourtOpportunities: "Works physically inside the chambers of Supreme Court and High Court judges.",
        governmentJobs: "Empanelled as official researchers for Law Commission of India.",
        policyLegislativeOpportunities: "Their research notes directly form the basis of massive multi-judge bench rulings.",
        workNature: "Pure Elite Legal Research & Academic Drafting.",
        riskLevel: "Low",
        futureScope: "The ultimate launching pad. A clerkship under a Supreme Court judge is the most coveted credential before entering high-level constitutional litigation.",
        jobDemandTrend: "Highly Competitive",
        summary: "The intellectual researchers finding the obscure precedents that tip the scales in massive, nation-changing constitutional cases."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Legislative Consultant",
        description: "Hired by parliamentarians, senators, or lobbying firms to draft private member bills, analyze the loopholes in upcoming government legislation, and lobby for constitutional amendments favoring specific industries.",
        educationPath: "LLB / Public Policy Masters",
        competitiveExams: ["None"],
        yearsOfStudy: "4 to 5 Years",
        certifications: ["Legislative Drafting Diplomas"],
        skills: ["Lobbying", "Policy Analysis", "Statutory Design", "Political Networking"],
        salaryRange: "India: ₹8 LPA - ₹20+ LPA | Global: $90,000 - $200,000+ per year",
        roadmap: ["Legislative Assistant (LAMP Fellow)", "Policy Consultant", "Chief Lobbyist", "Elected Representative (Optional)"],
        supremeCourtHighCourtOpportunities: "None. Entirely focused on the legislature (Parliament/State Assemblies).",
        governmentJobs: "Consultants to Parliamentary Standing Committees.",
        policyLegislativeOpportunities: "The absolute core of the job—influencing the physical drafting of national policy.",
        workNature: "Political Advising, Bill Drafting & High-Level Lobbying.",
        riskLevel: "Low",
        futureScope: "Exploding demand. As laws become increasingly complex (e.g., AI regulation, Data Privacy), politicians desperately need specialized lawyers to write the bills.",
        jobDemandTrend: "Growing Rapidly",
        summary: "A powerful hybrid of law and politics, drafting the laws and influencing the politicians inside the halls of Parliament."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Constitutional Policy Analyst",
        description: "Works for massive think tanks, NGOs, or media houses. They break down hyper-complex Supreme Court judgments and new government amendments for the public, explaining their macroeconomic and constitutional impact.",
        educationPath: "LLB / Masters in Public Administration",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Journalism/Public Policy Certifications"],
        skills: ["Data Synthesis", "Constitutional Demystification", "Public Speaking", "Op-Ed Writing"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $65,000 - $130,000 per year",
        roadmap: ["Policy Analyst", "Senior Media Commentator", "Think-Tank Head", "Public Intellectual"],
        supremeCourtHighCourtOpportunities: "None directly; they analyze what happens in the courts for public consumption.",
        governmentJobs: "Consulted occasionally by policy-forming agencies.",
        policyLegislativeOpportunities: "Shapes public opinion through media architectures, forcing legislative shifts.",
        workNature: "Media Commentary, Academic Analysis & Public Policy Demystification.",
        riskLevel: "Low",
        futureScope: "High relevance in the information age. Translating apex court jargon into understandable public consequences is highly monetizable.",
        jobDemandTrend: "Stable",
        summary: "The public intellectual translating complex constitutional crises and apex judgments into digestible, actionable data for the masses."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Constitutional Law Professor",
        description: "The intellectual foundation of the legal system. They teach the nuances of fundamental rights, state powers, and landmark judgments to aspiring lawyers at elite universities, while publishing influential legal treatises.",
        educationPath: "LLB -> LLM -> Ph.D. in Constitutional Law",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Academic Mentorship", "Deep Historical Precedents", "Jurisprudential Debate", "Publishing"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $80,000 - $180,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean of Law School"],
        supremeCourtHighCourtOpportunities: "Frequently called upon by the Supreme Court as 'Amicus Curiae' (Friend of the Court) to assist in complex constitutional matters.",
        governmentJobs: "Permanent faculty in National Law Universities.",
        policyLegislativeOpportunities: "Their academic papers heavily influence how judges interpret ambiguous constitutional clauses.",
        workNature: "Teaching, Mentoring & Elite Academic Publishing.",
        riskLevel: "Low",
        futureScope: "Incredibly prestigious. The top professors of Constitutional law are considered the ultimate authorities on the subject, surpassing even senior advocates.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The elite academics who teach the constitution to the lawyers, and advise the judges who interpret it."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Legal Scholar in Constitutional Studies",
        description: "A pure academic who devotes their life to comparing global constitutions. They write massive theoretical books addressing the flaws in democratic structures and propose entirely new frameworks for human governance.",
        educationPath: "LLB -> LLM -> Ph.D. (Often foreign universities)",
        competitiveExams: ["GRE / Global Ph.D. Entrances"],
        yearsOfStudy: "8 to 10 Years",
        certifications: ["Post-Doctoral Fellowships"],
        skills: ["Comparative Global Law", "Political Philosophy", "Macro-System Design", "Book Authoring"],
        salaryRange: "India: ₹8 LPA - ₹20 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Research Fellow", "Author / Academic", "Global Policy Advisor", "International Fellow"],
        supremeCourtHighCourtOpportunities: "None directly.",
        governmentJobs: "Advising foreign nations drafting new constitutions post-revolution or independence.",
        policyLegislativeOpportunities: "Their theories shape macro-level international democratic developments.",
        workNature: "Pure Research, Philosophy & Elite Academics.",
        riskLevel: "Low",
        futureScope: "A highly esoteric but deeply respected field. Constitutional scholars are the architects of modern democratic theories.",
        jobDemandTrend: "Niche Academic",
        summary: "The philosopher-lawyers comparing global democracies to write the definitive textbooks on human governance."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Judicial Clerk (Supreme Court / High Court)",
        description: "An elite stepping-stone role for fresh law graduates. They are assigned directly to a High Court or Supreme Court Judge to assist them in researching precedents and writing the first drafts of massive judgments.",
        educationPath: "LLB",
        competitiveExams: ["Supreme Court / High Court Registry Clerkship Exams"],
        yearsOfStudy: "5 Years",
        certifications: ["None mandatory"],
        skills: ["Extreme Work Ethic", "Flawless Research", "Drafting Opinions", "Confidentiality"],
        salaryRange: "India: ₹6 LPA - ₹10 LPA (Stipend) | Global: $60,000 - $120,000 per year",
        roadmap: ["Judicial Clerk (1-2 Years)", "High Court Litigator", "AOR / Supreme Court Counsel", "Elevation to Judiciary"],
        supremeCourtHighCourtOpportunities: "Works directly alongside the highest judges in the nation every single day.",
        governmentJobs: "Official registry employee during the tenure of the clerkship.",
        policyLegislativeOpportunities: "They write the research memos that directly influence binding national case law.",
        workNature: "Chamber Assistance, Research & Judgment Drafting.",
        riskLevel: "Low",
        futureScope: "The most prestigious launchpad for a young lawyer. Former clerks usually become the most successful Supreme Court advocates in the country.",
        jobDemandTrend: "Hyper-Competitive",
        summary: "An incredibly prestigious apprenticeship, learning the mind of a judge by helping them write the nation's most important rulings."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Public Law Consultant",
        description: "A private consultant hired by massive infrastructure companies (like telecom or mining giants) to navigate the intense constitutional and administrative law requirements needed to secure multi-billion dollar government tenders.",
        educationPath: "LLB -> LLM in Administrative Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Government Contract Diplomas"],
        skills: ["Administrative Law", "Tender Mechanics", "Constitutional Writs", "Corporate Lobbying"],
        salaryRange: "India: ₹10 LPA - ₹30+ LPA | Global: $100,000 - $250,000 per year",
        roadmap: ["Consulting Associate", "Senior Administrative Counsel", "Partner - Public Law", "Chief Strategy Officer"],
        supremeCourtHighCourtOpportunities: "Often files writs in the High Court when government tenders are arbitrarily cancelled.",
        governmentJobs: "Frequent interactions with massive PSUs and central ministries.",
        policyLegislativeOpportunities: "Ensures that massive corporate-government partnerships are constitutionally sound.",
        workNature: "Corporate-Gov Strategy, Tender Drafting & High Court Litigation.",
        riskLevel: "Moderate",
        futureScope: "Extremely lucrative. Any corporation dealing with the government requires public law experts to prevent the state from arbitrarily seizing assets or canceling contracts.",
        jobDemandTrend: "High in Corporate Sector",
        summary: "The strategic liaison protecting massive private corporations from the unpredictable constitutional actions of the state."
    },
    {
        domain: "Law",
        branch: "Constitutional Law",
        title: "Constitutional Case Analyst",
        description: "An incredibly specialized role within elite Supreme Court Chambers. They strip down 10,000-page appeals into 10-page executive summaries, highlighting the exact constitutional loopholes the Senior Advocate must attack in court.",
        educationPath: "LLB",
        competitiveExams: ["None"],
        yearsOfStudy: "5 Years",
        certifications: ["None mandatory"],
        skills: ["Speed Information Processing", "Loophole Identification", "Briefing Seniors", "Supreme Court Rules Mastery"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $70,000 - $130,000 per year",
        roadmap: ["Junior Analyst", "Senior Chamber Briefer", "Arguing Counsel", "Designated Senior Advocate"],
        supremeCourtHighCourtOpportunities: "Operates deep within the chambers of the country's most famous Supreme Court litigators.",
        governmentJobs: "None.",
        policyLegislativeOpportunities: "N/A",
        workNature: "Intense Desk Analysis, Speed Reading & Chamber Briefings.",
        riskLevel: "Low",
        futureScope: "The invisible brains behind the 15-minute fiery arguments made by Senior Advocates in the Supreme Court. A vital role for those who prefer strategy over public speaking.",
        jobDemandTrend: "Stable within Elite Circles",
        summary: "A pure strategist who digests mountains of constitutional data so the lead litigator can execute the final, lethal argument in court."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Constitutional Law" });
        await Career.insertMany(constitutionalLawProfessions);
        console.log('Constitutional Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
