const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const labourLawProfessions = [
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Labour Lawyer",
        description: "The traditional courtroom advocate for the working class. They handle disputes arising under the Industrial Disputes Act, representing either the factory management or the blue-collar workers regarding strikes, lockouts, and illegal terminations.",
        educationPath: "LLB",
        competitiveExams: ["State law entrances / CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment (Mandatory)"],
        skills: ["Industrial Disputes Act Mastery", "Vernacular Fluency", "Trade Union Negotiation", "Labour Court Litigation"],
        salaryRange: "India: ₹3 LPA - ₹15 LPA | Global: $50,000 - $120,000 per year",
        roadmap: ["Junior Labour Advocate", "Independent Practitioner", "Union Counsel", "Senior Labour Court Advocate"],
        courtPracticeOpportunities: "Daily practice in highly specialized Labour Courts and Industrial Tribunals.",
        governmentJobs: "Appointed to state-run free legal aid clinics for impoverished workers.",
        corporateOpportunities: "Hired by manufacturing plants to defend against mass worker lawsuits.",
        workNature: "High-Volume Tribunal Argumentation, Conciliation Meetings & Drafting Claims.",
        futureScope: "A permanent necessity, particularly in developing nations heavily reliant on massive blue-collar manufacturing workforces.",
        jobDemandTrend: "Stable Volume / Highly Localized",
        summary: "The grassroots litigator navigating the chaotic industrial tribunals to resolve mass-employment disputes and strikes."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Employment Lawyer",
        description: "The 'White-Collar' equivalent of a labour lawyer. They manage complex executive contracts, non-compete clauses, sexual harassment (POSH) claims, and massive corporate severance packages.",
        educationPath: "LLB -> LLM in Employment/Corporate Law",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Executive Contract Drafting", "Non-Compete Enforcement", "POSH Compliance", "Corporate Mediation"],
        salaryRange: "India: ₹8 LPA - ₹35 LPA | Global: $90,000 - $250,000 per year",
        roadmap: ["Employment Associate", "Senior Corporate Counsel", "Partner - Employment Practice", "General Counsel"],
        courtPracticeOpportunities: "Litigates in High Courts and Civil Courts rather than traditional Labour Tribunals.",
        governmentJobs: "Minimal.",
        corporateOpportunities: "Practiced extensively by Tier-1 corporate law firms advising multi-national companies.",
        workNature: "High-Stakes Contract Negotiation, Advisory & Corporate Litigation.",
        futureScope: "Extremely lucrative. As the gig economy and remote-work create complex white-collar legal ambiguities, specialized employment lawyers are in immense demand by tech and finance sectors.",
        jobDemandTrend: "Very High Demand",
        summary: "The sophisticated legal strategists handling complex executive contracts, corporate restructuring, and high-value non-compete litigations."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Industrial Relations Lawyer",
        description: "Focuses on the incredibly delicate balance of power between factory management and massive organized trade unions. They orchestrate massive collective bargaining agreements affecting thousands of workers.",
        educationPath: "LLB -> MBA in HR / MSW (Social Work)",
        competitiveExams: ["CLAT / TISSNET"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Labour Welfare Diplomas"],
        skills: ["Collective Bargaining", "Strike De-escalation", "Trade Union Act", "Mass Crisis Negotiation"],
        salaryRange: "India: ₹5 LPA - ₹25 LPA | Global: $70,000 - $160,000 per year",
        roadmap: ["IR Officer", "Senior IR Legal Counsel", "VP of Industrial Relations", "Chief HR/Legal Officer"],
        courtPracticeOpportunities: "Only intervenes in court if the pre-litigation collective bargaining collapses.",
        governmentJobs: "Advising massive Public Sector Undertakings (e.g., Indian Railways, BSNL) on union appeasement.",
        corporateOpportunities: "Massive reliance by heavy industries (Steel, Auto, Mining) to prevent crippling factory strikes.",
        workNature: "Intense Union Negotiation, Desk Drafting & Boardroom De-escalation.",
        futureScope: "Critical for manufacturing economies. A single day of a massive factory strike costs millions; a flawless IR lawyer is a multi-million dollar insurance policy for the corporation.",
        jobDemandTrend: "Stable within Manufacturing",
        summary: "The master negotiators maintaining peace between corporate management and aggressive trade unions to prevent catastrophic industrial strikes."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Workplace Compliance Lawyer",
        description: "Operates exclusively out of court to ensure the company perfectly obeys the hundreds of overlapping national and state labor laws (Minimum Wage, Provident Fund, Gratuity, Maternity Benefits) to prevent government raids.",
        educationPath: "LLB -> CS (Company Secretary) or LLM",
        competitiveExams: ["None required for practice"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Statutory Compliance Certifications"],
        skills: ["Deep Statutory Auditing", "Provident Fund / ESI Laws", "Due Diligence", "Detail Orientation"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $75,000 - $140,000 per year",
        roadmap: ["Compliance Analyst", "Compliance Manager", "Director of HR Legal", "Chief Compliance Officer"],
        courtPracticeOpportunities: "Zero. If they go to court, it means they failed their preventative job.",
        governmentJobs: "Appointed as Labour Inspectors to raid non-compliant factories.",
        corporateOpportunities: "Guaranteed employment in every single mid-to-large corporation. HR departments cannot function legally without them.",
        workNature: "Desk Auditing, Internal Policymaking & Government Filing.",
        futureScope: "Highly secure and recession-proof. Regardless of economic downturns, government labour compliance must be filed flawlessly every single month.",
        jobDemandTrend: "High and Constant",
        summary: "The meticulous internal auditors ensuring corporations rigorously follow complex national wage and benefit laws, completely avoiding government lawsuits."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "HR Legal Advisor",
        description: "The internal legal brain of the Human Resources department. They do not calculate payroll; they draft the legal policies for remote work, frame the criteria for mass-layoffs to avoid lawsuits, and mediate internal toxic workplace disputes.",
        educationPath: "BBA/MBA in HR -> LLB",
        competitiveExams: ["Management Entrances -> Law Entrances"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["SHRM Certified Professional (Optional)"],
        skills: ["Severance Risk Assessment", "Policy Formulation", "Internal Mediation", "Corporate Governance"],
        salaryRange: "India: ₹7 LPA - ₹25 LPA | Global: $80,000 - $170,000 per year",
        roadmap: ["HR Executive", "HR Legal Manager", "VP of Human Resources", "Chief People Officer (CPO)"],
        courtPracticeOpportunities: "None. Strictly a corporate desk and boardroom advisory role.",
        governmentJobs: "Advising the government on modernization of civil servant employment policies.",
        corporateOpportunities: "The absolute nexus of HR and Legal in massive SaaS, IT, and Consulting firms.",
        workNature: "Policy Drafting, Risk Management & Executive Advisory.",
        futureScope: "Exploding. The shift to globalized remote work has created an absolute nightmare of overlapping employment jurisdictions; HR Legal Advisors are the only ones capable of mapping this out.",
        jobDemandTrend: "Rapidly Growing",
        summary: "The strategic advisors merging HR management with legal risk-mitigation to run highly compliant, globalized corporate workforces."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Employee Rights Lawyer",
        description: "The David fighting the corporate Goliath. They strictly represent individual employees (not companies) in lawsuits regarding wrongful termination, unpaid overtime, workplace discrimination, and whistleblower retaliation.",
        educationPath: "LLB",
        competitiveExams: ["State Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Aggressive Plaintiff Litigation", "Whistleblower Protection Laws", "Discrimination Evidence Gathering", "Contingency Fee Structures"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $60,000 - $180,000 per year",
        roadmap: ["Associate Lawyer", "Independent Plaintiff Lawyer", "Class Action Specialist", "Civil Rights Leader"],
        courtPracticeOpportunities: "Aggressive litigation in Civil Courts, High Courts, and specialized tribunals.",
        governmentJobs: "Often clash with government bodies on behalf of terminated civil servants (CAT tribunals).",
        corporateOpportunities: "Adversarial only. They exist entirely to sue corporations.",
        workNature: "High-Stress Plaintiff Litigation & Settlement Extortion.",
        futureScope: "A highly rewarding, independent path. As corporate layoffs become more ruthless and algorithm-driven, the demand for aggressive employee-side litigators is rising sharply.",
        jobDemandTrend: "High Volume",
        summary: "The aggressive plaintiff lawyers who utilize the courtroom to legally punish massive corporations for abusing, underpaying, or wrongfully firing individuals."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Trade Union Legal Advisor",
        description: "Serves as the exclusive legal shield for organized labor unions. They draft the union's operational constitution, legally protect strike leaders from being fired or criminally charged, and organize massive legal strategies against political union-busting.",
        educationPath: "LLB -> Deep background in Labour History/Activism",
        competitiveExams: ["None"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Trade Union Constitution Drafting", "Injunction Defense", "Mass Political Negotiation", "Activism"],
        salaryRange: "India: ₹3 LPA - ₹12 LPA | Global: $55,000 - $130,000 per year",
        roadmap: ["Union Fellow", "Union Retainer Counsel", "General Secretary of Legal Affairs", "Elected Labour Politician"],
        courtPracticeOpportunities: "Fights rapid injunctions sought by companies to declare strikes 'illegal' in High Courts.",
        governmentJobs: "Occasionally appointed to tripartite government labour boards.",
        corporateOpportunities: "None. Purely an activist / union-funded role.",
        workNature: "Legal Activism, High-Stress Negotiations & Courtroom Defense.",
        futureScope: "A politically charged path. While traditional unions are shrinking globally, the rise of 'gig-worker' unions (Uber drivers, Amazon warehouse workers) is creating an entirely new, massive demand for union lawyers.",
        jobDemandTrend: "Evolving (Gig Economy focus)",
        summary: "The intellectual vanguard for organized labor, protecting the constitutional right to strike and legally shielding vulnerable workers from aggressive corporate retaliation."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Labour Court Advocate",
        description: "A highly specialized subset of litigators who spend their entire lives exclusively within the specific procedural walls of the localized Labour Courts, mastering the administrative quirks and judicial temperaments unique to these tribunals.",
        educationPath: "LLB",
        competitiveExams: ["State Law Entrances"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["Administrative Procedures Mastery", "High Volume Case Management", "Vernacular Legal Jargon", "Conciliation Procedures"],
        salaryRange: "India: ₹3 LPA - ₹15+ LPA | Global: N/A (Highly Localized Role)",
        roadmap: ["Junior Court Practitioner", "Independent Labour Advocate", "Labour Bar President", "Elevation to Tribunal Presiding Officer"],
        courtPracticeOpportunities: "Absolute immersion in Labour Courts and Industrial Dispute Act Tribunals.",
        governmentJobs: "Applying for roles as Presiding Officers of the Labour Courts.",
        corporateOpportunities: "Running independent localized chambers retained by hundreds of small factory owners.",
        workNature: "Relentless Courtroom Appearances & Cross-Examination.",
        futureScope: "The bedrock of localized justice. These courts resolve the millions of micro-disputes (unpaid wages, illegal sudden firings) that keep the blue-collar economy functioning.",
        jobDemandTrend: "High Volume",
        summary: "The localized, high-volume trial advocates who know every inch of the Labour Court procedures, securing rapid justice for individual workers."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Workplace Dispute Resolution Lawyer",
        description: "A specialized mediator who steps in when a toxic internal corporate environment threatens a massive lawsuit. They investigate internal claims of bullying or racism impartially, attempting to broker a quiet resignation and severance before it hits the media.",
        educationPath: "LLB -> Alternative Dispute Resolution (ADR) Specialization",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Certified Workplace Investigator/Mediator"],
        skills: ["Impartial Investigative Interviewing", "De-escalation", "Evidence Preservation", "Severance Negotiation"],
        salaryRange: "India: ₹6 LPA - ₹20 LPA | Global: $80,000 - $160,000 per year",
        roadmap: ["Internal Investigator", "Senior Mediator", "Independent Investigative Consultant", "Partner - ADR/Employment"],
        courtPracticeOpportunities: "Exists solely to divert toxic disputes completely away from public courts.",
        governmentJobs: "Appointed to state-run conciliation boards.",
        corporateOpportunities: "Hired internally by massive tech companies or brought in as 'impartial third parties' by elite boutiques.",
        workNature: "Intense Interviewing, Report Writing & Quiet Financial Dealmaking.",
        futureScope: "Extremely lucrative. A public discrimination or harassment lawsuit can wipe billions off a company's stock value. These lawyers prevent that entirely by solving the issue quietly behind closed doors.",
        jobDemandTrend: "Rapidly Growing",
        summary: "The quiet corporate fixers, deployed to impartially investigate and financially settle toxic workplace disputes before they become public scandals."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Employment Contract Specialist",
        description: "The commercial draftspeople of the HR world. They write ironclad employment agreements that precisely define massive executive bonus structures, stock options (ESOPs), and strict global non-disclosure agreements (NDAs).",
        educationPath: "LLB -> Focus in Corporate/Contract Law",
        competitiveExams: ["CLAT"],
        yearsOfStudy: "3 to 5 Years",
        certifications: ["Bar Council Enrollment"],
        skills: ["ESOP Structuring", "Complex Compensation Drafting", "Multi-Jurisdictional Tax Law", "NDA Architecture"],
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $90,000 - $180,000 per year",
        roadmap: ["Drafting Associate", "Senior Commercial Counsel", "Partner - Executive Compensation", "General Counsel"],
        courtPracticeOpportunities: "Zero.",
        governmentJobs: "Drafting the strict employment terms for specialized lateral-entry government contractors.",
        corporateOpportunities: "Massive demand. Every tech startup and global bank relies on these specialists to lock down their most valuable executives.",
        workNature: "Heavy Commercial Drafting & Financial Compensation Structuring.",
        futureScope: "Extremely secure. As companies compensate top talent with increasingly complex mechanisms (crypto, variable stock, deferred bonuses), specialized drafting skills are paramount.",
        jobDemandTrend: "High and Stable",
        summary: "The legal architects of corporate compensation, wrapping immense executive wealth and corporate secrets into bulletproof employment contracts."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Labour Law Consultant",
        description: "Independent experts hired heavily by startups and foreign companies entering a new country. They explain exactly how to legally hire, fire, and compensate locals without triggering massive penalties from unfamiliar local labor departments.",
        educationPath: "LLB -> Extensive Industry Experience",
        competitiveExams: ["None"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Labour Compliance Diplomas"],
        skills: ["FDI Labor Navigations", "Cross-Border Employment Law", "Startup Structuring", "Advisory"],
        salaryRange: "India: ₹6 LPA - ₹25 LPA | Global: $80,000 - $170,000 per year",
        roadmap: ["Consulting Associate", "Senior Labour Strategist", "Of Counsel to Tier-1 Firms", "Independent Boutique Owner"],
        courtPracticeOpportunities: "Minimal.",
        governmentJobs: "None, acts purely as private commercial advisors.",
        corporateOpportunities: "The absolute first person a foreign company (like Amazon or BYD) hires when opening a factory or office in a new country.",
        workNature: "Strategic Business Advisory & Cross-Border Compliance Mapping.",
        futureScope: "Highly lucrative. The penalties for foreign companies violating local employment laws are massive; these consultants provide the foundational 'safe' roadmap for market entry.",
        jobDemandTrend: "High (Globalization Driven)",
        summary: "The strategic guides who prevent foreign MNCs and local startups from accidentally breaking complex regional employment laws during their expansion."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Employment Policy Legal Analyst",
        description: "Operates at the macro level within think-tanks and ministries, studying the socioeconomic shifts in how humans work (e.g., AI replacing jobs, the 4-day workweek) and drafting the future national legislations to govern them.",
        educationPath: "LLB -> Masters in Public Policy (MPP) / Economics",
        competitiveExams: ["None specifically"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["Policy Fellowships"],
        skills: ["Macro-Economic Labor Analysis", "Legislative Drafting", "Gig-Economy Law", "Policy Synthesis"],
        salaryRange: "India: ₹6 LPA - ₹15 LPA | Global: $70,000 - $140,000 per year",
        roadmap: ["Research Analyst", "Senior Policy Fellow", "Director of Think-Tank", "Ministerial Draftsman"],
        courtPracticeOpportunities: "None.",
        governmentJobs: "Advising the Ministry of Labour and Employment or the International Labour Organization (ILO).",
        corporateOpportunities: "Hired by massive gig-economy tech companies (Uber, Swiggy) to lobby governments for favorable labour reforms.",
        workNature: "Pure Policy Research, Macro-Economic Studying & Legislative Drafting.",
        futureScope: "Critical for modern economies. As algorithms and AI fundamentally destroy the traditional '9-to-5' employment model, entirely new laws must be written by these visionary analysts.",
        jobDemandTrend: "Niche but Expanding",
        summary: "The intellectual architects analyzing the changing nature of human work, drafting the future laws that will govern the gig-economy and AI-driven workforces."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Labour Law Researcher",
        description: "Dives into the deep academic roots of workers' rights, analyzing global precedents on minimum wage viability, occupational safety standards, and unionization laws, publishing papers frequently cited in Supreme Court judgements.",
        educationPath: "LLB -> LLM in Labour Rights",
        competitiveExams: ["CLAT (PG)"],
        yearsOfStudy: "5 to 6 Years",
        certifications: ["None mandatory"],
        skills: ["Precedent Synthesis", "Comparative Global Law", "Academic Writing", "Historical Jurisprudence"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $100,000 per year",
        roadmap: ["Research Assistant", "Senior Independent Scholar", "Think-Tank Director", "Global Labour Law Expert"],
        courtPracticeOpportunities: "Drafting the most complex 'unicorn' writs for Senior litigators arguing unprecedented labour-constitutional matters.",
        governmentJobs: "Researchers for the Law Commission mapping out the consolidation of archaic labour codes.",
        corporateOpportunities: "Occasionally consulting for massive multi-nationals predicting multi-jurisdictional union clashes.",
        workNature: "Intense Academic Research, Publishing & High-Level Jurisprudential Theory.",
        futureScope: "Essential for pushing the boundaries of what constitutes 'fair work'. The transition of 44 complex Indian labour laws into 4 consolidated Labour Codes relies entirely on backend researchers.",
        jobDemandTrend: "Stable within Academia",
        summary: "The academic pioneers unearthing profound historical precedents to assist senior advocates in radically expanding the constitutional definition of workers' rights."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Labour & Employment Law Professor",
        description: "Educates the next generation of lawyers and HR executives on the incredibly dense web of industrial dispute acts, wage codes, and corporate compliance regimes, designing modern curricula for law schools.",
        educationPath: "LLB -> LLM -> Ph.D. in Labour Law",
        competitiveExams: ["UGC NET (Mandatory for India)"],
        yearsOfStudy: "8+ Years (Including Ph.D.)",
        certifications: ["UGC NET"],
        skills: ["Pedagogy", "Syllabus Modernization", "Doctrinal Analysis", "Academic Mentorship"],
        salaryRange: "India: ₹8 LPA - ₹24 LPA | Global: $70,000 - $150,000 per year",
        roadmap: ["Assistant Professor", "Associate Professor", "Professor of Law", "Dean of specialized Institutes"],
        courtPracticeOpportunities: "Occasionally appointed as Amicus Curiae by High Courts in complex constitutional labour disputes.",
        governmentJobs: "Permanent faculty in National Law Universities or the V.V. Giri National Labour Institute.",
        corporateOpportunities: "Highly sought after by elite corporations to conduct specialized legal workshops for their top HR executives.",
        workNature: "Teaching, Mentoring, Curriculum Design & Elite Academic Publishing.",
        futureScope: "Highly prestigious. As corporate compliance becomes infinitely more complex, the demand for professors who can actually demystify labour law for incoming professionals is vast.",
        jobDemandTrend: "High for Ph.D. Holders",
        summary: "The academic authorities who demystify archaic labour codes and train the lawyers and HR executives who will manage the workforces of the future."
    },
    {
        domain: "Law",
        branch: "Labour & Employment Law",
        title: "Corporate Labour Compliance Officer",
        description: "The absolute nexus between legal requirement and operational reality. They physically inspect massive manufacturing plants and corporate offices to ensure every fire-exit, overtime slip, and maternity leave perfectly matches the law.",
        educationPath: "LLB -> PG Diploma in Labour Laws",
        competitiveExams: ["None"],
        yearsOfStudy: "4 to 5 Years",
        certifications: ["Factory Act Compliance Certifications"],
        skills: ["Physical Auditing", "Occupational Health & Safety (OHS) Laws", "Corporate Governance", "Bureaucratic Communication"],
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $70,000 - $130,000 per year",
        roadmap: ["Compliance Inspector", "Site Compliance Head", "Regional Compliance Director", "Chief Operations/Compliance Officer"],
        courtPracticeOpportunities: "Zero.",
        governmentJobs: "Essentially doing the job of a government Factory Inspector, but from the inside of the corporation.",
        corporateOpportunities: "Massive demand. Every single physical factory, warehouse (Amazon), or massive office complex requires an internal compliance officer.",
        workNature: "Physical Site Auditing, Report Drafting & Enforcing Internal Legal Regulations.",
        futureScope: "Extremely stable. While software can automate contracts, checking physical compliance (like factory lighting or safety gear) requires highly trained human legal auditors on the ground.",
        jobDemandTrend: "High and Stable",
        summary: "The boots-on-the-ground legal officers who physically inspect corporate operations to ensure perfect alignment with national occupational safety and wage laws."
    }
];

const seedData = async () => {
    try {
        await Career.deleteMany({ branch: "Labour & Employment Law" });
        await Career.insertMany(labourLawProfessions);
        console.log('Labour and Employment Law Professions Appended Successfully!'.green.inverse);
        process.exit();
    } catch (err) {
        console.error('Error during seeding:', err);
        process.exit(1);
    }
};

seedData();
