const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const journalismProfessions = [
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Broadcast News Reporter",
        description: "Gather information on current events, conduct interviews, and write or broadcast stories for news outlets.",
        summary: "Frontline news gatherers providing daily updates on local, national, or international events.",
        skills: ["Writing", "Research", "Interviewing", "Deadline Management", "Objectivity"],
        salaryRange: "India: ₹3L - ₹12L | Global: $40K - $80K",
        educationPath: "B.A. Journalism / Mass Communication",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Newspapers", "Television Networks", "Radio Stations", "Online News Portals"],
        futureScope: "Continuous demand, though shifting heavily towards digital media platforms.",
        jobDemandTrend: "Stable, Shifting to Digital",
        governmentJobs: "Opportunities in state broadcasters like Doordarshan (India) or BBC (UK).",
        freelanceOpportunities: "High. Plentiful opportunities as stringers or freelance contributors.",
        fieldWork: "Very High. Requires constant on-ground presence, travel to event locations.",
        riskLevel: "Moderate (High in conflict zones)",
        certifications: ["None specific (Portfolio is key)"],
        roadmap: ["Degree in Journalism", "Intern at Local News", "City Reporter", "National Correspondent / Broadcast News Anchor"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Investigative Journalist",
        description: "Spend months researching a single topic to uncover hidden truths, corruption, corporate wrongdoings, or criminal activities.",
        summary: "Deep-dive reporters who expose corruption and systemic issues through extensive research.",
        skills: ["Deep Research", "Data Analysis", "Source Cultivation", "Legal Knowledge", "Persistence"],
        salaryRange: "India: ₹5L - ₹18L | Global: $55K - $120K",
        educationPath: "B.A. Journalism → Specialised training in investigative techniques",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Major News Networks", "Independent Investigative Outlets (e.g., ProPublica)", "Magazines"],
        futureScope: "High impact. Essential for democratic accountability, often funded by grants and non-profits.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "Rare, as the role often involves scrutinizing the government.",
        freelanceOpportunities: "Moderate. Often requires institutional backing due to legal risks.",
        fieldWork: "High. Involves secretive meetings and extensive travel.",
        riskLevel: "High (Potential legal and physical risks)",
        certifications: ["Data Journalism Certificates"],
        roadmap: ["Field Reporter", "Build network of sources", "Join Investigative Desk", "Senior Investigative Editor / Author"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Broadcast News Anchor",
        description: "Present news stories on television or radio, summarizing complex information clearly and conducting live interviews.",
        summary: "The public face of a news organization, presenting reports and conducting live broadcasts.",
        skills: ["Public Speaking", "Charisma", "Quick Thinking", "Teleprompter Reading", "On-Camera Presence"],
        salaryRange: "India: ₹8L - ₹50L+ | Global: $60K - $250K+",
        educationPath: "B.A. Journalism / Broadcast Media",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Television News Channels", "Radio Networks", "Digital Broadcasting (YouTube/OTT)"],
        futureScope: "Highly lucrative but faces pressure from digital influencers and independent media.",
        jobDemandTrend: "Highly Competitive, Star-Driven",
        governmentJobs: "Opportunities as anchors for state-run media.",
        freelanceOpportunities: "Low. Usually contracted to a specific network.",
        fieldWork: "Low. Primarily studio-based.",
        riskLevel: "Low",
        certifications: ["Broadcast Training"],
        roadmap: ["Field Reporter", "Weekend Anchor", "Prime Time Anchor", "Managing Editor"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Broadcast Journalist",
        description: "Research, write, and present news stories specifically formulated for television, radio, or podcasts.",
        summary: "Journalists specialized in producing audio and video news packages.",
        skills: ["Video/Audio Editing", "Script Writing for Ear/Eye", "Voice Operation", "Storyboarding"],
        salaryRange: "India: ₹4L - ₹15L | Global: $45K - $90K",
        educationPath: "B.A. Broadcast Journalism",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["TV Stations", "Radio Stations", "Podcast Networks"],
        futureScope: "Growing rapidly in the podcast and digital video sectors.",
        jobDemandTrend: "Growing (Audio/Video formats)",
        governmentJobs: "Roles in national broadcasting corporations.",
        freelanceOpportunities: "High. Producing independent documentaries or podcasts.",
        fieldWork: "Moderate to High.",
        riskLevel: "Moderate",
        certifications: ["Editing Software Certifications (Premiere, Audition)"],
        roadmap: ["Broadcast Degree", "Production Assistant", "Reporter/Producer", "Executive Producer"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Photojournalist",
        description: "Tell news stories through compelling photographs, capturing the emotion and reality of events as they unfold.",
        summary: "Visual storytellers who document news, events, and human interest stories through compelling photography.",
        skills: ["Photography", "Visual Storytelling", "Photo Editing", "Situational Awareness", "Ethical Judgment"],
        salaryRange: "India: ₹3L - ₹10L | Global: $40K - $80K",
        educationPath: "B.A. / Diploma in Photojournalism or Photography",
        yearsOfStudy: "2 to 4 Years",
        industriesHiring: ["News Agencies (AP, Reuters)", "Magazines", "Digital News"],
        futureScope: "Impactful, though highly competitive due to the ubiquity of smartphone cameras.",
        jobDemandTrend: "Competitive",
        governmentJobs: "Official photographers for government departments.",
        freelanceOpportunities: "Very High. Most photojournalists work on a freelance or contract basis.",
        fieldWork: "Maximum. Requires constantly being at the center of the action.",
        riskLevel: "Moderate to High (Depending on the assignment)",
        certifications: ["None specific (Portfolio driven)"],
        roadmap: ["Photography training", "Freelance for local papers", "Staff Photographer", "Chief Photo Editor / Agency Photographer"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Video Journalist",
        description: "A one-person crew (VJ) who reports, shoots, and edits their own video news stories, primarily for digital platforms and TV.",
        summary: "Multimedia journalists who handle all aspects of video news production independently.",
        skills: ["Videography", "Video Editing", "Reporting", "On-Camera Reporting", "Technical Independence"],
        salaryRange: "India: ₹4L - ₹12L | Global: $45K - $85K",
        educationPath: "B.A. Multimedia Journalism",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Digital First News Outlets (Vice, Vox)", "TV Networks", "Documentary Studios"],
        futureScope: "Explosive growth as newsrooms cut costs and heavily prioritize digital video content.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Multimedia roles in government PR departments.",
        freelanceOpportunities: "High. Producing independent content or stringing for larger networks.",
        fieldWork: "High. Operating independently in the field.",
        riskLevel: "Moderate to High",
        certifications: ["Video Production Certificates"],
        roadmap: ["Degree in Multimedia", "Digital Video Producer", "Senior VJ", "Documentary Filmmaker"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Political Journalist",
        description: "Cover political campaigns, government policies, legislative sessions, and the actions of elected officials.",
        summary: "Specialized reporters covering the inner workings of government and political campaigns.",
        skills: ["Political Knowledge", "Networking", "Analysis", "Fast Writing", "Discretion"],
        salaryRange: "India: ₹6L - ₹20L | Global: $55K - $110K",
        educationPath: "B.A. Journalism / Political Science",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["National Newspapers", "Political Magazines", "TV News Networks"],
        futureScope: "High prestige. Critical for informing the public during volatile political eras.",
        jobDemandTrend: "Stable, High Prestige",
        governmentJobs: "Press Secretary or Communications Director roles.",
        freelanceOpportunities: "Moderate. Usually requires institutional backing for access.",
        fieldWork: "High. Traveling with campaigns and attending rallies/press conferences.",
        riskLevel: "Low to Moderate (Target for public animosity)",
        certifications: ["None specific."],
        roadmap: ["City Reporter", "State Capital Correspondent", "National Political Reporter", "Bureau Chief / Columnist"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Business Journalist",
        description: "Track the stock market, analyze corporate earnings, report on economic trends, and cover the tech and finance industries.",
        summary: "Specialists reporting on the economy, financial markets, and the corporate world.",
        skills: ["Financial Literacy", "Data Interpretation", "Networking with Executives", "Translating Jargon", "Market Analysis"],
        salaryRange: "India: ₹6L - ₹25L | Global: $60K - $130K",
        educationPath: "B.A. Journalism / Economics / B.Com → M.A. Business Journalism",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Financial Newspapers (WSJ, FT)", "Business News Channels (CNBC, Bloomberg)", "Tech Blogs"],
        futureScope: "Highly lucrative and stable. Reliable financial journalism is essential for markets.",
        jobDemandTrend: "High Demand (Niche Skill)",
        governmentJobs: "Reporting for economic ministries or central banks' publications.",
        freelanceOpportunities: "Moderate. Analyzing trends across various platforms.",
        fieldWork: "Low to Moderate. Mostly office/studio based, attending corporate events.",
        riskLevel: "Low",
        certifications: ["Financial Analysis Certificates (CFA Level 1 is a huge plus)"],
        roadmap: ["Business/Economics Degree", "Markets Reporter", "Corporate Investigator", "Financial Editor / Broadcast News Anchor"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Sports Journalist",
        description: "Cover athletic events, conduct player and coach interviews, provide commentary, and analyze team statistics.",
        summary: "Journalists dedicated to covering athletic competitions, teams, and sports culture.",
        skills: ["Sports Knowledge", "Live Commentary", "Engaging Writing Style", "Networking", "Statistical Analysis"],
        salaryRange: "India: ₹4L - ₹18L | Global: $45K - $100K",
        educationPath: "B.A. Journalism",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Sports Networks (ESPN)", "Sports Websites (The Athletic)", "Newspapers"],
        futureScope: "Strong and fan-driven. Evolving quickly with the rise of sports betting and deep analytics.",
        jobDemandTrend: "Stable, Passion-Driven",
        governmentJobs: "Sporting authority PR roles.",
        freelanceOpportunities: "High. Podcasting and writing for independent sports blogs.",
        fieldWork: "High. Constant travel to stadiums and press boxes.",
        riskLevel: "Low",
        certifications: ["None specific."],
        roadmap: ["Cover high school/college sports", "Beat Reporter for a Pro Team", "National Columnist / TV Analyst"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Entertainment Journalist",
        description: "Report on the film, music, television, and celebrity industries, including reviews, interviews, and industry trends.",
        summary: "Reporters covering pop culture, arts, and the entertainment industry.",
        skills: ["Pop Culture Knowledge", "Interviewing Celebrities", "Critical Reviewing", "Networking", "Trend Spotting"],
        salaryRange: "India: ₹3L - ₹15L | Global: $40K - $90K",
        educationPath: "B.A. Journalism / Communications",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Entertainment Magazines (Variety, Rolling Stone)", "Entertainment TV Channels", "Digital Portals"],
        futureScope: "Massive digital audience, heavily influenced by social media and influencer culture.",
        jobDemandTrend: "High Volume, Evolving",
        governmentJobs: "Rare. Roles in state film development boards.",
        freelanceOpportunities: "Very High. Reviewing content and writing for multiple pop-culture outlets.",
        fieldWork: "Moderate. Attending premieres, festivals, and press junkets.",
        riskLevel: "Low",
        certifications: ["None specific."],
        roadmap: ["Entertainment Degree", "Staff Writer", "Senior Critic / Celebrity Interviewer", "Entertainment Editor"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Digital Journalist",
        description: "Focus entirely on creating content for the web, utilizing SEO, social media algorithms, and interactive media to drive traffic and engagement.",
        summary: "Modern journalists optimizing stories for the internet, social media, and digital audiences.",
        skills: ["SEO", "Social Media Management", "Content Management Systems (CMS)", "Data Analytics", "Rapid Writing"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $85K",
        educationPath: "B.A. Journalism / Digital Media",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["All Modern News Organizations", "Digital-Only Publishers", "Social Media Platforms"],
        futureScope: "The current baseline of journalism. Every journalist must now process digital skills.",
        jobDemandTrend: "Very High",
        governmentJobs: "Managing digital presence for government entities.",
        freelanceOpportunities: "High. Running independent newsletters (Substack) or managing social media.",
        fieldWork: "Low. Primarily desk-based, monitoring social trends.",
        riskLevel: "Low (High risk of burnout from rapid news cycle)",
        certifications: ["Google Analytics, SEO Certifications"],
        roadmap: ["Digital Media Degree", "Social Media Coordinator", "Digital Editor", "Director of Digital Strategy"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Columnist",
        description: "Write opinion pieces expressing personal views and analysis on news, politics, or cultural events for a dedicated readership.",
        summary: "Opinion writers who use their unique voice and expertise to analyze and comment on the news.",
        skills: ["Distinct Voice", "Persuasive Writing", "Deep Expertise in a Subject", "Analytical Thinking", "Thick Skin"],
        salaryRange: "India: ₹6L - ₹30L | Global: $60K - $150K+",
        educationPath: "B.A./M.A. Journalism, Political Science, or English",
        yearsOfStudy: "3 to 6 Years",
        industriesHiring: ["Major Newspapers", "Magazines", "Digital Publications"],
        futureScope: "Highly dependent on personal brand and audience loyalty. Substack and independent newsletters are the future of this role.",
        jobDemandTrend: "Niche, High Prestige",
        governmentJobs: "None. Requires independence from government.",
        freelanceOpportunities: "High. Often syndicated across multiple platforms.",
        fieldWork: "Low. Primarily thought-work and writing.",
        riskLevel: "Low (Risk of public backlash/cancel culture)",
        certifications: ["None specific."],
        roadmap: ["Establish expertise as a reporter/writer", "Write guest op-eds", "Secure a regular column", "Syndicated Columnist / Author"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Editorial Writer",
        description: "Write the unsigned opinion pieces representing the collective institutional view of the newspaper or publication's editorial board.",
        summary: "The voice of the publication, writing policy-focused opinion pieces representing the editorial board.",
        skills: ["Persuasive Argumentation", "Institutional Tone Matching", "Policy Knowledge", "Debate", "Synthesis of Complex Ideas"],
        salaryRange: "India: ₹6L - ₹18L | Global: $60K - $110K",
        educationPath: "B.A./M.A. Journalism or Public Policy",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Newspapers", "Digital Political Outlets"],
        futureScope: "Traditional newspaper editorials are declining, but specialized digital outlets still require institutional voices.",
        jobDemandTrend: "Declining in Print, Stable in Specialized Digital",
        governmentJobs: "Speechwriting roles.",
        freelanceOpportunities: "Low. Usually an in-house salaried position.",
        fieldWork: "Low.",
        riskLevel: "Low",
        certifications: ["None specific."],
        roadmap: ["Journalist/Policy Analyst", "Join Editorial Board", "Editorial Writer", "Editorial Page Editor"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "News Editor",
        description: "Assign stories to reporters, edit copy for accuracy, clarity, and style (usually AP Style), and determine the daily layout or news rundown.",
        summary: "The gatekeepers of the newsroom, managing reporters and ensuring the quality and accuracy of published stories.",
        skills: ["Copy Editing", "Leadership", "News Judgment", "Fact-Checking", "Stress Management"],
        salaryRange: "India: ₹6L - ₹20L | Global: $60K - $115K",
        educationPath: "B.A. Journalism / English",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["All News Organizations", "Publishing Houses", "Content Marketing Firms"],
        futureScope: "Constant demand. Editors are essential for maintaining the credibility and legal safety of a publication.",
        jobDemandTrend: "Stable",
        governmentJobs: "Editing government publications and press releases.",
        freelanceOpportunities: "Moderate. Freelance copy editing.",
        fieldWork: "Low. Office/Newsroom based.",
        riskLevel: "Low",
        certifications: ["Editing/Style Guide Certifications"],
        roadmap: ["Copy Editor", "Assistant News Editor", "Section Editor (e.g., City Editor)", "Editor-in-Chief"]
    },
    {
        domain: "Arts",
        branch: "Journalism",
        title: "Field Correspondent",
        description: "Deployed to specific geographical locations or conflict zones to report live and gather first-hand intelligence on major developing events.",
        summary: "Journalists sent directly into the heart of major global events, disasters, or war zones to report live.",
        skills: ["Crisis Management", "Foreign Languages", "Live Reporting", "Adaptability", "Physical Endurance"],
        salaryRange: "India: ₹6L - ₹25L | Global: $65K - $150K",
        educationPath: "B.A. Journalism / International Relations",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["International News Agencies (BBC, CNN, Al Jazeera)", "Major Newspapers"],
        futureScope: "Highly respected but facing budget cuts in many newsrooms. Often relied upon during major geometric crises.",
        jobDemandTrend: "Niche, High Risk",
        governmentJobs: "Diplomatic communication roles.",
        freelanceOpportunities: "Moderate. Many war correspondents operate as freelance stringers.",
        fieldWork: "Maximum. Constant international travel to unpredictable environments.",
        riskLevel: "Very High (Physical danger, conflict zones)",
        certifications: ["Hostile Environment Training (HET)"],
        roadmap: ["Foreign Desk Reporter", "Foreign Bureau Staff", "Field Correspondent", "Foreign Bureau Chief"]
    }
];

const seedJournalism = async () => {
    try {
        await Career.deleteMany({ branch: "Journalism" });
        await Career.insertMany(journalismProfessions);
        console.log('Journalism Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedJournalism();
