const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const tourismProfessions = [
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Tourism Manager / Director",
        description: "Oversee the operations of tourism boards, large travel agencies, or resort complexes, developing strategies to attract visitors and ensure high-quality guest experiences.",
        summary: "Executives managing large-scale tourism operations and regional tourism strategies.",
        skills: ["Strategic Planning", "Business Management", "Marketing", "Public Relations", "Financial Forecasting"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $70K - $140K+",
        educationPath: "B.A. Tourism Studies / BBA → MBA in Tourism Management",
        yearsOfStudy: "5 Years",
        industriesHiring: ["State Tourism Boards", "Major Travel Agencies (Thomas Cook, MakeMyTrip)", "Luxury Resorts"],
        futureScope: "Extremely lucrative. As global travel expands post-pandemic, strategic leaders are needed to manage mass tourism sustainably.",
        jobDemandTrend: "High Growth",
        governmentJobs: "High. Directorships in state and national tourism departments.",
        freelanceOpportunities: "Low. Primarily salaried executive roles.",
        fieldWork: "Moderate. Traveling to industry conferences and inspecting regional tourist infrastructure.",
        riskLevel: "Low",
        certifications: ["Certified Travel Industry Executive (CTIE)"],
        internshipRequirements: "Management internships at top-tier hotels or travel agencies.",
        roadmap: ["Tourism Operations Executive", "Regional Tourism Manager", "Director of Tourism", "Secretary of State Tourism"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Travel Consultant / Advisor",
        description: "Provide expert advice and construct complex, personalized travel itineraries for clients, handling flights, accommodations, tours, and visas.",
        summary: "Specialized planners curating tailored travel experiences for individuals and groups.",
        skills: ["Customer Service", "Geography Knowledge", "GDS Software (Amadeus, Sabre)", "Sales", "Problem Solving"],
        salaryRange: "India: ₹3L - ₹10L | Global: $40K - $80K",
        educationPath: "B.A. Tourism / Diploma in Travel & Ticketing",
        yearsOfStudy: "1 to 3 Years",
        industriesHiring: ["Travel Agencies", "Corporate Travel Management Companies", "Luxury Concierge Services"],
        futureScope: "Shifting from basic booking (now done online) to highly specialized, luxury, or niche travel advising.",
        jobDemandTrend: "Stable, Shifting to Niche",
        governmentJobs: "Low.",
        freelanceOpportunities: "Maximum. Many operate as independent travel advisors under host agencies.",
        fieldWork: "Low. Mostly desk-based, though 'FAM' (familiarization) trips are common.",
        riskLevel: "Low",
        certifications: ["IATA Travel and Tourism Professional"],
        internshipRequirements: "Ticketing and customer service internships at travel agencies.",
        roadmap: ["Junior Ticketing Agent", "Travel Consultant", "Senior Leisure Travel Advisor", "Luxury Travel Curator"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Tour Operator / Product Manager",
        description: "Design, organize, and price comprehensive tour packages, negotiating contracts with airlines, hotels, and local ground handlers.",
        summary: "The architects of tour packages, assembling the logistics and pricing for group travel.",
        skills: ["Negotiation", "Logistics", "Contracting", "Pricing Strategies", "Supplier Relationship Management"],
        salaryRange: "India: ₹4L - ₹15L | Global: $55K - $95K",
        educationPath: "B.A. / BBA in Tourism Management",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Inbound/Outbound Tour Operators", "Destination Management Companies (DMCs)"],
        futureScope: "Crucial role as experiential and group travel continues to grow; operators must now focus on sustainable supply chains.",
        jobDemandTrend: "Growing",
        governmentJobs: "Roles in state-run tour companies (e.g., IRCTC in India).",
        freelanceOpportunities: "Moderate. Independent tour curators.",
        fieldWork: "Moderate. Traveling to destination countries to vet hotels and local guides.",
        riskLevel: "Low (High financial stress regarding package sales and contract minimums)",
        certifications: ["Tour Management Certificates"],
        internshipRequirements: "Operations internships with inbound DMCs.",
        roadmap: ["Operations Executive", "Product Executive", "Tour Product Manager", "VP of Tour Operations"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Tour Guide / Escort",
        description: "Lead groups of tourists through historical sites, cities, or natural landscapes, providing engaging and educational commentary.",
        summary: "The frontline storytellers and local experts leading tourist groups.",
        skills: ["Public Speaking", "Extensive Local/Historical Knowledge", "Foreign Languages", "Crisis Management", "Stamina"],
        salaryRange: "India: ₹2L - ₹8L (Highly seasonal) | Global: $30K - $65K",
        educationPath: "B.A. History / Tourism → Official Guide License",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Tour Operators", "Museums", "Historical Sites", "Cruise Lines"],
        futureScope: "AI and audio guides present a challenge, so successful guides must offer highly personalized, charismatic experiences.",
        jobDemandTrend: "Stable (Seasonal)",
        governmentJobs: "High. State-certified guides are required for major national monuments.",
        freelanceOpportunities: "Maximum. Most tour guides operate as independent contractors.",
        fieldWork: "Maximum. Constantly on the move, leading groups outdoors or through sites.",
        riskLevel: "Low to Moderate (Dealing with group logistics, medical emergencies on tours)",
        certifications: ["State/National Tour Guide License (Mandatory in many regions)"],
        internshipRequirements: "Shadowing experienced guides.",
        roadmap: ["Assistant Guide", "Licensed Regional Guide", "Specialized Historical/Adventure Guide", "Tour Company Owner"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Heritage Tourism Manager",
        description: "Develop and manage tourism initiatives focused specifically on historical, cultural, and archaeological sites, balancing visitor influx with site preservation.",
        summary: "Specialists who commercialize and protect historical and cultural landmarks.",
        skills: ["Conservation Awareness", "Tourism Marketing", "Grant Writing", "Cultural Sensitivity", "Stakeholder Management"],
        salaryRange: "India: ₹5L - ₹18L | Global: $55K - $100K",
        educationPath: "B.A. History / Archaeology → M.A. Heritage Tourism",
        yearsOfStudy: "5 Years",
        industriesHiring: ["UNESCO", "National Trusts", "Archaeological Surveys", "Specialized Tour Agencies"],
        futureScope: "High demand as heritage tourism is one of the most profitable and globally recognized sectors of the industry.",
        jobDemandTrend: "Stable Growth",
        governmentJobs: "High. Working for national heritage preservation boards.",
        freelanceOpportunities: "Moderate. Heritage consulting.",
        fieldWork: "High. Regular on-site presence at historical monuments.",
        riskLevel: "Low",
        certifications: ["Cultural Heritage Certificates"],
        internshipRequirements: "Internships with historical societies or national trusts.",
        roadmap: ["Site Coordinator", "Heritage Tourism Officer", "Director of Heritage Conservation", "Minister of Culture/Tourism"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Ecotourism / Sustainable Tourism Specialist",
        description: "Develop travel programs and policies that minimize environmental impact, respect local cultures, and generate funds for ecological conservation.",
        summary: "Advocates and planners making the travel industry environmentally and socially responsible.",
        skills: ["Environmental Science Basics", "Sustainable Business Practices", "Community Organizing", "Policy Advocacy"],
        salaryRange: "India: ₹4L - ₹15L | Global: $55K - $95K",
        educationPath: "B.A. Tourism / Environmental Studies → M.A. Sustainable Tourism",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Eco-Lodges", "Wildlife Sanctuaries", "Environmental NGOs", "Government Tourism Boards"],
        futureScope: "The fastest-growing sub-sector in tourism. 'Green travel' is transitioning from a niche to an absolute mainstream requirement.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Advising state tourism boards on sustainable development policies.",
        freelanceOpportunities: "High. Consultants auditing hotels and operators for 'green' certifications.",
        fieldWork: "High. Evaluating remote eco-lodges and conservation areas.",
        riskLevel: "Low to Moderate (Depending on remote field locations)",
        certifications: ["GSTC (Global Sustainable Tourism Council) Certification"],
        internshipRequirements: "Working with wildlife reserves or eco-certified hotels.",
        roadmap: ["Sustainability Coordinator", "Ecotourism Consultant", "Director of Sustainable Tourism Protocol"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Destination Marketing Organization (DMO) Executive",
        description: "Promote a specific city, region, or country as an attractive destination for tourists and business conferences, managing massive marketing campaigns.",
        summary: "The marketing directors responsible for putting a specific geographic location on the global tourist map.",
        skills: ["Destination Branding", "Digital Marketing", "Public Relations", "B2B Sales", "Campaign Management"],
        salaryRange: "India: ₹6L - ₹20L | Global: $65K - $120K",
        educationPath: "B.A. Tourism / Mass Communication / Marketing → MBA",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["State Tourism Departments", "City Convention & Visitors Bureaus (CVBs)"],
        futureScope: "Critical role as destinations compete fiercely for global tourist dollars post-pandemic.",
        jobDemandTrend: "Growing",
        governmentJobs: "Maximum. DMOs are typically state or city-funded entities.",
        freelanceOpportunities: "Moderate. Independent destination branding consultants.",
        fieldWork: "Moderate. Attending major global travel marts (e.g., WTM London, ITB Berlin).",
        riskLevel: "Low",
        certifications: ["Certified Destination Management Executive (CDME)"],
        internshipRequirements: "Marketing internships with state tourism boards.",
        roadmap: ["Tourism Marketing Assistant", "PR Manager for DMO", "VP of Destination Marketing", "CEO of Tourism Board"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Aviation / Airline Ground Operations Manager",
        description: "Oversee all airport ground operations for an airline, including ticketing, baggage handling, gate management, and passenger relations to ensure on-time departures.",
        summary: "The managers ensuring smooth, safe, and efficient passenger flow at airports.",
        skills: ["Crisis Management", "Aviation Regulations", "Customer Service Leadership", "Logistics", "Time Management"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $110K",
        educationPath: "B.A. Tourism / BBA Aviation Management",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Airlines", "Airport Authorities", "Ground Handling Agencies"],
        futureScope: "Highly demanding and stable field as total global air traffic continues to multiply.",
        jobDemandTrend: "Stable Growth",
        governmentJobs: "Roles within national airport authorities.",
        freelanceOpportunities: "Low. Institutional aviation role.",
        fieldWork: "High. Constantly moving around the active airport concourse and tarmac.",
        riskLevel: "Moderate (High stress, strict security environments)",
        certifications: ["IATA Airport Operations Certification"],
        internshipRequirements: "Customer service roles at airport terminals.",
        roadmap: ["Check-in Agent", "Duty Manager", "Station Manager", "Head of Ground Operations"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "MICE (Meetings, Incentives, Conferences, Exhibitions) Coordinator",
        description: "Plan and execute massive corporate travel events, international conferences, and trade shows, handling complex logistics for thousands of attendees.",
        summary: "Specialized event planners managing the highly profitable corporate travel sector.",
        skills: ["Large-scale Event Logistics", "Corporate Negotiation", "Budgeting", "Attention to Detail", "Networking"],
        salaryRange: "India: ₹5L - ₹20L | Global: $60K - $110K",
        educationPath: "B.A. Tourism / Event Management",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Event Management Companies", "Corporate Travel Agencies", "Convention Centers"],
        futureScope: "Bouncing back rapidly. Corporate incentives and international trade shows remain essential for global business networking.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Managing state-sponsored international summits (e.g., G20 logistics).",
        freelanceOpportunities: "High. Independent MICE consultants.",
        fieldWork: "High. On-site execution at massive convention centers globally.",
        riskLevel: "Low (Very high stress due to zero margin for error in corporate events)",
        certifications: ["Certified Meeting Professional (CMP)"],
        internshipRequirements: "Event planning internships.",
        roadmap: ["Events Assistant", "MICE Executive", "MICE Manager", "Director of Corporate Events"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Travel Tech Product Manager",
        description: "Develop and manage travel-related software, mobile apps, or booking platforms (like Airbnb, Skyscanner), bridging the gap between tourism operations and software engineering.",
        summary: "Tech-savvy managers building the digital platforms that power modern travel.",
        skills: ["Agile/Scrum", "Understanding of Travel APIs (GDS, NDC)", "UX/UI Principles", "Data Analytics", "Cross-functional Leadership"],
        salaryRange: "India: ₹12L - ₹35L+ | Global: $90K - $180K+",
        educationPath: "B.A. Tourism / B.Tech → MBA or Tech Certifications",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Online Travel Agencies (OTAs - Expedia, MakeMyTrip)", "Travel Tech Startups", "Airlines (Digital Div.)"],
        futureScope: "The most lucrative sub-sector in travel. The industry is entirely dependent on seamless digital booking and AI-driven recommendations.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Developing digital tourism portals for state governments.",
        freelanceOpportunities: "Moderate. Consulting for travel startups.",
        fieldWork: "Low. Primarily office/remote tech work.",
        riskLevel: "Low",
        certifications: ["Product Management Certifications (e.g., CSPO)"],
        internshipRequirements: "Internships at OTAs or tech companies.",
        roadmap: ["Business Analyst", "Product Manager", "Senior Product Manager", "VP of Product (Travel Tech)"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Cruise Director / Entertainment Manager",
        description: "Manage all onboard passenger entertainment, activities, and communication on massive cruise ships, acting as the public face of the vessel.",
        summary: "The charismatic leaders overseeing the passenger experience and activities on cruise ships.",
        skills: ["Public Speaking", "Event Management", "High Charisma", "Crisis De-escalation", "Maritime Safety Basics"],
        salaryRange: "India: ₹8L - ₹25L (Tax free often) | Global: $70K - $130K",
        educationPath: "B.A. Tourism / Hospitality / Performing Arts",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Major Cruise Lines (Royal Caribbean, Carnival, MSC)"],
        futureScope: "Cruise tourism is expanding rapidly globally, requiring dynamic leaders to manage increasingly complex onboard 'mega-resorts'.",
        jobDemandTrend: "Stable",
        governmentJobs: "None.",
        freelanceOpportunities: "Low. Contractual work bound to specific ships/lines.",
        fieldWork: "Maximum. Living and working aboard ships for 4-6 months at a time.",
        riskLevel: "Moderate (Maritime hazards, managing thousands of passengers in isolated environments)",
        certifications: ["STCW (Standards of Training, Certification and Watchkeeping for Seafarers)"],
        internshipRequirements: "Onboard entry-level entertainment or hospitality roles.",
        roadmap: ["Entertainment Staff", "Assistant Cruise Director", "Cruise Director", "Fleet Entertainment Director"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Travel Journalist / Blogger",
        description: "Travel the world to write, photograph, and create video content about destinations, cultures, and hotels for magazines, websites, or personal media channels.",
        summary: "Content creators who document and review global travel experiences.",
        skills: ["Writing / Storytelling", "Photography/Videography", "SEO & Digital Marketing", "Networking", "Adaptability"],
        salaryRange: "India: ₹3L - ₹15L | Global: $40K - $100K+ (Highly variable based on sponsorships)",
        educationPath: "B.A. Journalism / Mass Communication / Tourism",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Travel Magazines (Nat Geo, Condé Nast)", "Digital Media", "Self-Employed"],
        futureScope: "Extremely competitive. Traditional publishing is tough, but successful independent influencers and bloggers command massive audiences and incomes.",
        jobDemandTrend: "Highly Competitive",
        governmentJobs: "Freelance PR writing for state tourism boards.",
        freelanceOpportunities: "Maximum. The majority of this industry is freelance or entrepreneurial.",
        fieldWork: "Maximum. Constant travel.",
        riskLevel: "Moderate (Risks associated with constant global travel to diverse regions)",
        certifications: ["None specific."],
        internshipRequirements: "Writing for indie travel blogs or college magazines.",
        roadmap: ["Freelance Contributor", "Staff Travel Writer", "Senior Editor", "Independent Travel Media Brand Owner"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Adventure Tourism Specialist",
        description: "Design and lead high-adrenaline tours such as mountaineering, white-water rafting, or deep-sea diving, ensuring strict safety protocols in extreme environments.",
        summary: "Experts leading safe but thrilling extreme sports and adventure travel experiences.",
        skills: ["Extreme Sports Proficiency", "Wilderness First Aid", "Risk Management", "Leadership", "Logistics"],
        salaryRange: "India: ₹4L - ₹12L | Global: $45K - $85K",
        educationPath: "B.A. Tourism → Specialized Outdoor/Mountaineering Certifications",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Adventure Travel Companies", "Ski Resorts", "National Park Concessionaires"],
        futureScope: "Growing rapidly as tourists seek 'experience-based' and physically challenging vacations over traditional sightseeing.",
        jobDemandTrend: "High Growth",
        governmentJobs: "Search and rescue advisories, national park management.",
        freelanceOpportunities: "High. Independent mountain guides or dive masters.",
        fieldWork: "Maximum. Working entirely in extreme outdoor environments.",
        riskLevel: "High (Inherent physical dangers of extreme sports and remote wilderness)",
        certifications: ["Wilderness First Responder (WFR), specialized sports certs (PADI, Mountaineering)"],
        internshipRequirements: "Assistant guide roles in adventure camps.",
        roadmap: ["Assistant Outdoor Guide", "Lead Adventure Guide", "Base Camp Manager", "Owner of Adventure Expedition Company"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Medical Tourism Facilitator",
        description: "Coordinate international travel for patients seeking specialized or more affordable medical procedures abroad, managing hospital liaisons, visas, and post-op care logistics.",
        summary: "Specialized agents bridging healthcare, logistics, and international travel for patients.",
        skills: ["Healthcare System Knowledge", "Empathy", "Logistics", "Cross-Cultural Communication", "Confidentiality"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $110K",
        educationPath: "B.A. Tourism / Healthcare Administration",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Specialized Medical Travel Agencies", "Major International Hospitals", "Health Insurance Companies"],
        futureScope: "Explosive growth. As healthcare costs rise in the West, international medical travel for surgeries and wellness retreats is an industry worth billions.",
        jobDemandTrend: "Explosive Growth",
        governmentJobs: "Promoting national medical tourism via state health boards.",
        freelanceOpportunities: "Moderate. Independent medical travel consultants.",
        fieldWork: "Low to Moderate. Inspecting international hospital facilities.",
        riskLevel: "Low",
        certifications: ["Certified Medical Tourism Professional (CMTP)"],
        internshipRequirements: "Patient relations roles in hospitals or specialized agencies.",
        roadmap: ["Patient Coordinator", "Medical Travel Facilitator", "Hospital International Relations Director"]
    },
    {
        domain: "Arts",
        branch: "Tourism and Travel Studies",
        title: "Revenue Manager (Hospitality/Airlines)",
        description: "Use complex data analysis and algorithms to dynamically adjust pricing for hotel rooms, airline seats, or tour packages to maximize overall company profit.",
        summary: "Analytical experts who dictate the fluctuating prices of travel products.",
        skills: ["Data Analytics", "Financial Modeling", "Pricing Strategies", "Yield Management Software", "Critical Thinking"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $75K - $150K",
        educationPath: "BBA Tourism / Finance → MBA or Data Science certification",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Airlines", "Global Hotel Chains (Marriott, Hilton)", "OTAs (Expedia)", "Cruise Lines"],
        futureScope: "Highly critical and lucrative. Algorithms and AI are changing this field, but human oversight to interpret sudden market trends remains essential.",
        jobDemandTrend: "Stable, Highly Valued",
        governmentJobs: "Low. Primarily private corporate sector.",
        freelanceOpportunities: "Moderate. Revenue consulting for independent boutique hotels.",
        fieldWork: "Low. Office-based data crunching.",
        riskLevel: "Low",
        certifications: ["CRME (Certified Revenue Management Executive)"],
        internshipRequirements: "Finance or data internships at hotel corporate offices.",
        roadmap: ["Revenue Analyst", "Revenue Manager", "Regional Director of Revenue", "Chief Commercial Officer"]
    }
];

const seedTourism = async () => {
    try {
        await Career.deleteMany({ branch: "Tourism and Travel Studies" });
        await Career.insertMany(tourismProfessions);
        console.log('Tourism and Travel Studies Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error('DB ERROR:', err.message);
        process.exit(1);
    }
};

seedTourism();
