const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const ecomProfessions = [
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "E-Commerce Manager",
        description: "An E-Commerce Manager oversees the entire online sales operation for a brand. They manage the website interface, coordinate digital marketing campaigns, monitor website analytics, and ensure a seamless customer journey from click to delivery.",
        educationPath: "BBA / B.Com / MBA / Digital Marketing",
        isFormalDegreeMandatory: "Optional",
        certifications: ["Google Analytics", "Shopify/Magento Certification"],
        yearsOfStudy: "3 to 4 Years",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $70,000 - $130,000 per year",
        roadmap: [
            "Executive: E-Commerce Executive",
            "Manager: E-Commerce Manager",
            "Head: Head of E-Commerce",
            "Director: VP of Digital / E-Commerce Director"
        ],
        freelanceOpportunities: "Consulting for traditional brands moving online.",
        remoteWorkPossibilities: "High",
        platformKnowledge: ["Shopify", "Magento", "WooCommerce", "BigCommerce"],
        growthModel: "Launch -> Optimize Conversions -> Scale Marketing -> Expansion",
        futureScope: "As all retail shifts online, the manager who controls the digital storefront is essentially the modern-day retail CEO of a brand.",
        jobDemandTrend: "Very High",
        workNature: "Business-Oriented",
        summary: "The conductor of a brand's digital orchestra, ensuring that marketing, web design, and logistics harmonize to generate online sales."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Online Store Owner",
        description: "An Online Store Owner builds and operates their own Direct-to-Consumer (D2C) brand. They source products, build the website, run the ads, and manage customer service, either handling inventory themselves or using a 3PL (Third Party Logistics) provider.",
        educationPath: "Self-Learning / Digital Marketing / BBA",
        isFormalDegreeMandatory: "No",
        certifications: ["None required. Proven sales metrics matter."],
        yearsOfStudy: "Not Applicable",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Moderate",
        incomePotential: "Unlimited",
        salaryRange: "India: Profit Dependent | Global: Unlimited",
        roadmap: [
            "Launch: Finding Product/Market Fit",
            "Scale: Scaling Ad Spend & Optimizing Supply Chain",
            "Automation: Hiring a team / using 3PL",
            "Expansion/Exit: Selling the brand (e.g., to an aggregator)"
        ],
        freelanceOpportunities: "N/A (Owner)",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["Shopify", "WooCommerce", "Stripe/Razorpay"],
        growthModel: "Launch -> Scale -> Automation -> Expansion",
        futureScope: "The barrier to entry for building a global retail brand has never been lower. Creative founders can build multi-million dollar brands from their laptops.",
        jobDemandTrend: "Very High",
        workNature: "Business-Oriented",
        summary: "A modern digital retail entrepreneur building scalable consumer brands without the overhead of physical brick-and-mortar stores."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Marketplace Manager (Amazon / Flipkart)",
        description: "Marketplace Managers specifically focus on selling a brand's products on massive third-party platforms like Amazon, Flipkart, or Walmart. They navigate complex platform algorithms for SEO, manage aggressive PPC (Pay-Per-Click) campaigns, and ensure strict compliance with platform rules.",
        educationPath: "B.Com / BBA / Specialized E-Commerce Training",
        isFormalDegreeMandatory: "No",
        certifications: ["Amazon Advertising Sponsored Ads Certification"],
        yearsOfStudy: "3 Years",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low (If employed) / Moderate (If agency)",
        incomePotential: "High",
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $60,000 - $110,000 per year",
        roadmap: [
            "Executive: Marketplace Executive / Listing Specialist",
            "Manager: Marketplace / Amazon Manager",
            "Head: Head of Marketplaces",
            "Director: E-Commerce Director"
        ],
        freelanceOpportunities: "High. Many act as fractional managers for multiple brands.",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["Amazon Seller Central", "Flipkart Seller Hub", "Walmart Seller Center"],
        growthModel: "Listing Optimization -> PPC Scaling -> Inventory Management -> Global Marketplaces",
        futureScope: "Over 50% of digital product searches start on Amazon, not Google. Brands desperately need experts who understand how to win 'The Buy Box' on these monolithic platforms.",
        jobDemandTrend: "Very High",
        workNature: "Analytical",
        summary: "A highly specialized algorithmic marketer focused solely on dominating search results and sales within massive, highly competitive digital marketplaces."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Dropshipping Entrepreneur",
        description: "Dropshippers sell products online without ever holding physical inventory. When a customer buys from their site, the order is automatically forwarded to a third-party supplier (often in China) who ships it directly to the customer.",
        educationPath: "Self-Learning (YouTube / Courses)",
        isFormalDegreeMandatory: "No",
        certifications: ["None required."],
        yearsOfStudy: "Not Applicable",
        technicalSkillRequirementLevel: "Low to Moderate",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India & Global: Entirely profit margin dependent",
        roadmap: [
            "Testing: Rapidly testing products with Meta/TikTok Ads",
            "Scaling: Finding a winning product and scaling ad spend",
            "Branding: Transitioning from generic dropshipping to white-labeling",
            "Expansion: Building a legitimate defensible D2C brand"
        ],
        freelanceOpportunities: "N/A (Business Owner)",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["Shopify", "Aliexpress/CJ Dropshipping", "Meta Ads Manager", "TikTok Ads"],
        growthModel: "Test -> Scale -> Brand -> Automate",
        futureScope: "While getting highly competitive, dropshipping remains the ultimate low-risk entry point for learning practical, aggressive digital marketing and e-commerce.",
        jobDemandTrend: "High (As a side-hustle/business)",
        workNature: "Analytical / Business-Oriented",
        summary: "A master of rapid digital marketing, leveraging extreme supply-chain efficiency to sell products globally with minimal upfront risk."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "E-Commerce Operations Manager",
        description: "E-Commerce Operations Managers are responsible for everything that happens *after* the customer clicks 'Buy'. They manage inventory forecasting, warehouse software integration, shipping partner negotiations, and return processing logistics.",
        educationPath: "B.Tech / BBA -> MBA Supply Chain / Operations",
        isFormalDegreeMandatory: "Yes (Preferred for larger brands)",
        certifications: ["Supply Chain Certifications (APICS)"],
        yearsOfStudy: "3 to 5 Years",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low (Salaried Role)",
        incomePotential: "High",
        salaryRange: "India: ₹8 LPA - ₹20 LPA | Global: $70,000 - $120,000 per year",
        roadmap: [
            "Executive: Operations Analyst / Coordinator",
            "Manager: E-Commerce Operations Manager",
            "Head: Head of Supply Chain / Fulfillment",
            "Director: Chief Operating Officer (COO)"
        ],
        freelanceOpportunities: "Operations consulting for scaling D2C brands.",
        remoteWorkPossibilities: "Moderate",
        platformKnowledge: ["ERP Systems", "WMS (Warehouse Management Systems)", "Shipping Aggregators (ShipRocket)"],
        growthModel: "Streamline -> Automate -> Scale Volume -> Global Fulfillment",
        futureScope: "Marketing gets the sale, but operations gets the profit. The ability to deliver goods faster and cheaper is the primary battleground of modern e-commerce (e.g., Amazon Prime).",
        jobDemandTrend: "Stable to High",
        workNature: "Analytical / Technical",
        summary: "The backbone of the digital retail promise, ensuring that physical goods move from warehouses to doorsteps identically to the digital clicks that bought them."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "E-Commerce Analyst",
        description: "E-Commerce Analysts dive deep into website and sales data. They analyze customer heatmaps, track cart abandonment rates, calculate Customer Acquisition Cost (CAC), and provide data-driven recommendations to increase overall sales and profitability.",
        educationPath: "B.Sc Math/Stats / B.Tech / BBA -> Data Analytics Courses",
        isFormalDegreeMandatory: "Yes (Quantitative degree highly preferred)",
        certifications: ["Google Analytics (GA4) Certification", "SQL/Data Visualization certs"],
        yearsOfStudy: "3 to 4 Years",
        technicalSkillRequirementLevel: "High",
        initialInvestmentRequirement: "Low",
        incomePotential: "Moderate to High",
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $65,000 - $110,000 per year",
        roadmap: [
            "Executive: Junior Data Analyst",
            "Manager: E-Commerce Analyst / Senior Analyst",
            "Head: Head of Analytics / Data Science",
            "Director: VP of Data"
        ],
        freelanceOpportunities: "High request for freelance GA4 setup and dashboard creation.",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["Google Analytics 4", "Tableau/PowerBI", "SQL", "Excel"],
        growthModel: "Data Collection -> Visualization -> Insight Generation -> Strategic Implementation",
        futureScope: "The lifeblood of digital business is data. Analysts who can translate a sea of numbers into actionable, money-making business advice are indispensable.",
        jobDemandTrend: "High",
        workNature: "Analytical",
        summary: "The numerical detective of the online store, finding hidden revenue leaks and diagnosing the exact reasons why customers buy or bounce."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Product Listing Specialist",
        description: "Product Listing Specialists create compelling, SEO-optimized product pages. They write persuasive product descriptions, manage high-quality image/video uploads, ensure correct categorization, and input critical backend search terms to improve organic visibility.",
        educationPath: "Any Bachelor's Degree / B.A English",
        isFormalDegreeMandatory: "No",
        certifications: ["SEO Basics (Optional)"],
        yearsOfStudy: "3 Years",
        technicalSkillRequirementLevel: "Low",
        initialInvestmentRequirement: "Low",
        incomePotential: "Low to Moderate",
        salaryRange: "India: ₹3 LPA - ₹8 LPA | Global: $40,000 - $65,000 per year",
        roadmap: [
            "Executive: Catalog Executive / Data Entry",
            "Manager: Product Listing Specialist / SEO Copywriter",
            "Head: Content / Catalog Manager",
            "Director: Head of E-Commerce Content"
        ],
        freelanceOpportunities: "Extremely high on platforms like Upwork/Fiverr.",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["Shopify Admin", "Amazon Seller Central Catalog", "Basic HTML"],
        growthModel: "Data Entry -> SEO Optimization -> Conversion Copywriting -> Content Strategy",
        futureScope: "A great entry-level role into E-commerce. While AI is automating basic descriptions, specialists who can use AI to optimize mass catalogs perfectly remain necessary.",
        jobDemandTrend: "Stable",
        workNature: "Business-Oriented / Content",
        summary: "The digital merchandiser, responsible for making a product look exactly as appealing on a screen as it would on a physical store shelf."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Conversion Rate Optimization (CRO) Specialist",
        description: "CRO Specialists scientifically test variations of a website to maximize the percentage of visitors who make a purchase. They change button colors, rewrite headlines, and restructure checkout flows using A/B testing software.",
        educationPath: "B.Tech / BBA / Psychology -> Specialized CRO/UX training",
        isFormalDegreeMandatory: "Optional",
        certifications: ["Google Optimize (Historical) / VWO / Optimizely Certifications"],
        yearsOfStudy: "3 to 4 Years",
        technicalSkillRequirementLevel: "Moderate to High",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $75,000 - $125,000 per year",
        roadmap: [
            "Executive: UX/UI Analyst",
            "Manager: CRO Specialist",
            "Head: Head of Growth / Optimization",
            "Director: VP of E-Commerce"
        ],
        freelanceOpportunities: "High-ticket freelance consulting for large stores.",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["VWO", "Optimizely", "Hotjar", "Google Analytics"],
        growthModel: "Hypothesis Generation -> A/B Testing -> Implementation -> Scale",
        futureScope: "Traffic is expensive. If a CRO expert can increase a store's conversion rate from 2% to 3%, they increase top-line revenue by 50% without spending an extra dollar on ads. It is one of the highest ROI skills in marketing.",
        jobDemandTrend: "High",
        workNature: "Analytical / Technical",
        summary: "A behavioral scientist and data nerd who uses psychological triggers and statistical testing to turn window-shoppers into paying customers."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "E-Commerce Marketing Manager",
        description: "Focusing purely on driving highly-qualified traffic to the store, E-Commerce Marketing Managers handle digital advertising budgets, coordinate email marketing campaigns, and manage affiliate or influencer partnerships specifically designed to generate direct sales.",
        educationPath: "BBA / B.Com -> MBA Marketing / Proven Ad Results",
        isFormalDegreeMandatory: "Optional",
        certifications: ["Meta Blueprint", "Google Ads Certification", "Klaviyo/Mailchimp"],
        yearsOfStudy: "3 to 5 Years",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India: ₹8 LPA - ₹28 LPA | Global: $75,000 - $130,000 per year",
        roadmap: [
            "Executive: Digital Marketing Executive",
            "Manager: E-Commerce / Performance Marketing Manager",
            "Head: Head of Digital Marketing",
            "Director: Chief Marketing Officer (CMO)"
        ],
        freelanceOpportunities: "Running a specialized performance marketing agency.",
        remoteWorkPossibilities: "High",
        platformKnowledge: ["Meta Ads", "Google Ads", "Klaviyo", "Shopify Analytics"],
        growthModel: "Audience Testing -> CAC Optimization -> LTV Expansion -> Omni-channel Marketing",
        futureScope: "The demand for this role is tied directly to the growth of D2C brands. The ability to profitably acquire customers online is the single most important skill for a young brand's survival.",
        jobDemandTrend: "Very High",
        workNature: "Analytical / Business-Oriented",
        summary: "The aggressive, data-driven marketer responsible for buying the traffic that fuels the entire e-commerce machine."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Fulfillment & Logistics Manager",
        description: "Working closely with E-Commerce Operations, the Fulfillment Manager manages the actual physical warehouses (or the relationship with external 3PL providers). They focus on picking, packing, shipping speed, and reducing return shipping costs.",
        educationPath: "BBA / B.Tech / Diploma in Logistics",
        isFormalDegreeMandatory: "No (Experience heavily outweighs degrees)",
        certifications: ["Logistics & Transportation Certifications"],
        yearsOfStudy: "3 Years",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low",
        incomePotential: "Moderate to High",
        salaryRange: "India: ₹6 LPA - ₹18 LPA | Global: $60,000 - $100,000 per year",
        roadmap: [
            "Executive: Warehouse Supervisor",
            "Manager: Fulfillment / Logistics Manager",
            "Head: Head of Fulfillment",
            "Director: VP of Supply Chain"
        ],
        freelanceOpportunities: "Low. Highly localized operational role.",
        remoteWorkPossibilities: "Low (Requires site visits/warehouse management)",
        platformKnowledge: ["WMS (Warehouse Management Software)", "ShipStation", "Ecom Express/Delhivery panels"],
        growthModel: "Process Standardization -> Tech Integration -> Multi-node Warehouse Expansion",
        futureScope: "Customers now expect 1-or-2-day delivery. Brands that fail at fulfillment lose customers forever. This role ensures the brand promise is physically met.",
        jobDemandTrend: "Stable",
        workNature: "Business-Oriented / Operations",
        summary: "The gritty, detail-oriented operator ensuring that thousands of individual packages safely leave the warehouse and arrive at the correct doorsteps daily."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Catalog Manager",
        description: "Catalog Managers oversee massive databases of thousands or millions of products (think Amazon or Myntra). They ensure data consistency, manage hierarchy and taxonomies, and handle the bulk upload/update of product pricing and inventory levels.",
        educationPath: "B.Sc IT / BBA / B.Com",
        isFormalDegreeMandatory: "Yes",
        certifications: ["Data Management / PIM (Product Information Management) Training"],
        yearsOfStudy: "3 Years",
        technicalSkillRequirementLevel: "Moderate to High",
        initialInvestmentRequirement: "Low",
        incomePotential: "Moderate",
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $55,000 - $95,000 per year",
        roadmap: [
            "Executive: Data Entry Analyst",
            "Manager: Catalog Manager",
            "Head: Head of Catalog / Master Data",
            "Director: VP of Merchandising"
        ],
        freelanceOpportunities: "Moderate (Bulk data clean-up projects).",
        remoteWorkPossibilities: "High",
        platformKnowledge: ["Excel/Google Sheets (Advanced)", "PIM Software (Akeneo, Salsify)", "SQL Basics"],
        growthModel: "Data accuracy -> Automated Updating -> AI-driven taxonomy",
        futureScope: "Crucial for massive marketplaces. Bad data ruins the search experience. Clean, structured catalog data is the unseen foundation of every major retail site.",
        jobDemandTrend: "Stable",
        workNature: "Technical / Analytical",
        summary: "The ultimate organizer of digital retail, maintaining strict hierarchical order over databases containing millions of distinct products."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Performance Marketing for E-Commerce Specialist",
        description: "A hyper-specialized branch of marketing focusing *only* on math-driven ad platforms (Google Shopping, Meta Catalog Sales). They do not care about 'brand awareness'; their only job is to spend $1 on ads and get $3 back in immediate sales.",
        educationPath: "B.Tech / B.Sc Math / Any degree with strong analytical skills",
        isFormalDegreeMandatory: "No",
        certifications: ["Google Ads Search/Shopping", "Meta Certified Media Buying Professional"],
        yearsOfStudy: "3 to 4 Years",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India: ₹7 LPA - ₹25+ LPA | Global: $70,000 - $130,000 per year",
        roadmap: [
            "Executive: Media Buyer Analyst",
            "Manager: Performance Marketing Specialist / Manager",
            "Head: Head of Growth",
            "Director: VP Marketing"
        ],
        freelanceOpportunities: "Massive. Most work for multiple clients concurrently on a retainer basis.",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["Meta Ads", "Google Ads", "TikTok Ads", "Snapchat Ads"],
        growthModel: "Testing -> Scaling ROAS (Return on Ad Spend) -> Cross-platform domination",
        futureScope: "The most directly accountable marketing role. Good performance marketers are essentially printing money for a brand and are compensated accordingly.",
        jobDemandTrend: "Very High",
        workNature: "Analytical / Business-Oriented",
        summary: "A high-stakes, data-obsessed media buyer who treats advertising budgets like a stock market, day-trading for customer acquisitions."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Shopify / WooCommerce Developer",
        description: "E-Commerce Developers build the actual code or use heavily customized templates to create the digital storefront. They build custom themes, create bespoke app integrations, and ensure the website is lightning fast on mobile devices.",
        educationPath: "B.Tech Computer Science / BCA / Coding Bootcamps",
        isFormalDegreeMandatory: "No (Portfolios rule here)",
        certifications: ["Shopify Partner Developer Certifications"],
        yearsOfStudy: "3 to 4 Years",
        technicalSkillRequirementLevel: "High",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India: ₹6 LPA - ₹22 LPA | Global: $70,000 - $130,000 per year",
        roadmap: [
            "Executive: Junior Front-End Developer",
            "Manager: Senior E-Commerce Developer",
            "Head: Tech Lead / Solutions Architect",
            "Director: Chief Technology Officer (CTO)"
        ],
        freelanceOpportunities: "Extremely High. Massive ecosystem of freelance developers.",
        remoteWorkPossibilities: "Very High",
        platformKnowledge: ["Shopify Liquid", "React.js", "PHP (for WooCommerce)", "HTML/CSS/JS"],
        growthModel: "Template Customization -> Custom App Building -> Headless Commerce Architecture",
        futureScope: "While standard templates exist, serious brands need highly customized, extremely fast web applications. Developers who understand both code and retail conversion psychology are highly sought after.",
        jobDemandTrend: "Very High",
        workNature: "Technical",
        summary: "The digital architect and builder who constructs the fast, beautiful, and secure technology that powers modern online shopping."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "E-Commerce Business Consultant",
        description: "E-Commerce Consultants advise traditional brick-and-mortar retail companies on how to transition online, or audit existing online stores to improve their profitability. They provide high-level strategy regarding tech stacks, team hiring, and marketing strategy.",
        educationPath: "MBA / Extensive past E-Commerce Management experience",
        isFormalDegreeMandatory: "Optional (Experience is everything)",
        certifications: ["Platform Specific Architecture Certifications (e.g., Salesforce Commerce Cloud)"],
        yearsOfStudy: "Not Applicable",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India: ₹12 LPA - ₹30+ LPA | Global: $90,000 - $160,000 per year",
        roadmap: [
            "Executive: Junior Consultant (Agency side)",
            "Manager: Senior Consultant",
            "Head: Agency Partner / Fractional E-Commerce Director",
            "Director: Independent Agency Owner"
        ],
        freelanceOpportunities: "This is primarily a freelance / boutique agency role.",
        remoteWorkPossibilities: "High",
        platformKnowledge: ["Broad knowledge of all major SaaS commerce platforms and ERP integrations."],
        growthModel: "Hourly Consulting -> Retainer Contracts -> Profit-Share Agreements",
        futureScope: "Massive legacy brands still struggle with digital transformation. They pay hefty fees to consultants who can guide them through the complex transition without destroying their brand.",
        jobDemandTrend: "High",
        workNature: "Analytical / Business-Oriented",
        summary: "A seasoned veteran of digital commerce acting as a strategic guide for massive companies navigating the shift from physical to digital borders."
    },
    {
        domain: "Commerce",
        branch: "E-Commerce",
        title: "Cross-Border E-Commerce Specialist",
        description: "Cross-Border Specialists focus exclusively on taking a successful domestic brand and selling it internationally. They navigate multi-currency pricing, international tax laws (VAT/GST), and hyper-complex global shipping solutions.",
        educationPath: "BBA / B.Com / IB (International Business)",
        isFormalDegreeMandatory: "Yes (or extremely solid experience)",
        certifications: ["International Trade/Logistics Certifications"],
        yearsOfStudy: "3 to 4 Years",
        technicalSkillRequirementLevel: "Moderate",
        initialInvestmentRequirement: "Low",
        incomePotential: "High",
        salaryRange: "India: ₹8 LPA - ₹25 LPA | Global: $75,000 - $130,000 per year",
        roadmap: [
            "Executive: Global Catalog Executive",
            "Manager: Cross-Border Specialist / Manager",
            "Head: Head of International Expansion",
            "Director: VP Global E-Commerce"
        ],
        freelanceOpportunities: "Consulting for D2C brands looking to launch in the US/EU.",
        remoteWorkPossibilities: "High",
        platformKnowledge: ["Shopify Markets", "Global-e", "Amazon Global Selling", "International Tax Software Avalara"],
        growthModel: "Market Research -> Compliance Validation -> Logistics Setup -> International Marketing",
        futureScope: "For ambitious brands, expanding globally is the logical next step. Navigating the legal and logistical nightmare of cross-border D2C shipping requires highly specialized knowledge.",
        jobDemandTrend: "High",
        workNature: "Analytical / Business-Oriented",
        summary: "The international diplomat of e-commerce, ensuring a company's website can legally and logistically sell and ship to a customer on the other side of the planet."
    }
];

const seedEcomProfessions = async () => {
    try {
        await Career.deleteMany({ branch: "E-Commerce" });
        await Career.insertMany(ecomProfessions);
        console.log('E-Commerce Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedEcomProfessions();
