const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const marketingProfessions = [
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Digital Marketing Specialist",
        description: "Digital Marketing Specialists develop, execute, and manage online marketing campaigns across various digital channels (Search, Social, Email, Web). They analyze metrics to optimize campaigns and drive online brand awareness and lead generation.",
        skills: ["SEO/SEM", "Content Marketing", "Data Analytics (Google Analytics)", "Social Media Strategy", "CRM Management"],
        salaryRange: "India: ₹4 LPA - ₹15 LPA | Global: $50,000 - $90,000 per year",
        educationPath: "BBA/B.Com/BA/B.Sc -> Digital Marketing Certifications -> MBA Marketing (Optional)",
        futureScope: "As all businesses shift aggressively online, the demand for holistic digital marketers who can navigate changing search and social algorithms is practically universal.",
        roadmap: [
            "Executive: Digital Marketing Executive",
            "Specialist: Digital Marketing Specialist",
            "Manager: Digital Marketing Manager",
            "Director: Head of Digital / VP Marketing"
        ],
        certifications: ["Google Ads Certification", "HubSpot Content Marketing", "Meta Blueprint"],
        summary: "A high-demand, tech-oriented marketing role combining creativity with hard data analysis to conquer the online marketplace.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["E-commerce", "SaaS", "Retail", "Agencies", "Healthcare"],
        jobDemandTrend: "Very High",
        governmentJobs: "Contractual roles for 'Digital India' initiatives and state tourism boards.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Massive demand in every modern agency, startup, and corporation.",
        internationalJobOpportunities: "High remote work and international relocation potential.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "Extensive freelance and consulting opportunities.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Brand Manager",
        description: "Brand Managers are responsible for adapting a brand strategy for a company's target market. They maintain brand integrity across all marketing initiatives and communications, acting as the 'guardian' of the brand's public perception.",
        skills: ["Brand Strategy", "Market Research", "Consumer Psychology", "Project Management", "Creative Direction"],
        salaryRange: "India: ₹8 LPA - ₹25+ LPA | Global: $75,000 - $140,000 per year",
        educationPath: "BBA/BA/B.Com -> MBA in Marketing (Highly Preferred)",
        futureScope: "In crowded markets, a strong brand is the only differentiator. Companies pay absolute top dollar for managers who can build emotional connections with consumers.",
        roadmap: [
            "Executive: Assistant Brand Manager",
            "Specialist: Brand Manager",
            "Manager: Senior Brand Manager / Category Head",
            "Director: VP of Brand / Chief Marketing Officer (CMO)"
        ],
        certifications: ["Brand Management Certification (e.g., eCornell)"],
        summary: "A prestigious, heavily strategic role focused on the long-term emotional and financial value of a company's identity.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["FMCG (HUL, P&G)", "Automotive", "Luxury Goods", "Tech Giants"],
        jobDemandTrend: "High",
        governmentJobs: "Limited; mostly applicable in large public sector consumer brands.",
        competitiveExams: ["CAT/XAT (for MBA)"],
        privateSectorOpportunities: "The pinnacle marketing role in FMCG and consumer packaged goods (CPG) companies.",
        internationalJobOpportunities: "Global brand guardianship roles in MNCs.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Brand consulting for startups and rebranding exercises.",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Marketing Manager (General)",
        description: "Marketing Managers oversee a company's overarching marketing strategy. They coordinate various marketing teams (digital, PR, content, events) to ensure cohesive campaigns that meet revenue and growth targets.",
        skills: ["Leadership", "Budgeting", "Integrated Marketing Communications", "Strategic Planning", "Analytics Review"],
        salaryRange: "India: ₹10 LPA - ₹30+ LPA | Global: $85,000 - $160,000 per year",
        educationPath: "BBA/B.Com / B.Tech -> MBA in Marketing -> Relevant Experience",
        futureScope: "A staple leadership role in any business. As marketing channels multiply, the need for a central orchestrator governing the entire budget and strategy is critical.",
        roadmap: [
            "Executive: Marketing Trainee / Coordinator",
            "Specialist: Marketing Executive",
            "Manager: Marketing Manager",
            "Director: Marketing Director / CMO"
        ],
        certifications: ["PMP (Optional)", "Advanced Management Programs"],
        summary: "A cross-functional leadership role balancing creative campaign generation with strict ROI and budget management.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["All Private Sector Industries", "Tech", "Manufacturing", "Finance"],
        jobDemandTrend: "High",
        governmentJobs: "Marketing Officer roles in PSUs (e.g., Banking, Oil Companies).",
        competitiveExams: ["IBPS SO (Marketing)"],
        privateSectorOpportunities: "Required in every mid-to-large scale business globally.",
        internationalJobOpportunities: "Regional Marketing Head roles serving multiple countries.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Fractional CMO / Marketing Consultant roles for SMEs.",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Social Media Marketing Manager",
        description: "Social Media Managers curate, create, and manage a brand's presence across platforms like Instagram, LinkedIn, TikTok, and X. They build community, handle customer service issues publicly, and drive viral organic growth.",
        skills: ["Social Media Algorithms", "Community Management", "Copywriting", "Basic Graphic/Video Editing", "Trend Analysis"],
        salaryRange: "India: ₹3.5 LPA - ₹12 LPA | Global: $45,000 - $85,000 per year",
        educationPath: "Any Bachelor's Degree -> Social Media Marketing Courses",
        futureScope: "Social media is now the primary discovery engine for brands. Specialists who understand platform algorithms and cultural trends have massive leverage.",
        roadmap: [
            "Executive: Social Media Executive",
            "Specialist: Social Media Specialist",
            "Manager: Social Media Manager",
            "Director: Head of Social Media / Communications Director"
        ],
        certifications: ["Hootsuite Social Marketing", "Meta Social Media Marketing Professional"],
        summary: "A highly creative, always-on career requiring an innate understanding of viral internet culture and brand voice.",
        yearsOfStudy: "3 Years",
        industriesHiring: ["Agencies", "Media/Entertainment", "D2C Brands", "Corporate Comms"],
        jobDemandTrend: "Very High",
        governmentJobs: "Managing official social media handles for ministries and politicians.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Massive demand across all B2C and increasingly B2B companies.",
        internationalJobOpportunities: "High remote work viability globally.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "Highly prevalent. Many manage accounts for multiple small businesses simultaneously.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Content Marketing Strategist",
        description: "Content Marketing Strategists plan, design, and manage the creation of valuable content (blogs, whitepapers, videos, podcasts) to attract and retain a clearly defined audience, ultimately driving profitable customer action.",
        skills: ["Copywriting/Editing", "Content Management Systems (CMS)", "SEO Foundations", "Storytelling", "Editorial Planning"],
        salaryRange: "India: ₹5 LPA - ₹16 LPA | Global: $60,000 - $100,000 per year",
        educationPath: "BA English/Journalism / Mass Comm -> Marketing Certifications",
        futureScope: "Traditional advertising is losing trust. 'Inbound marketing' through high-quality, educational, or entertaining content is the future of sustainable brand growth.",
        roadmap: [
            "Executive: Content Writer / Creator",
            "Specialist: Content Strategist",
            "Manager: Content Marketing Manager",
            "Director: Head of Content / VP Brand"
        ],
        certifications: ["HubSpot Content Marketing", "Various Copywriting Certifications"],
        summary: "A career tailored for exceptional writers and storytellers aiming to turn brand narratives into tangible revenue.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["SaaS", "B2B Tech", "EdTech", "Media Publishing", "Agencies"],
        jobDemandTrend: "High",
        governmentJobs: "Content creation for state information departments and public awareness campaigns.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Critical for B2B companies where complex products require deep educational content.",
        internationalJobOpportunities: "High remote potential if proficient in native-level English/target language.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "One of the most robust freelance markets globally (freelance writing/strategy).",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "SEO Specialist",
        description: "Search Engine Optimization (SEO) Specialists analyze, review, and implement changes to websites so they are optimized for search engines. This means maximizing the traffic to a site by improving page rank within search engines like Google.",
        skills: ["Technical SEO", "Keyword Research", "Link Building", "HTML/CSS Basics", "Data Analytics (Ahrefs/SEMrush)"],
        salaryRange: "India: ₹4 LPA - ₹15+ LPA | Global: $55,000 - $95,000 per year",
        educationPath: "Any Bachelor's Degree -> Specialized SEO Training/Certifications",
        futureScope: "Despite AI shifts, search intent remains the highest converting traffic source. Technical SEO experts who can navigate continuously updating search algorithms are inherently valuable.",
        roadmap: [
            "Executive: SEO Executive",
            "Specialist: SEO Analyst / Specialist",
            "Manager: SEO Manager",
            "Director: VP of Organic Growth / VP Marketing"
        ],
        certifications: ["Google Analytics IQ", "SEMrush/Ahrefs Certifications"],
        summary: "A highly analytical, technical marketing role focused entirely on dominating organic search results and driving 'free' traffic.",
        yearsOfStudy: "3 Years",
        industriesHiring: ["Digital Marketing Agencies", "E-commerce", "Media Publishers", "SaaS"],
        jobDemandTrend: "High",
        governmentJobs: "Rare, mostly outsourced to private agencies.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Vital for e-commerce and media companies where organic traffic equals revenue.",
        internationalJobOpportunities: "Extremely high remote work viability.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "Massive freelance and agency-building potential.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Performance Marketing Manager",
        description: "Performance Marketing Managers handle paid advertising campaigns (PPC). They manage massive budgets on Google, Meta, and LinkedIn Ads, constantly tweaking bids and ad copy to achieve the lowest possible Customer Acquisition Cost (CAC).",
        skills: ["PPC Advertising", "Data Analysis", "A/B Testing", "Budget Management", "Conversion Rate Optimization (CRO)"],
        salaryRange: "India: ₹6 LPA - ₹25+ LPA | Global: $70,000 - $130,000+ per year",
        educationPath: "BBA/B.Tech/B.Com / B.Sc Math -> MBA (Optional) -> Deep Platform Expertise",
        futureScope: "The most directly impact-driven marketing role. If you can spend $1 and reliably track that it made the company $3, you will possess limitless job security and high compensation.",
        roadmap: [
            "Executive: Paid Media Analyst",
            "Specialist: Performance Marketing Specialist",
            "Manager: Performance Marketing Manager",
            "Director: Head of Growth / VP Performance Marketing"
        ],
        certifications: ["Google Ads Certification", "Meta Certified Media Buying Professional"],
        summary: "A high-stakes, data-obsessed role managing large advertising budgets to instantly generate measurable sales and leads.",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Ad Agencies", "E-commerce", "Fintech", "D2C Brands", "EdTech"],
        jobDemandTrend: "Very High",
        governmentJobs: "None; strictly a private/corporate sector optimization role.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Some of the highest-paid non-leadership marketing roles in tech startups.",
        internationalJobOpportunities: "High remote potential; managing global ad accounts.",
        remoteWorkPossibilities: "High",
        freelanceOpportunities: "High demand for freelance media buyers managing SME ad accounts.",
        licenseRequired: "None",
        riskLevel: "Moderate (High budget handling responsibility)"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Market Research Analyst (Marketing)",
        description: "Market Research Analysts in marketing departments study consumer behavior and competitive landscapes. They run focus groups, surveys, and analyze market data to guide product development, pricing strategy, and marketing messaging.",
        skills: ["Survey Design", "Qualitative/Quantitative Research", "SPSS/Excel", "Presentation Skills", "Consumer Psychology"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $60,000 - $100,000 per year",
        educationPath: "B.Sc Statistics / BBA / BA Psychology -> MBA Marketing or M.Sc Stats",
        futureScope: "Essential for avoiding catastrophic product launches. Data-backed decision making is becoming the standard across all corporate marketing departments.",
        roadmap: [
            "Executive: Research Executive",
            "Specialist: Market Research Analyst",
            "Manager: Consumer Insights Manager",
            "Director: Director of Market Research / VP Strategy"
        ],
        certifications: ["Market Research Society (MRS) Certifications"],
        summary: "The intelligence-gathering wing of marketing, ensuring campaigns and products align perfectly with hidden consumer desires.",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Market Research Agencies (Nielsen, Kantar)", "FMCG", "Automotive", "Consulting"],
        jobDemandTrend: "Stable",
        governmentJobs: "Roles in census operations, demographic studies, and tourism boards.",
        competitiveExams: ["None specific."],
        privateSectorOpportunities: "Core roles in large multinational corporations driving multi-million dollar product decisions.",
        internationalJobOpportunities: "Global consumer insight roles in MNC HQs.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Consulting projects for startups needing market viability studies.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Advertising Manager",
        description: "Advertising Managers oversee the creation and execution of large-scale advertising campaigns (TV, Print, Billboards, Digital media buys). They work closely with creative agencies and media planners to maximize ad impact.",
        skills: ["Creative Judgment", "Media Buying", "Campaign Management", "Negotiation", "Budget Optimization"],
        salaryRange: "India: ₹8 LPA - ₹20+ LPA | Global: $70,000 - $130,000 per year",
        educationPath: "BBA / BA Mass Comm -> MBA in Advertising/Marketing",
        futureScope: "While shifting heavily toward digital, omni-channel advertising (combining offline scale with online precision) remains the cornerstone of massive brand launches.",
        roadmap: [
            "Executive: Account Executive (Agency side) / Ad Coordinator",
            "Specialist: Advertising Executive",
            "Manager: Advertising Manager / Account Director",
            "Director: Group Account Director / VP Advertising"
        ],
        certifications: ["None strictly required."],
        summary: "A classic 'Mad Men' style role focused on high-visibility, big-budget campaigns across traditional and digital media.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Ad Agencies (Ogilvy, McCann)", "Media Conglomerates", "FMCG", "Telecom"],
        jobDemandTrend: "Stable",
        governmentJobs: "DAVP (Directorate of Advertising & Visual Publicity) roles for government campaigns.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "High demand in top-tier advertising agencies and large corporate marketing divisions.",
        internationalJobOpportunities: "Account management roles in global ad agency networks.",
        remoteWorkPossibilities: "Low to Moderate (Highly collaborative role)",
        freelanceOpportunities: "Creative consulting and freelance ad direction.",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Public Relations (PR) Manager",
        description: "PR Managers build and protect the pristine public image of a company or individual. They write press releases, mitigate media crises, build relationships with journalists, and secure favorable, non-paid media coverage.",
        skills: ["Media Relations", "Crisis Communication", "Exceptional Writing", "Networking", "Event Management"],
        salaryRange: "India: ₹6 LPA - ₹18+ LPA | Global: $65,000 - $120,000 per year",
        educationPath: "BA Journalism / Mass Comm -> Master's in PR / Corporate Communications",
        futureScope: "In an era where a single bad tweet can wipe billions off a company's market cap, expert crisis communicators and positive narrative builders are invaluable.",
        roadmap: [
            "Executive: PR Executive",
            "Specialist: PR Specialist",
            "Manager: PR Manager / Corporate Communications Manager",
            "Director: VP of Communications / Chief Communications Officer (CCO)"
        ],
        certifications: ["PRSA (Public Relations Society of America) Certifications"],
        summary: "A high-stakes, networking-heavy role acting as the official voice and shield of a brand in the public and media eyes.",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["PR Agencies (Edelman, Weber Shandwick)", "Corporate Comms", "Politics", "Entertainment"],
        jobDemandTrend: "High",
        governmentJobs: "PRO (Public Relations Officer) roles in defense, ministries, and PSUs.",
        competitiveExams: ["UPSC (Information Service)"],
        privateSectorOpportunities: "Crucial for tech giants, troubled industries, and high-profile celebrities/executives.",
        internationalJobOpportunities: "Global corporate communications spanning multiple jurisdictions.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Independent PR consultants for startups and personal branding for executives.",
        licenseRequired: "None",
        riskLevel: "High (During corporate crisis events)"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Email Marketing Specialist",
        description: "Email Marketing Specialists create, send, and optimize email campaigns. They manage massive subscriber databases, design email automation flows, and focus on maximizing open rates, click-through rates, and customer retention.",
        skills: ["Email Automation (Klaviyo/Mailchimp)", "Copywriting", "A/B Testing", "List Segmentation", "Basic HTML/Design"],
        salaryRange: "India: ₹4 LPA - ₹12 LPA | Global: $55,000 - $90,000 per year",
        educationPath: "Any Bachelor's Degree -> CRM/Email Marketing Certifications",
        futureScope: "Email remains the highest ROI marketing channel globally because it is an 'owned' audience (unlike social media followers). Retaining customers via email is a forever-demand skill.",
        roadmap: [
            "Executive: Email Marketing Executive",
            "Specialist: Email Marketing Specialist / CRM Specialist",
            "Manager: CRM / Retention Marketing Manager",
            "Director: VP of Lifecycle Marketing"
        ],
        certifications: ["Klaviyo Product Certification", "HubSpot Email Marketing"],
        summary: "A specialized digital role focused intensely on customer retention, repeat purchases, and direct-response copywriting.",
        yearsOfStudy: "3 Years",
        industriesHiring: ["E-commerce", "SaaS", "Media Newsletters", "B2B Tech"],
        jobDemandTrend: "High",
        governmentJobs: "Rare.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Vital for D2C/E-commerce brands where lifetime customer value (LTV) dictates profitability.",
        internationalJobOpportunities: "Extremely high remote work viability.",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "Massive freelance market; many set up complex automation flows as one-off high-ticket projects.",
        licenseRequired: "None",
        riskLevel: "Low"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Influencer Marketing Manager",
        description: "Influencer Marketing Managers identify, negotiate with, and manage relationships with social media creators. They integrate influencers into broader marketing campaigns to leverage their niche audiences and credibility.",
        skills: ["Networking/Negotiation", "Contract Management", "Trend Spotting", "Campaign Metrics Analysis", "Project Management"],
        salaryRange: "India: ₹5 LPA - ₹15 LPA | Global: $60,000 - $100,000 per year",
        educationPath: "BBA / Mass Comm / PR -> Industry Experience",
        futureScope: "As ad-blockers rise and consumers trust individuals over faceless brands, influencer marketing has become a multi-billion dollar mandatory strategy for consumer brands.",
        roadmap: [
            "Executive: Influencer Outreach Coordinator",
            "Specialist: Influencer Marketing Specialist",
            "Manager: Influencer Campaign Manager",
            "Director: Head of Creator Partnerships"
        ],
        certifications: ["None primarily required."],
        summary: "A modern, relationship-driven role bridging the gap between corporate brands and internet celebrities.",
        yearsOfStudy: "3 Years",
        industriesHiring: ["Fashion/Beauty", "Gaming", "Consumer Tech", "Agencies", "D2C Brands"],
        jobDemandTrend: "Very High",
        governmentJobs: "Increasingly used for digital awareness campaigns (e.g., Swachh Bharat).",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Extensive in lifestyle, fashion, and consumer tech sectors.",
        internationalJobOpportunities: "Managing global influencer campaigns remotely.",
        remoteWorkPossibilities: "High",
        freelanceOpportunities: "Consultant roles matching brands with specific creator niches.",
        licenseRequired: "None",
        riskLevel: "Moderate (Risk of influencer scandals)"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Growth Hacker",
        description: "Growth Hackers (or Growth Marketers) use rapid experimentation across marketing channels, product design, and engineering to identify the most efficient ways to grow a business. They completely disregard traditional marketing for raw metric hacking.",
        skills: ["A/B Testing", "Data Scraping", "Viral Mechanics", "Funnel Optimization", "Basic Coding/Automation"],
        salaryRange: "India: ₹8 LPA - ₹25+ LPA (Often includes equity) | Global: $80,000 - $150,000+ per year",
        educationPath: "B.Tech / B.Sc Math / Deep self-taught marketing -> Real world startup experience",
        futureScope: "The apex role in the startup ecosystem. Companies pay immense premiums for professionals who can artificially engineer viral user acquisition without massive ad spends.",
        roadmap: [
            "Executive: Marketing Analyst",
            "Specialist: Growth Marketer",
            "Manager: Head of Growth",
            "Director: Chief Revenue Officer / VP Growth"
        ],
        certifications: ["Reforge Programs (Highly respected in Silicon Valley)"],
        summary: "A highly analytical, slightly technical marketing role obsessed solely with rapid, scalable user and revenue acquisition.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Tech Startups", "SaaS", "Consumer Apps", "Web3/Crypto"],
        jobDemandTrend: "Very High",
        governmentJobs: "None. Strictly startup/tech focused.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Foundational early hires in heavily funded tech startups.",
        internationalJobOpportunities: "Massive demand in global tech hubs (SF, NY, London, Bangalore).",
        remoteWorkPossibilities: "Very High",
        freelanceOpportunities: "Growth consulting for early-stage startups on retainer.",
        licenseRequired: "None",
        riskLevel: "High (Startup environments)"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Product Marketing Manager (PMM)",
        description: "Product Marketing Managers (PMMs) sit at the intersection of product development, sales, and marketing. They dictate product positioning, messaging, and go-to-market strategy, ensuring the sales team knows how to sell the product's value.",
        skills: ["Go-to-Market Strategy", "Product Positioning", "Sales Enablement", "Competitor Analysis", "Cross-functional Leadership"],
        salaryRange: "India: ₹12 LPA - ₹35+ LPA | Global: $90,000 - $180,000 per year",
        educationPath: "B.Tech / BBA -> MBA Marketing (Highly Preferred)",
        futureScope: "Considered one of the most prestigious roles in tech marketing. A great product dies without great positioning; PMMs ensure the market fundamentally understands 'why' they need the product.",
        roadmap: [
            "Executive: Associate PMM",
            "Specialist: Product Marketing Manager",
            "Manager: Senior PMM",
            "Director: VP of Product Marketing / CMO"
        ],
        certifications: ["Pragmatic Institute Certifications", "Product Marketing Alliance (PMA) Certifications"],
        summary: "An elite strategic role ensuring that complex tech or corporate products are perfectly packaged, priced, and explained to the target buyer.",
        yearsOfStudy: "5 Years",
        industriesHiring: ["SaaS", "Enterprise Tech", "Hardware/Electronics", "Fintech"],
        jobDemandTrend: "Very High",
        governmentJobs: "None.",
        competitiveExams: ["CAT/GMAT (for MBA)"],
        privateSectorOpportunities: "Crucial roles in major tech companies (Salesforce, Microsoft, Adobe, Atlassian).",
        internationalJobOpportunities: "Global launch management roles in tech MNCs.",
        remoteWorkPossibilities: "Moderate to High",
        freelanceOpportunities: "Consulting on go-to-market strategies for SaaS launches.",
        licenseRequired: "None",
        riskLevel: "Moderate"
    },
    {
        domain: "Commerce",
        branch: "Marketing",
        title: "Media Marketing Planner",
        description: "Media Planners determine the best combination of media platforms to achieve a marketing campaign's objectives. They research audience behavior to decide whether a budget should be spent on TV, Meta Ads, billboards, or podcasts.",
        skills: ["Media Math / Analytics", "Negotiation", "Consumer Research", "Budget Allocation", "Strategic Thinking"],
        salaryRange: "India: ₹5 LPA - ₹18 LPA | Global: $60,000 - $110,000 per year",
        educationPath: "BBA / BA Mass Comm / B.Sc Stats -> Advertising/Media degrees",
        futureScope: "As the number of media channels fragments (Streaming, Web3, DOOH, Social), figuring out exactly *where* to put ad money is increasingly complex and vital.",
        roadmap: [
            "Executive: Media Assistant / Executive",
            "Specialist: Media Planner / Buyer",
            "Manager: Media Planning Manager",
            "Director: Media Director / Head of Strategy"
        ],
        certifications: ["Certifications from media buying associations."],
        summary: "The financial brains behind large advertising campaigns, ensuring every dollar is spent on the exact medium the target audience is actually watching.",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Media Buying Agencies (GroupM, Dentsu)", "Large Corporate Marketing Departments"],
        jobDemandTrend: "Stable",
        governmentJobs: "Roles in Information and Broadcasting ministry coordinating public awareness campaigns.",
        competitiveExams: ["None"],
        privateSectorOpportunities: "Dominant in massive global media agency networks handling Fortune 500 ad budgets.",
        internationalJobOpportunities: "Transferable skills valid across global media networks.",
        remoteWorkPossibilities: "Moderate",
        freelanceOpportunities: "Independent media buying consultant.",
        licenseRequired: "None",
        riskLevel: "Low"
    }
];

const seedMarketingProfessions = async () => {
    try {
        await Career.deleteMany({ branch: "Marketing" });
        await Career.insertMany(marketingProfessions);
        console.log('Marketing Professions Seeded Successfully!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedMarketingProfessions();
