const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const psychologyProfessions = [
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Clinical Psychologist",
        description: "Diagnose and treat mental, emotional, and behavioral disorders ranging from short-term crises to severe, chronic conditions like schizophrenia or severe depression.",
        summary: "Licensed professionals who diagnose and treat severe mental health disorders using psychotherapy and clinical assessments.",
        skills: ["Psychological Diagnostics (DSM-5)", "Cognitive Behavioral Therapy (CBT)", "Crisis Intervention", "Empathy", "Clinical Assessment"],
        salaryRange: "India: ₹6L - ₹20L | Global: $70K - $130K",
        educationPath: "B.A./B.Sc. Psychology → M.A./M.Sc. Clinical Psychology → M.Phil. or Psy.D. / Ph.D.",
        yearsOfStudy: "7 to 9 Years",
        industriesHiring: ["Hospitals", "Private Clinics", "Rehabilitation Centers", "Mental Health Facilities"],
        futureScope: "Extremely high. The global mental health crisis has created a massive shortage of licensed clinical psychologists.",
        jobDemandTrend: "High Growth",
        licenseRequired: "RCI License (India) / State Board License (US/UK)",
        governmentJobs: "High. State hospitals, military veterans affairs, and prison systems.",
        privateSectorOpportunities: "Maximum. Private practice is highly lucrative. Corporate Employee Assistance Programs (EAPs) also hire them.",
        hospitalClinicOpportunities: "Maximum. This is the primary work environment for clinical psychologists.",
        internshipRequirements: "Rigorous 1 to 2-year supervised clinical internship/residency before licensing.",
        roadmap: ["Psychology Degree", "Master's & M.Phil/Ph.D.", "Supervised Clinical Hours", "Licensed Clinical Psychologist"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Counseling Psychologist",
        description: "Help people with physical, emotional, and mental health issues improve their sense of well-being, alleviate feelings of distress, and resolve crises in relationships or work.",
        summary: "Therapists focusing on helping individuals manage daily life stresses, relationships, and emotional wellbeing.",
        skills: ["Active Listening", "Counseling Techniques", "Couples Therapy", "Group Facilitation", "Conflict Resolution"],
        salaryRange: "India: ₹4L - ₹15L | Global: $60K - $110K",
        educationPath: "B.A. Psychology → M.A. Counseling Psychology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Educational Institutions", "Private Practice", "Corporations (HR/Wellness)", "Community Centers"],
        futureScope: "Very Strong. The stigma around therapy is dissolving globally, leading to mass adoption of counseling services.",
        jobDemandTrend: "High Growth",
        licenseRequired: "Varies by region (Licensed Professional Counselor - LPC in the US).",
        governmentJobs: "Moderate. Working in public health clinics or military wellness programs.",
        privateSectorOpportunities: "High. Setting up private counseling practices or working for online therapy platforms (e.g., BetterHelp).",
        hospitalClinicOpportunities: "Moderate. Focused more on outpatient clinics than inpatient psychiatric wards.",
        internshipRequirements: "Completion of practicum hours (usually 500-1000 hours) during the Master's program.",
        roadmap: ["Bachelor's Degree", "M.A. Counseling", "Practicum & Licensing Exam", "Private Practitioner"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Arts Educational Psychologist",
        description: "Study how people learn, including teaching methods, instructional processes, and individual differences in learning. They design better curriculums and educational interventions.",
        summary: "Experts who study the science of learning to create better educational systems and interventions.",
        skills: ["Educational Assessment", "Learning Theories", "Special Education Knowledge", "Curriculum Design", "Psychometrics"],
        salaryRange: "India: ₹4L - ₹12L | Global: $65K - $115K",
        educationPath: "B.A. Psychology/Education → M.A. Educational Psychology → Ph.D. (Optional)",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "School Districts", "Educational Tech Companies (EdTech)", "Government Education Boards"],
        futureScope: "Steady. Crucial for developing inclusive learning modules for neurodivergent students (ADHD, Autism).",
        jobDemandTrend: "Stable",
        licenseRequired: "Usually requires state certification for school systems.",
        governmentJobs: "High. State and federal departments of education.",
        privateSectorOpportunities: "Growing. EdTech companies aggressively hire them to design scientifically backed learning apps.",
        hospitalClinicOpportunities: "Low. Primarily based in academic settings.",
        internshipRequirements: "Practicum within an educational or school setting.",
        roadmap: ["Degree in Psychology/Education", "Master's Degree", "School District Consultant", "Senior Educational Theorist"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Arts Child Psychologist",
        description: "Specialize entirely in the psychological development, emotional well-being, and behavioral issues of infants, toddlers, children, and adolescents.",
        summary: "Specialized clinical psychologists focused entirely on treating emotional and behavioral disorders in children.",
        skills: ["Child Development Theory", "Play Therapy", "Family Systems Therapy", "Autism Spectrum Diagnostics", "Patience"],
        salaryRange: "India: ₹5L - ₹18L | Global: $70K - $125K",
        educationPath: "B.A. Psychology → M.A. Clinical Child Psychology → Ph.D. / Psy.D.",
        yearsOfStudy: "7 to 9 Years",
        industriesHiring: ["Children's Hospitals", "Pediatric Clinics", "Schools", "Private Practice"],
        futureScope: "Extremely high. Rates of anxiety and depression among adolescents are rising, creating massive demand for pediatric specialists.",
        jobDemandTrend: "High Growth",
        licenseRequired: "Clinical License Required (e.g., RCI in India).",
        governmentJobs: "Moderate. State-run child welfare departments.",
        privateSectorOpportunities: "Maximum. Highly lucrative private practices catering specifically to pediatric mental health.",
        hospitalClinicOpportunities: "Maximum. Essential staff in pediatric neurology and psychiatric wards.",
        internshipRequirements: "1-2 years of supervised clinical experience specifically with children.",
        roadmap: ["Psychology Degree", "Doctorate with Child Focus", "Pediatric Residency", "Licensed Child Psychologist"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Arts Industrial Psychologist",
        description: "Apply psychological principles to the workplace. They focus on improving employee productivity, wellbeing, organizational structure, and hiring processes.",
        summary: "The psychologists of the corporate world, optimizing workplace culture, hiring, and employee productivity.",
        skills: ["Organizational Behavior", "Talent Assessment", "Statistical Analytics", "Conflict Management", "Corporate Strategy"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $80K - $150K+",
        educationPath: "B.A. Psychology/Business → M.A. I/O Psychology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Fortune 500 Companies", "Management Consulting Firms (McKinsey, BCG)", "HR Departments"],
        futureScope: "Incredibly lucrative. Companies constantly seek data-driven ways to reduce turnover and increase employee satisfaction.",
        jobDemandTrend: "High Growth",
        licenseRequired: "None strictly required, though board certification exists.",
        governmentJobs: "Moderate. Improving structural efficiency in massive military or civil service bureaucracies.",
        privateSectorOpportunities: "Maximum. This is arguably the highest-paying branch of psychology in the private sector.",
        hospitalClinicOpportunities: "Low. Almost exclusively corporate.",
        internshipRequirements: "Corporate HR or management consulting internships.",
        roadmap: ["Psychology/Business degree", "M.A. I/O Psych", "HR/Talent Consultant", "VP of Organizational Development"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Arts Sports Psychologist",
        description: "Work with athletes to improve focus, overcome performance anxiety, recover from injuries emotionally, and optimize overall athletic performance and teamwork.",
        summary: "Specialists who help professional athletes master the mental game of sports to achieve peak performance.",
        skills: ["Performance Coaching", "Motivation Theory", "Anxiety Management", "Kinesiology basics", "Resilience Training"],
        salaryRange: "India: ₹5L - ₹15L | Global: $65K - $120K+",
        educationPath: "B.A. Psychology → M.A. Sports Psychology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Professional Sports Teams (IPL, NBA, NFL)", "Olympic Committees", "University Athletics", "Private Coaching"],
        futureScope: "Growing rapidly. Professional sports franchises now recognize mental health is as critical as physical conditioning.",
        jobDemandTrend: "Growing (Niche but Lucrative)",
        licenseRequired: "Clinical license required if treating clinical disorders (e.g., eating disorders in athletes), otherwise specialized certification.",
        governmentJobs: "Low. Mainly associated with national sports institutes (like SAI in India).",
        privateSectorOpportunities: "Maximum. Employed by private leagues and wealthy individual athletes.",
        hospitalClinicOpportunities: "Low. Usually operate in training facilities or on the road with teams.",
        internshipRequirements: "Shadowing experienced sports psychologists or working with collegiate teams.",
        roadmap: ["Psychology degree", "M.A. Sports Psychology", "Collegiate team counselor", "Lead Psychologist for Pro Team"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Arts Forensic Psychologist",
        description: "Apply psychology to the criminal justice system. They evaluate defendants' mental competency to stand trial, assess the risk of re-offending, and provide expert testimony in court.",
        summary: "The intersection of psychology and law, evaluating criminals and providing expert testimony in the justice system.",
        skills: ["Risk Assessment", "Legal/Court Procedures", "Clinical Diagnostics", "Psychopathy Evaluation", "Objective Report Writing"],
        salaryRange: "India: ₹6L - ₹15L | Global: $70K - $130K",
        educationPath: "B.A. Psychology → M.A. Forensic Psychology → Ph.D. (Preferred)",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Prisons/Correctional Facilities", "Law Enforcement Agencies", "Courts", "Private Legal Consulting"],
        futureScope: "Steady. Always required by the legal system to ensure fair trials and evaluate parole eligibility.",
        jobDemandTrend: "Stable",
        licenseRequired: "Clinical Psychologist License is usually mandatory to testify in court.",
        governmentJobs: "Maximum. Heavily integrated with the state justice and prison systems.",
        privateSectorOpportunities: "High. Working as high-paid expert witnesses for private defense attorneys.",
        hospitalClinicOpportunities: "Moderate. Working in high-security forensic psychiatric hospitals.",
        internshipRequirements: "Clinical internships within correctional facilities or courts.",
        roadmap: ["Psychology Degree", "Ph.D. Forensic/Clinical", "Prison System Evaluator", "Expert Legal Consultant"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Arts Rehabilitation Psychologist",
        description: "Help individuals recover and adapt after suffering severe physical injuries, chronic illnesses, strokes, or trauma that results in long-term disability.",
        summary: "Therapists assisting patients in regaining their independence and mental stability after life-altering injuries.",
        skills: ["Trauma Therapy", "Neuropsychology Basics", "Patience", "Grief Counseling", "Interdisciplinary Medical Collaboration"],
        salaryRange: "India: ₹4L - ₹12L | Global: $65K - $115K",
        educationPath: "B.A. Psychology → M.A. Rehabilitation Psychology",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Physical Rehab Centers", "Veterans Affairs Hospitals", "Spinal Cord Injury Units", "NGOs"],
        futureScope: "High demand. As medical tech saves more lives from severe trauma, rehabilitation psychologists are needed for the aftermath.",
        jobDemandTrend: "Steady",
        licenseRequired: "Clinical or Counseling License usually required.",
        governmentJobs: "High. Working extensively with military veterans and state disability boards.",
        privateSectorOpportunities: "Moderate. Specialized private trauma centers.",
        hospitalClinicOpportunities: "Maximum. Integrated closely with medical doctors and physical therapists in hospitals.",
        internshipRequirements: "Clinical practicum in a hospital rehab unit.",
        roadmap: ["Psychology degree", "Master's specialization", "Hospital trainee", "Lead Rehabilitation Psychologist"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Behavioral Therapist",
        description: "Focus on modifying harmful or disruptive behaviors through conditioning techniques. They prominently work with autism spectrum disorders using Applied Behavior Analysis (ABA).",
        summary: "Specialists who use targeted conditioning techniques to replace harmful behaviors with positive ones.",
        skills: ["Applied Behavior Analysis (ABA)", "Data Tracking", "Patience", "Operant Conditioning", "Special Education"],
        salaryRange: "India: ₹3L - ₹10L | Global: $50K - $90K",
        educationPath: "B.A. Psychology → Specialized Certification (BCBA)",
        yearsOfStudy: "4 to 5 Years",
        industriesHiring: ["Autism Treatment Centers", "Schools", "Group Homes", "Private Practice"],
        futureScope: "Massive demand, particularly for Board Certified Behavior Analysts (BCBAs) dealing with the rising diagnosis rates of Autism.",
        jobDemandTrend: "High Growth",
        licenseRequired: "Board Certified Behavior Analyst (BCBA) or equivalent.",
        governmentJobs: "Moderate. State-funded disability support systems.",
        privateSectorOpportunities: "High. Private autism therapy clinics and in-home therapy services.",
        hospitalClinicOpportunities: "High. Associated with pediatric development clinics.",
        internshipRequirements: "1500+ hours of supervised fieldwork for BCBA certification.",
        roadmap: ["Bachelor's Degree", "Master's or ABA coursework", "Supervised Fieldwork", "Licensed BCBA"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Mental Health Counselor",
        description: "Provide general counseling services for individuals dealing with substance abuse, anxiety, grief, and self-esteem issues in community settings.",
        summary: "Frontline mental health professionals providing accessible therapy and support to the community.",
        skills: ["Empathic Listening", "Addiction Counseling", "Crisis Management", "Cognitive Behavioral Therapy (CBT)", "Record Keeping"],
        salaryRange: "India: ₹3L - ₹8L | Global: $45K - $80K",
        educationPath: "B.A. Psychology → M.A. Counseling / Social Work",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Community Health Centers", "Addiction Rehabs", "NGOs", "Universities"],
        futureScope: "Crucial community role. Essential for addressing the grassroots level of the mental health and addiction crises.",
        jobDemandTrend: "High Demand (but lower relative pay globally)",
        licenseRequired: "Licensed Professional Counselor (LPC) or equivalent state licensing.",
        governmentJobs: "High. Operating within public health departments and state mental health wards.",
        privateSectorOpportunities: "Moderate. Private substance abuse clinics.",
        hospitalClinicOpportunities: "High. Working in outpatient psychiatric and addiction clinics.",
        internshipRequirements: "Clinical practicum (often 600+ hours) during Master's.",
        roadmap: ["Psychology degree", "Master's in Counseling", "Accrue supervised hours", "Licensed Community Counselor"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Research Psychologist",
        description: "Focus entirely on conducting experiments and studies to understand human brain functions, perception, memory, and social behavior, usually publishing in academic journals.",
        summary: "The scientists of psychology, conducting lab experiments to discover new insights about the human brain.",
        skills: ["Experimental Design", "Advanced Statistics (R/Python/SPSS)", "Neuroscience Basics", "Academic Writing", "Grant Writing"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $120K",
        educationPath: "B.Sc. Psychology → M.Sc. → Ph.D. Experimental Psychology",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Universities", "Government Research (NIH)", "Private AI/Tech Labs"],
        futureScope: "Highly relevant. Cognitive researchers are increasingly hired by tech companies to help design AI and Human-Computer Interactions.",
        jobDemandTrend: "Steady",
        licenseRequired: "No clinical license needed as they do not treat patients. Ph.D. required.",
        governmentJobs: "High. Working for national institutes of health or military research branches.",
        privateSectorOpportunities: "High. Tech companies (like Meta/Google) hire them as UX Researchers or Behavioral Scientists.",
        hospitalClinicOpportunities: "Low. Strictly lab-based.",
        internshipRequirements: "Postdoctoral fellowships (1-3 years) are standard.",
        roadmap: ["B.Sc. Psychology", "Ph.D. in a research specialty", "Postdoc researcher", "Tenured Professor / Lead Tech Researcher"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "School Counselor",
        description: "Work within primary and secondary schools to help students address academic challenges, social anxieties, bullying, and home life issues interfering with their education.",
        summary: "The primary mental health and academic advisors located directly within school systems.",
        skills: ["Adolescent Counseling", "Career Guidance", "Mediation", "Bullying Intervention", "Safeguarding Protocols"],
        salaryRange: "India: ₹3L - ₹8L | Global: $50K - $85K",
        educationPath: "B.A. Psychology → M.A. School Counseling",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Public Schools", "Private Schools", "Boarding Academies"],
        futureScope: "Stable and essential. A permanently mandated role in most educational systems worldwide.",
        jobDemandTrend: "Stable",
        licenseRequired: "State educational counseling certification usually required.",
        governmentJobs: "Maximum. The vast majority work in public/state-funded school systems.",
        privateSectorOpportunities: "Moderate. Working at elite private academies or as independent college admissions counselors.",
        hospitalClinicOpportunities: "Low. Exclusively based in educational environments.",
        internshipRequirements: "Practicum completed within a school setting during the degree.",
        roadmap: ["Bachelor's Degree", "Master's in School Counseling", "State Certification", "Head of School Counseling"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Neuropsychologist",
        description: "Study the complex relationship between the physical brain structure and behavior. They assess and treat patients with brain injuries, Alzheimer's, tumors, or severe learning disabilities.",
        summary: "Elite specialists linking physical brain damage/diseases directly to psychological symptoms.",
        skills: ["Cognitive Neuroscience", "Neuroimaging interpretation (MRI/CT)", "Advanced Diagnostics", "Anatomy Knowledge", "Clinical Diagnostics"],
        salaryRange: "India: ₹8L - ₹25L+ | Global: $90K - $160K+",
        educationPath: "B.Sc. Psychology/Neuroscience → Ph.D. Clinical Neuropsychology",
        yearsOfStudy: "9 to 12 Years",
        industriesHiring: ["Neurology Departments in Hospitals", "Research Institutes", "Pharmaceutical Companies", "Private Practice"],
        futureScope: "Massive potential. As the global population ages (increasing dementia) and neuroscience advances, this is a premium specialty.",
        jobDemandTrend: "High Growth, Very Niche",
        licenseRequired: "Clinical License + Board Certification in Neuropsychology.",
        governmentJobs: "Moderate. Specialized military or state research hospitals.",
        privateSectorOpportunities: "High. Lucrative private practice conducting complex cognitive assessments.",
        hospitalClinicOpportunities: "Maximum. You will work closely with neurologists and neurosurgeons.",
        internshipRequirements: "2-year specialized postdoctoral fellowship in neuropsychology.",
        roadmap: ["Neuroscience/Psychology Degree", "Ph.D. in Clinical Psych", "2-Year Postdoc", "Board Certified Neuropsychologist"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Psychotherapist",
        description: "An umbrella term for professionals trained to treat mental health problems through various 'talk therapies' (Psychoanalysis, Gestalt, CBT) rather than medical means.",
        summary: "Trained professionals using deep 'talk therapy' techniques over long periods to heal psychological distress.",
        skills: ["Deep Talk Therapy", "Psychoanalysis", "Active Empathy", "Boundary Setting", "Unconditional Positive Regard"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $120K",
        educationPath: "B.A. → M.A. Psychology / Social Work → Specialized Modality Training",
        yearsOfStudy: "6 to 8 Years",
        industriesHiring: ["Private Practice", "Psychiatric Clinics", "Therapy Retreat Centers"],
        futureScope: "Consistent demand. While quick CBT is popular, there is a returning appreciation for long-term, deep psychodynamic therapy.",
        jobDemandTrend: "Stable",
        licenseRequired: "Requires a counseling or clinical license depending on state jurisdiction.",
        governmentJobs: "Low to Moderate.",
        privateSectorOpportunities: "Maximum. The classic private 'therapy couch' business model.",
        hospitalClinicOpportunities: "Moderate. Often work in associations or groups of private clinics.",
        internshipRequirements: "Usually involves undergoing years of personal therapy alongside clinical supervision.",
        roadmap: ["Psychology Degree", "Master's & License", "Extensive training in a specific therapy modality", "Private Psychotherapist"]
    },
    {
        domain: "Arts",
        branch: "Psychology",
        title: "Human Behavior Analyst",
        description: "Analyze behavioral patterns for non-clinical applications. They may profile criminal behavior for law enforcement or analyze consumer purchasing patterns for rapid marketing adjustments.",
        summary: "Specialists applying psychological behavior models to criminal profiling or corporate consumer analysis.",
        skills: ["Pattern Recognition", "Behavioral Economics", "Statistical Analytics", "Profiling", "Market Research"],
        salaryRange: "India: ₹6L - ₹18L | Global: $70K - $130K",
        educationPath: "B.A. Psychology → M.A. Behavioral Economics / Forensic Psych",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Law Enforcement (FBI/CBI)", "Tech Giants (UX Research)", "Marketing Agencies"],
        futureScope: "Exploding in the corporate sector. Tech companies use behavioral analysts to design habit-forming apps and efficient consumer pipelines.",
        jobDemandTrend: "High Growth",
        licenseRequired: "None.",
        governmentJobs: "Moderate. Niche roles in intelligence and criminal profiling.",
        privateSectorOpportunities: "Maximum. Extremely high demand in product design and high-end marketing.",
        hospitalClinicOpportunities: "Low. Completely non-clinical.",
        internshipRequirements: "Marketing analytics or law enforcement internships.",
        roadmap: ["Psychology degree", "Master's in Behavioral Science", "Junior Analyst", "Director of Behavioral Insights"]
    }
];

const seedPsychology = async () => {
    try {
        await Career.deleteMany({ branch: "Psychology" });
        await Career.insertMany(psychologyProfessions);
        console.log('Psychology Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedPsychology();
