const mongoose = require('mongoose');
const dotenv = require('dotenv');
const colors = require('colors');
const Career = require('./models/Career');

dotenv.config({ path: __dirname + '/.env' });

mongoose.connect(process.env.MONGO_URI);

const linguisticsProfessions = [
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Arts Linguist",
        description: "Study the structure, evolution, and usage of language. They analyze sounds (phonetics), word structures (morphology), and societal language shifts (sociolinguistics) to understand human communication.",
        summary: "Scientists of language, studying how language evolves, how it's structured, and how it impacts society.",
        skills: ["Phonetics & Phonology", "Syntax Analysis", "Sociolinguistics", "Data Analysis", "Research Methodology"],
        salaryRange: "India: ₹4L - ₹15L | Global: $55K - $100K",
        educationPath: "B.A. Linguistics/English → M.A. Linguistics → Ph.D.",
        yearsOfStudy: "5 to 8 Years",
        industriesHiring: ["Universities", "Government Intelligence", "Tech Companies (NLP)", "Publishing"],
        futureScope: "Extremely high in the tech sector. Linguists are essential for training AI and large language models (LLMs).",
        jobDemandTrend: "High Growth",
        certifications: ["None required, though Ph.D. is standard for research/academia."],
        governmentJobs: "High. Employed by intelligence agencies (RAW, CIA) for threat analysis and language decryption.",
        internationalJobOpportunities: "High. Linguistic research often spans multiple countries and cultures.",
        freelanceOpportunities: "Moderate. Usually independent consulting on dialect or language preservation projects.",
        remoteWorkPossibilities: "High. Data analysis and research can easily be done remotely.",
        roadmap: ["Linguistics Degree", "Master's & Ph.D.", "Research Fellow", "Tenured Professor / NLP Consultant"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Arts Translator",
        description: "Convert written text from one language to another while preserving the original meaning, tone, and cultural context. They work on books, legal documents, websites, and manuals.",
        summary: "Experts who accurately convert written texts from a source language to a target language.",
        skills: ["Bilingual/Multilingual Fluency", "Cultural Nuance Understanding", "Excellent Writing Skills", "Subject Matter Expertise", "CAT Tools (Trados, MemoQ)"],
        salaryRange: "India: ₹3L - ₹12L | Global: $45K - $85K",
        educationPath: "B.A. in Foreign Language / Linguistics → M.A. Translation Studies",
        yearsOfStudy: "3 to 5 Years",
        industriesHiring: ["Publishing Houses", "Localization Agencies", "Corporate Multinationals", "Government Embassies"],
        futureScope: "Stable but evolving. While AI translation exists, human translators are still required for nuanced literature, legal texts, and marketing copy.",
        jobDemandTrend: "Steady",
        certifications: ["ATA Certification", "UN Translators Roster"],
        governmentJobs: "Moderate. Official document translation for ministries.",
        internationalJobOpportunities: "Maximum. The entire nature of the job is crossing international borders.",
        freelanceOpportunities: "Maximum. The majority of translators operate as independent freelancers.",
        remoteWorkPossibilities: "Maximum. Easily a 100% remote career.",
        roadmap: ["Language Degree", "Junior Translator", "Specialized Translator (Legal/Medical)", "Translation Agency Owner"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Interpreter",
        description: "Translate spoken language verbally in real-time. They work in high-pressure environments like diplomatic meetings, international conferences, hospitals, and courtrooms.",
        summary: "Real-time verbal translators facilitating communication bridging language barriers in live settings.",
        skills: ["Simultaneous Interpretation", "Active Listening", "Memory Retention", "Quick Thinking", "Subject Specific Vocabulary"],
        salaryRange: "India: ₹6L - ₹20L | Global: $60K - $120K+",
        educationPath: "B.A. Foreign Language → M.A. Interpretation",
        yearsOfStudy: "5 Years",
        industriesHiring: ["United Nations / EU", "International Corporations", "Courts", "Hospitals"],
        futureScope: "High demand. AI struggles with real-time, culturally nuanced, secure, verbal interpretation in high-stakes diplomatic or legal settings.",
        jobDemandTrend: "High Growth",
        certifications: ["AIIC Membership", "Court Interpreter Certification"],
        governmentJobs: "High. Working for the Ministry of External Affairs or international embassies.",
        internationalJobOpportunities: "Maximum. Requires frequent international travel to global summits and corporate meetings.",
        freelanceOpportunities: "High. Many operate on a daily contract basis for conferences.",
        remoteWorkPossibilities: "Increasing. 'Remote Simultaneous Interpretation' (RSI) became popular post-COVID via Zoom/Teams.",
        roadmap: ["Language Fluency", "Interpretation Master's", "Conference Interpreter", "Chief Diplomatic Interpreter"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Language Professor / Lecturer",
        description: "Teach languages, literature, and linguistic theories at the university level. They conduct academic research, publish papers, and participate in academic symposiums.",
        summary: "Academic experts teaching languages and conducting literary or linguistic research at universities.",
        skills: ["Advanced Pedagogy", "Academic Writing", "Curriculum Development", "Mentorship", "Public Speaking"],
        salaryRange: "India: ₹6L - ₹18L | Global: $60K - $110K",
        educationPath: "B.A. Literature/Language → M.A. → M.Phil / Ph.D.",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Universities", "Language Academies (Alliance Française, Goethe-Institut)"],
        futureScope: "Stable. Academia remains a reliable, prestige-driven path, especially for widely spoken global languages or preserving endangered ones.",
        jobDemandTrend: "Steady",
        certifications: ["UGC NET (India)", "TEFL/TESOL (for English)"],
        governmentJobs: "High. State and central universities.",
        internationalJobOpportunities: "Moderate. Guest lecturing or visiting professorships abroad.",
        freelanceOpportunities: "Moderate. Private tutoring or consulting.",
        remoteWorkPossibilities: "Moderate. Online universities and remote lectures are increasingly common.",
        roadmap: ["Ph.D. Candidate", "Assistant Professor", "Associate Professor", "Tenured Head of Department"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Foreign Language Specialist",
        description: "Corporate experts fluent in foreign languages who assist multinational companies in entering new markets. They handle foreign client communications, market research, and cultural consulting.",
        summary: "Corporate diplomats helping businesses navigate foreign cultures and languages.",
        skills: ["Business Level Fluency", "Cultural Etiquette", "Market Research", "Negotiation", "Corporate Strategy"],
        salaryRange: "India: ₹5L - ₹16L | Global: $60K - $100K",
        educationPath: "B.A. Foreign Language + MBA / BBA",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Multinational IT Firms (TCS, Infosys)", "Export/Import Businesses", "Foreign Embassies"],
        futureScope: "High. As global supply chains and digital markets expand, companies need bilingual professionals to secure international deals.",
        jobDemandTrend: "Growing",
        certifications: ["JLPT N1/N2 (Japanese)", "DELF/DALF (French)", "DELE C1/C2 (Spanish)", "Goethe-Zertifikat C1/C2 (German)"],
        governmentJobs: "Moderate. Export advisory boards.",
        internationalJobOpportunities: "Maximum. The ideal candidate to be sent to a foreign branch as an expat manager.",
        freelanceOpportunities: "Moderate. Freelance cultural consulting.",
        remoteWorkPossibilities: "High.",
        roadmap: ["Language Degree + Biz Cert", "Bilingual Executive", "Foreign Market Strategist", "Director of International Operations"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Speech Therapist",
        description: "Diagnose and treat communication disorders, speech impediments, and swallowing difficulties in children and adults (often stroke or accident victims).",
        summary: "Clinical professionals who help patients overcome vocal, speech, and swallowing disorders.",
        skills: ["Clinical Assessment", "Patience", "Anatomy of Speech", "Rehabilitation Techniques", "Pediatric Care"],
        salaryRange: "India: ₹4L - ₹12L | Global: $70K - $115K",
        educationPath: "B.Sc. Audiology and Speech-Language Pathology (BASLP) → M.Sc.",
        yearsOfStudy: "4 to 6 Years",
        industriesHiring: ["Hospitals", "Rehabilitation Centers", "Special Needs Schools", "Private Clinics"],
        futureScope: "Excellent. High demand in both pediatric care (autism, stuttering) and geriatric care (stroke recovery).",
        jobDemandTrend: "High Growth",
        certifications: ["RCI Registration (India)", "ASHA Certification (US)"],
        governmentJobs: "High. Public health hospitals and state-run disability programs.",
        internationalJobOpportunities: "Moderate. Medical licenses may not easily transfer borders.",
        freelanceOpportunities: "High. Running a lucrative private speech pathology clinic.",
        remoteWorkPossibilities: "Growing. Tele-therapy for speech pathology became widely accepted post-2020.",
        roadmap: ["BASLP Degree", "Clinical Intern", "Licensed Speech Therapist", "Clinic Director"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Computational Linguist",
        description: "Combine computer science, AI, and linguistics to teach machines how to understand and generate human language. They build voice assistants, translation apps, and LLMs like ChatGPT.",
        summary: "The engineers bridging human language and artificial intelligence.",
        skills: ["Python/C++ Programming", "Natural Language Processing (NLP)", "Machine Learning", "Syntax & Semantics", "Data Modeling"],
        salaryRange: "India: ₹10L - ₹30L+ | Global: $100K - $200K+",
        educationPath: "B.A. Linguistics + B.Tech CS / M.A. Computational Linguistics",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Big Tech (Google, Apple, OpenAI)", "AI Startups", "Defense & Intelligence"],
        futureScope: "Astronomical. This is currently one of the most sought-after and highest-paying intersectional careers in the world.",
        jobDemandTrend: "Explosive Growth",
        certifications: ["AWS/GCP Machine Learning Certifications (Optional)"],
        governmentJobs: "Moderate. Signal intelligence and automated threat analysis.",
        internationalJobOpportunities: "Maximum. Global tech hubs aggressively recruit top talent.",
        freelanceOpportunities: "High. Consulting for AI startups implementing NLP.",
        remoteWorkPossibilities: "Maximum. Highly remote-friendly tech role.",
        roadmap: ["Linguistics + Coding", "Junior NLP Engineer", "Senior Computational Linguist", "Lead AI Researcher"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Content Localization Specialist",
        description: "Adapt software, video games, websites, and marketing campaigns for foreign markets. It goes beyond translation to ensure cultural relevance, adapting humor, UI layout, and local sensitivities.",
        summary: "Cultural experts who adapt digital products so they feel native to a foreign audience.",
        skills: ["UX/UI Principles", "Cultural Competency", "Transcreation", "Project Management", "Bilingual Fluency"],
        salaryRange: "India: ₹5L - ₹15L | Global: $60K - $110K",
        educationPath: "B.A. Foreign Language / Media → Certification in Localization",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Video Game Studios", "Streaming Services (Netflix/Amazon)", "Tech Software Companies"],
        futureScope: "High Growth. Global digital products must be perfectly localized to succeed in foreign consumer markets.",
        jobDemandTrend: "Fast Growing",
        certifications: ["Localization Project Management Certification (LPM)"],
        governmentJobs: "Low.",
        internationalJobOpportunities: "Maximum. Often hired directly by the headquarters of the digital product.",
        freelanceOpportunities: "Maximum. Very common to work as a freelance localization consultant.",
        remoteWorkPossibilities: "Maximum. Digital adaptation requires zero on-site presence.",
        roadmap: ["Language Degree", "Localization Tester", "Localization Manager", "Director of Global Expansion"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Lexicographer",
        description: "Write, compile, and edit dictionaries. They track how new words enter the language, monitor changing definitions, and document slang or technological jargon.",
        summary: "The guardians of the dictionary, tracking the evolution of words and formally defining them.",
        skills: ["Etymology", "Semantic Precision", "Extreme Attention to Detail", "Corpus Linguistics", "Research"],
        salaryRange: "India: ₹4L - ₹10L | Global: $50K - $85K",
        educationPath: "B.A. English / Linguistics → M.A. Linguistics / Lexicography",
        yearsOfStudy: "5 Years",
        industriesHiring: ["Academic Publishers (Oxford, Merriam-Webster)", "Tech (Search Engines)"],
        futureScope: "Niche but stable. The role is shifting from physical dictionary creation to maintaining massively complex digital language databases used by search engines.",
        jobDemandTrend: "Stable, Niche",
        certifications: ["None specific."],
        governmentJobs: "Low.",
        internationalJobOpportunities: "Moderate. Working with historic universities (e.g., Oxford).",
        freelanceOpportunities: "High. Freelance editing for academic publications.",
        remoteWorkPossibilities: "Maximum. Entirely research and text-based.",
        roadmap: ["Linguistics Degree", "Junior Editor", "Senior Lexicographer", "Chief Editor of a Dictionary"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Subtitling Specialist",
        description: "Create perfectly timed subtitles for movies, TV shows, and YouTube videos. They must rapidly condense dialogue while maintaining the plot's meaning and natural reading speed.",
        summary: "Media professionals who translate and adapt spoken video dialogue into readable on-screen subtitles.",
        skills: ["Spotting (Timing)", "Concise Translation", "Cultural Adaptation", "Subtitling Software", "High WPM Typing"],
        salaryRange: "India: ₹3L - ₹8L | Global: $45K - $80K",
        educationPath: "B.A. Language/Media → Subtitling Certification",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["Streaming Giants", "Post-Production Studios", "Video Marketing Agencies", "Freelance Networks"],
        futureScope: "High volume. The explosion of global streaming content (K-dramas, Anime, global Netflix originals) has created a massive need for localized subtitles.",
        jobDemandTrend: "Growing",
        certifications: ["Netflix HERMES certification (Historical), general AVT certifications."],
        governmentJobs: "Low. Sometimes translating state media.",
        internationalJobOpportunities: "Maximum. Creating subtitles for foreign media conglomerates.",
        freelanceOpportunities: "Maximum. This is one of the most common freelance side-hustles.",
        remoteWorkPossibilities: "Maximum. Entirely remote via secure media portals.",
        roadmap: ["Language Degree", "Freelance Subtitler", "Quality Assurance Editor", "Localization Agency Owner"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Language Trainer",
        description: "Teach practical language skills rapidly to corporate clients, expatriates, or BPO employees. The focus is strictly on conversational fluency, accent neutralization, and business etiquette rather than literature.",
        summary: "Instructors who rapidly teach business fluency and accent neutralization to corporate professionals.",
        skills: ["Accent Neutralization", "Business Communication", "Adult Pedagogy", "Patience", "Corporate Etiquette"],
        salaryRange: "India: ₹4L - ₹12L | Global: $50K - $90K",
        educationPath: "B.A. English/Foreign Language + Trainer Certification",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["BPO/KPO Sector", "Multinational Corporations", "Aviation/Hospitality", "Immigration Services"],
        futureScope: "Very high in nations like India where the BPO and IT outsourcing sectors heavily rely on flawless Western accent and communication skills.",
        jobDemandTrend: "High Demand",
        certifications: ["Train The Trainer (TTT)", "TEFL/TESOL", "CELTA"],
        governmentJobs: "Low.",
        internationalJobOpportunities: "Moderate. Traveling with expats to train foreign branches.",
        freelanceOpportunities: "Maximum. Corporate consulting on a freelance/contractual basis.",
        remoteWorkPossibilities: "Maximum. Online tutoring platforms (Preply, iTalki) are booming.",
        roadmap: ["Language Degree", "Voice & Accent Trainer", "Corporate Language Consultant", "Head of Global Training"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "ESL (English as Second Language) Teacher",
        description: "Teach English globally to non-native speakers in foreign countries or online. Focus is on grammar, conversation, and reading comprehension for students ranging from children to adults.",
        summary: "Educators traveling the globe or working online to teach English to non-native speakers.",
        skills: ["Creative Lesson Planning", "Grammar Expertise", "Cross-Cultural Communication", "Adaptability", "Patience"],
        salaryRange: "India: ₹3L - ₹8L | Global: $35K - $85K (Tax-free often in Gulf/Asia)",
        educationPath: "Bachelor's Degree (Any) + TEFL/CELTA Certification",
        yearsOfStudy: "3 to 4 Years",
        industriesHiring: ["International Schools", "Private Language Academies (EPIK, JET)", "Online EdTech (VIPKid)"],
        futureScope: "Massive global demand. English remains the dominant language of global business, creating endless opportunities, especially in East Asia and the Middle East.",
        jobDemandTrend: "Very High",
        certifications: ["CELTA (Cambridge)", "TEFL/TESOL"],
        governmentJobs: "Moderate. Working in state-sponsored exchange programs (e.g., JET in Japan).",
        internationalJobOpportunities: "Maximum. This is the ultimate 'digital nomad' or expat career.",
        freelanceOpportunities: "High. Private tutoring.",
        remoteWorkPossibilities: "Maximum. Online English teaching is a massive industry.",
        roadmap: ["Degree + TEFL", "ESL Teacher Abroad", "Senior Curriculum Developer", "Director of Studies (Language School)"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Technical Translator",
        description: "A highly specialized translator focusing exclusively on complex subjects like legal contracts, medical manuals, engineering specs, or patents, where zero margin of error is allowed.",
        summary: "Specialized translators for high-stakes medical, legal, and engineering documents.",
        skills: ["Flawless Grammar", "Extreme Domain Knowledge (e.g., Medical/Legal)", "Terminology Management", "Precision", "Confidentiality"],
        salaryRange: "India: ₹6L - ₹18L | Global: $65K - $120K+",
        educationPath: "B.A. Translation + Degree/Experience in specific technical field",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Pharmaceuticals", "Law Firms", "Engineering/Manufacturing Multinationals", "Patent Offices"],
        futureScope: "Extremely lucrative. While AI can translate basic text, legally binding contracts and medical device manuals legally require certified human translators.",
        jobDemandTrend: "High Growth, Highly Lucrative",
        certifications: ["ATA Certification in specific technical domains.", "ISO Translation Standards."],
        governmentJobs: "Moderate. Translating international treaties or patents.",
        internationalJobOpportunities: "Maximum.",
        freelanceOpportunities: "Maximum. Technical freelancers command the highest per-word rates in the translation industry.",
        remoteWorkPossibilities: "Maximum. Entirely remote.",
        roadmap: ["Translation Degree", "General Translator", "Technical Specialization (e.g., Medical)", "Elite Freelance Consultant"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Diplomatic Language Officer",
        description: "Serve as the official linguistic and cultural liaison for a nation's foreign service. They facilitate delicate diplomatic negotiations, translate official state documents, and brief ambassadors on cultural nuances.",
        summary: "The elite linguistic operatives of a country's foreign diplomatic corps.",
        skills: ["Flawless Bilingualism", "Geopolitical Knowledge", "Extreme Discretion", "Protocol Management", "Crisis Communication"],
        salaryRange: "India: ₹10L - ₹25L+ (Including allowances) | Global: $80K - $150K+",
        educationPath: "B.A. Foreign Affairs/Language → Civil Services Exams → Trainee Program",
        yearsOfStudy: "5 to 6 Years",
        industriesHiring: ["Ministry of External Affairs (MEA)", "Foreign Embassies", "United Nations"],
        futureScope: "Elite prestige. Always necessary to maintain international relations, negotiate treaties, and prevent geopolitical misunderstandings.",
        jobDemandTrend: "Stable, Highly Competitive",
        certifications: ["Civil Services qualification.", "High-level security clearances."],
        governmentJobs: "Maximum. This role is exclusively working for the state.",
        internationalJobOpportunities: "Maximum. Requires living in foreign embassies, rotating assignments globally.",
        freelanceOpportunities: "None. Requires strict loyalty and security clearance to the state.",
        remoteWorkPossibilities: "Low. Requires physical presence in embassies or diplomatic summits.",
        roadmap: ["UPSC / Civil Service Exam", "Junior Diplomat (Language focus)", "Senior Attaché", "Ambassador"]
    },
    {
        domain: "Arts",
        branch: "Languages and Linguistics",
        title: "Language Researcher",
        description: "Study and document endangered, dying, or unwritten languages. They travel to remote areas to record native speakers, create alphabets, and preserve linguistic heritage before it vanishes.",
        summary: "Field scientists racing against time to document and preserve endangered global languages.",
        skills: ["Field Ethnography", "Audio Recording/Archiving", "Phonetic Transcription", "Cultural Empathy", "Grant Writing"],
        salaryRange: "India: ₹4L - ₹10L | Global: $50K - $90K",
        educationPath: "B.A. Linguistics/Anthropology → M.A. → Ph.D. Field Linguistics",
        yearsOfStudy: "8 to 10 Years",
        industriesHiring: ["Universities", "Cultural NGOs (UNESCO)", "National Geographic / Research Institutes"],
        futureScope: "Crucial cultural work. With hundreds of languages expected to die this century, the rush to preserve them is a major priority for global cultural organizations.",
        jobDemandTrend: "Niche",
        certifications: ["None specific, PhD expected."],
        governmentJobs: "Moderate. Anthropological Survey organizations.",
        internationalJobOpportunities: "Maximum. Travelling globally to remote tribes or communities.",
        freelanceOpportunities: "Moderate. Operating via independent research grants.",
        remoteWorkPossibilities: "Low. Requires heavy, on-the-ground fieldwork and direct human interaction.",
        roadmap: ["Linguistics Degree", "Ph.D. Fieldwork", "Grant-funded Researcher", "Director of Linguistic Preservation"]
    }
];

const seedLinguistics = async () => {
    try {
        await Career.deleteMany({ branch: "Languages and Linguistics" });
        await Career.insertMany(linguisticsProfessions);
        console.log('Linguistics Professions Seeded!'.cyan.inverse);
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedLinguistics();
